CodeGen: Move current call site out of MachineModuleInfo
llvm/llvm-project pull request #100369
Opened 2024-07-24 13:10 UTC by arsenm

I do not know understand what this is for, but it's only used in
SelectionDAGBuilder, so move it to FunctionLoweringInfo like other
function scope DAG builder state. The intrinsics are not documented
in the LangRef or Intrinsics.td.

This removes the last piece of codegen state from MachineModuleInfo.

2024-07-24 13:10 UTC, arsenm commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/100369?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#100369** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/100369?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#100368** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/100368?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#100357** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/100357?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#100353** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/100353?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#100333** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/100333?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#100319** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/100319?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @arsenm and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-07-24 17:14 UTC, dpaoliello requested changes

2024-07-24 17:14 UTC, dpaoliello commented on llvm/include/llvm/CodeGen/FunctionLoweringInfo.h
> +  /// \name Exception Handling
I don't think we need to keep this

2024-07-24 17:14 UTC, dpaoliello commented on llvm/include/llvm/CodeGen/FunctionLoweringInfo.h
> +  void setCurrentCallSite(unsigned Site) { CurCallSite = Site; }
Please move these down next to the rest of the functions

2024-07-24 20:32 UTC, dpaoliello approved these changes

2024-07-24 20:48 UTC, rnk approved these changes
lgtm

2024-07-26 07:21 UTC, arsenm commented
### Merge activity

* **Jul 26, 3:21 AM EDT**: @arsenm started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/llvm/llvm-project/100369).

2024-07-26 07:25 UTC, s-barannikov commented on llvm/include/llvm/CodeGen/FunctionLoweringInfo.h
> +  // go into .eh_frame only, while others go into .debug_frame only.
This comment should be somewhere else wherether the "switch" it refers to should be added.
Somewhere near MF.needsFrameMoves, probably?

2024-07-26 07:49 UTC, s-barannikov approved these changes

2024-07-26 09:02 UTC, merged