[flang] Match the type of the element size in the box in creating fir.box_elesize
llvm/llvm-project pull request #100512
Opened 2024-07-25 05:54 UTC by kkwli

Currently, `%17 = fir.box_elesize %16 : (!fir.class<!fir.ptr<!fir.type<_QFTt{a:i32,b:i32}>>>) -> i32`
is translated to
```
  %4 = getelementptr { ptr, i64, i32, i8, i8, i8, i8, ptr, [1 x i64] }, ptr %1, i32 0, i32 1
  %5 = load i32, ptr %4, align 4
```
The type of the element size is `i64`. The load essentially truncates the value and yields incorrect result in the big endian environment. The problem occurs in the `storage_size` intrinsic on a polymorphic variable.

2024-07-25 07:19 UTC, jeanPerier requested changes
Thanks for finding this bug.

I would rather the bug to be fixed where it is in codegen.cpp: the GEP + load should use the descriptor type and a cast should be inserted. That way, there is no need to assume the type inside the descriptor in lowering, and future creation of fir.box_elesize will be safe.

2024-07-25 17:18 UTC, kkwli commented
@jeanPerier Thanks for the review. I update the patch. Instead of fixing it in `genStorageSize`, the change is in `getValueBox` that insert a cast after the load.

2024-08-01 18:06 UTC, kkwli commented
Ping

2024-08-01 18:09 UTC, clementval approved these changes
LGTM

2024-08-06 22:23 UTC, merged