[libc++] Fix -Wsign-compare warning in `ranges::search`
llvm/llvm-project pull request #100983
Opened 2024-07-29 08:23 UTC by hewillk

The type returned by `ranges::size` is not guaranteed to be unsigned, so using `ranges::distance` here ensures that it always returns a signed type.

2024-07-29 09:12 UTC, philnik777 requested changes
What exactly is the problem here you're trying to solve? AFAICT `ranges::size` is guaranteed to be correct here.

2024-07-29 11:32 UTC, hewillk commented
> What exactly is the problem here you're trying to solve? AFAICT `ranges::size` is guaranteed to be correct here.

As the title describes: "Fix -Wsign-compare warning in ranges::search":
https://godbolt.org/z/de8Gv9dWx

2024-07-29 11:41 UTC, philnik777 commented
> > What exactly is the problem here you're trying to solve? AFAICT `ranges::size` is guaranteed to be correct here.
> 
> As the title describes: "Fix -Wsign-compare warning in ranges::search": https://godbolt.org/z/de8Gv9dWx

But why is that a problem? You can fix your container if you care about `-Wsign-compare`, or don't compile with warnings enabled in system headers.

2024-08-29 14:30 UTC, ldionne commented
Gentle ping. I tend to agree that getting a warning is fine here if you pass ranges with signed/unsigned size types to this algorithm, but can be convinced otherwise. I'll close this next week unless there's new information.

2024-09-05 13:04 UTC, closed without merging