[analyzer] Assert Callee is FunctionDecl in doesFnIntendToHandleOwner…
llvm/llvm-project pull request #101066
Opened 2024-07-29 18:59 UTC by smanna12

…ship()

This patch replaces dyn_cast<> with cast<> for converting Callee to FunctionDecl, asserting non-null assumption to prevent undefined behavior due to null dereferences and enforces the invariant that Callee must be a valid FunctionDecl.

2024-07-30 06:46 UTC, steakhal commented
If this function only cares about FunctionDecls, why does it accept a generic Decl? I'd prefer a clear interface instead.

BTW, what does prevent a BlockDecl from taking ownership?

2024-07-30 09:46 UTC, Szelethus requested changes
Already under fix in #100719, I'm just a lazy bum and haven't fixed the buildbots. I'll try to speed things up!

2024-07-30 14:30 UTC, closed without merging

2024-07-30 14:35 UTC, smanna12 commented
> Already under fix in #100719, I'm just a lazy bum and haven't fixed the buildbots. I'll try to speed things up!

Thanks for reviews. Closing this JIRA

2024-08-01 19:26 UTC, smanna12 commented
> > > Already under fix in #100719, I'm just a lazy bum and haven't fixed the buildbots. I'll try to speed things up!
> > 
> > 
> > @Szelethus, would it possible to speed up the PR#100719? Thanks
> 
> Why?

It impacts our scan with static analyzer tool.

2024-08-01 19:41 UTC, steakhal commented
> > > > Already under fix in #100719, I'm just a lazy bum and haven't fixed the buildbots. I'll try to speed things up!
> > > 
> > > 
> > > @Szelethus, would it possible to speed up the PR#100719? Thanks
> > 
> > Why?
> 
> It impacts our scan with static analyzer tool.

I see. In that case I think it makes sense to mark that report in your tool as a true-positive, and it will be eventually fixed. Probably pretty soon, but I don't want to speak for Husi, as he might be on vacation. If it's urgent, a downstream patch should be always an option, but I don't think this issue would justify one - at least it wouldn't for me.

2024-08-05 11:33 UTC, Szelethus commented
Just landed the patch, sorry for the slack!