[clang][Tests][NFC] Add CWG882 test (Defining `main` as deleted)
llvm/llvm-project pull request #101382
Opened 2024-07-31 18:22 UTC by MitalAshok

https://cplusplus.github.io/CWG/issues/882.html

This was implemented for Clang 3.5 by b63b6ee9a00ef0710d899df6cfda78a1b8bd762a

2024-07-31 19:14 UTC, Endilll requested changes

2024-07-31 19:14 UTC, Endilll commented on clang/test/CXX/drs/cwg8xx.cpp
> +// cxx98-error@-2 {{deleted function definitions are a C++11 extension}}
`delete` came in C++11, so you should guard the test with `#ifdef __cplusplus`

2024-07-31 20:14 UTC, Endilll approved these changes

2024-07-31 20:14 UTC, Endilll commented
Do you want this to be merged once CI passes?

2024-08-01 08:54 UTC, MitalAshok commented
@Endilll Yes, thanks!

2024-08-01 09:59 UTC, merged