[clang-tidy] Add support for bsl::optional
llvm/llvm-project pull request #101450
Opened 2024-08-01 03:51 UTC by ccotter

2024-08-01 16:52 UTC, PiotrZSL approved these changes
I'm fine with change, but at the same time this check should be made configurable.
Also please update check documentation before committing.

2024-08-01 18:12 UTC, ccotter commented
Agreed it should be configurable.

I updated the docs, would you mind merging if you are OK as I don't have perms?

2024-08-02 18:16 UTC, ymand requested changes

2024-08-10 04:55 UTC, ccotter commented on clang/lib/Analysis/FlowSensitive/Models/UncheckedOptionalAccessModel.cpp
> +static bool hasNestedNamespace(const NamespaceDecl &NS, llvm::StringRef Name,
Good point, thanks! Updated.

2024-08-19 02:41 UTC, ccotter commented
bump @ymand @PiotrZSL?

2024-08-26 01:59 UTC, dayshah approved these changes
huge for bloomberg 🔥

2024-09-25 00:32 UTC, nicovank approved these changes
LGTM. Rebase to fix release notes conflict and I'll merge 👍

2024-09-25 14:54 UTC, merged