[BOLT] Support map other function entry address
llvm/llvm-project pull request #101466
Opened 2024-08-01 10:01 UTC by linsinan1995

Allow BOLT to map the old address to a new binary address if the old address is the entry of the function.

2024-08-01 10:15 UTC, linsinan1995 commented
take the assembly code attached in the test as an example
```
    .text
    .type   chain, @function
chain:
    movq    $1, %rax
Lable:
    ret
    .size   chain, .-chain
    .type   _start, @function
    .global _start
_start:
    jmpq    *.Lfoo(%rip)
    ret
    .size   _start, .-_start
  .data
.Lfoo:
  .quad Lable
```

(1) if -no-pie, there is not a dynamic relocation for `Label`, then everything is fine.
```
gcc test.s -nostdlib -nodefaultlibs -Wl,-q
llvm-bolt a.out -o a.opt
```

(2) if it is pie, then an error occurs
```
gcc test.s -nostdlib -nodefaultlibs -Wl,-q -fPIC -fPIE -pie
llvm-bolt a.out -o a.opt
```

BOLT-ERROR: unable to get new address corresponding to input address 0x1007 in function chain/1(*2). Consider adding this function to --skip-funcs=...

This change can make the case (2) work

2024-08-01 17:30 UTC, yota9 commented on bolt/test/X86/dynamic-relocs-on-entry.s
> +    .size   chain, .-chain
New line here please

2024-08-01 17:30 UTC, yota9 commented on bolt/test/X86/dynamic-relocs-on-entry.s
> +// This test examines whether BOLT can correctly update when
In order to check that BOLT can correctly ~update~  process the binary please add extra check that relocation new symbol address is correct in output binary

2024-08-02 12:38 UTC, yota9 approved these changes
LGTM thanks!
JFYI next time you can use objdump with -R in order to skip extra file creation for readelf+objdump. It's a minor thing so I don't really mind anyway.

2024-08-02 13:01 UTC, linsinan1995 commented on bolt/test/X86/dynamic-relocs-on-entry.s
> +    .size   chain, .-chain
updated, Thanks!

2024-08-02 14:31 UTC, ayermolo commented
Looks like an X86 test is failing.

2024-08-02 15:14 UTC, yota9 requested changes

2024-08-02 15:14 UTC, yota9 commented on bolt/test/X86/dynamic-relocs-on-entry.s
> +# CHECK: [[#ADDR]]: c3 retq
I think you need either remove # here or (probably even better) make var setting above like  [[#%x,ADDR:]]

2024-08-02 17:52 UTC, yota9 approved these changes
Test passed, thanks

2024-08-05 14:47 UTC, linsinan1995 commented
Thanks for reviewing && suggestions @ayermolo @yota9 

I will merge the code by Wednesday if there are no new comments.

2024-08-05 14:52 UTC, yota9 commented
Also could you please push this one and #69136 to 19.x branch? Thanks!

2024-08-07 07:57 UTC, merged

2024-08-07 07:57 UTC, linsinan1995 commented
/cherry-pick 734c048