[mlir][emitc] fix emitc dialect's operations' summary
llvm/llvm-project pull request #101515
Opened 2024-08-01 16:42 UTC by EtoAndruwa

Due to the [ODS](https://mlir.llvm.org/docs/DefiningDialects/Operations/#operation-arguments) the summary of the operation in the TableGen must start with the capital letter.

From the text: `The summary should be short and concise. It should be a one-liner starting with a capital letter and without trailing punctuation. Put expanded explanation in the description.`

2024-08-01 17:20 UTC, marbre requested changes
Thanks for your patch! Just one suggestion.

Furthermore, you may want to start the PR description with a capital letter and make it`Fix EmitC`

2024-08-01 17:20 UTC, marbre commented on mlir/include/mlir/Dialect/EmitC/IR/EmitC.td
> +  let summary = "An if-then-else operation";
```suggestion
  let summary = "If-then-else operation";
```

2024-08-01 20:18 UTC, marbre approved these changes
Thanks!

2024-08-02 09:50 UTC, EtoAndruwa commented
> Thanks!

Hello! Thank you for reviewing this patch. Due to [the same PR for ControlFlow dialect](https://github.com/llvm/llvm-project/pull/101494) should I close the PR or you will merge it?

2024-08-02 12:09 UTC, merged