[libcxx] Do not redeclare `lgamma_r` when targeting the LLVM C library
llvm/llvm-project pull request #102036
Opened 2024-08-05 18:43 UTC by jhuber6

Summary:
We use `lgamma_r` for the random normal distrubtion support. In this
code we redeclare it, which caused issues with the LLVM C library as
this function has the `noexcept` flag. Also make sure we include
`features.h` when using the GPU so it gets this as well.

2024-08-14 16:11 UTC, ldionne requested changes

2024-08-14 16:11 UTC, ldionne commented on libcxx/include/__configuration/platform.h
> +#elif defined(__AMDGPU__) || defined(__NVPTX__)
This makes me wonder if we should instead do this:

```
// <features.h> defines macros that allows detecting the libc we're using
#if __has_include(<features.h>)
#  include <features.h>
#endif
#if defined(__GLIBC_PREREQ)
  // etc...
#endif
```

Can you try that out and see if that breaks anything in the CI?

2024-08-21 19:06 UTC, jhuber6 commented
ping

2024-08-27 15:42 UTC, jhuber6 commented
ping

2024-08-27 21:44 UTC, ldionne approved these changes

2024-08-27 21:46 UTC, merged

2025-01-15 21:39 UTC, ldionne commented on libcxx/include/__configuration/platform.h
> +#if __has_include(<features.h>)
When pre-qualifying LLVM 20, we just found out that this breaks some code. Indeed, folks are free to have a header named `<features.h>` available on their include paths, and in fact it seems not uncommon to have that. So the `__has_include(<features.h>)` is going to lie, and the `#include <features.h>` is going to pick up the wrong one anyway.

We'd need to find another header we can include to provide this version macro. Since C lacks a standardized header to provide version stuff (what a shame), we often rely on using some minimal header like `<iso646.h>` to get implementation-specific values. That should work for glibc, and llvm-libc could be changed to provide a `<iso646.h>` header. Also, all of llvm-libc's headers should define the feature macros like `__LLVM_LIBC__`, which I think is not the case right now.

CCing @var-const @jhuber6 @michaelrj-google

2025-09-02 21:31 UTC, yuxuanchen1997 commented
Actually, there's also noexcept on math functions used in glibc:
https://github.com/bminor/glibc/blob/54bd776f991f1a228a6bb6d76bf542edd915a0e3/math/bits/mathcalls-macros.h#L29-L48
https://github.com/bminor/glibc/blob/54bd776f991f1a228a6bb6d76bf542edd915a0e3/misc/sys/cdefs.h#L86

The reason we don't notice this today is because clang and gcc both ignore this difference when one declaration is marked as a system header: https://godbolt.org/z/cGvj555qP

This is not ignored under nvcc or edg though. Hence the trouble with redeclaration didn't stop here.