[libc] Enable more entrypoints for riscv
llvm/llvm-project pull request #102055
Opened 2024-08-05 20:31 UTC by mikhailramalho

This patch enables more entrypoints for riscv. The changes to the test cases are introduced to support rv32 which has long double but doesn't have int128

2024-08-05 20:46 UTC, lntue approved these changes

2024-08-05 23:39 UTC, overmighty requested changes
`default_snan_payload` and `default_snan_payload_bits` are incorrect/misleading variable names in this context.

2024-08-06 14:37 UTC, overmighty commented on libc/test/src/math/smoke/SetPayloadTest.h
> +    // from BigInt to long double.
Nit: in this case it's `float128`. The `long double` variant of `setpayload` isn't enabled yet.

```suggestion
    // Essentially this:
    //   T nan_payload = T(FPBits::FRACTION_MASK >> 1);
    // but won't try to cast from BigInt to a floating-point type on RISC-V,
    // which supports float128 but not 128-bit ints.
```

2024-08-06 14:57 UTC, overmighty approved these changes

2024-08-06 14:57 UTC, overmighty commented on libc/test/src/math/smoke/SetPayloadTest.h
> +    // The following code is creating a NaN manually to prevent a conversion
Nit: it's creating the payload which will be stored in the NaN mantissa. It's not creating the NaN itself.

2024-08-06 15:05 UTC, overmighty approved these changes

2024-08-06 15:16 UTC, merged