scalbln
llvm/llvm-project pull request #102219
Opened 2024-08-06 20:44 UTC by aaryanshukla

- **1/5**
- **added to config**
- **[libc][c23][math] scalbln**

2024-08-06 21:21 UTC, lntue commented on libc/newhdrgen/yaml/math.yaml
> +  - name: floorf128
should this be in a separate PR?

2024-08-06 21:22 UTC, overmighty requested changes
I would drop C23 from the PR title, as the `scalbln` function family is from C99. See https://en.cppreference.com/w/c/numeric/math/scalbn. Only `scalblnf128` is a C23 function, so I don't think it would make sense to have C23 in the PR title.

2024-08-06 21:22 UTC, overmighty commented on libc/config/linux/aarch64/entrypoints.txt
>      libc.src.math.scalbnf128
Nit: sorting.

2024-08-06 21:22 UTC, overmighty commented on libc/newhdrgen/yaml/math.yaml
> +    guard: LIBC_TYPES_HAS_FLOAT128scalbln
This line should be reverted.

2024-08-06 21:22 UTC, overmighty commented on libc/newhdrgen/yaml/math.yaml
> +      - llvm_libc_ext
All the `scalbln*` functions are standard C functions. They're not LLVM libc extensions.

You can use https://www.open-std.org/jtc1/sc22/wg14/www/docs/n3096.pdf if you need access to a draft of the C23 standard. You can also look up pre-C23 functions on cppreference.com.

2024-08-06 21:22 UTC, overmighty commented on libc/spec/llvm_libc_ext.td
> +
Should be moved to libc/spec/stdc.td.

2024-08-06 21:22 UTC, overmighty commented on libc/spec/stdc.td
> +
Nit: you added trailing spaces in this line.

2024-08-06 21:22 UTC, overmighty commented on libc/src/math/generic/CMakeLists.txt
> +  scalblnl
Nit: sorting. `scalblnf` should appear before `scalblnl`.

2024-08-06 21:22 UTC, overmighty commented on libc/src/math/generic/CMakeLists.txt
> +    libc.src.__support.FPUtil.manipulation_functions
```suggestion
  DEPENDS
    libc.hdr.float_macros
    libc.src.__support.FPUtil.manipulation_functions
```

2024-08-06 21:22 UTC, overmighty commented on libc/src/math/generic/scalblnf.cpp
> +#include "src/__support/macros/properties/types.h"
```suggestion
```

2024-08-06 21:22 UTC, overmighty commented on libc/src/math/generic/scalblnf.cpp
> +namespace LIBC_NAMESPACE_DECL {
Nit: whitespace.

```suggestion
#endif

namespace LIBC_NAMESPACE_DECL {
```

2024-08-06 21:22 UTC, overmighty commented on libc/src/math/scalblnl.h
> +#include "src/__support/macros/properties/types.h"
```suggestion
```

2024-08-06 21:22 UTC, overmighty commented on libc/test/src/math/smoke/CMakeLists.txt
> +)
The `scalbn*` tests' dependencies should be updated to match the includes of LdExpTest.h, which is itself included by ScalbnTest.h. The `ldexp*` tests' dependencies are correct.

2024-08-06 21:24 UTC, lntue commented on libc/newhdrgen/yaml/math.yaml
> +      - llvm_libc_ext
`scalblnf128` should be in the stdc standards, not an LLVM extension.

2024-08-06 21:25 UTC, lntue commented on libc/spec/llvm_libc_ext.td
> +          GuardedFunctionSpec<"scalblnf128", RetValSpec<Float128Type>, [ArgSpec<Float128Type>, ArgSpec<LongType>], "LIBC_TYPES_HAS_FLOAT128">,
move this to `stdc.td`

2024-08-07 22:21 UTC, overmighty requested changes

2024-08-07 22:21 UTC, overmighty commented on libc/newhdrgen/yaml/math.yaml
> +    guard: LIBC_TYPES_HAS_FLOAT12
Regression.

2024-08-07 22:21 UTC, overmighty commented on libc/spec/stdc.td
> +          FunctionSpec<"scalblnf", RetValSpec<FloatType>, [ArgSpec<FloatType>, ArgSpec<LongType>]>,
Nit: sorting.

```suggestion
          FunctionSpec<"scalblnf", RetValSpec<FloatType>, [ArgSpec<FloatType>, ArgSpec<LongType>]>,
          FunctionSpec<"scalblnl", RetValSpec<LongDoubleType>, [ArgSpec<LongDoubleType>, ArgSpec<LongType>]>,
```

2024-08-07 22:21 UTC, overmighty commented on libc/src/math/CMakeLists.txt
> +add_math_entrypoint_object(scalblnf)
Nit: sorting.

```suggestion
add_math_entrypoint_object(scalblnf)
add_math_entrypoint_object(scalblnl)
```

2024-08-07 22:21 UTC, overmighty commented on libc/src/math/generic/CMakeLists.txt
> +    libc.src.__support.FPUtil.manipulation_functions
This wasn't resolved, you just swapped `scalblnl` and `scalblnf`.

2024-08-07 22:21 UTC, overmighty commented on libc/test/src/math/smoke/CMakeLists.txt
> +
Nit: extra blank line.

2024-08-07 22:21 UTC, overmighty commented on libc/test/src/math/smoke/CMakeLists.txt
> +)
Nit: sorting. Same for the other changes below.

Here's a shell function I use to check sorting sometimes:

```sh
foo() { cat > /tmp/foo.txt; diff -u /tmp/foo.txt <(sort /tmp/foo.txt) }
```

Run `foo` (feel free to rename it), paste the dependencies or entrypoints or whatever, hit Enter, then hit Ctrl+D, and you'll get something like this:

```sh
~ ➜ foo() { cat > /tmp/foo.txt; diff -u /tmp/foo.txt <(sort /tmp/foo.txt) }
~ ➜ foo
    libc.src.math.scalbln
    libc.src.__support.FPUtil.fp_bits
    libc.src.__support.CPP.limits
    libc.src.__support.FPUtil.normal_float
--- /tmp/foo.txt	2024-08-08 00:19:32.174274463 +0200
+++ /proc/self/fd/11	2024-08-08 00:19:35.004294971 +0200
@@ -1,4 +1,4 @@
     libc.src.math.scalbln
-    libc.src.__support.FPUtil.fp_bits
     libc.src.__support.CPP.limits
+    libc.src.__support.FPUtil.fp_bits
     libc.src.__support.FPUtil.normal_float
~ ➜
```

2024-08-08 17:04 UTC, overmighty requested changes

2024-08-08 17:04 UTC, overmighty commented on libc/newhdrgen/yaml/math.yaml
> +    guard: LIBC_HAS_TYPES_FLOAT16
```suggestion
    guard: LIBC_TYPES_HAS_FLOAT16
```

2024-08-08 17:04 UTC, overmighty commented on libc/newhdrgen/yaml/math.yaml
> +    guard: LIBC_HAS_TYPES_FLOAT128
```suggestion
    guard: LIBC_TYPES_HAS_FLOAT128
```

2024-08-08 17:18 UTC, overmighty approved these changes
LGTM with one more nit.

2024-08-08 17:18 UTC, overmighty commented on libc/test/src/math/smoke/CMakeLists.txt
> +)
Nit: sorting.

```suggestion
  DEPENDS
    libc.src.math.scalblnf
    libc.src.__support.CPP.limits
    libc.src.__support.FPUtil.fp_bits
    libc.src.__support.FPUtil.normal_float
)
```

2024-08-08 20:00 UTC, lntue approved these changes

2024-08-08 21:33 UTC, merged