[libc][docs] Update docs to reflect new headergen
llvm/llvm-project pull request #102381
Opened 2024-08-07 21:49 UTC by michaelrj-google

Since new headergen is now the default for building LLVM-libc, the docs
need to be updated to reflect that. While I was editing those docs, I
took a quick pass at updating other out-of-date pages.

2024-08-07 22:25 UTC, jhuber6 reviewed
There should probably be a mention that `pyyaml` needs to be installed.

2024-08-08 16:59 UTC, michaelrj-google commented
I've added a note to the fullbuild pages

2024-08-08 22:39 UTC, aaryanshukla reviewed
clear conflicts

2024-08-15 16:39 UTC, jhuber6 approved these changes

2024-08-15 16:40 UTC, aaryanshukla approved these changes
LGTM

2024-08-15 16:43 UTC, lntue requested changes

2024-08-15 16:46 UTC, jhuber6 commented on libc/docs/full_host_build.rst
> +   $> cmake ../runtimes \
Hm, we might need to refine the  weird hacky logic for `set(NEED_LIBC_HDRGEN FALSE)`

2024-08-15 17:17 UTC, michaelrj-google commented on libc/docs/full_host_build.rst
> +   $> cmake ../runtimes \
That's odd, when I run it on a fresh build folder it works fine. Could you make sure that you didn't have a lingering CMakeCache.txt and try it again?

2024-08-15 17:38 UTC, lntue commented on libc/docs/full_host_build.rst
> +   $> cmake ../runtimes \
I started with a clean build folder, just sync to the current LLVM head.

2024-08-15 17:51 UTC, michaelrj-google commented on libc/docs/full_host_build.rst
> +   $> cmake ../runtimes \
Ah, the error is showing up now that I've sync'd, I have a guess as to what happened.

2024-08-15 23:38 UTC, michaelrj-google commented on libc/docs/full_host_build.rst
> +   $> cmake ../runtimes \
This patch fixes the issue: https://github.com/llvm/llvm-project/pull/104522
The `elf` and `link` headers were not properly set up to use newheadergen.

2024-08-16 17:24 UTC, michaelrj-google commented on libc/docs/full_host_build.rst
> +   $> cmake ../runtimes \
Now that that patch is landed, could you try the build again? It's passing on my end.

2024-08-16 17:36 UTC, lntue commented on libc/docs/full_host_build.rst
> +   $> cmake ../runtimes \
It works for me now.

2024-08-16 17:37 UTC, lntue commented on libc/docs/full_host_build.rst
> +   $> ninja libc check-libc
right now in full build `libm.a` is built separately with `ninja libm`.  You might want to add it here, until we combine their cmake targets for full build similar to overlay mode.

2024-08-20 21:21 UTC, michaelrj-google commented
I've addressed the comments, and the build works on my system. I'm planning to land this patch tomorrow.

2024-08-20 23:20 UTC, lntue approved these changes

2024-08-21 17:50 UTC, merged