[libc++] The rest of P2278R4 (cdata, as_const_view, span changes)
llvm/llvm-project pull request #102301
Opened 2024-08-07 10:44 UTC by strega-nil

This PR depends on, and is committed on top of, [LLVM-PR-99915][].

This PR completes the rest of [P2278R4][] that was not done in the original PR:

- `cdata`
- Changes to `span` (includes some interesting choices since `const_iterator` cannot support `volatile` element types)
- `as_const_view` and `views::as_const`
- The `__cpp_lib_ranges_as_const` feature macro

[LLVM-PR-99915]: https://github.com/llvm/llvm-project/pull/99915

2024-08-07 17:33 UTC, frederick-vs-ja requested changes

2024-08-07 17:33 UTC, frederick-vs-ja commented on libcxx/include/__ranges/as_const_view.h
> +    __ref_view,
[LWG3811](https://cplusplus.github.io/LWG/issue3811) and [LWG3850](https://cplusplus.github.io/LWG/issue3850) are completed here and thus the entries should be updated:
https://github.com/llvm/llvm-project/blob/445023f1739d3764f1dae6e6b7b0602328198a1e/libcxx/docs/Status/Cxx23Issues.csv#L257
https://github.com/llvm/llvm-project/blob/445023f1739d3764f1dae6e6b7b0602328198a1e/libcxx/docs/Status/Cxx23Issues.csv#L272

2024-08-07 17:33 UTC, frederick-vs-ja commented on libcxx/include/__ranges/const_access.h
> +  _LIBCPP_HIDE_FROM_ABI constexpr static auto __as_const_pointer(const _Tp* __ptr) noexcept {
Ditto for [LWG3948](https://cplusplus.github.io/LWG/issue3948) (assuming the #99915 will be merged first):
https://github.com/llvm/llvm-project/blob/445023f1739d3764f1dae6e6b7b0602328198a1e/libcxx/docs/Status/Cxx2cIssues.csv#L30

2024-08-07 17:33 UTC, frederick-vs-ja commented on libcxx/include/__ranges/view_interface.h
> +    requires input_range<_Derived>
Ditto for [LWG3766](https://cplusplus.github.io/LWG/issue3766):
https://github.com/llvm/llvm-project/blob/445023f1739d3764f1dae6e6b7b0602328198a1e/libcxx/docs/Status/Cxx23Issues.csv#L223

2024-09-02 12:39 UTC, strega-nil commented
Closing as this will be merged into the original PR.

2024-09-02 12:39 UTC, closed without merging