[clang] Add frontend flag to enable support for broken external resugarers
llvm/llvm-project pull request #102510
Opened 2024-08-08 17:52 UTC by mizvekov

There are some external projects that can't rely on our own sugar propagation for templated entities, because they need to resugar types which only exist within their framework, and so are entirely invisible to our internal tooling.

This new flag is meant to prevent our transforms from removing any Subst* nodes.

For this patch, it's wired only to template type alias substitutions.

Note that our AST does *not* represent enough information to correctly resugar template type alias, so any users of this are either defective or working under limited scenarios.

See discussion at https://github.com/llvm/llvm-project/pull/101858 for motivation.

2024-08-09 13:05 UTC, gribozavr approved these changes
Thank you! This change fixes and unblocks our nullability and lifetime tooling. Please merge at your convenience.

2024-08-09 13:49 UTC, AaronBallman commented
The precommit CI failures are related to your changes and need to be addressed.

2024-08-09 13:55 UTC, AaronBallman requested changes
I think using "broken" in the name of the diagnostic and the internal option is a bit problematic -- that's too much of a value judgement, IMO. After all, the previous functionality worked well enough for those folks.

Would it make more sense to name it something along the lines of "retain substitution ast nodes"?

2024-08-12 13:25 UTC, ymand commented
Gentle ping. It's critical that this land so we can unbreak our system. Thanks!

2024-08-13 15:03 UTC, ymand commented
I've posted a fix as https://github.com/llvm/llvm-project/pull/103219

2024-08-13 18:04 UTC, ymand commented
https://github.com/llvm/llvm-project/pull/103219 has been merged as https://github.com/llvm/llvm-project/commit/661dda9df13c65ce021407bb726b558c7a414731.

2024-08-13 18:46 UTC, mizvekov commented
> I think using "broken" in the name of the diagnostic and the internal option is a bit problematic -- that's too much of a value judgement, IMO. After all, the previous functionality worked well enough for those folks.
> 
> 
> 
> Would it make more sense to name it something along the lines of "retain substitution ast nodes"?

Thanks. My intention was mostly to discourage users from trying it, without at least looking sideways.

Though I am fine with the name change.

Thanks for fixing the commit up.

2024-08-14 20:30 UTC, mizvekov commented
Closed as completed elsewhere.

2024-08-14 20:30 UTC, closed without merging