Fixes and closes issues, #53390 and #58710. Added new controls to IndentNamespaceAliases, IndentUsingDeclarations and DecorateReflowedComments.
llvm/llvm-project pull request #102894
Opened 2024-08-12 12:40 UTC by rajkumarananthu

Issue #53390 was reported to have an option to control indenting namespace aliases independently of NamespaceIndentation, added this feature.

Issue #58710 was reported to have an option to control the decoration of the block comments, added this feature.

2024-08-12 19:00 UTC, HazardyKnusperkeks requested changes
First of all you need a better title for your change, beginning with "[clang-format]"

Second of all, could you please split this in multiple reviews?

Third of all, you need to add tests.

2024-08-12 19:00 UTC, HazardyKnusperkeks commented on clang/lib/Format/UnwrappedLineParser.cpp
> +      parseStmt(Style.IndentUsingDeclarations);
```suggestion
      parseStmt(/*KeepIndentation=*/Style.IndentUsingDeclarations);
```

2024-08-12 23:48 UTC, rajkumarananthu commented
Thankyou @HazardyKnusperkeks for the review, I am beginner level contributor to LLVM Project and that might be the reason I might have missed some minor details. I will address them. And as advised I will close this pull-request and split into multiple small reviews after addressing this suggestions.

2024-08-12 23:48 UTC, rajkumarananthu commented on clang/lib/Format/UnwrappedLineParser.cpp
> +    OS << I->Tok->Tok.getName() << "[" << "T=" << (unsigned)I->Tok->getType()
I ran clang-format on each file before committing the changes, this additional change came in because of that.

2024-08-13 06:33 UTC, mydeveloperday commented
Why are we added 2 features in one PR please separate

2024-08-13 06:36 UTC, mydeveloperday requested changes
Isn't there overlap here with the other comments review, please separate out the 2 changes

2024-08-13 08:29 UTC, rajkumarananthu commented
Hi @mydeveloperday, I will close this PR and correct it by making individual PRs for individual features.

Thankyou
Rajkumar.

2024-08-13 13:58 UTC, mydeveloperday commented
see my comment here (https://github.com/llvm/llvm-project/issues/53390) about why do we need `IndentNamespaceAliases` and `IndentUsingDeclarations` this just feels like it open the door to `IndentFunctions`, `IndentWhatever`  I don't get why Aliases and Using would need to be treated differently from anything else? am I missing something?

2024-08-13 14:13 UTC, mydeveloperday commented
> Hi @mydeveloperday, I will close this PR and correct it by making individual PRs for individual features.
> 
> Thankyou Rajkumar.

Incase this is your first submission here is some guidance for clang-format commits: (this isn't an exhaustive list)

- Get buy in from the main contributors @owenca , @HazardyKnusperkeks , @rymiel, @mydeveloperday before struggling through a large PR, we want to welcome new comers but we sort of need to have agreement on if we want the change.
- Always add tests 
- If you touch TokenAnnotator.cpp then likely you'll need an AnnotatorTest, but a formatting test is good
- We don't use lit tests much but 99% of the time we use the GoogleTests
- Try not to change existing tests
- Always git-clang-format the code before submission
- If you change Format.h you need to regenerate the documentation ClangStyleFormatOptions.rst every time
- Documentation needs to carry a /version when it was introduced if the option is new.
- New options need to carry /code examples
- Backwards compatibility is king! people get grump if we change default behavior.
- Ask yourself does this need a new option or can an existing option support what you need (maybe change it from bool -> enum)
- Begin all commits with [clang-format] in the title
- Adding the people above as reviewer helps your change get attention, some of us have lower cadence than the others (me), my day job gets in the way.
- We really want new features to have a public style guide for a largish open source project  that support the feature (not one or two people personal opinion), if you can quote the style guide wanting it that's extra points.
- Don't try and do more than one piece of work at a time.
- Don't change other pieces of code unrelated to your change (do that separately if its important)
- Run all the FormatTests before submitting (this times I've fat fingered that!)
- If you can run the sphinx documentation generation. (harder to setup)

2024-08-13 15:29 UTC, rajkumarananthu commented
as per the conversation, closing and discarding the PR, will add individual PR addressing the review comments.

2024-08-13 15:29 UTC, closed without merging