[Clang][AST] Add Test Cases for Reference Qualifiers in Opr Overload
llvm/llvm-project pull request #102878
Opened 2024-08-12 10:46 UTC by 0xzre

Follow up of issue #102422

2024-08-12 11:39 UTC, zwuis commented on clang/test/SemaCXX/function-type-qual.cpp
> +struct C {
```suggestion
struct GH102422 {
```

2024-08-15 15:58 UTC, zwuis commented
CC @shafik

2024-08-27 07:35 UTC, cor3ntin approved these changes
Thanks!

2024-08-27 15:29 UTC, cor3ntin requested changes
FYI the tests are failing

2024-08-28 13:51 UTC, 0xzre commented
> FYI the tests are failing

@cor3ntin  The solution here #79748 doesn't pass the test too. Kinda expected not to pass the test clang

2024-08-28 15:48 UTC, Endilll commented
> @cor3ntin The solution here #79748 doesn't pass the test too. Kinda expected not to pass the test clang

If tests are not intended to pass, you should expect the diagnostics we issue today, and leave FIXMEs appropriately to indicate where Clang's behavior is wrong.

2024-08-28 15:54 UTC, Endilll commented
Here's an example:
https://github.com/llvm/llvm-project/blob/114ff99e93edd699fd94cf2a84de75e8845fc76b/clang/test/CXX/drs/cwg10xx.cpp#L85-L90

2024-11-22 07:22 UTC, charan-003 commented
hi, i want to work on it

2025-11-15 08:13 UTC, closed without merging