[mlir][spirv] Fix incorrect metadata in SPIR-V Header
llvm/llvm-project pull request #104242
Opened 2024-08-14 21:24 UTC by AmrDeveloper

SRIP-V Generator Magic Number is a 32 bit word: The high order 16 bits are a tool ID. The low order 16 bits are for verion number, So fix the metadata generator to put the version major and minor in the low 16 bits

fixes: #99071

2024-08-15 02:22 UTC, kuhar commented
@andfau-amd could you help review this?

2024-08-15 12:33 UTC, andfau-amd commented on mlir/lib/Target/SPIRV/SPIRVBinaryUtils.cpp
> +  // | Version number (bytes: 0 | 0 | major number | minor number)             |
This seems to contradict the text of the spec: https://registry.khronos.org/SPIR-V/specs/unified1/SPIRV.html#_physical_layout_of_a_spir_v_module_and_instruction (see section 2.3 "Physical Layout of a SPIR-V Module and Instruction")

Can you demonstrate that it's correct? For example, does `spirv-dis` agree with it?

2024-08-15 12:34 UTC, andfau-amd requested changes

2024-08-15 12:34 UTC, andfau-amd commented on mlir/lib/Target/SPIRV/SPIRVBinaryUtils.cpp
>    header.push_back(kGeneratorNumber);
The generator number was the thing the issue was about, and that isn't changed here, so this pull request doesn't fix the issue.

2024-08-17 09:00 UTC, AmrDeveloper commented
Can you check it @andfau-amd 

Thank you

2024-08-19 12:08 UTC, andfau-amd approved these changes

2024-08-19 12:08 UTC, andfau-amd commented on mlir/lib/Target/SPIRV/SPIRVBinaryUtils.cpp
> +  header.push_back((kGeneratorNumber << 16) | LLVM_VERSION_MAJOR);
This looks good. Ideally the major, minor and patch version should be included, but I don't think 16 bits is enough to fit all of those safely, and it'd be hard to read in something like `spirv-dis`, so this is probably fine. Thanks for the contribution.

2024-08-19 14:23 UTC, kuhar reviewed
Could you show a sample output from spirv-dis after this change?

2024-08-19 18:41 UTC, AmrDeveloper commented
> Could you show a sample output from spirv-dis after this change?

```
; SPIR-V
; Version: 1.0
; Generator: Google MLIR SPIR-V Serializer; 20
; Bound: 95
; Schema: 0
```
[hello.module.zip](https://github.com/user-attachments/files/16664117/hello.module.zip)

2024-08-19 18:57 UTC, kuhar approved these changes
LGTM, thanks for fixing this

2024-08-19 18:58 UTC, merged