[clang][driver] Don't warn when -S and -c are used together without -fsyntax-only
llvm/llvm-project pull request #104477
Opened 2024-08-15 17:52 UTC by ilovepi

Claim `-c` when using `-S`, so that we don't warn for unused arguments
when they are used together without `-fsyntax-only`.

Fixes #104347

2024-08-15 17:54 UTC, ilovepi commented on clang/test/Driver/warn-fsyntax-only.c
> +// RUN: %clang --target=x86_64 -fsyntax-only -S -c %s 2>&1 | FileCheck %s --check-prefixes=CHECK-ASM,CHECK-OBJ
Do these need the target set? Seems like this should be fine for any target, right?

2024-08-15 18:00 UTC, ilovepi commented on clang/lib/Driver/Driver.cpp
> +    // -c compilation only runs up to the assembler.
Not sure why `git clang-format` wanted to update this comment, but 🤷 .

2024-08-15 18:23 UTC, MaskRay commented
> Fixes https://github.com/llvm/llvm-project/issues/104347

I made a comment on #104347  . The warning for `-S -c` works as intended.

2024-09-16 08:58 UTC, MaskRay requested changes
.

2024-09-16 15:38 UTC, closed without merging