[MLIR][MathDialect] fix fp32 promotion crash when encounters scf.if
llvm/llvm-project pull request #104451
Opened 2024-08-15 14:56 UTC by crazydemo

This PR fixes a corner case, which needs to do promotion within a `scf.if` block.
The current main branch crashes in such case, due to `scf.if` will also be promoted.

2024-08-15 15:01 UTC, crazydemo commented
take the below case as an example:
```
func.func @promote_in_if_block(%arg0: bf16, %arg1: bf16, %arg2: i1) -> bf16 {
  %0 = scf.if %arg2 -> bf16 {
    %1 = math.absf %arg0 : bf16
    scf.yield %1 : bf16
  } else {
    scf.yield %arg1 : bf16
  }
  return %0 : bf16
}
```

after applied `LegalizeToF32RewritePattern` will get:
```
"builtin.module"() ({
  "func.func"() <{function_type = (bf16, bf16, i1) -> bf16, sym_name = "promote_in_if_block"}> ({
  ^bb0(%arg0: bf16, %arg1: bf16, %arg2: i1):
    %0 = "scf.if"(%arg2) : (i1) -> f32
    %1 = "arith.truncf"(%0) <{fastmath = #arith.fastmath<contract>}> : (f32) -> bf16
    %2 = "scf.if"(%arg2) ({
      "scf.yield"(%arg0) : (bf16) -> ()
    }, {
      "scf.yield"(%arg1) : (bf16) -> ()
    }) : (i1) -> bf16
    "func.return"(%2) : (bf16) -> ()
  }) : () -> ()
}) : () -> ()
```
Note that here's a newly generated `%0 = "scf.if"(%arg2) : (i1) -> f32`, which is invalid for further scf::IfOp folder, as its `numRegions=1`. The folder function needs the `numRegions=2`, otherwise when `getElseRegion()` will exceed the index range.

2024-08-16 16:22 UTC, krzysz00 requested changes
I think this change could be generalized and introduces a dependency on `scf` that's not needed here - that is, this could cause issues with, say, `scf.for`

2024-08-19 12:40 UTC, crazydemo commented on mlir/lib/Dialect/Math/Transforms/LegalizeToF32.cpp
> +  target.addLegalOp<scf::IfOp>();
I set all the `non-math` dialects as legal. Maybe Arith should be processed in `emulate-unsupported-floats`.

2024-08-19 12:41 UTC, crazydemo commented on mlir/lib/Conversion/MathToLibm/MathToLibm.cpp
> +  populatePatternsForOp<math::RsqrtOp>(patterns, ctx, "rsqrtf", "rsqrt");
find `rsqrtOp` is not legalized in `mathToLibm pass`, fix it in this PR.

2024-08-20 18:09 UTC, krzysz00 approved these changes
Lgtm, though maybe break the `rsqrt` change into a different PR

2024-08-21 02:06 UTC, BRUCE11111 approved these changes

2024-08-21 02:08 UTC, merged