[clang-tidy] Support member functions with modernize-use-std-print/format
llvm/llvm-project pull request #104675
Opened 2024-08-17 16:07 UTC by mikecrowe

These checks can be made to work on member functions quite easily and it's not unknown to have at least printf-style functions as members. Let's remove the restriction.

2024-08-17 19:16 UTC, PiotrZSL approved these changes

2024-08-17 19:16 UTC, PiotrZSL commented on clang-tools-extra/docs/ReleaseNotes.rst
> +  <clang-tidy/checks/modernize/use-std-format>` and
wrong name, and split that entry into 2, even if you would need to duplicate description

2024-08-17 20:13 UTC, PiotrZSL approved these changes

2024-08-18 14:23 UTC, EugeneZelenko requested changes

2024-08-18 14:23 UTC, EugeneZelenko commented on clang-tools-extra/docs/ReleaseNotes.rst
> +- Improved :doc:`modernize-use-std-print
Duplicate entry.

2024-08-18 15:46 UTC, merged