[lldb-dap] Fix disassembled ranges for `disassemble` request
llvm/llvm-project pull request #105446
Opened 2024-08-20 23:05 UTC by vogelsgesang

This is a first draft PR which fixes #103021

The main issue was that the `instructionOffset` was handled as a byte offset and not as an instruction offset.

This commit also incorporates previous feedback from https://reviews.llvm.org/D140358: With this change, we are using symbols and DWARF debug information to find function boundaries and correctly start disassembling at this address.

TODO:
* Update test case
* Check if we can also support disassembling across functions

2024-08-20 23:58 UTC, vogelsgesang commented
@clayborg I would be interested in your guidance for this PR, given that you previously reviewed a similar change in https://reviews.llvm.org/D140358

I did use `SBFunction` / `SBSymbol` as suggested by you in [this comment](https://reviews.llvm.org/D140358#4027551). 

I did not know how to address the part

```
    // then we need to repeat the search for the next function or symbol. 
    // note there may be bytes between functions or symbols which we can disassemble
    // by calling _get_instructions_from_memory(...) but we must find the next
    // symbol or function boundary and get back on track
```

from your comment, though. Is there some API to find the next symbol? Or some API to get a list of symbols, sorted by their start address?

I could of course use a brute-force approach, similar to

```
SBAddress addr;
while (!addr.GetFunction() && !addr.GetSymbol())
   addr = addr.OffsetAddress(1);
```

but that seems a bit wasteful

2025-02-28 02:23 UTC, clayborg requested changes
Sorry for the delay, let me know if you have any questions!

2025-02-28 02:23 UTC, clayborg commented on lldb/tools/lldb-dap/lldb-dap.cpp
> +  addr_ptr += GetSigned(arguments, "offset", 0);
Is "offset" required? If so we don't want to set it to zero if this fails, we would wan't to return an error. Use the above `GetSigned` function that returns an `llvm::Expected`

2025-02-28 02:23 UTC, clayborg commented on lldb/tools/lldb-dap/lldb-dap.cpp
> -  addr_ptr += GetSigned(arguments, "instructionOffset", 0);
We still need to use the "instructionOffset" here if it is specified. Seems like it isn't optional, so if it isn't here, then maybe return an error if it is required. We might want to add a overload of GetSigned like:
```
llvm::Expected<int64_t> GetSigned(arguments, "instructionOffset");
```
This would return an error if it isn't in the args, or if the decoding failed. We can just return a string version of the error as an error to this command.

2025-02-28 02:23 UTC, clayborg commented on lldb/tools/lldb-dap/lldb-dap.cpp
> +  const int64_t inst_count = GetSigned(arguments, "instructionCount", 0);
Use the `llvm::Expected<int64_t> GetSigned(...)`? If this is required. Same thing for "instructionOffset" above.

2025-02-28 02:23 UTC, clayborg commented on lldb/tools/lldb-dap/lldb-dap.cpp
> +  offset += inst_offset;
Need to watch for "offset" exceeding the size of the `insts` instruction list here. If we exceed, we need to get the next function and continue the search and update the "inst_offset" and "offset" correctly if we exceed the boundary

2025-02-28 02:23 UTC, clayborg commented on lldb/tools/lldb-dap/lldb-dap.cpp
> +    // Past the range of disassembled instructions?
We will only have 1 function's worth of instructions in "insts" and we will need to update it. I would keep trying to resolve a new Symbol or Function by adding the last instruction byte size the last load address of the last instruction in the list and keep searching for a function or symbol after each resolve call. We will bail if we reach the end of the bytes that were specified.

2025-06-03 11:58 UTC, vogelsgesang commented
superseded by #140486

2025-06-03 11:58 UTC, closed without merging