AMDGPU: Remove flat/global fmin/fmax intrinsics
llvm/llvm-project pull request #105642
Opened 2024-08-22 11:06 UTC by arsenm

These have been replaced with atomicrmw

2024-08-22 11:06 UTC, arsenm commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/105642?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#105642** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/105642?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#97051** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/97051?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#97050** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/97050?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#96876** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/96876?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#96875** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/96875?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#96874** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/96874?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#96873** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/96873?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#96872** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/96872?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#96760** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/96760?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#96759** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/96759?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#96444** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/96444?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#96443** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/96443?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#96442** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/96442?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#95930** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/95930?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#95929** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/95929?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @arsenm and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-08-26 09:09 UTC, rovka approved these changes

2024-08-27 13:01 UTC, arsenm commented on llvm/test/CodeGen/AMDGPU/GlobalISel/fp64-atomics-gfx90a.ll
> -define amdgpu_kernel void @global_atomic_fmin_f64_noret(ptr addrspace(1) %ptr, double %data) {
Yes

2024-09-10 14:13 UTC, doru1004 commented
@arsenm can you provide an alternative to the current functionality which you are removing?

2024-09-10 14:14 UTC, arsenm commented
> @arsenm can you provide an alternative to the current functionality which you are removing? 

Use atomicrmw with appropriate metadata. See the autoupgrade code

2024-09-10 14:15 UTC, doru1004 requested changes
Can you provide a similar intrinsic which can be called as Intrinsic::int_amdgcn_global_atomic_fmax which calls your desired intrinsic instead?

2024-09-10 14:16 UTC, arsenm commented
> Can you provide a similar intrinsic which can be called as Intrinsic::int_amdgcn_global_atomic_fmax which calls your desired intrinsic instead?

No. The point is no intrinsics. Adding an identical intrinsic helps nothing. Only atomicrmw is an acceptable atomic representation

2024-09-10 14:16 UTC, doru1004 commented
> > @arsenm can you provide an alternative to the current functionality which you are removing?
> 
> Use atomicrmw with appropriate metadata. See the autoupgrade code

Are you exposing something like Intrinsic::atomicrmw which I can call from Clang code gen?

2024-09-10 14:19 UTC, arsenm commented
> 
> Are you exposing something like Intrinsic::atomicrmw which I can call from Clang code gen?

atomicrmw is already a first class IR instruction. The intrinsics were always a hack for missing operations and annotations on atomicrmw

2024-09-10 14:19 UTC, doru1004 commented
> > Can you provide a similar intrinsic which can be called as Intrinsic::int_amdgcn_global_atomic_fmax which calls your desired intrinsic instead?
> 
> No. The point is no intrinsics. Adding an identical intrinsic helps nothing. Only atomicrmw is an acceptable atomic representation

I understand and you are free to only use atomicrmw under the hood. I just need to have a way to do it from Clang code gen.

2024-09-10 14:22 UTC, doru1004 commented
> > Are you exposing something like Intrinsic::atomicrmw which I can call from Clang code gen?
> 
> atomicrmw is already a first class IR instruction. The intrinsics were always a hack for missing operations and annotations on atomicrmw

Are there examples of how to emit such an instruction in clang code gen?

2024-09-10 14:30 UTC, arsenm commented
> > > Are you exposing something like Intrinsic::atomicrmw which I can call from Clang code gen?
> 
> > 
> 
> > atomicrmw is already a first class IR instruction. The intrinsics were always a hack for missing operations and annotations on atomicrmw
> 
> 
> 
> Are there examples of how to emit such an instruction in clang code gen?

Yes. The corresponding builtins are already emitting atomicrmw with annotations.

2024-09-10 14:31 UTC, doru1004 commented
> > > > Are you exposing something like Intrinsic::atomicrmw which I can call from Clang code gen?
> > 
> > 
> > > 
> > 
> > 
> > > atomicrmw is already a first class IR instruction. The intrinsics were always a hack for missing operations and annotations on atomicrmw
> > 
> > 
> > Are there examples of how to emit such an instruction in clang code gen?
> 
> Yes. The corresponding builtins are already emitting atomicrmw with annotations.

Can you point me to where this is happening please?

2024-09-11 12:21 UTC, arsenm commented
> Can you point me to where this is happening please?

https://github.com/llvm/llvm-project/blob/b9c2e2e3e910f8283f52c574fd8b6a7981d6cb0d/clang/lib/CodeGen/CGBuiltin.cpp#L19552

2024-09-11 13:47 UTC, doru1004 commented
@arsenm I am not ok with the removal of these intrinsics that allow direct call to some of these atomics. I think you should keep them while you still do the changes that you want with the other atomicrmw. Your change is not backwards compatible.
It is not yet clear to me if calling create atomicrmw is equivalent to calling the old intrisincs.

2024-09-11 13:55 UTC, arsenm commented
> @arsenm I am not ok with the removal of these intrinsics that allow direct call to some of these atomics. I think you should keep them while you still do the changes that you want with the other atomicrmw. 

The changes are already completed and we are at the final point of removal. 

> Your change is not backwards compatible. It is not yet clear to me if calling create atomicrmw is equivalent to calling the old intrisincs.

The intrinsics are strictly less expressive than atomicrmw. There is no plus to using the intrinsics, and it is trivial to migrate to an atomicrmw that will produce the ISA instruction. The old intrinsics had broken scope and ordering arguments which did not work. You only need to decide whether the use case is OK with breaking remote memory, fine grained memory, or both.

2024-09-12 07:39 UTC, rovka commented
> @arsenm I am not ok with the removal of these intrinsics that allow direct call to some of these atomics. I think you should keep them while you still do the changes that you want with the other atomicrmw. Your change is not backwards compatible. It is not yet clear to me if calling create atomicrmw is equivalent to calling the old intrisincs.

@doru1004 Can you please provide an example use case where it's not clear how to use atomicrmw to replace the old intrinsics? Then maybe we can add something to the docs or at least commit message to clarify.

2024-09-16 15:28 UTC, doru1004 commented
> > @arsenm I am not ok with the removal of these intrinsics that allow direct call to some of these atomics. I think you should keep them while you still do the changes that you want with the other atomicrmw. Your change is not backwards compatible. It is not yet clear to me if calling create atomicrmw is equivalent to calling the old intrisincs.
> 
> @doru1004 Can you please provide an example use case where it's not clear how to use atomicrmw to replace the old intrinsics? Then maybe we can add something to the docs or at least commit message to clarify.

For all the cases where the intrinsic was used i.e. fadd/fmin/fmax emitting atomic RMW without any metadata is conservative, safe but not equivalent with the behavior of the intrinsic. So one thing that has not been clear is what is the correct combination of metadata attributes that allows the newly emitted atomic RMW instruction to be equivalent (or very very close) to the behavior of the intrinsic that was removed. I would argue that some higher level functions like emitAtomicRMW{FAdd/FMin/FMax} are needed to cover those cases and emit the atomicRMW with the correct combination of metadata attributes.

2024-10-08 19:44 UTC, shiltian approved these changes
LGTM, as long as @doru1004 's concern has been resolved.

2024-10-08 19:51 UTC, doru1004 commented
I would still like to see something like the functions I suggested in my previous comment. Something that will be equivalent with the intrinsic that is being eliminated. These functions would use the new atomicRMW method AND also set the attributes accordingly such that it matches the behavior of the intrinsic.

2024-10-08 19:55 UTC, arsenm commented
> I would still like to see something like the functions I suggested in my previous comment. Something that will be equivalent with the intrinsic that is being eliminated. These functions would use the new atomicRMW method AND also set the attributes accordingly such that it matches the behavior of the intrinsic.

There won't be a new function, but @yxsamliu is working on source level controls for these fields for the atomic builtins

2024-10-08 20:02 UTC, doru1004 commented
> There won't be a new function, but @yxsamliu is working on source level controls for these fields for the atomic builtins

I need to be able to call this from Clang code gen. The reason I insist on this is because I don't think the selection of attributes to pass to the current atomicRMW function is clear enough i.e. if I was relying on the intrinsic up until now, it is not clear what set of additional options to pass to atomicRMW() to make it behave like the intrinsic. So I would like that knowledge to live somewhere in the compiler i.e. in the shape of a function atomicRMWFastFAdd or something like that which calls atomicRMW under the hood BUT ALSO provides the set of additional options that make it behave like the intrinsic.

2024-10-08 20:08 UTC, arsenm commented
> I need to be able to call this from Clang code gen. The reason I insist on this is because I don't think the selection of attributes to pass to the current atomicRMW function is clear enough i.e. if I was relying on the intrinsic up until now, it is not clear what set of additional options to pass to atomicRMW() to make it behave like the intrinsic. 

This is exactly why we must remove this intrinsic or anything that acts like it. You, the frontend writer, must semantically know what you can do. The semantics cannot be "do whatever the intrinsic happens to do on this target"

2024-10-08 20:20 UTC, doru1004 commented
> This is exactly why we must remove this intrinsic or anything that acts like it. You, the frontend writer, must semantically know what you can do. The semantics cannot be "do whatever the intrinsic happens to do on this target"

But you're not removing everything that acts like it except for the intrinsic itself. There's nothing illegal about asking for a new style of atomic RMW with a particular set of additional options that happens to match the previous intrinsic.

2024-10-08 20:41 UTC, arsenm commented
> But you're not removing everything that acts like it except for the intrinsic itself. There's nothing illegal about asking for a new style of atomic RMW with a particular set of additional options that happens to match the previous intrinsic.

Part of the point of this is to make you do this work. Adding a convenience to "match the intrinsic" is counterproductive. The intrinsic was not semantically defined

2024-10-08 20:59 UTC, doru1004 commented
> Part of the point of this is to make you do this work. Adding a convenience to "match the intrinsic" is counterproductive. The intrinsic was not semantically defined

The problem is that no one knows what options to use to make the atomicRMW closer to the old intrinsic. You do not document that anywhere.

2024-10-08 21:19 UTC, arsenm commented
> The problem is that no one knows what options to use to make the atomicRMW closer to the old intrinsic. You do not document that anywhere.

[It's in AMDGPUUsage](https://llvm.org/docs/AMDGPUUsage.html#llvm-ir-metadata)

2024-10-09 05:27 UTC, merged

2024-10-11 12:41 UTC, doru1004 commented
> > The problem is that no one knows what options to use to make the atomicRMW closer to the old intrinsic. You do not document that anywhere.
> 
> [It's in AMDGPUUsage](https://llvm.org/docs/AMDGPUUsage.html#llvm-ir-metadata)

I agree but that doesn't say what combination of those options to use to be as close as possible to the previous intrinsic. So if we can document that then we will be all good!