[InstCombine] Simplify `(add/sub (sub/add) (sub/add))` irrelevant of use-count
llvm/llvm-project pull request #105866
Opened 2024-08-23 18:03 UTC by goldsteinn

- **[InstCombine] Add tests for reassosiating `(add/sub (sub/add) (sub/add))`; NFC**
- **[InstCombine] Simplify `(add/sub (sub/add) (sub/add))` irrelivant of use-count**

Added folds:
    - `(add (sub X, Y), (sub Z, X))` -> `(sub Z, Y)`
    - `(sub (add X, Y), (add X, Z))` -> `(sub Y, Z)`

The fold typically is handled in the `Reassosiate` pass, but it fails
if the inner `sub`/`add` are multi-use. Less importantly, Reassosiate
doesn't propagate flags correctly.

This patch adds the fold explicitly the InstCombine

Proofs: https://alive2.llvm.org/ce/z/p6JyRP

2024-08-23 18:04 UTC, goldsteinn commented
NB regarding if this patch exists, saw changes in:

./lib/Demangle/MicrosoftDemangle.cpp
./lib/Target/ARM/ARMConstantIslandPass.cpp
./lib/Target/ARM/ARMISelDAGToDAG.cpp
./lib/Target/Mips/MipsConstantIslandPass.cpp
./lib/Transforms/Scalar/DeadStoreElimination.cpp
./lib/Transforms/Vectorize/SLPVectorizer.cpp
./tools/clang/lib/Edit/EditedSource.cpp
./tools/clang/lib/Format/BreakableToken.cpp

when bootstrapping LLVM (changes in final output of O3 pipeline).

2024-08-23 19:53 UTC, dtcxzyw requested changes
This patch causes clang to miscompile lief:
Reproducer:
```
static inline unsigned char mbedtls_ct_uchar_in_range_if(unsigned char low,
                                                         unsigned char high,
                                                         unsigned char c,
                                                         unsigned char t)
{
    const unsigned char co = (unsigned char) (c);
    const unsigned char to = (unsigned char) (t);

    /* low_mask is: 0 if low <= c, 0x...ff if low > c */
    unsigned low_mask = ((unsigned) co - low) >> 8;
    /* high_mask is: 0 if c <= high, 0x...ff if c > high */
    unsigned high_mask = ((unsigned) high - co) >> 8;

    return (unsigned char) (~(low_mask | high_mask)) & to;
}

unsigned char mbedtls_ct_base64_enc_char(unsigned char value)
{
    unsigned char digit = 0;
    /* For each range of values, if value is in that range, mask digit with
     * the corresponding value. Since value can only be in a single range,
     * only at most one masking will change digit. */
    digit |= mbedtls_ct_uchar_in_range_if(0, 25, value, 'A' + value);
    digit |= mbedtls_ct_uchar_in_range_if(26, 51, value, 'a' + value - 26);
    digit |= mbedtls_ct_uchar_in_range_if(52, 61, value, '0' + value - 52);
    digit |= mbedtls_ct_uchar_in_range_if(62, 62, value, '+');
    digit |= mbedtls_ct_uchar_in_range_if(63, 63, value, '/');
    return digit;
}

int main() {
    return mbedtls_ct_base64_enc_char(0);
}
```
It should map `0` to `65(ascii 'A')`, not `-1`.

2024-08-23 20:27 UTC, goldsteinn commented
> This patch causes clang to miscompile lief: Reproducer:
> 
[... snip ...]
> 
> It should map `0` to `65(ascii 'A')`, not `-1`.

Fixed... wasnt guarding the `foldAddLike` in `visitOr` with a `disjoint` check...

2024-08-24 09:01 UTC, dtcxzyw commented on llvm/lib/Transforms/InstCombine/InstCombineAddSub.cpp
> +      if (W == Z)
```suggestion
      else if (W == Z)
```
We will create unused sub when W == Y && W == Z.

2024-08-24 10:00 UTC, nikic commented on llvm/lib/Transforms/InstCombine/InstCombineInternal.h
> +  Instruction *foldAddLike(BinaryOperator &I);
If we add this kind of API, I think it would be better to make the signature `Value *LHS, Value *RHS, bool NUW, bool NSW`.

2024-08-25 07:00 UTC, dtcxzyw approved these changes
LG

2024-08-25 09:31 UTC, nikic commented on llvm/lib/Transforms/InstCombine/InstructionCombining.cpp
> +Instruction *InstCombinerImpl::foldAddLike(Value *LHS, Value *RHS, bool NSW,
I'd also add `foldAddLikeCommutative()` which is invoked with both LHS/RHS orders, as most add folds with non-constant RHS will want to check both orders.

Then your pattern here will reduce down to:
```
if (match(LHS, m_Sub(m_Value(A), m_Value(B))) &&
    match(RHS, m_Sub(m_Value(C), m_Specific(A)))) {
```

2024-08-27 12:15 UTC, nikic approved these changes
LGTM

2024-08-27 18:43 UTC, closed without merging