[AMDGPU][LTO] Assume closed world after linking
llvm/llvm-project pull request #105845
Opened 2024-08-23 15:27 UTC by gandhi56

Change-Id: I7d8fa4251c80a6f815f55a0998677d18ade25b72

2024-08-23 16:08 UTC, shiltian commented on llvm/lib/Target/AMDGPU/AMDGPUTargetMachine.cpp
> +              AMDGPUAttributorPass(*this, AMDGPUAttributorOptions{true}));
I'd suggest to do:

```
AMDGPUAttributorOptions Options;
Options.IsClosedWorld = true;
```

And then pass the option.

2024-08-23 16:22 UTC, shiltian approved these changes
LGTM with one nit

2024-08-23 16:23 UTC, shiltian requested changes
Oops, replied the wrong PR. Sorry.

2024-08-23 16:23 UTC, shiltian commented on clang/test/CodeGenCUDA/gpu-rdc-amdgpu-attrs.cu
> +// RUN: clang -x hip -O3 -fgpu-rdc %s -mllvm -debug-only=amdgpu-attributor -o - | FileCheck %s
This should not be a clang test. You can have an opt test.

2024-08-23 18:47 UTC, shiltian commented on llvm/lib/Target/AMDGPU/AMDGPUTargetMachine.cpp
> +        AMDGPUAttributorOptions Opts;
Bring these into the `if` block.

2024-08-23 18:48 UTC, shiltian commented on llvm/lib/Target/AMDGPU/AMDGPUAttributor.cpp
> +  dbgs() << "Module " << M.getName() << " is "
Where the `LLVM_DEBUG` macro?

2024-08-23 19:06 UTC, shiltian approved these changes

2024-08-25 17:12 UTC, gandhi56 commented
Rebased against trunk

2024-08-25 18:06 UTC, merged