[ADT] Skip destroying trivially destructible values in DenseMap
llvm/llvm-project pull request #106934
Opened 2024-09-02 01:45 UTC by kazutakahirata

2024-09-02 14:01 UTC, kuhar reviewed
This looks fine in isolation, but I wonder if we do have a test that makes sure that non-trivial destructors get run?

2024-09-03 05:20 UTC, kazutakahirata commented
> This looks fine in isolation, but I wonder if we do have a test that makes sure that non-trivial destructors get run?

Let me come up with some tests.  Thanks!

2024-12-07 19:04 UTC, MaskRay requested changes
Test?

2024-12-09 19:26 UTC, dwblaikie commented
> Test?

Not sure this is testable? If they're trivially destructible, it wouldn't be possible to observe the difference between destroying them and not destroying them, right?

2024-12-09 19:28 UTC, MaskRay approved these changes

2024-12-09 19:40 UTC, kuhar commented
> > Test?
> 
> Not sure this is testable? If they're trivially destructible, it wouldn't be possible to observe the difference between destroying them and not destroying them, right?

We could have the test for the non-trivially destructible case to make sure we don't unintentionally skip destructors.

2024-12-09 20:17 UTC, dwblaikie commented
> > > Test?
> > 
> > 
> > Not sure this is testable? If they're trivially destructible, it wouldn't be possible to observe the difference between destroying them and not destroying them, right?
> 
> We could have the test for the non-trivially destructible case to make sure we don't unintentionally skip destructors. If we already do, it would be good to point out in the PR description.

Sure, that'd be nice - good call.

2025-10-25 13:25 UTC, kazutakahirata commented
I've landed #165080 with tests instead.  Closing.

2025-10-25 13:25 UTC, closed without merging