[libc++] Remove _LIBCPP_USING_IF_EXISTS from fundamental aliases
llvm/llvm-project pull request #107220
Opened 2024-09-04 11:06 UTC by philnik777

There are a few types without which the library is hopelessly broken. Specifically, these are `size_t`, `ptrdiff_t` and the `intX_t` and `uintX_t` types. This results in significantly better diagnostics if they are missing, since they are flagged at the `using` instead of the inevitable first use.

2024-09-05 14:05 UTC, ldionne requested changes
This makes sense to me for `ptrdiff_t`, `size_t` and `nullptr_t`, but not for the optional types like `int8_t`. Also this should be rebased on top of the new `__cstddef` headers.

2024-09-05 16:34 UTC, ldionne commented on libcxx/include/cstdint
> +using ::uint64_t;
You convinced me.

2024-09-13 13:32 UTC, ldionne commented
@philnik777 I rebased the patch and applied my comments, and I also dropped `using_if_exists` from `max_align_t`. Please let me know what you think of the patch now -- I'd be fine to land as-is.

If you land, please remember to update the PR description first so it reflects what the new version of the patch does.

2024-09-13 13:32 UTC, ldionne approved these changes

2024-11-05 15:21 UTC, philnik777 commented
This is superseded by #114788.

2024-11-05 15:21 UTC, closed without merging