[MLIR] Add f6E2M3FN type
llvm/llvm-project pull request #107999
Opened 2024-09-10 10:50 UTC by sergey-kozub

This PR adds `f6E2M3FN` type to mlir.

`f6E2M3FN` type is proposed in [OpenCompute MX Specification](https://www.opencompute.org/documents/ocp-microscaling-formats-mx-v1-0-spec-final-pdf). It defines a 6-bit floating point number with bit layout S1E2M3. Unlike IEEE-754 types, there are no infinity or NaN values.

```c
f6E2M3FN
- Exponent bias: 1
- Maximum stored exponent value: 3 (binary 11)
- Maximum unbiased exponent value: 3 - 1 = 2
- Minimum stored exponent value: 1 (binary 01)
- Minimum unbiased exponent value: 1 − 1 = 0
- Has Positive and Negative zero
- Doesn't have infinity
- Doesn't have NaNs

Additional details:
- Zeros (+/-): S.00.000
- Max normal number: S.11.111 = ±2^(2) x (1 + 0.875) = ±7.5
- Min normal number: S.01.000 = ±2^(0) = ±1.0
- Max subnormal number: S.00.111 = ±2^(0) x 0.875 = ±0.875
- Min subnormal number: S.00.001 = ±2^(0) x 0.125 = ±0.125
```

Related PRs:
- [PR-94735](https://github.com/llvm/llvm-project/pull/94735) [APFloat] Add APFloat support for FP6 data types
- [PR-105573](https://github.com/llvm/llvm-project/pull/105573) [MLIR] Add f6E3M2FN type - was used as a template for this PR

2024-09-11 22:16 UTC, apivovarov requested changes

2024-09-11 22:16 UTC, apivovarov commented on mlir/include/mlir/IR/BuiltinTypes.td
> +  let summary = "6-bit floating point with 3 bits exponent and 2 bit mantissa";
2 bits exponent and 3 bit mantissa

2024-09-16 07:08 UTC, sergey-kozub commented on mlir/include/mlir/IR/BuiltinTypes.td
> +  let summary = "6-bit floating point with 3 bits exponent and 2 bit mantissa";
Fixed.

2024-09-16 18:08 UTC, apivovarov approved these changes

2024-09-16 19:09 UTC, merged