[mlir][vector] Replace cast_or_null with dyn_cast_or_null
llvm/llvm-project pull request #108048
Opened 2024-09-10 15:54 UTC by CoTinker

This patch replaces cast_or_null with dyn_cast_or_null, which fixes a crash when operation in `vector.mask` not implements the `MaskableOpInterface`. Fixes #107811.

2024-09-10 16:52 UTC, MaheshRavishankar approved these changes

2024-09-10 22:15 UTC, joker-eph approved these changes

2024-09-10 22:30 UTC, dcaballe requested changes
Hmm... this is not correct. If there is a maskable op it should implement the maskable op interface, otherwise it's a bug.

For this particular test case, we shouldn't be masking a `vector.bitcast` because speculatively executing a bitcast don't have any side effects.

2024-09-10 23:36 UTC, joker-eph commented
> Hmm... this is not correct. If there is a maskable op it should implement the maskable op interface, otherwise it's a bug.

Are you saying we're missing a verifier here?

2024-09-11 00:53 UTC, dcaballe commented
> Are you saying we're missing a verifier here?

Yes, I took a quick look: https://github.com/llvm/llvm-project/pull/108123
We should check that this is not breaking downstreams using `vector.mask`, though. @hanhanW @banach-space, could you help with that? We may have to add MaskableOpInterface to a few operations.

2024-09-16 07:49 UTC, hanhanW commented
> > Are you saying we're missing a verifier here?
> 
> Yes, I took a quick look: #108123 We should check that this is not breaking downstreams using `vector.mask`, though. @hanhanW @banach-space, could you help with that? We may have to add MaskableOpInterface to a few operations.

Thanks for taking a look at this! I am just back from vacation and catching up with changes. I'll get back to this later.

2024-09-17 14:00 UTC, banach-space commented
> We should check that this is not breaking downstreams using `vector.mask`, though. @hanhanW @banach-space, could you help with that? We may have to add MaskableOpInterface to a few operations.

All seems good at our end, thanks for waiting!

2024-10-14 11:36 UTC, closed without merging