Add missing FillOp to winograd lowering
llvm/llvm-project pull request #108181
Opened 2024-09-11 10:04 UTC by RoboTux

Winograd lowering involves a number of matmul and batch_matmul which
are currently passed tensor.empty result as out parameter, thereby
are undefined behaviour. This commit adds the necessary linalg.fill.

2024-09-11 16:37 UTC, Max191 requested changes
Thanks for catching this. It's a little hard to see what's changing in the lit tests, since all the names in the checks have changed. Could you keep the names there the same? Also, please add checks in the decomposition tests that fill ops are created and used in the matmuls.

2024-09-11 16:37 UTC, Max191 commented on mlir/test/Dialect/Linalg/transform-tile-and-winograd-rewrite.mlir
> +// CHECK:      %[[INSERTED_SLICE:.*]] = tensor.insert_slice %[[S15]] into %[[ARG6]][0, 0, %[[ARG5]], %[[ARG3]]] [6, 6, 1, 1] [1, 1, 1, 1]
Can you also check that the `outs` has the result of the fill?

2024-09-11 16:37 UTC, Max191 commented on mlir/test/Dialect/Linalg/transform-tile-and-winograd-rewrite.mlir
> +// CHECK:          %[[S19:.*]] = linalg.matmul
Same here, check that fill is in the `outs`

2024-09-11 16:37 UTC, Max191 commented on mlir/test/Dialect/Linalg/transform-tile-and-winograd-rewrite.mlir
> +// CHECK:      %[[EXTRACTED_SLICE_8:.*]] = tensor.extract_slice %[[S2]][0, 0, %[[ARG3]], %[[ARG5]], 0, 0] [6, 6, 1, 1, 2, 5] [1, 1, 1, 1, 1, 1]
Why are the names of all these checks changing? It doesn't seem to be necessary.

2024-09-12 08:42 UTC, RoboTux commented
> Thanks for catching this. It's a little hard to see what's changing in the lit tests, since all the names in the checks have changed. Could you keep the names there the same? Also, please add checks in the decomposition tests that fill ops are created and used in the matmuls.

I've reduced the noise somewhat but adding the fill inevitably resequence quite a bit of SSA values. It also leads to some FileCheck variable reuse because not everything was renamed. Alternatively if you prefer I could do a NFC patch that just update all FileCheck variable like in my first attempt but doesn't have the fix. Then in a second patch I can add just the fix and the new CHECK and land that as a rebase rather than squash if that's possible in github.

2024-09-13 13:34 UTC, Max191 approved these changes
Thanks! This looks much better.

2024-09-13 13:34 UTC, Max191 commented on mlir/test/Dialect/Linalg/transform-tile-and-winograd-rewrite.mlir
> +// CHECK:      %[[S15:.*]] = linalg.matmul ins(%[[S12]], %[[CST_4]] : tensor<6x3xf32>, tensor<3x6xf32>) outs(%14 : tensor<6x6xf32>) -> tensor<6x6xf32>
```suggestion
// CHECK:      %[[S13:.*]] = tensor.empty() : tensor<6x6xf32>
// CHECK:      %[[S14:.*]] = linalg.fill ins(%[[CST_6]] : f32) outs(%[[S13]] : tensor<6x6xf32>) -> tensor<6x6xf32>
// CHECK:      %[[S15:.*]] = linalg.matmul ins(%[[S12]], %[[CST_4]] : tensor<6x3xf32>, tensor<3x6xf32>) outs(%[[S14]] : tensor<6x6xf32>) -> tensor<6x6xf32>
```

2024-09-13 13:37 UTC, Max191 commented
> I've reduced the noise somewhat but adding the fill inevitably resequence quite a bit of SSA values. It also leads to some FileCheck variable reuse because not everything was renamed. Alternatively if you prefer I could do a NFC patch that just update all FileCheck variable like in my first attempt but doesn't have the fix. Then in a second patch I can add just the fix and the new CHECK and land that as a rebase rather than squash if that's possible in github.

It looks better now, so no worries. It is usually good to have more meaningful FileCheck variable names, but I probably should have caught that on the original PRs. It makes lit tests more readable and maintainable when the variables aren't just numbered ssa values (you don't need to do anything about that in this PR, just noting).

2024-09-13 14:48 UTC, merged