[libc++] Only include math implementation headers from `math.h`.
llvm/llvm-project pull request #109073
Opened 2024-09-18 00:41 UTC by var-const

`math.h` has logic for undefining macros that might be defined in the
C Standard Library. We need to make sure we do that prelude before
referring to any function names that might potentially be macros;
otherwise, valid user code that includes a macro-prone `<math.h>` from
the C Standard Library before including `<cmath>` (or a header that
transitively includes `<cmath>`) ends up broken.

2024-09-18 08:35 UTC, philnik777 requested changes
IMO `math.h` shouldn't include the special functions, since they don't belong there. Also, what is the failure mode here?
This code works perfectly fine:
```c++
void frexp();
#define frexp
#undef frexp
void func() {
  frexp();
}
```
I'm pretty sure we had a very similar patch previously and the failure mode never got explained.

2024-09-23 18:37 UTC, ldionne commented
@var-const Do you think that https://github.com/llvm/llvm-project/pull/94533 would solve this issue? I believe it would?

2025-01-09 20:30 UTC, philnik777 commented
@var-const Do you plan to keep pursuing this patch?

2025-01-09 20:47 UTC, var-const commented
@philnik777 Thanks for the reminder -- this fell off my radar. Closing, I don't think this is necessary anymore.

2025-01-09 20:47 UTC, closed without merging