[libc++][C++03] Update include guards
llvm/llvm-project pull request #109001
Opened 2024-09-17 15:56 UTC by philnik777

2024-09-17 15:57 UTC, philnik777 commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/109001?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#109002** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/109002?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#109001** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/109001?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#109000** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/109000?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#108999** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/108999?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @philnik777 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-10-30 15:17 UTC, ldionne reviewed
This looks good to me in principle, however the patch itself has a few incorrect renamings. One thing you could do is use `git diff --stat` to confirm that all the changed files have exactly 3 lines changed in them. A few headers like the C compat headers might need additional renames, that needs to be investigated.

2024-10-30 15:17 UTC, ldionne commented on libcxx/include/__cxx03/__algorithm/pstl.h
> +  _LIBCPP___CXX03_REQUIRE_CPP17_FORWARD_ITERATOR(_ForwardIterator, "any_of requires a ForwardIterator");
Oops!

2024-12-04 22:06 UTC, ldionne approved these changes

2024-12-04 22:08 UTC, ldionne requested changes
Oops, there are still many instances of `_LIBCPP___CXX03_REQUIRE_`

2024-12-09 15:04 UTC, ldionne approved these changes

2024-12-09 16:33 UTC, philnik777 commented
### Merge activity

* **Dec 9, 11:33 AM EST**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/llvm/llvm-project/109001).

2024-12-09 16:34 UTC, merged