[NFC] Add explicit #include abi-breaking.h where its macros are used.
llvm/llvm-project pull request #109453
Opened 2024-09-20 18:06 UTC by dfukalov

Without these explicit includes, removing other headers, who implicitly include `abi-breaking.h`, may have non-trivial side effects. For example, `clangd` may report even `abi-breaking.h` as "no used" in case it defines a macro, that is explicitly used with `#ifdef`. It is actually amplified with different build configs which use different set of macros.

2024-09-25 12:08 UTC, joker-eph requested changes
None of the MLIR changes are needed, we are covered by -Wundef I believe.

Also I feel we debated this before, but the PR description is still written in a way that is just completely confusing to me. Can you please rework all this?

2024-09-25 17:39 UTC, dwblaikie commented
> None of the MLIR changes are needed, we are covered by -Wundef I believe.

This patch seems to be an "include what you use" fix, which generally fix fragility (as the description says - cases where if an unrelated header was removed, the build would fail because the file that included the unrelated header was depending on that header providing some other header that's used). Looks like `-Wundef` would only protect from using a macro that's truly undefined, yeah?

> Also I feel we debated this before, but the PR description is still written in a way that is just completely confusing to me. Can you please rework all this?

I think I'm mostly following it - could you clarify what's confusing to you?

I will say I don't understand the second sentence ("For example, clangd may report even abi-breaking.h as "no used" in case it defines a macro, that is explicitly used with #ifdef."). ooh, actually, I think I follow - clangd could identify abi-breaking.h as unused in some other header x.h (because clangd would do a local analysis, and find abi-breaking.h unused in x.h), even though the macros are used from from some other file that /includes/ x.h.

2024-09-25 20:46 UTC, joker-eph commented
> This patch seems to be an "include what you use" fix, which generally fix fragility (as the description says - cases where if an unrelated header was removed, the build would fail because the file that included the unrelated header was depending on that header providing some other header that's used). Looks like -Wundef would only protect from using a macro that's truly undefined, yeah?

Do you believe that any change in MLIR is protecting us from anything not covered by Wunder? If so can you describe the possible failure here?


> I think I'm mostly following it - could you clarify what's confusing to you?


Everythig about clangd: the sentence starts with "for example" as if it is an important illustration from "removing other headers, who implicitly include abi-breaking.h, may have non-trivial side effects".

I don't quite see how "removing abi-breaking.h"  can have as "side-effect" the fact that "clangd may report even abi-breaking.h as "no used" "

2024-09-25 21:05 UTC, dwblaikie commented
> > This patch seems to be an "include what you use" fix, which generally fix fragility (as the description says - cases where if an unrelated header was removed, the build would fail because the file that included the unrelated header was depending on that header providing some other header that's used). Looks like -Wundef would only protect from using a macro that's truly undefined, yeah?
> 
> Do you believe that any change in MLIR is protecting us from anything not covered by Wunder? If so can you describe the possible failure here?

My expectation is that these changes would avoid a correct header removal from causing a build break under `-Wundef`. Means folks can remove unused headers without the spooky-action-at-a-distance cleanup required.

> 
> > I think I'm mostly following it - could you clarify what's confusing to you?
> 
> Everythig about clangd: the sentence starts with "for example" as if it is an important illustration from "removing other headers, who implicitly include abi-breaking.h, may have non-trivial side effects". I don't quite see how "removing abi-breaking.h" can have as "side-effect" the fact that "clangd may report even abi-breaking.h as "no used" "
> 
> (You're touching on this: this is most of the description though!)

Looks like we agree on this, more or less.

> In general a description that is simply saying "IWYU / Without these includes, removing other headers, who implicitly include xxxx.h, may have non-trivial side effects" looks to me like a negation of LLVM policy about "including the minimum needed".

Not relying on implicit/indirect dependencies seems to me consistent with LLVM's policy. The https://llvm.org/docs/CodingStandards.html#include-as-little-as-possible is about avoiding the inclusion entirely (to reduce total preprocessed bytes), when an include can be replaced by a forward declaration, etc. That's not the case we're talking about here - where the inclusion is needed, but is relied upon indirectly.

Admittedly the policy here does allow indirect dependencies, but doesn't encourage or discourage it: "You must include all of the header files that you are using — you can include them either directly or indirectly through another header file." - though C++ and C style in general would be that explicit inclusion is preferred for maintainability (so there's no spooky-action-at-a-distance cleanup when someone removes a header that isn't used directly (from the user or the usee, as it were)).

2024-09-25 21:36 UTC, joker-eph commented
> My expectation is that these changes would avoid a correct header removal from causing a build break under -Wundef. Means folks can remove unused headers without the spooky-action-at-a-distance cleanup required.

If this is really the problem to be solved, then this is what the description should explain clearly, and we can argue about it :)


Right now it seems that you're arguing against the policy of " You must include all of the header files that you are using — you can include them either directly or indirectly through another header file" ; so I'd rather first see a PR that rewrite this to endorse the policy you want to see in place (probably with an RFC on Discourse).

2024-09-25 22:03 UTC, dfukalov commented
> None of the MLIR changes are needed, we are covered by -Wundef I believe.
> 
There are some places in MLIR where the option will not work, e.g.
https://github.com/llvm/llvm-project/blob/fe06a6daae6be85d47cd1e51654e91f9ac6e63d7/mlir/include/mlir/Dialect/Transform/Interfaces/TransformInterfaces.h#L199
, since `-Wundef` works for `#if` only, not for `#ifdef`.

We have no coding style requirement of the topic **and** pre-commit tests/checks. While we have no such requirements, the macros which configure compilation still be fragile.

2024-09-25 22:08 UTC, dwblaikie commented
> > None of the MLIR changes are needed, we are covered by -Wundef I believe.
> 
> There are some places in MLIR where the option will not work, e.g.
> 
> https://github.com/llvm/llvm-project/blob/fe06a6daae6be85d47cd1e51654e91f9ac6e63d7/mlir/include/mlir/Dialect/Transform/Interfaces/TransformInterfaces.h#L199
> 
> 
> , since `-Wundef` works for `#if` only, not for `#ifdef`.
> We have no coding style requirement of the topic **and** pre-commit tests/checks. While we have no such requirements, the macros which configure compilation still be fragile.

I guess that usage is just buggy/incorrect, unfortunately (unfortunately in terms of this not providing any extra motivation for this proposed patch, I think) - ifdef abi_breaking_checks will be true even when abi_breaking_checks is disabled (because it'll be disabled by being defined to 0, so ifdef will still be true because it is defined (albeit to 0))

2024-09-26 23:09 UTC, joker-eph commented
Thanks, fixing in https://github.com/llvm/llvm-project/pull/110185 FYI

2025-03-25 12:40 UTC, closed without merging