[mlir][AMDGPU] Add a scheduling barrier guard around inlineAsm lds.barrier
llvm/llvm-project pull request #109678
Opened 2024-09-23 15:42 UTC by dhernandez0

This commit adds a scheduling region around the inlineAsm to guard against possible complications arising from them interfering with the backend scheduler / register allocation.

CC: @manupak @krzysz00

2024-09-23 16:28 UTC, arsenm reviewed
This makes no sense. Asm should not be used and is already the strongest barrier

2024-09-23 16:34 UTC, manupak commented
> Asm should not be used

I dont think this PR introduces the asm. 
here is the context :  https://github.com/llvm/llvm-project/pull/77942

2024-09-23 17:47 UTC, krzysz00 commented
And re "asm should not be used" - this is the "trust me, we specifically don't want to wait on global memory to complete at the barrier because we're doing software pipelining" barrier where we're by-hand mitigating the effects of `BackOffBarrier` not being set (even though it breaks debugging, hence the warning).

This rewrite only uses ASM on the architectures where you need to use inline ASM to get that effect

2024-09-24 05:42 UTC, arsenm requested changes
You're turning one scheduling barrier into 3, and I see no reason to do this. Do you have an example where this manifests in a real codegen difference?

2024-09-25 11:41 UTC, dhernandez0 commented
> You're turning one scheduling barrier into 3, and I see no reason to do this. Do you have an example where this manifests in a real codegen difference?

In the zip file you will find "pass.ll" and "failure.ll". The difference between pass and failure is that pass.ll was generated with the changes proposed in this PR.
[asm_failure.zip](https://github.com/user-attachments/files/17130134/asm_failure.zip)

If I run the following command:
```bash
llc -mtriple=amdgcn-amd-amdhsa -mattr=+sramecc,-xnack -mcpu=gfx908 -O3 -o pass.o asm_failure/failure.ll
```
Compilation fails while it works for pass.ll:

```
llc: /home/danherna/mlir-dev/rocMLIR/external/llvm-project/llvm/lib/CodeGen/SplitKit.cpp:1661: void llvm::SplitEditor::splitLiveThroughBlock(unsigned int, unsigned int, SlotIndex, unsigned int, SlotIndex): Assertion `(!LeaveBefore || Idx <= LeaveBefore) && "Interference"' failed.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.      Program arguments: ../external/llvm-project/build/bin/llc -mtriple=amdgcn-amd-amdhsa -mattr=+sramecc,-xnack -mcpu=gfx908 -O3 -o failure.o asm_failure/failure.ll
1.      Running pass 'CallGraph Pass Manager' on module 'asm_failure/failure.ll'.
2.      Running pass 'Greedy Register Allocator' on function '@rock_gemm'
 #0 0x00005595081f6b15 ___interceptor_backtrace (../external/llvm-project/build/bin/llc+0x7de5b15)
 #1 0x000055950e59ba80 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) /home/danherna/mlir-dev/rocMLIR/external/llvm-project/llvm/lib/Support/Unix/Signals.inc:727:8
 #2 0x000055950e594e26 llvm::sys::RunSignalHandlers() /home/danherna/mlir-dev/rocMLIR/external/llvm-project/llvm/lib/Support/Signals.cpp:0:5
 #3 0x000055950e59d168 SignalHandler(int) /home/danherna/mlir-dev/rocMLIR/external/llvm-project/llvm/lib/Support/Unix/Signals.inc:0:3
 #4 0x00007fb588ad1420 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x14420)
 #5 0x00007fb58857800b raise (/lib/x86_64-linux-gnu/libc.so.6+0x4300b)
 #6 0x00007fb588557859 abort (/lib/x86_64-linux-gnu/libc.so.6+0x22859)
 #7 0x00007fb588557729 (/lib/x86_64-linux-gnu/libc.so.6+0x22729)
 #8 0x00007fb588568fd6 (/lib/x86_64-linux-gnu/libc.so.6+0x33fd6)
 #9 0x000055950bb6a226 llvm::SplitEditor::splitLiveThroughBlock(unsigned int, unsigned int, llvm::SlotIndex, unsigned int, llvm::SlotIndex) /home/danherna/mlir-dev/rocMLIR/external/llvm-project/llvm/lib/CodeGen/SplitKit.cpp:1661:5
#10 0x000055950b8f6fc3 llvm::RAGreedy::splitAroundRegion(llvm::LiveRangeEdit&, llvm::ArrayRef<unsigned int>) /home/danherna/mlir-dev/rocMLIR/external/llvm-project/llvm/lib/CodeGen/RegAllocGreedy.cpp:0:11
#11 0x000055950b8fa62f ~LiveRangeEdit /home/danherna/mlir-dev/rocMLIR/external/llvm-project/llvm/include/llvm/CodeGen/LiveRangeEdit.h:138:29
#12 0x000055950b8fa62f llvm::RAGreedy::doRegionSplit(llvm::LiveInterval const&, unsigned int, bool, llvm::SmallVectorImpl<llvm::Register>&) /home/danherna/mlir-dev/rocMLIR/external/llvm-project/llvm/lib/CodeGen/RegAllocGreedy.cpp:1227:1
#13 0x000055950b8f9218 llvm::RAGreedy::tryRegionSplit(llvm::LiveInterval const&, llvm::AllocationOrder&, llvm::SmallVectorImpl<llvm::Register>&) /home/danherna/mlir-dev/rocMLIR/external/llvm-project/llvm/lib/CodeGen/RegAllocGreedy.cpp:1091:1
#14 0x000055950b907960 llvm::RAGreedy::trySplit(llvm::LiveInterval const&, llvm::AllocationOrder&, llvm::SmallVectorImpl<llvm::Register>&, llvm::SmallSet<llvm::Register, 16u, std::less<llvm::Register>> const&) /home/danherna/mlir-dev/rocMLIR/external/llvm-project/llvm/lib/CodeGen/RegAllocGreedy.cpp:1826:9
#15 0x000055950b90e087 llvm::RAGreedy::selectOrSplitImpl(llvm::LiveInterval const&, llvm::SmallVectorImpl<llvm::Register>&, llvm::SmallSet<llvm::Register, 16u, std::less<llvm::Register>>&, llvm::SmallVector<std::pair<llvm::LiveInterval const*, llvm::MCRegister>, 8u>&, unsigned int) /home/danherna/mlir-dev/rocMLIR/external/llvm-project/llvm/lib/CodeGen/RegAllocGreedy.cpp:0:24
#16 0x000055950b90f339 llvm::RAGreedy::selectOrSplit(llvm::LiveInterval const&, llvm::SmallVectorImpl<llvm::Register>&) /home/danherna/mlir-dev/rocMLIR/external/llvm-project/llvm/lib/CodeGen/RegAllocGreedy.cpp:0:7
#17 0x000055950b863dd0 llvm::RegAllocBase::allocatePhysRegs() /home/danherna/mlir-dev/rocMLIR/external/llvm-project/llvm/lib/CodeGen/RegAllocBase.cpp:115:9
#18 0x000055950b91b4df llvm::RAGreedy::runOnMachineFunction(llvm::MachineFunction&) /home/danherna/mlir-dev/rocMLIR/external/llvm-project/llvm/lib/CodeGen/RegAllocGreedy.cpp:2770:3
#19 0x000055950b218634 llvm::MachineFunctionPass::runOnFunction(llvm::Function&) /home/danherna/mlir-dev/rocMLIR/external/llvm-project/llvm/lib/CodeGen/MachineFunctionPass.cpp:0:13
#20 0x000055950c37623d llvm::FPPassManager::runOnFunction(llvm::Function&) /home/danherna/mlir-dev/rocMLIR/external/llvm-project/llvm/lib/IR/LegacyPassManager.cpp:1442:27
#21 0x000055950a1272a5 RunPassOnSCC /home/danherna/mlir-dev/rocMLIR/external/llvm-project/llvm/lib/Analysis/CallGraphSCCPass.cpp:180:25
#22 0x000055950a1272a5 RunAllPassesOnSCC /home/danherna/mlir-dev/rocMLIR/external/llvm-project/llvm/lib/Analysis/CallGraphSCCPass.cpp:470:9
#23 0x000055950a1272a5 (anonymous namespace)::CGPassManager::runOnModule(llvm::Module&) /home/danherna/mlir-dev/rocMLIR/external/llvm-project/llvm/lib/Analysis/CallGraphSCCPass.cpp:535:18
#24 0x000055950c3780cf runOnModule /home/danherna/mlir-dev/rocMLIR/external/llvm-project/llvm/lib/IR/LegacyPassManager.cpp:0:27
#25 0x000055950c3780cf llvm::legacy::PassManagerImpl::run(llvm::Module&) /home/danherna/mlir-dev/rocMLIR/external/llvm-project/llvm/lib/IR/LegacyPassManager.cpp:542:44
#26 0x000055950829d705 compileModule(char**, llvm::LLVMContext&) /home/danherna/mlir-dev/rocMLIR/external/llvm-project/llvm/tools/llc/llc.cpp:0:8
#27 0x0000559508296da0 main /home/danherna/mlir-dev/rocMLIR/external/llvm-project/llvm/tools/llc/llc.cpp:409:13
#28 0x00007fb588559083 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x24083)
#29 0x00005595081b206e _start (../external/llvm-project/build/bin/llc+0x7da106e)
Aborted (core dumped)
```

2024-09-25 12:31 UTC, arsenm commented
> Compilation fails while it works for pass.ll:

This is just a bug, and this patch in no way works around it. This may be hidden or exposed by just about any code perturbation 

> 
> ```
> llc: /home/danherna/mlir-dev/rocMLIR/external/llvm-project/llvm/lib/CodeGen/SplitKit.cpp:1661: void llvm::SplitEditor::splitLiveThroughBlock(unsigned int, unsigned int, SlotIndex, unsigned int, SlotIndex): Assertion `(!LeaveBefore || Idx <= LeaveBefore) && "Interference"' failed.

This is #109294, but this test case is much simpler than the current one. I'll see if this one reduces any better

2024-09-25 12:37 UTC, manupak commented
Ack... then we dont need that if thats being fixed.

2024-09-25 12:43 UTC, dhernandez0 commented
> > Compilation fails while it works for pass.ll:
> 
> This is just a bug, and this patch in no way works around it. This may be hidden or exposed by just about any code perturbation
> 
> > ```
> > llc: /home/danherna/mlir-dev/rocMLIR/external/llvm-project/llvm/lib/CodeGen/SplitKit.cpp:1661: void llvm::SplitEditor::splitLiveThroughBlock(unsigned int, unsigned int, SlotIndex, unsigned int, SlotIndex): Assertion `(!LeaveBefore || Idx <= LeaveBefore) && "Interference"' failed.
> > ```
> 
> This is #109294, but this test case is much simpler than the current one. I'll see if this one reduces any better

Thanks for clarifying this. Closing PR.

2024-09-25 12:43 UTC, closed without merging