Update correct dependency
llvm/llvm-project pull request #109937
Opened 2024-09-25 09:37 UTC by Akshat-Oke

2024-09-25 09:37 UTC, Akshat-Oke commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/109937?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#109939** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/109939?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#109938** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/109938?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#109937** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/109937?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#109936** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/109936?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @Akshat-Oke and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-09-25 11:42 UTC, arsenm reviewed
Description needs to be more specific

2024-10-07 17:14 UTC, arsenm commented
> Description needs to be more specific

Bump

2024-10-09 06:38 UTC, Akshat-Oke commented
ping

2024-10-09 06:52 UTC, arsenm commented
> ping

Fix the description

2024-10-14 10:25 UTC, optimisan commented
Also updated in PR.
Initializes correct dependency as VirtRegMapWrapper is unused here

2024-10-14 11:13 UTC, arsenm requested changes
Description still not fixed

2024-10-21 17:23 UTC, arsenm approved these changes

2024-10-22 09:41 UTC, optimisan commented
### Merge activity

* **Oct 22, 5:41 AM EDT**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/llvm/llvm-project/109937).

2024-10-22 09:50 UTC, merged