Support BasedOnStyle referencing an arbitrary file
llvm/llvm-project pull request #110634
Opened 2024-10-01 07:16 UTC by jediry

This change adds support for clang-format's BasedOnStyle to reference an explicit, arbitrary file, using syntax like:

```BasedOnStyle: file:../../format/my-team.clang-format```
or
```BasedOnStyle: file:$(CLANG_FORMAT_DIR)/my-team.clang-format```

In the first form, the string after ```file:``` is treated as a path relative to the current .clang-format file. In the second, when the path starts with the string ```$(CLANG_FORMAT_DIR)```, the value of the CLANG_FORMAT_DIR environment variable (which must be defined and must identify a readable directory) is substituted. For security reasons (and because it's likely not that useful anyway), absolute paths are not supported.

The .clang-format file referenced in this way may itself use ```BasedOnStyle: file:``` to include another file, or ```BasedOnStyle: InheritParentConfig```, in which case the parent config file is searched upward, starting from the included file.

2024-10-02 13:13 UTC, mydeveloperday requested changes
Can this have some unit test?

2024-10-08 21:49 UTC, jediry commented
> Can this have some unit test?

Done. Added docs as well.

2024-10-15 22:50 UTC, jediry commented
Ping

2024-10-21 22:59 UTC, jediry commented
Ping @mydeveloperday @owenca

2024-10-23 07:30 UTC, owenca commented
Please see https://github.com/llvm/llvm-project/issues/107808#issuecomment-2431139406.

2026-03-28 21:39 UTC, closed without merging

2026-03-28 21:39 UTC, HazardyKnusperkeks commented
Superseeded by #182791.