Propagate IsText parameter to openFileForRead function
llvm/llvm-project pull request #110661
Opened 2024-10-01 12:59 UTC by abhina-sree

This patch adds an IsText parameter to the following functions openFileForRead, getBufferForFile, getBufferForFileImpl. The default is set to OF_Text instead of OF_None, this change in value does not affect any other platforms other than z/OS. Setting this parameter correctly is required to open files on z/OS in the correct encoding.

2024-10-01 13:27 UTC, kadircet requested changes
sorry this is same as https://github.com/llvm/llvm-project/pull/107906 (with a bigger impact radius, as you're also changing getBufferForFile) and doesn't address any of the issues mention about explaining the semantics of `IsText` or justification for changing the core VFS interfaces, for an operation that's can solely be performed on physical fileystem.

@perry-ca raised some concerns in https://github.com/llvm/llvm-project/pull/109664 about this functionality requiring some context awareness, I don't think any of those is addressed by this patch either. Pretty much all of the callers apart from ASTReader is just using `IsText = true`.

2024-10-01 15:26 UTC, abhina-sree commented
> > @perry-ca raised some concerns in #109664 about this functionality requiring some context awareness, I don't think any of those is addressed by this patch either. Pretty much all of the callers apart from ASTReader is just using `IsText = true`.
> 
> It just happens that 90% of the time you are dealing with text files. As you noted, in the context of the ASTReader, the file being read is expected to be a binary file. In that case the parameter is false.
> 
> These change mirror interface to `getFileOrSTDIN()` which has a IsText parameter. This does touch a number of places but I feel the changes are in line with the rest of the file I/O functions in llvm.

Yes, I agree with Sean. Most of the time it is a text file when this function is called, there are only a few places where we expect binary files. And the reason for changing in VirtualFileSystem.cpp is because this is where the OF_None flag is being passed unconditionally, and there are other parameters like RequiresNullTerminator and IsVolatile that are being passed here as well which is why it seems like the correct place

2024-10-02 16:30 UTC, cor3ntin commented
> sorry this is same as #107906 (with a bigger impact radius, as you're also changing getBufferForFile) and doesn't address any of the issues mention about explaining the semantics of `IsText` or justification for changing the core VFS interfaces, for an operation that's can solely be performed on physical fileystem.
> 
> @perry-ca raised some concerns in #109664 about this functionality requiring some context awareness, I don't think any of those is addressed by this patch either. Pretty much all of the callers apart from ASTReader is just using `IsText = true`.

To give some context, the problem we are trying to solve initially is that file opened by `#embed` should not be utf-8 converted.

2024-10-02 17:13 UTC, perry-ca commented
> > sorry this is same as #107906 (with a bigger impact radius, as you're also changing getBufferForFile) and doesn't address any of the issues mention about explaining the semantics of `IsText` or justification for changing the core VFS interfaces, for an operation that's can solely be performed on physical fileystem.
> > @perry-ca raised some concerns in #109664 about this functionality requiring some context awareness, I don't think any of those is addressed by this patch either. Pretty much all of the callers apart from ASTReader is just using `IsText = true`.
> 
> To give some context, the problem we are trying to solve initially is that file opened by `#embed` should not be utf-8 converted.

Correct.  The overall/original problem is that we have many places where text files were being read as binary files.  Adding the IsText parameter to the openFileForRead() function just like we have in the getFileOrStdin() group of functions solves that problem.  It tells the compiler to read files that should be text as text and binary as binary.

2024-10-02 17:27 UTC, abhina-sree commented
> > sorry this is same as #107906 (with a bigger impact radius, as you're also changing getBufferForFile) and doesn't address any of the issues mention about explaining the semantics of `IsText` or justification for changing the core VFS interfaces, for an operation that's can solely be performed on physical fileystem.
> > @perry-ca raised some concerns in #109664 about this functionality requiring some context awareness, I don't think any of those is addressed by this patch either. Pretty much all of the callers apart from ASTReader is just using `IsText = true`.
> 
> To give some context, the problem we are trying to solve initially is that file opened by `#embed` should not be utf-8 converted.

Thanks, I've tested the `#embed` lit tests with this fix and did not see any regressions

2024-10-07 08:29 UTC, kadircet commented
Sorry for not responding here for a while.

> These change mirror interface to getFileOrSTDIN() which has a IsText parameter. This does touch a number of places but I feel the changes are in line with the rest of the file I/O functions in llvm.

I think there's a huge difference between `getFileOrSTDIN` and `llvm::vfs::FileSystem` interfaces. The former has a single implementation that's meant to always work with a physical filesytem. The latter has many implementations and is meant to decouple physical filesystem, we're now leaking that abstraction solely because physical system is trying to receive some information.

> Thanks, I've tested the #embed lit tests with this fix and did not see any regressions

I am still wary of this. Logic that handles #embed directives lives in https://github.com/llvm/llvm-project/blob/main/clang/lib/Lex/PPDirectives.cpp#L3964-L3990. As you can see, all of them use the default filemanager/filesystem interfaces, which will read this file with `IsText = true` after this patch.

---

All of that being said;

If you folks are in alignment with this being required, I think we should still make it as least intrusive to rest of the users of this interface as possible.

Looks like this only has affects on `RealFileSystem` implementation (and probably isn't really useful for the rest anyways).

Can we at least change the implementation here to:
- Introduce a new virtual methods called `openFileForReadBinary` and `getBufferForFileBinary` into `llvm::vfs::Filesystem`. Make default implementations just delegate to `openFileForRead` and `getBufferForFile`. Explain when the binary specific overloads should be preferred and how the default versions assume operating on text files in the comments for these methods.
- Override these new methods in `RealFileSystem` to pass different flags to underlying calls
- Make sure place like #embed handling and astreader calls the `read-binary` versions of these methods.

2024-10-09 17:32 UTC, abhina-sree commented
> The default is set to OF_Text instead of OF_None, this change in value does not affect any other platforms other than z/OS. Setting this parameter correctly is required to open files on z/OS in the correct encoding. The IsText parameter is based on the context of where we open files, for example, the embed directive requires that files always be opened in binary even though they might be tagged as text.

Thanks for your patience. I've put up this PR https://github.com/llvm/llvm-project/pull/111723 to implement your suggestion. I kept the IsText parameter in the getBufferForFile, getBufferForFileImpl because it already has other attributes like IsVolatile, RequiresNullTerminator but created a new virtual function for openFileForReadBinary which greatly reduces the number of files touched compared to this PR. The current `#embed` lit tests seem to work without additional changes but I will experiment with creating a testcase with inputs that are non-ascii to expose any issues

2024-10-21 12:20 UTC, closed without merging