[clang][HLSL] Add radians intrinsic
llvm/llvm-project pull request #110802
Opened 2024-10-02 08:34 UTC by adam-yang

partially fixes #99151

### Changes
* Implemented `radians` clang builtin
* Linked `radians` clang builtin with `hlsl_intrinsics.h`
* Added sema checks for `radians` to `CheckHLSLBuiltinFunctionCall` in `SemaChecking.cpp`
* Add codegen for `radians` to `EmitHLSLBuiltinExpr` in `CGBuiltin.cpp`
* Add codegen tests to `clang/test/CodeGenHLSL/builtins/radians.hlsl`
* Add sema tests to `clang/test/SemaHLSL/BuiltIns/radians-errors.hlsl`

### Related PRs
* [[DXIL] Add radians intrinsic #110616](https://github.com/llvm/llvm-project/pull/110616)
* [[SPIRV] Add radians intrinsic #110800](https://github.com/llvm/llvm-project/pull/110800)

2024-10-02 19:40 UTC, farzonl commented on clang/lib/CodeGen/CGBuiltin.cpp
> +    if (!E->getArg(0)->getType()->hasFloatingRepresentation())
Line 1864 of  `SemaHLSL.cpp` you have a check for this, Turn this into an assert.

2024-10-02 19:42 UTC, farzonl commented on clang/test/SemaHLSL/BuiltIns/radians-errors.hlsl
> +
There is a file called `clang\test\SemaHLSL\BuiltIns\half-float-only-errors.hlsl` Add `__builtin_hlsl_elementwise_radians` to that file.

2024-10-02 19:42 UTC, farzonl approved these changes

2024-10-02 19:48 UTC, farzonl requested changes
Please run clang-format

2024-10-04 21:46 UTC, spall approved these changes
LGTM but I didn't look too closely at the tests.

2024-10-04 22:18 UTC, adam-yang commented
@farzonl This is also ready for merging if there's no further feedback.

2024-10-04 22:34 UTC, farzonl approved these changes

2024-10-04 22:34 UTC, merged