[X86] Add AMD Llano family detection
llvm/llvm-project pull request #111312
Opened 2024-10-06 21:12 UTC by RipleyTom

Very simple one liner, adds the missing detection for the Llano family which is essentially a refreshed K10:
Documentation of the family id: https://en.wikichip.org/wiki/amd/cpuid#Family_18_.2812h.29
Documentation that it fits into amdfam10: https://en.wikipedia.org/wiki/AMD_10h#12h

2024-10-06 22:02 UTC, boomanaiden154 requested changes
This patch needs to be mirrored in `compiler-rt/lib/builtins/cpu_model/x86.c`.

2024-10-07 03:08 UTC, ganeshgit commented
LGTM!

2024-10-07 10:30 UTC, RKSimon approved these changes

2024-10-07 15:33 UTC, boomanaiden154 approved these changes
(Merging given this is a new contributor that can't merge themselves).

2024-10-07 15:33 UTC, merged