GVN: generalize impliesEquivalence (NFC)
llvm/llvm-project pull request #111416
Opened 2024-10-07 18:16 UTC by artagnon

impliesEquivalenceIfTrue and impliesEquivalenceIfFalse can be extended to aggregates easily, although as the added tests show, the codepath cannot be exercised: GVN does not propogate values through a vector-select. Generalize the code anyway, as it opens up opportunities for optimizing GVN. While at it, note that the optimization is invalid for the no-signed-zeros case, and strip the bad FIXME.

 Alive2 proof: https://alive2.llvm.org/ce/z/vEaK8M

-- 8< --
Based on #111365.

2024-10-08 15:50 UTC, nikic requested changes
I agree that doing the transform with nsz wouldn't be valid, given its peculiar semantics.

However, `!isZeroValue` does not imply that the value isn't zero. It could either be a vector that has zero elements (but is not entirely zero) or a constant expression that evaluates to zero.

Additionally, when it comes to replacements based on vector comparisons you have to be quite careful, because they are only legal if no cross-lane operations are involved.

If we wanted to do the select fold, we'd do this in InstCombine rather than GVN. InstCombine already does this for integer comparisons, but not float comparisons.

2024-10-09 13:35 UTC, artagnon commented
> If we wanted to do the select fold, we'd do this in InstCombine rather than GVN. InstCombine already does this for integer comparisons, but not float comparisons.

Not sure what you mean, because InstCombine doesn't seem to work here: https://godbolt.org/z/5b36ccK9j. Proof: https://alive2.llvm.org/ce/z/Lr6jqc. If we change the `udiv` to an `add`, InstCombine has some special code for folding select-icmp-and-add. Is it within the scope of InstCombine to do GVN-like replacements, and not really "combine" or "fold" anything?

2024-10-09 13:45 UTC, nikic commented
See https://github.com/llvm/llvm-project/blob/7d9f9938ff788aa7565c61ce6f391264750515af/llvm/lib/Transforms/InstCombine/InstCombineSelect.cpp#L1320 for the relevant transform. Your code uses udiv, which is non-speculatable, so the transform is generally unsafe. And it uses vectors, which are not fully supported for the reason I mentioned previously.

2024-10-10 10:28 UTC, artagnon commented
I hope I've addressed the points correctly now. Currently working on a patch for InstCombine.

2024-11-04 17:37 UTC, closed without merging