[clang][RISCV] Extend intrinsic size check variable from 16 -> 32 bits. NFC
llvm/llvm-project pull request #111481
Opened 2024-10-08 05:04 UTC by 4vtomat

We currently have over 67000 intrinsics, uint16_t will overflow.

2024-10-08 05:13 UTC, topperc reviewed
Why doesn't any test catch it?

2024-10-08 05:19 UTC, jerryzj commented
> Why doesn't any test catch it?

I suppose the [CI](https://github.com/riscv-non-isa/rvv-intrinsic-doc/actions/runs/11216383892/job/31175562939) of intrinsic doc should catch this, but it is not reporting errors as expected.
I happen to notice the failures and working on a fix now.

2024-10-08 06:42 UTC, wangpc-pp approved these changes
LGTM.

2024-10-08 07:33 UTC, topperc commented
Why don’t any of our lit tests that use every intrinsic catch it?

2024-10-08 07:38 UTC, topperc commented on clang/lib/Sema/SemaRISCV.cpp
> +  uint32_t Index = IntrinsicList.size();
What is the type of Intrinsics on this line further down

```
Intrinsics.insert({Name, Index});
```

2024-10-08 08:02 UTC, wangpc-pp commented
> Why don’t any of our lit tests that use every intrinsic catch it?

We don't see any error, is it because your downstream added some intrinsics?

2024-10-08 08:13 UTC, topperc commented
Does the number intrinsics vary with the number of extensions enabled? Maybe we don't have a test with all extensions?

2024-10-08 15:52 UTC, 4vtomat commented
> Why don’t any of our lit tests that use every intrinsic catch it?

Somehow if we add more "target-feature" the intrinsics increase, I'm not sure why.
For example:
```
test.c

#include "riscv_vector.h"
  vfloat16mf4x7_t test_vlseg7e16ff_v_f16mf4x7(const _Float16 *base, size_t *new_vl, size_t vl) {
  return __riscv_vlseg7e16ff_v_f16mf4x7(base, new_vl, vl);
}
```
Compile with this command:
```
clang -cc1 -triple riscv64-- -S -target-feature +v -target-feature +zvfh -target-abi lp64d test.c
```
generate 61674 intrinsics.
However if we add `-target-feature +zvfbfmin`
```
clang -cc1 -triple riscv64-- -S -target-feature +v -target-feature +zvfh -target-feature +zvfbfmin -target-abi lp64d test.c
```
generate 64568 intrinsics

it's weird.

2024-10-08 16:37 UTC, topperc commented
> > Why don’t any of our lit tests that use every intrinsic catch it?
> 
> Somehow if we add more "target-feature" the intrinsics increase, I'm not sure why. For example:
> 
> ```
> test.c
> 
> #include "riscv_vector.h"
>   vfloat16mf4x7_t test_vlseg7e16ff_v_f16mf4x7(const _Float16 *base, size_t *new_vl, size_t vl) {
>   return __riscv_vlseg7e16ff_v_f16mf4x7(base, new_vl, vl);
> }
> ```
> 
> Compile with this command:
> 
> ```
> clang -cc1 -triple riscv64-- -S -target-feature +v -target-feature +zvfh -target-abi lp64d test.c
> ```
> 
> generate 61674 intrinsics. However if we add `-target-feature +zvfbfmin`
> 
> ```
> clang -cc1 -triple riscv64-- -S -target-feature +v -target-feature +zvfh -target-feature +zvfbfmin -target-abi lp64d test.c
> ```
> 
> generate 64568 intrinsics
> 
> it's weird.

Why is it weird? Some intrinsics require specific features. If that feature isn't enabled, the intrinsic is skipped.

2024-10-08 16:45 UTC, 4vtomat commented
> > > Why don’t any of our lit tests that use every intrinsic catch it?
> 
> > 
> 
> > Somehow if we add more "target-feature" the intrinsics increase, I'm not sure why. For example:
> 
> > 
> 
> > ```
> 
> > test.c
> 
> > 
> 
> > #include "riscv_vector.h"
> 
> >   vfloat16mf4x7_t test_vlseg7e16ff_v_f16mf4x7(const _Float16 *base, size_t *new_vl, size_t vl) {
> 
> >   return __riscv_vlseg7e16ff_v_f16mf4x7(base, new_vl, vl);
> 
> > }
> 
> > ```
> 
> > 
> 
> > Compile with this command:
> 
> > 
> 
> > ```
> 
> > clang -cc1 -triple riscv64-- -S -target-feature +v -target-feature +zvfh -target-abi lp64d test.c
> 
> > ```
> 
> > 
> 
> > generate 61674 intrinsics. However if we add `-target-feature +zvfbfmin`
> 
> > 
> 
> > ```
> 
> > clang -cc1 -triple riscv64-- -S -target-feature +v -target-feature +zvfh -target-feature +zvfbfmin -target-abi lp64d test.c
> 
> > ```
> 
> > 
> 
> > generate 64568 intrinsics
> 
> > 
> 
> > it's weird.
> 
> 
> 
> Why is it weird? Some intrinsics require specific features. If that feature isn't enabled, the intrinsic is skipped.

Oh I see, but if we extend the size, the memory usage will grow.

2024-10-15 17:45 UTC, topperc requested changes
I think we need to change

```
struct RVVOverloadIntrinsicDef {
  // Indexes of RISCVIntrinsicManagerImpl::IntrinsicList.
  SmallVector<uint16_t, 8> Indexes;
};
```
and

``` 
  // Mapping function name to index of IntrinsicList.
  StringMap<uint16_t> Intrinsics;
```

Those places were both changed by e0092eae431956a2fd17f7ea88e7ba26d5e44f7e

2024-10-17 03:58 UTC, 4vtomat commented
> I think we need to change
> 
> ```
> struct RVVOverloadIntrinsicDef {
>   // Indexes of RISCVIntrinsicManagerImpl::IntrinsicList.
>   SmallVector<uint16_t, 8> Indexes;
> };
> ```
> 
> and
> 
> ```
>   // Mapping function name to index of IntrinsicList.
>   StringMap<uint16_t> Intrinsics;
> ```
> 
> Those places were both changed by [e0092ea](https://github.com/llvm/llvm-project/commit/e0092eae431956a2fd17f7ea88e7ba26d5e44f7e) in addition to the place you've currently changed.

Oh, nice catch! I didn't even remember I've changed this before lol~

2024-10-17 18:11 UTC, topperc approved these changes
LGTM

2024-10-18 18:33 UTC, goldsteinn commented
Can this get merged?

2024-10-18 18:36 UTC, merged