[RISCV] Add support for inline asm constraint vd
llvm/llvm-project pull request #111653
Opened 2024-10-09 09:27 UTC by tclin914

It constrains vector registers excluding v0.

This patch also adds a testcase for constraints vr, vd and vm.

2024-10-09 12:51 UTC, lenary commented
I think you've missed making the relevant clang changes to `RISCVTargetInfo::validateAsmConstraint` to support `vd`.

I don't understand why this constraint is needed but it's good to stay in line with GCC.

2024-10-11 08:17 UTC, lenary approved these changes
LGTM

2024-10-11 17:03 UTC, topperc requested changes

2024-10-11 17:03 UTC, topperc commented on clang/lib/Basic/Targets/RISCV.cpp
> +    if (Name[1] == 'r' || Name[1] == 'd' || Name[1] == 'm') {
This needs to be tested in clang/test/CodeGen/RISCV/riscv-inline-asm-rvv.c

2024-10-11 18:18 UTC, lenary commented on clang/test/CodeGen/RISCV/riscv-inline-asm-rvv.c
> +  asm volatile ("vadd.vv %0, %1, %2" : "=vd"(ret) : "vd"(a), "vd"(b));
@topperc is this test not enough?

2024-10-11 21:24 UTC, topperc commented on clang/test/CodeGen/RISCV/riscv-inline-asm-rvv.c
> +  asm volatile ("vadd.vv %0, %1, %2" : "=vd"(ret) : "vd"(a), "vd"(b));
weird how did i not see that was here.

2024-10-11 21:24 UTC, topperc approved these changes
LGTM

2024-10-11 21:32 UTC, topperc commented on clang/lib/Basic/Targets/RISCV.cpp
> +    if (Name[1] == 'r' || Name[1] == 'd' || Name[1] == 'm') {
Nevermind. I guess I'm blind.

2024-10-14 02:47 UTC, merged