InstCombine: extend select-equiv to support vectors
llvm/llvm-project pull request #111966
Opened 2024-10-11 09:02 UTC by artagnon

foldSelectEquivalence currently doesn't support comparisons on vector types due to correctness concerns. Note that the only concern is lane-crossing; ShuffleVector is the only possible lane-crossing instruction, and ShuffleVectorInst::{isIdentity,isShuffle} are the exact properties that should not be broken for valid vector-replacements. Put in the checks, and lift the limitation.

-- 8< --
Based on #111694.

2024-10-11 09:54 UTC, nikic requested changes
Shufflevector is not the only lane-crossing operation, see https://github.com/llvm/llvm-project/blob/80c15c48d1fbb53478c9400e598abcbdcae0d962/llvm/lib/Analysis/InstructionSimplify.cpp#L4347-L4351 for a more accurate heuristic.

2024-10-11 14:58 UTC, nikic commented
Yes, we should move that code plus https://github.com/llvm/llvm-project/blob/c13f806f17ac61961015e38b69c8b39ba7d454ac/llvm/lib/Transforms/InstCombine/InstCombineCalls.cpp#L3635-L3650 into a ValueTracking function `isLanewiseOperation()` or so.

2024-10-14 14:37 UTC, artagnon commented
Rebased, ready to review now.

2024-10-14 19:04 UTC, nikic approved these changes
LGTM

2024-10-15 10:10 UTC, merged