[mlir][transforms] Add `signalPassFailure` in RemoveDeadValues
llvm/llvm-project pull request #112199
Opened 2024-10-14 13:40 UTC by CoTinker

This PR adds `signalPassFailure` in RemoveDeadValues to ensure that a pipeline would stop here.
Fixes #111757.

2024-10-14 16:07 UTC, MaheshRavishankar requested changes
Could you add a test here please?

2024-10-14 16:18 UTC, CoTinker commented
> Could you add a test here please?

I don't know how to add test for signalPassFailure, could you please give me some advice.

2024-10-14 17:04 UTC, MaheshRavishankar reviewed
You can add a test with `// expected-error` and use `--verify-diagnostics` (I think).

2024-10-14 18:45 UTC, joker-eph approved these changes

2024-10-15 03:19 UTC, CoTinker commented
Sorry, I'm still having trouble understanding how to check for `signalPassFailure` in mlir-opt. I know `expected-error` and `verify-diagnostics` can check for `emitError`, but I'm not sure how to handle `signalPassFailure`.

2024-10-15 05:49 UTC, MaheshRavishankar commented
> Sorry, I'm still having trouble understanding how to check for `signalPassFailure` in mlir-opt. I know `expected-error` and `verify-diagnostics` can check for `emitError`, but I'm not sure how to handle `signalPassFailure`.

Emit an error message before the `return signalPassFailure` and check for the error message?

2024-10-15 06:11 UTC, CoTinker commented
> > Sorry, I'm still having trouble understanding how to check for `signalPassFailure` in mlir-opt. I know `expected-error` and `verify-diagnostics` can check for `emitError`, but I'm not sure how to handle `signalPassFailure`.
> 
> Emit an error message before the `return signalPassFailure` and check for the error message?

https://github.com/llvm/llvm-project/blob/57d109c4c93c8cf2d7ff9e5877a48152ed7a617a/mlir/test/Transforms/remove-dead-values.mlir#L3-L12
It has already been checked.

2024-10-15 06:13 UTC, CoTinker commented
Error message is here.
https://github.com/llvm/llvm-project/blob/57d109c4c93c8cf2d7ff9e5877a48152ed7a617a/mlir/lib/Transforms/RemoveDeadValues.cpp#L578-L592

2024-10-17 16:51 UTC, MaheshRavishankar approved these changes

2024-10-18 01:23 UTC, CoTinker commented
Thanks for your review.

2024-10-18 01:55 UTC, merged