[libc++][vector] include formatter only in C++23
llvm/llvm-project pull request #112675
Opened 2024-10-17 08:13 UTC by atetubou

This is to reduce included header file size in pre C++23 build.

e.g. 2% of total included file coming from formatter_bool.h in chrome build.
https://commondatastorage.googleapis.com/chromium-browser-clang/chrome_includes_2024-10-17_004801.html#view=edges&filter=&sort=asize&reverse=&includer=%5Ethird_party%2Flibc%5C%2B%5C%2B%2Fsrc%2Finclude%2Fvector%24&included=&limit=1000

2024-10-17 11:38 UTC, frederick-vs-ja requested changes
Perhaps we should correspondingly remove related entries in cxx11.csv ~ cxx20.csv in `libcxx/test/libcxx/transitive_includes`.

2024-10-17 11:53 UTC, zmodem commented
There was some discussion of this in https://reviews.llvm.org/D149543 with @mordante 

I'm not familiar with the standard's requirements, but if they're only needed only in C++23, making the includes conditional sounds like a good option.

2024-10-18 06:12 UTC, atetubou commented
I updated `libcxx/test/libcxx/transitive_includes` for some C++ versions.

From my understanding, formatter headers are only used from C++23's code for `vector<bool>` and we don't need to include then in earlier version.

2024-10-19 14:18 UTC, philnik777 requested changes
See #99705

2024-10-23 08:20 UTC, atetubou commented
@philnik777 oh thanks, will you update the PR to rebase and pass the tests?

2024-10-31 11:08 UTC, frederick-vs-ja commented
This PR seems to be superseded. Is there any additional necessary work?

2024-10-31 11:10 UTC, atetubou commented
No, let me close this PR. Thank you for your reminder.

2024-10-31 11:10 UTC, closed without merging