clastb representation in existing IR, and AArch64 codegen
llvm/llvm-project pull request #112738
Opened 2024-10-17 16:16 UTC by huntergr-arm

These commits show a possible representation of SVE's `clastb` instruction using existing IR instructions and intrinsics, along with DAGCombines to emit the actual instruction.

At 9 instructions to represent `clastb`, it feels a little fragile and may be changed by passes between LoopVectorize and codegen. While we can sink the loop-invariant terms back into the right block in CGP, I do wonder if we want a more direct intrinsic to represent this kind of operation.

Perhaps something like `llvm.vector.extract.last.active(data, mask)` ?

This is something we would use to support the CSA vectorization in #106560 for SVE, though we would prefer to use clastb inside the vector loop instead of after it. That patch uses an int max reduction to determine the index instead of the cttz.elts based approach in this PR, so we have another existing IR option to use if we want.

2024-10-17 21:15 UTC, efriedma-quic commented
Reliably matching the integer arithmetic seems problematic; I think I'd lean towards an intrinsic.   Maybe `llvm.vector.extract.last.active(data, mask, passthru)`, set the passthru to poison if you don't care.

2024-11-27 16:20 UTC, huntergr-arm commented
Rebased on top of the intrinsic.

2024-12-02 11:39 UTC, SamTebbs33 approved these changes
Looks good to me apart from a doc comment needed.

2024-12-02 13:13 UTC, arsenm requested changes
Bad TargetLowering API with no use context. SelectionDAGBuilder should directly translate into dag nodes and not be a point of configuration

2024-12-03 11:15 UTC, huntergr-arm commented
> Bad TargetLowering API with no use context. SelectionDAGBuilder should directly translate into dag nodes and not be a point of configuration

I was following a pattern of existing TLI functions (starting with `shouldExpandGetActiveLaneMask` 3 years ago). If that's the wrong way to do it, then I guess we have some cleanup to do later in addition to removing the function from this patch.

I'll investigate leaving it as an intrinsic and moving the current code in SelectionDAGBuilder to an expand legalization function instead.

2024-12-03 13:17 UTC, arsenm commented
> I was following a pattern of existing TLI functions (starting with `shouldExpandGetActiveLaneMask` 3 years ago). If that's the wrong way to do it, then I guess we have some cleanup to do later in addition to removing the function from this patch.
> 

It's developing an ad-hoc, parallel legalization mechanism to the regular one that happens in a different place. This expands the surface area of developing a target, and I have endless trouble fighting with non-trivial logic in the builder. All the legalization decisions should be made during legalization, not before

2025-01-22 16:10 UTC, huntergr-arm commented
Rebased on the vecops-expansion-based lowering from #118810. I implemented basic SVE isel pattern matching for the new ISD node, then added a couple new dag combines to fold to lastb, then clastb.

2025-01-31 10:27 UTC, huntergr-arm commented
@arsenm has the changed design addressed your concerns? The SDAGBuilder lowering is the same for all targets, and now I'm just marking the new ISD node as Legal for AArch64 to avoid the default vecops expansion here to improve SVE codegen.

2025-01-31 15:26 UTC, MacDue approved these changes
LGTM, I think @arsenm's main concern as been addressed as there's no new target lowering hook anymore. I think the PR description needs updating though as the `llvm.vector.extract.last.active` intrinsic now exists and this patch is improves the SVE lowering.

2025-01-31 15:26 UTC, MacDue commented on llvm/include/llvm/Target/TargetSelectionDAG.td
> +
Is it worth adding any constrains for `find_last_active`?

2025-01-31 18:23 UTC, sdesmalen-arm commented on llvm/lib/Target/AArch64/AArch64SVEInstrInfo.td
> +  // opportunity to fold into a lastb or clastb directly.
I agree it would be good to have some tests for these.

2025-01-31 18:23 UTC, sdesmalen-arm commented on llvm/lib/Target/AArch64/AArch64ISelLowering.cpp
> +  if (!Subtarget->hasSVE() || DCI.isBeforeLegalize() ||
nit: the test for `Subtarget->hasSVE()` is redundant and tested by the `getOperationAction(..) == legal` below.

2025-01-31 18:23 UTC, sdesmalen-arm commented on llvm/lib/Target/AArch64/AArch64ISelLowering.cpp
> +  SDValue Vec = LastB.getOperand(1);
nit: only has one use, can just as well propagate into expression below.

2025-02-05 12:30 UTC, huntergr-arm commented on llvm/lib/Target/AArch64/AArch64SVEInstrInfo.td
> +  // opportunity to fold into a lastb or clastb directly.
Sadly it's pretty difficult to do this once the combines have been added. I don't see a global switch to disable combining, just the target-indepedent combines. We do check the optimization level in a few places in AArch64ISelLowering, but mostly for TLI methods for IR-level decisions. Deliberately turning off (c)lastb pattern matching at O0 feels odd. Adding a new switch just for this feature also feels excessive.

I could potentially add a globalisel-based test, though I'm not sure how much code that requires. We've added a few new ISD nodes recently, and none have added support in globalisel.

I guess this is mostly due to it being hard to just create a selectiondag without IR and run selection over it.

2025-02-05 14:59 UTC, arsenm approved these changes

2025-02-05 14:59 UTC, arsenm commented on llvm/lib/Target/AArch64/AArch64ISelLowering.cpp
> +                             Mask.getValueType()) != TargetLowering::Legal)
isOperationLegal?

2025-02-06 11:41 UTC, sdesmalen-arm approved these changes

2025-02-06 13:38 UTC, merged