[NFC][Clang] Fix enumerated mismatch warning
llvm/llvm-project pull request #112816
Opened 2024-10-18 03:04 UTC by jsji

This is one of the many PRs to fix errors with LLVM_ENABLE_WERROR=on. Built by GCC 11.

Fix warning:
llvm-project/clang/lib/Parse/ParseDeclCXX.cpp:3153:14: error: enumerated mismatch in conditional expression: ‘clang::diag::<unnamed enum>’ vs ‘clang::diag::<unnamed enum>’ [-Werror=enum-compare]
 3152 |          DS.isFriendSpecified() || NextToken().is(tok::kw_friend)
      |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 3153 |              ? diag::err_friend_concept
      |              ^~~~~~~~~~~~~~~~~~~~~~~~~~
 3154 |              : diag::
      |              ~~~~~~~~
 3155 |                    err_concept_decls_may_only_appear_in_global_namespace_scope);

2024-10-18 03:59 UTC, Sirraide requested changes
This doesn’t seem right: that diagnostic is only used in the parser, which is why it is in `DiagnosticParseKinds.td`. Instead, it’d be better to cast the two diagnostic IDs that are causing the problem to `unsigned` where they’re used.

2024-10-19 15:42 UTC, cor3ntin commented on clang/lib/Parse/ParseDeclCXX.cpp
> +            ? unsigned(diag::err_friend_concept)
```suggestion
            ? llvm::to_underlying(diag::err_friend_concept)
```

2024-10-19 15:42 UTC, cor3ntin commented on clang/lib/Parse/ParseDeclCXX.cpp
> +            : unsigned(
```suggestion
            : llvm::to_underlying((
```

2024-10-22 00:51 UTC, jsji commented
@Sirraide @cor3ntin Updated, can you please have another look? Thanks.

2024-10-22 11:07 UTC, Sirraide approved these changes
LGTM

2024-10-22 11:23 UTC, cor3ntin approved these changes

2024-10-22 13:35 UTC, merged