[libc] Add cospif16 function
llvm/llvm-project pull request #113001
Opened 2024-10-18 23:23 UTC by wldfngrs

Implementation of `cospi` for half precision floating point inputs scaled by pi, correctly rounded for all rounding modes.

2024-10-19 00:10 UTC, overmighty reviewed
Most of the code is shared with `sinpif16`. You could move most of it to a header and have both `cospif16` and `sinpif16` call a function from that header.

2024-10-19 00:10 UTC, overmighty commented on libc/src/math/cospif16.h
> +// ===--------------------------------------------------------------------===//
Nit: formatting.

```suggestion
//===-- Implementation header for cospif16 ----------------------*- C++ -*-===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//
```

You can use https://github.com/overmighty/llvm-dev-utils/blob/master/llvm_libc_add_math_function.py to generate this and other bits of boilerplate. I should probably open a PR at some point to add it to libc/utils and document it.

2024-10-19 00:10 UTC, overmighty commented on libc/test/src/math/cospif16_test.cpp
> +//===---------------------------------------------------------------------===//
Nit: formatting.

```suggestion
//===----------------------------------------------------------------------===//
```

2024-10-19 16:27 UTC, lntue approved these changes

2024-10-20 10:01 UTC, overmighty requested changes

2024-10-20 10:01 UTC, overmighty commented on libc/src/math/generic/CMakeLists.txt
> +    libc.src.__support.common
`.range_reduction` is unused.

2024-10-24 00:14 UTC, overmighty requested changes

2024-10-24 00:14 UTC, overmighty commented on libc/src/math/generic/CMakeLists.txt
> +    libc.src.__support.FPUtil.fp_bits
Some dependencies are missing.

```suggestion
  DEPENDS
    .sincosf16_utils
    libc.hdr.errno_macros
    libc.hdr.fenv_macros
    libc.src.__support.FPUtil.cast
    libc.src.__support.FPUtil.fenv_impl
    libc.src.__support.FPUtil.fp_bits
    libc.src.__support.FPUtil.multiply_add
    libc.src.__support.macros.optimization
```

2024-10-29 08:45 UTC, overmighty requested changes

2024-10-29 08:45 UTC, overmighty commented on libc/src/math/generic/sinpif16.cpp
> +#include "sincosf16_utils.h"
```suggestion
#include "src/math/sinpif16.h"
#include "hdr/errno_macros.h"
#include "hdr/fenv_macros.h"
#include "sincosf16_utils.h"
```

2024-10-29 08:45 UTC, overmighty commented on libc/src/math/generic/CMakeLists.txt
>    DEPENDS
```cmake
  DEPENDS
    .sincosf16_utils
    libc.hdr.errno_macros
    libc.hdr.fenv_macros
    libc.src.__support.FPUtil.cast
    libc.src.__support.FPUtil.fenv_impl
    libc.src.__support.FPUtil.fp_bits
    libc.src.__support.FPUtil.multiply_add
```

2024-10-29 08:45 UTC, overmighty commented on libc/src/math/generic/cospif16.cpp
> +  //           + sin(y * pi/32) * sin(k * pi/32)
Nit: formatting.

```suggestion
  //   cos(x * pi) = cos((k + y) * pi/32)
  //               = cos(k * pi/32) * cos(y * pi/32) +
  //                 sin(y * pi/32) * sin(k * pi/32)
```

2024-10-29 08:45 UTC, overmighty commented on libc/src/math/generic/cospif16.cpp
> +  // * pi/32) and cos(y * pi/32) are computed using degree-9 chebyshev
Nit: formatting.

```suggestion
  // precomputed and stored using a vector of 64 single precision floats.
  // sin(y * pi/32) and cos(y * pi/32) are computed using degree-9 Chebyshev
```

2024-10-29 08:45 UTC, overmighty commented on libc/src/math/generic/sincosf16_utils.h
> +  // errors.
Nit: formatting.

```suggestion
  // sin(x * pi/32) = sin((k + y) * pi/32)
  //                = sin(y * pi/32) * cos(k * pi/32) +
  //                  cos(y * pi/32) * sin(k * pi/32)
  // Recall, after range reduction, -0.5 <= y <= 0.5. For very small values of
  // y, calculating sin(y * p/32) can be inaccurate. Generating a polynomial for
  // sin(y * p/32)/y instead significantly reduces the relative errors.
```

2024-10-29 08:45 UTC, overmighty commented on libc/utils/MPFRWrapper/MPFRUtils.cpp
> +      auto d = mpz_tstbit(integer, 0);
`mpz_tstbit` returns an `int` as far as I can tell. Should probably just use `int` directly instead of `auto`.

2024-10-29 08:45 UTC, overmighty commented on libc/src/math/generic/sinpif16.cpp
>    // * pi/32) and cos(y * pi/32) are computed using degree-9 chebyshev
Similar formatting nits as for `cospif16`. If it's the same explanation for both then you could just have it in the shared header only.

2024-10-29 10:33 UTC, overmighty approved these changes

2024-10-29 10:39 UTC, merged