Add clang::lifetimebound annotation to ArrayRef constructors.
llvm/llvm-project pull request #113547
Opened 2024-10-24 10:58 UTC by hokein

This enables clang to detect more dangling issues.

```
ArrayRef<int> func() {
   constexpr int array[] = {...}; // oops, missing the static
   return array; // return a dangling reference, bomb.
}
```

See #113533.

2024-10-24 11:04 UTC, Xazax-hun approved these changes
LGTM, thanks!

Any reason for not annotating the rest of the constructors?

2024-10-24 12:25 UTC, Xazax-hun approved these changes
Thanks! I think the `std::vector` and `std::array` ones could also be annotated.

2024-10-24 12:26 UTC, hokein commented
> Any reason for not annotating the rest of the constructors?

Note that the ArrayRef is already annotated as gsl::Pointer, so constructor for the gsl::Owner already works without the lifetimebound annotation. I only target on the non-working cases, mostly the generic pointer/reference types.

Below is my test:

```
llvm::ArrayRef<int> test() {
   int array[10];
   std::vector<int> k;
   std::array<int, 10> k2;
   return k; // warning, local vector (owner)
   return k2; // warning, local array (owner)
   return {1, 2, 3}; // warning, initializing_list, backing array is destoryed.
   return llvm::ArrayRef<int>(array+0, array+10); // wanring
   return array; // warning
   return {array, 10}; // warning
}
```

2024-10-24 12:28 UTC, Xazax-hun requested changes

2024-10-24 12:28 UTC, Xazax-hun commented on llvm/include/llvm/ADT/ArrayRef.h
> +        const std::initializer_list<T> &Vec LLVM_LIFETIME_BOUND)
Hmm, actually, I am not sure if I'm super confident about this one.

Consider:
```
ArrayRef<int> ref({1, 2, 3, 4});
use(ref);
```

What would happen here? I wonder if this is actually safe despite the initializer list itself was a temporary and already destroyed when I invoke `use`.

2024-10-24 12:29 UTC, Xazax-hun commented
> I only target on the non-working cases, mostly the generic pointer/reference types.

Ah, I see! Thanks! That makes sense. I guess one question is if the future direction is to use both annotations together or to standardize on one of them for more clarity. I don't have a strong opinion on this one.

2024-10-24 13:06 UTC, Xazax-hun commented on llvm/include/llvm/ADT/ArrayRef.h
> +        const std::initializer_list<T> &Vec LLVM_LIFETIME_BOUND)
Actually, I am surprised we take an initializer list by const-ref here. I wonder if the right solution here is to take it by value and keep the annotation. I think lifetime annotations might work out just right after taking it by value.

2024-10-24 13:19 UTC, hokein commented on llvm/include/llvm/ADT/ArrayRef.h
> +        const std::initializer_list<T> &Vec LLVM_LIFETIME_BOUND)
> Consider:

> ArrayRef<int> ref({1, 2, 3, 4});
> use(ref);


> Hmm, actually, I am not sure if I'm super confident about this one.
> 
> Consider:
> 
> ```
> ArrayRef<int> ref({1, 2, 3, 4});
> use(ref);
> ```
> 
> What would happen here? I wonder if this is actually safe despite the initializer list itself was a temporary and already destroyed when I invoke `use`.

This is actually a use-after-free, the backing array of the initializer_list is destroyed after the ref declaration statement, see https://godbolt.org/z/fYW7Tqcfq.

> The backing array has the same lifetime as any other [temporary object](https://en.cppreference.com/w/cpp/language/lifetime#Temporary_object_lifetime), except that initializing an [std::initializer_list](https://en.cppreference.com/w/cpp/utility/initializer_list) object from the backing array extends the lifetime of the array exactly like [binding a reference to a temporary](https://en.cppreference.com/w/cpp/language/reference_initialization#Lifetime_of_a_temporary).

2024-10-24 13:21 UTC, hokein commented on llvm/include/llvm/ADT/ArrayRef.h
> +        const std::initializer_list<T> &Vec LLVM_LIFETIME_BOUND)
> Actually, I am surprised we take an initializer list by const-ref here. 

I think it doesn't matter much, I agree that in general `std::initializer_list` is passed by value.

2024-10-24 13:56 UTC, Xazax-hun commented on llvm/include/llvm/ADT/ArrayRef.h
> +        const std::initializer_list<T> &Vec LLVM_LIFETIME_BOUND)
Ah, I see! Thanks! I have not realized the backing array is also a temporary with it's lifetime extended in some scenarios.

2024-10-24 13:56 UTC, Xazax-hun approved these changes

2024-10-24 15:24 UTC, hokein commented on llvm/include/llvm/ADT/ArrayRef.h
> +        const std::initializer_list<T> &Vec LLVM_LIFETIME_BOUND)
We have a tricky case with an empty initializer_list:

```
ArrayRef<int> ref({}); 
```

clang still diagnoses it as dangling reference, but the code doesn't have any dangling references. I think it is ok, this is similar to `make_unique<pointer>(nullptr).get()` case (https://github.com/llvm/llvm-project/issues/97471).

2024-10-24 18:36 UTC, Xazax-hun commented on llvm/include/llvm/ADT/ArrayRef.h
> +        const std::initializer_list<T> &Vec LLVM_LIFETIME_BOUND)
Now that the patch to remove the reference from the initialiser list, this should no longer warn, right?

2024-10-25 07:01 UTC, hokein commented on llvm/include/llvm/ADT/ArrayRef.h
> +        const std::initializer_list<T> &Vec LLVM_LIFETIME_BOUND)
> Now that the patch to remove the reference from the initialiser list landed, this should no longer warn, right?

Ah, you're right. For initializer_list, we actually track its backing array, for the empty case `{}`, there is no `MaterializeTemporaryExpr` inside.

2024-10-25 18:16 UTC, dwblaikie commented on llvm/include/llvm/Support/Compiler.h
> +#define LLVM_LLVM_LIFETIME_BOUND
extra `LLVM_` here by accident?

2024-10-25 19:26 UTC, hokein commented on llvm/include/llvm/Support/Compiler.h
> +#define LLVM_LLVM_LIFETIME_BOUND
good catch, removed the extra `LLVM_`.

2024-10-28 07:38 UTC, merged