[mlir][Vector] Depreciate vector.extractelement/vector.insertelement
llvm/llvm-project pull request #113829
Opened 2024-10-27 18:24 UTC by Groverkss

See https://discourse.llvm.org/t/rfc-psa-remove-vector-extractelement-and-vector-insertelement-ops-in-favor-of-vector-extract-and-vector-insert-ops/71116/6 for more information.

2024-10-27 18:24 UTC, Groverkss commented
Depends on https://github.com/llvm/llvm-project/pull/113827

2024-10-27 23:12 UTC, kuhar reviewed
We should also list this on https://mlir.llvm.org/deprecation/

2024-10-27 23:12 UTC, kuhar commented on mlir/include/mlir/Dialect/Vector/IR/VectorOps.td
> +    Note: This operation is depreciated. Please use vector.extract insert.
```suggestion
    Note: This operation is deprecated. Please use vector.extract insert.
```

2024-10-27 23:12 UTC, kuhar commented on mlir/include/mlir/Dialect/Vector/IR/VectorOps.td
> +    Note: This operation is depreciated. Please use vector.insert instead.
```suggestion
    Note: This operation is deprecated. Please use vector.insert instead.
```

2024-10-27 23:28 UTC, kuhar requested changes
Before we deprecate this, we should also handle the dynamic case in vector-to-spirv. We support it for insertelement/extractelement but not insert/extract:
* https://github.com/llvm/llvm-project/blob/fb33af08e4c105a05855f8beeb972d493410e72f/mlir/lib/Conversion/VectorToSPIRV/VectorToSPIRV.cpp#L252-L254
* https://github.com/llvm/llvm-project/blob/fb33af08e4c105a05855f8beeb972d493410e72f/mlir/lib/Conversion/VectorToSPIRV/VectorToSPIRV.cpp#L303-L312

2024-10-28 19:13 UTC, dcaballe commented
LGTM. Final approval should come from @kuhar after addressing his concerns. Thanks!

2024-10-29 22:22 UTC, Groverkss commented
> Before we deprecate this, we should also handle the dynamic case in vector-to-spirv. We support it for insertelement/extractelement but not insert/extract:
> 
> * https://github.com/llvm/llvm-project/blob/fb33af08e4c105a05855f8beeb972d493410e72f/mlir/lib/Conversion/VectorToSPIRV/VectorToSPIRV.cpp#L252-L254
> * https://github.com/llvm/llvm-project/blob/fb33af08e4c105a05855f8beeb972d493410e72f/mlir/lib/Conversion/VectorToSPIRV/VectorToSPIRV.cpp#L303-L312

https://github.com/llvm/llvm-project/pull/114137

2024-12-09 18:09 UTC, banach-space commented
Hey @Groverkss , how's progress with this? Is this blocked?

2024-12-10 11:20 UTC, Groverkss commented
> Hey @Groverkss , how's progress with this? Is this blocked?

Hi! It's not blocked, I just got held up by some other work. I plan to finish sending the final patch to remove all uses of vector.extractelement/vector.insertelement this week.

2024-12-10 14:04 UTC, banach-space commented
> > Hey @Groverkss , how's progress with this? Is this blocked?
> 
> Hi! It's not blocked, I just got held up by some other work. I plan to finish sending the final patch to remove all uses of vector.extractelement/vector.insertelement this week.

Sure, no rush. I've just realised that @kuhar has one outstanding request - I guess that's what we're waiting for? I'd be tempted to land this as is, but will defer to Jakub - I'm happy either way :) And really appreciate your work in this area 🙏🏻

2024-12-10 14:48 UTC, kuhar commented
The typos from this review are not fixed yet: https://github.com/llvm/llvm-project/pull/113829#pullrequestreview-2397652757

2025-02-19 20:41 UTC, kuhar approved these changes

2025-02-19 20:42 UTC, merged