[libc++] Refactor __split_buffer to eliminate code duplication
llvm/llvm-project pull request #114138
Opened 2024-10-29 22:23 UTC by winner245

This PR refactors the `__split_buffer` class to eliminate code duplication in the `push_back` and `push_front` member functions.

**Motivation:**  
The lvalue and rvalue reference overloads of `push_back` share identical logic, which coincides with that of `emplace_back`. Similarly, the overloads of `push_front` also share identical logic but lack an `emplace_front` member function, leading to an inconsistency. These identical internal logics lead to significant code duplication, making future maintenance more difficult.

**Summary of Refactor:**  
This PR reduces code redundancy by:
1. Modifying both overloads of `push_back` to call `emplace_back`.
2. Introducing a new `emplace_front` member function that encapsulates the logic of `push_front`, allowing both overloads of `push_front` to call it (The addition of `emplace_front` also avoids the inconsistency regarding the absence of `emplace_front`).

The refactoring results in reduced code duplication, improved maintainability, and enhanced readability.

2024-10-30 10:16 UTC, frederick-vs-ja approved these changes

2024-10-30 10:16 UTC, frederick-vs-ja commented
This follows up #113481. CC @ldionne @philnik777.

2024-10-30 10:38 UTC, philnik777 requested changes
The other patch removed some code duplication, but this introduces `emplace_front` and only uses it to implement `push_front`. What is the point of that?

2024-10-30 12:01 UTC, frederick-vs-ja commented
> The other patch removed some code duplication, but this introduces `emplace_front` and only uses it to implement `push_front`. What is the point of that?

There're currently 2 `push_front` overloads, taking `const value_type&` and `value_type&&` respectively, containing almost identical code. The newly introduced `emplace_front` makes the code only written once.

2024-10-30 13:48 UTC, winner245 commented
Thank you, philnik777, for your insightful feedback. I also appreciate frederick-vs-ja's assistance in clarifying the purpose of my refactor, which effectively highlighted the code duplication issue with the current `push_front` implementation.

Considering philnik777's suggestion to replace any uses of `__split_buffer::push_front` and `__split_buffer::push_back` with their `emplace_xxx` equivalents, I reviewed the current usage of `__split_buffer`. It appears that it is primarily utilized by `std::vector` and `std::deque`. Therefore, the proposed changes based on philnik777's suggestion would be:

- Remove the two overloads of `__split_buffer::push_back` and retain only `__split_buffer::emplace_back`.
- Remove the two overloads of `__split_buffer::push_front`, while adding `__split_buffer::emplace_front` (noting that `__split_buffer` currently does not provide `emplace_front`).
- Modify `std::vector` and `std::deque` to replace all instances of `__split_buffer::push_front` and `__split_buffer::push_back` with the `emplace_xxx` methods.

This approach seems to provide a more comprehensive refactor. However, I would like to hear @ldionne and @frederick-vs-ja's perspectives on this before proceeding. Thank you.

2024-10-31 10:48 UTC, frederick-vs-ja commented
Let's just replace all `__split_buffer::push_{front,back}`. The changes are still simple and clear to me.

> It appears that it is primarily utilized by `std::vector` and `std::deque`.

That's all. It is not used elsewhere.

2024-10-31 16:56 UTC, philnik777 approved these changes

2024-11-01 13:42 UTC, frederick-vs-ja commented
CI failures are unrelated (due to missed inclusion in unrelated headers). You can try to rebase now.

2024-11-01 13:52 UTC, winner245 commented
Thanks. I'll proceed with rebase now.

2024-11-04 07:35 UTC, frederick-vs-ja approved these changes

2024-11-04 12:54 UTC, merged