[libc] Add some integration features into newhdrgen
llvm/llvm-project pull request #114272
Opened 2024-10-30 17:18 UTC by frobtech

This adds some command-line switches to the newhdrgen script
that facilitate more generalized build system integration.
These enable the use of the script in Fuchsia's GN build.

The --write-if-changed switch avoids touching the .h output file
if it's unchanged, which is beneficial to incremental rebuilds.

The --depfile switch writes out a make/ninja-compatible depfile
describing the inputs and outputs.  This is crucial for build
system integration when using the following new feature.

When the new --libc-dir switch is given, the YAML file argument
is optional.  Instead, the --h_def_file input file path must have
the --libc-dir path as a prefix and the yaml file is found in its
corresponding place in the libc source tree.

2024-10-30 19:52 UTC, michaelrj-google reviewed
Code changes overall LGTM, make sure to update the docs where necessary: https://github.com/llvm/llvm-project/blob/main/libc/docs/dev/header_generation.rst?plain=1

2024-10-30 21:14 UTC, frobtech commented on libc/newhdrgen/yaml_to_classes.py
> +        yaml_file = libc_yaml_dir / args.h_def_file.with_suffix("").with_suffix(
`.with_suffix("")` strips `.def` and then `.with_suffix(".yaml")` replaces the remaining `.h` with `.yaml`.

2024-10-30 21:18 UTC, frobtech commented
> Code changes overall LGTM, make sure to update the docs where necessary: https://github.com/llvm/llvm-project/blob/main/libc/docs/dev/header_generation.rst?plain=1

That does not currently include any explanation of the file-related command line switches. It's not really documentation for the tool as a tool. It's more a few examples of things to try and what might happen.

2024-10-31 18:45 UTC, fabio-d requested changes
I think it'd be great if the two blocks that decide `yaml_file` and `output_file_path` had some comment explaining the various cases with examples, because the code alone was a bit hard to follow to me

2024-10-31 18:45 UTC, fabio-d commented on libc/newhdrgen/yaml_to_classes.py
> +        final_header_content = str
`final_header_content = header_str`?

2024-10-31 18:45 UTC, fabio-d commented on libc/newhdrgen/yaml_to_classes.py
> +    if args.add_function:
Is this repetition (see 5 lines above) on purpose?

2024-12-10 19:07 UTC, michaelrj-google approved these changes
Overall LGTM, but you need to fix the paths before landing.

2024-12-28 08:15 UTC, frobtech commented
I'm going to abandon this and do some more basic refactoring to get towards a good CLI for both programmatic and human use. It will be in several smaller steps.

2024-12-28 08:15 UTC, closed without merging