Fixes #86579
llvm/llvm-project pull request #114939
Opened 2024-11-05 06:02 UTC by krishna2803

Fixed imports for all files *within* `libc/src/string/memory_utils`.
Note: This doesn't include **all** files that need to be fixed.

2024-11-05 16:43 UTC, nickdesaulniers reviewed
ah, libc/src/__support/CMakeLists.txt the definition of the `common` header library (L54) is missing the dependency on config.h and attributes.h. It also falsely depends on endian.h, common.h, and cpu_features.h. That should get cleaned up in your PR.

Once that's cleaned up, then we can revisit changing the header source files.

2024-11-09 14:52 UTC, lntue commented on libc/src/string/allocating_string_utils.h
> -#include "src/__support/macros/config.h"
`src/__support/macros/config.h` is needed for `LIBC_NAMESPACE_DECL`.

2024-11-09 14:52 UTC, lntue commented on libc/src/string/memory_utils/aarch64/inline_bcmp.h
> -#include "src/__support/macros/config.h"
`src/__support/macros/config.h` is needed for `LIBC_NAMESPACE_DECL`

2024-11-09 14:52 UTC, lntue commented on libc/src/string/memory_utils/aarch64/inline_memset.h
> -#include "src/__support/macros/config.h"
`src/__support/macros/config.h` is needed for `LIBC_NAMESPACE_DECL`

2024-11-09 14:53 UTC, lntue commented on libc/src/string/memory_utils/generic/builtin.h
> -#include "src/__support/macros/config.h"
`src/__support/macros/config.h` is needed for `LIBC_NAMESPACE_DECL`

2024-11-09 14:53 UTC, lntue commented on libc/src/string/memory_utils/inline_bcmp.h
> -#include "src/__support/macros/config.h"
`src/__support/macros/config.h` is needed for `LIBC_NAMESPACE_DECL`

2024-11-09 14:53 UTC, lntue commented on libc/src/string/memory_utils/inline_bzero.h
> -#include "src/__support/macros/config.h"
`src/__support/macros/config.h` is needed for `LIBC_NAMESPACE_DECL`

2024-11-09 14:53 UTC, lntue commented on libc/src/string/memory_utils/inline_memmem.h
> -#include "src/__support/macros/config.h"
`src/__support/macros/config.h` is needed for `LIBC_NAMESPACE_DECL`

2024-11-09 14:53 UTC, lntue commented on libc/src/string/memory_utils/inline_memmove.h
> -#include "src/__support/macros/config.h"
`src/__support/macros/config.h` is needed for `LIBC_NAMESPACE_DECL`

2024-11-09 14:53 UTC, lntue commented on libc/src/string/memory_utils/inline_strcmp.h
> -#include "src/__support/macros/config.h"
`src/__support/macros/config.h` is needed for `LIBC_NAMESPACE_DECL`

2024-11-09 14:53 UTC, lntue commented on libc/src/string/memory_utils/inline_strstr.h
> -#include "src/__support/macros/config.h"
`src/__support/macros/config.h` is needed for `LIBC_NAMESPACE_DECL`

2024-11-09 14:54 UTC, lntue commented on libc/src/string/memory_utils/x86_64/inline_memset.h
> -#include "src/__support/macros/config.h"
`src/__support/macros/config.h` is needed for `LIBC_NAMESPACE_DECL`

2024-11-09 14:54 UTC, lntue commented on libc/src/string/memory_utils/x86_64/inline_bcmp.h
> -#include "src/__support/macros/config.h"
`src/__support/macros/config.h` is needed for `LIBC_NAMESPACE_DECL`

2024-11-09 14:54 UTC, lntue commented on libc/src/string/memory_utils/utils.h
> -#include "src/__support/macros/config.h"
`src/__support/macros/config.h` is needed for `LIBC_NAMESPACE_DECL`

2024-11-09 14:54 UTC, lntue commented on libc/src/string/memory_utils/riscv/inline_memset.h
> -#include "src/__support/macros/config.h"
`src/__support/macros/config.h` is needed for `LIBC_NAMESPACE_DECL`

2024-11-09 14:54 UTC, lntue commented on libc/src/string/memory_utils/riscv/inline_memmove.h
> -#include "src/__support/macros/config.h"
`src/__support/macros/config.h` is needed for `LIBC_NAMESPACE_DECL`

2024-11-09 14:54 UTC, lntue commented on libc/src/string/memory_utils/riscv/inline_memcpy.h
> -#include "src/__support/macros/config.h"
`src/__support/macros/config.h` is needed for `LIBC_NAMESPACE_DECL`

2024-11-09 14:54 UTC, lntue commented on libc/src/string/memory_utils/riscv/inline_memcmp.h
> -#include "src/__support/macros/config.h"
`src/__support/macros/config.h` is needed for `LIBC_NAMESPACE_DECL`

2024-11-09 14:54 UTC, lntue commented on libc/src/string/memory_utils/riscv/inline_bcmp.h
> -#include "src/__support/macros/config.h"
`src/__support/macros/config.h` is needed for `LIBC_NAMESPACE_DECL`

2024-11-09 14:54 UTC, lntue commented on libc/src/string/memory_utils/op_x86.h
> -#include "src/__support/macros/config.h"
`src/__support/macros/config.h` is needed for `LIBC_NAMESPACE_DECL`

2024-11-09 14:55 UTC, lntue commented on libc/src/string/memory_utils/op_riscv.h
> -#include "src/__support/macros/config.h"
`src/__support/macros/config.h` is needed for `LIBC_NAMESPACE_DECL`

2024-11-09 14:55 UTC, lntue commented on libc/src/string/memory_utils/op_generic.h
> -#include "src/__support/macros/config.h"
`src/__support/macros/config.h` is needed for `LIBC_NAMESPACE_DECL`

2024-11-09 14:55 UTC, lntue commented on libc/src/string/memory_utils/op_builtin.h
> -#include "src/__support/macros/config.h"
`src/__support/macros/config.h` is needed for `LIBC_NAMESPACE_DECL`

2024-11-09 14:55 UTC, lntue commented on libc/src/string/memory_utils/op_aarch64.h
> -#include "src/__support/macros/config.h"
`src/__support/macros/config.h` is needed for `LIBC_NAMESPACE_DECL`

2024-11-11 04:47 UTC, lntue approved these changes

2024-11-11 17:29 UTC, nickdesaulniers commented on libc/src/string/memory_utils/x86_64/inline_memset.h
> +#include "src/__support/macros/attributes.h" // LIBC_INLINE_VAR
`LIBC_INLINE` is also used from this header.

```suggestion
#include "src/__support/macros/attributes.h" // LIBC_INLINE, LIBC_INLINE_VAR
```

2024-11-11 17:29 UTC, nickdesaulniers commented on libc/src/__support/CMakeLists.txt
> -    macros/properties/cpu_features.h
May need to audit all uses of `LIBC_TARGET_CPU_HAS` (TODO: @nickdesaulniers )

2024-11-11 17:30 UTC, nickdesaulniers requested changes
left more feedback

2025-01-26 12:36 UTC, krishna2803 commented on libc/src/string/memory_utils/aarch64/inline_bcmp.h
> -#include "src/__support/macros/attributes.h"   // LIBC_INLINE
isn't `LIBC_INLINE` supposed to be used from `src/__support/macros/attributes.h`  instead of `src/__support/macros/config.h`?

2025-01-27 17:36 UTC, nickdesaulniers commented
> This branch has conflicts that must be resolved

Hi @krishna2803 , thanks for updating this PR. It looks like you'll need to rebase on `main`. Do you mind doing that? You'll need to force push to your github branch.

2025-01-27 21:58 UTC, krishna2803 commented
yeah sure! I'm on it

2025-02-02 18:26 UTC, krishna2803 commented on libc/src/__support/CMakeLists.txt
> -    macros/properties/cpu_features.h
can you please provide some guidance on what exactly needs to be done here?

2025-02-03 22:00 UTC, nickdesaulniers requested changes

2025-02-03 22:00 UTC, nickdesaulniers commented on libc/src/string/memory_utils/aarch64/inline_bcmp.h
> -#include "src/__support/macros/config.h"
This is still an issue in the last version of this patch.

2025-02-03 22:00 UTC, nickdesaulniers commented on libc/src/__support/CMakeLists.txt
> -    macros/properties/cpu_features.h
Specifically, there's a bunch of headers in src/__support/FPUtil/ and src/__support/HashTable/ that depend on cpu_features.h.  If their cmake doesn't directly depend on cpu_features header library in their cmake (instead indirectly dependending on them), then this change will sever that dependency.

libc/src/__support/HashTable/CMakeLists.txt LGTM
libc/src/__support/FPUtil/CMakeLists.txt does not LGTM, so you'll need to add explicit dependencies in that cmake file on `libc.src.__support.macros.properties.cpu_features`.

2025-02-04 16:48 UTC, nickdesaulniers requested changes

2025-02-04 17:02 UTC, krishna2803 commented on libc/src/__support/FPUtil/CMakeLists.txt
> +    libc.src.__support.macros.properties.cpu_features
shouldn't this be for `nearest_integer.h`?

2025-02-04 17:06 UTC, nickdesaulniers commented on libc/src/__support/FPUtil/CMakeLists.txt
> +    libc.src.__support.macros.properties.cpu_features
huh, oh, sorry, did I not unfold the diff in github UI? Anyways, my mistake; for some reason I think this hunk was being added to PolyEval, not nearest_integer.

Ok, I'll approve this once I test it quickly locally, but LGTM.

2025-02-04 17:08 UTC, nickdesaulniers approved these changes
Thanks for the patch! Need us to merge this for you?

2025-02-04 17:14 UTC, krishna2803 commented
yeah! thanks :D

2025-02-05 17:24 UTC, merged