[mlir][IR] Add `Block::isReachable` helper function
llvm/llvm-project pull request #114928
Opened 2024-11-05 05:35 UTC by matthias-springer

Add a new helper function `isReachable` to `Block`. This function traverses all successors of a block to determine if another block is reachable from the current block.

This functionality has been reimplemented in multiple places in MLIR. Possibly additional copies in downstream projects. Therefore, moving it to a common place.

2024-11-05 06:20 UTC, River707 requested changes
Why don't the various transforms just use DominatorTree? Answering these queries is what it's intended for.

2024-11-05 07:03 UTC, River707 commented
Coming back to this PR after reading https://github.com/llvm/llvm-project/pull/114940 (which uses this function). I don't think we should add this kind of thing to Block, I'd rather push people to use DominanceInfo (which does this more optimally). Things like Dialect Conversion (which make a muck of blocks and all kinds of other things) are generally very unique compared to the majority of users. For API's on the core data structures, the APIs should (generally) be pushing for the best way to do something.

2024-11-06 07:10 UTC, matthias-springer commented
> Why don't the various transforms just use DominanceInfo? Answering these queries is what it's intended for.

Block reachability and block dominance are two different things. Just because there is a path from `block A -> block B` does not necessarily mean that `block A dominates block B`. I'm not sure how "block reachability" could be implemented with `DominanceInfo`.

That being said, in the dialect conversion I actually need dominance, so this helper function is actually not useful there...

2024-11-06 22:01 UTC, joker-eph commented on mlir/lib/IR/Block.cpp
> +      continue;
This is a linear search, should this be the last check of the three?

2024-11-06 22:03 UTC, joker-eph commented on mlir/lib/IR/Block.cpp
> +  SmallPtrSet<Block *, 16> visited;
What about having the "except" parameters be a `SmallPtrSetImpl<Block *>` passed by copy (user should move) and use it to store the visited elements.
That way the user can still pre-populate it with blocks to skip, but we have one less check and one less data-structure around.

2024-11-13 05:47 UTC, River707 approved these changes
LG!

2024-11-13 05:58 UTC, merged