[Mips] Support llvm.readsteadycounter intrinsic
llvm/llvm-project pull request #114953
Opened 2024-11-05 08:48 UTC by yingopq

The llvm.readcyclecounter intrinsic can be implemented via the `rdhwr $3, $hwr_cc` instruction.
$hwr_cc: High-resolution cycle counter. This register provides read access to the coprocessor 0 Count Register.

Fix #106318.

2024-11-11 03:05 UTC, yingopq commented
@topperc @wzssyqa Could you help review, thanks!

2024-11-25 02:31 UTC, yingopq commented
Ping.

2024-11-25 04:28 UTC, wzssyqa requested changes

2024-11-25 04:28 UTC, wzssyqa commented on llvm/lib/Target/Mips/MipsISelLowering.cpp
> +    DestReg = Mips::V1_64;
Why can V1 can hardcoded here?
If the IR is quite long, will it overwrite some previous value?

2025-01-02 07:09 UTC, yingopq commented
Ping.

2025-01-05 07:25 UTC, wzssyqa commented on llvm/lib/Target/Mips/MipsISelLowering.cpp
> +  SmallVector<SDValue, 3> Results;
We should only support it for mips32r2+ or linux triples.
I mean you should check if it is mips32r2+ or the os section of triple is Linux.

2025-01-07 03:32 UTC, wzssyqa commented on llvm/lib/Target/Mips/MipsISelLowering.cpp
> +  if (!Subtarget.hasMips32r6() &&
r2.

2025-01-07 03:32 UTC, wzssyqa commented on llvm/test/CodeGen/Mips/readcyclecounter.ll
> +;RUN: llc -mtriple=mipsel-linux-gnu -mcpu=mips32r2 < %s | FileCheck %s --check-prefix=MIPSEL
What will happen for pre-r2 or non Linux?

2025-01-08 03:55 UTC, wzssyqa commented on llvm/test/CodeGen/Mips/readcyclecounter.ll
> +;RUN: llc -mtriple=mipsel-linux-gnu -mcpu=mips32r2 < %s | FileCheck %s --check-prefix=MIPSEL
Please add test cases for
```
llc -mtriple=mipsel-linux-gnu -mcpu=mips2
llc -mtriple=mips64el-linux-gnu -mcpu=mips3
llc -mtriple=mipsel -mcpu=mips32r2
llc -mtriple=mips64el -mcpu=mips64r2
llc -mtriple=mipsel -mcpu=mips2
llc -mtriple=mips64el -mcpu=mips3
```

2025-01-10 01:18 UTC, wzssyqa commented on llvm/test/CodeGen/Mips/readcyclecounter.ll
> +; MIPSEL-NEXT:    rdhwr $2, $hwr_cc
Ohh, I find another problem, the return value is `i64`.
It means that we should set `$a1/$3` to zero here, just as `MIPSEL_NOT_SUPPORTED` does.

2025-01-23 07:35 UTC, yingopq commented
Ping.

2025-01-23 09:31 UTC, wzssyqa commented on llvm/test/CodeGen/Mips/readcyclecounter.ll
> +; MIPSEL-NEXT:    rdhwr $2, $hwr_cc
@yingopq please fix this problem.

2025-02-06 00:48 UTC, brad0 commented
@wzssyqa

2025-02-11 00:47 UTC, merged

2025-02-11 06:38 UTC, wzssyqa commented
I reverted this commit. @yingopq can you have a look at this problem?

2025-02-18 02:06 UTC, yingopq commented
> I reverted this commit. @yingopq can you have a look at this problem?

I try to reproduce this failure, but the result was OK.
```
root@debian-sid-amd64:~/llvm-project# ./build/bin/llvm-lit -v llvm/test/CodeGen/Mips/readcyclecounter.ll
-- Testing: 1 tests, 1 workers --
PASS: LLVM :: CodeGen/Mips/readcyclecounter.ll (1 of 1)

Testing Time: 0.11s

Total Discovered Tests: 1
  Passed: 1 (100.00%)
root@debian-sid-amd64:~/llvm-project# cat /proc/version
Linux version 5.19.0-40-generic (buildd@lcy02-amd64-047) (x86_64-linux-gnu-gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0, GNU ld (GNU Binutils for Ubuntu) 2.38) #41~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Mar 31 16:00:14 UTC 2

```

I would commit a change.