[Docs][llvm-exegesis] Clarify AArch64 support
llvm/llvm-project pull request #114989
Opened 2024-11-05 13:55 UTC by sjoerdmeijer

Claiming AArch64 support for llvm-exegesis is a bit of a stretch in my opinion as only a couple of opcodes with GPR64 operands will work, so I propose to clarify that AArch64 support is very experimental. Also added some clarifications about its libpfm4 dependency.

2024-11-05 20:38 UTC, boomanaiden154 requested changes

2024-11-05 20:38 UTC, boomanaiden154 commented on llvm/docs/CommandGuide/llvm-exegesis.rst
> +(AArch64 only and very experimental), MIPS, and PowerPC (PowerPC64LE only) on
I would explicitly state here that snippet generation is experimental. In process snippet execution should "just work".

Maybe something like "AArch64 only, snippet generation support is sparse".

2024-11-05 20:38 UTC, boomanaiden154 commented on llvm/tools/llvm-exegesis/README.md
> +  * Very experimental AArch64 support only, most opcodes probably won't work.
Same clarification here.

2024-11-05 20:38 UTC, boomanaiden154 commented on llvm/tools/llvm-exegesis/README.md
> +due to a dependency on the Linux perf subsystem and libpfm4 for reading
This should probably go in the LLVM CMake documentation. This page isn't intended to provide detailed build directions, and people are more likely to look there.

2024-11-05 20:38 UTC, boomanaiden154 commented on llvm/docs/CommandGuide/llvm-exegesis.rst
> +mode that is supported on every platform that LLVM is. See README.md for
Reference the CMake documentation here. It's a bit odd to reference a README from proper documentation.

2024-11-06 11:34 UTC, sjoerdmeijer commented
Thanks for the review! I have addressed all comments, I think.

2024-11-07 01:13 UTC, boomanaiden154 approved these changes
LGTM. Thanks!

2024-11-07 07:42 UTC, davemgreen approved these changes
This matches my understanding of the support level in AArch64 at the moment. Thanks

2024-11-07 10:48 UTC, merged