[MLIR][OpenMP] Prevent loop wrapper translation crashes
llvm/llvm-project pull request #115475
Opened 2024-11-08 12:59 UTC by skatrak

This patch updates the `convertOmpOpRegions` translation function to prevent calling it for a loop wrapper region from causing a compiler crash due to a lack of terminator operations.

This problem is currently not triggered because there are no cases for which the region of a loop wrapper is passed to that function. This might have to change in order to support composite construct translation to LLVM IR.

2024-11-08 13:16 UTC, kiranchandramohan requested changes
> *[Reviewable](https://reviewable.io/reviews/llvm/llvm-project/115475)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @agozillon, @bhandarkar-pranav, @DominikAdamski, @ergawy, @jsjodin, @kparzysz, @Meinersbur, @mjklemm, @raghavendhra, @skatrak, @tblah, and @TIFitis)

___
*[`mlir/lib/Target/LLVMIR/Dialect/OpenMP/OpenMPToLLVMIRTranslation.cpp` line 482 at r1](https://reviewable.io/reviews/llvm/llvm-project/115475#-OBAuXhr0lTsRZE9mcbF:-OBAuXhr0lTsRZE9mcbG:b-ipecp3) ([raw file](https://github.com/llvm/llvm-project/blob/a18ac6599fb602c8b0abb17b9887a39c51d84e8e/mlir/lib/Target/LLVMIR/Dialect/OpenMP/OpenMPToLLVMIRTranslation.cpp#L482)):*
> ```cpp
>       builder.CreateBr(continuationBlock);
>       continue;
>     }
> ```

Can we write a test for this?


<!-- Sent from Reviewable.io -->

2024-11-08 13:33 UTC, skatrak commented
Thanks @kiranchandramohan for the quick review!

> Can we write a test for this?

At the moment we can't because this code path is not triggered by anything. Translation functions for loop wrappers currently call this function passing the region of the nested `omp.loop_nest`, so a loop wrapper region is never passed here. However, if you check the code directly below you can tell that this is doing the same thing as if an `omp.terminator` was present.

I think it's preferable to have this implemented before needing it rather than having it crash later on, since I think it was an oversight from when I implemented #112229. But let me know if you don't agree and I can keep it around until some composite construct lowering ends up triggering the issue.

2024-11-08 14:18 UTC, tblah approved these changes
This LGTM.

If there are currently no paths using this lowering, how did you find this bug? If you expect to upstream something in the near future that makes this testable (and you will make sure it is covered by tests for that thing) then I think it is okay.

2024-11-08 14:41 UTC, kiranchandramohan commented
> Thanks @kiranchandramohan for the quick review!
> 
> > Can we write a test for this?
> 
> At the moment we can't because this code path is not triggered by anything. Translation functions for loop wrappers currently call this function passing the region of the nested `omp.loop_nest`, so a loop wrapper region is never passed here. However, if you check the code directly below you can tell that this is doing the same thing as if an `omp.terminator` was present.
> 
> I think it's preferable to have this implemented before needing it rather than having it crash later on, since I think it was an oversight from when I implemented #112229. But let me know if you don't agree and I can keep it around until some composite construct lowering ends up triggering the issue.

The danger with this is that someone can remove this piece of code in refactoring and think it was accidentally introduced since no test fails. Ideally, such code can be introduced in the first patch that needs it. You can organize such patches as two commits, where the first commit is this patch and the second commit is the one that needs it

Note: I did not intend to request changes. I was trying reviewable.io and did not realise that it requested changes.

2024-11-08 14:41 UTC, kiranchandramohan approved these changes

2024-11-11 12:32 UTC, skatrak commented
> If there are currently no paths using this lowering, how did you find this bug?

> The danger with this is that someone can remove this piece of code in refactoring and think it was accidentally introduced since no test fails. Ideally, such code can be introduced in the first patch that needs it. You can organize such patches as two commits, where the first commit is this patch and the second commit is the one that needs it

Thank you both for your reviews. I found this bug through our current downstream support for 'distribute parallel do'. However, it will take a bit of time to get to upstreaming it, since other pieces must make it first, and there's a chance that we might want to rethink how we do it before then (potentially circumventing this code path). So I'll keep this PR around until we're ready to upstream the code that would trigger this failure, and I'll close it if we end up not needing it at that point.

2025-02-22 02:51 UTC, jsjodin approved these changes

2025-02-24 11:32 UTC, merged