MLIR-QUERY DefinitionsMatcher implementation & DAG
llvm/llvm-project pull request #115670
Opened 2024-11-10 22:15 UTC by chios202

This Pull Request aims to enhance the MLIR-QUERY tool by introducing a new matcher that identifies defining operations for a given operation, tracing back through dependencies up to n hops, including operations within regions. To support this functionality, a new data structure, BoundOperationsGraphBuilder, has been introduced. This structure constructs a Directed Acyclic Graph (DAG) to represent the relationships between operations, allowing for efficient dependency analysis. This addition will improve the tool's capability to query and understand how operations in MLIR modules are interrelated, which is crucial for debugging, optimization, and transformation tasks.

2025-01-10 06:55 UTC, jpienaar reviewed
Quick skim comments.

2025-01-10 06:55 UTC, jpienaar commented on mlir/include/mlir/IR/Matchers.h
> +  std::string name;
Why is this change needed?

2025-01-10 06:55 UTC, jpienaar commented on mlir/include/mlir/Query/Matcher/ExtraMatchers.h
> +//===- Matchers.h - Various common matchers ---------------------*- C++ -*-===//
You'd need to update the filename here.

2025-01-10 06:55 UTC, jpienaar commented on mlir/include/mlir/Query/Matcher/ExtraMatchers.h
> +// This file provides extra matchers that are very useful for mlir-query
All the matchers in this dir is for mlir-query.

2025-01-10 06:55 UTC, jpienaar commented on mlir/include/mlir/Query/Matcher/MatchersInternal.h
> +// Part of the LLVM Project, under the Apache License v2.0 wIth LLVM Exceptions.
Typo?

2025-01-10 06:55 UTC, jpienaar commented on mlir/lib/Query/Matcher/Parser.cpp
> +    // Try to recognize a floating point literal.
Where are floats needed in query?

2025-01-10 06:55 UTC, jpienaar commented on mlir/lib/Query/Query.cpp
> +        "  let NAME MATCHER, l NAME MATCHER  "
Could this be split out into it's own change?

2025-01-10 12:05 UTC, chios202 commented on mlir/include/mlir/IR/Matchers.h
> +  std::string name;
This change was necessary due to a bug I found while implementing the LetQuery. If one used hasOpName("arith.mulf") it would work just fine, but when used `let myMatch hasOpName("arith.mulf")` there was a dangling reference when the query was insterted into the `namedValues `container

2025-01-10 12:06 UTC, chios202 commented on mlir/lib/Query/Query.cpp
> +        "  let NAME MATCHER, l NAME MATCHER  "
We could do this

2025-01-10 12:09 UTC, chios202 commented on mlir/lib/Query/Matcher/Parser.cpp
> +    // Try to recognize a floating point literal.
They are not needed. I will remove the float parser part.

2025-01-10 12:46 UTC, dbudii commented on mlir/include/mlir/Query/Matcher/MatchersInternal.h
> +#include <vector>
Some of these can be removed too

2025-01-20 21:50 UTC, chios202 commented on mlir/include/mlir/Query/Matcher/ExtraMatchers.h
> +// This file provides extra matchers that are very useful for mlir-query
So I think we could remove this description?

2025-01-25 13:46 UTC, chios202 commented on mlir/lib/Query/Query.cpp
> +        "  let NAME MATCHER, l NAME MATCHER  "
I removed this feature

2025-01-25 13:47 UTC, chios202 commented on mlir/include/mlir/IR/Matchers.h
> +  std::string name;
I let this for now as it is, even though we are not introducing the LetQuery feature now. I think it's still a good thing to prevent future bugs, but I could revert this back to `StringRef`.

2025-02-03 03:15 UTC, jpienaar commented
I see the presubmit is failing on the newly added tests (mlir-query/complex-test.mlir failing)

2025-02-03 03:39 UTC, jpienaar requested changes

2025-02-03 03:39 UTC, jpienaar commented on mlir/include/mlir/Query/Matcher/ExtraMatchers.h
> +//===- ExtraMatchers.h - Various common matchers ---------------------*- C++
Nit: make fit on one line

2025-02-03 03:39 UTC, jpienaar commented on mlir/include/mlir/Query/Matcher/ExtraMatchers.h
> +// This file provides extra matchers that are very useful for mlir-query
Yes, SGTM. Should these even be merged with the others ? (e.g., I'm not sure when a matcher would be considered extra or not)

2025-02-03 03:39 UTC, jpienaar commented on mlir/include/mlir/Query/Matcher/ExtraMatchers.h
> +    if (op->hasTrait<OpTrait::IsIsolatedFromAbove>()) {
It would be good here to document behavior of BackwardSliceMatcher. Give a little example with a before and after. Helps with also talking about edge cases (is an op it is own backwardslice?)

2025-02-03 03:39 UTC, jpienaar commented on mlir/include/mlir/Query/Matcher/ExtraMatchers.h
> +    auto processValue = [&](Value value) {
Could mlir/include/mlir/Analysis/SliceAnalysis.h's methods be used here?

2025-02-03 03:39 UTC, jpienaar commented on mlir/include/mlir/Query/Matcher/ExtraMatchers.h
> +               QueryOptions &options, unsigned tempHops) {
Could you add documentation for the args? tempHops is a bit non-descriptive.

2025-02-03 03:39 UTC, jpienaar commented on mlir/include/mlir/Query/Matcher/ExtraMatchers.h
> +private:
Nit: I prefer keeping public section together followed by private, that way one sees the interface all together.

2025-02-03 03:39 UTC, jpienaar commented on mlir/include/mlir/Query/Matcher/ExtraMatchers.h
> +namespace mlir {
Use C++17 style nested namespace decl here.

2025-02-03 03:39 UTC, jpienaar commented on mlir/include/mlir/Query/Matcher/MatchFinder.h
> +private:
Same as above.

2025-02-03 03:39 UTC, jpienaar commented on mlir/include/mlir/Query/Matcher/MatchFinder.h
> +    unsigned matchCount = 0;
Lets use int here, prefer to use signed when doing arithmetic (https://groups.google.com/g/llvm-dev/c/q80EgETJGh0/m/hKCh7N4XAgAJ for context why I prefer it). The usage internally isn't consistent unfortunately.

2025-02-03 03:39 UTC, jpienaar commented on mlir/include/mlir/Query/Matcher/MatchFinder.h
> +            printMatch(os, qs, op, "root");
Would this result in marking these all as root?

2025-02-03 03:39 UTC, jpienaar commented on mlir/include/mlir/Query/Matcher/MatchersInternal.h
>  //
Accidental?

2025-02-03 03:39 UTC, jpienaar commented on mlir/include/mlir/Query/Matcher/MatchersInternal.h
>  // Matchers are methods that return a Matcher which provides a method
Update comment as there are multiple

2025-02-03 03:39 UTC, jpienaar commented on mlir/include/mlir/Query/Matcher/MatchersInternal.h
> +}
Missing comment. But also if this is just nested here, use C++17 nested namespace.

2025-02-03 03:39 UTC, jpienaar commented on mlir/include/mlir/Query/Matcher/MatchersInternal.h
> +struct has_simple_match<T, std::void_t<decltype(std::declval<T>().match(
Could you document these?

2025-02-03 03:39 UTC, jpienaar commented on mlir/include/mlir/Query/Matcher/VariantValue.h
> +  void setUnsigned(unsigned Unsigned);
MLIR's naming convention is camelBack (https://mlir.llvm.org/getting_started/DeveloperGuide/#style-guide).

2025-02-03 03:39 UTC, jpienaar commented on mlir/include/mlir/Query/Query.h
> +enum class QueryKind { Invalid, NoOp, Help, Match, Quit, SetBool };
Beyond Invalid, any reason to not have these sorted?

2025-02-03 03:39 UTC, jpienaar commented on mlir/include/mlir/Query/Query.h
> +struct QueryOptions {
This is part of public interface, lets use doxygen comments for.

2025-02-03 03:39 UTC, jpienaar commented on mlir/include/mlir/Query/QuerySession.h
> +}
Missing comment

2025-02-03 03:39 UTC, jpienaar commented on mlir/include/mlir/Query/QuerySession.h
> +  bool omitBlockArguments = false;
So these are set per query session?

2025-02-03 03:39 UTC, jpienaar commented on mlir/lib/Query/Matcher/Parser.cpp
> +  void consumeNumberLiteral(TokenInfo *result) {
Where is this called?

2025-02-03 03:39 UTC, jpienaar commented on mlir/test/mlir-query/complex-test.mlir
> +
Remove some of this vertical whitespace.

2025-02-03 03:39 UTC, jpienaar commented on mlir/test/mlir-query/complex-test.mlir
> +// CHECK: %[[COLLAPSED:.*]] = tensor.collapse_shape %0 {{\[\[.*\]\]}} : tensor<5x5xf32> into tensor<25xf32>
You are capturing on the output but not using the captured in operands, avoid hard coding there too.

2025-02-04 15:38 UTC, chios202 commented on mlir/include/mlir/Query/Matcher/ExtraMatchers.h
> +// This file provides extra matchers that are very useful for mlir-query
The naming is a bit redundant, I think a more fitting name could be ComplexMatchers or SliceMatchers. Moving them to mlir/include/mlir/IR/Matchers.h could also be a good approach I believe.

2025-02-04 15:41 UTC, chios202 commented on mlir/include/mlir/Query/QuerySession.h
> +  bool omitBlockArguments = false;
That's how I thought of it. The user sets these per query session. Should we consider a different approach for this?

2025-02-08 20:30 UTC, chios202 commented on mlir/include/mlir/Query/Matcher/ExtraMatchers.h
> +    auto processValue = [&](Value value) {
temHops parameter which specifies how far into the graph we are searching (how many levels) limits us to reuse code from mlir/include/mlir/Analysis/SliceAnalysis.h

2025-02-22 17:27 UTC, chios202 commented on mlir/include/mlir/Query/Matcher/ExtraMatchers.h
> +    auto processValue = [&](Value value) {
I think `maxDepth` would be more fitting for this parameter.

2025-02-23 15:10 UTC, chios202 commented on mlir/lib/Query/Matcher/Parser.cpp
> +  void consumeNumberLiteral(TokenInfo *result) {
It is called on line 148

2025-02-23 15:14 UTC, chios202 commented on mlir/include/mlir/Query/Matcher/ExtraMatchers.h
> +    if (op->hasTrait<OpTrait::IsIsolatedFromAbove>()) {
I added extensive documentation for these matchers and moved them to `Matchers.h` along with the existing ones. As you pointed out, I'm not sure they belonged in the `ExtraMatchers.h` file.

2025-02-23 15:20 UTC, chios202 commented on mlir/include/mlir/Query/Matcher/MatchersInternal.h
> +}
I omitted this, but I'll include it with any new changes. Otherwise, I'll include it anyway.

2025-02-25 07:10 UTC, chios202 commented on mlir/include/mlir/Query/Matcher/MatchFinder.h
> +              printMatch(os, qs, op, "root");
This should use the overloaded print method with no argument for the binding. I accidentally reverted this back to using the old method, but will update it accordingly with the next changes.

2025-02-25 17:00 UTC, jpienaar commented on mlir/include/mlir/Query/Matcher/MatchFinder.h
> +              printMatch(os, qs, op, "root");
SG

2025-02-27 05:30 UTC, jpienaar commented on mlir/include/mlir/Query/Query.h
> +  /// When omitUsesFromAbove is true, the matcher omits
Reflow paragraph to avoid extra whitespace

2025-02-27 05:30 UTC, jpienaar commented on mlir/lib/Query/Matcher/Parser.cpp
> +  void consumeNumberLiteral(TokenInfo *result) {
I was missing which query kinds were using it, so m_GetDefinitions is one of them.

2025-02-27 05:30 UTC, jpienaar commented on mlir/lib/Query/Matcher/Parser.cpp
> +    case '0':
Would this have previously parsed as an identifier?

2025-02-27 05:30 UTC, jpienaar commented on mlir/lib/Query/Matcher/Parser.cpp
> +    unsigned length = 1;
Wouldn't stringref consumeInteger also work here?

2025-02-27 05:30 UTC, jpienaar commented on mlir/lib/Query/Matcher/VariantValue.cpp
> +  assert(isSigned());
I can't see how this could possibly fail.

2025-02-27 05:30 UTC, jpienaar commented on mlir/lib/Query/Matcher/VariantValue.cpp
> +// Unsinged
Signed

2025-02-27 05:30 UTC, jpienaar commented on mlir/lib/Query/QueryParser.cpp
> +          .Case("set", ParsedQueryKind::Set)
Lets keep these in alphabetical order

2025-02-27 05:30 UTC, jpienaar commented on mlir/include/mlir/Query/Matcher/ExtraMatchers.h
> +    auto processValue = [&](Value value) {
Looking at it, it may be possible (but less efficient) by keeping track of the depth in a map and then having the filter return whether the minimum depth of any of the operation's argument's depth is greater or equal to maxDepth.

2025-02-27 06:51 UTC, chios202 commented on mlir/include/mlir/IR/Matchers.h
> +class BackwardSliceMatcher {
Yes, implementations would be better in a .cpp file

2025-03-01 12:39 UTC, chios202 commented on mlir/include/mlir/IR/Matchers.h
> +                << "Error: Expected parentOp to have exactly one region and "
This limitation comes from the original implementation of the algoritm; it's treated with an assert there (the parent op must have exactly one region with exactly one block). E.g: I think it would be tricky to figure out whether the other blocks are part of the slice (the flow into this block). I think it would be more fitting to treat this with an assert here too?

2025-03-03 09:31 UTC, chios202 commented on mlir/include/mlir/Query/Matcher/MatchFinder.h
> +  // print operations
Would we want to return a vector of vectors (each one containing rootOp + matching environment)  for printing and for reusability we could return a vector containing sequences of rootOp + matching environment?

2025-03-04 16:22 UTC, chios202 commented
A simple implementation where we would reuse most of the original logic while preserving a DFS approach would be: 
```cpp
llvm::DenseMap<Operation *, int64_t> opDepths;
    opDepths[rootOp] = 0;

    BackwardSliceOptions depthOptions = options;
    depthOptions.filter = [&](Operation *op) {
      for (auto operand : op->getOperands()) {
        if (auto definingOp = operand.getDefiningOp()) {
          if (!opDepths.count(definingOp)) {
            if (opDepths[op] > limitDepth) {
              return false;
            }
            opDepths[definingOp] = opDepths[op] + 1;
          }
        } else if (auto blockArgument = dyn_cast<BlockArgument>(operand)) {
          Operation *parentOp = blockArgument.getOwner()->getParentOp();
          if (!opDepths.count(parentOp)) {
            if (opDepths[op] > limitDepth) {
              return false;
            }
            opDepths[parentOp] = opDepths[op] + 1;
          }
        }
      }
      return true;
    };
    getBackwardSlice(rootOp, &backwardSlice, depthOptions);

2025-03-29 15:21 UTC, chios202 commented on mlir/lib/Dialect/Linalg/IR/LinalgOps.cpp
>                             ArrayRef<OpFoldResult> offsets,
I renamed this to avoid naming collision with SliceAnalysis::getSlice

2025-03-29 15:22 UTC, chios202 commented on mlir/lib/Query/Matcher/Parser.cpp
> +    unsigned length = 1;
It does. Thank you for the suggestion

2025-03-29 15:41 UTC, chios202 commented on mlir/include/mlir/Query/Matcher/MatchFinder.h
> +  // print operations
It now follows a similar design to clang-query's MatchFinder class

2025-03-29 15:46 UTC, chios202 commented on mlir/lib/Query/Query.cpp
>  static Operation *extractFunction(std::vector<Operation *> &ops,
Could this method be a candidate for the MatchFinder class?

2025-03-29 15:48 UTC, chios202 commented on mlir/lib/IR/Matchers.cpp
> +//===- Matchers.h - Various common matchers ---------------------*- C++ -*-===//
This should be Matchers.cpp

2025-04-01 17:33 UTC, chios202 commented on mlir/include/mlir/Query/Matcher/MatchFinder.h
> +  /// A subclass which preserves the matching information
I do think this class promotes modularity and aligns well with clang-query. I think more features could be incorporated that may be used in or outside the Query context. E.g : we could implement a method, addMatchers(Matcher, Callback), then once a matcher has returned, it's callback for can be invoked. We could also add a subclass, MatcherOptions (this could possibly include the QueryOptions)

2025-04-21 15:27 UTC, jpienaar reviewed
Is the example output in the PR description still the current output?

2025-04-21 15:27 UTC, jpienaar commented on mlir/include/mlir/IR/Matchers.h
> +    if (innerMatcher.match(op) &&
Just do

return innerMatcher.match(op) && matches(op, backwardSlice, options, maxDepth);

2025-04-21 15:27 UTC, jpienaar commented on mlir/include/mlir/Query/Matcher/MatchersInternal.h
> +#include "mlir/Analysis/SliceAnalysis.h"
Could this be in a different file? (have internal only be matcher internal details independent of any matchers)

2025-04-21 15:27 UTC, jpienaar commented on mlir/include/mlir/Query/Matcher/MatchersInternal.h
> +#include "mlir/Analysis/SliceAnalysis.h"
(I don't see any use here TBH)

2025-04-21 15:27 UTC, jpienaar commented on mlir/include/mlir/Query/Matcher/VariantValue.h
> +enum class ArgKind { Matcher, String, Signed };
Lets keep these sorted

2025-04-21 15:27 UTC, jpienaar commented on mlir/include/mlir/Query/QuerySession.h
> +#include "Matcher/VariantValue.h"
Lets add prefix (follow line 14)

2025-04-21 15:27 UTC, jpienaar commented on mlir/include/mlir/Query/QuerySession.h
> +  bool omitBlockArguments = false;
Yes, coming back with fresh eyes. These affect only one matcher (e.g., inclusive in isolation is difficult to interpret, while specific to backwards analysis its clear). Could these be made args of the matcher?

2025-04-21 15:27 UTC, jpienaar commented on mlir/lib/Dialect/Linalg/IR/LinalgOps.cpp
>                             ArrayRef<OpFoldResult> offsets,
Why is a naming conflict here a problem?

2025-04-21 15:27 UTC, jpienaar commented on mlir/lib/IR/Matchers.cpp
> +#include "mlir/Dialect/Tensor/IR/Tensor.h"
We can't have IR depend on Tensor either.

2025-04-21 15:27 UTC, jpienaar commented on mlir/lib/IR/Matchers.cpp
> +#include "mlir/Dialect/Tensor/IR/Tensor.h"
(but don't see need for it here)

2025-04-21 15:27 UTC, jpienaar commented on mlir/lib/IR/Matchers.cpp
> +        if (!opDepths.contains(definingOp)) {
Wouldn't it be the min of all the defining op's depth?

2025-04-21 15:27 UTC, jpienaar commented on mlir/lib/Query/Matcher/MatchFinder.cpp
> +      qs.getBufferId(), fileLoc.getLine(), fileLoc.getColumn());
You dyn\_cast but then query without checking if null. Either cast (so that at least one has an assert in non-opt builds) or check.

2025-04-21 15:27 UTC, jpienaar commented on mlir/lib/Query/Matcher/MatchFinder.cpp
> +      qs.getBufferId(), fileLoc.getLine(), fileLoc.getColumn());
You dyn\_cast but then query without checking if null. Either cast (so that at least one has an assert in non-opt builds) or check.

2025-04-21 15:27 UTC, jpienaar commented on mlir/lib/Query/Matcher/VariantValue.cpp
> +  reset();
Is this needed?

2025-04-21 15:27 UTC, jpienaar commented on mlir/lib/Query/Query.cpp
>  static Operation *extractFunction(std::vector<Operation *> &ops,
Yes, or even higher, such as a utility function in Analysis or Transform or so, as this is rather common.

2025-04-21 18:58 UTC, chios202 commented on mlir/lib/IR/Matchers.cpp
> +        if (!opDepths.contains(definingOp)) {
Good point

2025-04-22 08:03 UTC, chios202 commented on mlir/lib/Query/Matcher/Parser.cpp
> +    case '0':
From what I recall, yes. It would have parsed an identifier, resulting in a `TokenKind::InvalidChar`

2025-04-22 12:47 UTC, chios202 commented on mlir/lib/Query/Matcher/MatchFinder.cpp
> +      qs.getBufferId(), fileLoc.getLine(), fileLoc.getColumn());
I did cast. The reasoning behind it being that, ideally this the file location should always be available?

2025-04-22 14:42 UTC, chios202 commented on mlir/lib/Query/Query.cpp
>  static Operation *extractFunction(std::vector<Operation *> &ops,
I could move it to MatchFinder. I could also create an issue for this and assign it to myself. I’d need to investigate where in Analysis or Transform would be the most suitable place.

2025-04-22 19:26 UTC, chios202 commented
I'm not sure why complex-test.mlir is failing in CI for Linux. Locally I use wsl and it seems to pass. Also I did not modify the printing logic.

2025-04-23 13:19 UTC, chios202 commented on mlir/include/mlir/IR/Matchers.h
> +#include "mlir/Query/Matcher/MatchersInternal.h"
Looking at it again, I think it may be possible to make `BackwardSlice` matcher not to depend on `MatcherInternals` , but I'm not so sure about the dependency on Analysis, I think it may be possible with the use of a function pointer.

2025-05-04 12:28 UTC, chios202 commented
@jpienaar could you provide feedback on the latest changes?

2025-05-12 18:05 UTC, chios202 commented on mlir/test/mlir-query/complex-test.mlir
> +func.func @slice_use_from_above(%arg0: tensor<5x5xf32>, %arg1: tensor<5x5xf32>) {
I've copied this test from `mlir/test/IR/slice.mlir`  I coud at least rename it to "slicing-query" and/or change the contents to avoid duplication?

2025-05-13 07:48 UTC, jpienaar reviewed
I think this look overall good. Thanks. Lets do the one rename you were also thinking about, and then can approve. Do you need help landing it?

2025-05-13 11:18 UTC, merged