[lld][Hexagon] Fix R_HEX_B22_PCREL range checks
llvm/llvm-project pull request #115925
Opened 2024-11-12 19:00 UTC by quic-akaryaki

Range checks for R_HEX_B22_PCREL did not account for the fact that offset is measured in instructions, not bytes.

Add a test for all range-checked relocations.

2024-11-12 21:22 UTC, androm3da approved these changes

2024-11-12 22:00 UTC, androm3da commented on lld/test/ELF/hexagon-jump.s
> +# CHECK: 1000010: {  jump 0x1800000 }
Should these / can these be `CHECK-NEXT` instead?

2024-11-13 17:29 UTC, MaskRay requested changes
We should not add a new test lld/test/ELF/hexagon-jump.s here. Just reuse the existing positive test than tests B22_PCREL.

2024-11-13 19:35 UTC, quic-akaryaki commented
> We should not add a new test lld/test/ELF/hexagon-jump.s here. Just reuse the existing positive test than tests B22_PCREL.
What is the drawback of adding a test file for a specific purpose?
The new test has specific layout requirements, which will make it more difficult to maintain the combined test.
But I can do that.

2024-11-19 03:36 UTC, androm3da approved these changes

2024-11-19 06:43 UTC, MaskRay approved these changes

2024-11-19 15:27 UTC, merged