[clang][Driver] Use shared_ptr in the Compilation class
llvm/llvm-project pull request #116406
Opened 2024-11-15 16:27 UTC by vhscampos

This patch replaces uses of raw pointers by shared_ptrs in the Driver's Compilation class.

The manual memory management which was done before this patch could be error prone. Plus, code is now simpler.

2024-11-18 14:35 UTC, DavidTruby requested changes
Thanks for the patch!
I don't think there's any actual shared ownership happening here so I think you could use `unique_ptr` instead, and that has lower overhead so would be preferable I think.

I've left a comment as to why the patch fails the CI at the moment too.

2024-11-27 12:44 UTC, vhscampos commented on clang/lib/Driver/Driver.cpp
> +                                   std::move(TranslatedArgs), ContainsError);
Thanks for the information. I've fixed the issues.

2024-11-30 05:01 UTC, MaskRay requested changes
Using unique_ptr for `Args` is good, but I am not sure about shared_ptr for TranslatedArgs. There is no shared_ptr usage in clangDriver and we want to keep avoiding it.

2024-12-02 14:13 UTC, DavidTruby reviewed
I think you still don't need any of the shared_ptr usage here, there's no shared ownership semantics. If you change all these to unique_ptr then I think the patch would look good to me.

2024-12-02 14:13 UTC, DavidTruby commented on clang/include/clang/Driver/Compilation.h
> +  std::shared_ptr<llvm::opt::DerivedArgList> TranslatedArgs;
This can be a unique_ptr as well; TranslatedArgs is fully owned by the Compilation class and doesn't share ownership with anyone else.

2024-12-02 14:13 UTC, DavidTruby commented on clang/lib/Driver/Compilation.cpp
> +  std::shared_ptr<DerivedArgList> &Entry =
You can just use a reference to the unique_ptr here, since no ownership is being taken.

2024-12-02 14:13 UTC, DavidTruby commented on clang/lib/Driver/Compilation.cpp
> +    std::shared_ptr<DerivedArgList> OpenMPArgs;
```suggestion
    std::unique_ptr<DerivedArgList> OpenMPArgs;
```

2025-11-28 13:04 UTC, closed without merging