[DA] disambiguate evolution of base addresses
llvm/llvm-project pull request #116628
Opened 2024-11-18 14:22 UTC by sebpop

This patch fixes two bugs:
https://github.com/llvm/llvm-project/issues/41488
https://github.com/llvm/llvm-project/issues/53942

The dependence analysis assumes that the base address of array accesses is invariant across loop iterations. In both bugs the base address evolves following loop iterations: the base address flip-flops between two different memory objects.

Based on the scalar evolution of base addresses, the patch adds code to separate the 3 alias cases {must, no, may}-alias where the base addresses are identical at every iteration, never the same, and unknown.

2024-11-19 13:54 UTC, nikic requested changes
I think the overall approach here isn't right. This is basically trying to mitigate a specific case in the BasicAA implementation, but doesn't really provide a guarantee that we can't hit the same underlying issue through a different pathway. I would expect that it's possible to construct a similar problematic case using selects instead of phis.

I think the correct way to address this issue would be to enable the cross-iteration mode of AA, which is also what LAA does. However, it currently doesn't actually catch the examples here, which I'm addressing in https://github.com/llvm/llvm-project/pull/116802.

Though I should also note that doing this alone is not sufficient to make this code correct, because it *also* makes an additional incorrect assumptions about AATags. In particular, this will handle scoped noalias metadata incorrectly for cases where the metadata is only valid within one loop iteration. It is necessary to inspect noalias.scope intrinsics to disambiguate these cases.

2024-11-27 15:59 UTC, nikic reviewed
Now that https://github.com/llvm/llvm-project/pull/116802 has landed, I think you should be able to fix the issue using BatchAAResults::enableCrossIterationMode.

2024-12-12 21:45 UTC, sebpop commented
I see 2 extra errors when using BatchAA in cross iter mode:
```
  LLVM :: Analysis/DependenceAnalysis/AA.ll
  LLVM :: Analysis/DependenceAnalysis/NonAffineExpr.ll
```
Both fails are in https://github.com/llvm/llvm-project/blob/main/llvm/lib/Analysis/BasicAliasAnalysis.cpp#L1620 where the dyn_cast<Instruction> fails for some reason on a LoadInst.
@nikic could you please have a look? It's in the patch you pointed out above.

2024-12-12 21:49 UTC, nikic commented
@sebpop Just from a quick look, it's probably because IR is modified during BatchAA lifetime and the cache becomes invalid. To start with you can just create the BatchAA directly inside underlyingObjectsAlias (without any batching). It would be nice to use it in a larger scope for compile-time reasons, but it requires some more care.

2024-12-13 11:45 UTC, nikic approved these changes
LGTM, thanks!

2024-12-13 11:45 UTC, nikic commented on llvm/test/Analysis/DependenceAnalysis/FlipFlopBaseAddress.ll
> +; RUN: opt < %s -disable-output "-passes=print<da>" -aa-pipeline=basic-aa 2>&1 \
Can use the update_analyze_checks support you added recently?

2025-01-30 04:53 UTC, merged

2025-07-09 18:25 UTC, kasuga-fj commented
Unfortunately, it appears that this patch doesn't seem to resolve the original issues.  Consider the following case: 

```llvm
; // Pseudo code
; void f(int A[][42]) {
;   for (int i = 0; i < 100; i++)
;     for (int j = 0; j < 41; j++)
;       (j % 2 == 0 ? A[i][j] : A[i][j+1]) = 1;
; }
;
define void @f(ptr %A) {
entry:
  br label %loop.i.header

loop.i.header:
  %i = phi i32 [ 0, %entry ], [ %i.inc, %loop.i.latch ]
  %A1 = getelementptr i32, ptr %A, i32 1
  br label %loop.j

loop.j:
  %j = phi i32 [ 0, %loop.i.header ], [ %j.inc, %loop.j ]
  %ptr0 = phi ptr [ %A, %loop.i.header ], [ %ptr1, %loop.j ]
  %ptr1 = phi ptr [ %A1, %loop.i.header ], [ %ptr0, %loop.j ]
  %idx = getelementptr [42 x i32], ptr %ptr0, i32 %i, i32 %j
  store i32 1, ptr %idx
  %j.inc = add i32 %j, 1
  %cmp.j = icmp slt i32 %j.inc, 41
  br i1 %cmp.j, label %loop.j, label %loop.i.latch

loop.i.latch:
  %i.inc = add i32 %i, 1
  %cmp.i = icmp slt i32 %i.inc, 100
  br i1 %cmp.i, label %loop.i.header, label %exit

exit:
  ret void
}
```

Here is the result of running DA with the above IR as input (command: `opt --passes=print<da> -aa-pipeline=basic-aa`)

```
Printing analysis 'Dependence Analysis' for function 'f':
Src:  store i32 1, ptr %idx, align 4 --> Dst:  store i32 1, ptr %idx, align 4
  da analyze - none!
```

(godbolt: https://godbolt.org/z/W6bcMY96f)

IIUIC, this result is incorrect because the same address will be accessed by the store instruction in different iterations, e.g., the value of `%idx` will be the same whether `(i, j)` is `(0, 1)` or `(0, 2)`.

As mentioned in the description of #53942 , we also make an assumption that the base pointer is invariant in all loops, which is wrong in general. Probably we must check if it holds before trying delinearization.

Let me know if I misunderstood something.