Add sinf16 function
llvm/llvm-project pull request #116674
Opened 2024-11-18 18:38 UTC by wldfngrs

Sin for 16-bit floating point input

2024-11-22 23:39 UTC, wldfngrs commented
@lntue please review

2024-11-23 23:35 UTC, overmighty commented on libc/src/math/generic/sinf16.cpp
> +//===-- Half-precision sin function ------------------------------------===//
Nit: formatting.

```suggestion
//===-- Half-precision sin(x) function ------------------------------------===//
```

2024-11-23 23:35 UTC, overmighty commented on libc/test/src/math/sinf16_test.cpp
> +//===---------------------------------------------------------------------===//
Nit: formatting.

```suggestion
//===----------------------------------------------------------------------===//
```

2024-11-27 17:51 UTC, overmighty requested changes

2024-11-27 17:51 UTC, overmighty commented on libc/src/math/generic/sinf16.cpp
> +  using FPBits = typename fputil::FPBits<float16>;
`typename` is redundant here.

```suggestion
  using FPBits = fputil::FPBits<float16>;
```

2024-11-27 17:51 UTC, overmighty commented on libc/src/math/generic/sinf16.cpp
> +  // For !x| > pi/32, we perform range reduction as follows:
```suggestion
  // For |x| > pi/32, we perform range reduction as follows:
```

2024-11-27 17:51 UTC, overmighty commented on libc/src/math/generic/sinf16.cpp
> +  if (LIBC_UNLIKELY(x_abs == 0x585C || x_abs == 0x5cb0 || x_abs == 0x51f5)) {
Nit: stick to lowercase hexadecimal for consistency.

```suggestion
  if (LIBC_UNLIKELY(x_abs == 0x585c || x_abs == 0x5cb0 || x_abs == 0x51f5)) {
```

2024-11-27 17:51 UTC, overmighty commented on libc/src/math/generic/sinf16.cpp
> +  if (LIBC_UNLIKELY(x_abs <= 0x13d0)) {
Could you add comments for all these cases from here to line 83?

2024-11-27 17:51 UTC, overmighty commented on libc/src/math/generic/sinf16.cpp
> +    if (x_abs == 0x7c00) {
Could use `xbits.is_inf_or_nan()` and `xbits.is_inf()` for readability.

2024-12-02 09:52 UTC, overmighty commented on libc/src/math/generic/sinf16.cpp
> +  // - When x < 0, and rounding upward, sin(x) == (x - 1ULP)
Nit: I think writing what `0x13d0` corresponds to in hex float notation would be more helpful, and each "When ..., sin(x) = ..." comment should be put right above the corresponding `if` statement.

2024-12-03 11:55 UTC, overmighty commented on libc/src/math/generic/sinf16.cpp
>        return x;
The comments don't seem to match the code here.

```suggestion
    // sin(+/-0) = +/-0
    if (LIBC_UNLIKELY(x_abs == 0U))
      return x;

    // When x > 0, and rounding upward, sin(x) == x.
    // When x < 0, and rounding downward, sin(x) == x.
    if ((rounding == FE_UPWARD && xbits.is_pos()) ||
        (rounding == FE_DOWNWARD && xbits.is_neg()))
      return x;
```

2024-12-03 15:05 UTC, overmighty approved these changes

2024-12-03 19:02 UTC, overmighty requested changes

2024-12-03 19:09 UTC, overmighty approved these changes

2024-12-03 20:08 UTC, merged