[libc] Set default visibility for LLVM functions
llvm/llvm-project pull request #116686
Opened 2024-11-18 19:38 UTC by petrhosek

This is a follow up to 5ff3ff3 addressing the issue reported in #74881.

2024-11-18 19:49 UTC, nickdesaulniers approved these changes
Thanks! This produces the global visibility for the non-namespeaced symbols that was accidentally regressed by 5ff3ff33ff930e4ec49da7910612d8a41eb068cb.

Though, I do wonder if the diff I proposed in https://github.com/llvm/llvm-project/issues/74881#issue-2033161156 perhaps would have been a smaller incision than 665efe896746b1dd138773e6e4d300ec97de27c2  + 5ff3ff33ff930e4ec49da7910612d8a41eb068cb ?

One potential issue with this patch might be that users who do use `-DLLVM_LIBC_FUNCTION_ATTR` may be surprised that they may need to re-set default visibility.

We probably should document `LLVM_LIBC_FUNCTION_ATTR` on https://libc.llvm.org/configure.html.

2024-11-18 20:00 UTC, nickdesaulniers commented
> One potential issue with this patch might be that users who do use -DLLVM_LIBC_FUNCTION_ATTR may be surprised that they may need to re-set default visibility.

Something like:
```diff
diff --git a/libc/src/__support/common.h b/libc/src/__support/common.h
index 20d6f4c4a2af..d11a0b557570 100644
--- a/libc/src/__support/common.h
+++ b/libc/src/__support/common.h
@@ -18,14 +18,14 @@
 #include "src/__support/macros/properties/architectures.h"
 
 #ifndef LLVM_LIBC_FUNCTION_ATTR
-#define LLVM_LIBC_FUNCTION_ATTR [[gnu::visibility("default")]]
+#define LLVM_LIBC_FUNCTION_ATTR
 #endif
 
 // MacOS needs to be excluded because it does not support aliasing.
 #if defined(LIBC_COPT_PUBLIC_PACKAGING) && (!defined(__APPLE__))
 #define LLVM_LIBC_FUNCTION_IMPL(type, name, arglist)                           \
-  LLVM_LIBC_FUNCTION_ATTR decltype(LIBC_NAMESPACE::name)                       \
-      __##name##_impl__ __asm__(#name);                                        \
+  LLVM_LIBC_FUNCTION_ATTR [[gnu::visibility("default")]]                       \
+  decltype(LIBC_NAMESPACE::name) __##name##_impl__ __asm__(#name);             \
   decltype(LIBC_NAMESPACE::name) name [[gnu::alias(#name)]];                   \
   type __##name##_impl__ arglist
 #else
```
might avoid that, but I guess I don't know if downstream you're specifically trying to avoid default visibility on the non-namespaced symbols by setting `LLVM_LIBC_FUNCTION_ATTR`?

2024-11-18 21:57 UTC, nickdesaulniers commented
> see for example: https://cs.opensource.google/fuchsia/fuchsia/+/main:zircon/system/ulib/c/BUILD.gn;l=184;drc=4cd8bba05cb37d30da9eb365b369ed0a0bb43267.

Right, that's exactly what bionic would need to do, too, without this PR. Once this PR lands, Bionic (and zircon, I suspect) no longer need to set `LLVM_LIBC_FUNCTION_ATTR` to default vis.

> That's why we provide the LLVM_LIBC_FUNCTION_ATTR macro

If that's the only downstream use case...and this PR fixes that use case...

> I cannot think of a reason why we'd ever want to expose the internal symbols

💯 hence #74881.

2024-11-19 01:34 UTC, vonosmas commented
> > That's why we provide the LLVM_LIBC_FUNCTION_ATTR macro
> 
> If that's the only downstream use case...and this PR fixes that use case...

FWIW LLVM_LIBC_FUNCTION_ATTR is used to set the default visibility in the default Bazel configuration as well:

https://github.com/llvm/llvm-project/blob/6626ed6f9fae79d35aba504f50bac4375686a03b/utils/bazel/llvm-project-overlay/libc/libc_build_rules.bzl#L116

2024-11-19 18:58 UTC, nickdesaulniers commented
> FWIW LLVM_LIBC_FUNCTION_ATTR is used to set the default visibility in the default Bazel configuration as well:

So now that's three cases where downstream users are using `LLVM_LIBC_FUNCTION_ATTR` just to set the non-namespaced symbols to default visibility! :vomiting_face: 
1. [Fuchsia](https://cs.opensource.google/fuchsia/fuchsia/+/main:zircon/system/ulib/c/BUILD.gn;l=184;drc=4cd8bba05cb37d30da9eb365b369ed0a0bb43267)
2. [Android](https://cs.android.com/android/platform/superproject/main/+/main:external/llvm-libc/Android.bp;l=41)
3. [Bazel](https://github.com/llvm/llvm-project/blob/6626ed6f9fae79d35aba504f50bac4375686a03b/utils/bazel/llvm-project-overlay/libc/libc_build_rules.bzl#L114-L120)

(Bazel is also using LLVM_LIBC_FUNCTION_ATTR to add weak linkage attributes, but I think that can be better solved by @lntue's https://github.com/llvm/llvm-project/pull/116160).

So I think we should:
1. always mark the non-namespaced symbols as default visibility. (See diff below)
2. remove LLVM_LIBC_FUNCTION_ATTR, as there don't appear to be any downstream use cases other than fixing the visibility, which is better addressed by 1 above. Maybe a use case comes back in the future, at which point I'm happy to revisit adding it.

My suggestion for 1 above would look like:
```diff
diff --git a/libc/src/__support/common.h b/libc/src/__support/common.h
index 48c773fa02c1..45ded79f061a 100644
--- a/libc/src/__support/common.h
+++ b/libc/src/__support/common.h
@@ -24,6 +24,7 @@
 // MacOS needs to be excluded because it does not support aliasing.
 #if defined(LIBC_COPT_PUBLIC_PACKAGING) && (!defined(__APPLE__))
 #define LLVM_LIBC_FUNCTION_IMPL(type, name, arglist)                           \
+  [[gnu::visibility("default")]]                                               \
   LLVM_LIBC_FUNCTION_ATTR decltype(LIBC_NAMESPACE::name)                       \
       __##name##_impl__ __asm__(#name);                                        \
   decltype(LIBC_NAMESPACE::name) name [[gnu::alias(#name)]];                   \
```

My suggestion for 2 (stacked on top of 1) would look like:
```diff
diff --git a/libc/src/__support/common.h b/libc/src/__support/common.h
index 45ded79f061a..5bb08c6a1195 100644
--- a/libc/src/__support/common.h
+++ b/libc/src/__support/common.h
@@ -17,16 +17,11 @@
 #include "src/__support/macros/config.h"
 #include "src/__support/macros/properties/architectures.h"
 
-#ifndef LLVM_LIBC_FUNCTION_ATTR
-#define LLVM_LIBC_FUNCTION_ATTR
-#endif
-
 // MacOS needs to be excluded because it does not support aliasing.
 #if defined(LIBC_COPT_PUBLIC_PACKAGING) && (!defined(__APPLE__))
 #define LLVM_LIBC_FUNCTION_IMPL(type, name, arglist)                           \
   [[gnu::visibility("default")]]                                               \
-  LLVM_LIBC_FUNCTION_ATTR decltype(LIBC_NAMESPACE::name)                       \
-      __##name##_impl__ __asm__(#name);                                        \
+  decltype(LIBC_NAMESPACE::name) __##name##_impl__ __asm__(#name);             \
   decltype(LIBC_NAMESPACE::name) name [[gnu::alias(#name)]];                   \
   type __##name##_impl__ arglist
 #else
```
(There's a few other mentions of `LLVM_LIBC_FUNCTION_ATTR` in comments/docs to clean up, too.  utils/bazel/llvm-project-overlay/libc/libc_build_rules.bzl would have to get cleaned up, too).

Thoughts?

2024-11-19 19:01 UTC, jhuber6 requested changes
We do not want every symbol to have default visibility without some config. This will be very, very bad for the GPU case which wants LTO to be able to internalize these symbols.

2024-11-19 21:18 UTC, nickdesaulniers commented
@jhuber6 thoughts?
```diff
diff --git a/libc/cmake/modules/LLVMLibCCompileOptionRules.cmake b/libc/cmake/modules/LLVMLibCCompileOptionRules.cmake
index 65851f1c8657..2686655f9f0f 100644
--- a/libc/cmake/modules/LLVMLibCCompileOptionRules.cmake
+++ b/libc/cmake/modules/LLVMLibCCompileOptionRules.cmake
@@ -184,7 +184,6 @@ function(_get_common_compile_options output_var flags)
   endif()
   if (LIBC_TARGET_OS_IS_GPU)
     list(APPEND compile_options "-nogpulib")
-    list(APPEND compile_options "-fvisibility=hidden")
     list(APPEND compile_options "-fconvergent-functions")
     list(APPEND compile_options "-flto")
     list(APPEND compile_options "-Wno-multi-gpu")
diff --git a/libc/src/__support/common.h b/libc/src/__support/common.h
index 45ded79f061a..92e985964f8c 100644
--- a/libc/src/__support/common.h
+++ b/libc/src/__support/common.h
@@ -21,10 +21,16 @@
 #define LLVM_LIBC_FUNCTION_ATTR
 #endif
 
+#ifdef LIBC_TARGET_ARCH_IS_GPU
+#define LIBC_PUBLIC_VIS [[gnu::visibility("hidden")]]
+#else
+#define LIBC_PUBLIC_VIS [[gnu::visibility("default")]]
+#endif
+
 // MacOS needs to be excluded because it does not support aliasing.
 #if defined(LIBC_COPT_PUBLIC_PACKAGING) && (!defined(__APPLE__))
 #define LLVM_LIBC_FUNCTION_IMPL(type, name, arglist)                           \
-  [[gnu::visibility("default")]]                                               \
+  LIBC_PUBLIC_VIS                                                              \
   LLVM_LIBC_FUNCTION_ATTR decltype(LIBC_NAMESPACE::name)                       \
       __##name##_impl__ __asm__(#name);                                        \
   decltype(LIBC_NAMESPACE::name) name [[gnu::alias(#name)]];                   \
```

2024-11-19 21:20 UTC, jhuber6 commented
> @jhuber6 thoughts?
> 
> ```diff
> diff --git a/libc/cmake/modules/LLVMLibCCompileOptionRules.cmake b/libc/cmake/modules/LLVMLibCCompileOptionRules.cmake
> index 65851f1c8657..2686655f9f0f 100644
> --- a/libc/cmake/modules/LLVMLibCCompileOptionRules.cmake
> +++ b/libc/cmake/modules/LLVMLibCCompileOptionRules.cmake
> @@ -184,7 +184,6 @@ function(_get_common_compile_options output_var flags)
>    endif()
>    if (LIBC_TARGET_OS_IS_GPU)
>      list(APPEND compile_options "-nogpulib")
> -    list(APPEND compile_options "-fvisibility=hidden")
>      list(APPEND compile_options "-fconvergent-functions")
>      list(APPEND compile_options "-flto")
>      list(APPEND compile_options "-Wno-multi-gpu")
> diff --git a/libc/src/__support/common.h b/libc/src/__support/common.h
> index 45ded79f061a..92e985964f8c 100644
> --- a/libc/src/__support/common.h
> +++ b/libc/src/__support/common.h
> @@ -21,10 +21,16 @@
>  #define LLVM_LIBC_FUNCTION_ATTR
>  #endif
>  
> +#ifdef LIBC_TARGET_ARCH_IS_GPU
> +#define LIBC_PUBLIC_VIS [[gnu::visibility("hidden")]]
> +#else
> +#define LIBC_PUBLIC_VIS [[gnu::visibility("default")]]
> +#endif
> +
>  // MacOS needs to be excluded because it does not support aliasing.
>  #if defined(LIBC_COPT_PUBLIC_PACKAGING) && (!defined(__APPLE__))
>  #define LLVM_LIBC_FUNCTION_IMPL(type, name, arglist)                           \
> -  [[gnu::visibility("default")]]                                               \
> +  LIBC_PUBLIC_VIS                                                              \
>    LLVM_LIBC_FUNCTION_ATTR decltype(LIBC_NAMESPACE::name)                       \
>        __##name##_impl__ __asm__(#name);                                        \
>    decltype(LIBC_NAMESPACE::name) name [[gnu::alias(#name)]];                   \
> ```

If we're going this route it should put in `config.json` and also allow users to specify via CMake.

2024-11-19 22:19 UTC, petrhosek commented
> > FWIW LLVM_LIBC_FUNCTION_ATTR is used to set the default visibility in the default Bazel configuration as well:
> 
> So now that's three cases where downstream users are using `LLVM_LIBC_FUNCTION_ATTR` just to set the non-namespaced symbols to default visibility! 🤮
> 
> 1. [Fuchsia](https://cs.opensource.google/fuchsia/fuchsia/+/main:zircon/system/ulib/c/BUILD.gn;l=184;drc=4cd8bba05cb37d30da9eb365b369ed0a0bb43267)
> 2. [Android](https://cs.android.com/android/platform/superproject/main/+/main:external/llvm-libc/Android.bp;l=41)
> 3. [Bazel](https://github.com/llvm/llvm-project/blob/6626ed6f9fae79d35aba504f50bac4375686a03b/utils/bazel/llvm-project-overlay/libc/libc_build_rules.bzl#L114-L120)
> 
> (Bazel is also using LLVM_LIBC_FUNCTION_ATTR to add weak linkage attributes, but I think that can be better solved by @lntue's #116160).
>
> (There's a few other mentions of `LLVM_LIBC_FUNCTION_ATTR` in comments/docs to clean up, too. utils/bazel/llvm-project-overlay/libc/libc_build_rules.bzl would have to get cleaned up, too).
> 
> Thoughts?

This is a flawed analysis because it ignores all users that don't set `LLVM_LIBC_FUNCTION_ATTR` because they want hidden visibility. Even in Fuchsia, we build LLVM libc several times for several different use cases, and only one of those is using `[[gnu::visibility("default")]]`, that is when building `libc.so`. In general, I think `libc.so` is probably the only case where you want `[[gnu::visibility("default")]]`, for all other cases `[[gnu::visibility("hidden")]]` is preferable.

I agree with @jhuber6, I think we should keep `LLVM_LIBC_FUNCTION_ATTR` and introduce a new `config.json` option to let you set the default (and if unset we should default to hidden).

2024-11-19 22:22 UTC, jhuber6 commented
> I agree with @jhuber6, I think we should keep `LLVM_LIBC_FUNCTION_ATTR` and introduce a new `config.json` option to let you set the default (and if unset we should default to hidden).

IMO, the default visibility of `libc.a` should be hidden and `lib.so` should be default. Maybe some day we'll install `libc.so`, my understanding is that it is contingent on having `dl.so` functioning.

2024-11-19 22:28 UTC, petrhosek commented
> > I agree with @jhuber6, I think we should keep `LLVM_LIBC_FUNCTION_ATTR` and introduce a new `config.json` option to let you set the default (and if unset we should default to hidden).
> 
> IMO, the default visibility of `libc.a` should be hidden and `lib.so` should be default. Maybe some day we'll install `libc.so`, my understanding is that it is contingent on having `dl.so` functioning.

While you cannot build `libc.so` purely out of LLVM libc (yet), there are several projects that combine LLVM libc with downstream bits to build `libc.so` (effectively linking `libllvmlibc.a` into `libc.so`), for example Fuchsia or Android, and that use case requires default visibility.

2024-11-21 00:44 UTC, nickdesaulniers commented
Closing; @petrhosek and @frobtech were able to answer the remaining questions I had related to this.

2024-11-21 00:44 UTC, closed without merging

2024-11-21 16:59 UTC, lntue commented
also, technically users can use something like `-DLIBC_COMPILE_OPTIONS_DEFAULT="-DLLVM_LIBC_FUNCTION_ATTR=..."` in the cmake invocation if needed?