[libc++] Update the status for lwg-3120
llvm/llvm-project pull request #116772
Opened 2024-11-19 09:39 UTC by love1angel

Current implementation already have struct __initial_descriptor which saves the initial state.
When release() called, we will reset ptr __initial_descriptor.__cur_.

This path update the lwg 3120 issue latest status.

Close #104274

2024-11-19 09:47 UTC, love1angel commented
the two example provided in https://cplusplus.github.io/LWG/issue3120 is also tested.

## example 1 provided
``` cpp
#include <memory_resource>

int main() 
{
  char buffer[100];
  {
    std::pmr::monotonic_buffer_resource mr(buffer, 100, std::pmr::null_memory_resource());
    mr.release();
    mr.allocate(60);  // A
  }
  {
    std::pmr::monotonic_buffer_resource mr(buffer, 100, std::pmr::null_memory_resource());
    mr.allocate(60);  // B
    mr.release();
    mr.allocate(60);  // C
  }
}
```

below is the test result
``` text
[4/5] Building CXX object CMakeFiles/main.dir/main.cpp.o
/Users/heli/github/cpp/main.cpp:9:5: warning: ignoring return value of function declared with 'nodiscard' attribute [-Wunused-result]
    9 |     mr.allocate(60);  // A
      |     ^~~~~~~~~~~
/Users/heli/github/cpp/main.cpp:13:5: warning: ignoring return value of function declared with 'nodiscard' attribute [-Wunused-result]
   13 |     mr.allocate(60);  // B
      |     ^~~~~~~~~~~
/Users/heli/github/cpp/main.cpp:15:5: warning: ignoring return value of function declared with 'nodiscard' attribute [-Wunused-result]
   15 |     mr.allocate(60);  // C
      |     ^~~~~~~~~~~
3 warnings generated.
[5/5] Linking CXX executable main
 heli@helis-MacBook-Pro ~/github/cpp  cmake --build build --parallel 3 && ./build/main
```

## example 2 provided

``` cpp
std::pmr::monotonic_buffer_resource mr(std::pmr::new_delete_resource());
for (int i=0; i < 100; ++i) {
  mr.allocate(1);  // D
  mr.release();
}
```

i tested it through this, A, B, C is succeess.
``` cpp
#include <memory_resource>
#include <print>

class MyPmr : public std::pmr::memory_resource {
public:
    explicit MyPmr(std::pmr::memory_resource* upstream)
        : m_upstream(upstream)
    {
    }

private:
    void* do_allocate(size_t bytes, size_t align) override
    {
        std::println("allocate: {}, {}", bytes, align);
        void* p = m_upstream->allocate(bytes, align);
        return p;
    }

    void do_deallocate(void* p, size_t bytes, size_t align) override
    {
        std::println("deallocate: {}, {}, {}", p, bytes, align);
        m_upstream->deallocate(p, bytes, align);
    }

    bool do_is_equal(memory_resource const& other) const noexcept override
    {
        return other.is_equal(*m_upstream);
    }

private:
    std::pmr::memory_resource* m_upstream;
};

int main()
{
    MyPmr s { std::pmr::new_delete_resource() };
    std::pmr::monotonic_buffer_resource mr { &s };
    for (int i = 0; i < 100; ++i) {
        mr.allocate(1); // D
        mr.release();
    }
}
```

which output always
``` text
deallocate: 0x122809200, 2080, 8
allocate: 2080, 8
deallocate: 0x122809200, 2080, 8
allocate: 2080, 8
deallocate: 0x122809200, 2080, 8
allocate: 2080, 8
deallocate: 0x122809200, 2080, 8
allocate: 2080, 8
deallocate: 0x122809200, 2080, 8
allocate: 2080, 8
deallocate: 0x122809200, 2080, 8
```
means we don't increase the next buffer size.

2024-11-19 12:00 UTC, love1angel commented on libcxx/docs/Status/Cxx23Issues.csv
> +"`LWG3120 <https://wg21.link/LWG3120>`__","Unclear behavior of ``monotonic_buffer_resource::release()``","2020-11 (Virtual)","|Nothing To Do|","",""
done, thanks.

2024-11-19 12:44 UTC, frederick-vs-ja approved these changes

2024-11-19 13:01 UTC, love1angel commented
Hi, @frederick-vs-ja, also, can you assign the [lwg 3143](https://github.com/llvm/llvm-project/issues/104258) issue to me? I also working on this. thanks in advance

2024-11-19 16:44 UTC, frederick-vs-ja approved these changes

2024-11-28 19:52 UTC, ldionne requested changes
Don't we need to add tests for https://wg21.link/LWG3120 ?

2024-11-29 04:17 UTC, love1angel commented
> Don't we need to add tests for https://wg21.link/LWG3120 ?

yes, so i changed to draft. need to add test here.

2025-02-10 09:34 UTC, love1angel commented on libcxx/test/std/utilities/utility/mem.res/mem.res.monotonic.buffer/mem.res.monotonic.buffer.mem/release_reset_initial_status.pass.cpp
> +}
done. thanks, could you review it again?

2025-02-10 09:38 UTC, love1angel commented on libcxx/test/std/utilities/utility/mem.res/mem.res.monotonic.buffer/mem.res.monotonic.buffer.mem/release_reset_initial_status.pass.cpp
> +        std::ignore = mr.allocate(1);
could you tell me why here suggest use (void) instead. std::ignore is more readable but introduce another header <tuple>. thank you.

2025-02-15 17:14 UTC, frederick-vs-ja commented on libcxx/test/std/utilities/utility/mem.res/mem.res.monotonic.buffer/mem.res.monotonic.buffer.mem/release_reset_initial_status.pass.cpp
> +        std::ignore = mr.allocate(1);
I think we conventionally use `(void)` cast to ignore expressions in libc++ tests.

2025-02-15 17:14 UTC, frederick-vs-ja approved these changes

2025-02-16 07:48 UTC, philnik777 commented on libcxx/test/std/utilities/utility/mem.res/mem.res.monotonic.buffer/mem.res.monotonic.buffer.mem/release_reset_initial_status.pass.cpp
> +//===----------------------------------------------------------------------===//
```suggestion
//===----------------------------------------------------------------------===//
```

2025-02-16 07:48 UTC, philnik777 commented on libcxx/test/std/utilities/utility/mem.res/mem.res.monotonic.buffer/mem.res.monotonic.buffer.mem/release_reset_initial_status.pass.cpp
> +      // when init given a buffer, after release(), initial ptr will reset to it's initial state
Sorry, I don't understand what this comment is trying to tell me. Could you formulate this in full sentences?

2025-02-16 07:48 UTC, philnik777 commented on libcxx/test/std/utilities/utility/mem.res/mem.res.monotonic.buffer/mem.res.monotonic.buffer.mem/release_reset_initial_status.pass.cpp
> +      constexpr auto expect_next_buffer_size{512ULL};
```suggestion
      constexpr size_t expect_next_buffer_size = 512;
```

though I wonder whether just inlining the 512 would actually be more readable.

2025-02-16 07:48 UTC, philnik777 commented on libcxx/test/std/utilities/utility/mem.res/mem.res.monotonic.buffer/mem.res.monotonic.buffer.mem/release_reset_initial_status.pass.cpp
> +      for (auto i{0}; i < 100; ++i) {
```suggestion
      for (size_t i = 0; i < 100; ++i) {
```
Same elsewhere.

2025-02-16 07:48 UTC, philnik777 commented on libcxx/test/std/utilities/utility/mem.res/mem.res.monotonic.buffer/mem.res.monotonic.buffer.mem/release_reset_initial_status.pass.cpp
> +      for (auto i{0}; i < 100; ++i) {
Why do we do this in a loop?

2025-02-16 07:48 UTC, philnik777 commented on libcxx/test/std/utilities/utility/mem.res/mem.res.monotonic.buffer/mem.res.monotonic.buffer.mem/release_reset_initial_status.pass.cpp
> +// UNSUPPORTED: c++03, c++11, c++14
```suggestion
// REQUIRES: std-at-least-c++17
```
Might as well make use of the new features.

2025-02-17 11:51 UTC, philnik777 commented on libcxx/test/std/utilities/utility/mem.res/mem.res.monotonic.buffer/mem.res.monotonic.buffer.mem/release_reset_initial_status.pass.cpp
> +      // when init given a buffer, after release(), initial ptr will reset to it's initial state
I don't think you've addressed this.

2025-02-18 01:57 UTC, love1angel commented on libcxx/test/std/utilities/utility/mem.res/mem.res.monotonic.buffer/mem.res.monotonic.buffer.mem/release_reset_initial_status.pass.cpp
> +      // when init given a buffer. after release(), reset current buffer
Hi, @philnik777, but here, i just want to check whether the offset of the buffer has been reset after release(). what else should i add here? thanks.

2025-02-18 11:31 UTC, philnik777 commented on libcxx/test/std/utilities/utility/mem.res/mem.res.monotonic.buffer/mem.res.monotonic.buffer.mem/release_reset_initial_status.pass.cpp
> +      // when init given a buffer. after release(), reset current buffer
I'm just asking for something like `// Check whether the offset into the initial buffer has been reset after release()`. Full sentences make it _way_ easier to understand what you're trying to do. A similar refactoring for the above would also be nice FWIW, but I won't insist, since I did at least understand it after reading it twice.

2025-02-19 01:37 UTC, love1angel commented on libcxx/test/std/utilities/utility/mem.res/mem.res.monotonic.buffer/mem.res.monotonic.buffer.mem/release_reset_initial_status.pass.cpp
> +      // when init given a buffer. after release(), reset current buffer
Sorry, i got it. Thank you for you explain.

2025-02-19 07:56 UTC, philnik777 approved these changes

2025-03-26 00:22 UTC, ldionne approved these changes

2025-03-26 00:23 UTC, ldionne commented on libcxx/test/std/utilities/utility/mem.res/mem.res.monotonic.buffer/mem.res.monotonic.buffer.mem/release_reset_initial_status.pass.cpp
> +// class monotonic_buffer_resource
```suggestion
// class monotonic_buffer_resource

// This test checks the behavior required by LWG3120.
```

2025-03-26 00:24 UTC, merged