[Clang] Add __builtin_invoke and detect std::invoke as a builtin
llvm/llvm-project pull request #116709
Opened 2024-11-18 23:15 UTC by philnik777

`std::invoke` is currently quite heavy compared to a function call, since it involves quite heavy SFINAE. This can be done significantly more efficient by the compiler, since most calls to `std::invoke` are simple function calls and 6 out of the seven overloads for `std::invoke` exist only to support member pointers. Even these boil down to a few relatively simple checks. Furthermore, this results in significantly better code gen at -O0, since it removes multiple levels of function calls.

Some real-world testing with this patch revealed some significant results. For example, instantiating `std::format("Banane")` (and its callees) went down from ~130ms on my system to ~100ms, or with some questionable trickery even down to ~90ms.

2024-11-22 15:56 UTC, philnik777 commented
@ldionne I think this is the more appropriate place to discuss this.

(From https://github.com/llvm/llvm-project/pull/116637#discussion_r1854114956)

> Chris had a patch on Clang at some point where we discussed this and I voiced concerns. Here it is: https://reviews.llvm.org/D130867
> 
> Here are some of my concerns:
> 
>     1. Implementing more stuff in the compiler adds complexity to the compiler, and does not decrease the complexity of the library because libc++ still needs to implement invoke on other compilers.
> 
>     2. It duplicates the tests, since we need to test the builtin and the standard library interface to the same level.
> 
>     3. Duplicating functionality in libc++ and in the compiler is confusing. For instance, it sets up the stage for people not knowing where a bug in `std::invoke` should be fixed. Is it in the compiler? In the library? In both? And the set of folks who can fix a bug in the compiler is a lot smaller than the set of folks who can do that in the library.
> 
>     4. It creates another level of coupling between the library and the compiler version-wise. For example, if we have a LWG issue fixing `std::invoke`, we must now fix it in Clang and whether the issue is fixed is not something we can determine from the library, it becomes something that depends on the compiler. This is technically a pre-existing issue with the builtin type traits, but in practice the type traits have a simple API and they don't change much, unlike `std::invoke` which has a complex simplification and could be the target of changes.

1. I'm not convinced the library part is true. The reality is that we support Clang and GCC, and if they both support the builtins (or provide different ones for the same feature) we remove our fallback implementations and thus reducing the complexity for libc++. GCC 15 already adds `__is_invocable`, so we would be able to at least simplify our traits. Whether the complexity is too high for the compiler is something the compiler maintainers should judge IMO. FWIW IMO The compiler implementations is actually much easier to understand than the mess we have in the library.

2. True. I'm not sure this is a huge burden though.

3. IMO that's not the case. We call a builtin. If that builtin is wrong we file a bug against the compiler. I don't really see the confusion here. It's exactly the same as with type traits.

4. I don't think this is just "technically pre-existing". There are bugs in the compiler builtins. In some cases we've waited until these bugs are fixed to use a builtin trait, but when the bug was pre-existing for a significant amount of time we didn't bother trying to work around it in the library. I'm not sure what you mean by "complex simplification".

2024-11-22 16:34 UTC, ldionne commented
> 
> 1. I'm not convinced the library part is true. The reality is that we support Clang and GCC, and if they both support the builtins (or provide different ones for the same feature) we remove our fallback implementations and thus reducing the complexity for libc++. GCC 15 already adds `__is_invocable`, so we would be able to at least simplify our traits. Whether the complexity is too high for the compiler is something the compiler maintainers should judge IMO. FWIW IMO The compiler implementations is actually much easier to understand than the mess we have in the library.

Does GCC implement (or have plans to implement) `__builtin_invoke`?

> 2. True. I'm not sure this is a huge burden though.

Well, our tests for `std::invoke` are not simple, and we'd have to do the same in Clang if we want to have the same amount of coverage.

> 3. IMO that's not the case. We call a builtin. If that builtin is wrong we file a bug against the compiler. I don't really see the confusion here. It's exactly the same as with type traits.

Your PR description says that the compiler recognizes `std::invoke` itself as a builtin, is that right? It makes a difference to me whether `std::invoke` is a builtin directly or `std::invoke` calls `__builtin_invoke`.

> 4. I don't think this is just "technically pre-existing". There are bugs in the compiler builtins. In some cases we've waited until these bugs are fixed to use a builtin trait, but when the bug was pre-existing for a significant amount of time we didn't bother trying to work around it in the library. I'm not sure what you mean by "complex simplification".

Sorry, I meant complex specification. I mean that `invoke` is not like `is_constructible` -- it may be updated in the future. The updates would be to the library wording, and I'd find it really weird to have to go change the compiler builtin to account for what's effectively a library change.

2024-11-23 00:08 UTC, philnik777 commented
> > 1. I'm not convinced the library part is true. The reality is that we support Clang and GCC, and if they both support the builtins (or provide different ones for the same feature) we remove our fallback implementations and thus reducing the complexity for libc++. GCC 15 already adds `__is_invocable`, so we would be able to at least simplify our traits. Whether the complexity is too high for the compiler is something the compiler maintainers should judge IMO. FWIW IMO The compiler implementations is actually much easier to understand than the mess we have in the library.
> 
> Does GCC implement (or have plans to implement) `__builtin_invoke`?

Not that I'm aware of.

> > 2. True. I'm not sure this is a huge burden though.
> 
> Well, our tests for `std::invoke` are not simple, and we'd have to do the same in Clang if we want to have the same amount of coverage.

AFAICT we have one test for `invoke` plus a constexpr test which should really just be rolled into the generic `invoke` test. That test is ~400 LoC, which is definitely not nothing, but also not unmanageable IMO. We could probably also simplify that by not explicitly listing every cv combination but instead using `types::for_each`.

> > 3. IMO that's not the case. We call a builtin. If that builtin is wrong we file a bug against the compiler. I don't really see the confusion here. It's exactly the same as with type traits.
> 
> Your PR description says that the compiler recognizes `std::invoke` itself as a builtin, is that right? It makes a difference to me whether `std::invoke` is a builtin directly or `std::invoke` calls `__builtin_invoke`.

Yes, it does. If that is the main point of contention we can move that into a separate patch. I don't expect the compile times to differ significantly between recognizing `std::invoke` as a builtin itself and having `std::invoke` use `__builtin_invoke` as the implementation. It would still be nice for improved debug performance and reduced debug info though.

What exactly is the difference you perceive between the two? I mean, sure, there is one, but if `std::invoke` just always calls `__builtin_invoke` there really isn't a meaningful one.

> > 4. I don't think this is just "technically pre-existing". There are bugs in the compiler builtins. In some cases we've waited until these bugs are fixed to use a builtin trait, but when the bug was pre-existing for a significant amount of time we didn't bother trying to work around it in the library. I'm not sure what you mean by "complex simplification".
> 
> Sorry, I meant complex specification. I mean that `invoke` is not like `is_constructible` -- it may be updated in the future. The updates would be to the library wording, and I'd find it really weird to have to go change the compiler builtin to account for what's effectively a library change.

Is your main concern here that we'd be limited in the library what we can change without the changing the compiler? If that is the case, would your concerns be alleviated if we could opt out of the builtin recognition for specific overloads, e.g. through an attribute?

2024-11-26 19:32 UTC, ldionne commented
> 
> AFAICT we have one test for `invoke` plus a constexpr test which should really just be rolled into the generic `invoke` test. That test is ~400 LoC, which is definitely not nothing, but also not unmanageable IMO. We could probably also simplify that by not explicitly listing every cv combination but instead using `types::for_each`.

As long as libc++ keeps testing its public API fully, I'm OK with this. What I don't want is to start shifting test burden towards Clang because the compiler actually implements most of the functionality. These builtins should be implementation details, so we should still be testing the full public API in libc++ itself.

The testing question from the Clang side is interesting and I would expect Clang folks to have an opinion. From the Clang side, I'd expect some concerns about adding a builtin with such a complex and user-visible "API". But those concerns are not really for me to raise, if Clang folks are fine with it, that's not an issue for me.

> 
> Yes, it does. If that is the main point of contention we can move that into a separate patch. I don't expect the compile times to differ significantly between recognizing `std::invoke` as a builtin itself and having `std::invoke` use `__builtin_invoke` as the implementation. It would still be nice for improved debug performance and reduced debug info though.
> 
> What exactly is the difference you perceive between the two? I mean, sure, there is one, but if `std::invoke` just always calls `__builtin_invoke` there really isn't a meaningful one.
> 
> [...]
> 
> Is your main concern here that we'd be limited in the library what we can change without the changing the compiler? If that is the case, would your concerns be alleviated if we could opt out of the builtin recognition for specific overloads, e.g. through an attribute?

As discussed just now in the libc++ monthly:
- Silently hijacking a libc++ function by the compiler is surprising and certainly unexpected unless you already know what's going on. I can imagine someone trying to fix a bug in `std::invoke` and spending hours scratching their heads not understanding why `std::invoke` is still not doing the right thing after their changes, only to find out that the compiler was really implementing the function under the hood. These things should be explicit.
- Silently hijacking also means that we lose control over what's happening from the library side, so a bug or an improvement requires changes to the compiler.

My view is that compiler builtins should be tools to implement an API more simply and more efficiently. They shouldn't *be* the API itself.

Personally, I think the best way to move this forward would be to remove the hijacking from this patch to make it less contentious, and  then to potentially pursue an attribute to formalize how hijacking works. This could (and should) be used beyond `std::invoke`, for example with `std::forward` and `std::move`. That would actually be an improvement to the status-quo in relation to my concerns with "discoverability".

2025-05-20 13:38 UTC, erichkeane reviewed
Couple of nits, else I'm reasonably ok with this.  Interested to hear what @AaronBallman has to say, else I think this is beneficial.

2025-05-20 13:38 UTC, erichkeane commented on clang/lib/Parse/ParseDeclCXX.cpp
> +          tok::kw___is_convertible, // Last use in libc++ was removed in 925a11a
I'm missing something, what happened to the ones on the LHS here?

2025-05-20 13:38 UTC, erichkeane commented on clang/lib/Sema/SemaChecking.cpp
> +  auto Loc = TheCall->getBeginLoc();
Don't use auto here.

2025-05-20 13:38 UTC, erichkeane commented on clang/lib/Sema/SemaChecking.cpp
> +  assert(llvm::none_of(Args,
Is this enforced earlier?  Why can't type dependent args make it here?

2025-05-20 13:38 UTC, erichkeane commented on clang/lib/Sema/SemaChecking.cpp
> +        << 0 << 1 << 0 << 0 << TheCall->getSourceRange();
These 4 need some sort of comments showing what they mean.

2025-05-20 13:38 UTC, erichkeane commented on clang/lib/Sema/SemaChecking.cpp
> +          << 0 << 2 << 1 << 0 << TheCall->getSourceRange();
Same here, we do the /*whatever=*/ pattern here.

2025-05-20 14:10 UTC, philnik777 commented on clang/lib/Sema/SemaChecking.cpp
> +  assert(llvm::none_of(Args,
I'm not sure whether dependent arguments can make it here, but I haven't been able to get any here. Should I remove the assertion?

2025-05-20 14:17 UTC, erichkeane commented on clang/lib/Sema/SemaChecking.cpp
> +          << 0 << 2 << Args.size() << 0 << TheCall->getSourceRange();
Here too.

2025-05-20 14:17 UTC, erichkeane commented on clang/lib/Sema/SemaChecking.cpp
> +  if (Args.size() == 0) {
Instead of all of these separate diagnostics, is there a reason we can't just use `Sema::checkArgCountAtLeast` and friends?   This one looks like a 'at least 1'.  5427 looks like `Sema::checkArgCountAtMost`, and 5440 `Sema::checkArgCount`.

WDYT?

2025-05-20 15:00 UTC, philnik777 commented on clang/lib/Sema/SemaChecking.cpp
> +  assert(llvm::none_of(Args,
```
template <class T>
auto test(T v) {
  return __builtin_invoke(v);
}
```
should do the trick, right? Assuming I've set things up correctly on my end, this does not trigger the assert here.

2025-05-20 15:00 UTC, philnik777 commented on clang/lib/Sema/SemaChecking.cpp
> +  if (Args.size() == 0) {
AFAICT `checkArgCountAtLeast` actually prints "expected x, have y". IMO the "at least" here is quite important, since the number of required arguments changes depending on the first argument. I guess I could introduce a new helper; not sure that this is the patch to do it though. I've replaced the 5440 one.

2025-05-20 15:06 UTC, erichkeane approved these changes
I'm happy as-is.  Please give Aaron a chance to poke if he wants to.

2025-05-20 15:06 UTC, erichkeane commented on clang/lib/Sema/SemaChecking.cpp
> +  assert(llvm::none_of(Args,
Yep, I would expect that to be enough to get it.  Looks like we must handle it elsewhere for these, I wasn't sure!

2025-05-20 15:06 UTC, erichkeane commented on clang/lib/Sema/SemaChecking.cpp
> +  if (Args.size() == 0) {
Ah, thats unfortunate.  But yes, I think that seems to be the way it is.  Its a little odd we don't actually print the 'right' thing for the 'at least' function, but I see this is far from the first.  SGMT.

2025-05-20 17:19 UTC, cor3ntin reviewed
Thanks for working on that. Do you have any benchmarks?

- Please add an entry in LanguageExensions.rst
-  Can you add a minimum of tests for static  / explicit object member functions, lambdas?
- Something like https://compiler-explorer.com/z/s5s9sbzn7

I think my general concern here is "did we forget something?

2025-05-20 17:19 UTC, cor3ntin commented on clang/lib/Sema/SemaChecking.cpp
> +
Can you check that this SFINAE properly?

2025-05-20 17:19 UTC, cor3ntin commented on clang/lib/Sema/SemaChecking.cpp
> +    auto ObjectT = Args[1]->getType();
We try to avoid auto when the RHS is not a cast

2025-05-20 17:19 UTC, cor3ntin commented on clang/lib/Sema/SemaExprCXX.cpp
> +static bool EvaluateBinaryTypeTrait(Sema &Self, TypeTrait BTT, const TypeSourceInfo *Lhs,
Were these refactors necessary?

2025-05-20 17:19 UTC, cor3ntin commented on clang/include/clang/Sema/Sema.h
> +  ExprResult BuiltinInvoke(CallExpr *TheCall);
This doesn't need to be in the header

2025-05-20 17:22 UTC, AaronBallman reviewed
Please also update `clang/docs/LanguageExtensions.rst` to document the new builtin, and update `clang/docs/ReleaseNotes.rst` so users know about the new functionality.

2025-05-20 17:22 UTC, AaronBallman commented on clang/lib/Sema/SemaChecking.cpp
> +  auto FuncT = Args[0]->getType();
```suggestion
  QualType FuncT = Args[0]->getType();
```

2025-05-20 17:22 UTC, AaronBallman commented on clang/lib/Sema/SemaChecking.cpp
> +  auto Args = MutableArrayRef(TheCall->getArgs(), TheCall->getNumArgs());
```suggestion
  MutableArrayRef Args(TheCall->getArgs(), TheCall->getNumArgs());
```

2025-05-20 17:22 UTC, AaronBallman commented on clang/lib/Sema/SemaChecking.cpp
> +  if (auto *MPT = FuncT->getAs<MemberPointerType>()) {
```suggestion
  if (const auto *MPT = FuncT->getAs<MemberPointerType>()) {
```
You can make this same kind of correction elsewhere; best to try to aim for const correctness where it's not virally annoying.

2025-05-20 17:22 UTC, AaronBallman commented on clang/lib/Sema/SemaChecking.cpp
> +    auto ObjectT = Args[1]->getType();
Please spell out the types instead of using `auto` (I'll stop commenting on that, should just make a general pass and correct them all)

2025-05-20 17:22 UTC, AaronBallman commented on clang/lib/Sema/SemaChecking.cpp
> +      // (1.1): (t1.*f)(t2, …, tN) when f is a pointer to a member function of a
```suggestion
      // (1.1): (t1.*f)(t2, ..., tN) when f is a pointer to a member function of a
```
Replacing non-ASCII with ASCII.

2025-05-20 18:09 UTC, AaronBallman requested changes
Precommit CI failures look related to this patch:
```
/var/lib/buildkite-agent/builds/linux-56-59b8f5d88-g6cdk-1/llvm-project/github-pull-requests/build-runtimes/include/c++/v1/__type_traits/invoke.h:123:29: error: variable has incomplete type 'struct _LIBCPP_TEMPLATE_VIS'
  123 | struct _LIBCPP_TEMPLATE_VIS is_invocable : bool_constant<__is_invocable_v<_Fn, _Args...> > {};
      |                             ^
```

2025-05-22 08:03 UTC, philnik777 commented
> Thanks for working on that. Do you have any benchmarks?

I haven't benchmarked extensively, but as stated in the commit message, The instantiation of `std::format` is ~20ms faster. IMO that's a significant enough speedup on its own that it grants adding a builtin. 

I've just tested with `ranges::adjacent_find`, and there the instantiation goes down from  ~14.9ms to ~13.5ms. Not as impressive, but still quite nice. (And I've also noticed that `common_reference` takes an absurd amount of time to instantiate on `ranges::adjacent_find`)

2025-05-28 14:30 UTC, ldionne approved these changes
I'm fine with the libc++ part of this patch. I like this new approach a lot more. I think it gives us most of the benefits without raising difficult questions.

2025-05-30 13:05 UTC, philnik777 commented
Gentle ping @AaronBallman @cor3ntin

2025-06-11 12:37 UTC, philnik777 commented
@AaronBallman @cor3ntin any more thoughts on this?

2025-06-11 14:23 UTC, AaronBallman reviewed
I don't see anything wrong with the changes, but I think we're missing test coverage.

2025-06-11 14:23 UTC, AaronBallman commented on clang/lib/Sema/SemaChecking.cpp
> +            RD->getDeclName().getAsString() == "reference_wrapper") {
I'm not opposed, but I'm also not delighted for more special knowledge about STL interfaces leaking into the compiler implementation.

2025-06-11 14:23 UTC, AaronBallman commented on clang/test/SemaCXX/builtin-invoke.cpp
> +  __builtin_invoke(malloc, 0);
I'd like to see a test where the function being invoked is variadic, along the lines of:
```
void func(int x, ...);

__builtin_invoke(func);  // Error
__builtin_invoke(func, 1); // Okay
__builtin_invoke(func, 1, 2, 3); // Okay
```

2025-06-11 14:23 UTC, AaronBallman commented on clang/test/SemaCXX/builtin-invoke.cpp
> +  __builtin_invoke(malloc, 0);
I'd like a test where we're calling a static member function, along the lines of:
```
struct S {
  static void func(int x);
};

__builtin_invoke(S::func, 1); // Okay
S s;
__builtin_invoke(s.func, 1); // Okay
```

2025-06-11 14:23 UTC, AaronBallman commented on clang/test/SemaCXX/builtin-invoke.cpp
> +  __builtin_invoke(malloc, 0);
And a test where we're calling a lambda, along the lines of:
```
__builtin_invoke([](int x) {}, 1);
```

2025-06-11 14:23 UTC, AaronBallman commented on clang/test/SemaCXX/builtin-invoke.cpp
> +  __builtin_invoke(malloc, 0);
And a test where the thing being invoked is dependent, along the lines of:
```

template <typename ClassTy, typename FnTy>
void func(ClassTy &C, FnTy &&Fn) {
  __builtin_invoke(Fn, C, 1, 2, 3);
}

struct S {
  void func(int i, int j, int k);
  void bad_func();
};

int main() {
  S s;
  func(s, &S::func); // Okay
  func(s, &S::bad_func); // Error, incorrect number of arguments
}
```

2025-06-13 03:20 UTC, shafik commented on clang/lib/Sema/SemaTypeTraits.cpp
> +    if (RequireCompleteType(RhsTLoc, RhsT,
I don't think this diagnostic is tested.

2025-06-13 03:20 UTC, shafik commented on clang/lib/Sema/SemaTypeTraits.cpp
> +  if (RequireCompleteType(RhsTLoc, RhsT,
Is this diagnostic tested?

2025-06-13 07:50 UTC, philnik777 commented on clang/lib/Sema/SemaTypeTraits.cpp
> +    if (RequireCompleteType(RhsTLoc, RhsT,
I've added a test for the case below. If anybody can inform me how to create an ObjCObjectType I'm happy to add a test for this as well (though I'm not sure testing this is that useful).

2025-06-13 08:09 UTC, tbaederr commented on clang/include/clang/Basic/Builtins.td
> +  let Attributes = [CustomTypeChecking, Constexpr];
There are no changes to `ExprConstant.cpp` - is this actually tested in a constexpr context?

2025-06-13 08:43 UTC, philnik777 commented on clang/include/clang/Basic/Builtins.td
> +  let Attributes = [CustomTypeChecking, Constexpr];
The builtin resolves to the appropriate nodes, so there is nothing to do specifically with `__builtin_invoke`.

2025-06-13 08:45 UTC, tbaederr commented on clang/include/clang/Basic/Builtins.td
> +  let Attributes = [CustomTypeChecking, Constexpr];
okay, thanks.

2025-06-13 19:03 UTC, AaronBallman commented on clang/include/clang/Basic/Builtins.td
> +  let Attributes = [CustomTypeChecking, Constexpr];
We should still add test coverage to `clang/test/SemaCXX` for it though; we don't want to have to wait for us to break libc++ tests to know we've regressed anything here.

2025-06-25 08:49 UTC, philnik777 commented
Ping @AaronBallman

2025-06-25 17:43 UTC, AaronBallman approved these changes
LGTM aside from testing nits.

2025-06-25 17:43 UTC, AaronBallman commented on clang/lib/Sema/SemaChecking.cpp
> +    if (Args.size() < 2) {
We should have a test case for a member pointer to a function with an explicit object parameter. I believe this logic all still works, but the coverage would be good to have.

2025-06-25 17:43 UTC, AaronBallman commented on clang/test/SemaCXX/builtin-invoke.cpp
> +
I think we should also have a test for a call through a vanilla function pointer rather than a pointer to member.

2025-06-26 11:36 UTC, AaronBallman commented
Precommit CI failures look related

2025-06-29 15:52 UTC, merged

2025-06-29 16:38 UTC, EricWF commented
@philnik777 I'm encountering a number of test failures related to libc++'s clang-tidy module when running the libc++ test suite with the new compiler:
```
# .---command stdout------------
# | /home/eric/llvm-project/build/libcxx/libcxx/test-suite-install/include/c++/v1/__type_traits/invoke.h:68:1: error: Internal aliases should always be marked _LIBCPP_NODEBUG [libcpp-nodebug-on-aliases,-warnings-as-errors]
# |    68 | using __invoke_result_t = decltype(__builtin_invoke(std::declval<_Args>()...));
# |       | ^
# | /home/eric/llvm-project/build/libcxx/libcxx/test-suite-install/include/c++/v1/__type_traits/invoke.h:79:1: error: Internal aliases should always be marked _LIBCPP_NODEBUG [libcpp-nodebug-on-aliases,-warnings-as-errors]
# |    79 | using __invoke_result = __invoke_result_impl<void, _Args...>;
# |       | ^

```
Could you please take a look at these?

2025-06-29 16:38 UTC, EricWF commented on clang/test/SemaCXX/builtin-invoke.cpp
> +static_assert(!invocable<std::reference_wrapper<InvalidSpecialization1>>);
Is there a positive test for `invocable`?

2025-06-29 16:38 UTC, EricWF commented on clang/test/SemaCXX/builtin-invoke.cpp
> +  auto invoke(Args&&... args) -> decltype(__builtin_invoke(args...));
Is this used anywhere in the tests?

2025-06-29 17:10 UTC, philnik777 commented
> @philnik777 I'm encountering a number of test failures related to libc++'s clang-tidy module when running the libc++ test suite with the new compiler:
> 
> ```
> # .---command stdout------------
> # | /home/eric/llvm-project/build/libcxx/libcxx/test-suite-install/include/c++/v1/__type_traits/invoke.h:68:1: error: Internal aliases should always be marked _LIBCPP_NODEBUG [libcpp-nodebug-on-aliases,-warnings-as-errors]
> # |    68 | using __invoke_result_t = decltype(__builtin_invoke(std::declval<_Args>()...));
> # |       | ^
> # | /home/eric/llvm-project/build/libcxx/libcxx/test-suite-install/include/c++/v1/__type_traits/invoke.h:79:1: error: Internal aliases should always be marked _LIBCPP_NODEBUG [libcpp-nodebug-on-aliases,-warnings-as-errors]
> # |    79 | using __invoke_result = __invoke_result_impl<void, _Args...>;
> # |       | ^
> ```
> 
> Could you please take a look at these?

Urgh, looks like clang-tidy doesn't run in the bootstrapping build. I'll update my local clang and fix any issues.

2025-07-22 23:20 UTC, alexfh commented
This breaks some valid code. Here a partially reduced test case that depends on libc++ and Google Test: https://gcc.godbolt.org/z/dPznsz44M

```
#include <variant>
#include <vector>

#include <gmock/gmock.h>

template <typename T>
class Nullable {
 public:
  Nullable() : value_() {}
  template <typename V>
  Nullable(V value) : value_(value) {}

  const T& value() const { return value_; }

 private:
  T value_;
};

template <typename L, typename R>
inline bool operator== (const Nullable<L>& lhs, const Nullable<R>& rhs) {
  return lhs.value() == rhs.value();
}

void f() {
  std::vector<std::variant<int, Nullable<int>>> v;
  ASSERT_THAT(v, ::testing::ElementsAre(16));
}
```

It used to compile fine, but now it triggers a compilation error:
```
/opt/compiler-explorer/clang-trunk-20250722/bin/../include/c++/v1/variant:1186:37: fatal error: recursive template instantiation exceeded maximum depth of 1024
 1186 |              enable_if_t<!is_same_v<__remove_cvref_t<_Arg>, variant>, int>        = 0,
      |                                     ^
/opt/compiler-explorer/clang-trunk-20250722/bin/../include/c++/v1/variant:1192:35: note: while substituting prior template arguments into non-type template parameter [with _Arg = testing::Matcher<const std::variant<int, Nullable<int>> &>]
 1192 |   _LIBCPP_HIDE_FROM_ABI constexpr variant(_Arg&& __arg) noexcept(is_nothrow_constructible_v<_Tp, _Arg>)
      |                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 1193 |       : __impl_(in_place_index<_Ip>, std::forward<_Arg>(__arg)) {}
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/opt/compiler-explorer/clang-trunk-20250722/bin/../include/c++/v1/__type_traits/invoke.h:71:69: note: while substituting deduced template arguments into function template 'variant' [with _Arg = testing::Matcher<const std::variant<int, Nullable<int>> &>, $1 = (no value), $2 = (no value), $3 = (no value), _Tp = (no value), _Ip = (no value), $6 = (no value)]
   71 | using __invoke_result_t _LIBCPP_NODEBUG = decltype(__builtin_invoke(std::declval<_Args>()...));
      |                                                                     ^
/opt/compiler-explorer/clang-trunk-20250722/bin/../include/c++/v1/__type_traits/invoke.h:387:1: note: in instantiation of template type alias '__invoke_result_t' requested here
  387 | using invoke_result_t = __invoke_result_t<_Fn, _Args...>;
      | ^
/opt/compiler-explorer/clang-trunk-20250722/bin/../include/c++/v1/variant:1140:1: note: in instantiation of template type alias 'invoke_result_t' requested here
 1140 | using __best_match_t _LIBCPP_NODEBUG = typename invoke_result_t<_MakeOverloads<_Types...>, _Tp, _Tp>::type;
      | ^
/opt/compiler-explorer/clang-trunk-20250722/bin/../include/c++/v1/variant:1189:45: note: in instantiation of template type alias '__best_match_t' requested here
 1189 |              class _Tp  = __variant_detail::__best_match_t<_Arg, _Types...>,
      |                                             ^
/opt/compiler-explorer/clang-trunk-20250722/bin/../include/c++/v1/variant:1192:35: note: (skipping 2533 contexts in backtrace; use -ftemplate-backtrace-limit=0 to see all)
 1192 |   _LIBCPP_HIDE_FROM_ABI constexpr variant(_Arg&& __arg) noexcept(is_nothrow_constructible_v<_Tp, _Arg>)
      |                                   ^
/opt/compiler-explorer/libs/googletest/trunk/googlemock/include/gmock/gmock-matchers.h:356:12: note: in instantiation of function template specialization 'testing::internal::MatcherCastImpl<const std::vector<std::variant<int, Nullable<int>>> &, testing::internal::ElementsAreMatcher<std::tuple<int>>>::CastImpl<false>' requested here
  356 |     return CastImpl(polymorphic_matcher_or_value,
      |            ^
/opt/compiler-explorer/libs/googletest/trunk/googlemock/include/gmock/gmock-matchers.h:529:43: note: in instantiation of member function 'testing::internal::MatcherCastImpl<const std::vector<std::variant<int, Nullable<int>>> &, testing::internal::ElementsAreMatcher<std::tuple<int>>>::Cast' requested here
  529 |   return internal::MatcherCastImpl<T, M>::Cast(matcher);
      |                                           ^
/opt/compiler-explorer/libs/googletest/trunk/googlemock/include/gmock/gmock-matchers.h:536:10: note: in instantiation of function template specialization 'testing::MatcherCast<const std::vector<std::variant<int, Nullable<int>>> &, testing::internal::ElementsAreMatcher<std::tuple<int>>>' requested here
  536 |   return MatcherCast<T>(polymorphic_matcher_or_value);
      |          ^
/opt/compiler-explorer/libs/googletest/trunk/googlemock/include/gmock/gmock-matchers.h:1661:39: note: in instantiation of function template specialization 'testing::SafeMatcherCast<const std::vector<std::variant<int, Nullable<int>>> &, testing::internal::ElementsAreMatcher<std::tuple<int>>>' requested here
 1661 |     const Matcher<const T&> matcher = SafeMatcherCast<const T&>(matcher_);
      |                                       ^
<source>:26:3: note: in instantiation of function template specialization 'testing::internal::PredicateFormatterFromMatcher<testing::internal::ElementsAreMatcher<std::tuple<int>>>::operator()<std::vector<std::variant<int, Nullable<int>>>>' requested here
   26 |   ASSERT_THAT(v, ::testing::ElementsAre(16));
      |   ^
/opt/compiler-explorer/libs/googletest/trunk/googlemock/include/gmock/gmock-matchers.h:5736:3: note: expanded from macro 'ASSERT_THAT'
 5736 |   ASSERT_PRED_FORMAT1(              \
      |   ^
/opt/compiler-explorer/libs/googletest/trunk/googletest/include/gtest/gtest_pred_impl.h:112:3: note: expanded from macro 'ASSERT_PRED_FORMAT1'
  112 |   GTEST_PRED_FORMAT1_(pred_format, v1, GTEST_FATAL_FAILURE_)
      |   ^
/opt/compiler-explorer/libs/googletest/trunk/googletest/include/gtest/gtest_pred_impl.h:100:28: note: expanded from macro 'GTEST_PRED_FORMAT1_'
  100 |   GTEST_ASSERT_(pred_format(#v1, v1), on_failure)
      |                            ^
/opt/compiler-explorer/libs/googletest/trunk/googletest/include/gtest/gtest_pred_impl.h:79:52: note: expanded from macro 'GTEST_ASSERT_'
   79 |   if (const ::testing::AssertionResult gtest_ar = (expression)) \
      |                                                    ^
1 error generated.
```

@philnik777 please take a look.

2025-07-23 12:59 UTC, philnik777 commented
@alexfh Could you maybe provide a reproducer without a dependency on Google Test? I don't easily have access to that, and it shouldn't be too hard to remove that. It looks to me like it's instantiating the variant constructor with something, but unfortunately the diagnostics are cut off at exactly that point.

2025-07-23 14:22 UTC, alexfh commented
I'm trying to unwrap this more, so far I got to this point: https://gcc.godbolt.org/z/q76YxfKzP

Hopefully I can leave only libc++ includes soon.

2025-07-24 00:58 UTC, alexfh commented
> I'm trying to unwrap this more, so far I got to this point: https://gcc.godbolt.org/z/q76YxfKzP
> 
> Hopefully I can leave only libc++ includes soon.

It turned out to be trickier than I thought, but the test is being automatically reduced. I'll post the result when it's ready.

2025-07-24 05:24 UTC, alexfh commented
The reduced test case: https://gcc.godbolt.org/z/KhebWaGsc

```
#include <variant>
#include <vector>
namespace testing {
template <typename T> struct Matcher {
  Matcher(int);
  Matcher(T);
};
template <typename T, typename M>
Matcher<T> SafeMatcherCast(M polymorphic_matcher_or_value) {
  return polymorphic_matcher_or_value;
}
namespace internal {
template <typename MatcherTuple> struct ElementsAreMatcher {
  template <typename Container> operator Matcher<Container>() {
    typedef typename std::remove_const<
        typename std::remove_reference<Container>::type>::type ::value_type
        Element;
    typedef std::vector<Matcher<Element>> MatcherVec;
    MatcherVec matchers;
    matchers.reserve(std::tuple_size<MatcherTuple>::value);
    return 0;
  }
};
} // namespace internal
} // namespace testing
template <typename> struct Nullable {
  template <typename V> Nullable(V);
};
void f(testing::internal::ElementsAreMatcher<std::tuple<>> m) {
  testing::SafeMatcherCast<std::vector<std::variant<Nullable<int>>>>(m);
}
```

```
In file included from <source>:1:
/opt/compiler-explorer/clang-trunk-20250723/bin/../include/c++/v1/variant:1186:37: fatal error: recursive template instantiation exceeded maximum depth of 1024
 1186 |              enable_if_t<!is_same_v<__remove_cvref_t<_Arg>, variant>, int>        = 0,
      |                                     ^
/opt/compiler-explorer/clang-trunk-20250723/bin/../include/c++/v1/variant:1192:35: note: while substituting prior template arguments into non-type template parameter [with _Arg = testing::Matcher<std::variant<Nullable<int>>>]
 1192 |   _LIBCPP_HIDE_FROM_ABI constexpr variant(_Arg&& __arg) noexcept(is_nothrow_constructible_v<_Tp, _Arg>)
      |                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 1193 |       : __impl_(in_place_index<_Ip>, std::forward<_Arg>(__arg)) {}
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/opt/compiler-explorer/clang-trunk-20250723/bin/../include/c++/v1/__type_traits/invoke.h:71:69: note: while substituting deduced template arguments into function template 'variant' [with _Arg = testing::Matcher<std::variant<Nullable<int>>>, $1 = (no value), $2 = (no value), $3 = (no value), _Tp = (no value), _Ip = (no value), $6 = (no value)]
   71 | using __invoke_result_t _LIBCPP_NODEBUG = decltype(__builtin_invoke(std::declval<_Args>()...));
      |                                                                     ^
/opt/compiler-explorer/clang-trunk-20250723/bin/../include/c++/v1/__type_traits/invoke.h:387:1: note: in instantiation of template type alias '__invoke_result_t' requested here
  387 | using invoke_result_t = __invoke_result_t<_Fn, _Args...>;
      | ^
/opt/compiler-explorer/clang-trunk-20250723/bin/../include/c++/v1/variant:1140:1: note: in instantiation of template type alias 'invoke_result_t' requested here
 1140 | using __best_match_t _LIBCPP_NODEBUG = typename invoke_result_t<_MakeOverloads<_Types...>, _Tp, _Tp>::type;
      | ^
/opt/compiler-explorer/clang-trunk-20250723/bin/../include/c++/v1/variant:1189:45: note: in instantiation of template type alias '__best_match_t' requested here
 1189 |              class _Tp  = __variant_detail::__best_match_t<_Arg, _Types...>,
      |                                             ^
/opt/compiler-explorer/clang-trunk-20250723/bin/../include/c++/v1/variant:1192:35: note: (skipping 2539 contexts in backtrace; use -ftemplate-backtrace-limit=0 to see all)
 1192 |   _LIBCPP_HIDE_FROM_ABI constexpr variant(_Arg&& __arg) noexcept(is_nothrow_constructible_v<_Tp, _Arg>)
      |                                   ^
/opt/compiler-explorer/clang-trunk-20250723/bin/../include/c++/v1/__vector/vector.h:845:8: note: in instantiation of function template specialization 'std::__uninitialized_allocator_relocate<std::allocator<testing::Matcher<std::variant<Nullable<int>>>>, testing::Matcher<std::variant<Nullable<int>>> *>' requested here
  845 |   std::__uninitialized_allocator_relocate(
      |        ^
/opt/compiler-explorer/clang-trunk-20250723/bin/../include/c++/v1/__vector/vector.h:1101:5: note: in instantiation of member function 'std::vector<testing::Matcher<std::variant<Nullable<int>>>>::__swap_out_circular_buffer' requested here
 1101 |     __swap_out_circular_buffer(__v);
      |     ^
<source>:20:14: note: in instantiation of member function 'std::vector<testing::Matcher<std::variant<Nullable<int>>>>::reserve' requested here
   20 |     matchers.reserve(std::tuple_size<MatcherTuple>::value);
      |              ^
<source>:10:10: note: in instantiation of function template specialization 'testing::internal::ElementsAreMatcher<std::tuple<>>::operator Matcher<std::vector<std::variant<Nullable<int>>>>' requested here
   10 |   return polymorphic_matcher_or_value;
      |          ^
<source>:30:12: note: in instantiation of function template specialization 'testing::SafeMatcherCast<std::vector<std::variant<Nullable<int>>>, testing::internal::ElementsAreMatcher<std::tuple<>>>' requested here
   30 |   testing::SafeMatcherCast<std::vector<std::variant<Nullable<int>>>>(m);
      |            ^
```

@philnik777 PTAL

2025-07-28 09:12 UTC, alexfh commented
@philnik777 please let me know, when you will be able to get to this. Thanks!

2025-07-28 19:43 UTC, philnik777 commented
@alexfh I've been able to take a look now. It looks like we're doing the `invoke_result_t` resolution more eagerly now, which results in recursively trying to instantiate the same template. I've opened #151028 to track the bug. I have no idea how to classify this bug at this point though. I have no idea whether this is a `variant` of `invoke` bug. I don't think it's a problem with the bultin at least...
I'll definitely talk with Louis about it tomorrow or latest on Wednesday though.

2025-07-28 19:50 UTC, alexfh commented
Thank you for the update! We can work around this for now, and the impact is quite limited, but it would be nice to get this working again relatively soon.

2025-07-28 19:55 UTC, philnik777 commented
> Thank you for the update! We can work around this for now, and the impact is quite limited, but it would be nice to get this working again relatively soon.

Absolutely. This is definitely a bug of some sort in libc++. I hope I'll be able to talk to @ldionne tomorrow so we can talk about this, since I'm genuinely at a loss right now.

2025-07-30 13:16 UTC, ldionne commented
I created https://github.com/llvm/llvm-project/issues/151328 to track this. I think we'll fix this in `std::variant`, at least until we have a better understanding of the issue and that points us to `std::invoke` being non-conforming after the change. I don't think that's the case but I'm not 100% certain.

2026-08-03 15:05 UTC, higher-performance commented
Commenting here for anyone interested: in #213403 I have a large speed improvement that makes the common case (ordinary function/non-member calls) _faster_ than the compiler built-in. I was thinking it could even be motivation to remove `__builtin_invoke` and avoid its maintenance burden, but not sure what folks think.