[GPU] ASAN failure due to use of erased operation
llvm/llvm-project pull request #116816
Opened 2024-11-19 14:54 UTC by pashu123

If the target op is an scf.forall op which is erased by `rewriteOneForallCommonImpl` method it leads to asan failure since it's used later by `replaceUnitMappingIdsHelper` fn.

Follows the same philosophy as done here:
https://github.com/llvm/llvm-project/blob/aff98e4be05a1060e489ce62a88ee0ff365e571a/mlir/lib/Dialect/GPU/TransformOps/GPUTransformOps.cpp#L599 and later passed to the same method here:
https://github.com/llvm/llvm-project/blob/aff98e4be05a1060e489ce62a88ee0ff365e571a/mlir/lib/Dialect/GPU/TransformOps/GPUTransformOps.cpp#L629

2024-11-19 15:01 UTC, joker-eph commented
Is there an existing tests failing with ASAN?

2024-11-19 15:04 UTC, pashu123 commented
> Is there an existing tests failing with ASAN?

Tests failed in the downstream project, but I'll add them here.

2024-11-19 15:14 UTC, pashu123 commented
> Is there an existing tests failing with ASAN?

I'm curious if we need to add tests for ASAN failures because I believe this patch addresses a fundamental issue.

2024-11-19 15:20 UTC, joker-eph commented
This is a problem of test coverage.
Many patch fixes crashes, assertions, and other similar fundamental issues but we're pretty consistent with adding test most of the time I think.

2024-11-26 08:30 UTC, ftynse requested changes
Take the downstream tests that triggered the asan issue, minimize it by removing downstream-specific parts, and put it somewhere it can run. Ideally, it would be a "unit test", i.e, a `.mlir` file running one pass and checking the output. Many MLIR integrators are running all tests under asan and would have seen the failure had it had the corresponding test.

Regardless of that, the change itself looks off to me. It calls `replaceUnitMappingIdsHelper` on the parent block of a target, which breaks the fundamental assumption of the transform dialect (and passes by the way, imaging target is the root operation of the interpreter pass).

2024-11-26 10:41 UTC, closed without merging

2024-11-26 10:41 UTC, pashu123 commented
The problem was with the downstream calling convention. I am closing this.