[mlir][spirv] Use assemblyFormat to define {InBound}PtrAccessChainOp assembly
llvm/llvm-project pull request #116943
Opened 2024-11-20 09:37 UTC by hahacyd

see #73359

Declarative assemblyFormat ODS is more concise and requires less boilerplate than filling out cpp interfaces.

Changes:
updates the PtrAccessChainOp and InBoundPtrAccessChainOp defined in SPIRVMemoryOps.td to use assemblyFormat. Removes part print/parse from MemoryOps.cpp which is now generated by assemblyFormat
Updates tests to updated format

2024-11-20 14:56 UTC, kuhar requested changes
I think we should be able to add type constrains that both `base_ptr` and `result` types match, and then remove the result type from the assembly format

2024-11-20 16:13 UTC, hahacyd commented
> I think we should be able to add type constrains that both `base_ptr` and `result` types match, and then remove the result type from the assembly format

I also feel the result's type is a little bit redundant, thanks for reminding "constraint", I will apply this method.

2024-11-21 16:36 UTC, kuhar approved these changes
After discussing this offline with @hahacyd, the result type is only redundant in the special case when there are no indices. So I think this is good as-is, because there's no duplication in the general case.

2024-11-24 04:03 UTC, hahacyd commented
ping~

2024-11-25 15:11 UTC, merged