Handle GEPs with negative offset and 'nuw' attribute
llvm/llvm-project pull request #117147
Opened 2024-11-21 12:07 UTC by pkarveti

This commit fixes incorrect DAG replacement when the 'nuw' attribute
 is added to inbound GEPs with a negative offset.

- If the offset is negative and the 'nuw' attribute is present, the 'nuw' flag is set to false.

2024-11-21 12:56 UTC, RKSimon commented on llvm/lib/CodeGen/SelectionDAG/SelectionDAGBuilder.cpp
> +          }
Merge this if-else into:
`Flags.setNoUnsignedWrap(Offs.isNonNegative() || !NW.hasNoUnsignedSignedWrap()` ?

2024-11-21 13:14 UTC, nikic requested changes
This change is incorrect, you are trying to work around an issue somewhere else, but your PR description doesn't have enough information to determine where.

`gep inbounds nuw` with a negative offset returns a poison value, and you should *not* try to suppress that fact.

2024-11-22 10:37 UTC, nikic commented
@pkarveti Please check whether your code is clean under `-fsanitize=undefined`. If you want to use a negative index on an array, you need to do so using a signed index, not an unsigned one.

2024-11-22 21:22 UTC, iajbar commented
Pavani checked if the code is clean under -fsanitize=undefined and an overflow was detected in the test. This patch can be abandoned.

2024-11-24 07:09 UTC, closed without merging