[clang] Absoultify paths in dependency file output
llvm/llvm-project pull request #117458
Opened 2024-11-24 01:57 UTC by xtexChooser

This fixes #117438.

If paths in dependency file are not absoulte, make (or ninja) will canonicalize them.
While their canonicalization does not involves symbolic links expansion (for IO performance concerns), leaving a non-absolute path in dependency file may lead to unexpected canonicalization.
For example, '/a/../b', where '/a' is a symlink to '/c/d', it should be '/c/b' but make (and ninja) canonicalizes it as '/b', and fails for file not found.

2024-12-01 04:19 UTC, xtexChooser commented
Ping

2024-12-01 07:23 UTC, xtexChooser commented
cc @jansvoboda11

2024-12-29 07:08 UTC, xtexChooser commented
cc @MaskRay

2024-12-30 21:50 UTC, MaskRay requested changes

2024-12-30 21:50 UTC, MaskRay commented on clang/lib/Frontend/DependencyFile.cpp
> +    FS->makeAbsolute(NativePath);
`makeAbsolute` does not resolve an absolute path, so this does not work as intended.

`Make path absolute` => `Resolve an absolute path`?

2024-12-30 21:51 UTC, MaskRay commented on clang/lib/Frontend/DependencyFile.cpp
> +    FS->makeAbsolute(NativePath);
You can make the function `functionName` instead of `FunctionName` while updating its signature.

2024-12-31 18:40 UTC, MaskRay approved these changes

2024-12-31 18:40 UTC, MaskRay commented on clang/test/VFS/external-names.c
> +// CHECK-DEP: Inputs
`Inputs{{..?}}external-names.h`

2024-12-31 18:40 UTC, MaskRay commented on clang/lib/Frontend/DependencyFile.cpp
> +  // Resolve absolute path. Make and Ninja canonicalize paths
TIL the Make behavior :)

@madscientist

2025-01-01 00:48 UTC, MaskRay commented
There is a typo in the subject. Absoultify => Absolutify. That said, sth like "canonicalize absolute paths " seem more appropriate wrt the changed semantics.

2025-01-01 08:27 UTC, xtexChooser commented
Done

2025-01-01 08:29 UTC, merged

2025-01-03 07:43 UTC, kadircet commented
It's hard to say what's the right/wrong behavior when it comes to symlink handling, but I am having a hard time understanding what kind of applications can benefit from this new behavior. AFAICT most workflows that involve dependency files use it for "caching" purposes, and some use it to for shipping dependencies to a remote build environment.

As some lit test changes also demonstrate, after this change a symlink like `b/header.h` -> `a/header.h` won't be captured in the dep output. So if the user modifies `b/header.h`, build systems won't invalidate their caches, or a remote build system that sets up a directory layout will fail compilations due to missing header `b/header.h` (as that's how clang will try to retrieve this file).

Hence I think clang's previous behavior that preserved symlinks was actually the only desired behavior for current applications, AFAICT there's no way to correctly capture all of this dependencies if we resolve symlinks. I'd argue that your issue is with the downstream consumers of these deps files and needs to be addressed at their layer.

If you think I misunderstood the situation around what's broken in the downstream users, can you please clarify why do you think the new behavior is "correct"? Otherwise I think we should revert this change to make sure we don't cause breakages that won't be detected until a new release.

2025-01-04 09:50 UTC, xtexChooser commented
what you said is also a problem. maybe we should print both raw path and resolved path?

If the path is not resolved, Make and Ninja will canonicalize these paths without resolving directory symbolic-links in the path, which may lead to a broken path.
As the example I have given above, `/lib64/../xxx.h` may be converted into `/xxx.h` and lead to broken caches.

It is also true that these build tools have their own performance concerns, while canonicalizing a large number of paths may be slow. Doing this in LLVM can make the process a one-time job (if the file is not modified). Thus, I think we need another change to print original non-canonicalized path, too.

2025-01-04 10:46 UTC, xtexChooser commented
Ahhh wait, if the original path is also printed, Make may see them as broken. I don't know what to do now, oops.