[LLDB][ThreadELFCore] Set all the properties of ELFLinuxSigInfo to a non build dependent size
llvm/llvm-project pull request #117604
Opened 2024-11-25 18:30 UTC by Jlalond

On #110065 the changes to LinuxSigInfo Struct introduced some variables that will differ in size on 32b or 64b. I've rectified this by setting them all to build independent types.

2024-11-25 18:30 UTC, Jlalond commented
@tuliom I don't have a way to verify this, would you mind assisting?

2024-11-25 21:28 UTC, tuliom requested changes
This didn't help. The size on 32-bits continue to be 44.
I think the difference is not really caused the size of the properties on 32 bits, but the implicit padding on 32/64 bits.

Look at the code generated here: https://godbolt.org/z/j5WxTTess

By commenting the pads or changing their size you can see the impact on the size of the struct and on the address of each of its member.

2024-11-25 22:42 UTC, Jlalond commented
@tuliom Experimented on godbolt a bit, it looks like alignas(8) will handle our padding to 56 on 32 and 64 https://godbolt.org/z/ssqeeEs71

2024-11-26 12:12 UTC, tuliom approved these changes
The build succeeded!

The source comment at line 82 caught my attention, though.
It may imply that data layout is important in this struct, i.e. it should match `siginfo_t` returned by the OS. But this change is not guaranteeing that.

Actually, the order of the first 3 integers do change on different systems.

With that said, this LGTM considering that data layout doesn't need to match the OS' `siginfo_t`.

2024-11-26 18:20 UTC, Jlalond commented
> The build succeeded!
> 
> The source comment at line 82 caught my attention, though. It may imply that data layout is important in this struct, i.e. it should match `siginfo_t` returned by the OS. But this change is not guaranteeing that.
> 
> Actually, the order of the first 3 integers do change on different systems.
> 
> With that said, this LGTM considering that data layout doesn't need to match the OS' `siginfo_t`.

I'll look into fixing the comment, but I'm going to merge to unbreak everyone's builds!

2024-11-26 18:20 UTC, merged