[Verifier] Allow vector type in atomic load and store
llvm/llvm-project pull request #117625
Opened 2024-11-25 20:20 UTC by jofrn

Vector types on atomics are assumed to be invalid by the verifier. However, this type can be valid if it is lowered by codegen.

2024-11-25 20:53 UTC, jofrn commented
#117189 requires this change.

2024-12-04 17:43 UTC, arsenm commented on llvm/test/Verifier/atomics.ll
> +%ty = type { i32 };
Add to the atomic test in test/Assembler with newly permitted cases

2024-12-04 18:34 UTC, jyknight commented
I'm a little confused by the steps being taken here.

Can we have this fallback via cast to integer by default on _all_ platforms, at the same time as making it legal? (That's how floats were handled, e.g.). We shouldn't have this work only on some platforms, but not others.

2024-12-04 18:41 UTC, jofrn commented
> I'm a little confused by the steps being taken here.
> 
> Can we have this fallback via cast to integer by default on _all_ platforms, at the same time as making it legal? (That's how floats were handled, e.g.). We shouldn't have this work only on some platforms, but not others.

We can do that. However, the Verifier would still mark it as invalid. The subsequent PR only lowers for X86 ; this PR allows vector types without disabling verifier checks.

2024-12-04 19:18 UTC, jyknight commented
I don't understand why do this in multiple steps? Allow vectors in the verifier and update all of the existing implementations of shouldCastAtomic{Load,Story}InIR to cast vectors at the same time?

2024-12-04 20:24 UTC, jofrn commented
Verifier checks can be disabled with `-disable-verify`, which already permits the lowering of atomic load/store with vector type in multiple targets, as such, some are already implemented. Permitting the type in Verifier/IR is different than a single implementation of the lowering.

2024-12-04 20:38 UTC, arsenm commented
> Can we have this fallback via cast to integer by default on _all_ platforms, at the same time as making it legal? (That's how floats were handled, e.g.). 

Disagree, split the IR verifier change from the codegen pieces.

> We shouldn't have this work only on some platforms, but not others.

There's a ton of IR that will not work on all platforms with varying failure modes, this case isn't special (e.g. 128-bit atomics)

2024-12-04 20:53 UTC, nikic commented
I agree with @jyknight that this needs to come with support for all targets, not just X86. Preferably implemented in a way that does not require defining a hook in every single backend.

> > We shouldn't have this work only on some platforms, but not others.
> 
> There's a ton of IR that will not work on all platforms with varying failure modes, this case isn't special (e.g. 128-bit atomics)

We should always aspire to make generic IR constructs work target-independently. If we have fallen short of that in some area, that's not an excuse to repeat the mistake.

2024-12-04 21:55 UTC, jyknight commented
> Verifier checks can be disabled with -disable-verify, which already permits the lowering of atomic load/store with vector type in multiple targets

Currently, IR having load/store atomic with a vector type is invalid. If you disable the verifier and provide invalid IR to LLVM, what happens next may be arbitrary -- nobody should be depending on that.

So, I would strongly suggest that the first change be to _unconditionally_ cast the vector to integers -- both in the base class TargetLoweringBase::shouldCastAtomicLoadInIR/shouldCastAtomicStoreInIR and in all the overrides (looks like 3 of those: NVPTX, AMDGPU, SystemZ).

Then, you can make separate follow-up changes for each target to opt out of the cast when possible.

2024-12-04 22:07 UTC, arsenm commented
> I agree with @jyknight that this needs to come with support for all targets, not just X86. Preferably implemented in a way that does not require defining a hook in every single backend.

Yes, the codegen patch should implement the generic path for all targets. But in terms of patch splitting, that shouldn't be in this PR

> We should always aspire to make generic IR constructs work target-independently. If we have fallen short of that in some area, that's not an excuse to repeat the mistake.

There are limits to what is practically implementable for operations that support arbitrary types. ppc_f128, x86_fp80, scalable vectors, and arbitrarily sized atomics are never going to be universally supported.

> So, I would strongly suggest that the first change be to unconditionally cast the vector to integers -- both in the base class TargetLoweringBase::shouldCastAtomicLoadInIR/shouldCastAtomicStoreInIR and in all the overrides (looks like 3 of those: NVPTX, AMDGPU, SystemZ).

We really should get rid of these hooks. There's no reason this can't just be handled by ordinary type legalization

2024-12-04 23:24 UTC, jyknight commented
> The change from my end only needs X86 support, and that is all that is implemented at the moment

That is insufficient. The functionality (of passing a vector type to load/store atomic) needs to work for all targets, even if your use-case doesn't require it.

2024-12-04 23:26 UTC, arsenm commented
> Sounds great, but _that_ certainly seems like a separable change. Since these hooks are how it's done today for floats, I don't see a reason to (initially) do something different for vectors.

I switched AMDGPU to use the DAG legalization in 82bb2534d4de16abb7a51fc646d5c31d6cec5eeb. I thought I switched X86 over but that seems to not have landed 

> The change from my end only needs X86 support. 

There's no plus to only doing x86. Just handle in the default implementation of the hook

2024-12-04 23:39 UTC, jofrn commented
Regardless of using the hook, backends are still able to implement atomic load/store of vector, so I do not see why we cannot enable the verifier change separately.

It is very easy to switch all the backends to use the hook, but the DAG legalization change will require more work to check all the backends.

We can add the hook for NVPTX, AMDGPU, and SystemZ by moving the check to the base class. And the DAG legalization can come later since that requires more work.

2024-12-05 10:53 UTC, nikic requested changes
We can land the verifier change separately, but only after a non-x86-specific patch for backend support is available as well.

2024-12-05 12:15 UTC, jofrn commented
| We can land the verifier change separately, but only after a non-x86-specific patch for backend support is available as well.
Okay, split https://github.com/llvm/llvm-project/pull/111414 into itself and https://github.com/llvm/llvm-project/pull/118793.

2024-12-18 18:36 UTC, jofrn commented
Follow-up is here: #120384
@nikic, do you have any other comments?

2024-12-18 23:34 UTC, jyknight commented
I'm a little confused as to which PRs are intended to be reviewed now. Is it only the "follow-up" series of 4 PRs you've linked to? Or are some/all of the other 3 PRs you've sent still active?

2024-12-19 02:40 UTC, jofrn commented
> I'm a little confused as to which PRs are intended to be reviewed now. Is it only the "follow-up" series of 4 PRs you've linked to? Or are some/all of the other 3 PRs you've sent still active?
The follow-up has a set of new PRs associated. #117625, #111414, #118793, and #120316 are now inactive.

2024-12-19 02:40 UTC, closed without merging