[mlir][Affine] Genarilze the linearize(delinearize()) simplifications
llvm/llvm-project pull request #117637
Opened 2024-11-25 22:38 UTC by krzysz00

The existing canonicalization patterns would only cancel out cases where the entire result list of an affine.delineraize_index was passed to an affine.lineraize_index and the basis elements matched exactly (except possibly for the outer bounds).

This was correct, but limited, and left open many cases where a delinearize_index would take a series of divisions and modulos only for a subsequent linearize_index to use additions and multiplications to undo all that work.

This sort of simplification is reasably easy to observe at the level of splititng and merging indexes, but difficult to perform once the underlying arithmetic operations have been created.

Therefore, this commit generalizes the existing simplification logic.

Now, any run of two or more delinearize_index results that appears within the argument list of a linearize_index operation with the same basis (or where they're both at the outermost position and so can be unbonded, or when `linearize_index disjoint` implies a bound not present on the `delinearize_index`) will be reduced to one signle delinearize_index output, whose basis element (that is, size or length) is equal to the product of the sizes that were simplified away.

That is, we can now simplify

    %0:2 = affine.delinearize_index %n into (8, 8) : inde, index
    %1 = affine.linearize_index [%x, %0#0, %0#1, %y] by (3, 8, 8, 5) : index

to the simpler

    %1 = affine.linearize_index [%x, %n, %y] by (3, 64, 5) : index

This new pattern also works with dynamically-sized basis values.

While I'm here, I fixed a bunch of typos in existing tests, and added a new getPaddedBasis() method to make processing
potentially-underspecified basis elements simpler in some cases.

2024-11-28 10:03 UTC, Abhishek-Varma requested changes
Thanks for adding this @krzysz00 !

2024-11-28 10:03 UTC, Abhishek-Varma commented on mlir/lib/Dialect/Affine/IR/AffineOps.cpp
> +    llvm::SmallPtrSet<Operation *, 2> seen;
Add a comment on what `seen` holds - also a bit descriptive name would work too.

2024-12-02 17:28 UTC, krzysz00 commented on mlir/lib/Dialect/Affine/IR/AffineOps.cpp
> +      ///  correct.
This actually doesn't require `disjoint` - the outputs of a delinearize are disjoint in that sense by definition

2024-12-02 17:30 UTC, krzysz00 commented on mlir/lib/Dialect/Affine/IR/AffineOps.cpp
> +      unsigned firstDelinArg = asResult.getResultNumber();
Yeah, solid point. I went with `delinArgIdx`

2024-12-02 17:32 UTC, krzysz00 commented on mlir/include/mlir/Dialect/Affine/IR/AffineOps.td
> +    SmallVector<OpFoldResult> getPaddedBasis();
It _might_, and ... yeah, I'm not strongly attached to the name

2024-12-02 17:33 UTC, krzysz00 commented on mlir/include/mlir/Dialect/Affine/IR/AffineOps.td
> +    SmallVector<OpFoldResult> getPaddedBasis();
But also it's a bit wordier - let me know if you have strong thoughts here

2024-12-04 06:37 UTC, Abhishek-Varma commented on mlir/include/mlir/Dialect/Affine/IR/AffineOps.td
> +    SmallVector<OpFoldResult> getPaddedBasis();
Sure, no worries - but I'd still prefer making the doc comment simpler : `Same as getMixedBasis, but the leading entry will include a nullptr if no outer bound is specified`.

2024-12-04 06:41 UTC, Abhishek-Varma requested changes
It'd be nice to make the current pattern work for the following case :-

```
func.func private @myfunc(%arg0: index) -> (index, index, index) {
  %c0 = arith.constant 0 : index
  %0:3 = affine.delinearize_index %arg0 into (8, 8, 4) : index, index, index
  %1 = affine.linearize_index disjoint [%0#2, %0#0, %c0, %c0] by (4, 8, 4, 8) : index
  %2 = affine.linearize_index disjoint [%0#1, %0#2, %c0, %c0] by (8, 4, 8, 4) : index
  %3 = affine.linearize_index disjoint [%0#1, %0#0, %c0, %c0] by (8, 8, 4, 4) : index
  return %1, %2, %3 : index, index, index
}
```

Basically this is the case where multiple `affine.linearize_index` feed off of SAME `affine.delinearize_index`. Currently this causes ` operand <NUM> does not dominate this use` resulting in an invalid IR.

Perhaps some missing `setInsertionPoint*` in the pattern.

2025-01-01 07:39 UTC, Abhishek-Varma approved these changes
LGTM! Thanks @krzysz00 for the changes!

2025-01-03 21:12 UTC, merged