[clang-tidy] fix false positive in bugprone-return-const-ref-from-parameter
llvm/llvm-project pull request #117734
Opened 2024-11-26 16:26 UTC by jcsxky

Fix https://github.com/llvm/llvm-project/issues/115743

2024-11-26 16:30 UTC, EugeneZelenko commented
Please rebase from current `main`.

2024-11-26 17:03 UTC, EugeneZelenko commented on clang-tools-extra/docs/ReleaseNotes.rst
> +  by using the conditional operator ``cond ? var1 : var2``and no longer giving
```suggestion
  by using the conditional operator ``cond ? var1 : var2`` and no longer giving
```

2024-11-26 17:14 UTC, PiotrZSL commented on clang-tools-extra/test/clang-tidy/checkers/bugprone/return-const-ref-from-parameter.cpp
> +}
Please add test:
```
const auto get = [](const T& t2) -> const T& { return t2; };
```
and verify that it's being still detected.

2024-11-26 17:14 UTC, PiotrZSL commented on clang-tools-extra/clang-tidy/bugprone/ReturnConstRefFromParameterCheck.cpp
> +                 parmVarDecl(hasDeclContext(functionDecl().bind("owner"))))
no need for duplicating parmVarDecl

2024-11-26 17:15 UTC, PiotrZSL requested changes
Please add positive test for lambdas.

2024-11-28 14:42 UTC, jcsxky commented
> Please add positive test for lambdas.

Positive test cases have been added.

2024-11-28 14:48 UTC, HerrCai0907 approved these changes

2024-11-28 14:48 UTC, HerrCai0907 commented on clang-tools-extra/docs/ReleaseNotes.rst
> +  by using the conditional operator ``cond ? var1 : var2`` and no longer giving
I am not sure it is a fix of false positives. Maybe in generic, it more looks like add support of lambda function.

2024-11-30 00:29 UTC, merged