users/ccc/fix/module use internal linkage
llvm/llvm-project pull request #117901
Opened 2024-11-27 16:25 UTC by HerrCai0907

- **[ast-matcher] add `exportDecl` matcher**
- **[clang-tidy][use-internal-linkage]fix false positives for `ExportDecl`**

2024-11-27 17:43 UTC, PiotrZSL requested changes
Documentation & Test for matcher is missing.
Except that everything looks ok.

2024-11-27 17:43 UTC, PiotrZSL commented on clang/include/clang/ASTMatchers/ASTMatchers.h
> +extern const internal::VariadicDynCastAllOfMatcher<Decl, ExportDecl> exportDecl;
Documentation for this matcher need to be updated so it would be visible on https://clang.llvm.org/docs/LibASTMatchersReference.html

2024-11-27 17:43 UTC, PiotrZSL commented on clang/include/clang/ASTMatchers/ASTMatchers.h
> +extern const internal::VariadicDynCastAllOfMatcher<Decl, ExportDecl> exportDecl;
Test for this matcher should be added (outside clang-tidy).

2024-11-30 10:37 UTC, 5chmidti reviewed
Please add the matcher to https://github.com/llvm/llvm-project/blob/main/clang/lib/ASTMatchers/Dynamic/Registry.cpp as well (clang-query).

2024-11-30 14:13 UTC, HerrCai0907 commented
> Please add the matcher to https://github.com/llvm/llvm-project/blob/main/clang/lib/ASTMatchers/Dynamic/Registry.cpp as well (clang-query).

i will do it separately to avoid this pr become bigger.

2024-11-30 14:34 UTC, PiotrZSL approved these changes

2024-11-30 20:51 UTC, 5chmidti commented
> > Please add the matcher to https://github.com/llvm/llvm-project/blob/main/clang/lib/ASTMatchers/Dynamic/Registry.cpp as well (clang-query).
> 
> i will do it separately to avoid this pr become bigger.

I think you only have to add it into that file for it to work, and IMO a single PR for this change would be better. But as long as it gets added, I'm fine with it

2024-12-02 05:59 UTC, merged