[FixIt] Improve Source Ranges and Fix-It Hints for Unused Lambda Captures
llvm/llvm-project pull request #117953
Opened 2024-11-28 01:55 UTC by charan-003

**Key Changes**
**Enhancements in SemaLambda.cpp:**

Updated the ExplicitCaptureRanges logic to compute more precise source ranges for unused lambda captures.

- Fixed the handling of edge cases, including:
- Trailing and leading whitespace in captures.
- Redundant commas.
- Mixed captures (e.g., [=, &a, b]).
- 

**Test Improvements in fixit-unused-lambda-capture.cpp:**

- Added new tests to validate correct Fix-It suggestions for edge cases:
- Redundant commas like [a, , b].
- Leading/trailing whitespace in capture lists.
- Mixed capture styles (e.g., [=, &a]).
- Single and multiple unused captures in different scenarios.

2024-11-28 04:53 UTC, charan-003 reviewed
[FixIt] Improve Source Ranges and Fix-It Hints for Unused Lambda Captures #106445

2024-11-28 04:59 UTC, charan-003 reviewed
[FixIt] Improve Source Ranges and Fix-It Hints for Unused Lambda Captures #106445

2024-11-28 05:07 UTC, charan-003 reviewed
mprove Source Ranges and Fix-It Hints for Unused Lambda Captures #106445

2024-11-28 05:16 UTC, charan-003 reviewed
[FixIt] Improve Source Ranges and Fix-It Hints for Unused Lambda Captures #106445

2024-11-28 13:40 UTC, cor3ntin commented
By the time we are in Sema, the ranges should be correct.
I think the issue is somewhere in `Parser::ParseLambdaIntroducer`. It does seem quite confused https://gcc.godbolt.org/z/h7rfEGnMb

In particular, can you check whether `SourceLocation LocEnd = PrevTokLocation;` behave correctly?

2024-11-30 01:23 UTC, charan-003 commented
hi @cor3ntin made necessary updates to ParseExprCXX.cpp, but now ten tests are failing. Could you kindly provide on how to debug them? What are the main areas in ParseExprCXX.cpp that I should concentrate on while debugging these kinds of problems?

2024-12-16 19:05 UTC, charan-003 commented
Hi @cor3ntin 

After making changes in ParseExprCXX.cpp, I’m down to 10 failing test cases related to lambda parsing and Fix-It hints for unused captures. I reviewed Parser::ParseLambdaIntroducer and checked how SourceLocation LocEnd = PrevTokLocation; is used, but I’m still uncertain about where the incorrect source ranges might be originating.

Could you suggest:

Specific Parsing Logic: Which part of ParseLambdaIntroducer should I focus on when debugging incorrect source ranges? Are there common issues with PrevTokLocation assignments?

Source Location Validations: Would it be helpful to insert assertions or debug prints at specific points in the parser to check computed source ranges during parsing?

Next Steps: Given the test cases I shared earlier, would focusing on a particular test provide better insight into the issue?

2024-12-20 22:10 UTC, charan-003 reviewed
added few test cases

2024-12-21 00:02 UTC, charan-003 reviewed
.

2024-12-21 00:07 UTC, charan-003 reviewed
.

2025-01-16 17:22 UTC, cor3ntin commented
@erichkeane this is still doing lexing things in Sema, I was actually wondering if you had suggestions :D

2025-01-16 17:24 UTC, erichkeane commented
> @erichkeane this is still doing lexing things in Sema, I was actually wondering if you had suggestions :D

Ah, i thought I'd mentioned on this before.  Yeah, I very much would expect all of the work this is doing to be possible in the parser.  Sema shouldn't be setting ranges, that is the responsibility of the parser, who knows where the actual lines/stuff is.

2025-01-21 19:38 UTC, charan-003 commented
> > @erichkeane this is still doing lexing things in Sema, I was actually wondering if you had suggestions :D
> 
> Ah, i thought I'd mentioned on this before. Yeah, I very much would expect all of the work this is doing to be possible in the parser. Sema shouldn't be setting ranges, that is the responsibility of the parser, who knows where the actual lines/stuff is.

Hii, can you please give me suggestions , where to work on , i'm kinda confused, little bit details would help me finishing this
thank you

2025-01-22 10:03 UTC, charan-003 commented
Hi @erichkeane, thank you for the feedback! I understand that the lexing logic should be moved to the parser. Could you please point me toward specific areas in the parser where this logic should be integrated? A bit more detail would help me ensure this is implemented correctly. Thank you!

2025-01-22 14:21 UTC, erichkeane commented
> Hi @erichkeane, thank you for the feedback! I understand that the lexing logic should be moved to the parser. Could you please point me toward specific areas in the parser where this logic should be integrated? A bit more detail would help me ensure this is implemented correctly. Thank you!

@cor3ntin is the parser owner can help identify a spot, but likely while we are parsing the lambda capture section directly.  If you debug it, you should be able to see where we consume that token.  Generally source locations should be created right about the same moment we consume the token.

2025-02-10 19:47 UTC, Sirraide commented on clang/lib/Sema/SemaLambda.cpp
> +      if (C->InitCaptureType.get().isNull() && !C->Init.isUsable()) {
The `&& !C->Init.isUsable()` makes this `if` statement effectively dead code since it’s inside a check for `C->Init.isUsable()`, which means this is basically just `&& false`.

2025-02-11 02:13 UTC, charan-003 commented on clang/lib/Sema/SemaLambda.cpp
> +      if (C->InitCaptureType.get().isNull() && !C->Init.isUsable()) {
@AaronBallman @Sirraide 
Okay, that makes sense. I tried working on it and removed the redundant && !C->Init.isUsable() condition, but I still get a crash when running tests. Here’s the error I see:

RUN: at line 1: /Users/.../clang -cc1 -internal-isystem /Users/.../build/lib/clang/20/include -nostdsysteminc -std=c++1y /Users/.../llvm-project/.../clang/test/SemaCXX/cxx1y-init-captures.cpp -verify -emit-llvm-only
+ /Users/.../clang -cc1 -internal-isystem /Users/.../build/lib/clang/20/include -nostdsysteminc -std=c++1y /Users/.../llvm-project/.../clang/test/SemaCXX/cxx1y-init-captures.cpp -verify -emit-llvm-only
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:


It seems like the issue is still present, so I’m wondering if there’s something else I might be missing. Could this be related to InitCaptureType still being null in some cases? Or could there be another part of createLambdaInitCaptureVarDecl() that needs to be adjusted? Any hints on what I should check next?

2025-02-19 16:47 UTC, erichkeane reviewed
Only a quick scroll through here, and @cor3ntin is the right one to review this, but the test coverage for the new diagnostics seems non-existant.  And much of the test changes themselves are just changing what looks like they are valid tests.

Please ADD tests for your new things, and make it clear what/why you're changing existing tests in this way.

2025-02-19 16:47 UTC, erichkeane commented on clang/test/SemaCXX/lambda-expressions.cpp
> +  auto s0 = S1([]() {}); // Remove invalid capture, no diagnostic expected
why change the test?  this one seemed like a useful diagnostic, and one I'd like to see.

2025-05-07 05:50 UTC, cor3ntin commented on clang/test/SemaCXX/lambda-expressions.cpp
> +  auto s0 = S1([]() {}); // Remove invalid capture, no diagnostic expected
@charan-003

2025-05-07 13:10 UTC, charan-003 commented
@cor3ntin Also, I'm nearly done with this task. Can it be assigned to me?

2025-05-14 03:15 UTC, ojhunt requested changes
There are a lot of changes that are non-functional (NFC) formatting changes, it would help to remove those changes from this PR as it makes the PR larger than necessary.

Another common issue is excess braces - the llvm formatting rule is no braces for `if`, etc if there is a single statement even if the statement crosses multiple lines.

2025-05-14 03:15 UTC, ojhunt commented on clang/lib/Sema/SemaLambda.cpp
> +    const bool CanCaptureThis = !S.CheckCXXThisCapture(
This looks like an irrelevant formatting change? possibly the result of accumulated changes

2025-05-14 03:15 UTC, ojhunt commented on clang/lib/Sema/SemaLambda.cpp
> +        /*R angle loc*/ LSI->ExplicitTemplateParamsRange.getEnd(),
irrelevant formatting change

2025-05-14 03:15 UTC, ojhunt commented on clang/lib/Sema/SemaLambda.cpp
> +      if (const DeclContext *LexicalDC =
irrelevant formatting change again

2025-05-14 03:15 UTC, ojhunt commented on clang/lib/Sema/SemaLambda.cpp
> +  assert(!TParams.empty() && "No template parameters to act on");
NFC formatting change

2025-05-14 03:15 UTC, ojhunt commented on clang/lib/Sema/SemaLambda.cpp
> +    if (EnumConstantDecl *D = dyn_cast<EnumConstantDecl>(DRE->getDecl())) {
NFC formatting change

2025-05-14 03:15 UTC, ojhunt commented on clang/lib/Sema/SemaLambda.cpp
> +static EnumDecl *findCommonEnumForBlockReturns(ArrayRef<ReturnStmt *> returns) {
NFC formatting changes

2025-05-14 03:15 UTC, ojhunt commented on clang/lib/Sema/SemaLambda.cpp
> +  if (!ED)
NFC formatting change

2025-05-14 03:15 UTC, ojhunt commented on clang/lib/Sema/SemaLambda.cpp
> +  if (!ED->hasNameForLinkage())
NFC formatting change

2025-05-14 03:15 UTC, ojhunt commented on clang/lib/Sema/SemaLambda.cpp
> +                .getAsRange();
I'd prefer `.getAsRange();` on the preceding line, but if clang-format puts it here I guess we accept that.

2025-05-14 03:15 UTC, ojhunt commented on clang/lib/Sema/SemaLambda.cpp
> +      continue; // // skip further processing for `this` and `*this` captures.
Remove the extra //

2025-05-14 03:15 UTC, ojhunt commented on clang/lib/Sema/SemaLambda.cpp
> +    if (!C->Id) {                                                     //
a bunch of excess `//`'s on this and the next block

2025-05-14 03:15 UTC, ojhunt commented on clang/lib/Sema/SemaLambda.cpp
> +        if (DeducedType.isNull()) {
single statement `if` should not have {}'s

2025-05-14 03:15 UTC, ojhunt commented on clang/lib/Sema/SemaLambda.cpp
> +          if (!DeducedType->isDependentType()) {
excess braces again

2025-05-14 03:15 UTC, ojhunt commented on clang/lib/Sema/SemaLambda.cpp
> +          if (!TempVarDecl) {
excess brace

2025-05-14 03:15 UTC, ojhunt commented on clang/lib/Sema/SemaLambda.cpp
> +        if (!DeducedType.isNull()) {
excess braces

2025-05-14 03:15 UTC, ojhunt commented on clang/lib/Sema/SemaLambda.cpp
> -                SourceRange(getLocForEndOfToken(PrevCaptureLoc), C->Loc));
NFC formatting change that should be removed

2025-05-14 03:15 UTC, ojhunt commented on clang/lib/Sema/SemaLambda.cpp
> +  SmallVector<Decl *, 4> Fields(Class->fields());
NFC formatting change

2025-05-20 01:00 UTC, ojhunt commented on clang/lib/Sema/SemaLambda.cpp
> +    llvm::iterator_range<CallingConv *> Range(std::begin(Convs),
what is the reason for this change?

2025-05-21 20:41 UTC, charan-003 reviewed
.

2025-05-21 20:53 UTC, ojhunt commented on clang/lib/Sema/SemaLambda.cpp
> +    llvm::iterator_range<CallingConv *> Range(std::begin(Convs),
I mean the `std::unique` to `llvm::unique` change -- llvm::unique is just a wrapper for std::unique so this change is not needed

2025-05-21 20:59 UTC, charan-003 commented on clang/lib/Sema/SemaLambda.cpp
> +    llvm::iterator_range<CallingConv *> Range(std::begin(Convs),
ohh okay sure, let me try changing it

2025-05-21 21:05 UTC, ojhunt commented on clang/lib/Sema/SemaLambda.cpp
> +    llvm::iterator_range<CallingConv *> Range(std::begin(Convs),
I think there's no actual behavioral change so just reverting this specific change seems reasonable - ideally we want to avoid unrelated changes from PRs

2025-05-22 10:07 UTC, ojhunt commented on clang/include/clang/Basic/DiagnosticSemaKinds.td
> +def err_invalid_lambda_capture_initializer_type : Error<
I think you've last the code to emit these :-O

2025-05-23 10:26 UTC, closed without merging