[InstCombine] Add an additional nnan constraint for xfrm fcmp + sel => fmax/fmin
llvm/llvm-project pull request #117977
Opened 2024-11-28 08:11 UTC by rajatbajpai

Add an additional `nnan` constraint on the `fcmp` instruction for the `fcmp` + `select` => `fmax`/`fmin` xfrm. Without the `nnan` constraint, this transformation is incorrect.

Alive2 with and without the fix: https://alive2.llvm.org/ce/z/Hpo7WX

2024-11-28 08:16 UTC, rajatbajpai commented
@arsenm Could you please review this fix?
Original discussion about fixing this issue: https://github.com/llvm/llvm-project/pull/106492#discussion_r1781035045

2024-11-28 08:36 UTC, nikic reviewed
It doesn't look like the nnan is required, you just can't always preserve it? https://alive2.llvm.org/ce/z/4Dj45b

2024-11-28 08:42 UTC, rajatbajpai commented
Right now we try to preserve it even if `fcmp` doesn't have that flag. https://godbolt.org/z/5vPjrWT95

2024-11-28 09:16 UTC, dtcxzyw requested changes
https://alive2.llvm.org/ce/z/4PKqnZ

You should drop `nnan` in the new `maxnum/minnum` instead of blocking this transform.

2024-11-28 09:18 UTC, dtcxzyw commented
> https://alive2.llvm.org/ce/z/4PKqnZ
> 
> You should drop `nnan` in the new `maxnum/minnum` instead of blocking this transform.

Ignore me. @nikic already pointed out this.

2024-11-29 14:27 UTC, dtcxzyw commented on llvm/lib/Transforms/InstCombine/InstCombineSelect.cpp
> +        cast<Instruction>(BinIntr)->setHasNoNaNs(FCmp->hasNoNaNs());
`BinIntr` may be folded into a constant by IRBuilder.

2024-12-02 09:00 UTC, dtcxzyw approved these changes
LGTM. Thank you!

2024-12-02 10:46 UTC, rajatbajpai commented
Please merge the PR if it looks okay. Thanks!

2024-12-02 13:38 UTC, nikic commented
Can you please update the PR description / proof to match the new implementation?

2024-12-03 05:14 UTC, rajatbajpai commented
> Can you please update the PR description / proof to match the new implementation?

Done, thanks!

2024-12-03 06:01 UTC, merged