[AVR] Force relocations for jumps and calls
llvm/llvm-project pull request #118015
Opened 2024-11-28 15:20 UTC by Patryk27

This commit changes `shouldForceRelocation()` to always return `true` for indirect jumps, direct jumps and calls.

# Motivation

Over https://github.com/Rahix/avr-hal/pull/585 it was found out that the AVR codegen sometimes crashes with the `out of range branch target` message - this turned out to be a fallout from https://github.com/llvm/llvm-project/pull/106722 related to the fact that linkers are smarter than they seem!

The issue stems from the `rjmp` instruction - even though it can only encode offsets in the +-4 kB range, it can be used to jump into further memory addresses by relying on the fact that AVR memory wraps around the boundaries. That is, for a CPU with 8 kB of flash, `rjmp 5000` (illegal) can be actually encoded as `rjmp -3192` (legal).

Linkers apply this trick automatically, but since over https://github.com/llvm/llvm-project/pull/106722 we've decided to go with the `let's avoid emitting relocations` route...

We would've caught this, but since the `branch-relaxation-long.ll` test generated only the textual assembly, it never went near the assertion - I've changed the test to use `-filetype=obj | llvm-objdump -dr` now (which causes it to crash on the main branch, but succeeds with my changes here).

# Alternatives

We could re-do the wrapping logic directly within the codegen - in fact, that's what I started with! I've taught `AVRDevices.td` about the flash sizes (relying on data from avr-gcc):

```
class Device<string Name, Family Fam, ELFArch Arch, int FlashSizeArg,
             list<SubtargetFeature> ExtraFeatures = []>
    : Processor<Name, NoItineraries, !listconcat([Fam, Arch], ExtraFeatures)> {
  int FlashSize = FlashSizeArg;
}

def : Device<"avr1", FamilyAVR1, ELFArchAVR1, 0x400>;
def : Device<"avr2", FamilyAVR2, ELFArchAVR2, 0x60000>;
def : Device<"avr25", FamilyAVR25, ELFArchAVR25, 0x2000>;
def : Device<"avr3", FamilyAVR3, ELFArchAVR3, 0x6000>;
/* ... */
```
... created a new TableGen emitter:
```cpp
static void EmitAVRTargetDef(RecordKeeper &RK, raw_ostream &OS) {
  OS << "// Autogenerated by AVRTargetDefEmitter.cpp\n\n";

  OS << "namespace llvm {\n";
  OS << "namespace AVR {\n";
  OS << "\n";
  OS << "static const std::map<StringRef, uint32_t> FlashSizes = {\n";

  for (const Record *Rec : RK.getAllDerivedDefinitions("Device")) {
    OS << "  { \"" << Rec->getValueAsString("Name") << "\", "
       << Rec->getValueAsInt("FlashSize") << " },\n";
  }

  OS << "};\n";
  OS << "\n";
  OS << "inline uint32_t getFlashSize(StringRef cpu) {\n";
  OS << "  return FlashSizes.at(cpu);\n";
  OS << "}\n";
  OS << "\n";
  OS << "} // end of namespace AVR\n";
  OS << "} // end of namespace llvm\n";
}

static TableGen::Emitter::Opt X("gen-avr-target-def", EmitAVRTargetDef,
                                "Generate the list of CPUs for AVR");
```
... adjusted `adjustRelativeBranch()` to access this brand new `AVR::getFlashSize()`: 
```cpp
/// Adjusts the value of a relative branch target before fixup application.
static void adjustRelativeBranch(unsigned Size, const MCFixup &Fixup,
                                 uint64_t &Value, MCContext *Ctx) {
  // Jumps are relative to the current instruction.
  Value -= 2;

  // We have one extra bit of precision because the value is rightshifted by
  // one.
  Size += 1;

  if (!isIntN(Size, Value)) {
    uint64_t FlashSize =
        AVR::getFlashSize(Ctx->getSubtargetInfo()->getCPU().data());

    uint64_t ReverseValue =
        Value > 0 ? (uint64_t)((int32_t)Value - (int32_t)FlashSize)
                  : (uint64_t)((int32_t)FlashSize + (int32_t)Value);

    if (isIntN(Size, ReverseValue)) {
      Value = ReverseValue;
    }
  }

  ensureSignedWidth(Size, Value, std::string("branch target"), Fixup, Ctx);

  AVR::fixups::adjustBranchTarget(Value);
}
```
... and it worked!

I've eventually settled on relocations, because that's both the simpler approach and what we'd like to have anyway (to resemble avr-gcc, as I remember from discussions from the past).

2024-11-28 15:20 UTC, Patryk27 commented
cc @benshi001

2024-11-29 11:51 UTC, benshi001 commented
I think this change is so aggressive, just for special devices with 8KB but without long range JMP/CALL.

I suggest this way:
1. Introduce a new target feature, something like "RjmpWrap" (or a better name??)
2. Add this target feature to these special devices.
3. And then we perform force relocation with this new target feature specified.

2024-11-29 11:58 UTC, benshi001 reviewed
I think this change is so aggressive, just for some special devices with 8KB but without long range JMP/CALL.

I suggest this way:

1. Introduce a new target feature, something like "RjmpWrap" (or a better name??)
2. Add this target feature to these special devices.
3. And then we perform force relocation with this new target feature specified.

2024-12-02 05:51 UTC, benshi001 commented
> Hmm, so we'd like to diverge from avr-gcc's behavior, right?

Unless there is a very strong reason force us to follow avr-gcc.

2024-12-02 10:12 UTC, benshi001 commented
> Hmm, so we'd like to diverge from avr-gcc's behavior, right?

Is there a strong reason for us to strictly follow avr-gcc? My key concern is that the AVR backend has been stable, we need not do aggressive functional changes.

2024-12-03 00:33 UTC, benshi001 commented
But I also think supporting the flash space wrapping is necessary. If you have no time for my suggested solution, I will try it later this month.

2024-12-03 15:17 UTC, Patryk27 commented
> Is there a strong reason for us to strictly follow avr-gcc?

No, I don't think so - I'm up for avoiding relocations as well 🙂 

> If you have no time for my suggested solution, I will try it later this month.

I can do that, no problem - I'm just reflecting on the approach:

- Option A: Create a new feature (like `RjmpWrap`) and enable it for the smaller (8 kB) microcontrollers,
- Option B: Teach LLVM flash sizes of _all_ of the AVRs and implement logic that automatically applies the memory wrapping trick.

Option A is simpler to implement, while option B (as described in the `Alternatives` approach at the top) is potentially more versatile (we'll be able to apply the wrapping trick even for larger microcontrollers, if we happen to generate a branch large enough). Note that for larger uCs this trick is just a program-size optimization, not a requirement.

I'm leaning towards option B, since it feels less hacky to me, but I don't have any strong preference here - care to choose?

2024-12-04 02:24 UTC, benshi001 commented
> > Is there a strong reason for us to strictly follow avr-gcc?
> 
> No, I don't think so - I'm up for avoiding relocations as well 🙂
> 
> > If you have no time for my suggested solution, I will try it later this month.
> 
> I can do that, no problem - I'm just reflecting on the approach:
> 
> * Option A: Create a new feature (like `RjmpWrap`) and enable it for the smaller (8 kB) microcontrollers,
> * Option B: Teach LLVM flash sizes of _all_ of the AVRs and implement logic that automatically applies the memory wrapping trick.
> 
> Option A is simpler to implement, while option B (as described in the `Alternatives` approach at the top) is potentially more versatile (we'll be able to apply the wrapping trick even for larger microcontrollers, if we happen to generate a branch large enough). Note that for larger uCs this trick is just a program-size optimization, not a requirement.
> 
> I'm leaning towards option B, since it feels less hacky to me, but I don't have any strong preference here - care to choose?

I prefer A to B, because:
1. It is simpler, and less code changes.
2. For larger devices, we use long `JMP`, and let the linker to do the branch relaxation.

What's more,
1. we only add this new TargetFeature to devices with larger flash but without long `JMP`. Devices with flash size less than 4KB or with long `JMP` are unnecessary.
2. Generally I prefer `force relocation`, but if the devices have a unique flash size (for example 8KB), I also accept hard coding it into `adjustRelativeBranch` and in your 'Alternatives'.

2024-12-10 16:30 UTC, Patryk27 commented
Okie, ready! I've adjusted the description above as well. cc @benshi001

2024-12-22 11:37 UTC, Patryk27 commented
Rebased due to a conflict over https://github.com/llvm/llvm-project/commit/806761a7629df268c8aed49657aeccffa6bca449.

2024-12-23 00:50 UTC, benshi001 commented
> Rebased due to a conflict over [806761a](https://github.com/llvm/llvm-project/commit/806761a7629df268c8aed49657aeccffa6bca449).

Are you now on the Christmas holiday? What's your opinion on my comments? Do you mind I do the modification based on your code?

2024-12-23 06:33 UTC, Patryk27 commented
> What's your opinion on my comments? 

Which comments? 👀 

You mentioned using the feature-based approach, which I did implement - I don’t see any more comments 😅

2024-12-24 01:06 UTC, benshi001 commented
<img width="905" alt="截屏2024-12-24 09 04 57" src="https://github.com/user-attachments/assets/b0e8fc42-8fc2-496e-a4dc-27426742529b" />
<img width="920" alt="截屏2024-12-24 09 05 03" src="https://github.com/user-attachments/assets/e939a9d9-553b-42b7-9ff6-6919efbd9f31" />
<img width="938" alt="截屏2024-12-24 09 05 59" src="https://github.com/user-attachments/assets/bc7af140-4afa-44de-875c-6beb13cea25f" />

2024-12-24 01:11 UTC, benshi001 commented
I have posted three review advices as above .

2024-12-24 01:11 UTC, benshi001 requested changes

2024-12-24 13:38 UTC, Patryk27 commented
Cool, thanks! I'll take a look at the comments tomorrow 🙂

2024-12-26 14:58 UTC, Patryk27 commented on llvm/lib/Target/AVR/AVRDevices.td
> +def : Device<"avr25", FamilyAVR25, ELFArchAVR25, [FeatureWrappingRjmp]>;
Sure - fwiw this was synchronized with gcc:

https://github.com/gcc-mirror/gcc/blob/d061c681814917c2208f383bd6069e6ab90db220/gcc/config/avr/avr-mcus.def#L88

2024-12-26 15:04 UTC, Patryk27 commented on llvm/test/CodeGen/AVR/branch-relaxation-long-backward.ll
> +
Sure, test extended.

2024-12-26 15:04 UTC, Patryk27 commented
Ready!

2024-12-27 03:43 UTC, benshi001 approved these changes
LGTM. Thanks.

2024-12-27 03:44 UTC, merged

2024-12-27 21:04 UTC, mbuesch commented
Does this fix `attiny26`, too?

I get this
```
error: out of range branch target (expected an integer in the range -4096 to 4095)
```
with the nightly rust compiler on an `attiny26` target, too.

Would this change fix this, even though it doesn't apply `FeatureWrappingRjmp` to `attiny26`?

2024-12-27 21:54 UTC, mbuesch commented
I get this behavior with recent rust-nightly in this completely empty project:

[attiny26test.tar.gz](https://github.com/user-attachments/files/18263935/attiny26test.tar.gz)

It does build and work fine with `nightly-2024-03-22`. See `rust-toolchain.toml`.

2024-12-27 21:56 UTC, Patryk27 commented
Thanks for the reproducer, I'll take a look!

2025-03-17 05:58 UTC, MaskRay commented
The PR introduced two tests, which each larger than 81KiB. There are many `call void asm sideeffect "nop", ""()`. You could replace then with a `.space` directive`. See other targets' tests named `branch-relaxation.ll`

2025-03-17 06:14 UTC, Patryk27 commented
Thanks for the tip, I agree the duplicated `nop`s are unfortunate - I was playing with the `.space` directive, but it didn't work as intended, I'll play around with it again.

2025-04-29 04:54 UTC, ashutoshmishra52 commented on llvm/lib/Target/AVR/AVRDevices.td
hey

2025-04-29 04:54 UTC, ashutoshmishra52 commented
xv bx