[clang-tidy] Add modernize-make-direct check
llvm/llvm-project pull request #118120
Opened 2024-11-29 18:18 UTC by hjanuschka

Adds a new check that converts std::make_* function calls to direct constructor calls using CTAD. Transforms make_optional, make_unique, make_shared and make_pair into their equivalent direct constructor calls, leveraging C++17's class template argument deduction.

2024-11-29 19:38 UTC, firewave commented
This will conflict with `modernize-make-shared` and `modernize-make-unique`.

I also very sure having `new` any modern C++ code is very much to be avoided.

Having no insight on the differences of the inner workings - but just based on https://en.cppreference.com/w/cpp/memory/shared_ptr/make_shared#Notes this appears to be something behaving very differently and less optimal/safe.

2025-05-18 13:30 UTC, denzor200 requested changes

2025-06-10 21:50 UTC, hjanuschka commented
@denzor200 feedback addressed.
@firewave also your feedback addressed.


thank you both for your time, i kind of missed notifications for this PR

2025-06-11 00:27 UTC, denzor200 approved these changes

2025-06-11 20:01 UTC, EugeneZelenko commented on clang-tools-extra/docs/ReleaseNotes.rst
> +  Converts std::make_* function calls to direct constructor calls using CTAD.
```suggestion
  Converts ``std::make_*`` function calls to direct constructor calls using CTAD.
```

2025-06-11 20:01 UTC, EugeneZelenko commented on clang-tools-extra/docs/ReleaseNotes.rst
> +  Transforms make_optional, make_pair, and make_tuple into equivalent
Single sentence is enough.

2025-06-11 20:01 UTC, EugeneZelenko commented on clang-tools-extra/docs/clang-tidy/checks/modernize/make-direct.rst
> +Replaces ``std::make_*`` function calls with direct constructor calls using class template
Please synchronize with statement in Release Notes.

2025-06-11 20:02 UTC, vbvictor requested changes
Generally good check idea, but needs some polishing.
- Neither `modernize-make-function-to-direct` nor `modernize-make-direct` sounds clear to me (specifically `direct` part), the main purpose of this transformation is to use `CTAD`, it should be in the check name at least. `modernize-use-ctad-constructor` could be it, but I'm not 100% sure others will agree.
- I don't like having many options that all do the same job. How about a list of key-value pairs of classes and their corresponding `make_` function. Something like "std::pair=std::make_pair;std::optional=std::make_optional...". Look at `readability-suspicious-call-argument.Abbreviations` for reference.
- Enhance tests with type aliases, macros, template parameters

2025-06-11 20:02 UTC, vbvictor commented on clang-tools-extra/clang-tidy/modernize/CMakeLists.txt
> +  MakeFunctionToDirectCheck.cpp
Please format alphabetically

2025-06-11 20:02 UTC, vbvictor commented on clang-tools-extra/clang-tidy/modernize/MakeFunctionToDirectCheck.cpp
> +} // namespace clang::tidy::modernize
Add newline

2025-06-11 20:02 UTC, vbvictor commented on clang-tools-extra/clang-tidy/modernize/MakeFunctionToDirectCheck.h
> +#endif // LLVM_CLANG_TOOLS_EXTRA_CLANG_TIDY_MODERNIZE_MAKEFUNCTIONTODIRECTCHECK_H
Add newline

2025-06-11 20:02 UTC, vbvictor commented on clang-tools-extra/clang-tidy/modernize/ModernizeTidyModule.cpp
> +        "modernize-make-direct");
Please format alphabetically

2025-06-11 20:02 UTC, vbvictor commented on clang-tools-extra/docs/ReleaseNotes.rst
> +- New :doc:`modernize-make-direct <clang-tidy/checks/modernize/make-direct>` check.
Please format alphabetically and place doc string same as other checks. `<>` should be on the next line

2025-06-11 20:02 UTC, vbvictor commented on clang-tools-extra/docs/ReleaseNotes.rst
> +  Converts std::make_* function calls to direct constructor calls using CTAD.
Please sync with docs first sentence (should be identical)

2025-06-11 20:02 UTC, vbvictor commented on clang-tools-extra/docs/clang-tidy/checks/modernize/make-direct.rst
> +modernize-make-direct
Sync check name accross all files, somewhere you have "MakeFunctionToDirect".

2025-06-11 20:02 UTC, vbvictor commented on clang-tools-extra/clang-tidy/modernize/MakeFunctionToDirectCheck.cpp
> +                     qualType(hasCanonicalType(qualType(asString("void")))))))))
Could you please elaborate why do you need this `unless(hasParen(...))` in your check?
I didn't find tests that will use this behavior, or I couldn't understand what existing test used it:(

2025-06-11 20:02 UTC, vbvictor commented on clang-tools-extra/clang-tidy/modernize/MakeFunctionToDirectCheck.cpp
> +  std::vector<RewriteRuleWith<std::string>> Rules;
consider using llvm::SmallVector

2025-07-01 17:21 UTC, denzor200 requested changes

2025-07-01 17:21 UTC, denzor200 commented on clang-tools-extra/test/clang-tidy/checkers/modernize/make-direct-check.cpp
> +  auto t1 = std::make_tuple(1, 2.0, "hi");
please add
```
const int arg = 2.0;
auto t2 = std::make_tuple(1, std::cref(arg), "hi");
```
this check must be silent in this case

2025-07-30 17:45 UTC, localspook commented
You should add "Fixes #121295" to the PR description

2025-07-30 19:09 UTC, carlosgalvezp commented on clang-tools-extra/docs/clang-tidy/checks/modernize/make-direct.rst
> +.. option:: CheckMakePair
This should instead be 1 option with a semicolon separated list of which functions to transform.

2025-07-30 19:10 UTC, carlosgalvezp commented on clang-tools-extra/docs/clang-tidy/checks/modernize/make-direct.rst
> +   Use the dedicated ``modernize-make-unique`` and ``modernize-make-shared`` checks
This is confusing, since these checks do the exact opposite of what this check is doing. I would vote for removing this line.

2025-07-30 19:13 UTC, carlosgalvezp requested changes
Couple of minor changes.

I'm not convinced about the name of the check, `make-function-to-direct` does not really say much. What is a "make function" and what is "direct"?

Would it make sense to call it `modernize-use-ctad` and possibly leave the door open for more use cases in follow-up patches?

2025-07-30 21:09 UTC, vbvictor commented
> Would it make sense to call it `modernize-use-ctad` and possibly leave the door open for more use cases in follow-up patches?

+1 on `modernize-use-ctad`, good to leave space for more patches.

2025-09-23 01:27 UTC, localspook commented
@hjanuschka, do you plan on finishing this check? If not, I'm happy to pick it up and finish it; I think it's a good check and I want to see it land.

2025-10-02 18:54 UTC, hjanuschka commented
@localspook damn, i missed that one, kind of like forgot about it!
not sure, if i can get back into the zone (brain reset 😂), to finish it, i am fine if you take it and land it!

2025-10-04 05:27 UTC, localspook commented
Alright, I'll take it on!

2026-02-18 09:26 UTC, hjanuschka commented
This has been landed on main as c741fffc1aa9. Thanks @localspook for picking it up and finishing it!

2026-02-18 09:26 UTC, closed without merging

2026-02-18 10:10 UTC, vbvictor commented
Did it actually land as https://github.com/llvm/llvm-project/commit/c741fffc1aa978e39946bb34efc455dc9333f993..?
It doesn't have PR linked and original issue is still open.
Also, it's not listed on https://clang.llvm.org/extra/clang-tidy/checks/list.html

2026-03-09 21:40 UTC, localspook commented
:thinking: I don't think anything's landed yet. I came up with a local prototype of the check (I used it to do #174109), but I kinda lost steam, because it needs a lot more polish before I can suggest making it a fully-fledged official check.