[libc++] Use [[clang::no_specializations]] to diagnose invalid user specializations
llvm/llvm-project pull request #118167
Opened 2024-11-30 11:09 UTC by philnik777

2025-01-08 16:07 UTC, ldionne requested changes
This seems like a nice improvement to me, but I have some comments.

2025-01-15 18:25 UTC, philnik777 commented on libcxx/include/__config
I'd rather not do that in this patch, since `allocator_traits` is much more likely to be specialized by users. I'd be fine with a follow-up patch though.

2025-01-16 15:35 UTC, ldionne requested changes

2025-01-16 15:35 UTC, ldionne commented on libcxx/include/__cxx03/__type_traits/add_cv.h
> +struct _LIBCPP_TEMPLATE_VIS _LIBCPP_DIAGNOSE_SPECIALIZATIONS add_cv {
```suggestion
struct _LIBCPP_TEMPLATE_VIS _LIBCPP_NO_SPECIALIZATIONS add_cv {
```

Applies in other places.

2025-01-20 14:15 UTC, ldionne approved these changes

2025-01-23 12:18 UTC, philnik777 commented
I'm pretty sure the CI failures are unrelated.

2025-01-23 12:18 UTC, merged