[SLP]Improved reduction cost/codegen
llvm/llvm-project pull request #118293
Opened 2024-12-02 13:37 UTC by alexey-bataev

SLP vectorizer is able to combine several reductions from the list of
(potentially) reduced values with the different opcodes/values kind.
Currently, these reductions are handled independently of each other. But
instead the compiler can combine them into wide vector operations and
then perform only single reduction.
E.g, if the SLP vectorizer emits currently something like:
```
%r1 = reduce.add(<4 x i32> %v1)
%r2 = reduce.add(<4 x i32> %v2)
%r = add i32 %r1, %r2
```

it can be emitted as:
```
%v = add <4 x i32> %v1, %v2
%r = reduce.add(<4 x i32> %v)
```

It allows to improve the performance in some cases.

AVX512, -O3+LTO
Metric: size..text

Program                                                                                           size..text
                                                                                                  results     results0    diff
                      test-suite :: SingleSource/Benchmarks/Shootout-C++/Shootout-C++-matrix.test     4553.00     4615.00  1.4%
                                 test-suite :: SingleSource/Benchmarks/Adobe-C++/loop_unroll.test   412708.00   416820.00  1.0%
        test-suite :: SingleSource/UnitTests/Vector/AVX512BWVL/Vector-AVX512BWVL-mask_set_bw.test    12901.00    12981.00  0.6%
                        test-suite :: MultiSource/Benchmarks/FreeBench/fourinarow/fourinarow.test    22717.00    22813.00  0.4%
                             test-suite :: MultiSource/Benchmarks/mediabench/gsm/toast/toast.test    39722.00    39850.00  0.3%
                      test-suite :: MultiSource/Benchmarks/MiBench/telecomm-gsm/telecomm-gsm.test    39725.00    39853.00  0.3%
test-suite :: SingleSource/Regression/C/gcc-c-torture/execute/GCC-C-execute-builtin-bitops-1.test    15918.00    15967.00  0.3%
                                       test-suite :: External/SPEC/CFP2006/433.milc/433.milc.test   155491.00   155587.00  0.1%
                                     test-suite :: MicroBenchmarks/ImageProcessing/Blur/blur.test   227894.00   227942.00  0.0%
                                    test-suite :: MultiSource/Benchmarks/7zip/7zip-benchmark.test  1062188.00  1062364.00  0.0%
                                test-suite :: External/SPEC/CINT2006/464.h264ref/464.h264ref.test   793672.00   793720.00  0.0%
                              test-suite :: External/SPEC/CINT2017rate/525.x264_r/525.x264_r.test   657371.00   657403.00  0.0%
                             test-suite :: External/SPEC/CINT2017speed/625.x264_s/625.x264_s.test   657371.00   657403.00  0.0%
                   test-suite :: External/SPEC/CINT2017speed/600.perlbench_s/600.perlbench_s.test  2074917.00  2074933.00  0.0%
                    test-suite :: External/SPEC/CINT2017rate/500.perlbench_r/500.perlbench_r.test  2074917.00  2074933.00  0.0%
                                     test-suite :: MultiSource/Applications/JM/lencod/lencod.test   855219.00   855203.00 -0.0%

Benchmarks/Shootout-C++ - same transformed reduction
Adobe-C++/loop_unroll - same transformed reductions, new vector code
AVX512BWVL/Vector-AVX512BWVL-mask_set_bw - same transformed reductions
FreeBench/fourinarow - same transformed reductions
MiBench/telecomm-gsm - same transformed reductions
execute/GCC-C-execute-builtin-bitops-1 - same transformed reductions
CFP2006/433.milc - better vector code, several x i64 reductions + trunc
to i32 gets trunced to x i32 reductions
ImageProcessing/Blur - same transformed reductions
Benchmarks/7zip - same transformed reductions, extra 4 x vectorization
CINT2006/464.h264ref - same transformed reductions
CINT2017rate/525.x264_r
CINT2017speed/625.x264_s - same transformed reductions
CINT2017speed/600.perlbench_s
CINT2017rate/500.perlbench_r - transformed same reduction
JM/lencod - extra 4 x vectorization

RISC-V, SiFive-p670, -O3+LTO

Metric: size..text

Program                                                                                           size..text
                                                                                                  results    results0   diff
test-suite :: SingleSource/Regression/C/gcc-c-torture/execute/GCC-C-execute-builtin-bitops-1.test    8990.00    9514.00   5.8%
                                test-suite :: External/SPEC/CINT2006/464.h264ref/464.h264ref.test  588504.00  588488.00  -0.0%
                    test-suite :: MultiSource/Benchmarks/MiBench/consumer-lame/consumer-lame.test  147464.00  147440.00  -0.0%
              test-suite :: MultiSource/Benchmarks/MiBench/automotive-susan/automotive-susan.test   21496.00   21492.00  -0.0%
                                     test-suite :: MicroBenchmarks/ImageProcessing/Blur/blur.test  165420.00  165372.00  -0.0%
                                    test-suite :: MultiSource/Benchmarks/7zip/7zip-benchmark.test  843928.00  843648.00  -0.0%
                                    test-suite :: External/SPEC/CINT2006/458.sjeng/458.sjeng.test  100712.00  100672.00  -0.0%
                      test-suite :: MultiSource/Benchmarks/MiBench/telecomm-gsm/telecomm-gsm.test   24384.00   24336.00  -0.2%
                             test-suite :: MultiSource/Benchmarks/mediabench/gsm/toast/toast.test   24380.00   24332.00  -0.2%
             test-suite :: SingleSource/UnitTests/Vectorizer/VPlanNativePath/outer-loop-vect.test   10348.00   10316.00  -0.3%
                                 test-suite :: SingleSource/Benchmarks/Adobe-C++/loop_unroll.test  221304.00  220480.00  -0.4%
                      test-suite :: SingleSource/Benchmarks/Shootout-C++/Shootout-C++-matrix.test    3750.00    3736.00  -0.4%
                            test-suite :: SingleSource/Regression/C/Regression-C-DuffsDevice.test     678.00     370.00 -45.4%

execute/GCC-C-execute-builtin-bitops-1 - extra 4 x reductions, same
transformed reductions
CINT2006/464.h264ref - extra 4 x reductions, same transformed reductions
MiBench/consumer-lame - 2 4 x i1 merged to 8 x i1 reductions (bitcast + ctpop)
MiBench/automotive-susan - same transformed reductions
ImageProcessing/Blur - same transformed reductions
Benchmarks/7zip - same transformed reductions
CINT2006/458.sjeng - 2 4 x i1 merged to 8 x i1 reductions (bitcast + ctpop)
MiBench/telecomm-gsm - same transformed reductions
Benchmarks/mediabench - same transformed reductions
Vectorizer/VPlanNativePath - same transformed reductions
Adobe-C++/loop_unroll - extra 4 x reductions, same transformed reductions
Benchmarks/Shootout-C++ - extra 4 x reductions, same transformed reductions
Regression/C/Regression-C-DuffsDevice - same transformed reductions

2024-12-02 18:30 UTC, preames requested changes
There are no tests changed by this review.

2025-01-06 14:38 UTC, alexey-bataev commented
Ping!

2025-01-06 16:21 UTC, RKSimon reviewed
Please can you add a patch description and not just the perf changes?

2025-01-06 16:21 UTC, RKSimon commented on llvm/include/llvm/Analysis/TargetTransformInfo.h
> +  /// false otherwise.
Improve the description as it doesn't seem to match the implementation in BasicTTIImpl.h

2025-01-06 16:22 UTC, RKSimon commented on llvm/test/Transforms/SLPVectorizer/X86/external-used-across-reductions.ll
> +; CHECK-NEXT:    [[OP_RDX16:%.*]] = call i64 @llvm.vector.reduce.add.v2i64(<2 x i64> [[RDX_OP21]])
why is all this better? it just feels like the reduction has been split to legal types

2025-01-06 16:32 UTC, alexey-bataev commented on llvm/test/Transforms/SLPVectorizer/X86/external-used-across-reductions.ll
> +; CHECK-NEXT:    [[OP_RDX16:%.*]] = call i64 @llvm.vector.reduce.add.v2i64(<2 x i64> [[RDX_OP21]])
Instead of 2 reductions it now emits only 1

2025-01-08 15:09 UTC, RKSimon commented on llvm/test/Transforms/SLPVectorizer/X86/external-used-across-reductions.ll
> +; CHECK-NEXT:    [[OP_RDX16:%.*]] = call i64 @llvm.vector.reduce.add.v2i64(<2 x i64> [[RDX_OP21]])
but isn't all the additional extract / add precisely the same as the expansion of the original v8i64 reduction?

2025-01-08 15:27 UTC, alexey-bataev commented on llvm/test/Transforms/SLPVectorizer/X86/external-used-across-reductions.ll
> +; CHECK-NEXT:    [[OP_RDX16:%.*]] = call i64 @llvm.vector.reduce.add.v2i64(<2 x i64> [[RDX_OP21]])
Not exactly. Instead of final 
```
%red1 = reduce_add1 %v1
%red2 = reduce_add2 %v2
%res = add i64 %red1, %red2
```
it will emit
```
%v = add<2 x i32> %v1, %v2
%res = reduce_add %v
```
which is slightly better for X86 and significantly better for other targets

2025-01-17 07:22 UTC, hiraditya commented
need to rebase

2025-01-21 13:18 UTC, RKSimon commented on llvm/test/Transforms/SLPVectorizer/X86/external-used-across-reductions.ll
> +; CHECK-NEXT:    [[OP_RDX16:%.*]] = call i64 @llvm.vector.reduce.add.v2i64(<2 x i64> [[RDX_OP21]])
I'm still of the opinion that this would be better:

```
; CHECK-NEXT: [[ADD:%.*]] = add <8 x i64> [[TMP5]], [[TMP7]]
; CHECK-NEXT: [[OP_RDX16:%.*]] = call i64 @llvm.vector.reduce.add.v8i64(<8 x i64> [[ADD]])
```

2025-01-21 16:05 UTC, alexey-bataev commented on llvm/test/Transforms/SLPVectorizer/X86/external-used-across-reductions.ll
> +; CHECK-NEXT:    [[OP_RDX16:%.*]] = call i64 @llvm.vector.reduce.add.v2i64(<2 x i64> [[RDX_OP21]])
Compared the codegen and the throughput, they are almost the same. The modified version produces 3 less instructions and has slightly less rthroughput: 14.3 for the modified version and 15.0 for the original version for the generic cpu.

2025-01-22 21:55 UTC, hiraditya commented on llvm/include/llvm/CodeGen/BasicTTIImpl.h
> +      if (unsigned VF = LT.second.getVectorNumElements();
Not sure if we need an initializer here when VF isn't used in the conditional? Moving this call inside would improve readability and avoid a call?

2025-01-24 00:01 UTC, alinas commented
Could you rebase this on ToT?
I tried to patch this in and resolve conflicts and I'm seeing a crash on https://github.com/google/highway/blob/master/hwy/contrib/sort/vqsort_i16a.cc. I might have missed something during conflict resolution, any chance you could test that?

2025-01-24 00:39 UTC, alexey-bataev commented
Can you attach preprocessed source code and shell script?

2025-01-24 15:42 UTC, alexey-bataev commented
> Could you rebase this on ToT? I tried to patch this in and resolve conflicts and I'm seeing a crash on https://github.com/google/highway/blob/master/hwy/contrib/sort/vqsort_i16a.cc. I might have missed something during conflict resolution, any chance you could test that?

Tried several different flags, cannot reproduce a crash, need a reproducer

2025-01-24 21:35 UTC, alinas commented
Attached reproducer; crashes with `opt --passes=slp-vectorizer reducedslpv.ll `
[reducedslpv.ll.txt](https://github.com/user-attachments/files/18542103/reducedslpv.ll.txt)

Hits this assert:
```
llvm-project/llvm/lib/Transforms/Vectorize/SLPVectorizer.cpp:821: Instruction *(anonymous namespace)::InstructionsState::getMainOp() const: Assertion `valid() && "InstructionsState is invalid."' failed.
```

2025-01-27 14:23 UTC, alexey-bataev commented
Ping!

2025-01-27 16:01 UTC, RKSimon commented on llvm/include/llvm/CodeGen/BasicTTIImpl.h
> +        Tp && LT.second.isFixedLengthVector()) {
Why are you checking for Tp null here?

2025-01-27 16:36 UTC, preames commented on llvm/include/llvm/Analysis/TargetTransformInfo.h
> +  /// \return true if \p Tp represents a type, fully occupying whole register,
Can you clarify that "fully occupied" means "up to known minimum length", not "dynamically at runtime"?  (i.e. w/zvl256b a runtime VLEN=512 case might only occupy half the register.)

2025-01-27 16:36 UTC, preames commented on llvm/test/Transforms/SLPVectorizer/AArch64/InstructionsState-is-invalid-0.ll
> +; CHECK-NEXT:    [[RDX_OP:%.*]] = or <4 x i1> [[TMP5]], [[TMP10]]
This test change looks pretty disconnected from full register types.  Is there possibly a change to how reduction trees are expanded which could be extracted as it's own change here?

2025-01-27 16:36 UTC, preames commented on llvm/test/Transforms/SLPVectorizer/RISCV/horizontal-list.ll
> +; CHECK-NEXT:    [[TMP5:%.*]] = call fast <4 x float> @llvm.vector.extract.v4f32.v16f32(<16 x float> [[TMP0]], i64 0)
Er, this does not look an improvement.  Assuming zvl128b (default), these extracts are going to translate to vslidedown.vx at m4 and m2 respectively.  3x m4 + 2 x m2 + m1 reduce is going to be more expensive than 1x each m4, m2 and m1 reductions plus scalar adds.  The new lowering here only looks profitable if we know the exact VLEN is 128, not if the lower bound on VLEN is 128.

There's an alternate lowering here which would likely work better.  If you sum the smaller vectors into the larger vectors (via extract, add, and insert), I think we'll be smart enough to turn that into a VL predicated vfadd.vv at the smaller lmul (check!).  If so, then that would be 1x m1 vfadd.vv + 1x m2 vfadd.vv + 1 m4 reduce.

2025-01-27 18:11 UTC, alexey-bataev commented on llvm/include/llvm/CodeGen/BasicTTIImpl.h
> +        Tp && LT.second.isFixedLengthVector()) {
Misprint, must be `FTp`

2025-01-27 18:13 UTC, alexey-bataev commented on llvm/include/llvm/Analysis/TargetTransformInfo.h
> +  /// \return true if \p Tp represents a type, fully occupying whole register,
Added `(up to known minimum length)`. Is this enough?

2025-01-27 18:15 UTC, alexey-bataev commented on llvm/test/Transforms/SLPVectorizer/AArch64/InstructionsState-is-invalid-0.ll
> +; CHECK-NEXT:    [[RDX_OP:%.*]] = or <4 x i1> [[TMP5]], [[TMP10]]
It is related to the second part - if the type is represented as `<n x i1>` or all types are the same. In this case, it just combines all reductions into a single reduction.

2025-01-27 19:43 UTC, alexey-bataev commented on llvm/test/Transforms/SLPVectorizer/RISCV/horizontal-list.ll
> +; CHECK-NEXT:    [[TMP5:%.*]] = call fast <4 x float> @llvm.vector.extract.v4f32.v16f32(<16 x float> [[TMP0]], i64 0)
That's a good idea, will give it a try

2025-02-03 19:18 UTC, hiraditya commented
@preames do you have any unaddressed comments?

2025-02-11 22:35 UTC, alexey-bataev commented
Ping!

2025-02-11 23:52 UTC, hiraditya commented
LGTM

2025-02-11 23:52 UTC, hiraditya approved these changes

2025-02-13 15:36 UTC, merged

2025-02-14 10:22 UTC, mstorsjo commented
This change miscompiles one file in ffmpeg, for x86 and x86_64.

To reproduce, clone https://github.com/ffmpeg/ffmpeg, compile and run tests like this:
```
$ git clone https://github.com/ffmpeg/ffmpeg
$ mkdir ffmpeg-build
$ cd ffmpeg-build
$ ../ffmpeg/configure --cc=clang --samples=$(pwd)/../ffmpeg-samples
$ make fate-rsync
$ make -j$(nproc) fate-msnsiren
```

The miscompiled object file is `libavcodec/siren.o`.

2025-02-14 11:16 UTC, mikaelholmen commented
I'm seeing a crash with this patch when compiling for my out-of-tree target:
```
opt: ../lib/IR/Instructions.cpp:1748: llvm::ShuffleVectorInst::ShuffleVectorInst(Value *, Value *, ArrayRef<int>, const Twine &, InsertPosition): Assertion `isValidOperands(V1, V2, Mask) && "Invalid shuffle vector instruction operands!"' failed.
[...]
 #9 0x0000555848bf2503 (anonymous namespace)::HorizontalReduction::tryToReduce(llvm::slpvectorizer::BoUpSLP&, llvm::DataLayout const&, llvm::TargetTransformInfo*, llvm::TargetLibraryInfo const&, llvm::AssumptionCache*) SLPVectorizer.cpp:0:0
#10 0x0000555848bc1089 llvm::SLPVectorizerPass::vectorizeHorReduction(llvm::PHINode*, llvm::Instruction*, llvm::BasicBlock*, llvm::slpvectorizer::BoUpSLP&, llvm::SmallVectorImpl<llvm::WeakTrackingVH>&) (build-all/bin/opt+0x5faa089)
#11 0x0000555848bc14f2 llvm::SLPVectorizerPass::vectorizeRootInstruction(llvm::PHINode*, llvm::Instruction*, llvm::BasicBlock*, llvm::slpvectorizer::BoUpSLP&) (build-all/bin/opt+0x5faa4f2)
#12 0x0000555848bb601c llvm::SLPVectorizerPass::vectorizeChainsInBlock(llvm::BasicBlock*, llvm::slpvectorizer::BoUpSLP&) (build-all/bin/opt+0x5f9f01c)
#13 0x0000555848bb2fd4 llvm::SLPVectorizerPass::runImpl(llvm::Function&, llvm::ScalarEvolution*, llvm::TargetTransformInfo*, llvm::TargetLibraryInfo*, llvm::AAResults*, llvm::LoopInfo*, llvm::DominatorTree*, llvm::AssumptionCache*, llvm::DemandedBits*, llvm::OptimizationRemarkEmitter*) (build-all/bin/opt+0x5f9bfd4)
#14 0x0000555848bb2557 llvm::SLPVectorizerPass::run(llvm::Function&, llvm::AnalysisManager<llvm::Function>&) (build-all/bin/opt+0x5f9b557)
```
I'll see if I can manage to reproduce for some in-tree target too.

2025-02-14 11:53 UTC, alexey-bataev commented
> I'm seeing a crash with this patch when compiling for my out-of-tree target:
> 
> ```
> opt: ../lib/IR/Instructions.cpp:1748: llvm::ShuffleVectorInst::ShuffleVectorInst(Value *, Value *, ArrayRef<int>, const Twine &, InsertPosition): Assertion `isValidOperands(V1, V2, Mask) && "Invalid shuffle vector instruction operands!"' failed.
> [...]
>  #9 0x0000555848bf2503 (anonymous namespace)::HorizontalReduction::tryToReduce(llvm::slpvectorizer::BoUpSLP&, llvm::DataLayout const&, llvm::TargetTransformInfo*, llvm::TargetLibraryInfo const&, llvm::AssumptionCache*) SLPVectorizer.cpp:0:0
> #10 0x0000555848bc1089 llvm::SLPVectorizerPass::vectorizeHorReduction(llvm::PHINode*, llvm::Instruction*, llvm::BasicBlock*, llvm::slpvectorizer::BoUpSLP&, llvm::SmallVectorImpl<llvm::WeakTrackingVH>&) (build-all/bin/opt+0x5faa089)
> #11 0x0000555848bc14f2 llvm::SLPVectorizerPass::vectorizeRootInstruction(llvm::PHINode*, llvm::Instruction*, llvm::BasicBlock*, llvm::slpvectorizer::BoUpSLP&) (build-all/bin/opt+0x5faa4f2)
> #12 0x0000555848bb601c llvm::SLPVectorizerPass::vectorizeChainsInBlock(llvm::BasicBlock*, llvm::slpvectorizer::BoUpSLP&) (build-all/bin/opt+0x5f9f01c)
> #13 0x0000555848bb2fd4 llvm::SLPVectorizerPass::runImpl(llvm::Function&, llvm::ScalarEvolution*, llvm::TargetTransformInfo*, llvm::TargetLibraryInfo*, llvm::AAResults*, llvm::LoopInfo*, llvm::DominatorTree*, llvm::AssumptionCache*, llvm::DemandedBits*, llvm::OptimizationRemarkEmitter*) (build-all/bin/opt+0x5f9bfd4)
> #14 0x0000555848bb2557 llvm::SLPVectorizerPass::run(llvm::Function&, llvm::AnalysisManager<llvm::Function>&) (build-all/bin/opt+0x5f9b557)
> ```
> 
> I'll see if I can manage to reproduce for some in-tree target too.

I'm going to revert the patch, please try to prepare the reproducer

2025-02-14 13:47 UTC, alexey-bataev commented
> This change miscompiles one file in ffmpeg, for x86 and x86_64.
> 
> To reproduce, clone https://github.com/ffmpeg/ffmpeg, compile and run tests like this:
> 
> ```
> $ git clone https://github.com/ffmpeg/ffmpeg
> $ mkdir ffmpeg-build
> $ cd ffmpeg-build
> $ ../ffmpeg/configure --cc=clang --samples=$(pwd)/../ffmpeg-samples
> $ make fate-rsync
> $ make -j$(nproc) fate-msnsiren
> ```
> 
> The miscompiled object file is `libavcodec/siren.o`.

Fixed

2025-02-14 14:16 UTC, luporl commented
This patch broke 2 bots:
- https://lab.llvm.org/buildbot/#/builders/4/builds/5019
- https://lab.llvm.org/buildbot/#/builders/143/builds/5429

clang crashes compiling `test-suite/MultiSource/Benchmarks/Prolangs-C/gnugo/endgame.c`:
```
clang-21: /home/leandro.lupori/llvm/llvm/lib/IR/Instructions.cpp:2112: static bool llvm::ShuffleVectorInst::isInsertSubvectorMask(ArrayRef<int>, int, int &, int &): Assertion `!Src0Elts.isZero() && !Src1Elts.isZero() && "2-source shuffle not found"' failed.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: /home/leandro.lupori/stage1/bin/clang-21 -cc1 -triple aarch64-unknown-linux-gnu -emit-obj -disable-free -clear-ast-before-backend -main-file-name endgame.c -mrelocation-model pic -pic-level 2 -pic-is-pie -mframe-pointer=non-leaf -fmath-errno -ffp-contract=on -fno-rounding-math -mconstructor-aliases -funwind-tables=2 -enable-tlsdesc -target-cpu neoverse-512tvb -target-feature +v8.4a -target-feature +aes -target-feature +bf16 -target-feature +ccdp -target-feature +ccidx -target-feature +ccpp -target-feature +complxnum -target-feature +crc -target-feature +dotprod -target-feature +fp-armv8 -target-feature +fp16fml -target-feature +fullfp16 -target-feature +i8mm -target-feature +jsconv -target-feature +lse -target-feature +neon -target-feature +pauth -target-feature +perfmon -target-feature +rand -target-feature +ras -target-feature +rcpc -target-feature +rdm -target-feature +sha2 -target-feature +sha3 -target-feature +sm4 -target-feature +spe -target-feature +ssbs -target-feature +sve -target-abi aapcs -mvscale-max=2 -mvscale-min=2 -debugger-tuning=gdb -fdebug-compilation-dir=/home/tcwg-buildbot/worker/clang-aarch64-sve-vls/test/sandbox/build/MultiSource/Benchmarks/Prolangs-C/gnugo -fcoverage-compilation-dir=/home/tcwg-buildbot/worker/clang-aarch64-sve-vls/test/sandbox/build/MultiSource/Benchmarks/Prolangs-C/gnugo -sys-header-deps -D NDEBUG -O3 -ferror-limit 19 -fno-signed-char -fgnuc-version=4.2.1 -fskip-odr-check-in-gmf -vectorize-loops -vectorize-slp -mllvm -treat-scalable-fixed-error-as-warning=false -target-feature +outline-atomics -target-feature -fmv -faddrsig -D__GCC_HAVE_DWARF2_CFI_ASM=1 -x c endgame-c4c5c8.c
1.	<eof> parser at end of file
2.	Optimizer
3.	Running pass "function<eager-inv>(float2int,lower-constant-intrinsics,chr,loop(loop-rotate<header-duplication;no-prepare-for-lto>,loop-deletion),loop-distribute,inject-tli-mappings,loop-vectorize<no-interleave-forced-only;no-vectorize-forced-only;>,infer-alignment,loop-load-elim,instcombine<max-iterations=1;no-verify-fixpoint>,simplifycfg<bonus-inst-threshold=1;forward-switch-cond;switch-range-to-icmp;switch-to-lookup;no-keep-loops;hoist-common-insts;no-hoist-loads-stores-with-cond-faulting;sink-common-insts;speculate-blocks;simplify-cond-branch;no-speculate-unpredictables>,slp-vectorizer,vector-combine,instcombine<max-iterations=1;no-verify-fixpoint>,loop-unroll<O3>,transform-warning,sroa<preserve-cfg>,infer-alignment,instcombine<max-iterations=1;no-verify-fixpoint>,loop-mssa(licm<allowspeculation>),alignment-from-assumptions,loop-sink,instsimplify,div-rem-pairs,tailcallelim,simplifycfg<bonus-inst-threshold=1;no-forward-switch-cond;switch-range-to-icmp;no-switch-to-lookup;keep-loops;no-hoist-common-insts;hoist-loads-stores-with-cond-faulting;no-sink-common-insts;speculate-blocks;simplify-cond-branch;speculate-unpredictables>)" on module "endgame-c4c5c8.c"
4.	Running pass "vector-combine" on function "endgame"
 #0 0x0000b6bdf3972c40 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/home/leandro.lupori/stage1/bin/clang-21+0x8152c40)
 #1 0x0000b6bdf3970b8c llvm::sys::RunSignalHandlers() (/home/leandro.lupori/stage1/bin/clang-21+0x8150b8c)
 #2 0x0000b6bdf39732cc SignalHandler(int, siginfo_t*, void*) Signals.cpp:0:0
 #3 0x0000e69b40ae48f8 (linux-vdso.so.1+0x8f8)
 #4 0x0000e69b404cf1f0 __pthread_kill_implementation ./nptl/./nptl/pthread_kill.c:44:76
 #5 0x0000e69b4048a67c gsignal ./signal/../sysdeps/posix/raise.c:27:6
 #6 0x0000e69b40477130 abort ./stdlib/./stdlib/abort.c:81:7
 #7 0x0000e69b40483fd4 __assert_fail_base ./assert/./assert/assert.c:91:7
 #8 0x0000e69b4048404c (/lib/aarch64-linux-gnu/libc.so.6+0x3404c)
 #9 0x0000b6bdf3333278 llvm::ShuffleVectorInst::isInsertSubvectorMask(llvm::ArrayRef<int>, int, int&, int&) (/home/leandro.lupori/stage1/bin/clang-21+0x7b13278)
#10 0x0000b6bdf12c5b0c llvm::TargetTransformInfoImplCRTPBase<llvm::AArch64TTIImpl>::getInstructionCost(llvm::User const*, llvm::ArrayRef<llvm::Value const*>, llvm::TargetTransformInfo::TargetCostKind) AArch64TargetMachine.cpp:0:0
#11 0x0000b6bdf2bff820 llvm::TargetTransformInfo::getInstructionCost(llvm::User const*, llvm::ArrayRef<llvm::Value const*>, llvm::TargetTransformInfo::TargetCostKind) const (/home/leandro.lupori/stage1/bin/clang-21+0x73df820)
#12 0x0000b6bdf29c67d0 llvm::TargetTransformInfo::getInstructionCost(llvm::User const*, llvm::TargetTransformInfo::TargetCostKind) const CodeMetrics.cpp:0:0
#13 0x0000b6bdf527f8d4 (anonymous namespace)::VectorCombine::run()::$_0::operator()(llvm::Instruction&) const VectorCombine.cpp:0:0
#14 0x0000b6bdf5277e14 llvm::VectorCombinePass::run(llvm::Function&, llvm::AnalysisManager<llvm::Function>&) (/home/leandro.lupori/stage1/bin/clang-21+0x9a57e14)
...
```

The full stacktrace is available in https://lab.llvm.org/buildbot/#/builders/143/builds/5429/steps/13/logs/stdio (search for `::PrintStackTrace`)

The reproducer is attached.

[repro.zip](https://github.com/user-attachments/files/18800363/repro.zip)

2025-02-14 14:33 UTC, alexey-bataev commented
> This patch broke 2 bots:
> 
> * https://lab.llvm.org/buildbot/#/builders/4/builds/5019
> * https://lab.llvm.org/buildbot/#/builders/143/builds/5429
> 
> clang crashes compiling `test-suite/MultiSource/Benchmarks/Prolangs-C/gnugo/endgame.c`:
> 
> ```
> clang-21: /home/leandro.lupori/llvm/llvm/lib/IR/Instructions.cpp:2112: static bool llvm::ShuffleVectorInst::isInsertSubvectorMask(ArrayRef<int>, int, int &, int &): Assertion `!Src0Elts.isZero() && !Src1Elts.isZero() && "2-source shuffle not found"' failed.
> PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
> Stack dump:
> 0.	Program arguments: /home/leandro.lupori/stage1/bin/clang-21 -cc1 -triple aarch64-unknown-linux-gnu -emit-obj -disable-free -clear-ast-before-backend -main-file-name endgame.c -mrelocation-model pic -pic-level 2 -pic-is-pie -mframe-pointer=non-leaf -fmath-errno -ffp-contract=on -fno-rounding-math -mconstructor-aliases -funwind-tables=2 -enable-tlsdesc -target-cpu neoverse-512tvb -target-feature +v8.4a -target-feature +aes -target-feature +bf16 -target-feature +ccdp -target-feature +ccidx -target-feature +ccpp -target-feature +complxnum -target-feature +crc -target-feature +dotprod -target-feature +fp-armv8 -target-feature +fp16fml -target-feature +fullfp16 -target-feature +i8mm -target-feature +jsconv -target-feature +lse -target-feature +neon -target-feature +pauth -target-feature +perfmon -target-feature +rand -target-feature +ras -target-feature +rcpc -target-feature +rdm -target-feature +sha2 -target-feature +sha3 -target-feature +sm4 -target-feature +spe -target-feature +ssbs -target-feature +sve -target-abi aapcs -mvscale-max=2 -mvscale-min=2 -debugger-tuning=gdb -fdebug-compilation-dir=/home/tcwg-buildbot/worker/clang-aarch64-sve-vls/test/sandbox/build/MultiSource/Benchmarks/Prolangs-C/gnugo -fcoverage-compilation-dir=/home/tcwg-buildbot/worker/clang-aarch64-sve-vls/test/sandbox/build/MultiSource/Benchmarks/Prolangs-C/gnugo -sys-header-deps -D NDEBUG -O3 -ferror-limit 19 -fno-signed-char -fgnuc-version=4.2.1 -fskip-odr-check-in-gmf -vectorize-loops -vectorize-slp -mllvm -treat-scalable-fixed-error-as-warning=false -target-feature +outline-atomics -target-feature -fmv -faddrsig -D__GCC_HAVE_DWARF2_CFI_ASM=1 -x c endgame-c4c5c8.c
> 1.	<eof> parser at end of file
> 2.	Optimizer
> 3.	Running pass "function<eager-inv>(float2int,lower-constant-intrinsics,chr,loop(loop-rotate<header-duplication;no-prepare-for-lto>,loop-deletion),loop-distribute,inject-tli-mappings,loop-vectorize<no-interleave-forced-only;no-vectorize-forced-only;>,infer-alignment,loop-load-elim,instcombine<max-iterations=1;no-verify-fixpoint>,simplifycfg<bonus-inst-threshold=1;forward-switch-cond;switch-range-to-icmp;switch-to-lookup;no-keep-loops;hoist-common-insts;no-hoist-loads-stores-with-cond-faulting;sink-common-insts;speculate-blocks;simplify-cond-branch;no-speculate-unpredictables>,slp-vectorizer,vector-combine,instcombine<max-iterations=1;no-verify-fixpoint>,loop-unroll<O3>,transform-warning,sroa<preserve-cfg>,infer-alignment,instcombine<max-iterations=1;no-verify-fixpoint>,loop-mssa(licm<allowspeculation>),alignment-from-assumptions,loop-sink,instsimplify,div-rem-pairs,tailcallelim,simplifycfg<bonus-inst-threshold=1;no-forward-switch-cond;switch-range-to-icmp;no-switch-to-lookup;keep-loops;no-hoist-common-insts;hoist-loads-stores-with-cond-faulting;no-sink-common-insts;speculate-blocks;simplify-cond-branch;speculate-unpredictables>)" on module "endgame-c4c5c8.c"
> 4.	Running pass "vector-combine" on function "endgame"
>  #0 0x0000b6bdf3972c40 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/home/leandro.lupori/stage1/bin/clang-21+0x8152c40)
>  #1 0x0000b6bdf3970b8c llvm::sys::RunSignalHandlers() (/home/leandro.lupori/stage1/bin/clang-21+0x8150b8c)
>  #2 0x0000b6bdf39732cc SignalHandler(int, siginfo_t*, void*) Signals.cpp:0:0
>  #3 0x0000e69b40ae48f8 (linux-vdso.so.1+0x8f8)
>  #4 0x0000e69b404cf1f0 __pthread_kill_implementation ./nptl/./nptl/pthread_kill.c:44:76
>  #5 0x0000e69b4048a67c gsignal ./signal/../sysdeps/posix/raise.c:27:6
>  #6 0x0000e69b40477130 abort ./stdlib/./stdlib/abort.c:81:7
>  #7 0x0000e69b40483fd4 __assert_fail_base ./assert/./assert/assert.c:91:7
>  #8 0x0000e69b4048404c (/lib/aarch64-linux-gnu/libc.so.6+0x3404c)
>  #9 0x0000b6bdf3333278 llvm::ShuffleVectorInst::isInsertSubvectorMask(llvm::ArrayRef<int>, int, int&, int&) (/home/leandro.lupori/stage1/bin/clang-21+0x7b13278)
> #10 0x0000b6bdf12c5b0c llvm::TargetTransformInfoImplCRTPBase<llvm::AArch64TTIImpl>::getInstructionCost(llvm::User const*, llvm::ArrayRef<llvm::Value const*>, llvm::TargetTransformInfo::TargetCostKind) AArch64TargetMachine.cpp:0:0
> #11 0x0000b6bdf2bff820 llvm::TargetTransformInfo::getInstructionCost(llvm::User const*, llvm::ArrayRef<llvm::Value const*>, llvm::TargetTransformInfo::TargetCostKind) const (/home/leandro.lupori/stage1/bin/clang-21+0x73df820)
> #12 0x0000b6bdf29c67d0 llvm::TargetTransformInfo::getInstructionCost(llvm::User const*, llvm::TargetTransformInfo::TargetCostKind) const CodeMetrics.cpp:0:0
> #13 0x0000b6bdf527f8d4 (anonymous namespace)::VectorCombine::run()::$_0::operator()(llvm::Instruction&) const VectorCombine.cpp:0:0
> #14 0x0000b6bdf5277e14 llvm::VectorCombinePass::run(llvm::Function&, llvm::AnalysisManager<llvm::Function>&) (/home/leandro.lupori/stage1/bin/clang-21+0x9a57e14)
> ...
> ```
> 
> The full stacktrace is available in https://lab.llvm.org/buildbot/#/builders/143/builds/5429/steps/13/logs/stdio (search for `::PrintStackTrace`)
> 
> The reproducer is attached.
> 
> [repro.zip](https://github.com/user-attachments/files/18800363/repro.zip)

Should be fixed already with the new version of the patch

2025-02-14 16:09 UTC, luporl commented
> Should be fixed already with the new version of the patch

Thanks for the fix.

2025-02-15 12:37 UTC, mikaelholmen commented
> I'm seeing a crash with this patch when compiling for my out-of-tree target:
> 
> ```
> opt: ../lib/IR/Instructions.cpp:1748: llvm::ShuffleVectorInst::ShuffleVectorInst(Value *, Value *, ArrayRef<int>, const Twine &, InsertPosition): Assertion `isValidOperands(V1, V2, Mask) && "Invalid shuffle vector instruction operands!"' failed.
> [...]
>  #9 0x0000555848bf2503 (anonymous namespace)::HorizontalReduction::tryToReduce(llvm::slpvectorizer::BoUpSLP&, llvm::DataLayout const&, llvm::TargetTransformInfo*, llvm::TargetLibraryInfo const&, llvm::AssumptionCache*) SLPVectorizer.cpp:0:0
> #10 0x0000555848bc1089 llvm::SLPVectorizerPass::vectorizeHorReduction(llvm::PHINode*, llvm::Instruction*, llvm::BasicBlock*, llvm::slpvectorizer::BoUpSLP&, llvm::SmallVectorImpl<llvm::WeakTrackingVH>&) (build-all/bin/opt+0x5faa089)
> #11 0x0000555848bc14f2 llvm::SLPVectorizerPass::vectorizeRootInstruction(llvm::PHINode*, llvm::Instruction*, llvm::BasicBlock*, llvm::slpvectorizer::BoUpSLP&) (build-all/bin/opt+0x5faa4f2)
> #12 0x0000555848bb601c llvm::SLPVectorizerPass::vectorizeChainsInBlock(llvm::BasicBlock*, llvm::slpvectorizer::BoUpSLP&) (build-all/bin/opt+0x5f9f01c)
> #13 0x0000555848bb2fd4 llvm::SLPVectorizerPass::runImpl(llvm::Function&, llvm::ScalarEvolution*, llvm::TargetTransformInfo*, llvm::TargetLibraryInfo*, llvm::AAResults*, llvm::LoopInfo*, llvm::DominatorTree*, llvm::AssumptionCache*, llvm::DemandedBits*, llvm::OptimizationRemarkEmitter*) (build-all/bin/opt+0x5f9bfd4)
> #14 0x0000555848bb2557 llvm::SLPVectorizerPass::run(llvm::Function&, llvm::AnalysisManager<llvm::Function>&) (build-all/bin/opt+0x5f9b557)
> ```
> 
> I'll see if I can manage to reproduce for some in-tree target too.

The problem I saw disappeared with 3b18d47ecbaba.
Probably the same bug as reported in https://github.com/llvm/llvm-project/issues/127220.