[mlir-tblgen] Relax builder ambiguity check
llvm/llvm-project pull request #118310
Opened 2024-12-02 15:45 UTC by RoboTux

The mlir-tblgen tool prevents the parameter of the build() constructor
for the first default-valued attribute of an operation from having a
default value to avoid ambiguity with the corresponding build()
constructor taking unwrapped value. However it does so even when earlier
wrapped unwrappable attribute would lift the ambiguity. This commit
relax the logic accordingly, which allows to remove a manual constructor
in Arith dialect.

2024-12-02 17:27 UTC, kuhar commented on mlir/tools/mlir-tblgen/OpDefinitionsGen.cpp
> +  for (int i = 0; i < op.getNumArgs(); ++i) {
nit: don't recompute the end after every iteration: https://llvm.org/docs/CodingStandards.html#don-t-evaluate-end-every-time-through-a-loop

You could probably also turn this into a range for loop

2024-12-02 17:51 UTC, krzysz00 commented
Seems reasonable conceptually aside the nits above

2024-12-05 23:36 UTC, jpienaar approved these changes
This looks good, thanks. I'll do a quick check to see if I see any other failures on larger test set later today.

2024-12-05 23:45 UTC, jpienaar commented
I see some failures MHLO side ( out-of-line definition of 'build' does not match any declaration ), so seems like this is not just avoiding ambiguity but may also skipping generating some build methods that was generated before.

2024-12-06 00:04 UTC, jpienaar commented
Yes, so this results in generating different number of build methods than before in the header, but not the bodies. You can check in build of

tensorflow/compiler/xla/mlir_hlo/_objs/mlir_hlo/hlo_ops

2024-12-06 00:05 UTC, jpienaar requested changes
Ensure generating same number of build methods in header as body.

2024-12-06 04:47 UTC, jpienaar approved these changes
OK, I had time to look more. The confusing thing was the user provided builder was not preferred but that's not new here. Post that only 1 change I noticed, seems a different build method being called which resulted in `DefaultValuedOptionalAttr` not being set. But that doesn't seem to be a difference introduce here.

2024-12-06 09:26 UTC, merged