Update CustomOp's dialect input and output names
llvm/llvm-project pull request #118408
Opened 2024-12-02 22:36 UTC by Jerry-Ge

Update input name from input to input_list
Update output name from outputs to output_list

To match specification: https://www.mlplatform.org/tosa/tosa_spec.html#_custom

2024-12-03 11:20 UTC, CoTinker requested changes
#

2024-12-03 11:20 UTC, CoTinker commented on mlir/include/mlir/Dialect/Tosa/IR/TosaOps.td
> `inputs` is the set of tensor inputs to the custom operator.
> `outputs is the list of tensors returned by the operator.

Please update the description, too.

2024-12-03 21:36 UTC, Jerry-Ge commented on mlir/include/mlir/Dialect/Tosa/IR/TosaOps.td
thanks for noting this and the review! updated the description.

2024-12-04 01:11 UTC, CoTinker approved these changes
LGTM, thanks.

2024-12-04 09:49 UTC, merged