VNCoercion: Safely handle targets where pointers are larger than the largest legal integers.
llvm/llvm-project pull request #118584
Opened 2024-12-04 03:10 UTC by resistor

This does not impact any in-tree targets, but does impact CHERI targets.

2024-12-04 10:48 UTC, nikic requested changes
Please add a test. This should be possible by just specifying an appropriate data layout, even outside the CHERI fork.

However, I don't really understand why this condition is necessary at all. How is the largest legal integer type relevant in this context?

2024-12-04 11:12 UTC, resistor commented
Moving this back to draft for now.

The origins of this code in the CHERI downstream of LLVM is somewhat mysterious (it first appears in an old merge commit, without a test, and then has gotten heavily refactored in a later merge with upstream that extracted code from GVN.cpp to VNCoercion.cpp).

I believe the original intent was to stop GVN from trying to use non-integral pointer types for VN coercion. Looking at the current code `canCoerceMustAliasedValueToLoad`, I suspect this is no longer needed, and might in fact already be bit-rotted.

2024-12-04 23:04 UTC, closed without merging

2024-12-10 00:36 UTC, resistor commented
Tagging @jrtc27 and @arichardson for awareness on CHERI-derived PRs

2024-12-10 01:12 UTC, jrtc27 commented
We know we have issues with GVN not honouring pointer provenance in ways that matter once that provenance is captured in hardware, whether via CHERI or some other provenance-tracking scheme that doesn't expose the provenance as bits in the address you can mess with. There's no sense upstreaming random historical cruft that we know is not sufficient, and may not be necessary.

2024-12-10 01:13 UTC, resistor commented
> We know we have issues with GVN not honouring pointer provenance in ways that matter once that provenance is captured in hardware, whether via CHERI or some other provenance-tracking scheme that doesn't expose the provenance as bits in the address you can mess with. There's no sense upstreaming random historical cruft that we know is not sufficient, and may not be necessary.

Agreed, I've abandoned this PR.