[MLIR][SCFToEmitC] Convert types while converting from SCF to EmitC
llvm/llvm-project pull request #118940
Opened 2024-12-06 08:16 UTC by josel-amd

Switch from rewrite patterns to conversion patterns. This allows to perform type conversions together with other parts of the IR. For example, this allows to convert from index to emit.size_t types.

2024-12-10 08:37 UTC, simon-camp requested changes
Sorry for the delayed respone. LGTM besides the one include that is not needed I think.

2024-12-10 15:02 UTC, josel-amd commented on mlir/lib/Conversion/SCFToEmitC/SCFToEmitC.cpp
> +#include "mlir/Transforms/OneToNTypeConversion.h"
Fixed. Thanks!

2024-12-10 15:03 UTC, simon-camp approved these changes

2025-01-02 09:41 UTC, josel-amd commented
Ping

2025-01-02 09:43 UTC, marbre commented
> Ping

As Simon already approved, should I merge on your behalf or what do you ping for? :)

2025-01-02 09:46 UTC, josel-amd commented
> > Ping
> 
> As Simon already approved, should I merge on your behalf or what do you ping for? :)

I was not sure if you still wanted to have an extra look. Feel free to merge it on my behalf. Thanks!

2025-01-02 10:13 UTC, marbre commented
> I was not sure if you still wanted to have an extra look. Feel free to merge it on my behalf. Thanks!

I can take a quick look but it is probably fine if Simon approved.

When squashing, the GH UI says:
> This commit will be authored by 166385423+josel-amd@users.noreply.github.com

However, https://llvm.org/docs/DeveloperPolicy.html#making-and-submitting-a-patch says

> The LLVM project uses email to communicate to contributors outside of the GitHub platform about their past contributions. Primarily, our buildbot infrastructure uses emails to contact contributors about build and test failures. Therefore, the LLVM community requires contributors to have a public email address associated with their GitHub commits, so please ensure that “Keep my email addresses private” is disabled in your [account settings](https://github.com/settings/emails).

Please adjust you settings so that I am allowed to merge.

2025-01-02 10:36 UTC, merged

2025-01-02 11:02 UTC, josel-amd commented
Change reverted due to conflict. Testing a fix, will push soon.