Add support for CHERI "purecap" as an environment in target triples.
llvm/llvm-project pull request #118927
Opened 2024-12-06 05:49 UTC by resistor

For context, CHERI architectures can support two modes:
* Hybrid mode, in which capabilities co-exist alongside normal pointers.
* Pure capability mode, in which all pointers are replaced with capabilities.

Hybrid mode does not require any indication in the target triple, as it
is treated the same as any other extension to the parent ISA. Pure cap mode,
however, is a different ABI from the native ABI of the parent architecture.

2024-12-09 15:23 UTC, jrtc27 commented
Yeah this should not be part of the environment, it should be part of the CPU if anything.

2024-12-09 15:24 UTC, jrtc27 commented
Environment is way too overloaded already and the cross product of multiple things, this would jus make it even worse.

2024-12-09 15:29 UTC, jrtc27 commented
Also, you can’t just go upstreaming random bits of CHERI support. You need to talk to us first about it as CHERI LLVM maintainers, and you need to talk to the upstream LLVM community first. Triples aren’t exactly useful without something behind them…

2024-12-09 15:30 UTC, jrtc27 requested changes
.

2024-12-10 02:16 UTC, resistor commented
> While I i initially added this for MIPS I'm not 100% convinced it's the best approach to use an environment here as we might want the existing ones too. I'm starting to think using an architecture like riscv64c might be cleaner an less error prone. @jrtc27 what do you think?

FWIW, we're planning to go a similar direction to what you're suggesting for CHERIoT, i.e. defining a `riscv32cheriot` sub-arch. There's a reasonable amount of precedent for similar sub-arch constructs in ARM and MIPS.

2024-12-10 02:16 UTC, resistor commented
Abandoning this at it seems this is not the direction we want.

2024-12-10 02:16 UTC, closed without merging