[libc++] Rename `__` prefix to `__libcpp_` for locale related functions
llvm/llvm-project pull request #119241
Opened 2024-12-09 18:17 UTC by zibi2

This PR is necessary to resolve name collisions between locale functions defined within libc++ and macros used in z/OS system   header, `locale.h`. Those macros cannot be changed since they are visible and out in the field for many releases. 

In addition, the zos wrapper locale.h header is created to remove conflict between `__locale` namespace and guard macro used by z/OS system header. This change is temporary until system header is altered to do the same.

The PR is to address build issues on z/OS caused by PR [114596](https://github.com/llvm/llvm-project/pull/114596).
The following is a sample of errors:
```
.../include/c++/v1/__locale_dir/locale_base_api.h:181:54: error: too many arguments provided to function-like macro invocation
  181 | inline _LIBCPP_HIDE_FROM_ABI int __islower(int __ch, __locale_t __loc) { return islower_l(__ch, __loc); }
      |                                                      ^
...util/usr/include/ctype.h:387:11: note: macro '__islower' defined here
  387 |   #define __islower(c) (_TYPCHK((c),__ISLOWER))
      |           ^
```

2024-12-09 18:25 UTC, ldionne requested changes
Instead, can't you `#undef` these macros? We're trying to move away from defining names with `__libcpp`.

2024-12-09 18:39 UTC, perry-ca commented
These macros can't be undef'ed as they are used to implement the functions like islower(int) by the headers like ctype.h.  Any name other than __X will work for these inline functions in libc++.

2025-01-28 16:02 UTC, zibi2 commented
Louis, are you still in position of not accepting the rename proposal in this PR? 

I was able to resolve the `__locale_t`  name collision with a wrapper, but unfortunately, as Sean pointed out, we cannot undefine other macros conflicting with the inline functions in `libc++`. If we cannot use the `__libcpp_`  prefix anymore, what is the recommended way of resolving name collisions? When the use of the `__libcpp_` prefix was discouraged, was there any alternative for resolving name collisions with the underlying system C library?

2025-01-28 21:31 UTC, ldionne commented
Which identifiers exactly are causing issues? I think we could tackle that by adding them to `__undef_macros` and to `_LIBCPP_PUSH_MACROS` and `_LIBCPP_POP_MACROS` instead. That's generally what we do to work around name collisions on individual platforms: it's more robust and doesn't require changing libc++'s source code due to name conflicts, which could be arbitrary (in principle, a platform could also be defining `__libcpp_strtof`, so the only bulletproof way of addressing this issue is push/pop).

2025-01-28 21:43 UTC, zibi2 commented
> ... the only bulletproof way of addressing this issue is push/pop

Thx, I will experiment with push/pop and handle only names we have in conflict.

2025-01-30 20:00 UTC, ldionne commented
Closing in the meantime, please reopen this PR or create a new one with the new approach whenever you're ready!

2025-01-30 20:00 UTC, closed without merging