[CodeGen][NewPM] Port RegAllocGreedy to NPM
llvm/llvm-project pull request #119540
Opened 2024-12-11 11:01 UTC by optimisan

2024-12-11 14:06 UTC, cdevadas reviewed
Do you have any real change in SplitKit.h as part of this PR?

2024-12-12 02:12 UTC, optimisan commented on llvm/include/llvm/CodeGen/SplitKit.h
> +  void removeBackCopies(SmallVectorImpl<VNInfo *> &Copies);
I moved these files to include, so they got picked up by clang-format. I'll add a new PR.

2024-12-23 07:49 UTC, arsenm commented on llvm/lib/CodeGen/RegAllocGreedy.cpp
> +  PA.preserve<MachineLoopAnalysis>();
These should be redundant with CFGAnalyses?

2025-01-01 07:00 UTC, optimisan commented on llvm/lib/CodeGen/RegAllocGreedy.cpp
> +  PA.preserve<MachineLoopAnalysis>();
Right.

2025-01-01 07:57 UTC, cdevadas commented on llvm/include/llvm/Passes/MachinePassRegistry.def
> +    "regallocgreedy", "RAGreedyPass",
What's the motivation for changing this passname? I would have preferred just greedy.

2025-01-01 09:01 UTC, optimisan commented on llvm/include/llvm/Passes/MachinePassRegistry.def
> +    "regallocgreedy", "RAGreedyPass",
Keeping it as greedy for now.

2025-01-23 09:30 UTC, optimisan commented on llvm/lib/CodeGen/RegAllocGreedy.cpp
> +  Impl.setAnalyses(Analyses);
Oh, I changed the evictionadvisor provider api so forgot to simplify this out.

2025-01-24 04:22 UTC, arsenm reviewed
Missing test

2025-01-24 04:22 UTC, arsenm commented on llvm/lib/CodeGen/RegAllocGreedy.cpp
> +  OS << "regallocgreedy<" << FilterName << '>';
```suggestion
  OS << "regalloc-greedy<" << FilterName << '>';
```

2025-01-24 04:22 UTC, arsenm commented on llvm/lib/CodeGen/RegAllocGreedy.cpp
> +void RAGreedy::setAnalyses(RequiredAnalyses &Analyses) {
Just do this directly in the constructor, there's no other user of setAnalyses

2025-02-12 05:42 UTC, optimisan commented
> Missing test

This PR was getting big, so I split out that to https://github.com/llvm/llvm-project/pull/120557 which inserts greedy in the codegen pipeline and adds -passes support.

2025-02-12 06:27 UTC, arsenm commented on llvm/lib/CodeGen/RegAllocGreedy.h
> +  struct RequiredAnalyses {
Can you sink this to the implementation file? At most you should need a forward declare in the header

2025-02-12 06:27 UTC, arsenm commented on llvm/lib/CodeGen/RegAllocGreedy.cpp
> +  Analyses.LIS = &MFAM.getResult<LiveIntervalsAnalysis>(MF);
Can you move all of these initializations to the RequiredAnalyses constructor(s)? We'd need one overload for each PM

2025-02-20 07:26 UTC, arsenm approved these changes

2025-02-20 08:03 UTC, optimisan commented on llvm/include/llvm/Passes/MachinePassRegistry.def
> +MACHINE_FUNCTION_ANALYSIS("regalloc-priority", RegAllocPriorityAdvisorAnalysis())
This isn't supposed to be here, will update this.
Graphite strangely isn't working for me, so I am rebasing PRs manually for now.

2025-02-20 08:04 UTC, optimisan commented on llvm/lib/CodeGen/RegAllocPriorityAdvisor.cpp
> +  initializeProvider(MF.getFunction().getContext());
It does. Alternative was to convert this to a module class that adds the extra proxy layer everytime.

2025-02-20 08:18 UTC, arsenm requested changes
Should still try to sink struct into implementation file

2025-02-25 10:16 UTC, arsenm approved these changes

2025-02-25 10:16 UTC, arsenm commented on llvm/lib/CodeGen/RegAllocGreedy.cpp
> +  RequiredAnalyses() {}
Probably don't need the default constructor
```suggestion
  RequiredAnalyses() = delete;
```

2025-02-26 05:35 UTC, arsenm approved these changes

2025-02-26 06:41 UTC, merged

2025-02-26 07:44 UTC, kazutakahirata commented
@optimisan I've landed cdfcce48d5c290a77ab868fb62c18f6ba16e58df to fix an unused variable warning from this PR.  Thanks!

2025-02-26 08:09 UTC, optimisan commented
Great, many thanks.