[libc++] Simplify vector<bool>::__construct_at_end implementation
llvm/llvm-project pull request #119632
Opened 2024-12-11 23:29 UTC by winner245

This PR proposes the removal of the unnecessary initialization in both overloads of `__construct_at_end` in `vector<bool>`, which serves as a helper function for various constructors, `assign`, and `reserve` methods of the class. The specific code segment in question is as follows:

```cpp
if (__old_size == 0 || ((__old_size - 1) / __bits_per_word) != ((this->__size_ - 1) / __bits_per_word)) {
  if (this->__size_ <= __bits_per_word)
    this->__begin_[0] = __storage_type(0);
  else
    this->__begin_[(this->__size_ - 1) / __bits_per_word] = __storage_type(0);
}
```

**Rationale for Removal**: 
The purpose of the above code is to initialize every bit in the last word to 0 when the new size crosses the boundary of the current last word. However, this initialization is unnecessary for the following reasons:

- ***Redundancy***: The initialization of the last word to zero is unnecessary, as it is immediately overwritten by the subsequent call to `std::fill_n`. Even without this initialization, the uninitialized bits in the range `[0, __size_)` will be correctly set by the `std::fill_n` call, ensuring that the bits of interest are properly initialized.

- ***Safety against out-of-bounds access***: Leaving the bits in the last word uninitialized does not introduce any risk, as they remain out of bounds for `vector<bool>`. The `std::fill_n` function itself operates within the valid range of the vector, so any uninitialized values in the last word will not affect the integrity of the operation.

The existing comprehensive tests for the constructors, `assign`, and `reserve` functions continue to pass successfully after the removal of the above code, thereby validating the changes in this PR.

2024-12-12 15:24 UTC, winner245 commented
You are right. I am just about to close.

2025-01-13 20:42 UTC, ldionne commented on libcxx/include/__vector/vector_bool.h
> +    // Ensure that the call to __construct_at_end(first, last, n) meets the precondition of n > 0
Previously, what would happen if `n == 0`? Is it possible to write a test that triggers that failure?

2025-01-13 20:42 UTC, ldionne commented on libcxx/include/__vector/vector_bool.h
>  vector<bool, _Allocator>::__construct_at_end(_InputIterator __first, _Sentinel __last, size_type __n) {
```suggestion
vector<bool, _Allocator>::__construct_at_end(_InputIterator __first, _Sentinel __last, size_type __n) {
  _LIBCPP_ASSERT_INTERNAL(size() > 0, "This function expects a non-empty vector<bool>");
```

To catch potential misuse.

2025-01-13 20:42 UTC, ldionne commented on libcxx/include/__vector/vector_bool.h
> +  this->__begin_[(this->__size_ - 1) / __bits_per_word] = __storage_type(0);
Aren't you overwriting elements just before `this->__size_` with `0` by doing this?

2025-01-13 23:01 UTC, winner245 commented on libcxx/include/__vector/vector_bool.h
> +  this->__begin_[(this->__size_ - 1) / __bits_per_word] = __storage_type(0);
Yes, this will overwrite the zero bits from the beginning of the last `__storage_type` word to the `(__size_ - 1)`-th bit. Pre-initializing the entire last word to 0 ensures that the unused trailing bits past the end of `vector<bool>` in the last word (i.e., bits from `__size`-th bit to the final bit of the last word) are all initialized to zeros. If those trailing bits are not initialized, we will encounter UB even when accessing the used bits in the last word. Although `vector<bool>` guarantees that we can only access the the initialized bits within the range `[0, __size_-1]`, we may still trigger UB if the accessed bits are from the last word with uninitialized trailing bits. This is because accessing any bit in `vector<bool>` involves accessing the entire word, followed by some bit-masking operations. However, with uninitialized trailing bits in the last word, accessing the last word triggers UB, which was captured by the MSan CI in my initial attempt. This is why initializing the last word is essential (Initially, I mistakenly thought we didn't need to initialize the last word to 0 since we would overwrite the front bits and we didn't use or touch the unused trailing bits. I realized my mistake until the UB was detected by the MSan CI failure.) 

There is also an equivalent implementation that avoids overwriting the used front bits and only assigns zeros to the unused trailing bits in the last word:

```cpp
std::__copy(__first, __last, end());
this->__size_ += __n;
if (end().__ctz_ != 0) // has uninitialized trailing bits in the last word
  std::fill_n(end(), __bits_per_word - end().__ctz_, 0);
```
This implementation might be more intuitive. However, this approach invokes an additional function `std::fill_n`, which might be slightly less efficient than my current implementation of just an assignment of one word.

2025-01-14 00:12 UTC, winner245 commented on libcxx/include/__vector/vector_bool.h
> +    // Ensure that the call to __construct_at_end(first, last, n) meets the precondition of n > 0
In the previous implementation, `n == 0` (i.e., the input parameter `__n` in `__construct_at_end(,,__n)` is 0) may lead to unnecessary initialization of the first word to 0 if the vector was empty before calling `__construct_at_end`, which may pose safety issues. 

https://github.com/llvm/llvm-project/blob/743c84bb9b79ed70d9bed926c2a173db3b30f587/libcxx/include/__vector/vector_bool.h#L539-L546

Given `__n == 0` and `size() == 0`, we have `__old_size == this->__size_ == __n == 0`, which means that the if conditions in Lines 541-542 are true. Thus, `this->__begin_[0] = __storage_type(0);` is executed, which initializes one word that currently dose not belong to the `vector`. In general, this could cause safety issues because it writes to some memory out of our control. Therefore, `__n > 0` is made a precondition for this function, and callers of this function must always check the condition before calling it.

Throughout the implementation of `vector<bool>`, every call to  `__construct_at_end(,,__n)` explicitly checks for the `__n > 0` precondition, except one call inside `reserve(__n)`, where the call to `__v.__construct_at_end(this->begin(), this->end(), this->size());` was not preceded by a precondition check for `this->size() > 0` (please note that the `__n` we have been talking about becomes `this->size()` within `reserve(__n)`, and `reserve(__n)`'s own `__n` denotes the requested capacity). However, we are lucky that not checking the precondition in `reserve(__n)` did not lead to a safety issue, as `reserve(__n)` will only do reallocation if the requested `__n` is greater than the current `capacity()`. This means that once `reserve` calls `__constrcut_at_end`, it must have reserved at least one word of memory. Thus, the unnecessary initialization of one word inside `__constrcut_at_end` actually writes to the memory currently reserved for future use by the vector. IMO, the reason we did not run into safety issues is only because we are lucky--`reserve()`'s own semantics is to reserve memory. If it were not `reserve`, omitting a precondition check before calling `__construc_at_end` would definitely leads to a safety issue. Thus, we should precede the call to `__construct_at_end` with the condition check `this->size() > 0` within `reserve`. 

However, I couldn't find a way to test it or trigger a failure because all existing calls (except the one in `reserve`) already have a precondition check, and the only call that omits a precondition check in `reserve` happens to be fine. Please let me know if you have some ideas on this. 

Besides testing it, I think you suggestion of adding a `_LIBCPP_ASSERT_INTERNAL` check inside `__construct_at_end` is definitely a great idea, as it makes the precondition more explicit.

2025-01-14 00:21 UTC, winner245 commented on libcxx/include/__vector/vector_bool.h
> +    // Ensure that the call to __construct_at_end(first, last, n) meets the precondition of n > 0
In my implementation of `__construct_at_end`, I explicitly calculate the index of the last word: 

```cpp
this->__begin_[(this->__size_ - 1) / __bits_per_word] = __storage_type(0);
```

This would be problematic if `this->__size_ == 0` (which is the case when the vector was empty and the precondition `__n == 0` is not satisfied). In this case, the index evaluation would go wrong and become `size_type(-1) / 64` (a huge number). So a safer way seems to be 

```cpp
if (this->__size_ > 0)
  this->__begin_[(this->__size_ - 1) / __bits_per_word] = __storage_type(0);
```
However, IMO I don't need this if condition here because it is guaranteed to be true as long as the precondition of `__n > 0` is satisfied.

2025-01-14 00:23 UTC, winner245 commented on libcxx/include/__vector/vector_bool.h
>  vector<bool, _Allocator>::__construct_at_end(_InputIterator __first, _Sentinel __last, size_type __n) {
This is great! I will add the `_LIBCPP_ASSERT_INTERNAL` check in both overloads of `__constrcut_at_end`.

2025-01-14 17:03 UTC, ldionne requested changes

2025-01-15 17:43 UTC, winner245 commented on libcxx/include/__vector/vector_bool.h
> +  this->__begin_[(this->__size_ - 1) / __bits_per_word] = __storage_type(0);
Great catch! Now I fully understand you from the code you provided. Your concern is indeed valid if user code is allowed to directly call `__construct_at_end`. In that case, overwriting the first few bits currently used in the last word would be problematic. This was overlooked in my refactor, as well as in the previous implementation, because `__construct_at_end` is only used by constructors, `__assign_with_size`, and `reserve`. When used inside constructors, we have an empty vector, so nothing got overwritten. For the usage in `__assign_with_size`, `__construct_at_end` is called after a `clear()` call, meaning we have an empty vector before the call. Moreover, since it's used for assignments, overwriting some cleared bits is not an issue. In `reserve`, `__v.__construct_at_end(this->begin(), this->end(), this->size())` is called on a newly created empty vector `__v`, so it's fine. 

So basically, all the existing usages of `__construct_at_end` implicitly requires that the vector is empty. After realizing this, I realized that the additional precondition you mentioned, that the vector must be empty before calling `__construct_at_end`, is valid. This precondition was previously ignored but hasn't led to issues because all existing calls satisfy it.

With this additional precondition you pointed out, we actually have two preconditions for this function `__construct_at_end(, , __n)`: 
- `_LIBCPP_ASSERT_INTERNAL(empty(), "this function requires an empty vector");`
- `_LIBCPP_ASSERT_VALID_INPUT_RANGE(__n > 0, "invalid range specified");`

Adding the above two checks in `__construct_at_end` is a great fix. 

I also have another implementation for `__construct_at_end` which seems to remove both preconditions: 

```cpp
void __construct_at_end(_InputIterator __first, _Sentinel __last, size_type __n) {
  std::__copy(__first, __last, end());
  this->__size_ += __n;
  if (end().__ctz_ != 0) // has uninitialized trailing bits in the last word
    std::fill_n(end(), __bits_per_word - end().__ctz_, 0);
}
```

This implementation only writes to the trailing bits in the last word, not overwriting the existing leading bits. Also, if `__n == 0` (i.e., `__first == __last`), this function does not do anything. 

What do you think about this approach?

2025-01-20 16:13 UTC, ldionne approved these changes
LGTM with your new proposed implementation.

2025-01-20 16:13 UTC, ldionne commented on libcxx/include/__vector/vector_bool.h
> +  this->__begin_[(this->__size_ - 1) / __bits_per_word] = __storage_type(0);
I like your new implementation best, I think. But we need to add a precondition check `_LIBCPP_ASSERT_INTERNAL(capacity() >= size() + __n)`.

2025-01-20 19:53 UTC, ldionne commented on libcxx/include/__vector/vector_bool.h
> +    // Ensure that the call to __construct_at_end(first, last, n) meets the precondition of n > 0
This precondition doesn't exist anymore, right? So we should be able to remove the comment, and maybe even the `if`?

2025-01-20 20:18 UTC, winner245 commented on libcxx/include/__vector/vector_bool.h
> +    // Ensure that the call to __construct_at_end(first, last, n) meets the precondition of n > 0
That's right! The comment doesn't apply any more and the if condition is unnecessary.

2025-01-29 16:46 UTC, ldionne approved these changes

2025-01-29 16:46 UTC, merged

2025-02-02 17:52 UTC, philnik777 commented on libcxx/include/__vector/vector_bool.h
> +    std::fill_n(end(), __bits_per_word - end().__ctz_, 0);
Why is this required?

2025-02-02 17:52 UTC, philnik777 commented on libcxx/include/__vector/vector_bool.h
>  vector<bool, _Allocator>::__construct_at_end(_InputIterator __first, _Sentinel __last, size_type __n) {
Is there a test for this function where `_InputIterator` isn't a `vector<bool>` iterator? e.g. `bool*`. I don't see how the elements are initialized which makes me think that we may read from uninitialized memory when the `__bit_iterator` optimization in `std::copy` doesn't kick in. I don't think this is a problem in reality, since we're setting the bits one-by-one, but could cause some sanitizer to complain.

2025-02-02 17:58 UTC, winner245 commented on libcxx/include/__vector/vector_bool.h
> +    std::fill_n(end(), __bits_per_word - end().__ctz_, 0);
This ensures that the unused leading bits in the last word are initialized, which serves the same purpose as the pre-initialization logic in the previous implementation: 

https://github.com/llvm/llvm-project/blob/743c84bb9b79ed70d9bed926c2a173db3b30f587/libcxx/include/__vector/vector_bool.h#L554-L561

Without this, we would have a Msan CI failure.

2025-02-02 18:13 UTC, winner245 commented on libcxx/include/__vector/vector_bool.h
>  vector<bool, _Allocator>::__construct_at_end(_InputIterator __first, _Sentinel __last, size_type __n) {
I understand your concern here. That's why I explicitly check if we have uninitialized bits, which could only exist in the last partial word. Previously, we pre-initialize the entire last word, whether it is a partial word or not. This patch implements it in a more compact form which initializes the bits to zero only when the last word is a partial word.

2025-02-02 18:36 UTC, philnik777 commented on libcxx/include/__vector/vector_bool.h
> +    std::fill_n(end(), __bits_per_word - end().__ctz_, 0);
But how is the previous `fill_n` not reading uninitialized elements? It has to load the bits of the last word after all.

2025-02-02 18:36 UTC, philnik777 commented on libcxx/include/__vector/vector_bool.h
>  vector<bool, _Allocator>::__construct_at_end(_InputIterator __first, _Sentinel __last, size_type __n) {
I think I have basically the same question here: How does the `__copy` avoid the uninitialized read?

2025-02-03 15:46 UTC, winner245 commented on libcxx/include/__vector/vector_bool.h
> +    std::fill_n(end(), __bits_per_word - end().__ctz_, 0);
In constant evaluation, we have no uninitialized bits at all because `__vallocate` guarantees that the allocated memory is default-constructed. In non-constant evaluation, we effectively only reads from bits within the bounds of `vector<bool>` since we utilize bit masks. So in this case, the purpose of the initialization is to make sanitizer tools happy. According to my test, sanitizers do not complain as long as the unused bits in the last word are initialized to 0 within `__construct_at_end`, regardless of whether this occurs before or after the initialization of other words. However, without the initialization of unused bits, subsequent read from `vector<bool>` would trigger a Msan CI failure.