[libc][docgen] regen docgen via cmake
llvm/llvm-project pull request #119628
Opened 2024-12-11 23:03 UTC by nickdesaulniers

2024-12-12 17:18 UTC, nickdesaulniers commented on libc/docs/CMakeLists.txt
> +      strings
I wonder why these are being highlighted? Are they keywords in CMake? Perhaps I should make this a `;` separated string?

2024-12-12 17:20 UTC, nickdesaulniers commented on libc/docs/CMakeLists.txt
> +                ${CMAKE_CURRENT_SOURCE_DIR}/headers/${stem}.rst)
So there's probably a better way to do this.  IIUC, it's going to run the command every time, which isn't necessary.  We should only need to re-run the command in the input file (`libc/utils/docgen/{stem}.json`) is modified.  Not sure yet how to express that in cmake...

2024-12-12 17:21 UTC, nickdesaulniers commented on libc/docs/CMakeLists.txt
> +      wctype
#119621 just landed. I should rebase and add arpa/inet and sys/mman.

2024-12-12 17:37 UTC, nickdesaulniers commented on libc/docs/CMakeLists.txt
> +                ${CMAKE_CURRENT_SOURCE_DIR}/headers/${stem}.rst)
Maybe the SOURCES argument?

2024-12-18 02:49 UTC, boomanaiden154 requested changes
For the most part, we can't have any build targets modify the source directory. If we want to have a build command rerun docgen automatically, it should be a separate target and not under `docs-libc-html`.

The better way to do this would be to do something similar to https://github.com/llvm/llvm-project/pull/113739. Convert everything in the `libc/docs` directory to templates and as part of `libc-docs-html`, run docgen writing all the outputs to a folder in the build directory that we then run sphinx over.

2024-12-19 20:51 UTC, nickdesaulniers commented
So it looks like clang itself copies its rst files into the build dir.  I can emulate the approach I think.

`copy-clang-rst-docs`

2024-12-19 21:13 UTC, nickdesaulniers commented
ok, I have that working.  One thing I think would be nice to add; I suspect there's a way to say that docgen depends on the yaml files. If those haven't changed, then docgen doesn't need to be rerun.  Looking at these docs https://cmake.org/cmake/help/latest/command/add_custom_target.html, I'm not sure if that's `DEPENDS` or `SOURCES`.

Looks like I need to rebase this pr...

2024-12-19 22:53 UTC, nickdesaulniers commented on libc/docs/CMakeLists.txt
> +                ${CMAKE_CURRENT_SOURCE_DIR}/headers/${stem}.rst)
Seems like NEITHER SOURCES or DEPENDS prevents rebuilds upon reinvocations of `ninja docs-libc-html`...oh well

2024-12-19 23:22 UTC, nickdesaulniers commented on libc/docs/CMakeLists.txt
> +                ${CMAKE_CURRENT_SOURCE_DIR}/headers/${stem}.rst)
`ninja docs-libc-html -d explain` prints useful info to debug that, but I don't plan to resolve that in this PR.  Nice to have; not required.

2024-12-20 17:47 UTC, boomanaiden154 approved these changes
LGTM with the latest approach.

2024-12-20 22:53 UTC, michaelrj-google approved these changes

2025-01-06 16:52 UTC, merged