[MLIR][GPU] Support bf16 and i1 gpu::shuffles to LLVMSPIRV conversion
llvm/llvm-project pull request #119675
Opened 2024-12-12 08:49 UTC by PietroGhg

This PR adds support to the `bf16` and `i1` data types when converting `gpu::shuffle` to the `LLVMSPV` dialect, by inserting `bitcast` to/from `i16` (for `bf16`) and extending/truncating to `i8` (for `i1`).

2025-01-02 12:01 UTC, victor-eds commented on mlir/lib/Conversion/GPUToLLVMSPV/GPUToLLVMSPV.cpp
> +    }
```suggestion
    result = bitcastOrTruncAfterShuffle(loc, result, rewriter);
```

2025-01-02 17:28 UTC, kuhar reviewed
Just some drive by nits

2025-01-02 17:28 UTC, kuhar commented on mlir/lib/Conversion/GPUToLLVMSPV/GPUToLLVMSPV.cpp
>      return llvm::formatv("_Z{0}{1}{2}", baseName.size(), baseName,
FYI, you don't need these indices, `"_Z{}{}{}"` should work too

2025-01-02 17:28 UTC, kuhar commented on mlir/lib/Conversion/GPUToLLVMSPV/GPUToLLVMSPV.cpp
> +        .Case<IntegerType>([&](auto intTy) -> Type {
nit: I don't see why these need to be generic over the argument type
```suggestion
        .Case<BFloat16Type>([&](Type) { return rewriter.getIntegerType(16); })
        .Case<IntegerType>([&](IntegerType intTy) -> Type {
```

2025-01-02 17:28 UTC, kuhar commented on mlir/lib/Conversion/GPUToLLVMSPV/GPUToLLVMSPV.cpp
> +        .Default([](auto) { return Type{}; });
```suggestion
        .Default([](Type) { return Type{}; });
```

2025-01-02 17:28 UTC, kuhar commented on mlir/lib/Conversion/GPUToLLVMSPV/GPUToLLVMSPV.cpp
> +        .Default([](auto) { return Type{}; });
Also below

2025-01-03 09:09 UTC, victor-eds commented on mlir/lib/Conversion/GPUToLLVMSPV/GPUToLLVMSPV.cpp
> +        .Case<IntegerType>([&](auto intTy) -> Type {
I am not sure that would compile.

```cpp
        .Case([&](BFloat16Type) { return rewriter.getIntegerType(16); })
        .Case([&](IntegerType intTy) -> Type {
```

Is nicer IMO tho

2025-01-06 17:12 UTC, FMarno commented on mlir/test/Conversion/GPUToLLVMSPV/gpu-to-llvm-spv.mlir
>    }
You have removed the reason for this module/function to exist. Maybe replace the `i1` value with another unsupported type like a large float.

2025-01-06 17:27 UTC, FMarno requested changes

2025-01-06 17:27 UTC, FMarno commented on mlir/lib/Conversion/GPUToLLVMSPV/GPUToLLVMSPV.cpp
> +  static bool needsBitCastOrExt(gpu::ShuffleOp op) {
unused

2025-01-07 16:04 UTC, FMarno approved these changes

2025-01-08 11:06 UTC, victor-eds reviewed
Just a couple NITs. LGTM!

2025-01-08 11:06 UTC, victor-eds commented on mlir/lib/Conversion/GPUToLLVMSPV/GPUToLLVMSPV.cpp
> +        .Default([&](auto) { return oldVal; });
```suggestion
    return TypeSwitch<Type, Value>(oldVal.getType())
        .Case([&](BFloat16Type) {
          return rewriter.create<LLVM::BitcastOp>(
              loc, rewriter.getI16Type(), oldVal);
        })
        .Case([&](IntegerType intTy) -> Value {
          if (intTy.getWidth() == 1)
            return rewriter.create<LLVM::ZExtOp>(
                loc, rewriter.getI8Type(), oldVal);
          return oldVal;
        })
        .Default(oldVal);
```

NITs. Not sure `.Default(oldVal);` works, but I think it should.

2025-01-08 11:06 UTC, victor-eds commented on mlir/lib/Conversion/GPUToLLVMSPV/GPUToLLVMSPV.cpp
> +        .Default([&](auto) { return oldVal; });
```suggestion
        .Default(oldVal);
```

Same as above. If it works, it works...

2025-01-08 13:40 UTC, PietroGhg commented on mlir/lib/Conversion/GPUToLLVMSPV/GPUToLLVMSPV.cpp
> +        .Default([&](auto) { return oldVal; });
Thanks, I applied your suggestions; `Default(oldVal)` should work because we either fall in a case where we need to bitcast/trunc/ext, or we don't and if we don't we want to use `oldVal`. If `oldVal` is of some unsupported type, we already have checks for it after getting the mangled shuffle builtin, so it looks fine to me

2025-01-08 13:41 UTC, victor-eds approved these changes

2025-01-08 16:09 UTC, kuhar approved these changes

2025-01-09 12:16 UTC, merged