[clang] Extend diagnose_if to accept more detailed warning information, take 2
llvm/llvm-project pull request #119712
Opened 2024-12-12 15:30 UTC by philnik777

This is take two of #70976. This iteration of the patch makes sure that custom
diagnostics without any warning group don't get promoted by `-Werror` or
`-Wfatal-errors`.

This implements parts of the extension proposed in https://discourse.llvm.org/t/exposing-the-diagnostic-engine-to-c/73092/7.

Specifically, this makes it possible to specify a diagnostic group in an optional third argument.

2024-12-12 15:32 UTC, philnik777 commented
@AaronBallman Your reproducer doesn't seem to work anymore in trunk (there's probably been another change?), so I couldn't test early diagnostics anymore. If you have another reproducer I'd be happy to add it.

2024-12-12 15:42 UTC, erichkeane reviewed
This ends up being shockingly invasive, and I'm pretty uncomfortable about that.  I realize I'm code owner of attributes here, but this touches so much of diagnostics that I don't feel comfortable being the primary reviewer, so I think we have to wait until January when Aaron comes back to get an answer here.

2025-01-13 15:44 UTC, nico commented
From the commit message, it sounds like this might introduce warnings that `-Werror` doesn't turn into warnings. Is that correct?

We found in chromium (and other large projects) that non-fatal warnings get ignored and over time just lead to a ton of warning spam in build output, which in turn leads to people tuning out warnings even more. We have the principle that diagnostics are either important, in which case they should be fatal and non-ignorable, or they aren't, in which case they should be silent.

https://www.linfo.org/rule_of_silence.html is along the same lines.

So it'd be nice if (assuming I read the PR description correctly) there was a way to force all warnings into errors.

(I think `#warning` currently also can't be mapped to errors, but that's luckily very rare in practice.)

2025-01-14 18:39 UTC, AaronBallman commented
> From the commit message, it sounds like this might introduce warnings that `-Werror` doesn't turn into warnings. Is that correct?

FWIW, that's already the case today (which we found out in the previous iteration of this): https://godbolt.org/z/nG4oWvv3s

I think the commit message is talking specifically about warnings which have no warning group whatsoever, which is something we've been slowly working to get rid of: https://github.com/llvm/llvm-project/blob/dcc141bc0bb471ba209c89aca4288dc5cd2ef8bc/clang/test/Misc/warning-flags.c#L19

2025-01-14 18:51 UTC, AaronBallman reviewed
The changes generally LGTM but I'd really love to hear from @kadircet as to whether this PR fully addresses the issues found before: https://github.com/llvm/llvm-project/pull/70976#discussion_r1775918960

2025-01-14 18:51 UTC, AaronBallman commented on clang-tools-extra/clangd/Diagnostics.cpp
> +      const StringRef Warning = [&] {
```suggestion
      StringRef Warning = [&] {
```

2025-01-14 18:51 UTC, AaronBallman commented on clang/include/clang/Basic/Diagnostic.h
> +  // [[deprecated("Use a CustomDiagDesc instead of a Level")]]
```suggestion
  // TODO: Deprecate this once all uses are removed from Clang.
  // [[deprecated("Use a CustomDiagDesc instead of a Level")]]
```
I kind of wonder if we should have `-Wno-error=deprecated` in our CMake scripts and then just enable these sort of deprecations. We're terrible about ever actually removing uses of deprecated APIs and I think it's because they don't cause enough pain for us.

2025-01-15 10:22 UTC, kadircet requested changes
> but I'd really love to hear from @kadircet as to whether this PR fully addresses the issues found before: https://github.com/llvm/llvm-project/pull/70976#discussion_r1775918960

I think it mostly does (left some comments in places that it might break).

it'd be nice to also document this new behavioral change in https://clang.llvm.org/docs/AttributeReference.html#diagnose-if.

--- 

TBH I find it somewhat confusing to have a severity in `diagnose_if` and an existing diagnostic group, which already has its own severity. It isn't obvious to me how the severity for such a diagnotic should be configured. Does the command line options take precedence, or the annotation in code? IME mostly the latter takes over in clang, but, IIUC, we're doing the opposite here. Since I was late the RFC, I am not pushing back on the change, but just wanted to share my thoughts. So feel free to ignore.

2025-01-15 10:22 UTC, kadircet commented on clang/include/clang/Basic/DiagnosticIDs.h
> +                   bool ShowInSystemMacro = false,
existing behavior says these actually default to `true`, https://github.com/llvm/llvm-project/blob/main/clang/lib/Basic/DiagnosticIDs.cpp#L585-587

2025-01-24 10:00 UTC, philnik777 reviewed
> TBH I find it somewhat confusing to have a severity in `diagnose_if` and an existing diagnostic group, which already has its own severity.

Diagnostic groups don't have severity. Individual diagnostics have severity. This just exposes the same semantics as the tablegen files. i.e. you specify a default and if that default is overridden by the command line or pragmas that severity is used instead. I'm not sure where the confusion is.

2025-01-27 12:21 UTC, kadircet approved these changes
thanks!

> This just exposes the same semantics as the tablegen files.

alright, i guess I was missing this perspective. that makes sense now, thanks for the explanation!

2025-01-27 12:21 UTC, kadircet commented on clang/lib/Basic/DiagnosticIDs.cpp
> +  // FIXME: Should -w be ignored for custom warnings without a group?
sorry you're right, i forgot that this code path wasn't executed for custom diags at all before this patch.

2025-01-28 07:41 UTC, merged

2025-01-28 10:52 UTC, nikic commented
It looks like one of the header changes here is expensive, adding 0.5% to the time to build clang. Per-file breakdown: https://llvm-compile-time-tracker.com/compare_clang.php?from=aab25f20f6c06bab7aac6fb83d54705ec4cdfadd&to=0865ecc5150b9a55ba1f9e30b6d463a66ac362a6&stat=instructions%3Au&sortBy=interestingness

Possible the DiagnosticCategories.h include in DiagnosticIDs.h? Or maybe the additional code in the DiagnosticIDs.h header?

Is it possible to implement this feature in a way that doesn't impact build times?

2025-01-28 11:27 UTC, philnik777 commented
> It looks like one of the header changes here is expensive, adding 0.5% to the time to build clang. Per-file breakdown: https://llvm-compile-time-tracker.com/compare_clang.php?from=aab25f20f6c06bab7aac6fb83d54705ec4cdfadd&to=0865ecc5150b9a55ba1f9e30b6d463a66ac362a6&stat=instructions%3Au&sortBy=interestingness
> 
> Possibly the DiagnosticCategories.h include in DiagnosticIDs.h? Or maybe the additional code in the DiagnosticIDs.h header?
> 
> Is it possible to implement this feature in a way that doesn't impact build times?

I guess it's be possible to move the `CustomDiagDesc` into a separate header to avoid the `DiagnosticCategories.h` dependency in `DiagnosticIDs.h`. @AaronBallman any thoughts?

2025-04-09 01:25 UTC, shafik commented on clang/lib/Basic/DiagnosticIDs.cpp
> +    forEachSubGroupImpl(&OptionTable[*SubGroups], std::move(func));
@philnik777 a static analysis tool recently flagged this `std::move` b/c we are using after move on the next iteration of this loop on the line above.

Now as far as I can tell this should only technically be UB but I also don't see that this will give us any performance gains here, so I would be inclined to remove it unless I am missing something.

CC @AaronBallman

2025-04-22 16:30 UTC, AaronBallman commented on clang/lib/Basic/DiagnosticIDs.cpp
> +    forEachSubGroupImpl(&OptionTable[*SubGroups], std::move(func));
Yeah, I think i favor removing it; it's a bad idea to call it, move it, then loop around to call it again.