Add check for SYS_gettid support
llvm/llvm-project pull request #119742
Opened 2024-12-12 18:51 UTC by apeskov

To improve compatibility with old glibc version which lack `syscall(SYS_gettid)` will use `pthread_self()` as a fallback.

2024-12-12 20:02 UTC, apeskov commented
@brad0 @devnexen 
Could you please take a look on this change?

2024-12-12 20:57 UTC, devnexen approved these changes

2024-12-13 08:32 UTC, brad0 commented on llvm/lib/Support/Unix/Threading.inc
> +#elif defined(__linux__) && defined(SYS_gettid)
It would be better to change SYS_gettid to __NR_gettid.

2024-12-13 08:33 UTC, brad0 requested changes
It would be better to change SYS_gettid to __NR_gettid.

I posted a PR here.

https://github.com/llvm/llvm-project/pull/120007

2024-12-16 11:20 UTC, apeskov commented
Ok, `__NR_gettid` will suite me as well. Thanks!

Your PR already passed some checks so I will not update this one.

2024-12-18 21:19 UTC, closed without merging