[libc++][bug] Fix compilation error in vector<bool> due to integral promotion
llvm/llvm-project pull request #119801
Opened 2024-12-13 02:37 UTC by winner245

This PR addresses a compilation error in `vector<bool>` that arises from integral promotion when using custom allocators with smaller integral types, such as `std::uint16_t`. It also optimizes similar code in `std::basic_string` to prevent potential issues related to integral promotions.

The following [code snippet](https://godbolt.org/z/3qGvoxsE1) reproduces the bug in `vector<bool>`:

```cpp
#include <exception>
#include <iostream>
#include <limits>
#include <memory>
#include <vector>

template <typename T, typename SIZE_TYPE = std::size_t, typename DIFF_TYPE = std::ptrdiff_t>
class CustomSizedAllocator {
  template <typename U, typename Sz, typename Diff>
  friend class CustomSizedAllocator;

public:
  using value_type                  = T;
  using size_type                   = SIZE_TYPE;
  using difference_type             = DIFF_TYPE;
  using propagate_on_container_swap = std::true_type;

  explicit CustomSizedAllocator(int i = 0) : data_(i) {}

  template <typename U, typename Sz, typename Diff>
  constexpr CustomSizedAllocator(const CustomSizedAllocator<U, Sz, Diff>& a) noexcept : data_(a.data_) {}

  constexpr T* allocate(size_type n) {
    if (n > max_size())
      throw std::bad_array_new_length();
    return std::allocator<T>().allocate(n);
  }

  constexpr void deallocate(T* p, size_type n) noexcept { std::allocator<T>().deallocate(p, n); }

  constexpr size_type max_size() const noexcept { return std::numeric_limits<size_type>::max() / sizeof(value_type); }

  int get() { return data_; }

private:
  int data_;

  constexpr friend bool operator==(const CustomSizedAllocator& a, const CustomSizedAllocator& b) {
    return a.data_ == b.data_;
  }
  constexpr friend bool operator!=(const CustomSizedAllocator& a, const CustomSizedAllocator& b) {
    return a.data_ != b.data_;
  }
};

int main() {
  using Alloc = CustomSizedAllocator<bool, std::uint16_t, std::int16_t>;
  std::vector<bool, Alloc> c{Alloc{1}};
  c.resize(10);

  return 0;
}
```

This code fails to compile in libc++, while it compiles successfully in other standard library implementations. The underlying issue is found in the following line of code within `vector<bool>`:

```cpp
return std::max(2 * __cap, __align_it(__new_size));
```

where the first operand's result type is promoted to int, while the second operand retains the `size_type` type, which is `std::uint16_t` in this case. This mismatch in argument types for `std::max<_Tp>` leads to the failure of template type argument deduction.

The solution is straightforward: explicitly specify the template type for `std::max` to ensure consistent types for both operands.

2025-01-09 12:06 UTC, frederick-vs-ja reviewed
I think we can add some simple test cases.

2025-01-09 15:51 UTC, winner245 commented
It appears that my added tests for `size_allocator<T, SIZE_TYPE, DIFF_TYPE>` have triggered a new bug in all the `__bit_iterator` algorithms, including `std::{copy, copy_n, copy_backward, fill, fill_n, find, count}` and their `ranges` algorithm equivalents. The bug is essentially caused by an integral promotion of unsigned integral types (`std::uint8_t`, `std::uint16_t`) to signed `int`, followed by a left shift of the signed negative values, which is UB before C++20. Additionally, there are also some undesired integral promotions of small unsigned integral types to `int`, followed by right-shifts, which are implementation-defined before C++20. Therefore, we need to fix this new bug in these algorithms as well.

2025-01-14 17:17 UTC, ldionne requested changes
Nice catch! I have some comments.

Requesting changes since IIUC other fixes need to go in before we can merge this.

2025-01-14 17:17 UTC, ldionne commented on libcxx/test/std/containers/sequences/vector.bool/sized_allocator.pass.cpp
> +template <typename T, typename SIZE_TYPE = std::size_t, typename DIFF_TYPE = std::ptrdiff_t>
```suggestion
template <typename T, typename Size = std::size_t, typename Difference = std::ptrdiff_t>
```

All caps template parameters are unusual in the codebase.

2025-01-15 18:10 UTC, winner245 commented on libcxx/test/std/containers/sequences/vector.bool/sized_allocator.pass.cpp
> +template <typename T, typename SIZE_TYPE = std::size_t, typename DIFF_TYPE = std::ptrdiff_t>
Yeah, fixing the UB or ambiguous calls in my other PRs is a prerequisite for this one. Given that all these PRs and various tests utilize the `sized_allocator` class, I've elevated it to a support header file for the tests.

2025-03-26 16:12 UTC, ldionne approved these changes
LGTM with minor comments!

2025-04-02 15:14 UTC, ldionne approved these changes

2025-04-02 15:14 UTC, merged