[TargetLibraryInfo] Add libmvec support for risc-v
llvm/llvm-project pull request #119844
Opened 2024-12-13 09:28 UTC by zengdage

1. Rename LIBMVEC_X86 into LIBMVEC to support libmvec (glibc vector match library) in risc-v.
2. Add RVVM1/2/4/8 in VFISAKind to distingusih the LMUL value, so we can take full advantage of  risc-v vector extension.
3. Declare some RVV vector math functions in VecFuncs.def.

In VecFuncs.def, I add the LI_DEFINE_VECFUNC of LIBMVEC_RVV as follow:

```
    TLI_DEFINE_VECFUNC("sin", "_ZGV1Nxv_sin", SCALABLE(1), "_ZGVr1Nxv")
    TLI_DEFINE_VECFUNC("sin", "_ZGV2Nxv_sin", SCALABLE(2), "_ZGVr2Nxv")
    TLI_DEFINE_VECFUNC("llvm.exp.f32", "_ZGV1Nxv_expf", SCALABLE(2), "_ZGVr1Nxv")
    TLI_DEFINE_VECFUNC("llvm.exp.f32", "_ZGV2Nxv_expf", SCALABLE(4), "_ZGVr2Nxv")
```

The `VEC` of TLI_DEFINE_VECFUNC (e.g., `_ZGV2Nxv_sin`), its name mangling rules defined in https://github.com/riscv-non-isa/riscv-elf-psabi-doc/pull/455 . Now it's  still under review.

The` VF` (e.g., ` SCALABLE(2)`) should be `vscale x (LMUL * 64 / sizeof(Type)`. For example, the type of the parameter of sin is double, so for `_ZGV2Nxv_sin`, its VF is `vscale x 2`.

In the `VABI_PREFIX`  (e.g., `_ZGVr1Nxv`), `r` means RISC-V vector extension, `1` is LMUL value.
```
    _ZGVr1Nxv  --> RISC-V Vector Extension with LMUL=1
    _ZGVr2Nxv  --> RISC-V Vector Extension with LMUL=2
    _ZGVr4Nxv  --> RISC-V Vector Extension with LMUL=4
    _ZGVr8Nxv  --> RISC-V Vector Extension with LMUL=8

```

2024-12-13 09:47 UTC, zengdage commented
@mga-sc Hi, can you help to review the pr? I add RVVM1/2/4/8 in VFISAKind to support multiple LMUL value, maybe it can take full advantage of rvv register group. Your pr (https://github.com/llvm/llvm-project/pull/114014) looks like just support LMUL=2.

2024-12-20 08:12 UTC, mga-sc requested changes
Finally, libmvec is still not ported to RISC-V (today check glibc ToT with `--enable-mathvec`). I think we should wait for this and also wait for commit to [riscv-elf-psabi-doc](https://github.com/riscv-non-isa/riscv-elf-psabi-doc/pull/455). Probably, implementation will differ from the proposals.

2024-12-20 08:12 UTC, mga-sc commented on llvm/include/llvm/IR/VFABIDemangler.h
> +  RVVM8,        // RISC-V Vector Extension LMUL=8
Are you sure we need to enable all of them (now enabled only one for each RISC-V and AArch64)?

2024-12-20 08:12 UTC, mga-sc commented on llvm/lib/Transforms/Utils/InjectTLIMappings.cpp
> -    for (ElementCount VF = ElementCount::getFixed(2);
Leave a comment about this change. It is unclear why this change is needed and whether it affects other vector libraries.

2026-04-23 11:39 UTC, closed without merging