[libc++] Slightly simplify max_size and add new tests for vector
llvm/llvm-project pull request #119990
Opened 2024-12-14 23:44 UTC by winner245

This PR slightly simplifies the implementation of `vector<bool>::max_size` and adds extensive tests for the `max_size()` function for both vector<bool> and std::vector. The main purposes of the new tests include:

- Verify correctness of `max_size()` under various `size_type` and `difference_type` definitions: check that `max_size()` works properly with allocators that have custom `size_type` and `difference_type`. This is particularly useful for `vector<bool>`, as different `size_type` lead to different `__storage_type` of different word lengths, resulting in varying `max_size()` values for `vector<bool>`. Additionally, different `difference_type` also sets different upper limit of `max_size()` for both `vector<bool>` and `std::vector`. These tests were previously missing.

- Eliminate incorrect implementations: Special tests are added to identify and reject incorrect implementations of `vector<bool>::max_size` that unconditionally return `std::min<size_type>(__nmax, __internal_cap_to_external(__amax))`. This can cause overflow in the `__internal_cap_to_external()` call and lead to incorrect results. The new tests ensure that such incorrect implementations are identified.

2025-01-29 17:39 UTC, ldionne requested changes
This basically LGTM, but I'd like to see this again with the updated tests before merging. Thanks a lot for the fix!

2025-01-29 17:39 UTC, ldionne commented on libcxx/test/std/containers/sequences/vector.bool/max_size.pass.cpp
> +  using storage_type        = typename Vector::__storage_type;
This alias only exists in libc++, and our test suite must be portable. I suspect this means you will need to significantly weaken the tests for non-libc++ implementations, and that's okay. But the tests should still work on non-libc++ implementations.

2025-01-29 17:39 UTC, ldionne commented on libcxx/test/support/sized_allocator.h
> +//===----------------------------------------------------------------------===//
The changes to this file will go away when you rebase.

2025-01-29 17:39 UTC, ldionne commented on libcxx/test/std/containers/sequences/vector/vector.capacity/max_size.pass.cpp
> +  using alloc_traits        = typename Vector::__alloc_traits;
```suggestion
  using alloc_traits        = std::allocator_traits<typename Vector::allocator_type>;
```

To stay portable.

2025-01-29 17:39 UTC, ldionne commented on libcxx/test/std/containers/sequences/vector.bool/max_size.pass.cpp
> +  // This can cause overflow in __internal_cap_to_external and lead to incorrect results.
```suggestion
  // Test cases to identify incorrect implementations that unconditionally compute
  // an internal-to-external capacity in a way that can overflow, leading to incorrect
  // results.
```

This is worded to be a bit more implementation-agnostic.

2025-01-29 17:39 UTC, ldionne commented on libcxx/test/std/containers/sequences/vector.bool/max_size.pass.cpp
> +  // Test with various allocators and diffrent size_type
```suggestion
  // Test with various allocators and different size_type
```

2025-01-30 14:04 UTC, winner245 commented on libcxx/test/std/containers/sequences/vector.bool/max_size.pass.cpp
> +  using storage_type        = typename Vector::__storage_type;
I've made part of the test libc++ only because libstdc++'s implementation is slightly different from libc++. The return values in the two implementations are, in math form (assuming no overflow)

```cpp
min(numeric_limits<difference_type>::max() - bits_per_word + 1, alloc_traits::max_size() * bits_per_word); // libstdc++
min(numeric_limits<difference_type>::max(), alloc_traits::max_size() * bits_per_word); // libc++, MSVC-STL
```

2025-01-30 14:12 UTC, winner245 commented on libcxx/test/std/containers/sequences/vector.bool/max_size.pass.cpp
> +  using storage_type        = typename Vector::__storage_type;
Another reason why this test is not fully portable to other standard implementations is that libc++, libstdc++, and MSVC-STL all use different word types for vector<bool> underlying storage:

| Compiler   | Size Type                      |
|------------|--------------------------------|
| MSVC       | `unsigned int` (fixed)           |
| libstdc++  | `unsigned long` (fixed)          |
| libc++     | `alloc_traits::size_type` (configurable through custom allocator) |

2025-02-05 16:42 UTC, ldionne approved these changes

2025-02-06 03:38 UTC, merged