[clangd] Augment code completion results with documentation from the index.
llvm/llvm-project pull request #120099
Opened 2024-12-16 15:45 UTC by bevin-hansson

When looking up code completions from Sema, there is no associated
documentation. This is due to crash issues with stale preambles.
However, this also means that code completion results from other
than the main file do not have documentation in certain cases,
which is a bad user experience.

This patch performs a lookup into the index using the code
completion result declarations to find documentation, and
attaches it to the results.

This fixes clangd/clangd#2252 and clangd/clangd#564.

2024-12-16 15:46 UTC, bevin-hansson commented
I'm not entirely sure how to add to the tests for clangd. Any advice?

2024-12-17 07:59 UTC, bevin-hansson commented
> > I'm not entirely sure how to add to the tests for clangd. Any advice?
> 
> We have GTest unit tests for code completion in `CodeCompleteTests.cpp`. [This test](https://searchfox.org/llvm/rev/2df48fa78b496a2d276aa848598634bb2aad6857/clang-tools-extra/clangd/unittests/CodeCompleteTests.cpp#1074-1102) is a good starting point -- the test cases we want would be pretty similar, except we want to test class members (and we don't care whether it's in a system header specifically).

Thanks for the pointer! I added a test based on that one.

2024-12-18 06:19 UTC, HighCommander4 commented
Thanks. I haven't had a chance to look through the patch in detail yet, but the general shape seems reasonable.

I also wanted to check, have you resolved the issue you described in [this comment](https://github.com/clangd/clangd/issues/2252#issuecomment-2545141457)?

> now it only gives the docstring for field members and not methods

(I know the unit test covers methods, just asking in case you were seeing it not work in a real project.)

2024-12-18 07:31 UTC, bevin-hansson commented
> Thanks. I haven't had a chance to look through the patch in detail yet, but the general shape seems reasonable.
> 
> I also wanted to check, have you resolved the issue you described in [this comment](https://github.com/clangd/clangd/issues/2252#issuecomment-2545141457)?
> 
> > now it only gives the docstring for field members and not methods
> 
> (I know the unit test covers methods, just asking in case you were seeing it not work in a real project.)

Ah, yes, I fixed it. It was just a mistake in the implementation. It works now. I've tested it on my LLVM project as well, and it works fine there too.

2024-12-20 08:11 UTC, bevin-hansson commented
I've come across an issue with this, again. This seems to work for headers I've written myself (or at least ones in my own project), but for e.g. standard library include types, it doesn't work. Something like
```
  std::string a;
  a.^
```
still contains no documentation in the autocompletion results even though there are doccomments in the header in question.

Maybe this is related to how the standard library headers are indexed somehow...

2024-12-22 04:37 UTC, HighCommander4 commented
> I've come across an issue with this, again. This seems to work for headers I've written myself (or at least ones in my own project), but for e.g. standard library include types, it doesn't work. Something like
> 
> ```
>   std::string a;
>   a.^
> ```
> 
> still contains no documentation in the autocompletion results even though there are doccomments in the header in question.

Seems to be template-related.

test.hpp:
```c++
template <typename T>
struct templated {
  // comment
  void foo();
};
struct nontemplated {
  // comment
  void foo();
};
```

test.cpp:
```c++
#include "main.hpp"
void foo() {
  nontemplated n;
  n.f^   // comment is shown
  templated<int> t;
  t.f^  // comment is not shown
}
```

2024-12-22 22:19 UTC, HighCommander4 requested changes
Thanks, this patch generally looks great.

It would be nice to have a couple of test cases exercising the behaviour with overloaded methods when overload bundling is enabled (`CodeCompleteOptions::BundleOverloads` is set to true):
  * if we have an overload set where multiple methods have documentation, we pick an unspecified one of them ([here](https://searchfox.org/llvm/rev/e8f1902cca2aeaa23db6080fe33fbc67ed203350/clang-tools-extra/clangd/unittests/CodeCompleteTests.cpp#2005) is an existing assertion for that, in a test case exercising the non-header scenario)
  * if we have an overload set where some but not all methods have documentation, we pick one that does (rather than one that doesn't)

I think the code already does the right thing and should pass these testcases, but it's good to verify and have test coverage for them.

(The template issue discussed in the previous two comments can be left to a follow-up PR to investigate and improve on.)

2024-12-22 22:19 UTC, HighCommander4 commented on clang-tools-extra/clangd/unittests/CodeCompleteTests.cpp
> +TEST(CompletionTest, CommentsOnMembers) {
nit: call this `CommentsOnMembersFromHeader`

2024-12-22 22:19 UTC, HighCommander4 commented on clang-tools-extra/clangd/CodeComplete.cpp
> +        if (S.Documentation.empty())
nit: this early-return can be moved to before the lookup in `SymbolToCompletion`

2025-01-15 06:13 UTC, HighCommander4 approved these changes
Thanks for the update! This looks good, I'll go ahead and merge it.

2025-01-15 06:14 UTC, merged

2025-01-15 06:21 UTC, HighCommander4 commented
> Seems to be template-related.
> 
> test.hpp:
> 
> ```c++
> template <typename T>
> struct templated {
>   // comment
>   void foo();
> };
> struct nontemplated {
>   // comment
>   void foo();
> };
> ```
> 
> test.cpp:
> 
> ```c++
> #include "main.hpp"
> void foo() {
>   nontemplated n;
>   n.f^   // comment is shown
>   templated<int> t;
>   t.f^  // comment is not shown
> }
> ```

Filed https://github.com/clangd/clangd/issues/2290 as a follow-up to track this remaining issue with templated methods.

2025-01-15 07:31 UTC, bevin-hansson commented
Thanks for merging!