Reapply "[Driver][OHOS] Fix lld link issue for OHOS (#118192)"
llvm/llvm-project pull request #120159
Opened 2024-12-16 23:05 UTC by phuang

The problem in original change is because OHOS::getCompilerRT()
pickes a wrong builtin runtime (./lib/clang/20/lib/linux/libclang_rt.builtins-x86_64.a),
if ./lib/clang/20/lib/linux/libclang_rt.builtins-x86_64.a does exist on
the test filesystem. Address the problem by adding a env suffix
"-ohos" into the runtime library file.

2024-12-17 16:36 UTC, nico commented
IIRC there are two possible compiler-rt directory layouts. @MaskRay worked on moving many platforms from one to another. I think the newer layout doesn't use platform suffixes.

We shouldn't change where clang looks for things just for my bot. Thanks for figuring it out; I can delete the file from that bot. (What about developers that are in the same position though -- maybe it'd make sense to have a cmake action that deletes the file in the old location for a bit? Wouldn't help my bot since it doesn't use cmake, but might help others.)

We should figure out which path we want independently of my bot :) I don't know the current naming rules. Maybe @MaskRay remembers if we have documentation on this. Else, just relanding the patch as it was is fine.

2024-12-17 17:39 UTC, MaskRay commented on clang/lib/Driver/ToolChain.cpp
> +    else if (TT.isOHOSFamily())
This is for the old compiler-rt file hierarchy where `-android` is for compatibility. New OSes don't need this change.

2024-12-17 17:39 UTC, MaskRay reviewed
Without a test this should not land. https://github.com/llvm/llvm-project/pull/118192#issuecomment-2539595603

2024-12-17 18:07 UTC, phuang commented
> Without a test this should not land. [#118192 (comment)](https://github.com/llvm/llvm-project/pull/118192#issuecomment-2539595603)

Hi @MaskRay could you please suggest how to test the changes? Do you mean add  I though ohos.c should already cover it.

2024-12-17 18:09 UTC, phuang commented
> Without a test this should not land. [#118192 (comment)](https://github.com/llvm/llvm-project/pull/118192#issuecomment-2539595603)

Hi @MaskRay could you please suggest how to test the changes? I though `ohos.c` should already cover it.

2024-12-19 14:08 UTC, phuang commented
@MaskRay friendly ping. thanks.

2024-12-25 03:21 UTC, MaskRay requested changes
We need a test to clang/test/Driver/ohos.c similar to linux-ld.c clang_rt.crtbegin.o.

You can add UNSUPPORTED: system-windows to ohos.c so that we don't need backslashes.

2024-12-25 20:02 UTC, phuang commented
> We need a test to clang/test/Driver/ohos.c similar to linux-ld.c clang_rt.crtbegin.o.
> 
> You can add UNSUPPORTED: system-windows to ohos.c so that we don't need backslashes.

[ohos.c](https://github.com/llvm/llvm-project/blob/main/clang/test/Driver/ohos.c#L25
) already has many tests for it. This PR changes behavior of function [OHOS::getCompilerRT()](https://github.com/llvm/llvm-project/pull/120159/files#diff-763eb55ff16745f240d46c78f988f7a2010f61d2ae2550260b3dcd65dd9ba1c7L341). It will search extra folders for compiler rt builtin libraries. But in tests, OHOS::getCompilerRT()'s return value will not be changed, becasue those extra folders don't have those requested builtin files. It will just returns the default library file path.

2025-01-01 17:55 UTC, MaskRay approved these changes

2025-01-01 19:06 UTC, phuang commented
Thanks for reviewing it. Could you please land it for me? Seems I cannot land it.

2025-01-01 21:19 UTC, merged

2025-01-01 22:31 UTC, phuang commented
I checked the log. And I don't think the failed test is caused by this PR.

2025-01-02 13:33 UTC, nico commented
I did remove the contents of out/gn/lib/clang/20/lib/linux, but `./lib/clang/20/lib/linux/libclang_rt.builtins-x86_64.a` just reappeared on the next build.

I'm guessing this might break tests in cmake builds that use `-DLLVM_ENABLE_PER_TARGET_RUNTIME_DIR=OFF` (?)

http://45.33.8.238/linux/156390/step_6.txt

2025-01-02 14:05 UTC, phuang commented
In that case,  probably we have to add `-ohos` suffix in [ToolChain::buildCompilerRTBasename()](https://github.com/phuang/llvm-project/blob/main/clang/lib/Driver/ToolChain.cpp#L748) to fix this confliction. WDYT?

2025-01-02 14:12 UTC, nico commented
Here's a command you can use to reproduce this:

```
cmake -GNinja -DCMAKE_BUILD_TYPE=Release -DLLVM_ENABLE_ASSERTIONS=ON -DLLVM_ENABLE_PROJECTS='clang;lld;compiler-rt' -DLLVM_APPEND_VC_REV=NO -DLLVM_TARGETS_TO_BUILD='X86' -DLLVM_ENABLE_PER_TARGET_RUNTIME_DIR=OFF ../llvm-project/llvm
```

```
$ time ninja check-clang
```

2025-01-02 15:20 UTC, phuang commented
Thanks for the repro command. I reproduced the problem and verified it can be fixed with adding `-ohos` suffix.

2025-01-02 15:35 UTC, phuang commented
I created a [PR](https://github.com/llvm/llvm-project/pull/121484) to fix the issue. @nico could you please try it? thanks

2025-01-03 07:12 UTC, MaskRay commented
This patch is reverted.

We can disable the test on -DLLVM_ENABLE_PER_TARGET_RUNTIME_DIR=OFF layouts, but I don't find a lit feature that.

The usual way is to create a compiler-rt file hierarchy under Inputs. Just fd libclang_rt.builtins.a for some examples.

2025-01-03 14:57 UTC, phuang commented
I created a new [PR](!https://github.com/llvm/llvm-project/pull/121575) , PTAL. Thanks