[libc++] Speed up vector<bool> copy/move-ctors [1/3]
llvm/llvm-project pull request #120132
Opened 2024-12-16 20:03 UTC by winner245

### General description
This PR is part of a series aimed at significantly improving the performance of `vector<bool>`. Each PR focuses on enhancing a specific subset of operations, ensuring they are self-contained and easy to review. The main idea for performance improvements involves using word-wise implementation along with bit manipulation techniques, rather than solely using bit-wise operations in the previous implementation, resulting in substantial performance gains.

### Current PR
This PR significantly improves the performance of various constructors in `vector<bool>` by at least **500x** under a variety of practical storage word sizes. The improvements for the above tests are:

- Copy constructor: **576x**
- Copy constructor with extended allocator: **546x**
- Move constructor with extended allocator: **568x**

#### Before:

```
-------------------------------------------------------------------------------------
Benchmark                                           Time             CPU   Iterations
-------------------------------------------------------------------------------------
BM_CopyConstruct/vector_bool/5140480          8596063 ns      8563419 ns           78
BM_MoveConstruct/vector_bool/5140480            0.474 ns        0.473 ns   1470604919
BM_CopyConstruct_Alloc/vector_bool/5140480    8182327 ns      8169876 ns           83
BM_MoveConstruct_Alloc/vector_bool/5140480    8544951 ns      8537676 ns           83
```

#### After:

```
-------------------------------------------------------------------------------------
Benchmark                                           Time             CPU   Iterations
-------------------------------------------------------------------------------------
BM_CopyConstruct/vector_bool/5140480            14899 ns        14943 ns        46010
BM_MoveConstruct/vector_bool/5140480            0.451 ns        0.453 ns   1571837345
BM_CopyConstruct_Alloc/vector_bool/5140480      14979 ns        15033 ns        47913
BM_MoveConstruct_Alloc/vector_bool/5140480      15043 ns        15101 ns        45906
```

2024-12-16 21:45 UTC, philnik777 requested changes
We should instead fix #64038.

2024-12-21 19:14 UTC, winner245 commented
Thank you for your feedback. If I understand correctly, you are suggesting that I work on the general `std::copy` algorithm (and possibly std::move and others) for the `__bit_iterator` overload. I am a bit confused. Isn't this overload already implemented in `libcxx/include/__bit_reference`?

2024-12-21 20:30 UTC, philnik777 commented
> Thank you for your feedback. If I understand correctly, you are suggesting that I work on the general `std::copy` algorithm (and possibly std::move and others) for the `__bit_iterator` overload. I am a bit confused. Isn't this overload already implemented in `libcxx/include/__bit_reference`?

Yes, basically. The overload is implemented there, but is currently not called from the copy constructor because that (indirectly) uses the internal `__copy` version, which isn't optimized. To fix that, we should do something similar to what I've done in https://reviews.llvm.org/D156956. That way we also optimize `ranges::copy` as a nice side effect.

2025-01-20 15:06 UTC, winner245 commented
> We should instead fix #64038.

We should prioritize fixing the bitwise algorithms in #64038. I have already submitted PRs to address this, but I believe the approach in this PR presents several advantages:

1. **Simplicity and Maintainability**: This approach directly calls the plain-form `std::copy`, which copies entire words instead of manipulating individual bits. This leads to simpler and more maintainable code. Bitwise algorithms can be complex and tricky to implement, potentially increasing the maintenance burden in the future.
 
2. **Reliability**: The method in this PR is inherently less error-prone, as the plain-form `std::copy` is a widely used and thoroughly tested algorithm. In contrast, bitwise overloads of `std::copy` can be challenging to implement and prone to errors. We've encountered undefined behavior issues with these algorithms, as highlighted in #122410 and #122528. Furthermore, our current test coverage for the bitwise algorithms is very limited, primarily focusing only on 1-2 bytes. I have submitted PRs (#121209, #121138, #120909) to enhance the test coverage for these algorithms.

Given the above concerns, I believe that proceeding with this PR remains a valuable choice.

2025-01-20 16:55 UTC, ldionne approved these changes
LGTM with comments.

I do think we should go for the general-purpose optimizations in `std::copy` and friends for `vector<bool>::iterator`, however I think this patch is simple and doesn't preclude that optimization from being made. Worst case, if we think this adds any maintenance burden in the long run (unlikely), we could go back and call `std::copy(__v.begin(), __v.end(), begin())` instead in these call sites and remove the bit of logic related to `__external_cap_to_internal`.

2025-01-20 16:55 UTC, ldionne commented on libcxx/include/__vector/vector_bool.h
> +  __alloc_and_copy(__v);
I have a bit of trouble justifying it, but I would find the code easier to understand if you inlined `__alloc_and_copy` into its call sites. It's a simple function and some call sites are slightly different (e.g. wouldn't require setting the size outside of the `if` branch). IMO that would simplify the code.

2025-01-20 16:55 UTC, ldionne commented on libcxx/test/benchmarks/containers/ContainerBenchmarks.h
> +    auto v = std::move(c);
This benchmark has the issue that it only moves from a non-empty vector the first time around. After the first iteration, it is moving from a moved-from vector.

There's also the cost of destruction inside this benchmark, which may or may not add too much noise.

Since your patch doesn't actually change the move constructor (and the move constructor is close to trivial), I don't think you need this benchmark as part of this patch at all. I would suggest removing it.

2025-01-20 16:55 UTC, ldionne commented on libcxx/test/benchmarks/containers/ContainerBenchmarks.h
> +void BM_MoveConstruct_Alloc(benchmark::State& st, Container, Allocator a) {
I'd be okay with dropping this benchmark as well since you're demonstrating your win with the copy benchmark above, even though in principle this benchmark is indeed needed for coverage. I think it's reasonable to remove it since it's tricky to write properly (given the moved-from container).

2025-01-20 16:56 UTC, ldionne commented on libcxx/include/__vector/vector_bool.h
>      __guard.__complete();
You should also add a release note for this nice improvement!

2025-01-20 16:59 UTC, ldionne commented on libcxx/include/__vector/vector_bool.h
> +// This function copies each storage word as a whole, which is substantially more efficient than copying
Can you please ensure that we have appropriate test coverage for these constructors of `vector<bool>`?

2025-01-20 17:08 UTC, philnik777 commented on libcxx/include/__vector/vector_bool.h
>      __guard.__complete();
Note that this is actually fixing a regression and not really improving performance.

2025-01-20 17:10 UTC, philnik777 commented
I'm personally not a huge fan of this, since it adds another code path you have to know about to understand what vector does, especially since this doesn't improve anything over calling `std::copy` (assuming the optimization is fixed).

2025-01-20 17:54 UTC, philnik777 commented
@winner245 I disagree. This patch means more code without an obvious benefit. Since we will have the bitwise versions anyways, I don't think the points you make actually apply. Having essentially the same (or a better optimization) twice yields its own problems, since optimizations are often only applied in one case. I don't know whether that will actually be a problem, but there have been lots of places where I though there was no optimiation to gain and it turned out I was wrong.

On the reliability side, given that the two cases you mention are either something that has been addressed by the standard itself (making it a questionable decision to exploit it for any implementation) and a compilation error which no one ran into in the last decade or so (AFAICT) I doubt there is much of a real problem. I agree these are in fact bugs, I just question how wide of an impact they actually have.

(Note that I'm adding even more constant folding in #106225 to work around more constant folding problems)

2025-01-20 19:06 UTC, ldionne commented
I suggest we then wait for the underlying regression fix to land so we can reevaluate this patch. At that point, this would become a pure NFC refactoring IIUC, and we can evaluate it on that basis.

2025-01-20 22:27 UTC, philnik777 commented
> I suggest we then wait for the underlying regression fix to land so we can reevaluate this patch. At that point, this would become a pure NFC refactoring IIUC, and we can evaluate it on that basis.

Yes, that should be the case. If it's not then this would probably get my approval as well.

(Also, how the hell does github work? I wrote the second comment before the first one, but GH deleted that for me and I didn't feel like re-writing it, so I wrote a shorter message)

2025-01-20 22:30 UTC, philnik777 commented on libcxx/include/__vector/vector_bool.h
> +  __alloc_and_copy(__v);
Actually, I wonder how I'd feel about this patch if this comment was addressed. IDK if it'd feel to me like the same mental overhead then as it is now.

2025-01-20 22:39 UTC, winner245 commented
> > I suggest we then wait for the underlying regression fix to land so we can reevaluate this patch. At that point, this would become a pure NFC refactoring IIUC, and we can evaluate it on that basis.
>
> Yes, that should be the case. If it's not then this would probably get my approval as well.

Thanks @philnik777. I think your concern is valid, and I am fine with that. In that case, we will need to land #121013 first. Then this one becomes NFC or I might need to improve the tests for the copy/move constructors as the existing ones only considered up to 3 bytes, which is less than the word size of 8 bytes.

2025-01-20 22:47 UTC, winner245 commented on libcxx/include/__vector/vector_bool.h
> +// This function copies each storage word as a whole, which is substantially more efficient than copying
We do have 4 tests (`copy.pass.cpp`, `move.pass.cpp`, `copy_alloc.pass.cpp`, `move_alloc.pass.cpp`) covering for these constructors but the tests are limited to <= 3 bytes, which is less than the word size of 8 bytes. However, the optimizations for `std::{copy, fill_n}` have code branches covering 3 cases: 
- less than 1 word (this is the case currently covered);
- 2+ words, which contains at least one whole word (currently not covered);
- 3+ words, which contains whole words as well as partial word at the end (currently not covered).

 IMO, we should improve the tests for these constructors to cover more words.

2025-01-21 16:45 UTC, winner245 commented on libcxx/include/__vector/vector_bool.h
> +  __alloc_and_copy(__v);
@philnik777 If the comment raised by @ldionne is addressed, we will have:


https://github.com/winner245/llvm-project/blob/ead9ab143db8f923e16d04c21276ff1d1728f7f8/libcxx/include/__vector/vector_bool.h#L708-L716

```cpp
template <class _Allocator>
_LIBCPP_CONSTEXPR_SINCE_CXX20 vector<bool, _Allocator>::vector(const vector& __v, const allocator_type& __a)
    : __begin_(nullptr), __size_(0), __cap_(0), __alloc_(__a) {
  if (__v.size() > 0) {
    __vallocate(__v.size());
    std::copy(__v.__begin_, __v.__begin_ + __external_cap_to_internal(__v.size()), __begin_);
    __size_ = __v.size();
  }
}
```


versus what we had before:

https://github.com/llvm/llvm-project/blob/afced70e697e66fb6920b53d489d3fa4498e22dc/libcxx/include/__vector/vector_bool.h#L707-L714

I would invite you and @ldionne for a second thought. IMO, this patch will slightly increase the clarity and reduce future maintenance burden. 

1. The call to the private function `__construct_at_end` is now replaced by a call to the general-purpose function `std::copy`, along with an explicit size update. Using the well-known `std::copy`, it is clear that the new implementation copies the underlying data and updates the size, without needing to understand what the internal `__construct_at_end` does. Additionally, making the size update explicit enhances clarity (previously, I had to jump into both overloads of `__construct_at_end` and make sure they both update the size).

2. The new implementation does not require any special optimization. It calls a general-purpose copy function, which naturally yields optimal performance. In contrast, the old implementation relies on complex optimizations for `__bit_iterator` to achieve similar performance. My patch actually removes these unnecessary bitwise optimizations, reducing future maintenance burdens (we cannot neglect the maintenance burdens of these bitwise optimization algorithms given that we are still fixing existing bugs related to these optimizations).

What do you think?

2025-01-29 17:02 UTC, ldionne approved these changes
LGTM with comments applied. I would also like @philnik777 to take another look.

Personally, I find the code a lot easier to read after this PR. We call `std::copy` directly, which everyone knows well, and we set the size explicitly from the constructor. That removes the need for calling `__construct_at_end`, which has a strange contract like that of only being called when the vector is empty.

2025-01-29 17:02 UTC, ldionne commented on libcxx/test/benchmarks/containers/ContainerBenchmarks.h
> +    Container v(c, a);
```suggestion
    Container v(c, a); // we assume the destructor doesn't dominate the benchmark
```

2025-01-29 21:40 UTC, winner245 commented on libcxx/test/std/containers/sequences/vector.bool/copy.pass.cpp
> +    using A = test_allocator<bool>;
This check was actually covered on line 29 (i.e., line 30 in this commit) of `copy.pass.cpp` in a more general form which extracts the allocator instead of hard-coded.

2025-01-29 21:42 UTC, winner245 commented on libcxx/test/std/containers/sequences/vector.bool/copy_alloc.pass.cpp
> +  bool a05[5]  = {1, 0, 1, 0, 1};
The usages of built-in arrays are have been replaced by `std::array` in the tests.

2025-01-29 21:43 UTC, winner245 commented on libcxx/test/benchmarks/containers/ContainerBenchmarks.h
> +    Container v(c, a);
Added the comment.

2025-02-02 16:14 UTC, philnik777 requested changes
> LGTM with comments applied. I would also like @philnik777 to take another look.
> 
> Personally, I find the code a lot easier to read after this PR. We call `std::copy` directly, which everyone knows well, and we set the size explicitly from the constructor. That removes the need for calling `__construct_at_end`, which has a strange contract like that of only being called when the vector is empty.

What strange contract are you talking about? AFAICT the only precondition is that there is enough space to construct the elements.

I don't really care whether we call `__construct_at_end` or use `std::copy` directly, but I still find `std::copy(__v.begin(), __v.end(), begin())` _much_ more readable than the current proposal. If the only reason for this PR is readability I don't see how the current proposal is any better than the status quo.

2025-02-02 16:58 UTC, winner245 commented
> > LGTM with comments applied. I would also like @philnik777 to take another look.
> >
> >Personally, I find the code a lot easier to read after this PR. We call `std::copy` directly, which everyone knows well, and we set the size explicitly from the constructor. That removes the need for calling `__construct_at_end`, which has a strange contract like that of only being called when the vector is empty.
>
>What strange contract are you talking about? AFAICT the only precondition is that there is enough space to construct the elements.

Before my patch #119632, `__construct_at_end(,,__n)` had a documented precondition of `__n > 0`, alongside an undocumented precondition of `size() > 0`. After applying #119632, we simplified this into a single precondition `size() + __n <= capacity()`. 

> I don't really care whether we call `__construct_at_end` or use `std::copy` directly, but I still find `std::copy(__v.begin(), __v.end(), begin())` _much_ more readable than the current proposal. If the only reason for this PR is readability I don't see how the current proposal is any better than the status quo.

Please note that we are not comparing `std::copy(__v.begin(), __v.end(), begin())` with `std::copy(__v.__begin_, __v.__begin_ + __external_cap_to_internal(__v.size()), __begin_);`, but rather 

```cpp
__construct_at_end(__v.begin(), __v.end(), __v.size());
```

with

```cpp
std::copy(__v.__begin_, __v.__begin_ + __external_cap_to_internal(__v.size()), __begin_);
__size_ = __v.size();
```

I have no idea what `__construct_at_end` does without delving into its implementation, which has a contract and multiple lines of code that invoke specialized versions of `std::__copy`. To fully understand what `__construct_at_end` does, one has to figure out a lot more internal implementation details such as `__bit_iterator`, `__bit_reference`, and the optimized algorithms of `std::__copy`  for `__bit_iterator`. In contrast, with this PR, one only needs to know the general purpose standard-form `std::copy`, which every C++ programmer is familiar with.

2025-03-13 18:57 UTC, ldionne requested changes
@philnik777 If this patch uses `std::copy(__v.begin(), __v.end(), begin())`, we need to handle the leading bits in the last word like `__construct_at_end` does:

```c++
if (end().__ctz_ != 0)
  std::fill_n(end(), __bits_per_word - end().__ctz_, 0);
```

Then, the benefit of this patch basically goes away since we'd be better off just calling `__construct_at_end` and not inlining anything.

That being said, since we are failing to gain consensus to move forward with this patch, I would suggest that we take the test improvements in this patch and land them, and not move forward with the refactoring part of the patch. After the recent improvements to `std::vector<bool>` optimizations, the refactoring part of this patch doesn't provide as much value, and I think our time may be better spent on something else than trying to gain consensus on a minor stylistic refactoring.

2025-03-14 16:18 UTC, winner245 commented
I've dropped all commits related to algorithm changes and refactoring, and retained only the test enhancements. Accordingly, I've updated the PR description and revised the title too reflect these changes.

2025-03-19 16:06 UTC, ldionne approved these changes
LGTM, thanks! Very minor nitpicky comments, please feel free to land after making those  changes.

2025-03-19 16:06 UTC, ldionne commented on libcxx/test/std/containers/sequences/vector.bool/move.pass.cpp
> +  assert(v.empty()); // The moved-from vector is guarantted to be empty after move-construction
```suggestion
  assert(v.empty()); // The moved-from vector is guaranteed to be empty after move-construction
```

2025-03-19 16:06 UTC, ldionne commented on libcxx/test/std/containers/sequences/vector.bool/move.pass.cpp
> +  std::vector<bool, A> v0(N, false, a);
```suggestion
  std::vector<bool, A> copy(N, false, a);
```

I think the test would be more readable like that. Or `std::vector<bool, A> original`.

2025-03-19 16:06 UTC, ldionne commented on libcxx/test/std/containers/sequences/vector.bool/move_alloc.pass.cpp
> +    assert(v.empty()); // After container-move, the vector is guarantted to be empty
```suggestion
    assert(v.empty()); // After container-move, the vector is guaranteed to be empty
```

2025-03-20 12:37 UTC, merged