[clang-tidy][NFC] swap cppcoreguidelines-narrowing-conversions and bugprone-narrowing-conversions
llvm/llvm-project pull request #120245
Opened 2024-12-17 15:32 UTC by HerrCai0907

According to #116591.
> Coding guidelines should "cherry-pick" (and posddsibly configure/harden/make more strict) base checks.
We should move narrowing conversion to bugprone and keep alias in cppcoreguidelines

2024-12-17 17:43 UTC, PiotrZSL approved these changes
LGTM

2024-12-18 08:23 UTC, carlosgalvezp requested changes
LGTM! However I think we need to update:

- Release Notes. This is not quite a NFC change for users, since most of them probably disable aliases, so some of them might be left out without this check enabled.

- Alias table: now the alias relationship is the other way around.

2024-12-18 13:16 UTC, HerrCai0907 commented
> most of them probably disable aliases

can clangtidy disable aliases?

2024-12-18 19:44 UTC, carlosgalvezp commented
> can clangtidy disable aliases?

No, I meant that people disable them manually. I have some WIP work on disabling aliases automatically but it's not quite ready yet :)

2024-12-19 00:22 UTC, HerrCai0907 commented
If we don't have disable alias, then it will not change anything in user side.

2024-12-19 20:23 UTC, carlosgalvezp commented
This change is not just a refactor, it leads to user-facing documentation changes (which check alias which), so I think it should be mentioned in the Release Notes. It doesn't cost anything to add it :)

2024-12-20 00:31 UTC, 5chmidti commented on clang-tools-extra/clang-tidy/bugprone/NarrowingConversionsCheck.h
Please change the header guard to use `bugprone` as the 'path' instead of `cppcoreguidelines`

2024-12-20 00:31 UTC, 5chmidti commented on clang-tools-extra/docs/clang-tidy/checks/bugprone/narrowing-conversions.rst
> +We enforce only part of the guideline, more specifically, we flag narrowing conversions from:
Should this part be slightly reworded?

2024-12-20 00:31 UTC, 5chmidti commented on clang-tools-extra/docs/clang-tidy/checks/list.rst
> +   :doc:`cppcoreguidelines-narrowing-conversions <bugprone/narrowing-conversions>`, :doc:`bugprone-narrowing-conversions <cppcoreguidelines/narrowing-conversions>`,
Please sort this in alphabetically

2024-12-23 12:35 UTC, carlosgalvezp commented on clang-tools-extra/clang-tidy/bugprone/NarrowingConversionsCheck.h
+1

2024-12-24 15:24 UTC, HerrCai0907 commented
ping

2024-12-26 21:45 UTC, carlosgalvezp commented on clang-tools-extra/clang-tidy/bugprone/NarrowingConversionsCheck.h
@HerrCai0907 I don't believe this comment has been addressed yet.

2024-12-27 08:56 UTC, HerrCai0907 commented on clang-tools-extra/clang-tidy/bugprone/NarrowingConversionsCheck.h
sorry for forgetting it

2024-12-28 14:44 UTC, 5chmidti approved these changes
LGTM, thanks

2024-12-29 11:22 UTC, merged