[LoopVectorizer] Add support for chaining partial reductions
llvm/llvm-project pull request #120272
Opened 2024-12-17 17:18 UTC by NickGuy-Arm

Currently depends on #92418, so this will be mangled with that patch and will remain as a draft until it is merged

2025-01-15 13:48 UTC, NickGuy-Arm commented
As a side effect of this work being motivated by supporting complex dot product instructions (and thus allowing use of straight loads instead of gathers/deinterleaving loads), this PR also introduces support for partial reduction subtractions via negating the second operand of `partial.reduce.add` calls.

2025-01-20 11:12 UTC, fhahn commented
> As a side effect of this work being motivated by supporting complex dot product instructions (and thus allowing use of straight loads instead of gathers/deinterleaving loads), this PR also introduces support for partial reduction subtractions via negating the second operand of `partial.reduce.add` calls.

Sounds like supporting partial reduction subtractions would be a good extension on its own (and test-able independently), could it be split off?

2025-01-20 11:30 UTC, SamTebbs33 requested changes

2025-01-20 11:30 UTC, SamTebbs33 commented on llvm/lib/Transforms/Vectorize/LoopVectorize.cpp
> +
The target checks this.

2025-01-20 11:30 UTC, SamTebbs33 commented on llvm/lib/Transforms/Vectorize/VPlan.h
> +                                        getUnderlyingInstr());
Why do we need to set the underlying instruction here? Partial reductions aren't equivalent to their underlying add/sub instruction.

2025-01-20 11:30 UTC, SamTebbs33 commented on llvm/test/CodeGen/AArch64/partial-reduction-chained.ll
> +attributes #0 = { mustprogress noinline nounwind vscale_range(1,16) "frame-pointer"="non-leaf" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="cortex-x3" "target-features"="
You can remove all of the strings other than "-target-features"="+sve"

2025-01-20 11:30 UTC, SamTebbs33 commented on llvm/test/CodeGen/AArch64/partial-reduction-chained.ll
> +;.
We don't need these.

2025-01-20 11:30 UTC, SamTebbs33 commented on llvm/test/CodeGen/AArch64/partial-reduction-chained.ll
> +; RUN: opt -S -o - %s --passes=loop-vectorize -force-vector-width=16 -force-vector-interleave=1 -scalable-vectorization=on | FileCheck %s
Is `-scalable-vectorisation` required if we have SVE enabled? I think it would be better to add these tests to the existing partial reduction test files, unless there's a reason why they can't share run lines. If there is a reason for that then we'll want a file for neon and a file for mixed extend types.

2025-01-20 11:30 UTC, SamTebbs33 commented on llvm/lib/Transforms/Vectorize/LoopVectorize.cpp
> +  if (auto *OpInst = dyn_cast<Instruction>(Op)) {
A comment here would be good.

2025-01-20 11:30 UTC, SamTebbs33 commented on llvm/test/CodeGen/AArch64/partial-reduction-chained.ll
> +; CHECK-NEXT:    br i1 [[EXITCOND_NOT]], label [[FOR_COND_CLEANUP]], label [[FOR_BODY]], !llvm.loop [[LOOP3:![0-9]+]], !loop [[META4:![0-9]+]]
You can remove the checks from and including the scalar.ph for each test.

2025-01-20 14:26 UTC, SamTebbs33 commented on llvm/lib/Transforms/Vectorize/VPlan.h
> +                                        getUnderlyingInstr());
Ah it's just passing what's already set, ignore me!

2025-01-20 14:40 UTC, NickGuy-Arm commented
> Sounds like supporting partial reduction subtractions would be a good extension on its own (and test-able independently), could it be split off?

Yep. I've pulled it out completely, and will create a new PR for adding sub support.

2025-01-20 14:40 UTC, NickGuy-Arm commented on llvm/test/CodeGen/AArch64/partial-reduction-chained.ll
> +; RUN: opt -S -o - %s --passes=loop-vectorize -force-vector-width=16 -force-vector-interleave=1 -scalable-vectorization=on | FileCheck %s
It was needed as otherwise `-force-vector-width=16` disables scalable vectorization. I've switched it to use `-vectorizer-maximize-bandwidth` now though, which achieves the same thing.

2025-01-20 14:40 UTC, NickGuy-Arm commented on llvm/lib/Transforms/Vectorize/LoopVectorize.cpp
> +  if (auto *OpInst = dyn_cast<Instruction>(Op)) {
Added

2025-01-20 14:40 UTC, NickGuy-Arm commented on llvm/test/CodeGen/AArch64/partial-reduction-chained.ll
> +; CHECK-NEXT:    br i1 [[EXITCOND_NOT]], label [[FOR_COND_CLEANUP]], label [[FOR_BODY]], !llvm.loop [[LOOP3:![0-9]+]], !loop [[META4:![0-9]+]]
These are all the auto-generated lines. I'd rather not mess with it as the tests will be updated again when the PR for adding `sub` support comes along. Especially now that we've added more run lines. It feels like a lot of tedium for little to no value.

2025-01-20 14:40 UTC, NickGuy-Arm commented on llvm/test/CodeGen/AArch64/partial-reduction-chained.ll
> +;.
Ack. See above.

2025-01-20 17:03 UTC, SamTebbs33 commented on llvm/lib/Transforms/Vectorize/LoopVectorize.cpp
> +
It used to be checked here until the second re-land of the partial reduction work so it could be back here because of rebasing gone wrong!

2025-01-22 10:59 UTC, SamTebbs33 commented on llvm/test/Transforms/LoopVectorize/AArch64/partial-reduce-chained.ll
> +;.
You can remove these.

2025-01-22 15:45 UTC, SamTebbs33 approved these changes
LGTM with a couple of ideas.

2025-01-22 17:11 UTC, fhahn commented
> > Sounds like supporting partial reduction subtractions would be a good extension on its own (and test-able independently), could it be split off?
> 
> Yep. I've pulled it out completely, and will create a new PR for adding sub support.
> 
> Edit; PR for adding subtraction partial reductions: #123636

Ok great thanks! It’s a deft at the moment, any issues?

2025-01-23 12:02 UTC, NickGuy-Arm commented
> > > Sounds like supporting partial reduction subtractions would be a good extension on its own (and test-able independently), could it be split off?
> > 
> > 
> > Yep. I've pulled it out completely, and will create a new PR for adding sub support.
> > Edit; PR for adding subtraction partial reductions: #123636
> 
> Ok great thanks! It’s a deft at the moment, any issues?

Only when isolating/creating the tests. As far as I can tell, subtraction partial reductions will rarely, if ever, be provided as an input to vplan (due to no `RecurKind::Sub`), I haven't looked into it since Monday though, so maybe there's a simpler test case I haven't found yet.
That, and partial-reduce-chained.ll from this PR will need to be updated too..

2025-01-23 17:24 UTC, merged

2025-01-23 22:03 UTC, vitalybuka commented
@NickGuy-Arm Reverted https://github.com/llvm/llvm-project/pull/124198
Note, revert includes a followup patch.