[Driver][SPIR-V] Use consistent tools to convert between text and binary form
llvm/llvm-project pull request #120266
Opened 2024-12-17 16:58 UTC by sarnex

Currently we produce SPIR-V text with `spirv-dis` but assemble it with `llvm-spirv`. The SPIR-V text format is different between the tools so the assemble fails. We need to use the same tool for both, and since `SPIRV-Tools` is technically an optional runtime dependency, just use `llvm-spirv` since that's already required. 

Once we are using the SPIR-V backend we should be able to get rid of this.

2025-01-02 16:12 UTC, sarnex commented
Ping on this one @llvm/pr-subscribers-backend-spir-v @llvm/pr-subscribers-clang-driver

Thx!

2025-01-07 16:05 UTC, sarnex commented
@bader Do you mind reviewing this as a member of the SPIR-V team (you already reviewed this internally) or recommend someone else to review, I'm having trouble finding someone :)

2025-01-07 18:10 UTC, bader approved these changes
LGTM.
@svenvh, do you have any objections?

2025-01-08 09:28 UTC, svenvh requested changes
Thanks for drawing this to my attention!

The output produced by llvm-spirv's `-to-text` is an internal textual format, intended for testing llvm-spirv only (@MrSidims please correct me if I'm wrong).  I don't think we should be exposing that format through the clang driver.

What is the use case that you're trying to solve?  Would it be possible to add a `spirv-as` invocation before passing textual SPIR-V back to llvm-spirv?  Alternatively, perhaps we should teach llvm-spirv to be able to consume the conventional SPIRV-Tools textual format.  That would be a natural counterpart to llvm-spirv's `--spirv-tools-dis` option.

> Once we are using the SPIR-V backend we should be able to get rid of this.

With the current patch, I expect you'd still have the problem that llvm-spirv cannot consume the output produced by the SPIR-V backend?

2025-01-08 11:18 UTC, MrSidims commented
I agree with Sven. We mustn't reuse llvm-spirv's tests format in other repositories.

2025-01-08 16:07 UTC, sarnex commented
Thanks for the review, let me use `spirv-as` so we rely on the SPIR-V tools format.

2025-01-08 17:21 UTC, sarnex commented
I just reworked this to use `spirv-as`, please take a look :)

2025-01-09 10:49 UTC, svenvh approved these changes

2025-01-09 14:33 UTC, MrSidims approved these changes

2025-01-09 15:59 UTC, merged

2025-01-09 16:14 UTC, jplehr commented
This also failed one of our bots: https://lab.llvm.org/buildbot/#/builders/140/builds/14350

2025-01-09 16:16 UTC, sarnex commented
Yep already working on it, integration issue with another change from me, my bad

2025-01-09 16:17 UTC, jplehr commented
> Yep already working on it, integration issue with another change from me, my bad

Thank you for working on a fix. :)

2025-01-09 16:36 UTC, sarnex commented
Fix https://github.com/llvm/llvm-project/pull/122310