[diagtool] Make the BuiltinDiagnosticsByID table sorted
llvm/llvm-project pull request #120321
Opened 2024-12-17 22:33 UTC by karka228

When building with -DLLVM_ENABLE_EXPENSIVE_CHECKS=ON with a recent libstdc++ (e.g. from gcc 13.3.0) the testcase
clang/test/Misc/warning-flags-tree.c fail with the message:
```
+ diagtool tree --internal
 .../include/c++/13.3.0/bits/stl_algo.h:2013:
In function:
    _ForwardIterator std::lower_bound(_ForwardIterator, _ForwardIterator,
    const _Tp &, _Compare) [_ForwardIterator = const
    diagtool::DiagnosticRecord *, _Tp = diagtool::DiagnosticRecord, _Compare
    = bool (*)(const diagtool::DiagnosticRecord &, const
    diagtool::DiagnosticRecord &)]

Error: elements in iterator range [first, last) are not partitioned by the predicate __comp and value __val.

Objects involved in the operation:
    iterator "first" @ 0x7ffea8ef2fd8 {
    }
    iterator "last" @ 0x7ffea8ef2fd0 {
    }
```
The reason for this error is that std::lower_bound is called on BuiltinDiagnosticsByID without it being entirely sorted. Calling std::lower_bound If the range is not sorted, the behavior of this function is undefined. This is detected when building with expensive checks.

To make BuiltinDiagnosticsByID sorted we need to slightly change the order the inc-files are included.

2024-12-19 09:07 UTC, bjope commented
Added some reviewers based on people that have touched code related to "diagnostics" (but don't really know much about the fix, nor who might know anything about this particular code in diagtool). Feel free to redirect to someone else (or let me know if I should try to find other reviewers).

2024-12-30 07:46 UTC, cor3ntin commented on clang/tools/diagtool/DiagnosticNames.cpp
> +#include "clang/Basic/DiagnosticCrossTUKinds.inc"
This seems brittle - Maybe we should call `std::sort` somewhere instead?

2025-01-03 10:16 UTC, kadircet requested changes

2025-01-03 10:16 UTC, kadircet commented on clang/tools/diagtool/DiagnosticNames.cpp
> +// clang-format off
also it's unclear where the "ground truth" for this order is coming from. AFAICT, order is defined by https://github.com/llvm/llvm-project/blob/main/clang/include/clang/Basic/DiagnosticIDs.h#L49-L65
and enforced by very subtle interactions between tablegen and how particular headers include these.

since this order needs to be preserved in multiple places, can you put together a wrapper header, which includes individual diagnostic kinds in the specific order and explain the relationship between these pieces? (I'd rather have a solution that puts all of this logic into tablegen instead, generating enums with a particular order once, but I can see that's a much bigger change that you might not want to sign up).

2025-01-16 06:27 UTC, karka228 commented on clang/tools/diagtool/DiagnosticNames.cpp
> +// clang-format off
"since this order needs to be preserved in multiple places, can you put together a wrapper header, which includes individual diagnostic kinds in the specific order and explain the relationship between these pieces?"
@kadircet I added a new file DiagnosticsID.inc as a "wrapper header".

2025-01-16 08:47 UTC, bjope commented on clang/include/clang/Basic/DiagnosticIDs.inc
> +// sure the table is sorted.
The context for "the table" is a bit unclear here.
Maybe something like
  "... to make sure tables based on Diagnostic IDs are partitioned/sorted based on DiagID."

2025-01-16 12:11 UTC, kadircet requested changes

2025-01-16 12:11 UTC, kadircet commented on clang/include/clang/Basic/DiagnosticIDs.inc
we already have a concept of `DiagnosticID`. can we rename this to `AllDiagnosticKinds.inc` ?

2025-01-16 12:11 UTC, kadircet commented on clang/include/clang/Basic/DiagnosticIDs.inc
> +// Turn off clang-format, as the order of the includes are important to make
can you mention that the order is dictated by https://github.com/llvm/llvm-project/blob/main/clang/include/clang/Basic/DiagnosticIDs.h#L49-L65 ?

2025-01-16 13:15 UTC, karka228 commented on clang/include/clang/Basic/DiagnosticIDs.inc
I have now renamed the file to AllDiagnosticKinds.inc

2025-01-16 13:15 UTC, karka228 commented on clang/include/clang/Basic/DiagnosticIDs.inc
> +// Turn off clang-format, as the order of the includes are important to make
I added a comment about that in the file header.

2025-01-16 13:30 UTC, kadircet approved these changes
thanks!

2025-01-17 09:20 UTC, cor3ntin approved these changes

2025-01-17 09:23 UTC, merged