[libc++] Fix shrink_to_fit implementation for vector<bool>
llvm/llvm-project pull request #120495
Opened 2024-12-18 23:29 UTC by winner245

The current implementation of `vector<bool>::shrink_to_fit` contains a logical error that prevents the function from doing anything, i.e., it will never shrink the capacity. This is because the current implementation checks the following  condition

```cpp
if (__external_cap_to_internal(size()) > __cap_) {
  do_shrink();
}
```

However, this condition is always false, as the number of used internal words `__external_cap_to_internal(size())` will never exceed the internal storage capacity (`__cap_`). This appears to be an implementation error, particularly since a similar logical error was found in the `reserve()` function of `__split_buffer` in #105681 and was corrected last month.

While the current implementation technically conforms to the standard—since the request to shrink is non-binding—it's hard to believe this implementation was intentional. If this were intentional, an empty function body would yield an equivalent effect, which raises doubts about the original intent of the implementation.

This PR addresses the issue by modifying `shrink_to_fit` to actually perform the necessary capacity reduction, ensuring it behaves as expected.

2025-01-14 17:34 UTC, ldionne requested changes

2025-01-14 17:34 UTC, ldionne commented on libcxx/test/std/containers/sequences/vector.bool/shrink_to_fit.pass.cpp
> +    unsigned bits_per_word = static_cast<unsigned>(sizeof(C::__storage_type) * CHAR_BIT);
The part of the test suite located under `libcxx/test/std` is intended to be portable and usable by other implementations (like MSVC STL or libstdc++). As such, we don't use things specific to libc++ like `C::__storage_type`. Or if we absolutely must, we either:

1. Put that part of the test under `libcxx/test/libcxx`, which contains tests that are not entirely portable, or
2. Guard the check with `#if defined(_LIBCPP_VERSION)`, or
3. Use something like `LIBCPP_ASSERT` from `test_macros.h`.

Which of those three we do depends on the amount of libc++ specific test code we're trying to add, maintenance burden, etc.

In this case, the very best would be to figure out the number of bits per word via some public-facing API if that's doable, but I'm not certain it is. Otherwise, I would probably go for `#if defined(_LIBCPP_VERSION)` around those two tests.

2025-01-14 18:35 UTC, winner245 commented on libcxx/test/std/containers/sequences/vector.bool/shrink_to_fit.pass.cpp
> +    unsigned bits_per_word = static_cast<unsigned>(sizeof(C::__storage_type) * CHAR_BIT);
Thank you for your insightful feedback. The three options you mentioned have provided me with some new and valuable information that I wasn't previously aware of.

Among the options, I believe using `#if defined(_LIBCPP_VERSION)` around the two tests that use `C::__storage_type` would be the most appropriate for my purpose. This is because libc++ and libstdc++ have different word sizes (libc++ uses `Alloc::size_type`, which is typically 64 bits, while libstdc++ uses `unsigned long`). Moreover, I don't find a way to extract this information from a public API. Even if I could, the decision on whether to shrink would be implementation-dependent as the request to shrink is non-binding. Therefore, I choose to use the `#if defined(_LIBCPP_VERSION)` option you suggested.

2025-01-15 21:18 UTC, winner245 commented
@asmok-g Thanks for your feedback! The previous change #120577 was an internal fix. I'm curious about how it caused issues with Google code, and how my current PR fixes that. Could you provide more details or context about the specific problems it created? This will help me understand the impact and ensure a comprehensive fix.

2025-01-17 10:36 UTC, asmok-g commented
We got `HeapLeakChecker: memory leak` reports. Running under asan for more details, the stack trace shows the leak is related to the allocation of a `vector_bool`. I unfortunately can only provide a repro next week. But can we still carry on with this fix as is for the time being ?

2025-01-18 11:43 UTC, alexfh commented
> @asmok-g Thanks for your feedback! The previous change #120577 was an internal fix. I'm curious about how it caused issues with Google code, and how my current PR fixes that. Could you provide more details or context about the specific problems it created? This will help me understand the impact and ensure a comprehensive fix.

I suspect that the issues we've seen may be caused by the same effect as described in #122502. If we find a distinct problem, we'll let you know.

2025-01-20 16:21 UTC, ldionne approved these changes
LGTM with a few comments, thanks a lot for fixing this!

2025-01-20 18:57 UTC, ldionne approved these changes

2025-01-21 21:28 UTC, merged