[WIP][LoopVectorize] Perform loop versioning for some early exit loops
llvm/llvm-project pull request #120603
Opened 2024-12-19 16:33 UTC by david-arm

2025-02-11 13:29 UTC, david-arm commented
Gentle ping. :)

2025-02-11 20:40 UTC, fhahn reviewed
Are there any documented guarantees related to alignment of pointers and dereferenceability of loads on the LLVM IR level? I had brief look in LangRef but couldn't find anything. 

Could the assumption cause problems with HW/software extensions, .e.g. something like AArch64 MTE or a software layer that checks out-of-bounds accesses? Not super familiar with the details of MTE, but I think it tracks sizes of allocations on smaller granularity than page sizes and traps on out-of-bound accesses.

2025-02-12 11:28 UTC, david-arm commented
> Are there any documented guarantees related to alignment of pointers and dereferenceability of loads on the LLVM IR level? I had brief look in LangRef but couldn't find anything.
> 
> Could the assumption cause problems with HW/software extensions, .e.g. something like AArch64 MTE or a software layer that checks out-of-bounds accesses? Not super familiar with the details of MTE, but I think it tracks sizes of allocations on smaller granularity than page sizes and traps on out-of-bound accesses.

This is something I'll look into - perhaps the worst case would be that loop versioning is off by default for AArch64 and would have to be enabled explicitly with a flag. Without digging into this in huge detail, is it possible that if MTE is a problem for this PR, then we also have a problem today in the loop vectoriser when we if-convert loads into unconditional loads based upon the result of `isDereferenceableAndAlignedInLoop` - see `LoopVectorizationLegality::canVectorizeWithIfConvert`. MTE can be used for stack tagging.

2025-02-13 11:16 UTC, david-arm commented on llvm/lib/Transforms/Vectorize/LoopVectorize.cpp
> +               "potentially faulting loads");
Yeah potentially, although currently we won't vectorise with UF>1 anyway because it's explicitly disabled in `selectInterleaveCount`. That's because we don't yet handle or'ing together the multiple early exit conditions for all the parts in vplan. So I didn't try adding support for runtime checks when UF>1 because there isn't any way to test it.

2025-02-13 13:21 UTC, david-arm commented on llvm/lib/Transforms/Vectorize/LoopVectorizationLegality.cpp
> +    PotentiallyFaultingLoads.push_back({LI, Start});
We need the Start because that's guaranteed to be loop-invariant, whereas `LI->getPointerOperand()` will be a loop-varying expression, i.e. `getelementptr i8, ptr %p, i64 %index` where `%index` comes from a PHI, or something like that. We have to add the pointer checks in the loop preheader.

In addition to `Start`, we also need to know the pointer type and the loaded type, which is why I thought it was easier to pass in `LI`. However, I could just collect 3 things instead - `{Start, PtrType, MemType}`. This would be more general than restricting to loads only?

2025-02-13 16:36 UTC, david-arm reviewed
For now, I've changed it so that loop versioning is turned off by default. When the user is confident that MTE compatibility is not required they can enable it manually. In future, it would be good to revisit this because even with MTE we can still vectorise with max vector widths of 16 bytes, and memory tagging is currently only supported in LLVM for Android targets anyway.

2025-02-13 16:36 UTC, david-arm commented on llvm/lib/Transforms/Vectorize/LoopVectorizationLegality.cpp
> +      return false;
Damn, forgot to look at this. I'm not sure to be honest. I thought I'd seen similar checks elsewhere, but I'll take another look.

2025-02-13 16:36 UTC, david-arm commented on llvm/lib/Transforms/Vectorize/LoopVectorize.cpp
> +  }
Done

2025-02-13 16:36 UTC, david-arm commented on llvm/lib/Transforms/Vectorize/LoopVectorize.cpp
> +}
Yeah, I think in an early version of the patch I required getMaxVScale for something, but never moved it. Anyway, it's back in it's original place now!

2025-02-13 16:36 UTC, david-arm commented on llvm/lib/Transforms/Vectorize/LoopVectorizationLegality.cpp
> +      reportVectorizationFailure(
I've just removed `isDereferenceableReadOnlyLoop` now and inlined some of the logic into the loop above.

2025-02-13 16:36 UTC, david-arm commented on llvm/lib/Transforms/Vectorize/LoopVectorize.cpp
> +               "potentially faulting loads");
I've updated the code to handle interleaving, although we can't currently test it when IC > 1. However, it seems trivial/obvious enough that it should work.

2025-02-13 16:36 UTC, david-arm commented on llvm/lib/Analysis/Loads.cpp
> +        Result = false;
Done

2025-02-13 16:36 UTC, david-arm commented on llvm/lib/Transforms/Vectorize/LoopVectorizationLegality.cpp
> +    PotentiallyFaultingLoads.push_back({LI, Start});
I've changed the list to now only require `Start` and the load type.

2025-02-13 16:36 UTC, david-arm commented on llvm/lib/Transforms/Vectorize/LoopVectorize.cpp
> +  }
Done

2025-02-13 20:28 UTC, fhahn reviewed
> This is something I'll look into - perhaps the worst case for now would be that loop versioning is off by default for AArch64 and would have to be enabled explicitly with a flag. Without digging into this in huge detail, is it possible that if MTE is a problem for this PR, then we also have a problem today in the loop vectoriser when we if-convert loads into unconditional loads based upon the result of `isDereferenceableAndAlignedInLoop` - see `LoopVectorizationLegality::canVectorizeWithIfConvert`. MTE can be used for stack tagging.

IIRC `isDereferenceableAndAlignedInLoop` determines dereferenceability separately from either attributes or known allocation sizes, so it should never return true if we could access out-of-bounds I think. I am not sure how the current uses would cause problems with extensions like MTE, is there any particular issue you are thinking about?

2025-02-13 20:28 UTC, fhahn commented on llvm/include/llvm/Transforms/Vectorize/LoopVectorizationLegality.h
> +    return &PotentiallyFaultingPtrs;
Can we just return an `ArrayRef` here, or do we need to return a pointer

2025-02-13 20:28 UTC, fhahn commented on llvm/include/llvm/Transforms/Vectorize/LoopVectorizationLegality.h
> +  bool analyzePotentiallyFaultingLoads(SmallVectorImpl<LoadInst *> *Loads);
Can pass by reference?

2025-02-13 20:28 UTC, fhahn commented on llvm/lib/Transforms/Vectorize/LoopVectorizationLegality.cpp
> +      return false;
It should always return a valid value.

2025-02-13 20:28 UTC, fhahn commented on llvm/lib/Transforms/Vectorize/LoopVectorize.cpp
> +    PSE.addPredicate(*(SE->getEqualPredicate(Rem, SE->getZero(PtrIntType))));
```suggestion
    PSE.addPredicate(*SE->getEqualPredicate(Rem, SE->getZero(PtrIntType)));
```

2025-02-13 20:28 UTC, fhahn commented on llvm/lib/Transforms/Vectorize/LoopVectorize.cpp
> +    const SmallVectorImpl<std::pair<const SCEV *, Type *>> *Ptrs, Function *F,
```suggestion
    ArrayRefl<std::pair<const SCEV *, Type *> Ptrs, Function *F,
```

2025-02-13 20:28 UTC, fhahn commented on llvm/lib/Transforms/Vectorize/LoopVectorizationLegality.cpp
> +    if (!AR || AR->getLoop() != TheLoop || !AR->isAffine())
Would be good to explain here that we check for add-recs because the reasoning is only safe if the load executes at least once?

We should probably also restrict this just for loads from the default address space (0) for now

2025-02-18 13:43 UTC, nikic requested changes
Do I understand correctly that this is generating out-of-bounds loads and relying on page granularity to guarantee they don't trap? If so, we cannot perform this transform with normal loads, because it is UB at the IR level -- the behavior of the underlying hardware is irrelevant.

You're going to need a new load intrinsic to support this. I have this RFC draft on the topic lying around: https://hackmd.io/-vd6H5YIQHimAiJKXpOjVA I haven't submitted it, because I'm not particularly happy with the `%defined_size` parameter, which is needed to specify the operational semantics of the intrinsic, but not relevant for lowering.

2025-02-18 16:53 UTC, programmerjake commented
I proposed a similar speculative load instruction here: https://discourse.llvm.org/t/rfc-supporting-more-early-exit-loops/84690/2?u=programmerjake

2025-02-21 08:54 UTC, david-arm commented
> For RVV first faulting loads, a VP variant intrinsic could support this, for example `declare { <8 x i8>, i32 } @llvm.vp.load.ff.v8i8.p0(ptr %ptr, <8 x i1> %mask, i32 %evl)`. It differs by returning a structure that includes both the loaded data and latest EVL.

This patch is explicitly avoiding using first faulting loads, by relying upon a combination of vector load alignment and knowledge of the hardware minimum page size. I believe @huntergr-arm recently created a RFC about an alternative approach using first faulting loads to vectorise more complex loops involving multiple exits and/or stores in the loop.

If I understand correctly, the point raised by @nikic is that the semantics of the IR load operation mean that if any portion of the vector load is out-of-bounds (even though we know it won't fault) then the entire load is UB. This essentially means the entire vectorised loop becomes UB and so in theory could be optimised away, even if in practice for existing tests and benchmark it works. Using a new out-of-bounds load intrinsic with different semantics avoids this problem, and still allows us to achieve the best performance.

2025-02-21 11:30 UTC, david-arm commented
Hi @nikic, just for my own understanding can you point me to the part of the LangRef that says out-of-bounds loads are UB? Perhaps I'm missing something, but I did have a look and it wasn't immediately obvious to me where this is stated.

2025-02-23 21:13 UTC, fhahn commented
> Hi @nikic, just for my own understanding can you point me to the part of the LangRef that says out-of-bounds loads are UB? Perhaps I'm missing something, but I did have a look and it wasn't immediately obvious to me where this is stated.

This was my understanding as well, but I also couldn't find a clear reference from LangRef. Put up https://github.com/llvm/llvm-project/pull/128429 to clarify

2025-02-24 10:55 UTC, david-arm reviewed
Updated the patch to deal with review comments and also fix a bug I spotted where I treated loads as being unconditionally dereferenceable after the early exit - see the new test `same_exit_block_no_live_outs_faulting_load_after_early_exit`. This is not true because the first lane of the vector load could be faulting, which would not have happened with the scalar loop.

2025-02-24 10:55 UTC, david-arm commented on llvm/lib/Transforms/Vectorize/LoopVectorizationLegality.cpp
> +    if (!AR || AR->getLoop() != TheLoop || !AR->isAffine())
Done

2025-02-24 10:55 UTC, david-arm commented on llvm/include/llvm/Transforms/Vectorize/LoopVectorizationLegality.h
> +    return &PotentiallyFaultingPtrs;
Done

2025-02-24 10:55 UTC, david-arm commented on llvm/include/llvm/Transforms/Vectorize/LoopVectorizationLegality.h
> +  bool analyzePotentiallyFaultingLoads(SmallVectorImpl<LoadInst *> *Loads);
Done

2025-02-24 10:55 UTC, david-arm commented on llvm/lib/Transforms/Vectorize/LoopVectorize.cpp
> +    PSE.addPredicate(*(SE->getEqualPredicate(Rem, SE->getZero(PtrIntType))));
Done

2025-02-24 10:55 UTC, david-arm commented on llvm/lib/Transforms/Vectorize/LoopVectorize.cpp
> +    const SmallVectorImpl<std::pair<const SCEV *, Type *>> *Ptrs, Function *F,
Done

2025-11-28 16:41 UTC, closed without merging

2026-02-04 11:14 UTC, fhahn commented
> Do I understand correctly that this is generating out-of-bounds loads and relying on page granularity to guarantee they don't trap? If so, we cannot perform this transform with normal loads, because it is UB at the IR level -- the behavior of the underlying hardware is irrelevant.
> 
> You're going to need a new load intrinsic to support this. I have this RFC draft on the topic lying around: https://hackmd.io/@nikic/S1O4QWYZkx I haven't submitted it, because I'm not particularly happy with the `%defined_size` parameter, which is needed to specify the operational semantics of the intrinsic, but not relevant for lowering.

I took a stab at a definition of a speculative load intrinsic (name subject to change): https://github.com/llvm/llvm-project/pull/179642

Instead of using `%defined_size` , it defines it to load the stored value for bytes in bounds, and undef otherwise. I don't think we could easily compute `%defined_size`, as it would depend on the load values, i.e. which lane would take an early exit.