[BoundsSafety][Doc] Add BoundsSafetyAdoptionGuide.rst
llvm/llvm-project pull request #120674
Opened 2024-12-20 03:27 UTC by rapidsna

This adds an instruction to adopt `-fbounds-safety` using the preview implementation available in the fork of llvm-project.

2024-12-20 11:09 UTC, hnrklssn commented
Given the number of small changes that need to be made, I think it's worth mentioning that fix-its exist and how their fixes can be applied, since that's not always obvious when building in the terminal. Perhaps we also want to mention that we'd appreciate reports of snippets that compile without errors but are optimised to unconditional traps?

2024-12-22 22:09 UTC, rapidsna commented
> Given the number of small changes that need to be made, I think it's worth mentioning that fix-its exist and how their fixes can be applied, since that's not always obvious when building in the terminal. Perhaps we also want to mention that we'd appreciate reports of snippets that compile without errors but are optimised to unconditional traps?

Sounds good. Let's add those in a follow up since we also need to add debugger support.

2025-01-14 23:38 UTC, hnrklssn approved these changes
If nobody else has any comments, I'd say LGTM

2025-01-16 02:14 UTC, delcypher requested changes
Seems reasonable and something we can expand on. The main issue is the fact `-fbounds-safety` is a cc1 option while this doc is written assuming its a driver option.

2025-01-16 02:14 UTC, delcypher commented on clang/docs/BoundsSafetyAdoptionGuide.rst
> +Pass ``-fbounds-safety`` as a Clang compilation flag for the C file that you
@rapidsna I thought `-fbound-safety` was broken in open source? I thought people needed to do `-Xclang -fbounds-safety`.. or something like that?

2025-01-16 02:14 UTC, delcypher commented on clang/docs/BoundsSafetyAdoptionGuide.rst
> +Annotate pointers on struct fields and function parameters if they are pointing
Nit: They might need to annotate globals and local variables too.

2025-01-16 02:14 UTC, delcypher commented on clang/docs/BoundsSafetyAdoptionGuide.rst
> +Once you pass ``-fbounds-safety`` to compiler a C file, you will see some new
```suggestion
Once you pass ``-Xclang -fbounds-safety`` to compiler C file, you will see some new
```

2025-01-16 02:14 UTC, delcypher commented on clang/docs/BoundsSafetyAdoptionGuide.rst
> +Pass ``-fbounds-safety`` as a Clang compilation flag for the C file that you
```suggestion
Pass ``-Xclang -fbounds-safety`` as a Clang compilation flag for the C file that you
```

2025-01-16 02:14 UTC, delcypher commented on clang/docs/BoundsSafetyAdoptionGuide.rst
> +to remove unsafeness in the code. Consider the following example:
```suggestion
compiler warnings and errors, which guide adoption of `-fbounds-safety`. Consider the following example:
```

2025-01-16 02:14 UTC, delcypher commented on clang/docs/BoundsSafetyAdoptionGuide.rst
> +complain about the code indexing into it (``p[i]``). To address the diagnostics,
Nit: Maybe note that the compiler assumes it points to a 0 or 1 `int` objects by default?

2025-01-16 02:14 UTC, delcypher commented on clang/docs/BoundsSafetyAdoptionGuide.rst
> +Run unit tests to fix new run-time traps
```suggestion
Run test suites to fix new run-time traps
```

2025-01-16 02:14 UTC, delcypher commented on clang/docs/BoundsSafetyAdoptionGuide.rst
> +bounds safety or it has incorrect adoption.
```suggestion
bounds safety or it has incorrect adoption. Thus it is necessary to perform runtime testing of your program to gain confidence that it won't trap at runtime.
```

2025-01-16 02:20 UTC, rapidsna commented on clang/docs/BoundsSafetyAdoptionGuide.rst
> +Pass ``-fbounds-safety`` as a Clang compilation flag for the C file that you
No. `-fbounds-safety` is available as a driver in the preview implementation I pointed out.

2025-01-16 02:22 UTC, rapidsna commented on clang/docs/BoundsSafetyAdoptionGuide.rst
> +Pass ``-fbounds-safety`` as a Clang compilation flag for the C file that you
Note that the purpose of this document is to instruct people on how to use the preview implementation.

2025-01-22 23:41 UTC, merged