[SelectionDAG] Split <n x T> vector types for atomic load
llvm/llvm-project pull request #120640
Opened 2024-12-19 21:28 UTC by jofrn

`load atomic <n x T>` is not valid. This change splits
vector types of atomic load in SelectionDAG
so that it can translate vectors of >1 size with type bfloat,half.

---

**Stack**:
- #120640 ⬅
- #120598
- #120387
- #120386
- #120385
- #120384

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

2024-12-20 12:50 UTC, arsenm commented on llvm/lib/CodeGen/SelectionDAG/LegalizeVectorTypes.cpp
> +    SplitVecRes_ATOMIC_LOAD(cast<AtomicSDNode>(N), Lo, Hi);
This is not a valid legalization. This should be coerced to an equivalent width integer as a default action

2025-01-06 20:08 UTC, jofrn commented on llvm/lib/CodeGen/SelectionDAG/LegalizeVectorTypes.cpp
> +    SplitVecRes_ATOMIC_LOAD(cast<AtomicSDNode>(N), Lo, Hi);
After trying to coerce them via `addRegisterClass` and `setOperationPromotedToType`, it changes the what the DAG can match on, for example a non-atomic load with type `<2 x half>` is affected; so to avoid this and make the splitting valid, it now builds a vector out of the elements that are split.

2025-01-08 16:11 UTC, arsenm requested changes

2025-01-08 16:11 UTC, arsenm commented on llvm/lib/CodeGen/SelectionDAG/LegalizeVectorTypes.cpp
> +  Lo = DAG.getAtomic(ISD::ATOMIC_LOAD, dl, LoMemVT, LoMemVT, Ch, Ptr,
Title should also not say split, this is forcing the type to a legal integer

2025-01-22 05:58 UTC, arsenm requested changes

2025-01-22 05:58 UTC, arsenm commented on llvm/lib/CodeGen/SelectionDAG/LegalizeVectorTypes.cpp
> +  SDValue Concat = DAG.getNode(ISD::CONCAT_VECTORS, dl, MemoryVT, Ops);
I don't think using CONCAT_VECTORS with 2 scale elements is valid. This should be setting the Lo and Hi fields like the other SplitVecRes_* functions do anyway, and not doing manual replacement. Here will need to do manual replacement of the load chain though

2025-01-22 05:58 UTC, arsenm commented on llvm/lib/CodeGen/SelectionDAG/LegalizeVectorTypes.cpp
> +  EVT IntMemoryVT = EVT::getVectorVT(*DAG.getContext(), MVT::i16, NumElts);
Shouldn't be assuming the type. This still should follow allow with SplitVecRes_LOAD, by using GetSplitDestVTs

2025-01-22 05:58 UTC, arsenm commented on llvm/lib/CodeGen/SelectionDAG/SelectionDAG.cpp
> +bool SelectionDAG::areNonVolatileConsecutiveLoads(AtomicSDNode *LD,
Unused? This is also just duplicated the non-load function (we should also just finish the project to remove ATOMIC_LOAD)

2025-01-22 05:58 UTC, arsenm commented on llvm/lib/CodeGen/SelectionDAG/SelectionDAGAddressAnalysis.cpp
> +static BaseIndexOffset matchSDNode(const T *N,
Unrelated change

2025-01-22 05:58 UTC, arsenm commented on llvm/lib/CodeGen/SelectionDAG/SelectionDAGBuilder.cpp
> +
Shouldn't need to touch this

2025-01-22 05:58 UTC, arsenm commented on llvm/lib/Target/X86/X86ISelLowering.cpp
> +static bool findEltLoadSrc(SDValue Elt, T *&Ld, int64_t &ByteOffset) {
Shouldn't need to touch this

2025-01-22 09:03 UTC, jofrn commented on llvm/lib/CodeGen/SelectionDAG/SelectionDAGBuilder.cpp
> +
It is here so that the elements are vectorized later in EltsFromConsecutiveLoads. Without this here, it will need to check the chain differently in EltsFromConsecutiveLoads based on being an Atomic or not in order to vectorize.

2025-01-22 09:06 UTC, jofrn commented on llvm/lib/CodeGen/SelectionDAG/SelectionDAGAddressAnalysis.cpp
> +static BaseIndexOffset matchSDNode(const T *N,
Without this, the split elements are not identified, and we end up having codegen emit extra moves for each element even though they are not used.

2025-01-22 09:09 UTC, arsenm commented on llvm/lib/CodeGen/SelectionDAG/SelectionDAGBuilder.cpp
> +
Atomics cannot be vectorized, so I don't understand. No matter what, this does not belong in this patch

2025-01-22 09:32 UTC, jofrn commented on llvm/lib/CodeGen/SelectionDAG/LegalizeVectorTypes.cpp
> +  SDValue Concat = DAG.getNode(ISD::CONCAT_VECTORS, dl, MemoryVT, Ops);
```
t21: v2i16,ch = AtomicLoad<(load acquire (s32) from %ir.x)> t0, t2
      t23: i16 = extract_vector_elt t21, Constant:i64<0>
    t24: v1bf16 = bitcast t23
      t26: i16 = extract_vector_elt t21, Constant:i64<1>
    t27: v1bf16 = bitcast t26
  t28: v2bf16 = concat_vectors t24, t27
t4: v2f16 = bitcast t28
```
In this way, if t4 is consumed by another concat_vectors, then they can all be combined via EltsFromConsecutiveLoads into a BUILD_VECTOR.

2025-01-22 09:35 UTC, jofrn commented on llvm/lib/CodeGen/SelectionDAG/SelectionDAGAddressAnalysis.cpp
> +static BaseIndexOffset matchSDNode(const T *N,
We had the Widening patch add in the mov optimization (with the .td records). The same thing is happening here. It just requires more work. If we don't add in the optimization here, the tests will have extra movs for this patch.

2025-01-22 09:36 UTC, jofrn commented on llvm/lib/CodeGen/SelectionDAG/SelectionDAGBuilder.cpp
> +
The elements of the atomic can be vectorized though. After splitting, we have each individual element, and EltsFromConsecutiveLoads ensures that unused elements are not emitted as movs.

2025-01-22 09:44 UTC, jofrn commented on llvm/lib/CodeGen/SelectionDAG/LegalizeVectorTypes.cpp
> +  EVT IntMemoryVT = EVT::getVectorVT(*DAG.getContext(), MVT::i16, NumElts);
This is where the type is coerced so that we load integers. It didn't seem appropriate to split into Lo and Hi here since atomics are different. GetSplitDestVTs will return floats when given a float, but we do not want to load from those (so as to reuse infrastructure), and we want to load the full size at once (not with a split size).

2025-01-24 06:00 UTC, arsenm commented on llvm/lib/CodeGen/SelectionDAG/SelectionDAGAddressAnalysis.cpp
> +static BaseIndexOffset matchSDNode(const T *N,
That's fine, the optimization can be another PR

2025-01-24 06:01 UTC, arsenm commented on llvm/lib/CodeGen/SelectionDAG/LegalizeVectorTypes.cpp
> +  SDValue Concat = DAG.getNode(ISD::CONCAT_VECTORS, dl, MemoryVT, Ops);
I'd consider this a bug, I would expect this to assert in getNode

2025-01-29 14:32 UTC, jofrn commented on llvm/lib/CodeGen/SelectionDAG/SelectionDAG.cpp
> +bool SelectionDAG::areNonVolatileConsecutiveLoads(AtomicSDNode *LD,
It is used within `EltsFromConsecutiveLoads`. I'll rewrite it to avoid the duplication.

2025-01-29 14:34 UTC, jofrn commented on llvm/lib/Target/X86/X86ISelLowering.cpp
> +static bool findEltLoadSrc(SDValue Elt, T *&Ld, int64_t &ByteOffset) {
Yes, that's should be possible. Trying it out. (Need to ensure we do not combine consecutive elements that are not all atomic or all non-atomic.) With the templates, this happens naturally.

2025-03-04 04:43 UTC, arsenm commented on llvm/lib/CodeGen/SelectionDAG/LegalizeVectorTypes.cpp
> +void DAGTypeLegalizer::SplitVecRes_ATOMIC_LOAD(AtomicSDNode *LD) {
This is missing the Lo / Hi out arguments, like all of the other SplitVecRes cases. You should still be trying to respect the result of DAG.GetSplitDestVTs. With this you are bypassing SetSplitVector

2025-03-04 04:43 UTC, arsenm commented on llvm/lib/CodeGen/SelectionDAG/LegalizeVectorTypes.cpp
> +  SmallVector<SDValue, 4> Ops;
This loop can be replaced with DAG.ExtractVectorElements (but I don't think you should be scalarizing here like this)

2025-04-25 22:12 UTC, arsenm commented on llvm/lib/CodeGen/SelectionDAG/LegalizeVectorTypes.cpp
> +void DAGTypeLegalizer::SplitVecRes_ATOMIC_LOAD(AtomicSDNode *LD) {
Bump

2025-04-28 16:10 UTC, jofrn commented on llvm/lib/CodeGen/SelectionDAG/LegalizeVectorTypes.cpp
> +void DAGTypeLegalizer::SplitVecRes_ATOMIC_LOAD(AtomicSDNode *LD) {
I had tried doing it by splitting Lo and Hi. I ran into an issue though because TokenFactor (what we join our values on) requires glue operands; however, EXTRACT_SUBVECTOR does not have these, nor does DAG.getAtomicLoad.

2025-05-01 07:45 UTC, arsenm commented on llvm/lib/CodeGen/SelectionDAG/LegalizeVectorTypes.cpp
> +void DAGTypeLegalizer::SplitVecRes_ATOMIC_LOAD(AtomicSDNode *LD) {
TokenFactor does not require glue operands. The most common use case for TokenFactor is pairing a modified real value with a chain

2025-05-01 07:50 UTC, arsenm commented on llvm/lib/CodeGen/SelectionDAG/LegalizeVectorTypes.cpp
> +  ReplaceValueWith(SDValue(LD, 0), Concat);
You don't need to associate the Hi and Lo halves, you need to report the Hi and Lo halves to the caller. The only special thing you need to do here is replace the chain uses, as is done in the non-atomic load case

2025-05-01 13:17 UTC, jofrn commented on llvm/lib/CodeGen/SelectionDAG/LegalizeVectorTypes.cpp
> +  ReplaceValueWith(SDValue(LD, 0), Concat);
How do you associate both chain uses at once? Doesn't that require a TokenFactor?

2025-05-01 13:20 UTC, jofrn commented on llvm/lib/CodeGen/SelectionDAG/LegalizeVectorTypes.cpp
> +void DAGTypeLegalizer::SplitVecRes_ATOMIC_LOAD(AtomicSDNode *LD) {
EXTRACT_SUBVECTOR does not have chain operands, nor does DAG.getAtomicLoad. I checked a few others too, but do we not need to use a TokenFactor if you are saying we do not have to associate them?

2025-05-01 14:18 UTC, jofrn commented on llvm/lib/CodeGen/SelectionDAG/LegalizeVectorTypes.cpp
> +  ReplaceValueWith(SDValue(LD, 0), Concat);
I'm talking about chain uses of Lo and Hi. The atomic_load lowering contains this, which looks to be associating the values:

`  Ch = DAG.getNode(ISD::TokenFactor, dl, MVT::Other, Lo.getValue(1),
                   Hi.getValue(1));`

However, Lo and Hi are uses from getLoad/getAtomicLoad, but getAtomicLoad does not have the chain that TokenFactor wants.

2025-05-01 14:34 UTC, arsenm commented on llvm/lib/CodeGen/SelectionDAG/LegalizeVectorTypes.cpp
> +  ReplaceValueWith(SDValue(LD, 0), Concat);
TokenFactor of a single input is identical to the single input value. But the atomic_load lowering should not contain this. The new lowering has exactly one chain as the original load. The atomic_load is specifically not being split, only the type profile is changing

2025-05-05 18:02 UTC, arsenm commented on llvm/lib/CodeGen/SelectionDAG/LegalizeVectorTypes.cpp
> +  std::tie(LoMemVT, HiMemVT) = DAG.GetSplitDestVTs(MemoryVT);
These are unused. You at most should be bit casting the in memory type to the target integer memory type, there's no splitting

2025-05-05 18:02 UTC, arsenm commented on llvm/lib/CodeGen/SelectionDAG/LegalizeVectorTypes.cpp
> +                                  LD->getMemOperand());
Maybe should assert this isn't an extending load, although you could in principle handle it

2025-05-05 18:02 UTC, arsenm commented on llvm/lib/CodeGen/SelectionDAG/LegalizeVectorTypes.cpp
> +                                  DAG.getVectorIdxConstant(0, dl));
This isn't a vector extract, so don't use getVectorIdxConstant. I'm not actually sure what the type for the second operand is supposed to be for extract_element

2025-05-06 04:09 UTC, jofrn commented on llvm/lib/CodeGen/SelectionDAG/LegalizeVectorTypes.cpp
> +                                  LD->getMemOperand());
This will fail for some reason, on at least atomic_vec2_ptr270 and atomic_vec2_half.

2025-05-06 06:38 UTC, jofrn commented on llvm/lib/CodeGen/SelectionDAG/LegalizeVectorTypes.cpp
> +  std::tie(LoMemVT, HiMemVT) = DAG.GetSplitDestVTs(MemoryVT);
Only one has to be used to get double that size. May we just remove it all and use `MemoryVT.getSizeInBits()`?

2025-05-06 09:27 UTC, arsenm commented on llvm/lib/CodeGen/SelectionDAG/LegalizeVectorTypes.cpp
> +  std::tie(LoMemVT, HiMemVT) = DAG.GetSplitDestVTs(MemoryVT);
Yes

2025-05-06 09:29 UTC, arsenm commented on llvm/lib/CodeGen/SelectionDAG/LegalizeVectorTypes.cpp
> +                                  DAG.getIntPtrConstant(0, dl));
This probably should be a target constant but this appears to be what existing uses do

2025-05-06 17:31 UTC, arsenm commented on llvm/lib/CodeGen/SelectionDAG/LegalizeVectorTypes.cpp
> +      EVT::getIntegerVT(*DAG.getContext(), 2 * LoMemVT.getSizeInBits());
MemVT should not be a derived quantity, directly bitcast the original memory type

2025-05-08 09:36 UTC, arsenm commented on llvm/lib/CodeGen/SelectionDAG/LegalizeVectorTypes.cpp
> +                                  LD->getMemOperand());
As written this is not going to handle extending loads correctly. I also don't know how you could end up with a vector extending load with the code as it is now. You should either try to handle it, or assert and figure out where it is coming from

2025-06-01 20:46 UTC, jofrn commented
Closing pull request: commit has gone away

2025-06-01 20:46 UTC, closed without merging