[compiler-rt][test] Apply CFLAGS from sanitizer_common to all tests
llvm/llvm-project pull request #120798
Opened 2024-12-20 21:44 UTC by aaronpuchert

Sanitizer-specific tests don't use the sanitizer_common flags, but the issues they address probably also apply to the individual sanitizers.

This was observed in #119071: moving a test from sanitizer_common to msan broke it in builds with CMAKE_SYSROOT set, because the --sysroot argument was no longer applied to the test.

2024-12-20 21:54 UTC, aaronpuchert commented
@nico or @alanzhao1: could you test this together with #119071 relanded? Does that solve the issue (and not create new issues)?

2025-03-09 03:01 UTC, vitalybuka commented on compiler-rt/cmake/config-ix.cmake
> +      list(APPEND ${cflags_out} -funwind-tables)
how bad to make it non-arm specific?

2025-03-09 03:05 UTC, vitalybuka commented on compiler-rt/cmake/config-ix.cmake
> +      list(APPEND ${cflags_out} -funwind-tables)
Actually arm should end up with line 303 version?

2025-03-09 03:14 UTC, vitalybuka requested changes
I suspect new code needs to be outside of 
"if(ANDROID OR (NOT APPLE AND ${arch} MATCHES "arm|aarch64|riscv32|riscv64"))"

2025-05-06 22:01 UTC, aaronpuchert commented on compiler-rt/cmake/config-ix.cmake
> +      list(APPEND ${cflags_out} -funwind-tables)
The old code applied these flags for non-Android Linux. Here we're on non-Android Linux, except where `${arch} MATCHES "arm|aarch64|riscv32|riscv64"`. I don't know why "this is only true if we are cross-compiling" as the comment says. There are [actual CMake variables](https://cmake.org/cmake/help/latest/variable/CMAKE_CROSSCOMPILING.html) to detect cross-compiles, and I don't see why you couldn't build all of LLVM on these arches directly. So I think this might be wrong, but I'm also afraid to fix it.

The issue was reported on x86, but I guess it could also appear on other architectures if they're built with a sysroot and no cross toolchain.

2025-05-06 22:12 UTC, aaronpuchert commented on compiler-rt/cmake/config-ix.cmake
> +      list(APPEND ${cflags_out} -funwind-tables)
We do it right in [compiler-rt/CMakeLists.txt](https://github.com/llvm/llvm-project/blob/main/compiler-rt/CMakeLists.txt):
```cmake
# We support running instrumented tests when we're not cross-compiling
# and target a UNIX-like system or Windows.
# We can run tests on Android even when we are cross-compiling.
if((NOT "${CMAKE_CROSSCOMPILING}" AND (UNIX OR WIN32))
   OR ANDROID OR COMPILER_RT_EMULATOR)
  option(COMPILER_RT_CAN_EXECUTE_TESTS "Can we execute instrumented tests" ON)
else()
  option(COMPILER_RT_CAN_EXECUTE_TESTS "Can we execute instrumented tests" OFF)
endif()
```

2025-05-06 22:35 UTC, aaronpuchert commented on compiler-rt/cmake/config-ix.cmake
> +      list(APPEND ${cflags_out} -funwind-tables)
"Android is always cross-compiling" was introduced in aa9d74cc5db8c2a16c2cd39bfb7e501ca1bb7c72, while for non-Android it seems to have been copied over in 6759fd9fdd3c9d49c8aaf64626d5a8c59648ed10. Then other architectures were added later, and there were refactorings, and so on.

2025-05-06 23:27 UTC, aaronpuchert commented on compiler-rt/cmake/config-ix.cmake
> +      list(APPEND ${cflags_out} -funwind-tables)
However, I think my points are unrelated and I should put the flags after the `if` anyway, as you suggested.

2025-05-07 00:10 UTC, vitalybuka approved these changes

2025-05-07 09:36 UTC, aaronpuchert commented
I've not changed anything about when `-funwind-tables` is applied, this is just moving the flags to apply to all tests. (All that use this function.)

2025-08-04 20:39 UTC, merged

2025-08-05 14:35 UTC, gulfemsavrun commented
We started seeing a test failure after this patch in our toolchain builders:
```
FAIL: AddressSanitizer-x86_64-linux-dynamic :: TestCases/Linux/global-overflow-bfd.cpp (954 of 17470)
******************** TEST 'AddressSanitizer-x86_64-linux-dynamic :: TestCases/Linux/global-overflow-bfd.cpp' FAILED ********************
Exit Code: 1

Command Output (stderr):
--
/b/s/w/ir/x/w/llvm_build/./bin/clang  --driver-mode=g++ -fsanitize=address -mno-omit-leaf-frame-pointer -fno-omit-frame-pointer -fno-optimize-sibling-calls -gline-tables-only   -funwind-tables --sysroot=/b/s/w/ir/x/w/cipd/linux  -shared-libasan -fuse-ld=bfd -Wl,-gc-sections -ffunction-sections -fdata-sections -O0 /b/s/w/ir/x/w/llvm-llvm-project/compiler-rt/test/asan/TestCases/Linux/global-overflow-bfd.cpp -o /b/s/w/ir/x/w/llvm_build/runtimes/runtimes-x86_64-unknown-linux-gnu-bins/compiler-rt/test/asan/X86_64LinuxDynamicConfig/TestCases/Linux/Output/global-overflow-bfd.cpp.tmp && not  /b/s/w/ir/x/w/llvm_build/runtimes/runtimes-x86_64-unknown-linux-gnu-bins/compiler-rt/test/asan/X86_64LinuxDynamicConfig/TestCases/Linux/Output/global-overflow-bfd.cpp.tmp 2>&1 | FileCheck /b/s/w/ir/x/w/llvm-llvm-project/compiler-rt/test/asan/TestCases/Linux/global-overflow-bfd.cpp # RUN: at line 3
+ /b/s/w/ir/x/w/llvm_build/./bin/clang --driver-mode=g++ -fsanitize=address -mno-omit-leaf-frame-pointer -fno-omit-frame-pointer -fno-optimize-sibling-calls -gline-tables-only -funwind-tables --sysroot=/b/s/w/ir/x/w/cipd/linux -shared-libasan -fuse-ld=bfd -Wl,-gc-sections -ffunction-sections -fdata-sections -O0 /b/s/w/ir/x/w/llvm-llvm-project/compiler-rt/test/asan/TestCases/Linux/global-overflow-bfd.cpp -o /b/s/w/ir/x/w/llvm_build/runtimes/runtimes-x86_64-unknown-linux-gnu-bins/compiler-rt/test/asan/X86_64LinuxDynamicConfig/TestCases/Linux/Output/global-overflow-bfd.cpp.tmp
/b/s/w/ir/x/w/cipd/binutils-gdb/bin/ld.bfd: warning: libdl.so.2, needed by /b/s/w/ir/x/w/llvm_build/lib/clang/22/lib/x86_64-unknown-linux-gnu/libclang_rt.asan.so, not found (try using -rpath or -rpath-link)
/b/s/w/ir/x/w/cipd/binutils-gdb/bin/ld.bfd: warning: librt.so.1, needed by /b/s/w/ir/x/w/llvm_build/lib/clang/22/lib/x86_64-unknown-linux-gnu/libclang_rt.asan.so, not found (try using -rpath or -rpath-link)
/b/s/w/ir/x/w/cipd/binutils-gdb/bin/ld.bfd: warning: libpthread.so.0, needed by /b/s/w/ir/x/w/llvm_build/lib/clang/22/lib/x86_64-unknown-linux-gnu/libclang_rt.asan.so, not found (try using -rpath or -rpath-link)
/b/s/w/ir/x/w/cipd/binutils-gdb/bin/ld.bfd: /b/s/w/ir/x/w/llvm_build/lib/clang/22/lib/x86_64-unknown-linux-gnu/libclang_rt.asan.so: undefined reference to `pthread_setspecific@GLIBC_2.2.5'
/b/s/w/ir/x/w/cipd/binutils-gdb/bin/ld.bfd: /b/s/w/ir/x/w/llvm_build/lib/clang/22/lib/x86_64-unknown-linux-gnu/libclang_rt.asan.so: undefined reference to `pthread_rwlock_rdlock@GLIBC_2.2.5'
/b/s/w/ir/x/w/cipd/binutils-gdb/bin/ld.bfd: /b/s/w/ir/x/w/llvm_build/lib/clang/22/lib/x86_64-unknown-linux-gnu/libclang_rt.asan.so: undefined reference to `pthread_getspecific@GLIBC_2.2.5'
/b/s/w/ir/x/w/cipd/binutils-gdb/bin/ld.bfd: /b/s/w/ir/x/w/llvm_build/lib/clang/22/lib/x86_64-unknown-linux-gnu/libclang_rt.asan.so: undefined reference to `dlvsym@GLIBC_2.2.5'
/b/s/w/ir/x/w/cipd/binutils-gdb/bin/ld.bfd: /b/s/w/ir/x/w/llvm_build/lib/clang/22/lib/x86_64-unknown-linux-gnu/libclang_rt.asan.so: undefined reference to `pthread_key_create@GLIBC_2.2.5'
/b/s/w/ir/x/w/cipd/binutils-gdb/bin/ld.bfd: /b/s/w/ir/x/w/llvm_build/lib/clang/22/lib/x86_64-unknown-linux-gnu/libclang_rt.asan.so: undefined reference to `dladdr@GLIBC_2.2.5'
/b/s/w/ir/x/w/cipd/binutils-gdb/bin/ld.bfd: /b/s/w/ir/x/w/llvm_build/lib/clang/22/lib/x86_64-unknown-linux-gnu/libclang_rt.asan.so: undefined reference to `pthread_rwlock_unlock@GLIBC_2.2.5'
/b/s/w/ir/x/w/cipd/binutils-gdb/bin/ld.bfd: /b/s/w/ir/x/w/llvm_build/lib/clang/22/lib/x86_64-unknown-linux-gnu/libclang_rt.asan.so: undefined reference to `dlsym@GLIBC_2.2.5'
/b/s/w/ir/x/w/cipd/binutils-gdb/bin/ld.bfd: /b/s/w/ir/x/w/llvm_build/lib/clang/22/lib/x86_64-unknown-linux-gnu/libclang_rt.asan.so: undefined reference to `pthread_getattr_np@GLIBC_2.2.5'
/b/s/w/ir/x/w/cipd/binutils-gdb/bin/ld.bfd: /b/s/w/ir/x/w/llvm_build/lib/clang/22/lib/x86_64-unknown-linux-gnu/libclang_rt.asan.so: undefined reference to `pthread_attr_setstacksize@GLIBC_2.2.5'
/b/s/w/ir/x/w/cipd/binutils-gdb/bin/ld.bfd: /b/s/w/ir/x/w/llvm_build/lib/clang/22/lib/x86_64-unknown-linux-gnu/libclang_rt.asan.so: undefined reference to `pthread_rwlock_wrlock@GLIBC_2.2.5'
clang: error: linker command failed with exit code 1 (use -v to see invocation)

--
```
https://luci-milo.appspot.com/ui/p/fuchsia/builders/toolchain.ci/clang-linux-x64/b8707434189452310849/overview

2025-08-06 12:40 UTC, aaronpuchert commented
@gulfemsavrun, can you explain how this impacts your build configuration? Do you use `CMAKE_SYSROOT`? I don't see any in the log, so I presume not? So I wonder what changed here.

As a side note, it's really annoying that whatever I do in `compiler-rt`, I get my change reverted by Google because it breaks some obscure build configuration that is not covered by the build bots. This change is already trying to fix an issue that caused a previous revert, and as you can see, I got zero feedback for half a year from the people who reverted my original change. (The change was arguably correct, but `--sysroot` was applied only to some tests, which caused a failure with certain sysroots.)

2025-08-06 12:47 UTC, aaronpuchert commented
Sorry, I must have overlooked it. The log has `--sysroot`.

But is that from `CMAKE_SYSROOT`? Then I wonder where "undefined reference to" is coming from, since the runtime should have been build against the same sysroot.

2025-08-06 13:22 UTC, aaronpuchert commented
In general, I don't know what the desired semantics of `CMAKE_SYSROOT` is. It's currently handled inconsistently, and it seems that Google's builds rely on that inconsistency.
1. It should probably apply to the build of LLVM (+ components) itself.
2. Should it apply to building the tests?
3. Should it apply to running the tests?

The answer to the second question was "sometimes" and I've tried to change it to "always" here. This should fix the issue after #119071, where the sysroot was older, but here it seems like the sysroot is newer? And then we would also need to run the tests against the sysroot? But maybe this is going to break another build, where the sysroot isn't actual meant for running stuff against it?

2025-09-06 16:39 UTC, aaronpuchert commented
This is the only test with sanitizer runtimes and `-fuse-ld=bfd`. The build itself is configured with `-DCMAKE_LINKER=/b/s/w/ir/x/w/cipd/bin/ld.lld`. So maybe `ld.bfd` is just generally unable to find libraries in that setup? Could you check that the sysroot is correctly set up?