[mlir][dataflow] disallow outside use of propagateIfChanged for DataFlowSolver
llvm/llvm-project pull request #120885
Opened 2024-12-22 09:54 UTC by ZenithalHourlyRate

Detailed writeup is in https://github.com/google/heir/issues/1153. See also https://github.com/llvm/llvm-project/pull/120881. In short, `propagateIfChanged` is used outside of the `DataFlowAnalysis` scope, because it is public, but it does not propagate as expected as the `DataFlowSolver` has stopped running.

To solve such misuse, `propagateIfChanged` should be made protected/private.

For downstream users affected by this, to correctly propagate the change, the Analysis should be re-run (check #120881) instead of just a `propagateIfChanged`

The change to `IntegerRangeAnalysis` is just a expansion of the `solver->propagateIfChanged`. The `Lattice` has already been updated by the `join`. Propagation is done by `onUpdate`.

Cc @Mogball for review

2024-12-27 01:08 UTC, Mogball requested changes
Thanks for the PR and I agree that this being a public method is a bit of a footgun. However, directly invoking this method inside other dataflow variables is the intended usage of the method. Do you have a better idea on how an API can be exposed that way? `propagateIfChanged` is supposed to be a shorthand so that users don't forget to check the result of `join`, for example. Maybe it should be marked as `nodiscard`? (Unless it already is...). Alternatively, placing an assert inside `propagateIfChanged` checking that the solver is running might do the trick.

2024-12-27 01:08 UTC, Mogball commented on mlir/lib/Analysis/DataFlow/IntegerRangeAnalysis.cpp
> +  if (!constant) {
This is actually the intended usage of the `propagateIfChanged` method. Data flow variables that depend on each other can issue updates to each other through this method.

2024-12-27 06:16 UTC, ZenithalHourlyRate commented
> Alternatively, placing an assert inside propagateIfChanged checking that the solver is running might do the trick.

Added a `isRunning` flag. It is working but management of that flag should be careful (unset it in each return).

> Do you have a better idea on how an API can be exposed that way? 

I was thinking that adding `propagateIfChanged` to `AnalysisState` so all children `AnalysisState` could access it.  

```cpp

class DataFlowSolver {
  friend class AnalysisState;
};

class AnalysisState {

  // existing API
  virtual void onUpdate(DataFlowSolver *solver) const;

  // NOTE: it is not virtual
  void propagateIfChanged(DataFlowSolver *solver, AnalysisState *state, ChangeResult changed) {
    solver->propagateIfChanged(state, changed);
  }

};

```

2025-01-27 17:27 UTC, Mogball reviewed
Thanks for the ping. I think this looks alright. Just one nit

2025-01-27 17:27 UTC, Mogball commented on mlir/include/mlir/Analysis/DataFlowFramework.h
> +  // The solver is working on the worklist.
```suggestion
  /// The solver is working on the worklist.
```

2025-01-27 17:27 UTC, Mogball commented on mlir/lib/Analysis/DataFlowFramework.cpp
> +  isRunning = true;
You can use `llvm::make_scope_exit` to ensure the flag is reset upon leaving the function

2025-01-28 03:24 UTC, ZenithalHourlyRate commented
Comments addressed.

2025-01-28 03:36 UTC, Mogball approved these changes

2025-01-28 05:32 UTC, merged