[Clang] allow restrict qualifier for array types with pointer types as element types
llvm/llvm-project pull request #120896
Opened 2024-12-22 13:15 UTC by a-tarasyuk

Fixes #92847

---

> Types other than pointer types whose referenced type is an object type and (possibly multi-dimensional) array types with such pointer types as element type shall not be restrict-qualified.

2025-01-13 16:17 UTC, cor3ntin commented
@AaronBallman ping

2025-01-16 23:07 UTC, a-tarasyuk commented
@AaronBallman could you review these changes? thanks

2025-01-21 21:04 UTC, a-tarasyuk commented
@AaronBallman could you review these changes? thanks

2025-01-31 15:05 UTC, AaronBallman reviewed
I believe these changes are correct, but adding a few more folks interested in C to verify because existing compilers definitely disagree: https://godbolt.org/z/1Yb44WP9o

2025-01-31 15:05 UTC, AaronBallman commented on clang/test/Sema/types.c
> +restrict S y;
Can you also add a test for multidimensional arrays, like:
```
typedef int *S[2][2];
restrict S y;
```
and (this should already work because it's adding the restrict to a pointer to an array):
```
typedef int (*S)[2];
restrict S y;
```
and finally, can you add some type verification tests like (for each of the test cases):
```
static_assert(_Generic(typeof(y), int * restrict[2]: 1, default : 0));
```

2025-01-31 18:25 UTC, efriedma-quic commented on clang/lib/Sema/SemaType.cpp
> +        T->isMemberPointerType() || T->isArrayType()) {
Don't you need some kind of recursion to check that the base element type ?  We don't want to allow `typedef int x[2]; typedef x restrict x2;`.  Or `typedef int (*x)(); typedef x x2[2]; typedef x2 restrict x3;`

2025-01-31 23:13 UTC, efriedma-quic commented on clang/lib/Sema/SemaType.cpp
> +        EltTy = BuildQualifiedType(Context.getBaseElementType(T), Loc, Qs);
I'm not sure this is the best way to write this... I mean, I guess it works, but it's hard to follow.  Can you separate out the array handling a bit more?  Maybe just put `QualType ProblemTy = Context.getBaseElementType(T)` before you start checking the inner type.

2025-02-03 13:52 UTC, a-tarasyuk commented on clang/test/Sema/types.c
> +restrict S y;
@AaronBallman thanks for the feedback. I've added additional tests

2025-02-03 13:52 UTC, a-tarasyuk commented on clang/lib/Sema/SemaType.cpp
> +        EltTy = BuildQualifiedType(Context.getBaseElementType(T), Loc, Qs);
@efriedma-quic I've moved `getBaseElementType`

2025-02-03 20:59 UTC, efriedma-quic commented on clang/lib/Sema/SemaType.cpp
> +        EltTy = BuildQualifiedType(Context.getBaseElementType(T), Loc, Qs);
I guess I wasn't clear enough.

My suggestion was to call `Context.getBaseElementType(T)`, and then perform all the pointer type/object type/etc. on the result of that, instead of recursively calling BuildQualifiedType.

2025-02-04 14:31 UTC, a-tarasyuk commented on clang/lib/Sema/SemaType.cpp
> +        EltTy = BuildQualifiedType(Context.getBaseElementType(T), Loc, Qs);
@efriedma-quic Whoops :). I had considered removing recursion but was not certain that was the main point. I've removed recursion. Could you check the latest changes? thanks

2025-02-05 01:24 UTC, efriedma-quic commented on clang/lib/Sema/SemaType.cpp
> +        EltTy->isMemberPointerType() || EltTy->isArrayType()) {
Drop the isArrayType() here; should be impossible for EltTy to be an array here.

2025-02-05 01:24 UTC, efriedma-quic commented on clang/test/Sema/restrict-qualifier.c
> +static_assert(_Generic(typeof (t3), int *restrict[2][2] : 1, default : 0));
Maybe also add a check that we handle this correctly in function types:

```
static_assert(_Generic(void(T3 restrict), void(int *restrict(*)[2]):1, default:0));
```

2025-02-06 20:39 UTC, a-tarasyuk commented on clang/test/Sema/restrict-qualifier.c
> +static_assert(_Generic(typeof (t3), int *restrict[2][2] : 1, default : 0));
@AaronBallman @efriedma-quic could you review the latest changes? thanks

2025-02-08 00:17 UTC, efriedma-quic approved these changes
LGTM

2025-02-08 00:31 UTC, efriedma-quic requested changes
Oh, just thought of one more thing: we probably want a c23_compat warning for this (assuming the language is new in c23).

2025-02-10 16:27 UTC, AaronBallman commented
> Oh, just thought of one more thing: we probably want a c23_compat warning for this (assuming the language is new in c23).

Good catch -- this is new in C23. C17 said: "Types other than pointer types whose referenced type is an object type shall not be restrict-qualified."

So there's two diagnostics needed: one is an `Extension` warning (so it fires in `-pedantic`) for use of an extension pre-C23, and the other is `Warning`, `DefaultIgnore` for code which is incompatible with standards before C23. (And test coverage for both).

2025-02-11 20:51 UTC, a-tarasyuk commented on clang/include/clang/Basic/DiagnosticSemaKinds.td
> +  "'restrict' qualifier on pointers to arrays is incompatible with C17 and earlier">,
@AaronBallman Thanks for the feedback. I've updated diagnostics

2025-02-11 20:55 UTC, a-tarasyuk commented on clang/test/Sema/pre-c2x-restrict-qualifier.c
> +restrict T1 t1;         // pedantic-warning {{'restrict' qualifier on pointers to arrays is a C23 extension}} \
@AaronBallman I've updated test/handling so it no longer emits a warning for this case.

2025-02-11 20:56 UTC, a-tarasyuk commented on clang/test/Sema/pre-c2x-restrict-qualifier.c
> +restrict T2 t2;         // pedantic-warning {{'restrict' qualifier on pointers to arrays is a C23 extension}} \
@AaronBallman definitely, I've updated the diagnostic.

2025-02-11 22:30 UTC, a-tarasyuk commented on clang/lib/Sema/SemaType.cpp
> +      }
@efriedma-quic thanks. I've added chaneges.

2025-02-12 20:06 UTC, AaronBallman reviewed
I think this is pretty close, mostly just nits from me.

2025-02-12 20:06 UTC, AaronBallman commented on clang/test/Sema/types.c
> +
For these tests, I'd say it's better to change the `int` return type to `void` to silence the warning; neither of the tests are testing the behavior of the return anyway.

2025-02-12 20:06 UTC, AaronBallman commented on clang/lib/Sema/SemaType.cpp
> +          Diag(Loc, diag::ext_restrict_on_array_of_pointers_c23);
```suggestion
        Diag(Loc, getLangOpts().C23 ? diag::warn_c23_compat_restrict_on_array_of_pointers : diag::ext_restrict_on_array_of_pointers_c23);
```
And wrapped properly for clang-format.

2025-02-12 20:06 UTC, AaronBallman commented on clang/lib/Sema/SemaType.cpp
> +      if (const MemberPointerType *PTy = EltTy->getAs<MemberPointerType>())
```suggestion
      if (const auto *PTy = EltTy->getAs<MemberPointerType>())
```

2025-02-12 20:06 UTC, AaronBallman commented on clang/test/Sema/pre-c2x-restrict-qualifier.c
> +// RUN: %clang_cc1 -std=c2x -fsyntax-only -Wpre-c2x-compat -verify=c2x-compat %s
```suggestion
// RUN: %clang_cc1 -std=c23 -fsyntax-only -verify %s
// RUN: %clang_cc1 -std=c17 -fsyntax-only -pedantic -verify=pedantic,expected %s
// RUN: %clang_cc1 -std=c2x -fsyntax-only -Wpre-c2x-compat -verify=c2x-compat,expected %s
```

2025-02-12 20:06 UTC, AaronBallman commented on clang/test/Sema/pre-c2x-restrict-qualifier.c
> +                        // c2x-compat-error {{pointer to function type 'int (void)' may not be 'restrict' qualified}}
```suggestion
typedef t5 restrict t6; // expected-error {{pointer to function type}}
```
(Could use expected-error-re and use a regular expression to handle the `()` vs `(void)` differences, too, but that makes the test slower to run and maybe this is sufficiently clear?)

2025-02-12 20:06 UTC, AaronBallman commented on clang/test/Sema/pre-c2x-restrict-qualifier.c
> +                        // c2x-compat-error {{restrict requires a pointer or reference ('t7' (aka 'int[2]') is invalid}}
```suggestion
typedef t7 restrict t8; // expected-error {{restrict requires a pointer or reference ('t7' (aka 'int[2]') is invalid)}}
```

2025-02-12 20:45 UTC, a-tarasyuk commented on clang/test/Sema/types.c
> +
@AaronBallman thanks, I've made changes to all the requested cases.

2025-02-13 15:27 UTC, AaronBallman approved these changes
LGTM! Please wait a bit before landing in case @efriedma-quic has any additional comments.

2025-02-13 19:55 UTC, efriedma-quic approved these changes

2025-02-14 17:06 UTC, merged