[Clang] Repair the function "rParenEndsCast" to make incorrect judgments in template variable cases
llvm/llvm-project pull request #120904
Opened 2024-12-22 15:21 UTC by dty2

Try to fix issue: https://github.com/llvm/llvm-project/issues/120148
I'm a newbie, please give me some suggestions for modification.
Especially I use a global array "castIdentifiers", I feel that this implementation is not good, but I don't know how to modify it.

2024-12-22 21:50 UTC, owenca commented
You need to add a unit test.

2024-12-22 23:39 UTC, owenca requested changes
Please run `ninja FormatTests` before submitting the patch. It fails a few unit tests before crashing.

2024-12-24 21:48 UTC, HazardyKnusperkeks commented on clang/lib/Format/TokenAnnotator.cpp
> +// TODO: Add new Type modifiers
```suggestion
// TODO: Add new Type modifiers.
```

2024-12-24 21:48 UTC, HazardyKnusperkeks commented on clang/lib/Format/TokenAnnotator.cpp
> +          return false;
```suggestion
          return std::find(castIdentifiers.begin(), castIdentifiers.end(), Prev->TokenText) != castIdentifiers.end();
```

2024-12-25 05:08 UTC, owenca commented on clang/lib/Format/TokenAnnotator.cpp
> +        if (Current.Next->Next->Next->isTypeName(LangOpts))
IMO this is too simplistic to be very useful. See the general syntax [here](https://en.cppreference.com/w/cpp/language/type_alias). Also, this doesn't work at all if the `using` statement is in a header file.

2024-12-25 05:14 UTC, owenca commented on clang/lib/Format/TokenAnnotator.cpp
> +                                                   "remove_reference_t"};
What about `std::vector`, `std::whatever`, `foo::bar`, etc?

2025-01-01 17:18 UTC, dty2 commented on clang/lib/Format/TokenAnnotator.cpp
> +          return false;
You are right, but I would use the llvm alternative version of std::find which is in STLExtras.h, You're right, but I would use the llvm alternative version of std::find, which is in STLExtras.h.

2025-01-02 02:27 UTC, owenca commented
See #121318.

2025-01-02 03:08 UTC, dty2 commented on clang/lib/Format/TokenAnnotator.cpp
> +          return false;
You are right, but I would use the llvm alternative version of std::find which is in STLExtras.h called "llvm::find".

2025-01-02 03:10 UTC, dty2 commented on clang/lib/Format/TokenAnnotator.cpp
> +        if (Current.Next->Next->Next->isTypeName(LangOpts))
You are right, I would plan to do it using the way you mentioned in #121318.

2025-01-02 17:56 UTC, closed without merging