[libc++] Optimize ranges::equal for vector<bool>::iterator
llvm/llvm-project pull request #121084
Opened 2024-12-25 05:01 UTC by winner245

This PR optimizes the performance of `std::ranges::equal` for `std::vector<bool>::iterator`, resulting in a performance improvement of up to **x** and **60x** for aligned and unaligned equality comparisons, respectively. 

- Aligned equality comparison

- Unaligned equality comparison

2025-02-05 17:20 UTC, ldionne approved these changes
LGTM with minor comments, thanks!

2025-02-05 17:20 UTC, ldionne commented on libcxx/include/__algorithm/equal.h
> +          bool _IC2,
```suggestion
          bool _IsConst1,
          bool _IsConst2,
```

2025-02-05 17:20 UTC, ldionne commented on libcxx/include/__algorithm/equal.h
> +                            __is_identity<_Proj2>::value,
The following should be sufficient:

```suggestion
          __enable_if_t<__desugars_to_v<__equal_tag, _Pred, bool, bool> && __is_identity<_Proj1>::value &&
                            __is_identity<_Proj2>::value,
```

`__desugars_to_v<__equal_tag, ranges::equal_to, ...>` should be true, so the `is_same` are not required. You can confirm that by double-checking that you still get the same speedup in your benchmark after making this change.

2025-02-05 17:20 UTC, ldionne commented on libcxx/include/__algorithm/equal.h
> +[[__nodiscard__]] inline _LIBCPP_HIDE_FROM_ABI _LIBCPP_CONSTEXPR_SINCE_CXX20 bool __equal_iter_impl(
Let's inline this function into `__equal_impl(__bit_iterator, ...)` below, since the additional indirection doesn't serve much of a purpose.

2025-02-07 00:30 UTC, winner245 commented on libcxx/include/__algorithm/equal.h
> +                            __is_identity<_Proj2>::value,
I've double-checked that libc++ provides the following specializations to ensure that both `std::__equal_to` and
`ranges::equal_to` desugars to `__equal_tag`: 

```cpp
template <class _Tp, class _Up>
inline const bool __desugars_to_v<__equal_tag, ranges::equal_to, _Tp, _Up> = true;

template <class _Tp, class _Up>
inline const bool __desugars_to_v<__equal_tag, __equal_to, _Tp, _Up> = true;
```

So this simplifies the SFINAE constraint as suggested.

2025-02-08 16:34 UTC, winner245 commented
I've updated the tests for the `fill, fill_n` algorithms to temporarily use the standard `std::equal` in their equality assertions. This change is necessary because the `std::equal` algorithm with the `__bit_iterator` optimization fails to correctly compare `vector<bool>` instances with storage types smaller than `int`, as tracked in #126369. Once this issue is resolved, we should revert to the `__bit_iterator` optimized version in the `fill` and `fill_n` tests. This is clearly stated in the corresponding test files with a FIXME comment.

The purpose of this change is to ensure that this PR can be merged independently of the issue resolution.

2025-02-19 17:02 UTC, ldionne requested changes
The change LGTM but I'd like to see it again after the `operator==` change.

2025-02-19 17:02 UTC, ldionne commented on libcxx/test/std/algorithms/alg.modifying.operations/alg.fill/fill.pass.cpp
> +    // assert(in == expected); // FIXME: Uncomment this line once issue #126369 is fixed.
This patch technically regresses functionality for `vector<bool>::operator==`. Instead of "breaking" it, I would suggest that we change https://github.com/llvm/llvm-project/blob/main/libcxx/include/__vector/comparison.h#L27 to:

```c++
template <class _Tp, class _Allocator>
_LIBCPP_CONSTEXPR_SINCE_CXX20 inline _LIBCPP_HIDE_FROM_ABI bool
operator==(const vector<_Tp, _Allocator>& __x, const vector<_Tp, _Allocator>& __y) {
  ... slow but correct implementation ...

  // FIXME: Once issue #126369 has been resolved, we can revert to using std::equal here, which is a lot faster.
  // const typename vector<_Tp, _Allocator>::size_type __sz = __x.size();
  // return __sz == __y.size() && std::equal(__x.begin(), __x.end(), __y.begin());
}
```

That way, you don't need to modify the tests here and the library will still be functionally correct, although `operator==` will be slower.

2025-02-20 21:14 UTC, winner245 commented on libcxx/include/__bit_reference
> +  template <class _Dp, bool _IsConst1, bool _IsConst2>
Great suggestion! Using the suggested iterator core access pattern will clean up all those ugly friend declarations in `__bit_iterator`. I’ll tackle this refactoring once this series is done.

2025-02-20 21:14 UTC, winner245 commented on libcxx/include/__algorithm/equal.h
> +#endif
Thanks. This has been removed.

2025-02-20 21:15 UTC, winner245 commented on libcxx/test/std/algorithms/alg.modifying.operations/alg.fill/fill.pass.cpp
> +    // assert(in == expected); // FIXME: Uncomment this line once issue #126369 is fixed.
Thank you very much for catching this! I agree that preserving the functionality of `operator==` is the priority here. I’ve added a slow but correct implementation for `vector<bool>::operator==` as you suggested. Since I've introduced a separate overload for `vector<bool>::operator==` instead of modifying the generic `vector<_Tp, _Allocator>::operator==`, we can simply remove it once #126369 is resolved. I’ve also added a FIXME comment to note this.

2025-02-26 17:16 UTC, ldionne approved these changes
LGTM, thanks!

2025-02-26 17:18 UTC, merged