Accept `cl`-style output arguments (`/Fo`, `-Fo`) for `--fmodule-output`
llvm/llvm-project pull request #121046
Opened 2024-12-24 09:30 UTC by sharadhr

2024-12-24 13:17 UTC, carlocab commented on clang/lib/Driver/Driver.cpp
> +    if (Arg *FinalOutput = C.getArgs().getLastArg(options::OPT_o, options::OPT__SLASH_Fo, options::OPT__SLASH_Fo_COLON))
We should probably gate checking the cl-style flags behind `isCLMode`.

2024-12-25 01:36 UTC, ChuanqiXu9 commented
The tests are failing and it looks relevent.

2025-01-03 21:03 UTC, nikic commented
Why is this submitted against the release/19.x branch? Is this a backport? If so, please indicate which commit it backports.

2025-01-05 16:31 UTC, sharadhr commented
> Why is this submitted against the release/19.x branch? Is this a backport? If so, please indicate which commit it backports.

Not a backport but a fix. I have now re-submitted it against `main`, but I'd like it back-ported to `19.x` if possible.

2025-01-06 02:02 UTC, ChuanqiXu9 commented
> > Why is this submitted against the release/19.x branch? Is this a backport? If so, please indicate which commit it backports.
> 
> Not a backport but a new commit. I have now re-submitted it against `main`, but I'd like it back-ported to `19.x` if possible.

It is better to fix the test failures (or announce they are not relevant with your pr)

2025-01-06 13:00 UTC, sharadhr commented
The Linux tests that failed nearly instantaneously seem to have failed because of a CI permissions issue and are hence irrelevant. There are more critical Windows/macOS failures that have to do with PCHs when running with `clang-cl`, and I shall investigate them.

2025-01-07 08:55 UTC, sharadhr commented
I think I need to be a little more nuanced—with my changes, PCHs requested with `/Fo` and `/Fp` aren't output, causing the PCH test failures.

2025-01-09 20:40 UTC, sharadhr commented
Hmm. Not quite sure why `cl-pch.cpp` is failing.

2025-01-13 00:02 UTC, sharadhr commented
I'm not sure how to fix the `Driver/at_file.c` and `ClangScanDeps/target-filename.cpp` tests. I'd love some help with these.

2025-01-16 09:42 UTC, sharadhr commented
@ChuanqiXu9 are you able to have a look?

2025-01-16 09:56 UTC, ChuanqiXu9 commented
> @ChuanqiXu9 are you able to have a look?

Sorry, I can't test and take a deeper look on windows. From https://discourse.llvm.org/t/driver-volunteer-wanted-for-modules-support-in-driver-for-mac-ubuntu-and-windows/83768/13, I think you can CC people there or calling again there.

2025-02-06 00:36 UTC, rnk commented
Thanks, the code seems correct, but can this be tested? cc @zmodem for clang-cl driver changes

2025-02-07 21:26 UTC, sharadhr commented
Ready for review; all relevant tests passing.

2025-02-08 01:55 UTC, ChuanqiXu9 commented
> Ready for review; all relevant tests passing.

I think @rnk was saying you should add a test for this.

2025-02-08 21:32 UTC, sharadhr commented
Fair point. Added a test. Additionally the CMake repository contains a bigger battery of tests that also all pass with this PR.

2025-02-10 07:07 UTC, sharadhr commented
A quick bump. I'd like to get this reviewed hopefully in time for the Clang 20.x release. I think having it in 19.x is a lost battle, it's a bit too late for that.

2025-02-10 13:51 UTC, zmodem commented on clang/lib/Driver/Driver.cpp
> +        options::OPT_o, options::OPT__SLASH_Fo, options::OPT__SLASH_Fo_COLON);
`_SLASH_Fo_COLON` is an alias for `_SLASH_Fo`, so I'm not sure that you need to check for it explicitly? (Also applies for the uses below.)

2025-02-10 13:51 UTC, zmodem commented on clang/lib/Driver/Driver.cpp
> +    }
I'm having trouble following the logic here. Can you add a comment explaining what's going on? I.e. when is `-o` and/or `/Fo` supposed to be considered?

2025-02-10 13:51 UTC, zmodem commented on clang/test/Driver/cl-cxx20-modules.cppm
> +// RUN: %clang_cl /std:c++20 --precompile -x c++-module -fmodule-output=%t/Hello.bmi -Fo"%t/Hello.bmi" -c %t/Hello.cppm -### 2>&1 | FileCheck %s
This is just one invocation, but the logic in GetNamedOutputPath() seems to cover many cases.

Also, is it `-fmodule-output` or `/Fo` that sets the output filename (or both?)

(Nit: you'll want to put `--` before `%t/Hello.cppm`, otherwise it may be interpreted as a command-line option e.g. if the path starts with `/Users`.)

2025-02-10 20:03 UTC, sharadhr commented on clang/lib/Driver/Driver.cpp
> +    }
I've updated the OP message with the reasoning for this. This logic in particular is to resolve `lit` test cases that failed when `/Yp` was passed to `clang-cl.exe`, i.e. PCHs were generated. I believe this is because `/Yp` uses `/Fo` for the PCH output, and therefore this invocation needs to use `/o` (or `-o`). 

`HasAnyOutputArg` was written _specifically_ to resolve `llvm-project\clang\test\ClangScanDeps\target-filename.cpp` failing. It feels like a weird hack and I'm open to suggestions.

2025-02-10 20:22 UTC, sharadhr commented on clang/test/Driver/cl-cxx20-modules.cppm
> +// RUN: %clang_cl /std:c++20 --precompile -x c++-module -fmodule-output=%t/Hello.bmi -Fo"%t/Hello.bmi" -c %t/Hello.cppm -### 2>&1 | FileCheck %s
> This is just one invocation, but the logic in GetNamedOutputPath() seems to cover many cases.

Agreed; once again; open to suggestions for more test cases. 

> Also, is it -fmodule-output or /Fo that sets the output filename (or both?)

From the [Clang user guide](https://clang.llvm.org/docs/StandardCPlusPlusModules.html#how-to-build-projects-using-modules), it appears _both_ are required, and CMake in particular uses the 'one-phase compilation' method.

2025-02-26 00:13 UTC, sharadhr commented on clang/lib/Driver/Driver.cpp
> +    }
I do hope there's some scope for a response, as I'm not sure how to proceed.

2025-02-26 01:53 UTC, ChuanqiXu9 commented on clang/lib/Driver/Driver.cpp
> +    }
You can ping the reviewer @zmodem . The suggested style is no more ping in a week.

2025-02-26 08:59 UTC, zmodem commented on clang/test/Driver/cl-cxx20-modules.cppm
> +// RUN: %clang_cl /std:c++20 --precompile -x c++-module -fmodule-output=%t/Hello.bmi -Fo"%t/Hello.bmi" -c %t/Hello.cppm -### 2>&1 | FileCheck %s
From the doc:

> To generate a BMI for an importable module unit, use either the --precompile or -fmodule-output command line options.

Your test uses *both*, with the same filename passed to two different flags. This seems wrong to me.

2025-02-26 08:59 UTC, zmodem commented on clang/lib/Driver/Driver.cpp
> +        options::OPT_o, options::OPT__SLASH_Fo, options::OPT__SLASH_Fo_COLON);
This still hasn't been addressed?

2025-02-26 08:59 UTC, zmodem commented on clang/lib/Driver/Driver.cpp
> +    }
The logic has to be clear to any reader. "It makes the lit tests pass" is not a good explanation.

I think you need to figure out how these flags are supposed to work together, and then translate that into code.

2025-04-11 00:33 UTC, sharadhr commented on clang/test/Driver/cl-cxx20-modules.cppm
> +// RUN: %clang_cl /std:c++20 --precompile -x c++-module -fmodule-output=%t/Hello.bmi -Fo"%t/Hello.bmi" -c %t/Hello.cppm -### 2>&1 | FileCheck %s
Coming back after a long while...

Both arguments were provided to exercise [CMake's command-line invocation](https://gitlab.kitware.com/cmake/cmake/-/issues/25731#note_1603044) which given this information might be incorrect.

@ChuanqiXu9 are you able to provide more information?

2025-04-16 22:21 UTC, sharadhr commented on clang/lib/Driver/Driver.cpp
> +    }
Given [the comment below](https://github.com/llvm/llvm-project/pull/121046#discussion_r1971184880), I believe it is incorrect to pass both `-fmodule-output` and the combination of `--precompile` and `-o` (or `-Fo`). I think there is hence scope to simplify this logic.

2025-05-11 16:15 UTC, cor3ntin commented on clang/lib/Driver/Driver.cpp
> +        options::OPT_o, options::OPT__SLASH_Fo, options::OPT__SLASH_Fo_COLON);
@sharadhr ping

2025-05-12 01:48 UTC, ChuanqiXu9 commented on clang/test/Driver/cl-cxx20-modules.cppm
> +// RUN: %clang_cl /std:c++20 --precompile -x c++-module -fmodule-output=%t/Hello.bmi -Fo"%t/Hello.bmi" -c %t/Hello.cppm -### 2>&1 | FileCheck %s
Sorry for ignoring this. `--precompile` will be meaningless if it is followed by a `-c`. So the command line in cmake's thread actually use `-fmodule-output`.

2025-05-12 12:57 UTC, bradking commented on clang/test/Driver/cl-cxx20-modules.cppm
> +// RUN: %clang_cl /std:c++20 --precompile -x c++-module -fmodule-output=%t/Hello.bmi -Fo"%t/Hello.bmi" -c %t/Hello.cppm -### 2>&1 | FileCheck %s
Please don't worry too much about what CMake's command-line invocations [linked above](https://github.com/llvm/llvm-project/pull/121046#discussion_r2038627647) are doing.  CMake doesn't yet support modules with `clang-cl`, and is waiting on the work here.  The command lines I posted over there are showing what *unmerged* changes to CMake are doing in its test suite as part of analyzing why not everything is working.  This PR should focus on the functionality in `clang-cl` and its test should focus on the documented and intended usage.  Once this is merged then CMake can be taught to do the right thing.

2025-05-15 03:11 UTC, ChuanqiXu9 reviewed
@zmodem given how important this, I hope we can make this for clang21. Thanks!

2025-05-15 13:24 UTC, mathstuf commented
That was discussed on Discourse. If/when `clang-cl` starts writing and reading MSVC-compatible BMIs, it can use the same flags. Until then, it would be very weird to use `-ifcOutput` for `clang-cl` when it is not using the IFC format at all.

2025-05-15 13:55 UTC, zmodem commented
Sorry, I don't remember seeing that discussion, and I'm probably missing lots of modules context. As a counter argument, clang-cl uses `/Yc` and `/Fp` to generate PCH files, to match MSVC's interface although the file format is different.

More importantly, it feels like we're being very unintentional about the interface design here. Why should clang-cl's `/Fo` name a BMI file if that's not what MSVC does, and the document clearly says that the flag "Specifies an object (.obj) file name or directory to be used instead of the default."?

If the idea is to punt on the design, maybe the solution is just to use regular clang flags for this?

2025-05-15 14:05 UTC, ChuanqiXu9 commented
> > @zmodem given how important this it, I hope we can make this for clang21. Thanks!
> 
> I'm just a reviewer here, and I still find the patch very confusing.

Not asking for an approval. It is just a ping : )
> 
> And taking a step back, the whole point of clang-cl is to provide a cl.exe compatible interface to clang. I presume cl.exe does not use `--precompile -x c++-module` to produce BMI files. Shouldn't we try to match what they're doing?

2025-05-15 14:43 UTC, zmodem commented
> I think '/Fo' is basically '-o'. Its semantic is to specify the path to the output file.

No, `/Fo` is for object files, `/Fe` for the executable, `/Fp` for pch file etc.

> So if now clang-cl can accept '-o' [...]

It works in general in clang-cl. I guess we'd have to double check if it works in the modules use case. And `-fmodule-output` is exposed in clang-cl as well, so it sounds like there are plenty of flags already :)

2025-05-15 15:25 UTC, mathstuf commented
Is `-Fo` even relevant here? The BMI output name comes from `-ifcOutput` (or `-fmodule-output=`). Consumption of external modules doesn't need an object, so it would only use `-fmodule-output=`.

> Sorry, I don't remember seeing that discussion

See this thread: https://discourse.llvm.org/t/clang-cl-exe-support-for-c-modules/72257

2025-05-16 01:56 UTC, ChuanqiXu9 commented
> Is `-Fo` even relevant here? The BMI output name comes from `-ifcOutput` (or `-fmodule-output=`). Consumption of external modules doesn't need an object, so it would only use `-fmodule-output=`.
> 
> > Sorry, I don't remember seeing that discussion
> 
> See this thread: https://discourse.llvm.org/t/clang-cl-exe-support-for-c-modules/72257

But if we want to generate BMI only instead of obj files, we should use `--precompile -o`

2025-05-16 02:08 UTC, sharadhr commented
> Is `-Fo` even relevant here? The BMI output name comes from `-ifcOutput` (or `-fmodule-output=`). Consumption of external modules doesn't need an object, so it would only use `-fmodule-output=`.

This is frankly for the Clang and build system authors (CC: @bradking, @mathstuf) to arrive at a consensus. 

In the CMake MR, it was determined that `/clang:-o` cannot be used to substitute for `/Fo:` (or `-Fo`).

2025-05-16 03:22 UTC, sharadhr commented
I think I have a better solution than using `/Fo`. From @zmodem's [comment above](https://github.com/llvm/llvm-project/pull/121046#issuecomment-2884086228), [MSVC documentation](https://learn.microsoft.com/en-gb/cpp/build/reference/fo-object-file-name?view=msvc-170), and [Clang-cl documentation](https://clang.llvm.org/docs/UsersManual.html#clang-cl:~:text=/Fo%3Cfile%20or%20directory%3E%20%20Set%20output%20object%20file%2C%20or%20directory%20(ends%20in%20/%20or%20%5C)%20(with%20/c)), I think it is incorrect to use `/Fo` for the BMI output, since `/Fo` is for _object files_. 

However it is clear Clang-cl handles `-o` and `/o` differently. Merely passing `--precompile /o` is a much cleaner solution, and all test cases pass.

2025-05-17 06:24 UTC, sharadhr commented
I believe the issue can be distilled further.

On the `main` branch, this command outputs `Hello.bmi`, assuming `Hello.cppm` exists and has `export module Hello;`:
```
clang.exe --precompile -x c++-module -o Hello.bmi -c Hello.cppm
```

This command does not:
```
clang-cl.exe --precompile -x c++-module -o Hello.bmi -c Hello.cppm
```

This command also does not:
```
clang-cl.exe --precompile -x c++-module /o Hello.bmi -c Hello.cppm
```

And the only lines where the driver behaviour appears to diverge, is the `if` block in `Driver.cpp`, commented as below:
```cxx
// Output to a user requested destination?
if (AtTopLevel && !isa<DsymutilJobAction>(JA) && !isa<VerifyJobAction>(JA)) {
  ...
}
```

2025-05-22 06:53 UTC, ChuanqiXu9 commented
@mathstuf in https://github.com/llvm/llvm-project/issues/140825#issuecomment-2900112555 , xmake dev said he can fix the problem by `/clang:-o`. I am wondering if you can did similar thing in CMake if there is an argument?

2025-05-22 09:11 UTC, sharadhr commented
> xmake dev said he can fix the problem by /clang:-o

We [tried this, but it didn't seem to work](https://gitlab.kitware.com/cmake/cmake/-/issues/25731#note_1603818). However, I think that issue has a subtle but important difference: @Arthapz has used [`/clang:-o -clang:<BMIfile>`](https://github.com/xmake-io/xmake/pull/6477/files#diff-b526124d8e7f20d143a49c263e4bf8ba6ebb77b799aa1b8d5e93639fd4e2d77cR44) whereas we used `/clang:-o<BMIfile>`. I'm not sure why this difference manifested, but it seems to _almost_ work now with the above change.

However, a `scan-with-pch` test still fails because `clang-cl: error: cannot specify -o when generating multiple output files`.

```
CMake Error at R:/cmake/Tests/RunCMake/RunCMake.cmake:289 (message):
examples/scan-with-pch-build - FAILED:

Result is [1], not [0].

Command was:

command> "R:/cmake/out/build/RelWithDebInfo/bin/cmake.exe" "--build" "." "--config" "Debug"

Actual stdout:

actual-stdout> [1/5] Building CXX object CMakeFiles\simple.dir\cmake_pch.cxx.obj
actual-stdout> FAILED: CMakeFiles/simple.dir/cmake_pch.cxx.obj
actual-stdout> R:\llvm-project\build\x64-release\bin\clang-cl.exe  /nologo -TP   /DWIN32 /D_WINDOWS /EHsc /Ob0 /Od /RTC1 -std:c++20 -MDd -Zi /YcR:/cmake/out/build/RelWithDebInfo/Tests/RunCMake/CXXModules/examples/scan-with-pch-build/CMakeFiles/simple.dir/cmake_pch.hxx /FpR:/cmake/out/build/RelWithDebInfo/Tests/RunCMake/CXXModules/examples/scan-with-pch-build/CMakeFiles/simple.dir/./cmake_pch.cxx.pch /FIR:/cmake/out/build/RelWithDebInfo/Tests/RunCMake/CXXModules/examples/scan-with-pch-build/CMakeFiles/simple.dir/cmake_pch.hxx /showIncludes -clang:-oCMakeFiles\simple.dir\cmake_pch.cxx.obj /FdCMakeFiles\simple.dir\ -c -- R:\cmake\out\build\RelWithDebInfo\Tests\RunCMake\CXXModules\examples\scan-with-pch-build\CMakeFiles\simple.dir\cmake_pch.cxx
actual-stdout> clang-cl: error: cannot specify -o when generating multiple output files
actual-stdout> ninja: build stopped: subcommand failed.
```

2025-07-03 23:45 UTC, h-vetinari commented
> given how important this it, I hope we can make this for clang21. Thanks!

FYI, branching for LLVM v21 is less than [two weeks away](https://discourse.llvm.org/t/llvm-21-x-release-information-and-branching/87065)

2025-07-04 02:10 UTC, ChuanqiXu9 approved these changes
Given the problem is important (I've heard the problem for clang-cl with modules several times) and the author have been active on this direction for years, I think I can trust him even if I can't test it actually. So LGTM.

I'll land this one week later if no objection or new comments come in, @sharadhr remind me that time if I forget it somehow.

2025-07-04 02:10 UTC, ChuanqiXu9 commented on clang/test/Driver/cl-cxx20-modules.cppm
> +// test whether the following outputs %Hello.bmi
```suggestion
// test whether the following outputs %t/Hello.bmi
```

2025-07-04 07:02 UTC, zmodem requested changes
> I'll land this one week later if no objection or new comments come in

I object.

Even the author seems to object:

> I believe it is now incorrect to use /Fo for the BMI output

The change to `Driver::GetNamedOutputPath` has not been explained yet, beyond "it seems to make the tests pass".

And the whole approach of making clang-cl's `/Fo` ("set object file noame") to something different from MSVC's seems very questionable.

I think this patch needs to go back to the drawing board.

2025-07-04 07:42 UTC, sharadhr commented
> I think this patch needs to go back to the drawing board.

I agree. `/Fo` is strictly for object files—that is, `.obj` as a result of a compilation—that is, `/c`, whereas `-o` is meant for 'any output'. 

My understanding is that @Arthapz made `/clang:-o` work with upstream, even without this patch. CMake needs to rework its understanding of the Clang compilation model and perhaps rework its invocation of BMI compilation and `clang-scan-deps`.

2025-07-04 07:50 UTC, ChuanqiXu9 commented
CC @mathstuf @bradking

2025-07-04 13:45 UTC, mathstuf commented
I don't really care how things are spelled as long as they're possible. Don't take what CMake does for `clang-cl` and modules as gospel as it is very much not declared as supported at all. We can rework how CMake constructs command lines for `clang-cl` and modules as needed.

2025-07-04 14:25 UTC, sharadhr commented
If this is consensus, then I will rework this PR from scratch to expose `/ifcOutput` (or any other appropriate flag, just not `/Fo` or `-o`) with `clang-cl`.

2025-07-23 04:21 UTC, closed without merging