[libc++] Fix vector sanitization annotations on destruction
llvm/llvm-project pull request #121031
Opened 2024-12-24 06:12 UTC by ddcc

In D144155/D136765, the asan annotations for std::vector were modified to unpoison freed backing memory on destruction, instead of leaving it poisoned. However, calling `__clear()` instead of `clear()` skips informing the asan runtime of this decrease in the accessible container size, which breaks the invariant that the value of `old_mid` should match the value of `new_mid` from the previous call to _sanitizer_annotate_contiguous_container(), which can trip the sanity checks for the partial poison between [d1, d2) and the container redzone between [d2, c), if enabled. To fix this, ensure that `clear()` is called instead, as is already done by `__vdeallocate()`.

2025-01-09 01:16 UTC, vitalybuka approved these changes
LGTM, but libc++ maintainers need to check

2025-01-09 11:48 UTC, philnik777 requested changes
Since this is fixing a bug, this needs a test.

2025-01-10 17:34 UTC, ldionne requested changes

2025-01-10 21:31 UTC, ddcc commented
I'm not too familiar with the libcxx testing infrastructure, and I'm not sure what the best way to test this would be. Part of the problem is that the two codepaths being changed call `__annotate_delete()` immediately after the `clear()`, so by the time control flow returns to the caller, the intermediate asan container state has been lost and we can't assert on it. The other factor is that the two sanity checks in the compiler-rt asan runtime for the asan shadow state are currently disabled: https://github.com/llvm/llvm-project/blob/main/compiler-rt/lib/asan/asan_poisoning.cpp#L448 (lines 448, 455), and I'm hesitant to touch that because it would have broader scope and may unintentionally break other things.

2025-01-13 11:42 UTC, AdvenamTacet approved these changes
Thank you for noticing it!

Let's make sure that the commit message mentions removal of `void __clear()`.

Please wait for a green light from @philnik777 before merging.

>  breaks the invariant that the value of old_mid should match the value of new_mid from the previous call to __sanitizer_annotate_contiguous_container()

It shouldn't be observed by a user as we actually do not want to enforce that "invariant" (we want to keep it only to easier ensure correctness of the implementation while testing).

Reasoning is that there are situations where users may want to (un)poison containers memory. We worked on making sure that annotation functions work with modified annotations (including over-unpoisoned memory), so it should not result in any error.

I support that change as keeping that "invariant" helps to avoid annotation errors in future, but unless I missed something, it's not necessary change. Users using public vectors API won't notice that.
Unpoisoning memory from [D144155](https://reviews.llvm.org/D144155) is necessary, but poisoning here is not.

> Part of the problem is that the two codepaths being changed call __annotate_delete() immediately after the clear()

I don't think we can test it in a reasonable way as it shouldn't be observable by using public vector functions. But if someone has an idea, I'm happy to learn how to do it (without cluttering vectors implementation or recompiling compiler-rt).

2025-01-13 19:11 UTC, ddcc commented
Yeah, I should clarify that the relevant sanity checks are currently disabled in the upstream asan runtime. However, we are using an internal asan runtime that does have these sanity checks enabled, and that is where we see the failures.

2025-01-15 21:05 UTC, ddcc commented
@ldionne @philnik777 Is this PR ok now?

2025-01-20 13:56 UTC, ldionne approved these changes

2025-01-20 13:57 UTC, merged