[libc][math][c23] Add tanf16 function
llvm/llvm-project pull request #121018
Opened 2024-12-24 01:27 UTC by wldfngrs

- Implementation of tan for 16-bit floating point inputs.
- Exhaustive tests across the 16-bit input range

2024-12-24 01:51 UTC, wldfngrs commented
@overmighty please review

2024-12-30 19:00 UTC, overmighty requested changes

2025-01-10 19:57 UTC, overmighty approved these changes
LGTM with a nit.

2025-01-10 19:57 UTC, overmighty commented on libc/src/math/generic/tanf16.cpp
> +    // |x| <= 1.398p-11
Nit:

```suggestion
    // |x| <= 0x1.398p-11
```

2025-01-13 04:46 UTC, lntue approved these changes

2025-01-13 04:46 UTC, merged