[mlir][emitc] Support convert arith.extf and arith.truncf to emitc
llvm/llvm-project pull request #121184
Opened 2024-12-27 07:25 UTC by jacquesguan

2024-12-28 09:32 UTC, CoTinker reviewed
Looks good to me, and adds a new line at end of the file maybe better.😊

2024-12-28 11:45 UTC, marbre reviewed
Thanks for adding further conversion! Adding a newline to the test would be indeed preferred. i am ooo and need to take a closer look when i am back but I wonder what the expectations with regards to casting and rounding are. `arith.trunc` states
> If the value cannot be exactly represented, it is rounded using the provided rounding mode or the default one if no rounding mode is provided.

but this seems not to be handled in the conversion.

2024-12-31 08:14 UTC, jacquesguan commented
> Looks good to me, and adds a new line at end of the file maybe better.😊

Thanks, I added a end line.

2024-12-31 08:17 UTC, jacquesguan commented
> Thanks for adding further conversion! Adding a newline to the test would be indeed preferred. i am ooo and need to take a closer look when i am back but I wonder what the expectations with regards to casting and rounding are. `arith.trunc` states
> 
> > If the value cannot be exactly represented, it is rounded using the provided rounding mode or the default one if no rounding mode is provided.
> 
> but this seems not to be handled in the conversion.

Thanks for comment. I added a early exit when the cast op has rounding mode.

2025-01-02 08:17 UTC, TinaAMD reviewed
Thanks for the PR!

2025-01-02 08:17 UTC, TinaAMD commented on mlir/lib/Conversion/ArithToEmitC/ArithToEmitC.cpp
> +
Can you add a check here that the types which are converted are cast compatible (see [here](https://github.com/llvm/llvm-project/blob/0c68155002edb30d6b0df3f17fe1f44a01afacd9/mlir/lib/Dialect/EmitC/IR/EmitC.cpp#L247))?

2025-01-02 08:17 UTC, TinaAMD commented on mlir/test/Conversion/ArithToEmitC/arith-to-emitc-unsupported.mlir
> +}
Maybe add the following tests (for extf and truncf):
* Unsupported source type
* Unsupported destination type
* Cast-incompatible type conversion (tensors of supported types should work)

2025-01-02 08:49 UTC, jacquesguan commented on mlir/lib/Conversion/ArithToEmitC/ArithToEmitC.cpp
> +
I think that the else of early exit `if (!emitc::isSupportedFloatType(dstType))` should cover all compatible cases?

2025-01-02 09:38 UTC, TinaAMD commented on mlir/lib/Conversion/ArithToEmitC/ArithToEmitC.cpp
> +
Yes, you're right, it will rule out the tensor case I had in mind already.

2025-01-02 09:40 UTC, TinaAMD approved these changes
LGTM!

2025-01-02 09:42 UTC, marbre commented on mlir/lib/Conversion/ArithToEmitC/ArithToEmitC.cpp
> +      if (roundingModeOp.getRoundingModeAttr())
Without looking further into the underlying code, is a `RoundingModeAttr` also provided for the default rounding mode? I think a test as suggested by @TinaAMD would help.

Furthermore, do we know what the default rounding mode is that's assumed by Arith? And is this what we would expect with C or C++? For C, https://en.cppreference.com/w/c/language/conversion (*Real floating-point conversions*) says
><p>A value of any real floating type can be implicitly converted to any other real floating type.
></p>
><ul><li> If the value can be represented by the target type exactly, it is unchanged
></li><li> if the value can be represented, but cannot be represented 
>exactly, the result is the nearest higher or the nearest lower value (in
 >other words, rounding direction is implementation-defined), although if
 >IEEE arithmetic is supported, rounding is to nearest
></li><li> if the value cannot be represented, the behavior is undefined <br>
> | This section is incompleteReason: check IEEE if appropriately-signed infinity is required |

2025-01-04 02:10 UTC, jacquesguan commented on mlir/lib/Conversion/ArithToEmitC/ArithToEmitC.cpp
> +      if (roundingModeOp.getRoundingModeAttr())
As `ArithToSPIRV` and `ArithToAMDGPU` also don't support the conversion of truncf with `RoundingModeAttr` now, I think we could leave it to future implementation?

2025-01-09 23:12 UTC, marbre requested changes

2025-01-09 23:12 UTC, marbre commented on mlir/test/Conversion/ArithToEmitC/arith-to-emitc-unsupported.mlir
> +  // expected-error @+1 {{failed to legalize operation 'arith.truncf'}}
```suggestion
  // expected-error @+1 {{failed to legalize operation 'arith.extf'}}
```
Your test are failing due to some copy paste errors.

2025-01-09 23:12 UTC, marbre commented on mlir/test/Conversion/ArithToEmitC/arith-to-emitc-unsupported.mlir
> +  // expected-error @+1 {{failed to legalize operation 'arith.truncf'}}
```suggestion
  // expected-error @+1 {{failed to legalize operation 'arith.extf'}}
```

2025-01-09 23:15 UTC, marbre commented on mlir/lib/Conversion/ArithToEmitC/ArithToEmitC.cpp
> +      if (roundingModeOp.getRoundingModeAttr())
Fair enough. The one difference however might be that the SPRI-V as well as the amdgpu dialect specify what rounding modes they assume in general. Maybe we could add at least some documentation to e.g. `emitc.td`?

2025-01-10 09:49 UTC, jacquesguan commented on mlir/lib/Conversion/ArithToEmitC/ArithToEmitC.cpp
> +      if (roundingModeOp.getRoundingModeAttr())
Can you point the position where these 2 dialects specify the default rounding mode? I don't find that.

2025-01-10 09:50 UTC, jacquesguan commented on mlir/test/Conversion/ArithToEmitC/arith-to-emitc-unsupported.mlir
> +  // expected-error @+1 {{failed to legalize operation 'arith.truncf'}}
Fixed

2025-01-10 10:34 UTC, marbre commented on mlir/lib/Conversion/ArithToEmitC/ArithToEmitC.cpp
> +      if (roundingModeOp.getRoundingModeAttr())
Well at least some ops specify who the rounding is done, see for example https://mlir.llvm.org/docs/Dialects/SPIR-V/#spirvclfma-spirvclfmaop. But I haven't had time to look into `ArithToSPRIV` to see what is the mapping between ops and what is done about rounding in the conversion.

2025-01-13 12:31 UTC, simon-camp commented on mlir/lib/Conversion/ArithToEmitC/ArithToEmitC.cpp
> +      if (roundingModeOp.getRoundingModeAttr())
I assume the arith dialect implicitly follows the LLVM LangRef, which would mean the default of rounding ties to even is used. `arith::TruncF` is also lowered to `llvm::LLVM::FPTruncOp` when missing the rounding mode attr. So this should match with the C behaviour IIUC. But adding a section to the docs about assumptions would be a good idea.

2025-01-15 10:43 UTC, marbre commented on mlir/lib/Conversion/ArithToEmitC/ArithToEmitC.cpp
> +    FpCastOpConversion<arith::TruncFOp>
Please excuse me for not having ask this earlier, but what's the motivation to convert to `emitc.cast` instead of to an `emitc.call` that calls `truncf` or even adding a new `emitc.trunc` op? @simon-camp WDYT?

2025-01-15 11:33 UTC, marbre commented on mlir/lib/Conversion/ArithToEmitC/ArithToEmitC.cpp
> +      if (roundingModeOp.getRoundingModeAttr())
Yeah, I think this should be fine :)

2025-01-15 11:34 UTC, marbre approved these changes

2025-01-15 11:34 UTC, marbre commented on mlir/lib/Conversion/ArithToEmitC/ArithToEmitC.cpp
> +    // Vectors in particular are not supported
NIT:
```suggestion
    // Vectors in particular are not supported.
```

2025-01-16 06:57 UTC, merged