[Clang] Add __builtin_common_reference
llvm/llvm-project pull request #121199
Opened 2024-12-27 10:27 UTC by philnik777

2025-03-31 18:20 UTC, huixie90 requested changes

2025-04-01 15:43 UTC, mordante commented on clang/docs/LanguageExtensions.rst
> +This alias is used for implementing ``std::common_refernce``. If ``std::common_reference`` should contain a ``type``
```suggestion
This alias is used for implementing ``std::common_reference``. If ``std::common_reference`` should contain a ``type``
```

2025-04-11 20:16 UTC, philnik777 commented on clang/lib/Sema/SemaTemplate.cpp
> +        if (S.BuiltinIsConvertible(S.BuiltinAddPointer(T1, TemplateLoc),
I'd rather just implement the paper separately. It feels like there are a few too many conditions to say "partially implemented".

2025-04-11 20:16 UTC, philnik777 commented on libcxx/include/__type_traits/common_reference.h
I've added one.

2025-05-19 08:20 UTC, philnik777 commented on clang/lib/Sema/SemaTemplate.cpp
> +        if (S.BuiltinIsConvertible(S.BuiltinAddPointer(T1, TemplateLoc),
I don't see why updating the non-builtin implementation should block implementing a builtin for it. According to the paper it makes almost no difference, so why is it really important here?

2025-05-24 09:13 UTC, philnik777 commented on clang/lib/Sema/SemaTemplate.cpp
> +        if (S.BuiltinIsConvertible(S.BuiltinAddPointer(T1, TemplateLoc),
Because I don't want to mix adding a builtin with implementing something in libc++.

2025-05-24 09:54 UTC, philnik777 commented on clang/lib/Sema/SemaTemplate.cpp
> +        if (S.BuiltinIsConvertible(S.BuiltinAddPointer(T1, TemplateLoc),
Users see different results based on the compiler version all the time. How is this different?

2025-05-24 11:50 UTC, philnik777 commented on clang/lib/Sema/SemaTemplate.cpp
> +        if (S.BuiltinIsConvertible(S.BuiltinAddPointer(T1, TemplateLoc),
I want to use the libc++ tests though to make sure it works as expected.

2025-05-25 16:16 UTC, frederick-vs-ja commented on clang/lib/Sema/SemaTemplate.cpp
> +            S.BuiltinIsConvertible(S.BuiltinAddPointer(T2, TemplateLoc),
I think P2655 should be treated as a DR per [this SG9 documentation](https://github.com/cplusplus/SG9/blob/b368831c2f8f533cd5c47f088cf3ae1bea9054f4/2022-Telecons.md).

2025-05-26 10:11 UTC, frederick-vs-ja commented on libcxx/include/__type_traits/common_reference.h
> +struct common_reference;
FYI I've opened #141465 to add `_LIBCPP_NO_SPECIALIZATIONS` to `common_reference`. Once the affected test gets fixed, we can also add `_LIBCPP_NO_SPECIALIZATIONS` here.

2025-05-27 14:25 UTC, erichkeane approved these changes
This seems reasonable to me?  I'm not a huge fan of how much is being put into `SemaTemplate.cpp` to support all the builtins though.  I'm wondering if we need to split that up in a follow-up and have a `SemaTemplateBuiltins` for all of these to live.

Please let Aaron/others take a poke at this, and make sure there are a few more Libc++ reviewers to make sure you're all in agreement with how this works (I see the convo that is happening).

Also, should we loop in libstdc++ folks here?

2025-05-27 14:25 UTC, erichkeane commented on clang/include/clang/Basic/BuiltinTemplates.td
> +foreach Ref = ["", "lvalue", "rvalue"] in {
Sorry if I'm being a little dense here... what is going on for the forloop?

2025-05-27 14:25 UTC, erichkeane commented on clang/lib/Sema/SemaTemplate.cpp
> +            S.Context.get__clang_internal_xref_Decl(),
ah, hrmph.... I see now.

2025-10-31 13:01 UTC, philnik777 commented
@huixie90 Are you happy with landing this now?

2025-11-14 15:42 UTC, AaronBallman reviewed
Precommit CI found relevant build failures:
```
  FAILED: tools/clang/lib/Sema/CMakeFiles/obj.clangSema.dir/SemaTemplate.cpp.o 
  sccache /opt/llvm/bin/clang++ -DCLANG_EXPORTS -DGTEST_HAS_RTTI=0 -D_DEBUG -D_GLIBCXX_ASSERTIONS -D_GLIBCXX_USE_CXX11_ABI=1 -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I/home/gha/actions-runner/_work/llvm-project/llvm-project/build/tools/clang/lib/Sema -I/home/gha/actions-runner/_work/llvm-project/llvm-project/clang/lib/Sema -I/home/gha/actions-runner/_work/llvm-project/llvm-project/clang/include -I/home/gha/actions-runner/_work/llvm-project/llvm-project/build/tools/clang/include -I/home/gha/actions-runner/_work/llvm-project/llvm-project/build/include -I/home/gha/actions-runner/_work/llvm-project/llvm-project/llvm/include -gmlt -fPIC -fno-semantic-interposition -fvisibility-inlines-hidden -Werror -Werror=date-time -Werror=unguarded-availability-new -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -pedantic -Wno-long-long -Wc++98-compat-extra-semi -Wimplicit-fallthrough -Wcovered-switch-default -Wno-noexcept-type -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wsuggest-override -Wstring-conversion -Wno-pass-failed -Wmisleading-indentation -Wctad-maybe-unsupported -fdiagnostics-color -ffunction-sections -fdata-sections -fno-common -Woverloaded-virtual -Wno-nested-anon-types -O3 -DNDEBUG -std=c++17  -fno-exceptions -funwind-tables -fno-rtti -UNDEBUG -MD -MT tools/clang/lib/Sema/CMakeFiles/obj.clangSema.dir/SemaTemplate.cpp.o -MF tools/clang/lib/Sema/CMakeFiles/obj.clangSema.dir/SemaTemplate.cpp.o.d -o tools/clang/lib/Sema/CMakeFiles/obj.clangSema.dir/SemaTemplate.cpp.o -c /home/gha/actions-runner/_work/llvm-project/llvm-project/clang/lib/Sema/SemaTemplate.cpp
  /home/gha/actions-runner/_work/llvm-project/llvm-project/clang/lib/Sema/SemaTemplate.cpp:3542:18: error: no matching function for call to 'InstantiateTemplate'
   3542 |       auto BCR = InstantiateTemplate(S, CommonReference,
        |                  ^~~~~~~~~~~~~~~~~~~
  /home/gha/actions-runner/_work/llvm-project/llvm-project/clang/lib/Sema/SemaTemplate.cpp:3215:17: note: candidate function not viable: requires 5 arguments, but 4 were provided
   3215 | static QualType InstantiateTemplate(Sema &S, ElaboratedTypeKeyword Keyword, TemplateName Template,
        |                 ^                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   3216 |                                     ArrayRef<TemplateArgument> Args,
        |                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   3217 |                                     SourceLocation Loc) {
        |                                     ~~~~~~~~~~~~~~~~~~
  /home/gha/actions-runner/_work/llvm-project/llvm-project/clang/lib/Sema/SemaTemplate.cpp:3559:19: error: no matching function for call to 'InstantiateTemplate'
   3559 |     if (auto CT = InstantiateTemplate(S, CommonType, {T1, T2}, TemplateLoc);
        |                   ^~~~~~~~~~~~~~~~~~~
  /home/gha/actions-runner/_work/llvm-project/llvm-project/clang/lib/Sema/SemaTemplate.cpp:3215:17: note: candidate function not viable: requires 5 arguments, but 4 were provided
   3215 | static QualType InstantiateTemplate(Sema &S, ElaboratedTypeKeyword Keyword, TemplateName Template,
        |                 ^                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   3216 |                                     ArrayRef<TemplateArgument> Args,
        |                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   3217 |                                     SourceLocation Loc) {
        |                                     ~~~~~~~~~~~~~~~~~~
  /home/gha/actions-runner/_work/llvm-project/llvm-project/clang/lib/Sema/SemaTemplate.cpp:3762:73: error: too few arguments to function call, expected 6, have 3
   3762 |       return SemaRef.CheckTemplateIdType(HasTypeMember, TemplateLoc, TAs);
        |              ~~~~~~~~~~~~~~~~~~~~~~~~~~~                                ^
  /home/gha/actions-runner/_work/llvm-project/llvm-project/clang/include/clang/Sema/Sema.h:11648:12: note: 'CheckTemplateIdType' declared here
   11648 |   QualType CheckTemplateIdType(ElaboratedTypeKeyword Keyword,
         |            ^                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   11649 |                                TemplateName Template,
         |                                ~~~~~~~~~~~~~~~~~~~~~~
   11650 |                                SourceLocation TemplateLoc,
         |                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~
   11651 |                                TemplateArgumentListInfo &TemplateArgs,
         |                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   11652 |                                Scope *Scope, bool ForNestedNameSpecifier);
         |                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  3 errors generated.
```

2025-11-14 15:42 UTC, AaronBallman commented on clang/include/clang/Basic/BuiltinTemplates.td
> +class Class<string name = "", bit is_variadic = 0> : TemplateArg<name> {
Do we really want these to have default arguments instead of passing `""` in explicitly? I'm worried this makes it easier to add new subclasses that accidentally forget to set the name.

2025-11-19 05:40 UTC, shafik commented on clang/lib/Sema/SemaTemplate.cpp
> +// COND-RES(X, Y) be decltype(false ? declval<X(&)()>()() : declval<Y(&)()>()())
This comment is very opaque, please expand on it.

After looking at the body of the function, it makes more sense (only just) but that is not how this should work. The comment on top of the function should be sufficient for the reader to understand what they expect to find in the body. I should not have to look at the body of the function to get the topline comment.

2025-11-19 05:40 UTC, shafik commented on clang/lib/Sema/SemaTemplate.cpp
> +    if (AddLValue)
`AddLalue` and `AddRvalue` should be exclusive, so this should be an if/else.

2025-11-19 05:40 UTC, shafik commented on clang/lib/Sema/SemaType.cpp
> +  if ((!From->isIncompleteArrayType() && !From->isVoidType() &&
A comment here along the lines of "types must be complete unless they are an incomplete array type or void" also a standard reference would be preferable as well.

2025-11-27 15:05 UTC, philnik777 commented on clang/lib/Sema/SemaTemplate.cpp
> +// COND-RES(X, Y) be decltype(false ? declval<X(&)()>()() : declval<Y(&)()>()())
What exactly do you want? I'm quoting the standard here, just like everywhere else.

2025-11-27 15:20 UTC, philnik777 commented on clang/include/clang/Basic/BuiltinTemplates.td
> +class Class<string name = "", bit is_variadic = 0> : TemplateArg<name> {
Currently the names are purely cosmetic in nature except when you have NTTPs which rely on a previous type, so I'm not too worried if someone forgets. I wanted to auto-generate docs with this at some point, but I didn't get to it yet.

2025-11-29 09:19 UTC, huixie90 approved these changes
libc++ changes LGTM. Leave the final approval to the clang folks

2025-12-01 14:42 UTC, philnik777 commented
Landing for now, since I don't think there are big concerns anymore and I'd like to avoid merge conflicts. @shafik @AaronBallman if you have any more comments I'm happy to address them post-commit.

2025-12-01 14:42 UTC, merged

2025-12-02 16:36 UTC, nico commented
This breaks building the libc++ module in the chromium build for me:

```
../../../../llvm-project/out/gn/bin/clang++ -MD -MF clang_arm64_for_rust_host_build_tools/obj/buildtools/third_party/libc++/std/module.pcm.d -D__ARM_NEON__=1 -DCR_XCODE_BUILD=17B100 -D_LIBCPP_HARDENING_MODE=_LIBCPP_HARDENING_MODE_EXTENSIVE -D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS -D_LIBCXXABI_DISABLE_VISIBILITY_ANNOTATIONS -D_LIBCPP_INSTRUMENTED_WITH_ASAN=0 -DCR_LIBCXX_REVISION=91c45fc28459e814889633be985b698c5e8050b4 -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -D_LIBCPP_BUILDING_LIBRARY -I../.. -Iclang_arm64_for_rust_host_build_tools/gen -fno-delete-null-pointer-checks -fno-strict-overflow -fno-ident -fno-math-errno -fno-strict-aliasing -fstack-protector -fcolor-diagnostics -fmerge-all-constants -fno-sized-deallocation -fcrash-diagnostics-dir=../clang-crashreports -mllvm -instcombine-lower-dbg-declare=0 -mllvm -split-threshold-for-reg-with-hint=0 -ffp-contract=off -fcomplete-member-pointers --target=arm64-apple-macos -mno-outline -Wno-builtin-macro-redefined -D__DATE__= -D__TIME__= -D__TIMESTAMP__= -ffile-compilation-dir=. -no-canonical-prefixes -Xclang -fmodule-file-home-is-cwd -Xclang -fmodules-cache-path=/not_exist_dummy_dir --warning-suppression-mappings=../../build/config/warning_suppression.txt -ftrivial-auto-var-init=pattern -O2 -fno-omit-frame-pointer -g0 -isysroot ../../../../../../../Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX26.1.sdk -mmacos-version-min=12.0 -fsanitize=array-bounds -fsanitize-trap=array-bounds -fvisibility=hidden -Wheader-hygiene -Wstring-conversion -Wtautological-overlap-compare -fstrict-aliasing -Wundef -fPIC -Wall -Wno-unused-variable -Wno-c++11-narrowing -Wno-unused-but-set-variable -Wunguarded-availability -Wno-missing-field-initializers -Wno-unused-parameter -Wno-psabi -Wloop-analysis -Wno-unneeded-internal-declaration -Wno-cast-function-type -Wno-thread-safety-reference-return -Wno-nontrivial-memcall -Wno-uninitialized-const-pointer -Wexit-time-destructors -Werror -Wno-exit-time-destructors -std=c++20 -Wno-trigraphs -fno-exceptions -fno-rtti -nostdinc++ -isystemgen/third_party/libc++/src/include -isystem../../third_party/libc++abi/src/include -fvisibility-inlines-hidden -Wno-invalid-offsetof -Wenum-compare-conditional -Wno-nullability-completeness -fbuiltin-module-map -fmodule-map-file=gen/third_party/libc++/src/include/module.modulemap -fmodule-map-file=../../../../../../../Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX26.1.sdk/usr/include/DarwinBasic.modulemap -fmodule-map-file=../../../../../../../Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX26.1.sdk/usr/include/DarwinFoundation1.modulemap -fmodule-map-file=../../../../../../../Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX26.1.sdk/usr/include/DarwinFoundation2.modulemap -fmodule-map-file=../../../../../../../Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX26.1.sdk/usr/include/DarwinFoundation3.modulemap -fmodule-file=_AvailabilityInternal=clang_arm64_for_rust_host_build_tools/obj/buildtools/third_party/libc++/_AvailabilityInternal/DarwinFoundation1.pcm -fmodule-file=_Builtin_float=clang_arm64_for_rust_host_build_tools/obj/buildtools/third_party/libc++/_Builtin_float/module.pcm -fmodule-file=_Builtin_inttypes=clang_arm64_for_rust_host_build_tools/obj/buildtools/third_party/libc++/_Builtin_inttypes/module.pcm -fmodule-file=_Builtin_limits=clang_arm64_for_rust_host_build_tools/obj/buildtools/third_party/libc++/_Builtin_limits/module.pcm -fmodule-file=_Builtin_stdalign=clang_arm64_for_rust_host_build_tools/obj/buildtools/third_party/libc++/_Builtin_stdalign/module.pcm -fmodule-file=_Builtin_stdarg=clang_arm64_for_rust_host_build_tools/obj/buildtools/third_party/libc++/_Builtin_stdarg/module.pcm -fmodule-file=_Builtin_stddef=clang_arm64_for_rust_host_build_tools/obj/buildtools/third_party/libc++/_Builtin_stddef/module.pcm -fmodule-file=_Builtin_stdint=clang_arm64_for_rust_host_build_tools/obj/buildtools/third_party/libc++/_Builtin_stdint/module.pcm -fmodule-file=_DarwinFoundation1=clang_arm64_for_rust_host_build_tools/obj/buildtools/third_party/libc++/_DarwinFoundation1/DarwinFoundation1.pcm -fmodule-file=_DarwinFoundation2=clang_arm64_for_rust_host_build_tools/obj/buildtools/third_party/libc++/_DarwinFoundation2/DarwinFoundation2.pcm -fmodule-file=_DarwinFoundation3=clang_arm64_for_rust_host_build_tools/obj/buildtools/third_party/libc++/_DarwinFoundation3/DarwinFoundation3.pcm -fmodule-file=std_core=clang_arm64_for_rust_host_build_tools/obj/buildtools/third_party/libc++/std_core/module.pcm -fmodule-file=std_ctype_h=clang_arm64_for_rust_host_build_tools/obj/buildtools/third_party/libc++/std_ctype_h/module.pcm -fmodule-file=std_errno_h=clang_arm64_for_rust_host_build_tools/obj/buildtools/third_party/libc++/std_errno_h/module.pcm -fmodule-file=std_fenv_h=clang_arm64_for_rust_host_build_tools/obj/buildtools/third_party/libc++/std_fenv_h/module.pcm -fmodule-file=std_float_h=clang_arm64_for_rust_host_build_tools/obj/buildtools/third_party/libc++/std_float_h/module.pcm -fmodule-file=std_inttypes_h=clang_arm64_for_rust_host_build_tools/obj/buildtools/third_party/libc++/std_inttypes_h/module.pcm -fmodule-file=std_math_h=clang_arm64_for_rust_host_build_tools/obj/buildtools/third_party/libc++/std_math_h/module.pcm -fmodule-file=std_private_mbstate_t=clang_arm64_for_rust_host_build_tools/obj/buildtools/third_party/libc++/std_private_mbstate_t/module.pcm -fmodule-file=std_string_h=clang_arm64_for_rust_host_build_tools/obj/buildtools/third_party/libc++/std_string_h/module.pcm -fmodule-file=std_uchar_h=clang_arm64_for_rust_host_build_tools/obj/buildtools/third_party/libc++/std_uchar_h/module.pcm -fmodule-file=std_wctype_h=clang_arm64_for_rust_host_build_tools/obj/buildtools/third_party/libc++/std_wctype_h/module.pcm -fmodule-file=xlocale=clang_arm64_for_rust_host_build_tools/obj/buildtools/third_party/libc++/xlocale/DarwinFoundation3.pcm -fmodule-name=std -c -x c++ -Xclang -emit-module gen/third_party/libc++/src/include/module.modulemap -o clang_arm64_for_rust_host_build_tools/obj/buildtools/third_party/libc++/std/module.pcm
In module 'std_core' imported from gen/third_party/libc++/src/include/__algorithm/comp.h:13:
gen/third_party/libc++/src/include/__type_traits/is_convertible.h:22:101: error: definition of '__nat' must be imported from module 'std_core.type_traits.nat' before it is required
   22 | struct _LIBCPP_NO_SPECIALIZATIONS is_convertible : integral_constant<bool, __is_convertible(_T1, _T2)> {};
      |                                                                                                     ^
gen/third_party/libc++/src/include/__filesystem/path.h:150:37: note: in instantiation of template class 'std::is_convertible<std::__nat, std::input_iterator_tag>' requested here
  150 | template <class _Iter, bool _IsIt = __has_input_iterator_category<_Iter>::value, class = void>
      |                                     ^
gen/third_party/libc++/src/include/__filesystem/path.h:171:48: note: in instantiation of default argument for '__is_pathable_iter<string_type>' required here
  171 |           bool _IsIterT     = !_IsCharIterT && __is_pathable_iter<_Tp>::value>
      |                                                ^~~~~~~~~~~~~~~~~~~~~~~
gen/third_party/libc++/src/include/__filesystem/path.h:384:59: note: in instantiation of default argument for '__is_pathable<string_type, true, false>' required here
  384 |   using _EnableIfPathable _LIBCPP_NODEBUG = __enable_if_t<__is_pathable<_SourceOrIter>::value, _Tp>;
      |                                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
gen/third_party/libc++/src/include/__filesystem/path.h:412:36: note: in instantiation of template type alias '_EnableIfPathable' requested here
  412 |   template <class _ [...]

2025-12-02 19:54 UTC, nico commented
Here's another snippet that builds fine before this patch but not after it:

```
#include <type_traits>

template <typename T>
class Foo;

struct Baz {
  Baz() = default;

#if 0
  Baz(Foo<int> foo) {}
#else
  template <typename T>
    requires(std::is_convertible_v<T, Foo<int>>)
  explicit Baz(T foo) {}
#endif
};

struct Quux {
  mutable Baz baz;
};
```

```
# libc++ built as described in libcxx/docs/VendorDocumentation.rst,
# but with -DCMAKE_INSTALL_PREFIX=$PWD/install-libcxx added to cmake invocation
# ninja -C build cxx cxxabi unwind
# ninja -C build install-cxx install-cxxabi install-unwind

out/gn/bin/clang -c repro.cc -std=c++20 -nostdinc++ -isystem install-libcxx/include/c++/v1 
```

Before, this built fine. After, it yields

```
% out/gn/bin/clang -c repro.cc -std=c++20 -nostdinc++ -isystem install-libcxx/include/c++/v1 
In file included from repro.cc:1:
In file included from install-libcxx/include/c++/v1/type_traits:491:
install-libcxx/include/c++/v1/__type_traits/is_convertible.h:26:96: error: implicit instantiation of undefined template 'Foo<int>'
   26 | _LIBCPP_NO_SPECIALIZATIONS inline constexpr bool is_convertible_v = __is_convertible(_From, _To);
      |                                                                                                ^
repro.cc:13:19: note: in instantiation of variable template specialization 'std::is_convertible_v<Baz, Foo<int>>' requested here
   13 |     requires(std::is_convertible_v<T, Foo<int>>)
      |                   ^
repro.cc:13:14: note: while substituting template arguments into constraint expression here
   13 |     requires(std::is_convertible_v<T, Foo<int>>)
      |              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
repro.cc:6:34: note: while checking constraint satisfaction for template 'Baz<Baz>' required here
    6 | struct __attribute__((lockable)) Baz {
      |                                  ^~~
repro.cc:6:34: note: while substituting deduced template arguments into function template 'Baz' [with T = Baz]
repro.cc:18:8: note: while declaring the implicit copy constructor for 'Quux'
   18 | struct Quux {
      |        ^
repro.cc:4:7: note: template is declared here
    4 | class Foo;
      |       ^
1 error generated.
```

The snippet is a bit weird! The motivation is that it wants to say `Baz(Foo<int> foo) {}`, but `Foo<T>` is forward-declared, so it uses that template hack, and everyone who wants to call that ctor has to make sure to include a definition of `Foo<>`.

This worked before this change, but not after. Was that behavior change intentional? (The repro only works if the `mutable` is present somehow, which suggests that this isn't intentional.)

Maybe this is also what's causing the libc++-built-as-module diag mentioned above?

2025-12-03 00:37 UTC, nico commented
I reverted this in e05fffbbc54d201a60e55e8c051bad81eaebd69a for now, per Discord.

2025-12-11 02:31 UTC, shafik commented on clang/lib/Sema/SemaTemplate.cpp
> +// COND-RES(X, Y) be decltype(false ? declval<X(&)()>()() : declval<Y(&)()>()())
I stand by my original review, it is pretty opaque comment. At minimum if at least had a stable name a paragraph number I could jump to the standard and it would more obvious.