[libc++][test] Refactor tests for ranges::swap_range algorithms
llvm/llvm-project pull request #121138
Opened 2024-12-26 03:52 UTC by winner245

This PR refactors tests for `ranges::swap_range`, `std::{swap_range, iter_swap, swap}` algorithm.

2025-02-05 17:50 UTC, ldionne requested changes
Thanks a lot for the improvements, I do have some comments before we merge this but it generally looks really good.

2025-02-05 17:50 UTC, ldionne commented on libcxx/test/std/algorithms/alg.modifying.operations/alg.swap/iter_swap.pass.cpp
>  #include <cassert>
Above in the comment:

```
// template<Iterator Iter1, Iterator Iter2>
//   requires HasSwap<Iter1::reference, Iter2::reference>
// void iter_swap(Iter1 a, Iter2 b); // constexpr since C++20
```

2025-02-05 17:50 UTC, ldionne commented on libcxx/test/std/algorithms/alg.modifying.operations/alg.swap/ranges.swap_ranges.pass.cpp
> +  types::for_each(cpp20_proxy_in_iterator_list<int*>(), TestProxyInIterators());
```suggestion
  types::for_each(types::cpp20_input_iterator_list<int*>(), []<class Iter1> {
    types::for_each(types::cpp20_input_iterator_list<int*>(), []<class Iter2> {
      test_iterators<Iter1, Iter2>();
      test_iterators<ProxyIterator<Iter1>, ProxyIterator<Iter2>>();
    });
  });
```

2025-02-05 17:50 UTC, ldionne commented on libcxx/test/std/algorithms/alg.modifying.operations/alg.swap/ranges.swap_ranges.pass.cpp
> +using cpp20_proxy_in_iterator_list =
With my suggested refactoring below, I think this can go away.

2025-02-05 17:50 UTC, ldionne commented on libcxx/test/std/algorithms/alg.modifying.operations/alg.swap/swap_ranges.pass.cpp
> +    std::swap(a, b);
I don't understand why we were (and are still) testing `std::swap` in this file. These tests for `std::swap` seem to belong in `libcxx/test/std/utilities/utility/utility.swap/swap_array.pass.cpp` instead. Perhaps you could ensure that we already have appropriate coverage in that file, and then move to testing `std::swap_ranges` exclusively in this file.

2025-02-05 17:50 UTC, ldionne commented on libcxx/test/std/algorithms/alg.modifying.operations/alg.swap/swap_ranges.pass.cpp
> +int main(int, char**) {
Let's introduce a single top-level `constexpr bool test()` function and transform `main` into:

```
test();
#if TEST_STD_VER
static_assert(test);
#endif
```

like we usually do.

And once that's done, you can inline some functions like `test_unq_ptr()` and `test_ptr()` into `test()` itself, which would look like:

```c++
constexpr bool test() {
  test_simple_cases();
  types::for_each(types::forward_iterator_list<std::unique_ptr<int>*>(), TestUnqPtr());
  types::for_each(types::forward_iterator_list<int*>(), TestPtr());
  return true;
}
```

You may also be able to templatize `test_simple_cases()` on an iterator type to increase the coverage while we're at it.

2025-02-05 17:50 UTC, ldionne commented on libcxx/test/std/algorithms/alg.modifying.operations/alg.swap/swap_ranges.pass.cpp
> +struct TestUnqPtr {
If you end up keeping this structure, I would rename it to `TestUniquePtr` -- it's more readable and we don't lose much from having a few additional characters.

2025-02-09 03:43 UTC, winner245 commented on libcxx/test/std/algorithms/alg.modifying.operations/alg.swap/ranges.swap_ranges.pass.cpp
> +  types::for_each(cpp20_proxy_in_iterator_list<int*>(), TestProxyInIterators());
Thanks! This suggested refactoring is really nice! It further simplifies the test.

2025-02-09 03:43 UTC, winner245 commented on libcxx/test/std/algorithms/alg.modifying.operations/alg.swap/ranges.swap_ranges.pass.cpp
> +using cpp20_proxy_in_iterator_list =
Yes, with the suggested approach implemented, this redundant code has disappeared, and the entire test is much cleaner.

2025-02-09 03:43 UTC, winner245 commented on libcxx/test/std/algorithms/alg.modifying.operations/alg.swap/swap_ranges.pass.cpp
> +    std::swap(a, b);
I completely agree that we should focus on testing `std::swap_ranges` exclusively within this file. Therefore, I've moved these tests for `std::swap` into `swap_array.pass.cpp`. 

Additionally, I think these tests can still provide value if we modify them to use `std::swap_range` instead of `std::swap`, as these tests address two-dimensionally arrays which are not considered by any other tests in this file. Thus, I've opted to include these modified tests in `test_simple_cases` by replacing `std::swap` with `std::swap_range`.

2025-02-09 03:43 UTC, winner245 commented on libcxx/test/std/algorithms/alg.modifying.operations/alg.swap/swap_ranges.pass.cpp
> +int main(int, char**) {
> Let's introduce a single top-level `constexpr bool test()` function and transform `main` into:
>
> ```
> test();
> #if TEST_STD_VER
> static_assert(test);
> #endif
> ```
> 
> like we usually do.

Thank you for your detailed suggestions. I've introduced a top-level `TEST_CONSTEXPR_CXX20 test()` function. However, I face a dilemma regarding the inclusion of `std::unique_ptr` tests. Since `std::unique_ptr` is only constexpr since C++23, I cannot incorporate its tests within the `test()` function which is constexpr since C++20. If I ignore this and include the `std::unique_ptr` tests within `test()`, we can only carry out `static_assert(test())` for C++23 and later, which would drop constexpr test coverage for other tests such as `test_simple_cases` and `test_ptr` that are constexpr since C++20. Considering this, I only incorporate all  other tests except the tests for `unique_ptr` in the top-level `test()` function, and maintain a separate top-level function `test_unique_ptr()` for `unique_ptr`. This allows us to do `static_assert(test())` for C++20 and `static_assert(test_unique_ptr())` for C++23. 

> You may also be able to templatize test_simple_cases() on an iterator type to increase the coverage while we're at it.
`test_simple_cases()`

I find it somewhat challenging to templatize `test_simple_cases()` because it currently contains tests for both one- and two- dimensional arrays, which have different iterator types. However, the existing iterator wrapper type list, such as `types::forward_iterator_list<Iter>()`, can only be used for the same `Iter` type. If we were to templatize `test_simple_cases()`, the first test would become the same test in `TestPtr`. Considering these considerations, I'd rather keep `test_simple_cases()` simple by including the 3 simple tests, as its name suggests.

2025-02-09 03:43 UTC, winner245 commented on libcxx/test/std/algorithms/alg.modifying.operations/alg.swap/swap_ranges.pass.cpp
> +struct TestUnqPtr {
Agreed! I've renamed it to `TestUniquePtr` for better readability.

2025-02-10 15:08 UTC, winner245 commented on libcxx/test/std/algorithms/alg.modifying.operations/alg.swap/swap_ranges.pass.cpp
> +int main(int, char**) {
After further considerations, I managed to implement a top-level `test()` function that integrates tests for `std::unique_ptr` and other tests. The difference in `constexpr` evaluation is now handled through preprocessing directives and condition checks with `std::is_constant_evaluated()`. 

Furthermore, `test_simple_cases()` has been templated as suggested. It now utilizes template template parameters instead of regular template parameters to accommodate different `Iter` types used by different tests within `test_simple_cases()`.

2025-02-19 17:18 UTC, ldionne approved these changes
LGTM with minor comments. Thanks a lot for the improved test coverage, that is awesome!

2025-02-19 17:18 UTC, ldionne commented on libcxx/test/std/algorithms/alg.modifying.operations/alg.swap/swap_ranges.pass.cpp
> +#endif
```suggestion
if (TEST_STD_AT_LEAST_23_OR_RUNTIME_EVALUATED)
  types::for_each(types::forward_iterator_list<std::unique_ptr<int>*>(), TestUniquePtr());
```

This is defined in `test_macros.h`. I'm not a huge fan of it, but it does simplify this code a lot. The alternative would be

```
if (!TEST_IS_CONSTANT_EVALUATED || TEST_STD_VER >= 23)
  types::for_each(types::forward_iterator_list<std::unique_ptr<int>*>(), TestUniquePtr());
```

This may trigger tautological comparison warnings though.

2025-02-19 17:18 UTC, ldionne commented on libcxx/test/std/utilities/utility/utility.swap/swap_array.pass.cpp
> +TEST_CONSTEXPR_CXX23 bool test_unique_ptr() {
You can actually inline this into `test` below and use the `IS_CONSTANT_EVALUATED` trick to only run that part of the function when it can be run. That will simplify your `main()`.

2025-02-21 21:35 UTC, winner245 commented on libcxx/test/std/algorithms/alg.modifying.operations/alg.swap/swap_ranges.pass.cpp
> +#endif
Thanks! This works really well!

2025-02-21 21:35 UTC, winner245 commented on libcxx/test/std/utilities/utility/utility.swap/swap_array.pass.cpp
> +TEST_CONSTEXPR_CXX23 bool test_unique_ptr() {
I tried to inline `test_unique_ptr()` into `test()`, but encountered a `[stage2 (generic-cxx20, clang-21, clang++-21)](https://github.com/llvm/llvm-project/actions/runs/13449074444/job/37621070195?pr=121138#logs)` CI failure. The issue arises because the top-level `test()` is constexpr since C++20 (declared via `TEST_CONSTEXPR_CXX20`), while `unique_ptr` is constexpr since C++23. Thus, inlining the code involving `unique_ptr` directly inside `test()` results in an error: `variable of non-literal type 'std::unique_ptr<int>' cannot be defined in a constexpr function before C++23`.

```cpp
TEST_CONSTEXPR_CXX20 bool test() { 
  // error: variable of non-literal type 'std::unique_ptr<int>' cannot be defined in a constexpr function before C++23
  if (TEST_STD_VER >= 23 || !TEST_IS_CONSTANT_EVALUATED)
    std::unique_ptr<int> p(new int); 

  return true;
}
```

A reproducer of this problem is avaialble: https://godbolt.org/z/Kzn96GEM9

To resolve this, I moved the test for `unique_ptr` into a separate function, `test_unique_ptr()`, which can be declared with `TEST_CONSTEXPR_CXX23`. Then, within `test()`, I used the suggested `TEST_IS_CONSTANT_EVALUATED` trick:

```cpp
TEST_CONSTEXPR_CXX23 void test_unique_ptr() {
  std::unique_ptr<int> p(new int);
}
 
TEST_CONSTEXPR_CXX20 bool test() { 
  if (TEST_STD_VER >= 23 || !std::__libcpp_is_constant_evaluated())
    test_unique_ptr();

  return true;
}
```

This resolves the CI failure. I am not sure if there is a better way to resolve this. I found reverting to the `test_unique_ptr()` function a simple fix.

2025-02-26 16:47 UTC, ldionne approved these changes
Thanks a lot for the refactoring!

2025-02-26 16:47 UTC, ldionne commented on libcxx/test/std/algorithms/alg.modifying.operations/alg.swap/swap_ranges.pass.cpp
> +      int a[] = {1, 2, 3};
This is fine since it's a pre-existing issue, but as a simple follow-up we should add coverage for sequences of more than 3 elements.

2025-02-26 16:47 UTC, ldionne commented on libcxx/test/std/utilities/utility/utility.swap/swap_array.pass.cpp
> +  // because `test()` is constexpr since C++20.
```suggestion
```

2025-02-26 16:49 UTC, merged