[GlobalISel] Catching inconsistencies in load memory, result, and range metadata type
llvm/llvm-project pull request #121247
Opened 2024-12-28 04:12 UTC by parsifal-47

This is a fix for:
https://github.com/llvm/llvm-project/issues/97290
Please let me know if that is the right way to address the issue. Thank you!

2024-12-28 04:13 UTC, parsifal-47 commented
@arsenm please take a look when you have a chance, thank you!

2025-01-03 16:55 UTC, parsifal-47 commented
The failure does not look related to the change:
```
# | /var/lib/buildkite-agent/builds/linux-56-59b8f5d88-54tww-1/llvm-project/github-pull-requests/libcxx/test/benchmarks/locale/num_get.bench.cpp:32:1: error: template specialization requires 'template<>'
# |    32 | BENCHMARK(BM_num_get<bool>);
```
@arsenm please take a look when you have a chance, thank you!

2025-01-04 09:56 UTC, arsenm requested changes

2025-01-04 09:56 UTC, arsenm commented on llvm/test/CodeGen/AMDGPU/GlobalISel/test_g_load_vector_to_scalar.mir
> +# RUN: not --crash llc -mtriple=amdgcn-mesa-mesa3d -mcpu=tahiti -run-pass=amdgpu-prelegalizer-combiner -verify-machineinstrs %s -o -
This belongs in test/MachineVerifier, and can use -run-pass=none (and does not need -verify-machineinstrs).

You should also include all the cases in the test I added to the bug (you'll probably need to merge the different MIR instructions into one function to test them in one mir file)

2025-01-04 09:56 UTC, arsenm commented on llvm/lib/CodeGen/MachineVerifier.cpp
> +        if (MMO.getRanges() && (ValTy.isVector() != MMO.getType().isVector())) {
This isn't quite right. You're checking a different condition than #97290 is asking for. Neither of the checked types are from MMO.getRanges. We probably should have a similar check, without requiring ranges, but I believe we're relying on the current behavior so it's beyond the scope of this patch.

Instead you should be verifying the IR type in MMO.getRanges() against ValTy and MMO.getType()

2025-01-05 15:54 UTC, parsifal-47 commented on llvm/test/CodeGen/AMDGPU/GlobalISel/test_g_load_vector_to_scalar.mir
> +# RUN: not --crash llc -mtriple=amdgcn-mesa-mesa3d -mcpu=tahiti -run-pass=amdgpu-prelegalizer-combiner -verify-machineinstrs %s -o -
Moved and updated, thank you!

2025-01-05 16:00 UTC, parsifal-47 commented on llvm/lib/CodeGen/MachineVerifier.cpp
> +        if (MMO.getRanges() && (ValTy.isVector() != MMO.getType().isVector())) {
This is something I likely do not understand,
I can get a type from range for example like this:
`mdconst::dyn_extract<ConstantInt>(MMO.getRanges()->getOperand(0))->getType()`
but there is no other option but ConstantInt, so it cannot be vector, and that was the reason I checked for range presence because I was thinking it indicates scalar nature of the value.
Let's assume, I have this type now, what should I check for, should int type of the range be equal to ValTy?
Should I check all three to be the same? Or should I just check for vector vs scalar mismatches?

Thank you for your help!

2025-01-06 03:56 UTC, arsenm commented on llvm/lib/CodeGen/MachineVerifier.cpp
> +        if (MMO.getRanges() && (ValTy.isVector() != MMO.getType().isVector())) {
You get the scalar integer type out of `mdconst::extract<ConstantInt>(MMO.getRanges()->getOperand(0))->getType()`. You need to verify the MIR result type has the same scalar type, something like `ValTy.getScalarType()->getSizeInBits() == mdconst::extract<ConstantInt>(MMO.getRanges()->getOperand(0)).getIntegerType()->getBitWidth()`. Whether the MIR type is vector isn't as significant as whether the element type matches the range IR type

2025-01-06 16:01 UTC, parsifal-47 commented on llvm/lib/CodeGen/MachineVerifier.cpp
> +        if (MMO.getRanges() && (ValTy.isVector() != MMO.getType().isVector())) {
I am not sure I understood it correctly, if I get the bitWidth, it will be 64 in all three cases and types will be compatible, but if I take actual bits that are used by lower and higher bounds of the range, it breaks existing tests. Please take a look at the updated code and let me know what am I missing. Thank you for your patience!

2025-01-06 16:30 UTC, arsenm commented on llvm/lib/CodeGen/MachineVerifier.cpp
> +            ConstantInt *i = mdconst::dyn_extract<ConstantInt>(o);
```suggestion
            ConstantInt *i = mdconst::extract<ConstantInt>(o);
```

2025-01-06 16:30 UTC, arsenm commented on llvm/test/MachineVerifier/test_g_load_vector_to_scalar.mir
> +# RUN: not --crash llc -mtriple=amdgcn-mesa-mesa3d -mcpu=tahiti -run-pass=none %s -o -
```suggestion
# RUN: not --crash llc -mtriple=amdgcn-mesa-mesa3d -mcpu=tahiti -run-pass=none %s -filetype=null 2>&1 | FileCheck %s
```

You need to redirect stderr to get the error messages

2025-01-06 16:30 UTC, arsenm commented on llvm/test/MachineVerifier/test_g_load_vector_to_scalar.mir
> +    ; CHECK: Bad machine code: range is incompatible with the value it gets assigned to
I think the verifier aborts after the first function fails, but keeps printing errors in the functions. As a consequence you would need all of these cases tested in one function

2025-01-06 16:30 UTC, arsenm commented on llvm/lib/CodeGen/MachineVerifier.cpp
> +            APInt reversed(i->getValue());
You shouldn't need to consider anything about the value of the range, only the type

2025-01-06 16:31 UTC, arsenm commented on llvm/lib/CodeGen/MachineVerifier.cpp
> +        if (MMO.getRanges() && (ValTy.isVector() != MMO.getType().isVector())) {
This set of IR tests happens to only use 64-bit values 

> , it breaks existing tests.

It's possible there are broken tests or bugs, that's why we write these verifiers

2025-01-06 17:55 UTC, parsifal-47 commented on llvm/lib/CodeGen/MachineVerifier.cpp
> +            APInt reversed(i->getValue());
This is something I still do not understand:

> The verifier should reject cases like this:
> ...
> !0 = !{i64 -4294967295, i64 4294967296}
> ...
> %3:_(<2 x s32>) = G_LOAD %0(p1) :: (volatile load (s64), align 4, !range !0, addrspace 1)

but if we get the information about the type, it is "i64" and there is a match between 2*32 == 64, no issues, you mentioned vector or scalar is not important, what would be the reason to reject this instruction?

2025-01-09 03:26 UTC, parsifal-47 commented on llvm/lib/CodeGen/MachineVerifier.cpp
> +            APInt reversed(i->getValue());
@arsenm could you please help me understand this piece, it looks like if I rely on type information alone, the cases that are mentioned in the description of this bug would be still legal. Thank you!

2025-01-09 15:06 UTC, parsifal-47 commented on llvm/lib/CodeGen/MachineVerifier.cpp
> +            APInt reversed(i->getValue());
thank you for the explanation, I will get back with updated code

2025-01-10 15:34 UTC, parsifal-47 commented on llvm/lib/CodeGen/MachineVerifier.cpp
> +            APInt reversed(i->getValue());
updated, please take a look

2025-01-10 15:34 UTC, parsifal-47 commented on llvm/test/MachineVerifier/test_g_load_vector_to_scalar.mir
> +    ; CHECK: Bad machine code: range is incompatible with the value it gets assigned to
not sure if I understood it correctly, I put them all in one function, but now they look too similar, please take a look, thank you!

2025-01-13 22:36 UTC, parsifal-47 commented
@arsenm please take a look when you have a chance, I think I resolved all your comments, but feel free to add more, thank you!

2025-01-15 04:24 UTC, arsenm reviewed
Change essentially LGTM with some rephrasing of the message and some more variety in the test

2025-01-15 04:24 UTC, arsenm commented on llvm/test/MachineVerifier/test_g_incompatible_range.mir
> +  define void @range_metadata_sext_i33_signed_range_i64_load_as_v2i32() {
```suggestion
  define void @mismatched_range_type() {
```

2025-01-15 04:24 UTC, arsenm commented on llvm/test/MachineVerifier/test_g_incompatible_range.mir
> +name:            range_metadata_sext_i33_signed_range_i64_load_as_v2i32
```suggestion
name:            mismatched_range_type
```

2025-01-15 04:24 UTC, arsenm commented on llvm/test/MachineVerifier/test_g_incompatible_range.mir
> +    %3:_(<2 x s32>) = G_LOAD %0(p1) :: (volatile load (s64), align 4, !range !1, addrspace 1)
All 3 of these loads appear to be testing the same thing

2025-01-15 04:24 UTC, arsenm commented on llvm/lib/CodeGen/MachineVerifier.cpp
> +            report("range is incompatible with the value it gets assigned to",
```suggestion
            report("range is incompatible with the result type",
```

2025-01-15 04:24 UTC, arsenm commented on llvm/test/MachineVerifier/test_g_incompatible_range.mir
> +    %4:_(<2 x s32>) = G_LOAD %0(p1) :: (volatile load (s64), align 4, !range !0, addrspace 1)
```suggestion
    %4:_(p0) = G_LOAD %0(p1) :: (volatile load (s64), align 4, !range !0, addrspace 1)
```

Test with a pointer?

2025-01-15 04:24 UTC, arsenm commented on llvm/test/MachineVerifier/test_g_incompatible_range.mir
> +    %5:_(<2 x s32>) = G_LOAD %0(p1) :: (volatile load (s64), align 4, !range !0, addrspace 1)
```suggestion
    %5:_(<2 x p0>) = G_LOAD %0(p1) :: (volatile load (s64), align 4, !range !0, addrspace 1)
```

Test with vector of pointer?

2025-01-15 15:17 UTC, parsifal-47 commented on llvm/test/MachineVerifier/test_g_incompatible_range.mir
> +    %3:_(<2 x s32>) = G_LOAD %0(p1) :: (volatile load (s64), align 4, !range !1, addrspace 1)
if I understand correctly, this should be resolved because I applied suggested changes

2025-01-15 15:20 UTC, parsifal-47 commented
> Change essentially LGTM with some rephrasing of the message and some more variety in the test

Thank you for the review and code suggestions, all should be resolved now!

2025-01-16 06:05 UTC, arsenm reviewed
Close, just a little more test cleanup

2025-01-16 06:05 UTC, arsenm commented on llvm/test/CodeGen/AMDGPU/GlobalISel/legalize-load-memory-metadata.mir
> +  !3 = !{i32 0, i32 1048575}
This shouldn't touch the input IR. However this makes me realize we are violating the principle that we shouldn't touch the underlying IR in codegen. I guess global metadata constants could be an exception

2025-01-16 06:05 UTC, arsenm commented on llvm/test/CodeGen/AMDGPU/GlobalISel/regbankselect-split-scalar-load-metadata.mir
> +  !3 = !{i32 0, i32 4294967295}
Same, shouldn't need to modify the input IR

2025-01-16 06:05 UTC, arsenm commented on llvm/test/MachineVerifier/test_g_incompatible_range.mir
> +  !1 = !{i64 -8589934591, i64 8589934592}
We don't need 2 i64 ranges with different values. Just need one, or test multiple range types for different instruction types

2025-01-22 15:25 UTC, parsifal-47 commented on llvm/test/CodeGen/AMDGPU/GlobalISel/legalize-load-memory-metadata.mir
> +  !3 = !{i32 0, i32 1048575}
got it, thank you!

2025-01-22 15:25 UTC, parsifal-47 commented on llvm/test/CodeGen/AMDGPU/GlobalISel/regbankselect-split-scalar-load-metadata.mir
> +  !3 = !{i32 0, i32 4294967295}
fixed, thank you!

2025-01-22 21:19 UTC, parsifal-47 commented
I noticed that tests are now failing, let me check the details and get back to you

2025-01-23 15:19 UTC, parsifal-47 commented on llvm/test/CodeGen/AMDGPU/GlobalISel/regbankselect-split-scalar-load-metadata.mir
> +  !3 = !{i32 0, i32 4294967295}
the instruction here:
```
    %1:_(<3 x s32>) = G_LOAD %0 :: (load (<3 x s32>), align 8, addrspace 4, !range !3)
```
how would you recommend to alter the test to make it pass?

2025-01-23 15:28 UTC, arsenm approved these changes
LGTM

2025-01-24 05:33 UTC, arsenm commented
Test still failing

2025-01-24 15:45 UTC, parsifal-47 commented
> Test still failing

Should be good now, but
1. switching from checking value type to rhs makes new negative test to pass
2. this in turn made me reverse the change for `legalize-load-memory-metadata.mir`
3. multiple checks for error messages within one negative test do not work because it crashes once, I can split three negative cases in three files or keep single check for error message

Let me know what do you think, thank you!

2025-01-24 16:04 UTC, arsenm commented on llvm/test/MachineVerifier/test_g_incompatible_range.mir
> +# RUN: not --crash llc -o - -mtriple=amdgcn-mesa-mesa3d -mcpu=tahiti -run-pass=none %s 2>&1 | FileCheck %s
This does not need -o and should use -filetype=null, you are only checking stderr

2025-01-24 16:06 UTC, arsenm commented on llvm/test/MachineVerifier/test_g_incompatible_range.mir
> +# RUN: not --crash llc -o - -mtriple=amdgcn-mesa-mesa3d -mcpu=tahiti -run-pass=none %s 2>&1 | FileCheck %s
e.g. in unsupported-subreg-index-aligned-vgpr-check.mir:
`# RUN: not --crash llc -mtriple=amdgcn-amd-amdhsa -mcpu=gfx942 -run-pass=none -filetype=null %s 2>&1 | FileCheck %s`

2025-01-24 16:13 UTC, parsifal-47 commented on llvm/test/MachineVerifier/test_g_incompatible_range.mir
> +# RUN: not --crash llc -o - -mtriple=amdgcn-mesa-mesa3d -mcpu=tahiti -run-pass=none %s 2>&1 | FileCheck %s
sorry, I touched this line when experimenting, fixed, thank you!

2025-01-28 13:54 UTC, merged

2025-01-28 15:18 UTC, parsifal-47 commented
thank you @arsenm ! 
I have noticed that buildbot found something wrong with `-mtriple=amdgcn-amd-amdhsa`, should I change it to something else?

2025-01-28 15:20 UTC, arsenm commented
> thank you @arsenm ! I have noticed that buildbot found something wrong with `-mtriple=amdgcn-amd-amdhsa`, should I change it to something else?

No, it just required the target to be build. I moved the test in ee1c6a6bc15091155f294d62d0ab67f75a90b7fb

2025-01-29 07:12 UTC, vvereschaka commented
@arsenm , @parsifal-47 ,

looks like these changes cause a failure of `LLVM :: CodeGen/AArch64/setcc_knownbits.ll' test on the expensive checks builder here
https://lab.llvm.org/buildbot/#/builders/187/builds/4023/steps/6/logs/FAIL__LLVM__setcc_knownbits_ll
```
*** Bad machine code: range is incompatible with the result type ***
- function:    logger
- basic block: %bb.2 land.rhs (0x55e1d64bd310)
- instruction: %16:_(s32) = G_LOAD %5:_(p0) :: (load (s8) from %ir.1, !range !0)
LLVM ERROR: Found 1 machine code errors.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.      Program arguments: /home/buildbot/worker/temp/build/bin/llc -mtriple=aarch64 -global-isel
1.      Running pass 'Function Pass Manager' on module '<stdin>'.
2.      Running pass 'Verify generated machine code' on function '@logger'
...
```

I found a problematic commit by bisecting though the commits for this buildbot's build. Reverting of these changes fixes the test.
Would you check it on your side accordingly?

2025-01-29 07:49 UTC, arsenm commented on llvm/lib/CodeGen/MachineVerifier.cpp
> +              ValTy.getScalarType().getSizeInBits()) {
The change to use the memory type got lost

2025-01-29 08:09 UTC, arsenm commented
Fix in #124894