Rewrites for I2 to I8 signed and unsigned extension
llvm/llvm-project pull request #121298
Opened 2024-12-29 15:50 UTC by ziereis

Adds rewrites for i2 to i8 signed and unsigned extension, similar to the ones that already exist for i4 to i8 conversion.

I use this for i6 quantized models, and this gives me roughly a 2x speedup for an i6 4096x4096 dequantization-matmul on an AMD 5950x.

I didn't add the rewrite for i8 to i2 truncation because I currently don't use it, but if this is needed, I can add it as well.

2025-01-05 17:29 UTC, banach-space reviewed
Thanks for working on this!

> I didn't add the rewrite for i8 to i2 truncation because I currently don't use it, but if this is needed, I can add it as well.

A TODO + negative test would be sufficient for me.

2025-01-05 17:29 UTC, banach-space commented on mlir/test/Dialect/Vector/vector-rewrite-narrow-types.mlir
> +func.func @aligned_extsi_i2_to_i8(%a: vector<8xi2>) -> vector<8xi8> {
[nit] I'd be tempted to move `@aligned_extsi_i2_to_i8` next to `@aligned_extsi_i4_to_i8`. Same for other tests.

2025-01-05 17:29 UTC, banach-space commented on mlir/lib/Dialect/Vector/Transforms/VectorEmulateNarrowType.cpp
> +  // interleave all 4 elements by first interleaving even elements and then odd
```suggestion
  // Interleave all 4 elements by first interleaving even elements and then odd.
```

2025-01-05 17:29 UTC, banach-space commented on mlir/lib/Dialect/Vector/Transforms/VectorEmulateNarrowType.cpp
> +  Value elem1 = rewriter.create<arith::AndIOp>(loc, shifted1, maskValues);
This block is repeated multiple times. Also, similar blocks are present in other functions. 

Could you try introducing an utility function instead? For example, `Value extractNBitsFromVal(int bitIdxStart, int bitIdxEnd, Value src)`?

2025-01-05 17:29 UTC, banach-space commented on mlir/lib/Dialect/Vector/Transforms/VectorEmulateNarrowType.cpp
> +/// LLVM to scramble with peephole optimizations.
> take advantage of high-level information

There's not much "high-level" info in arith.extsi ;-)

>  avoid leaving  LLVM to scramble with peephole optimizations

IMO, this is a perfect opportunity for the LLVM backend to shine. Once LLVM's optimizer can handle this, other frontends (i.e., not just MLIR + Vector) will benefit as well.

Just to clarify, I'm not against having these patterns here - quite the opposite! I'm very thankful that you're adding them. To me, this is more about working around LLVM's current limitations and filling the gap while LLVM catches up.

2025-01-06 12:13 UTC, ziereis commented on mlir/lib/Dialect/Vector/Transforms/VectorEmulateNarrowType.cpp
> +    // not supported currently.
Done. Also, a negative test should exist. I just check that I don't match on an i2 to i8 truncation, is that not sufficient?

2025-01-06 12:14 UTC, ziereis commented on mlir/lib/Dialect/Vector/Transforms/VectorEmulateNarrowType.cpp
> +  Value elem1 = rewriter.create<arith::AndIOp>(loc, shifted1, maskValues);
Very good idea, thank you. I created the function with ```int bitIdx, int numBits``` instead of a start and end index because this was easier for me to reason about.

2025-01-06 12:19 UTC, ziereis commented on mlir/lib/Dialect/Vector/Transforms/VectorEmulateNarrowType.cpp
> +/// LLVM to scramble with peephole optimizations.
Makes sense. Honestly, I just copied these comments from the other functions :D. I removed the part about the "high-level" information in the comments.

2025-01-06 12:22 UTC, ziereis commented
Thanks a lot for the review. I believe I have addressed all the comments. I also noticed a superfluous ```AndIOp`` for the unsigned case, so I removed it and adjusted the tests accordingly.

2025-01-07 07:04 UTC, hanhanW commented
cc @lialan who recently works on this area.

2025-01-07 07:46 UTC, hanhanW requested changes
The logic of signed and unsigned conversion is very similar. The only difference is that they use different `extractNBits*` functions. I think we can pass the function to the method, so we no longer need to duplicate the logic. E.g.,

```
using ExtractNBitsFn = std::function<Value(PatternRewriter&, Location, Value, int, int)>;

static Value rewriteI4ToI8(PatternRewriter &rewriter, Location loc,
                                    Value srcValue, ExtractNBitsFn extFn) {
// ...
  Value low = extFn(rewriter, loc, i8Vector, 0, 4);
  Value high = extFn(rewriter, loc, i8Vector, 4, 4);
// ...
}
```

2025-01-07 07:46 UTC, hanhanW commented on mlir/lib/Dialect/Vector/Transforms/VectorEmulateNarrowType.cpp
>      return rewriter.notifyMatchFailure(op, "Not a supported aligned case");
This statement is becoming more complicated, and it is not easy to parse if the comment match the check or not. How about we break it into three if-statement and collapse the comment into the error message? E.g.,

```cpp
// I feel that it is a requirement for emulation, so we can just say that it must be greater than or equal to 8
if (dstElemBitwidth < 8)
  return rewriter.notifyMatchFailure(op, "the bitwidth of dstType must be greater than or equal to 8");
if (dstElemBitwidth % srcElemBitwidth != 0)
  return ... "unaligned cases are not supported"
if (srcElemBitwidth != 2 && srcElemBitwidth != 4)
  return ... "only support src bitwidth to be 2 or 4 at this moment"
}
```

2025-01-07 07:46 UTC, hanhanW commented on mlir/lib/Dialect/Vector/Transforms/VectorEmulateNarrowType.cpp
> +}
Few suggestions:

- Add a documentation to the function.
- Add `static` keyword to the local function. Same for the below function. https://llvm.org/docs/CodingStandards.html#anonymous-namespaces
- Use auto for `srcVecType` because `cast` already spells the type. https://llvm.org/docs/CodingStandards.html#use-auto-type-deduction-to-make-code-more-readable
- [optional] I'd rename `i8VecShape` to `vecShape`.
- You do not need the llvm::to_vector. One of the SmallVector constructors takes ArrayRef type directly. So it can be `SmallVector<int64_t> vecShape(srcVecType.getShape())`.

2025-01-07 07:46 UTC, hanhanW commented on mlir/lib/Dialect/Vector/Transforms/VectorEmulateNarrowType.cpp
> +Value extractNBitsFromVectorSigned(PatternRewriter &rewriter, Location loc,
nit: add `static` keyword to the local function.
[optional]: it looks better if you can have an example in the doc.

2025-01-07 07:46 UTC, hanhanW commented on mlir/lib/Dialect/Vector/Transforms/VectorEmulateNarrowType.cpp
> +Value extractNBitsFromVectorUnsinged(PatternRewriter &rewriter, Location loc,
nit: add `static` keyword

2025-01-07 07:46 UTC, hanhanW commented on mlir/lib/Dialect/Vector/Transforms/VectorEmulateNarrowType.cpp
>      if (isSigned) {
nit: `conversionOp.getLoc()` is used several times. I think we can declare a variable, which makes code simpler. E.g., `Location loc = conversionOp.getLoc();`

2025-01-07 18:29 UTC, ziereis commented
Thanks again for the review. All comments should be addressed.

2025-01-08 17:03 UTC, banach-space reviewed
Thanks for all the updates so far!

2025-01-08 17:03 UTC, banach-space commented on mlir/lib/Dialect/Vector/Transforms/VectorEmulateNarrowType.cpp
> +  Value elem3 = extFn(rewriter, loc, i8Vector, 6, 2);
Are these vectors or scalars?

2025-01-08 17:03 UTC, banach-space commented on mlir/lib/Dialect/Vector/Transforms/VectorEmulateNarrowType.cpp
> +  // elem3 = [3,3,3,3]
If `elem0` is a scalar byte, then I read that as: 4 x i2, where every value is `0` (or `1` etc). But are these values really replicated like this?

2025-01-09 09:41 UTC, ziereis commented on mlir/lib/Dialect/Vector/Transforms/VectorEmulateNarrowType.cpp
> +/// result = shr & mask = [00000010]
it would, but you would end up with more instructions.

Example for 4 bit:

Shifts:
src : i8
shl = arith::shl(src)
low = artih::shrui(shl)
high = arith::shrui(src)

Mask:
src: i8
low = mask(src, 15)
high = artih::shrui(src)

2025-01-09 11:06 UTC, banach-space commented on mlir/lib/Dialect/Vector/Transforms/VectorEmulateNarrowType.cpp
> +/// result = shr & mask = [00000010]
In ideal world, we'd keep `extractNBitsFromVectorSigned` and `extractNBitsFromVectorUnsinged` very consistent, so I'm trying to understand the reason for divergence.

> Example for 4 bit:
> 
> Shifts: src : i8 
> shl = arith::shl(src) 
> low = artih::shrui(shl) 
> high = arith::shrui(src)

Let me make sure I got this right. I assume that we are extracting 2 bits at index 0 (indexing from MSB, i.e. left-most bit):
```bash
src: [10 10 11 00]
shl: arith.shl(src) --> [10 10 11 00]
shr: arith.shrui(shl) --> [00 00 00 10]
```
Why do we need another `shr` in your example? (i.e., what's `low` and `high`?)

2025-01-09 13:40 UTC, ziereis commented on mlir/lib/Dialect/Vector/Transforms/VectorEmulateNarrowType.cpp
> +/// result = shr & mask = [00000010]
okay, so my understanding is that when talking about bits the convention is to "read it right to left", so the LSB is at index 0. So the "low bits" are the right most bits and the "high bits" are the left most. 

src:         [ 1 | 0 | 1 | 0 | 1 | 1 | 0 | 0 ]
indices:  [ 7 | 6 | 5 | 4 | 3 | 2 | 1 | 0 ]

So i could always extract N bits starting from 0 with a single arith::AndIOp + mask. 
If i would use the shl + shrui pattern i would need to use 2 instructions. 

So this is basically a small shortcut i can take with unsigned numbers, but for the signed case i have to always do it with the shrsi for the sign.

2025-01-09 13:56 UTC, ziereis commented on mlir/lib/Dialect/Vector/Transforms/VectorEmulateNarrowType.cpp
> +        op, "only src bitwidth of 2 or 4 is supported at this moment");
Thank you

2025-01-09 14:50 UTC, ziereis commented on mlir/lib/Dialect/Vector/Transforms/VectorEmulateNarrowType.cpp
> +  // elem3 = [3,3,3,3]
elem0 is a vector, this is bad naming sorry. The values are just  "some values from vector i"

2025-01-09 14:56 UTC, ziereis commented on mlir/lib/Dialect/Vector/Transforms/VectorEmulateNarrowType.cpp
> +  Value elem3 = extFn(rewriter, loc, i8Vector, 6, 2);
vectors, i fixed the naming

2025-01-09 15:07 UTC, ziereis commented on mlir/lib/Dialect/Vector/Transforms/VectorEmulateNarrowType.cpp
> +/// starting at the specified bit index.
> * for every byte `b` in `src` (which is a vector of bytes),
> * extracts `numBits` starting at `bitIdx` (let's call it `inputVal`), and
yes
> * returns a byte matching the value encoded in `inputVal`.

it will return a vector of bytes, the resultType will always be the same as the srcType. 
so for example lets say `numBits` is 4, it will treat the `inputVal` as a `i4` and (sign)ext it to a `i8` value.

2025-01-09 15:12 UTC, ziereis commented on mlir/lib/Dialect/Vector/Transforms/VectorEmulateNarrowType.cpp
> +  assert(8 % srcBitwidth == 0 && "Invalid source bitwidth");
yes it should be verified, i guess i can also remove this?

2025-01-09 15:27 UTC, banach-space commented on mlir/lib/Dialect/Vector/Transforms/VectorEmulateNarrowType.cpp
> +/// result = shr & mask = [00000010]
> okay, so my understanding is that when talking about bits the convention is to "read it right to left", so the LSB is at index 0. So the "low bits" are the right most bits and the "high bits" are the left most. 

Yes, that makes more sense 😅  But then, when storing a _vector_ of 8 elements in memory, it's usually like: `v[0], v[1], v[2], ...`. Not to mention the split into little-endian/big-endian (but we are not storing anything in memory here, so not relevant). My point being - this is worth documenting.

> I will add this to the documentation

That was going to be my next request 😅 

> So this is basically a small shortcut i can take with unsigned numbers, but for the signed case i have to always do it with the shrsi for the sign.

TBH, this is where I'd really expect LLVM to do it's job (as in, I wouldn't consider optimising this much in MLIR). But your measurements might suggest you otherwise?

To me, it would make a lot of sense if you merged `extractNBitsFromVectorSigned` and `extractNBitsFromVectorUnsinged` - the only difference would be the right shift. Consistency is great :)

That said, I don't feel that strongly about it and I admit that it's a optimisation. If you decide to leave `arith::ShlOp + arith::AndIOp`, then could you add a comment in `extractNBitsFromVectorUnsinged` to document the reason for divergence? Something along the lines:

> NOTE: Similarly to `extractNBitsFromVectorUnsinged`, this could be used with arith::ShlOp + arith::ShrSOp`. However, by using `arith::ShlOp + arith::AndIOp`, we are eliminating shift left when the index is 0.

I know that this feels obvious today, but I always try to optimise for my future self who will forget :)

2025-01-09 15:28 UTC, banach-space reviewed
I love the updated comments 🙏🏻

2025-01-09 15:28 UTC, banach-space commented on mlir/lib/Dialect/Vector/Transforms/VectorEmulateNarrowType.cpp
> +/// starting at the specified bit index.
`extractNbitsPerByteAndExtendToI8`?

Am I correct that this method assumes that the src and dst element type is `i8`?

2025-01-09 17:05 UTC, ziereis commented on mlir/lib/Dialect/Vector/Transforms/VectorEmulateNarrowType.cpp
> +/// result = shr & mask = [00000010]
I have not measured if it would make any difference, i will look into this, for now i have just created the note. However changing this would also mean i have to change all the tests for the i4 to i8 rewrites.

2025-01-09 17:05 UTC, ziereis commented on mlir/lib/Dialect/Vector/Transforms/VectorEmulateNarrowType.cpp
> +/// starting at the specified bit index.
yes

2025-01-09 17:05 UTC, ziereis commented on mlir/lib/Dialect/Vector/Transforms/VectorEmulateNarrowType.cpp
> +  assert(8 % srcBitwidth == 0 && "Invalid source bitwidth");
alright i will leave it.

2025-01-10 15:55 UTC, banach-space reviewed
Thanks for all the updates, this is looking really neat 🙏🏻  A few final comments, nothing major.

2025-01-10 15:55 UTC, banach-space commented on mlir/lib/Dialect/Vector/Transforms/VectorEmulateNarrowType.cpp
> +/// vector<16x16xi4> -> vector<16x4xi8>
```suggestion
/// vector<16x16xi2> -> vector<16x4xi8>
/// vector<16x16xi4> -> vector<16x8xi8>
```

2025-01-10 15:55 UTC, banach-space commented on mlir/lib/Dialect/Vector/Transforms/VectorEmulateNarrowType.cpp
> +  int64_t bitwidthFactor = 8 / srcBitwidth;
To keep the naming consistent within the file, could this be `numSrcElemsPerByte`?

Similar variable elsewhere: https://github.com/llvm/llvm-project/blob/cfee344dda7394631f2177a15e56cfeee1d61fc4/mlir/lib/Dialect/Vector/Transforms/VectorEmulateNarrowType.cpp#L1098

2025-01-10 15:55 UTC, banach-space commented on mlir/lib/Dialect/Vector/Transforms/VectorEmulateNarrowType.cpp
> +/// Extracts a signed N-bit sequence from each element of an 8-bit vector,
[nit] This might be my "hardware" bias, but to me an 8-bit vector is literally a vector that holds 8-bits (for comparison, NEON has 128-bit vectors). 
```suggestion
/// Extracts a signed N-bit sequence from each element of a vector of bytes,
```

2025-01-10 15:55 UTC, banach-space commented on mlir/lib/Dialect/Vector/Transforms/VectorEmulateNarrowType.cpp
> +  // 13    = [1,3,1,3,...],...
[nit] I think that this would help readability of this
```suggestion
  // 02    = [0,2,0,2,0,2,0,2],...
  // 13    = [1,3,1,3,1,3,1,3],...
```

2025-01-10 15:55 UTC, banach-space commented on mlir/lib/Dialect/Vector/Transforms/VectorEmulateNarrowType.cpp
> +  const int numSrcElemsPerDestElem = 8 / srcElemBitwidth;
Why hard-code this to 8?

Also, comment for L1105 (sadly GitHub doesn't allow comments for things outside the diff) - please update the error msg.

2025-01-10 15:55 UTC, banach-space commented on mlir/test/Dialect/Vector/vector-rewrite-narrow-types.mlir
> +  return %0 : vector<2xi8>
These are the unaligned cases, right? Please move to https://github.com/llvm/llvm-project/blob/main/mlir/test/Dialect/Vector/vector-emulate-narrow-type-unaligned.mlir.

2025-01-10 15:55 UTC, banach-space commented on mlir/test/Dialect/Vector/vector-rewrite-narrow-types.mlir
> +// CHECK:           %[[ELEM3:.*]] = arith.shrsi %[[BITCAST]], %[[CST_6]] : vector<2xi8>
[nit] To improve readability (same comment for other tests)

```suggestion
// Extract bits 0-1
// CHECK:           %[[SHL_6:.*]] = arith.shli %[[BITCAST]], %[[CST_6]] : vector<2xi8>
// CHECK:           %[[ELEM0:.*]] = arith.shrsi %[[SHL_6]], %[[CST_6]] : vector<2xi8>
// Extract bits 2-3
// CHECK:           %[[SHL_4:.*]] = arith.shli %[[BITCAST]], %[[CST_4]] : vector<2xi8>
// CHECK:           %[[ELEM1:.*]] = arith.shrsi %[[SHL_4]], %[[CST_6]] : vector<2xi8>
// Extract bits 4-5
// CHECK:           %[[SHL_2:.*]] = arith.shli %[[BITCAST]], %[[CST_2]] : vector<2xi8>
// CHECK:           %[[ELEM2:.*]] = arith.shrsi %[[SHL_2]], %[[CST_6]] : vector<2xi8>
// Extract bits 6-7
// CHECK:           %[[ELEM3:.*]] = arith.shrsi %[[BITCAST]], %[[CST_6]] : vector<2xi8>
```

2025-01-10 20:31 UTC, ziereis commented
Thanks again for the comments

2025-01-13 06:31 UTC, hanhanW approved these changes
I like the updated documentation, thanks a lot! I just have a final optional nit.

2025-01-13 18:26 UTC, banach-space commented on mlir/test/Dialect/Vector/vector-rewrite-narrow-types.mlir
> +  return %0 : vector<2xi8>
Ping

2025-01-13 20:14 UTC, ziereis commented on mlir/lib/Dialect/Vector/Transforms/VectorEmulateNarrowType.cpp
> +  int64_t bitwidthFactor = 8 / srcBitwidth;
done, there are some other places that refer to the same name but im not sure if they refer to the same thing

2025-01-13 20:14 UTC, ziereis commented on mlir/lib/Dialect/Vector/Transforms/VectorEmulateNarrowType.cpp
> +  const int numSrcElemsPerDestElem = 8 / srcElemBitwidth;
I changed this check since the dst in this case will always be a i8 vector.

For example:

%0 = arith.extui %a : vector<4xi2> to vector<4xi32>

should be possible because its only important that i can pack the 4 i2 values into a 1xi8 vector (otherwise i would have a invalid bitcast).

But i also added a test that checks something like this fails:

%0 = arith.extui %a : vector<2xi2> to vector<2xi32>

2025-01-13 20:14 UTC, ziereis commented on mlir/test/Dialect/Vector/vector-rewrite-narrow-types.mlir
> +  return %0 : vector<2xi8>
This was meant like more of a negative test for the alignedConversionPrecondition. Also i think the file you linked refers to the void vector::populateVectorNarrowTypeEmulationPatterns and i changed the vector::populateVectorNarrowTypeRewritePatterns (in the same file) if i understood correctly?

2025-01-13 20:16 UTC, ziereis commented
@banach-space Sorry, I didn’t mean to ignore the comments. I somehow started my own review on the PR or something, so all the comments were only "pending." I didn’t know what this meant, but it appears they were only visible to me. 😅 I hope they’re visible now!

2025-01-14 11:44 UTC, banach-space approved these changes
LGTM % some minor requests.

This is quite intricate, and I really appreciate the effort you've put into implementing this and so patiently addressing all my comments.

2025-01-14 11:44 UTC, banach-space commented on mlir/lib/Dialect/Vector/Transforms/VectorEmulateNarrowType.cpp
> +            "the srcElemBitwidth / 8");
This doesn't feel right: "a multiple of the srcElemBitwidth / 8". Did you mean "a multiple of "8 / the srcElemBitwidth"?

In general, this is quite tricky to describe in words. Here's a suggestion:

```suggestion
        op, "the trailing dimension of the input vector of sub-bytes must be a multiple of "
            "8 / <sub-byte-width>");
```

2025-01-14 11:44 UTC, banach-space commented on mlir/test/Dialect/Vector/vector-rewrite-narrow-types.mlir
> +  return %0 : vector<2xi8>
Right, now I see. Then, still, `aligned` --> `unalagined` ;-) Also, to match the naming convention that follows this:
```mlir
@aligned_i4_trailing_dim_not_multiple --> @unaligned_extsi_i4_to_i8_trailing_dim_not_multiple
```

In fact, I'd do this:
```mlir
// Negative test - the trailing dim 2 is not a multiple of 4 (i.e. 8 / 2).

func.func @unaligned_extsi_i4_to_i8
```

Similar comment for the other negative test.

2025-01-14 11:44 UTC, banach-space commented on mlir/lib/Dialect/Vector/Transforms/VectorEmulateNarrowType.cpp
> +/// Extracts an unsigned N-bit sequence from each element of an 8-bit vector,
Simiarly to `extractNBitsPerByteAndSignExtendToI8`, please replace `8-bit vector` with `a vector of bytes" ;-)

2025-01-14 12:53 UTC, ziereis commented
The comments should be resolved now. Thanks as well for all the reviews and being patient with me :)

2025-01-14 16:00 UTC, banach-space commented
> Thanks as well for all the reviews and being patient with me :)

Works both ways :) Do you have commit access?

2025-01-14 20:51 UTC, ziereis commented
no, i would be happy if you could merge it.

2025-01-15 08:12 UTC, merged

2025-01-15 08:16 UTC, banach-space commented
> no, i would be happy if you could merge it.

Landed 🥳 Thanks for working on this 🙏🏻  

Note, GitHub added me as a co-author. AFAIK, that's the default behaviour when squashing commits like this:
* https://github.com/llvm/llvm-project/pull/121298/commits/8abb46d6418762be0609c87927c22e2a392153b1

(IIUC, you've incorporated my suggestion through GitHub's UI). I don't really mind, but obviously you've done 99% of the work here 😅