Fix typeinfo for undefined sanitizer
llvm/llvm-project pull request #121228
Opened 2024-12-27 20:40 UTC by MBkkt

This happened to me when I compiled my code on x86_64 linux (ubuntu 24.04) with clang-18 and everything except glibc built from source (llvm 19, llvm source)

I found this solution and luckily it works!
https://github.com/emscripten-core/emscripten/pull/13367 https://github.com/emscripten-core/emscripten/issues/13330

I saw that issue is abandoned, so I decided to try to push it in upstream

2025-01-09 16:49 UTC, ldionne requested changes
This patch does not make sense to me. It seems we're putting a band-aid on something a lot more serious. I'd much rather fix the underlying issue instead.

2025-01-09 16:55 UTC, MBkkt commented
> I'd much rather fix the underlying issue instead.

Ofc, but it's unrealistic, no one cares

2025-01-09 17:00 UTC, philnik777 commented
> > I'd much rather fix the underlying issue instead.
> 
> Ofc, but it's unrealistic, no one cares

You seem to care.

2025-01-09 21:30 UTC, ldionne commented
@MBkkt The point I was trying to make (which I didn't say explicitly but should have) is that this issue seems to be emscripten specific. It's not reproducing with ubsan in normal setups AFAICT. If someone from emscripten investigates the underlying issue and provides a reproducer that is not emscripten specific (if that's possible), we'd be happy to take over and fix the problem properly, whatever that means. But I'm not comfortable with taking a patch that changes our code:
- Without understanding what we're actually fixing
- Without having any test to prevent a regression
- Without having a test that confirms we're actually fixing the issue

Sorry, I know you just want this simple fix to be applied, but we must have some kind of bar for accepting contributions.

Closing for now, but we'd be happy to fix the underlying issue if someone can provide a reproducer that is not emscripten specific.

2025-01-09 21:30 UTC, closed without merging

2025-01-09 22:04 UTC, MBkkt commented
> The point I was trying to make (which I didn't say explicitly but should have) is that this issue seems to be emscripten specific.

It's not, I wrote in description, anyone can just build libc++ from source with -O1 and undefined sanitizer
But anyway you see what you want to see, so don't want to continue this discussion.

2025-01-09 23:13 UTC, MBkkt commented
I think the real issue is that when this function doesn't inline it is somehow ignore `-fno-sanitze=vptr`

https://android.googlesource.com/platform//external/v8/+/27d3291ef11ea9043d7b09525245fd30cd31b20d/tools/ubsan/vptr_blacklist.txt#9
and same for chromium.

Because according to my `compile_commands.json` I built without vptr this file (because using llvm-project cmake)
But it still failed with same issue (without provided patch)
I agree that my build is unusual, but I'm pretty sure this issue doesn't depend on anything except inline this function or not.
Maybe it's possible to easy reproduce this issue with making this function `no-inline` for ubsan build of libc++

```
{
  "directory": "/xxx/build",
  "command": "/usr/bin/clang++-18 -DHAVE___CXA_THREAD_ATEXIT_IMPL -DLIBCXX_BUILDING_LIBCXXABI -DNDEBUG -D_LIBCPP_BUILDING_LIBRARY -D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS=\"\" -D_LIBCPP_HAS_NO_PRAGMA_SYSTEM_HEADER -D_LIBCXXABI_BUILDING_LIBRARY -D_LIBCXXABI_DISABLE_VISIBILITY_ANNOTATIONS -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I/xxx/llvm/libunwind/include -I/xxx/llvm/libcxxabi/../libcxx/src -I/xxx/llvm/libcxxabi/include -isystem /xxx/build/llvm/runtimes/include/c++/v1 -fsized-deallocation -fvisibility-inlines-hidden -fno-omit-frame-pointer -O1 -fsanitize=undefined -fno-sanitize=vptr,function -fno-sanitize-recover=all -fdiagnostics-color  -O0 -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -fno-limit-debug-info -g3 -fstandalone-debug -fdebug-macro -glldb -std=c++23 -nostdinc++ -fstrict-aliasing -funwind-tables -DNDEBUG -fvisibility=hidden -fvisibility-global-new-delete=force-hidden -o llvm/runtimes/libcxxabi/src/CMakeFiles/cxxabi_static_objects.dir/private_typeinfo.cpp.o -c /xxx/llvm/libcxxabi/src/private_typeinfo.cpp",
  "file": "/xxx/llvm/libcxxabi/src/private_typeinfo.cpp",
  "output": "llvm/runtimes/libcxxabi/src/CMakeFiles/cxxabi_static_objects.dir/private_typeinfo.cpp.o"
},
```

2025-01-10 16:33 UTC, ldionne commented
> It's not, I wrote in description, anyone can just build libc++ from source with -O1 and undefined sanitizer
> But anyway you see what you want to see, so I don't want to continue this discussion.

Ah, no, I simply missed that. I do a lot of reviews every day and the only way that works is for me to read PR descriptions with varied levels of care depending on the PR. In this case, I read too fast and jumped to the links, and I didn't see that you were able to reproduce this issue on non-emscripten. That changes a lot. Let's follow-up in https://github.com/llvm/llvm-project/pull/122389

2025-01-10 17:21 UTC, MBkkt commented
@ldionne thanks and sorry, I was too emotional about this.

I hope noinline will be enough to reproduce, if not, I will experiment a little and will try to investigate on what it depends