[lldb-dap] Implement `runInTerminal` for Windows
llvm/llvm-project pull request #121269
Opened 2024-12-28 15:20 UTC by SuibianP

Currently, the named pipe is passed by name and a transient `ofstream` is constructed at each I/O request. This assumes,
  - Blocking semantics: FIFO I/O waits for the other side to connect.
  - Buffered semantics: Closing one side does not discard existing data.

The former can be replaced by `WaitNamedPipe`/`ConnectNamedPipe` on Win32, but the second cannot be easily worked around. It is also impossible to have another "keep-alive" pipe server instance, as server-client pairs are fixed on connection on Win32 and the client may get connected to it instead of the real one.

Refactor `FifoFile[IO]` to use an open file handles rather than file name.

2024-12-28 15:39 UTC, SuibianP commented
The patch currently suffers from a critical issue that I cannot diagnose. Help is much appreciated.

When the debug adapter attempts to attach to the launcher,

https://github.com/llvm/llvm-project/blob/4c8c18c8c54308b945d6c78e2c71ebabf29cb554/lldb/tools/lldb-dap/lldb-dap.cpp#L2039

it blocks at

https://github.com/llvm/llvm-project/blob/4c8c18c8c54308b945d6c78e2c71ebabf29cb554/lldb/source/Plugins/Process/Windows/Common/ProcessDebugger.cpp#L580-L581

although adding the following snippet at the front of `RunInTerminalLauncherCommChannel::WaitUntilDebugAdaptorAttaches` indicates that the launcher process does get paused and never resumed.

```cpp
for (int i = 0; !::IsDebuggerPresent(); ++i)
  LLVM_LOGV(log, "Waiting to be attached... {0}", i);
LLVM_LOGV(log, "Attached");
```

2025-01-07 13:48 UTC, SuibianP commented
Ping

2025-01-16 14:57 UTC, SuibianP commented
Hi @JDevlieghere, sorry for pinging again but could you please kindly help take a look at this when you have time? Thanks in advance!

2025-01-16 19:36 UTC, JDevlieghere commented
Sorry, I didn't get the ping (I think because this is marked as a draft). I'm not familiar enough with Windows to review this, so I'm adding some folks that are or work on related stuff in `lldb-dap`.

2025-01-17 18:58 UTC, ashgti commented
Is the process stopped? I think lldb is waiting for the process to be in a stopped state. In posix terms a `SIGSTOP`, although I'm not as familiar with the win32 equiv (DebugActiveProcess maybe).

2025-01-18 17:06 UTC, SuibianP commented
As it turns out that Win32 `execvp` actually [creates a new process instead of replace the current process image](https://github.com/python/cpython/issues/101191#issuecomment-1399013437), I changed the implementation to use `CreateProcess` before reporting the PID of the target.

The current implementation works with dape under emacs and should be functional, so I marked it ready for review. On VSCode however, while the extension is able to attach to the process and obtain sort of a stack backtrace, all breakpoints show up as unverified and does not trigger even if re-toggled. I am looking into it now.

---

This is not relevant anymore but for the sake of completion: In the old implementation (wait for attach then `execvp`), the launcher process does get resumed after some 3 minutes. I still do not understand how it happened.

2025-01-21 12:19 UTC, omjavaid requested changes
This should be able make lldb\test\API\tools\lldb-dap\runInTerminal\TestDAP_runInTerminal.py pass all tests. Please tests and remove the skipping decorators.

2025-01-21 12:19 UTC, omjavaid commented on lldb/tools/lldb-dap/FifoFiles.h
> +           std::chrono::milliseconds timeout = std::chrono::milliseconds(2000));
Is it ok to change to timeout here 20000 --> 2000?

2025-01-21 12:19 UTC, omjavaid commented on lldb/tools/lldb-dap/FifoFiles.h
> +  // private:
Why commenting out private?

2025-01-22 21:14 UTC, walter-erquinigo reviewed
To be honest it's a bit hard to review this because I'm not versed in these low level APIs, let along Windows. Could you make sure that your changes pass mac, linux and windows CI? IIRC you can trigger manually buildbots if you want to run custom tests.

2025-01-22 21:14 UTC, walter-erquinigo commented on lldb/tools/lldb-dap/FifoFiles.h
> +           std::chrono::milliseconds timeout = std::chrono::milliseconds(2000));
Don't change this. Some targets take a while to launch

2025-01-22 21:14 UTC, walter-erquinigo commented on lldb/tools/lldb-dap/FifoFiles.h
> +std::error_code createNamedPipe(const llvm::Twine &Prefix,
This API is unnecessarily complex. The Prefix can just be a StringRef. Also use lower case for names. You also never use the Suffix.
Finally, please write some documentation mentioning that a unique named pipe with the given prefix will be created.
You may consider renaming this function as `createUniqueNamedPipe`

2025-01-22 21:14 UTC, walter-erquinigo commented on lldb/tools/lldb-dap/RunInTerminal.cpp
> +    pid = getpid();
can you explain here why you added this?

2025-01-22 21:14 UTC, walter-erquinigo commented on lldb/tools/lldb-dap/RunInTerminal.cpp
> +                             "Error converting file descriptor to C FILE");
Please mention runInTerminal here, as otherwise the error is not actionable at all

2025-01-24 12:25 UTC, SuibianP commented on lldb/tools/lldb-dap/FifoFiles.h
> +  // private:
Debug leftover; rectified.

2025-01-24 12:32 UTC, SuibianP commented on lldb/tools/lldb-dap/RunInTerminal.cpp
> +    pid = getpid();
I used this as kind of a dynamic default argument. The original codepath always used `getpid()` as the PID to be sent through the pipe, but this does not work for Windows where the PID of the target differs from that of the launcher.

https://github.com/llvm/llvm-project/pull/121269/files#diff-2de0ddf6c080497da43990b05d21e6229d309f51cf269ba7e3860a677f507905R4903-R4905

Maybe an explicit argument without such implicit default would be more readable?

2025-01-24 12:54 UTC, SuibianP commented on lldb/tools/lldb-dap/FifoFiles.h
> +std::error_code createNamedPipe(const llvm::Twine &Prefix,
I was mimicking the `llvm::sys::fs::createTemporaryFile` API with the idea that this abstraction might be melded in there at some later time.

Is this considered too broad?

2025-01-24 12:56 UTC, SuibianP commented on lldb/tools/lldb-dap/FifoFiles.h
> +           std::chrono::milliseconds timeout = std::chrono::milliseconds(2000));
Debug leftover; rectified.

2025-01-25 02:36 UTC, SuibianP commented
I [enabled `runInTerminal` tests for Windows](https://github.com/llvm/llvm-project/pull/121269/files#diff-38cf10e0a83515e5c6acf5449a3f5de1d63f116d932a32ba169b746826ead1d4) (will fix line 93 later) except for the 4 launcher tests that requires `os.mkfifo` (https://github.com/python/cpython/issues/103510) and they pass on my local computer. This should be sufficient to guarantee the common functionalities. I can do a simple polyfill using `pywin32` for Windows if the ignored test is a blocker for this PR.

All LLDB tests still pass on Linux CI, so there seems to be no regression https://buildkite.com/llvm-project/github-pull-requests/builds/140240

2025-02-04 15:14 UTC, SuibianP commented on lldb/tools/lldb-dap/RunInTerminal.cpp
> +    pid = getpid();
Refactored with explicitly specified arguments.

2025-02-04 18:13 UTC, ashgti commented on lldb/tools/lldb-dap/lldb-dap.cpp
> +  llvm::errs() << "WaitForLauncher\n";
I think we can remove this

2025-02-04 18:13 UTC, ashgti commented on lldb/tools/lldb-dap/lldb-dap.cpp
> +  llvm::errs() << "WaitForLauncher returned\n";
I think we can remove this as well

2025-02-05 02:10 UTC, SuibianP commented on lldb/tools/lldb-dap/FifoFiles.cpp
> +        rewind(m_fifo_file.m_file);
It seemed to help on Windows, but I did not investigate further, as it is technically also required by ISO C standard (C23 draft N3220 §7.23.5.3.7)

> When a file is opened with update mode (’+’ as the second or third character in the previously
described list of mode argument values), both input and output may be performed on the associated
stream. However, output shall not be directly followed by input without an intervening call to the
`fflush` function or to a file positioning function (`fseek`, `fsetpos`, or `rewind`), and input shall not
be directly followed by output without an intervening call to a file positioning function, unless the
input operation encounters end-of-file. Opening (or creating) a text file with update mode may
instead open (or create) a binary stream in some implementations.

2025-02-05 02:17 UTC, SuibianP commented on lldb/tools/lldb-dap/FifoFiles.cpp
> +      "/tmp/"
On Windows FIFOs live on a virtual hierarchy `\\.\pipe\` not backed a real filesystem. I don't think it is possible to `mkdir` on them, although it is possible to specify something like `\\.\pipe\tmp\dir\myfifo` to `CreateNamedPipe`.

2025-02-05 14:07 UTC, SuibianP commented on lldb/tools/lldb-dap/FifoFiles.cpp
Removed one empty line and preserved those around `ifdef` guarded includes, the same way `lldb-dap.cpp` does it.

2025-02-05 14:07 UTC, SuibianP commented on lldb/tools/lldb-dap/FifoFiles.cpp
> +    return std::error_code(::GetLastError(), std::system_category());
Didn't know this utility function existed. Switched to it.

2025-02-05 14:08 UTC, SuibianP commented on lldb/tools/lldb-dap/FifoFiles.cpp
> +    return std::error_code(::GetLastError(), std::system_category());
Switched.

2025-02-05 14:13 UTC, SuibianP commented on lldb/tools/lldb-dap/FifoFiles.cpp
> +  other.m_file = nullptr;
Called `clear` on it.

Also fixed one place where the moved `m_path` was still used.

2025-02-05 14:14 UTC, SuibianP commented on lldb/tools/lldb-dap/FifoFiles.h
> +  // FifoFile(llvm::StringRef path, FILE *f);
Removed.

2025-02-05 14:15 UTC, SuibianP commented on lldb/tools/lldb-dap/FifoFiles.cpp
> +std::error_code EC;
Unintended, moved into function.

2025-02-05 14:17 UTC, SuibianP commented on lldb/tools/lldb-dap/FifoFiles.h
> +std::error_code createNamedPipe(const llvm::Twine &Prefix,
Added doxygen comments, changed to snake_case and renamed function to `createUniqueNamedPipe`.

2025-02-10 17:53 UTC, ashgti commented on lldb/tools/lldb-dap/FifoFiles.cpp
> +      "/tmp/"
`/tmp` is not always the appropriate platform path for non-windows platforms. Thats my main concern.

2025-02-10 17:53 UTC, ashgti commented on lldb/tools/lldb-dap/FifoFiles.cpp
> +        rewind(m_fifo_file.m_file);
I think the flow of the logic here is:

* `lldb-dap` (pid 1) opens the fifo
* pid 1 sends sends the `runInTerminal` command.
* pid 1 reads from the fifo (waiting for data)
* `lldb-dap --launch-target` (pid 2) starts
* pid 2 opens the fifo
* pid 2 spawns the new process
* pid 2 writes to the fifo (something like `{"pid":2}\n`) 
* pid 1 finishes the initial read from the fifo
* pid 1 lldb attaches to the process started by pid 2

This should mean that the parent side only reads from the file and the child side only writes to the file. Additionally, I think they're only each performing 1 write/read on each side so their respective file positions should still be at the beginning of the file after opening.

2025-02-10 17:53 UTC, ashgti commented on lldb/tools/lldb-dap/FifoFiles.h
> +std::error_code createUniqueNamedPipe(const llvm::Twine &prefix,
Should this return an `llvm::Error` instead of a `std::error_code`? `llvm::Error` has stronger requirements for handling errors.

2025-02-10 17:53 UTC, ashgti commented on lldb/tools/lldb-dap/RunInTerminal.cpp
> +  // llvm::buffer_istream
If you have the path, can't you use that to open the file with `std::ofstream`?

2025-02-21 13:44 UTC, SuibianP commented on lldb/tools/lldb-dap/RunInTerminal.cpp
> +  // llvm::buffer_istream
On the client (launcher) side it should be possible, but on the server end I suppose not. Windows has the distinction of "server" (from `CreateNamedPipe`) and "client" (from `CreateFile`) ends of FIFOs and unlike on POSIX where FIFOs can read from any previous write, clients can only communicate with server but not fellow clients.

Opening a `std::ofstream` (which underlyingly is `CreateFile`) would open a client of the pipe in the same process that connects to the server. The server side must use `CreateNamedPipe` which gives out a `HANDLE`, thus the issue of turning that into some platform independent file object.

2025-02-21 14:03 UTC, SuibianP commented on lldb/tools/lldb-dap/FifoFiles.cpp
> +      "/tmp/"
Hmm.. maybe `llvm::sys::path::system_temp_directory` then?

2025-02-21 14:08 UTC, SuibianP commented on lldb/tools/lldb-dap/FifoFiles.cpp
> +        rewind(m_fifo_file.m_file);
The DA side first sends a `RunInTerminalMessageDidAttach` message in `RunInTerminalDebugAdapterCommChannel::NotifyDidAttach` when it attaches to the launcher. This is also why the FIFO must be `PIPE_ACCESS_DUPLEX`.

2025-02-21 14:28 UTC, SuibianP commented on lldb/tools/lldb-dap/FifoFiles.cpp
> +  result_path.pop_back();
Yes, it is the NUL. It would be encoded into JSON if not popped.

I think it might have always been buggy and just happened to work, as NUL termination from `StringRef::data` is explicitly not guaranteed.

2025-02-21 14:46 UTC, SuibianP commented on lldb/tools/lldb-dap/FifoFiles.cpp
> +        line = buffer;
We can reinvent POSIX `getline`, but it is probably not worth the effort. Any JSON schema change that overruns the buffer will absolutely get truncated, break the test visibly and get caught during review.

2025-02-21 14:50 UTC, SuibianP commented on lldb/tools/lldb-dap/FifoFiles.cpp
> +        constexpr size_t buffer_size = 2048;
The two sizes are not related. The one passed to `CreateNamedPipe` is the kernel buffer, while this one is for the receiving user buffer. I do need to rethink how long the buffer needs to be, though.

2025-02-26 12:10 UTC, SuibianP commented on lldb/tools/lldb-dap/FifoFiles.cpp
> +      "/tmp/"
Changed back to `getPotentiallyUniqueTempFileName` for non-Windows platforms.

2025-02-26 12:11 UTC, SuibianP commented on lldb/tools/lldb-dap/FifoFiles.cpp
> +std::error_code createNamedPipe(const Twine &Prefix, StringRef Suffix,
Changed to return `llvm::Error`.

2025-02-26 12:12 UTC, SuibianP commented on lldb/tools/lldb-dap/FifoFiles.cpp
> +    std::terminate();
Change to static factory method `FifoFile::create` that returns an `Expected<FifoFile>`.

2025-02-26 12:14 UTC, SuibianP commented on lldb/tools/lldb-dap/FifoFiles.cpp
> +        constexpr size_t buffer_size = 2048;
Fixed at 512 which should be longer than any single message that passes through the FIFO. Mentioned in code comment as well.

2025-02-26 18:40 UTC, ashgti commented on lldb/tools/lldb-dap/FifoFiles.cpp
> +        rewind(m_fifo_file.m_file);
I think seeking isn't support on a fifo (`lseek` would return `ESPIPE`, see `man 2 lseek` or the Errors section of https://man7.org/linux/man-pages/man2/lseek.2.html). So I'm not sure if you need to do these `rewind` on non-windows platforms.

2025-02-27 10:07 UTC, SuibianP commented on lldb/test/API/tools/lldb-dap/runInTerminal/main.c
> +#include <threads.h>
[`threads.h`](https://en.cppreference.com/w/c/header/threads) is in ISO C11 standard §7.26. The tests are all [passing in Linux x64 CI](https://buildkite.com/llvm-project/github-pull-requests/builds/151090#0195426e-ca2c-4da7-b72b-6ac347c97b90/429-1562).

2025-02-27 11:31 UTC, SuibianP commented on lldb/tools/lldb-dap/FifoFiles.cpp
> +        rewind(m_fifo_file.m_file);
Practically it should not be needed, but I am tempted to leave the `rewind` there. It helps with standard compliance and does not harm anyways. There might as well be other non-Windows platforms requiring this invocation to properly function.

2025-02-28 10:20 UTC, SuibianP commented on lldb/tools/lldb-dap/FifoFiles.cpp
> +    llvm::errs() << "Error setting unbuffered mode on C FILE\n";
Changed.

2025-02-28 10:21 UTC, SuibianP commented on lldb/tools/lldb-dap/FifoFiles.h
> +std::error_code createUniqueNamedPipe(const llvm::Twine &prefix,
Changed.

2025-03-01 09:29 UTC, SuibianP commented on lldb/test/API/tools/lldb-dap/runInTerminal/main.c
> +#include <threads.h>
Turns out Apple does not yet support C11 `threads.h`.

https://github.com/llvm/llvm-project/blob/7e8a06cfa4a2951b8ee77e19e34926e6e535b4d1/clang/lib/Basic/Targets/OSTargets.cpp#L61-L62

Changed test case to use C++11 `thread` which is supported.

2025-03-03 12:12 UTC, SuibianP commented on lldb/tools/lldb-dap/FifoFiles.cpp
> +        rewind(m_fifo_file.m_file);
For future reference: refer to the comment chain below.

2025-04-03 16:25 UTC, SuibianP commented
Pinging @ashgti and @walter-erquinigo for review before I forget again

2025-05-06 09:46 UTC, SuibianP commented
Pinging again for review @ashgti @omjavaid @walter-erquinigo 

Also want to highlight https://github.com/SuibianP/llvm-project/commit/f9675fbe23abe59c3cf56a6263b7a78ec20e42d4#diff-ed319b24adfa654beeff8b32f9d8f975c62299fbe5cb6fbe1028aa6bbaa369e7. Not sure how it is passing CI though; I might as well be understanding it wrongly.

2025-05-08 07:59 UTC, SuibianP commented on lldb/tools/lldb-dap/FifoFiles.cpp
> +      path, PIPE_ACCESS_DUPLEX | FILE_FLAG_FIRST_PIPE_INSTANCE,
> when its opened for reading it blocks until the file is also opened for writing and vice versa

This is implemented with [`ConnectNamedPipe`](https://learn.microsoft.com/en-us/windows/win32/api/namedpipeapi/nf-namedpipeapi-connectnamedpipe) in `FifoFileIO::WaitForPeer` after creation. `WaitNamedPipe` was not needed as the server side would already be around by the time the client tries to connect.

> deadlock the process by having it wait on itself accidentally

Intra-process deadlock (waiting on its own pending output) should not be possible, since on Windows a process cannot even read back what it wrote into a named pipe from the same handle. The data flow is bidirectional, but can only be consumed by the other end.

Inter-process deadlock, with the exception of buffering, is also rather unlikely. Current protocol over the pipe is strictly synchronous and sequential, or "half-duplex" in some sense -- there are no overlapping transmissions; in other words, the process will not transmit before expected response is fully received, and will not block on read before it sends out the message.

Buffering can still cause deadlocks. Without the `rewind`, the process proceeds to wait for the response after write, but the payload has somehow not fully arrived at the other end, and the peer as a result does not respond yet. I speculated it to be due to libc buffering, but did not manage to penetrate through MS CRT code to verify.

> Should we instead switch to a communication channel that supports reading and writing for all platforms?

Using sockets feels a bit like overkill, but would definitely make code more uniform across platforms I suppose. I can give it a try if you deem it more maintainable.

> we have some existing helpers for supporting sockets already.

As an aside, I remember I did also attempt to retrofit the use case into `lldb_private::Pipe`, but gave up because duplex was too hard to shoehorn into the existing abstraction, and would have very limited utility even if implemented.

> Is that something you might have a chance to look into?

I am not too familiar with that so unable to give guarantees, but let me give it a try.
Also unsure if the socket rewrite is going to make it for LLVM 21 feature freeze in July.

2026-06-22 08:52 UTC, SuibianP commented
#185894 and #174635 merged an almost identical design (other than `HANDLE` vs `FILE*` and `PIPE_TYPE_MESSAGE` vs `PIPE_TYPE_BYTE` + `NUL`). Closing regrettably.

2026-06-22 08:52 UTC, closed without merging