[GlobalISel][AArch64] Combine unmerge(G_EXT v, undef) to unmerge(v).
llvm/llvm-project pull request #65263
Opened 2023-09-04 14:09 UTC by dzhidzhoev

When having `<N x t> d1, unused = unmerge(G_EXT <2*N x t> v1, undef, N)`, it is possible to express it just as `unused, d1 = unmerge v1`.

It is useful for tackling regressions in arm64-vcvt_f.ll, introduced in https://reviews.llvm.org/D144670.

2023-09-04 17:40 UTC, arsenm commented
Should be a generic combine. Can you generalize to N unused defs?

2023-09-05 09:23 UTC, dzhidzhoev commented
> Should be a generic combine. Can you generalize to N unused defs?

G_EXT is an opcode for AArch64's `ext` instruction. Could you please suggest how to generalize it for other targets?

2023-09-05 11:00 UTC, aemerson requested changes
I think this needs some MIR tests.

2023-09-05 12:27 UTC, aemerson approved these changes
LGTM with minor changes. We can actually rename the G_EXT and friends to specify AArch64 as well in another change.

2023-09-05 12:27 UTC, aemerson commented on llvm/lib/Target/AArch64/GISel/AArch64PostLegalizerLowering.cpp
> +  if (!MRI.use_nodbg_empty(Unmerge.getOperand(1).getReg()))
`GenericMachineInstr` also gives you `getReg(N)`

2023-09-05 12:27 UTC, aemerson commented on llvm/lib/Target/AArch64/GISel/AArch64PostLegalizerLowering.cpp
>    assert(MI.getOpcode() == TargetOpcode::G_UNMERGE_VALUES);
This assert becomes unnecessary once you have the `cast<GUnmerge>` below.

2023-09-05 14:07 UTC, merged