[MLIR][Presburger] Template Matrix to allow MPInt and Fraaction
llvm/llvm-project pull request #65272
Opened 2023-09-04 15:44 UTC by Abhinav271828

Matrix has been templated to Matrix<T> (for MPInt and Fraction) with explicit instantiation for both these types.
makeMatrix has been duplicated to makeIntMatrix and makeFracMatrix.
In Fraction, we implement basic arithmetic operations to allow for Matrix operations.

2023-09-05 06:28 UTC, Superty requested changes

2023-09-05 06:28 UTC, Superty commented on mlir/include/mlir/Analysis/Presburger/Matrix.h
> +  // This class is not intended for general use: it supports only integers and rational numbers
Please write full sentences in comments, with full stops

2023-09-05 06:28 UTC, Superty commented on mlir/lib/Analysis/Presburger/Matrix.cpp
> +template class Matrix<Fraction>;
Please split the Fraction instance and related changes to another patch

2023-09-18 15:12 UTC, Superty commented on mlir/include/mlir/Analysis/Presburger/Matrix.h
> +  // This class is not intended for general use: it supports only integers and rational numbers.
Can you move this comment two lines up above the template<typename

2023-09-18 17:22 UTC, merged

2023-09-18 17:54 UTC, NathanielMcVicar commented
It looks like this has broken the Windows MLIR bot: https://lab.llvm.org/buildbot/#/builders/13/builds/40242/steps/6/logs/stdio
```
FAILED: tools/mlir/lib/Analysis/Presburger/CMakeFiles/obj.MLIRPresburger.dir/Matrix.cpp.obj 
C:\buildbot\mlir-x64-windows-ninja\llvm-project\mlir\lib\Analysis\Presburger\Matrix.cpp(385): error C2220: the following warning is treated as an error
C:\buildbot\mlir-x64-windows-ninja\llvm-project\mlir\lib\Analysis\Presburger\Matrix.cpp(385): warning C4661: 'T mlir::presburger::Matrix<T>::normalizeRow(unsigned int)': no suitable definition provided for explicit template instantiation request
        with
        [
            T=mlir::presburger::Fraction
        ]
C:\buildbot\mlir-x64-windows-ninja\llvm-project\mlir\include\mlir/Analysis/Presburger/Matrix.h(165): note: see declaration of 'mlir::presburger::Matrix<mlir::presburger::Fraction>::normalizeRow'
```