[PowerPC] Prefer xxsel for vector selection
llvm/llvm-project pull request #65295
Opened 2023-09-05 06:06 UTC by ecnelises

2023-09-09 15:12 UTC, bzEq commented
Can you explain the rationale of the preference of VSX compare? We only see one case improved in the test.

2023-09-12 09:23 UTC, ecnelises commented
This is splitted from https://reviews.llvm.org/D75895. Since VSX instructions can use twice registers than VMX, it does no harm to codegen.

2023-09-15 04:55 UTC, nemanjai commented on llvm/lib/Target/PowerPC/PPCInstrVSX.td
> +          (XXSEL $fval, $tval, (XVCMPGEDP $lhs, $rhs))>;
Can you explain why it is OK to use double precision floating point compares to compare integers?

2023-09-15 04:56 UTC, nemanjai requested changes
Also, please add a description that will reflect what the eventual commit message would be.

2024-04-10 05:02 UTC, ecnelises commented
Gentle ping

2024-10-21 16:46 UTC, ecnelises commented
Gentle ping

2024-10-24 14:21 UTC, nemanjai approved these changes

2024-10-24 14:22 UTC, nemanjai commented
Please note that I have just approved to unblock the review. I have not reviewed it yet, simply approved it to remove my blocking change request so others can review it and I will try to find time to review it myself next week.

2025-04-02 14:47 UTC, arsenm commented
Is this still relevant?

2025-06-15 12:17 UTC, nemanjai commented
@lei137 Can you please close this if it isn't relevant or rebase to make it current and ask for another review if it is relevant?

2025-06-26 17:30 UTC, lei137 commented
Closing this PR as we are not certain if this is still relevant for us at this time.

2025-06-26 17:30 UTC, closed without merging