[BasicBlockSections] Introduce the basic block sections profile version 1.
llvm/llvm-project pull request #65506
Opened 2023-09-06 17:31 UTC by rlavaee

This patch introduces a new version for the basic block sections profile as was requested in D158442, while keeping backward compatibility for the old version.

The new encoding is as follows:
```
m <module_name>
f <function_name_1> <function_name_2>...
c <bb_id_1> <bb_id_2> <bb_id_3>
c <bb_id_4> <bb_id_5>
...
```
Module name specifier (starting with 'm') is optional and allows distinguishing profiles for internal-linkage functions with the same name. If not specified, profile will be applied to any function with the same name.
Function name specifier (starting with 'f') can specify multiple function name aliases.
Finally, basic block clusters are specified by 'c' and specify the cluster of basic blocks, and the internal order in which they must be placed in the same section.

2023-09-06 19:08 UTC, shenhanc78 reviewed
`f <function name 1> <function name 2>`
So func name 1 and func name 2 are aliaes, right?

2023-09-08 18:50 UTC, HazardyKnusperkeks commented
There went something wrong, hm?

2023-09-08 19:10 UTC, asl requested changes, later dismissed
Consider rebasing your commit before submission.

2023-09-08 19:26 UTC, rlavaee commented
> `f <function name 1> <function name 2>` So func name 1 and func name 2 are aliaes, right?

Correct. Fixed the function comment.

2023-09-14 18:14 UTC, rlavaee commented
ping. @tmsri

2023-09-19 16:21 UTC, rlavaee commented
Another friendly ping for review.

2023-09-22 18:43 UTC, tmsri commented on llvm/lib/CodeGen/BasicBlockSectionsProfileReader.cpp
> +Error BasicBlockSectionsProfileReader::ReadV1Profile() {
We have to put an expiry date on "ReadV0Profile".  create_llvm_prof has to be updated to start producing the new format and we should obsolete and delete the old function soon-ish.

2023-09-22 18:56 UTC, tmsri approved these changes

2023-09-22 19:37 UTC, merged