[clangd] Forward --target to system include extraction
llvm/llvm-project pull request #65824
Opened 2023-09-09 00:10 UTC by mincrmatt12

Some clang multilib configurations (such as the one currently used in the [beta ARM LLVM toolchain](https://github.com/ARM-software/LLVM-embedded-toolchain-for-Arm)) wind up only reporting the C++ include paths properly if they get passed the correct target. This patch ensures the `--target` (or `-target`) arguments are correctly sent to the queried driver.

2023-09-10 08:00 UTC, HighCommander4 requested changes
Thanks for the patch!

There is some prior work on this which I've looked over and will summarize:

 * This change was previously proposed in [D138546](https://reviews.llvm.org/D138546)
 * During its review, we discovered that clangd would run a processing step on the compile command that sometimes _adds_ a `-target` flag, inferred from the compiler name, to the command, _before_ running `SystemIncludeExtractor`, and propagating `-target` to the extraction command then caused an error if the compiler was a gcc (since gcc does not support `-target`).
   * The patch was updated to fix this (by moving that processing step to happen _after_ `SystemIncludeExtractor`). That change was since independently made and merged in [D143436](https://reviews.llvm.org/D143436).
 * We also discovered that `SystemIncludeExtractor` was failing to include arguments like `--sysroot` in the key under which it caches its results.
   * That has since been fixed in [D146941](https://reviews.llvm.org/D146941).

Activity on [D138546](https://reviews.llvm.org/D138546) has since stalled, but the next step would have been to rebase it on top of [D143436](https://reviews.llvm.org/D143436) and [D146941](https://reviews.llvm.org/D146941)... which is basically what this patch does!

So, I think this patch should be good to go (modulo a small bug I commented on inline).

cc @cpsauer (author of [D138546](https://reviews.llvm.org/D138546)) as an FYI

2023-09-10 08:25 UTC, mincrmatt12 commented on clang-tools-extra/clangd/SystemIncludeExtractor.cpp
> +                    RHS.Lang, RHS.Sysroot, ISysroot, Target);
Fixed in latest revision (both for `Target` and the existing bug)

2023-09-10 16:00 UTC, cpsauer commented
Thanks so much for carrying this forward, Nathan.

2023-09-11 08:09 UTC, HighCommander4 approved these changes

2023-09-11 08:11 UTC, merged

2023-09-11 20:58 UTC, cpsauer commented
🎉