[analyzer] Do not use APInt methods on _BitInt() Types
llvm/llvm-project pull request #65887
Opened 2023-09-10 11:08 UTC by vabridgers

evalIntegralCast is using APInt method to get the value of _BitInt() values after _BitInt() changes were introduced. Some of those methods assume values are less than or equal to 64-bits, which is not true for _BitInt() types. This change simply side steps that issue if the _BitInt() type is greater than 64 bits.

This was caught with our internal randomized testing.

<src-root>/llvm/include/llvm/ADT/APInt.h:1510:
  int64_t llvm::APInt::getSExtValue() const: Assertion
  `getSignificantBits() <= 64 && "Too many bits for int64_t"' failed.a

...
 #9 <address> llvm::APInt::getSExtValue() const
  <src-root>/llvm/include/llvm/ADT/APInt.h:1510:5
  llvm::IntrusiveRefCntPtr<clang::ento::ProgramState const>,
  clang::ento::SVal, clang::QualType, clang::QualType)
  <src-root>/clang/lib/StaticAnalyzer/Core/SValBuilder.cpp:607:24
  clang::Expr const*, clang::ento::ExplodedNode*, clang::ento::ExplodedNodeSet&)
  <src-root>/clang/lib/StaticAnalyzer/Core/ExprEngineC.cpp:413:61
...

 Fixes: https://github.com/llvm/llvm-project/issues/61960

 Reviewed By: donat.nagy

2023-09-10 11:19 UTC, steakhal commented
I guess this is one sideeffect of `getZExtValue` and `getSExtValue`.
To me, it feels like all such calls could hit the same assert, thus it fixes this instance, but we still lack a generic solution to this problem at other places.
I'm not opposing to this fix, but it might make sense to step back and grep for these calls to see the wider picture.

2023-09-11 11:00 UTC, DonatNagyE requested changes
I agree that it would be useful to systematically check the use of the `APSInt -> uint64_t` conversions, because it's likely that there are other ones that can lead to crashes.

2023-09-17 19:08 UTC, vabridgers commented on clang/test/Analysis/bitint-no-crash.c
> +}
Hi Donat, if you mean something like this, this does not crash. 

__int128 a;
__int128 b;
void c() {
  b = a;
}

2023-09-17 20:48 UTC, vabridgers commented on clang/lib/StaticAnalyzer/Core/SValBuilder.cpp
>        makeIntVal(ToTypeMax.isUnsigned() ? ToTypeMax.getZExtValue()
I think I fixed this, but it seems my push may not have worked as I expected :/ Checking this.

2023-09-18 09:45 UTC, vabridgers commented
The status above shows 1 change requested, but I believe I've resolved the requested changes. Please review at your convenience. Thank you.

2023-09-18 14:14 UTC, DonatNagyE approved these changes
Don't forget to update the commit message!

2023-09-18 16:07 UTC, steakhal approved these changes
What are the semantics of assigning a wider biting to a smaller one?
BTW LGTM.

2023-09-18 20:18 UTC, merged

2023-09-18 21:40 UTC, bjope commented
I reverted this patch since buildbots have been complaining for almost an hour.
Here is the first failure mail I got:

```
The Buildbot has detected a failed build on builder clang-armv8-quick while building clang.

Full details are available at:
    https://lab.llvm.org/buildbot/#/builders/245/builds/14207

Worker for this Build: linaro-clang-armv8-quick

BUILD FAILED: failed 1 unexpected failures 38187 expected passes 71 expected failures 36091 unsupported tests (failure)

Step 5 (ninja check 1) failure: 1 unexpected failures 38187 expected passes 71 expected failures 36091 unsupported tests (failure)
******************** TEST 'Clang :: Analysis/bitint-no-crash.c' FAILED ********************
Script:
--
: 'RUN: at line 1';   /home/tcwg-buildbot/worker/clang-armv8-quick/stage1/bin/clang -cc1 -internal-isystem /home/tcwg-buildbot/worker/clang-armv8-quick/stage1/lib/clang/18/include -nostdsysteminc -analyze -analyzer-constraints=range -setup-static-analyzer -analyzer-checker=core    -analyzer-checker=debug.ExprInspection    -verify /home/tcwg-buildbot/worker/clang-armv8-quick/llvm/clang/test/Analysis/bitint-no-crash.c
--
Exit Code: 1

Command Output (stderr):
--
error: 'expected-error' diagnostics seen but not expected: 
  File /home/tcwg-buildbot/worker/clang-armv8-quick/llvm/clang/test/Analysis/bitint-no-crash.c Line 7: signed _BitInt of bit sizes greater than 128 not supported
  File /home/tcwg-buildbot/worker/clang-armv8-quick/llvm/clang/test/Analysis/bitint-no-crash.c Line 8: signed _BitInt of bit sizes greater than 128 not supported
2 errors generated.

--
```