[RFC][GlobalISel] Use Builders in MatchTable
llvm/llvm-project pull request #65955
Opened 2023-09-11 12:45 UTC by Pierre-vh

The MatchTableExecutor did not use the MachineIRBuilder nor Observers to build instructions.
This meant that it only had a very superficial view of what's going on when rules are being applied. Custom code could create insts that the executor didn't know about.

Using a builder & an observer allows it to collect any instruction that's created as long as the same builder is used by the supporting C++ code. For instance, flags are propagated more thoroughly now.

Another benefit that may come later is that I'm trying to improve how constants are created in apply MIR patterns.
`MachineIRBuilder::buildConstant` automatically handles splats for us, this means that we may change `addCImm` to use that and handle vector cases automatically.
Overall it improves the flexibility and consistency of the builder

2023-09-11 20:07 UTC, arsenm commented
Currently you're only supposed to push one patch per pull request, you can just pre-push the test regeneration

2023-09-12 13:09 UTC, arsenm commented
I'm not really a fan of observers. Why does the match table need these? The execution should know precisely what it's doing without tracking other dynamic context?

2023-09-13 06:36 UTC, Pierre-vh commented
> I'm not really a fan of observers. Why does the match table need these? The execution should know precisely what it's doing without tracking other dynamic context?

We still use C++ most of the time, and it's impossible for the MatchTable to know what's going on in there unless it uses an observer, so I thought it'd be a nice change to use an observer for tracking all changes.
Likewise, when we use builder functions, like in #66077, we have no way of knowing how many insts were actually built without using a builder.

We can do without the builder, but then flag propagation will be a bit broken.

2023-09-22 10:34 UTC, qcolombet requested changes
I think it makes sense to use `MachineInstrBuilder` in general.
Regarding Observes, I think it makes sense (maybe?) to use them to manage the worklist of things that needs to be combined/selected, but it is a no-no IMHO for flag propagation.

2023-09-22 10:34 UTC, qcolombet commented on llvm/include/llvm/CodeGen/GlobalISel/GIMatchTableExecutorImpl.h
> +      Observer.changedInstr(*MI);
I don't think that code is correct anymore.
Given we have no control on which instructions end up in the CreatedInsts list anymore, I don't think it is safe to propagate flags blindly.

I've pointed out this problem in one of the test case that is updated in that pass.

2023-09-22 10:34 UTC, qcolombet commented on llvm/include/llvm/CodeGen/GlobalISel/GIMatchTableExecutorImpl.h
> +      Observer.erasingInstr(*MI);
I believe this fixes a problem that is independent from this PR.

Could you commit that part separately (and with a test if possible)?

2023-09-22 10:34 UTC, qcolombet commented on llvm/test/CodeGen/AArch64/GlobalISel/combine-sdiv.mir
> +    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = exact G_CONSTANT i32 3
It doesn't feel right to have the `exact` keyword on non-division like operations.

2023-09-22 11:22 UTC, Pierre-vh commented
I reverted the observer changes, so now it's just adding the MachineIRBuilder and nothing else changes pretty much.
It's all I need to implement the other patches in this series

2023-10-13 09:29 UTC, Pierre-vh commented
Ping :)

2023-10-13 10:29 UTC, jayfoad approved these changes
Looks reasonable to me.

2023-10-13 10:33 UTC, Pierre-vh commented
@qcolombet can this land? Thanks

2023-10-16 05:41 UTC, merged