[libc++] Remove _LIBCPP_AUTO_CAST
llvm/llvm-project pull request #66027
Opened 2023-09-11 23:07 UTC by philnik777

All supported compilers support `auto()`, so we can drop the workaround.

2023-09-12 16:36 UTC, EricWF commented
Even if you think the content of the patch is obvious, please write a description:
Considering including things like:

* Stating the two expressions are equivalent.
* using auto is more obviously correct.
* why the difference between `auto(x)` and `auto{x}` won't make a difference.

2023-09-12 16:36 UTC, EricWF requested changes
Please add a description, then otherwise this LGTM.

2023-11-23 23:18 UTC, ldionne commented
If no compilers are happy with this change, should we pursue it? If not, let's close.

2023-11-24 09:30 UTC, frederick-vs-ja reviewed
It's strange that `auto(x)` is only erroneous in `<__ranges/access.h>`.

2023-11-24 09:30 UTC, frederick-vs-ja commented on libcxx/include/__ranges/data.h
>      __can_borrow<_Tp> &&
`#include <__utility/auto_cast.h>` should also be removed from this file.

2024-03-17 19:25 UTC, philnik777 commented
Closing, since it turns out that the auto cast was not back-ported to older standards and we use it in a few places. I'll make a new patch which only removes its uses in C++23-only code.

2024-03-17 19:25 UTC, closed without merging