[sanitizer_symbolizer] Symbolizer Markup for linux
llvm/llvm-project pull request #66126
Opened 2023-09-12 18:46 UTC by avillega

This change adds support for sanitizer symbolizer markup for linux.
For more informationa about symbolzier markup please visit https://llvm.org/docs/SymbolizerMarkupFormat.html

2023-09-12 20:33 UTC, fmayer requested changes

2023-09-12 20:33 UTC, fmayer commented on compiler-rt/lib/sanitizer_common/sanitizer_symbolizer_libcdep.cpp
> +const ListOfModules *Symbolizer::GetRefreshedListOfModules() {
Why isn't this is a `const ListOfModules&`? This seems to always be non-NULL.

2023-09-12 20:33 UTC, fmayer commented on compiler-rt/lib/sanitizer_common/sanitizer_symbolizer_markup.cpp
> +  return module->base_address() == renderedModule->base_address &&
`assert(module->uuid_size) < sizeof(renderedModule->uuid)`

2023-09-12 20:33 UTC, fmayer commented on compiler-rt/lib/sanitizer_common/sanitizer_symbolizer_markup.cpp
> +  for (auto *it = renderedModules->begin(); it != renderedModules->end();
Why not use range-based loop?

2023-09-12 20:33 UTC, fmayer commented on compiler-rt/lib/sanitizer_common/sanitizer_symbolizer_markup.cpp
> +  for (auto *moduleIt = modules->begin(); moduleIt != modules->end();
Why no range-based loop?

2023-09-12 20:33 UTC, fmayer commented on compiler-rt/lib/sanitizer_common/sanitizer_symbolizer_markup.cpp
Can we link the reference for the markup format somewhere here?

2023-09-12 20:33 UTC, fmayer commented on compiler-rt/lib/sanitizer_common/sanitizer_symbolizer_markup.cpp
> +bool RenderNeedsSymbolizationMarkup() { return false; }
This always seems to be `false`? Why do we need this?

2023-09-12 20:33 UTC, fmayer commented on compiler-rt/lib/sanitizer_common/sanitizer_symbolizer_markup.cpp
> +bool MarkupSymbolizer::SymbolizeData(uptr addr, DataInfo *info) {
Add explanatory comment. This seems to *remove* symbols from the DataInfo, which is not obvious given the name.

2023-09-12 20:33 UTC, fmayer commented on compiler-rt/lib/sanitizer_common/sanitizer_symbolizer_markup.cpp
> +#if SANITIZER_SYMBOLIZER_MARKUP
I would prefer this as part of the includes above.

2023-09-12 20:33 UTC, fmayer commented on compiler-rt/lib/sanitizer_common/sanitizer_symbolizer_markup.cpp
>  // Always claim we succeeded, so that RenderDataInfo will be called.
This is not correct anymore

2023-09-12 20:33 UTC, fmayer commented on compiler-rt/lib/sanitizer_common/sanitizer_symbolizer_markup.cpp
>  // We ignore the format argument to __sanitizer_symbolize_global.
Explain why

2023-09-12 20:33 UTC, fmayer commented on compiler-rt/lib/sanitizer_common/sanitizer_symbolizer.h
> +  // returns the list of modules if it was refreshed
This doesn't seem to be what the method does from what I can tell.

2023-09-12 20:33 UTC, fmayer commented on compiler-rt/lib/sanitizer_common/sanitizer_symbolizer_markup.cpp
> +  SymbolizerTool *markupSymbolizer = tools_.front();
Why do we know this is `tools_[0]`? Why is this a list then?

2023-09-12 20:33 UTC, fmayer commented on compiler-rt/test/asan/TestCases/Linux/use-after-free-symbolizer-markup.cpp
> +// It does not test that asan works correctly.
I guess it kind of does, a bit? Otherwise we wouldn't get any report.

2023-09-12 20:33 UTC, fmayer commented on compiler-rt/lib/hwasan/hwasan_report.cpp
> +    uptr pc_mask = (1ULL << 48) - 1;
Maybe pull this and the other use out into a constexpr?

2023-09-12 20:33 UTC, fmayer commented on compiler-rt/lib/hwasan/hwasan_report.cpp
> +    const uptr *record_addr = &(*sa)[i];
if we made `sa` a reference this would be nicer, and there is only one caller for this

2023-09-12 20:33 UTC, fmayer commented on compiler-rt/lib/tsan/rtl/tsan_report.cpp
> +    if (const ListOfModules *modules =
I think you changed the code to never return nullptr here, so this if doesn't do anything?

2023-09-12 20:33 UTC, fmayer commented on compiler-rt/lib/hwasan/hwasan_report.cpp
> +  if (const ListOfModules *modules =
I think you changed the code to never return nullptr here, so this if doesn't do anything?

2023-09-12 20:33 UTC, fmayer commented on compiler-rt/lib/sanitizer_common/sanitizer_stacktrace_libcdep.cpp
> +      RenderFrame(output_, "", frame_num_++, cur->info.address, nullptr,
Add `/* foo = */` to the `""`

2023-09-13 06:57 UTC, petrhosek commented
Could we move functions in [compiler-rt/lib/sanitizer_common/sanitizer_stacktrace_printer.h](https://github.com/llvm/llvm-project/blob/231aa0f2120552b474bf86d5ff6721a6c555fdc3/compiler-rt/lib/sanitizer_common/sanitizer_stacktrace_printer.h) into a class, e.g. `StackTracePrinter`, of which there would be two implementations, e.g. `FormattedStackTracePrinter` and `MarkupStackTracePrinter`. That would eliminate a lot of these cases:

```
if (common_flags()->enable_symbolizer_markup)
  RenderFooMarkup(...)
else
  RenderFoo(...)
```

Instead we would end up with something like:

```
StackTracePrinter::GetOrInit()->RenderFoo(...)
```

This could be done as two changes. First to introduce the new class and refactor all existing use cases. Second to introduce the markup implementation. Each of these changes should be easier to review than the current patch.

2023-11-17 21:37 UTC, closed without merging