[clang] Avoid evaluating the BitWidth expression over and over again
llvm/llvm-project pull request #66203
Opened 2023-09-13 12:21 UTC by tbaederr

It's usually a ConstantExpr with a saved constant integer anyway, so we can just return that.

2023-09-13 12:26 UTC, cor3ntin approved these changes

2023-09-13 12:31 UTC, cor3ntin commented
Hum... should we put that in `EvaluateKnownConstInt` directly? Bitfields are not the only use case

2023-09-13 12:33 UTC, tbaederr commented
> Hum... should we put that in `EvaluateKnownConstInt` directly? Bitfields are not the only use case

See https://reviews.llvm.org/D155548 - I can't really support any of this with performance numbers (from my testing, I can't even support that we short-circuit `IntegerLiteral`s...), but this just seems like the right thing to do to me.

2023-09-13 12:55 UTC, cor3ntin requested changes
I knew there was a deja-vu here :)

I'd rather we do the general solution then. Maybe we should pursue the discussion on phab. I can't imagine the general solution is going to ever be noticeably worse.

I have the possibility to push a branch here http://llvm-compile-time-tracker.com/
@AaronBallman

2023-09-15 06:24 UTC, tbaederr commented
@cor3ntin Looking at this again... while I'd also like to see the general solution, I'd probably apply this anyway since it makes it clearer that this function can actually be fast. Its name is terrible for what it does. It sounds like it's a simply getter but in reality it might be pretty costly to call. This patch would mitigate this somewhat and make the performance expectations clearer when reading the code of this function.

2023-09-20 04:31 UTC, tbaederr commented
Ping

2023-09-27 04:48 UTC, tbaederr commented
Ping

2023-10-04 06:16 UTC, tbaederr commented
Ping

2023-10-06 12:39 UTC, AaronBallman commented
> @cor3ntin Looking at this again... while I'd also like to see the general solution, I'd probably apply this anyway since it makes it clearer that this function can actually be fast. Its name is terrible for what it does. It sounds like it's a simply getter but in reality it might be pretty costly to call. This patch would mitigate this somewhat and make the performance expectations clearer when reading the code of this function.

Once we have the general solution, this code would be redundant, wouldn't it? (I also would prefer the more general solution if reasonable -- playing whack-a-mole on constant evaluation is going to make for maintenance problems and this is an issue that plagues other parts of the compiler as well.)

2023-10-06 12:48 UTC, tbaederr commented
Well, this is not going to make a noticeable difference in runtime. https://reviews.llvm.org/D155548 didn't land because there are no measurements to make where this makes a measurable difference.

As for my earlier comment, it would also make sense to rename that function to `computeBitWidth()` or just cache the computed value (we compute it when parsing anyway to diagnose 0 size, etc. right?).

2023-10-06 13:00 UTC, AaronBallman commented
> Well, this is not going to make a noticeable difference in runtime. https://reviews.llvm.org/D155548 didn't land because there are no measurements to make where this makes a measurable difference.

Those changes didn't land because no measurements were attempted. Putting up a branch at https://llvm-compile-time-tracker.com/ would help get those measurements to at least start to see if there's benefit or harm from the changes.

> As for my earlier comment, it would also make sense to rename that function to `computeBitWidth()` or just cache the computed value (we compute it when parsing anyway to diagnose 0 size, etc. right?).

Caching the computed value would make sense, but that's sort of the goal of D155548, right? That's a generalized caching mechanism that should mean when we compute it to diagnose 0 size, we never need to re-compute it again.

2023-10-06 13:21 UTC, tbaederr commented
> > Well, this is not going to make a noticeable difference in runtime. https://reviews.llvm.org/D155548 didn't land because there are no measurements to make where this makes a measurable difference.
> 
> Those changes didn't land because no measurements were attempted. Putting up a branch at https://llvm-compile-time-tracker.com/ would help get those measurements to at least start to see if there's benefit or harm from the changes.

I did measure it, but only by myself, I can ask Nikita do use the compile-time tracker as well.

> 
> > As for my earlier comment, it would also make sense to rename that function to `computeBitWidth()` or just cache the computed value (we compute it when parsing anyway to diagnose 0 size, etc. right?).
> 
> Caching the computed value would make sense, but that's sort of the goal of D155548, right? That's a generalized caching mechanism that should mean when we compute it to diagnose 0 size, we never need to re-compute it again.

Well yes, we would never compute it again, but we still go through quite a few function calls to figure out that we've already computed it before. For a function called `getBitWidthValue()` I basically assume it has exactly one statement: `return BitWidthValue`.

I thought the bitwidth expression will always be a `ConstantExpr`, unless it's value-dependent (in which case it will be a `ConstantExpr` when we instantiate it, right?), but I might be wrong.

2023-10-06 13:32 UTC, AaronBallman commented
> > > Well, this is not going to make a noticeable difference in runtime. https://reviews.llvm.org/D155548 didn't land because there are no measurements to make where this makes a measurable difference.
> > 
> > 
> > Those changes didn't land because no measurements were attempted. Putting up a branch at https://llvm-compile-time-tracker.com/ would help get those measurements to at least start to see if there's benefit or harm from the changes.
> 
> I did measure it, but only by myself, I can ask Nikita do use the compile-time tracker as well.

Ah, I didn't realize you had measured on your own. But yeah, having some concrete numbers to play with would help.

> > > As for my earlier comment, it would also make sense to rename that function to `computeBitWidth()` or just cache the computed value (we compute it when parsing anyway to diagnose 0 size, etc. right?).
> > 
> > 
> > Caching the computed value would make sense, but that's sort of the goal of D155548, right? That's a generalized caching mechanism that should mean when we compute it to diagnose 0 size, we never need to re-compute it again.
> 
> Well yes, we would never compute it again, but we still go through quite a few function calls to figure out that we've already computed it before. For a function called `getBitWidthValue()` I basically assume it has exactly one statement: `return BitWidthValue`.

I'm hopeful the optimizer ends up inlining at least some of those calls, but otherwise, yeah you're right.

> I thought the bitwidth expression will always be a `ConstantExpr`, unless it's value-dependent (in which case it will be a `ConstantExpr` when we instantiate it, right?), but I might be wrong.

Per spec, it needs to be a constant expression. In terms of our implementation, I would also assume it would either be `ConstantExpr` or `IntegerLiteral` (which, strangely is an `Expr` and not a `ConstantExpr`)

2023-10-06 13:43 UTC, cor3ntin commented
> Ah, I didn't realize you had measured on your own. But yeah, having some concrete numbers to play with would help.

I'd like to see rough numbers too but I'm really hoping we can progress https://reviews.llvm.org/D155548.
I think it's the worse case it's harmless, at best it could have a pretty big positive impact.

2023-10-06 13:44 UTC, tbaederr commented
http://llvm-compile-time-tracker.com/index.php?config=NewPM-O3&stat=instructions%3Au&remote=tbaederr

2023-10-06 14:35 UTC, tbaederr commented
^ Removing integer and boolean expressions seems to have some negative impact though.

2023-10-10 11:50 UTC, tbaederr commented
I've merged https://reviews.llvm.org/D155548, so closing this.

2023-10-10 11:50 UTC, closed without merging