[LLDB] Add a setting for print hex values without leading zeroes
llvm/llvm-project pull request #66548
Opened 2023-09-15 20:43 UTC by walter-erquinigo

As suggested by Greg in https://github.com/llvm/llvm-project/pull/66534, I'm adding a setting at the Target level that controls whether to show leading zeroes in hex ValueObject values.

This has the benefit of reducing the amount of characters displayed in certain interfaces, like VSCode.

2023-09-15 20:46 UTC, clayborg approved these changes
Nice! LGTM

2023-09-15 20:47 UTC, clayborg requested changes

2023-09-15 20:47 UTC, clayborg commented on lldb/source/Core/DumpDataExtractor.cpp
> +        if (exe_scope->CalculateTarget()
Actually do you need to test if "exe_scope" is not NULL here?

2023-09-15 20:55 UTC, jimingham commented
There are other places we print hex numbers that don't go through the DataExtractor.  For instance, the "location" for a ValueObject is printed directly, so this change wouldn't catch it.  It's a little off-putting if you set a global setting to "not print leading zeros" and then sometimes we still print leading zeros.

This is not an objection to the contents of this patch, but I think to be complete we're going to end up finding more places where we should be checking this policy setting.

2023-09-15 21:09 UTC, walter-erquinigo commented
@jimingham , that's a good catch. Probably I should rename this because I want this setting to affect only SBValueObject::GetValue(), which is want ends up being sent to IDEs as a common interface. Trying to control all places that print as hex value is a bit too much and it'll be hard to enforce in the long term. Any particular suggestion? Because I can't really come up with a good name better than  `show-leading-zeroes-in-valueobject-values`.

2023-09-15 21:18 UTC, jimingham commented
That really should be `show-leading-zeros-in-valueobject-variables-using-hex-format`, shouldn't it?  I think you can actually just document what it actually does in the help string and then you shouldn't have to make the name overly pedantic.   The one you have already is probably enough.

2023-09-15 21:20 UTC, clayborg commented
> @jimingham , that's a good catch. Probably I should rename this because I want this setting to affect only SBValueObject::GetValue(), which is want ends up being sent to IDEs as a common interface. Trying to control all places that print as hex value is a bit too much and it'll be hard to enforce in the long term. Any particular suggestion? Because I can't really come up with a good name better than `show-leading-zeroes-in-valueobject-values`.

I think the setting name is ok as is. No one outside of LLDB developers have any idea what "valueobject" means. Also this setting is "show-hex-values-with-leading-zeroes" which does mention "values" so it can be ok for not all hex values emitted that are not values to have leading zeroes. The location is not a "value" technically and we might want some values coming out with leading zeroes like any command that dumps out table style output like "image dymp symtab" and other areas. Maybe we can name this setting:
```
show-hex-variable-values-with-leading-zeroes
```
The confirm this is for variable values only and not a system wide thing? 

If we switch the setting to be global in the target settings we can get the global target settings without needing to check the exe_scope. Thoughts?

2023-09-15 21:27 UTC, walter-erquinigo commented
I like Greg's proposal of naming it `show-hex-variable-values-with-leading-zeroes`. Seems very clear. I also like the idea of making it a global target config, which would simplify the code.

2023-09-15 21:46 UTC, walter-erquinigo commented
I've updated the PR following Greg's suggestions.

2023-09-16 04:46 UTC, clayborg reviewed
LGTM. Jim? You ok with this?

2023-09-18 16:47 UTC, jimingham commented
Sure.

2023-09-18 16:48 UTC, walter-erquinigo commented
Thanks Jim and Greg!

2023-09-18 16:48 UTC, merged

2023-09-19 07:50 UTC, DavidSpickett commented
This is failing on Arm 32 bit (https://lab.llvm.org/buildbot/#/builders/17/builds/43300), I'll reproduce and fix it. I expect it just needs to expect 8 hex characters instead of 16.

2023-09-19 08:53 UTC, DavidSpickett commented
https://github.com/llvm/llvm-project/commit/956860168b56f135b9facf3827ae9f3634d41f40

2023-09-19 12:23 UTC, walter-erquinigo commented
Thanks, man!

On Tue, Sep 19, 2023, 4:53 AM David Spickett ***@***.***>
wrote:

> 9568601
> <https://github.com/llvm/llvm-project/commit/956860168b56f135b9facf3827ae9f3634d41f40>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/llvm/llvm-project/pull/66548#issuecomment-1725090757>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAMKAMXBPHZKLWFBKO3EMPDX3FMRTANCNFSM6AAAAAA42J72F4>
> .
> You are receiving this because you modified the open/close state.Message
> ID: ***@***.***>
>