[InstSimplify] Fold `and A, (zext (icmp eq A, 0))` into 0
llvm/llvm-project pull request #66676
Opened 2023-09-18 17:39 UTC by dtcxzyw

This patch folds the pattern `and A, (zext (icmp eq A, 0))` into 0.
Fixes #66606.

2023-09-18 19:04 UTC, goldsteinn approved these changes
A bit niche, but LGTM.

2023-09-18 19:10 UTC, nikic requested changes
The general pattern here would be `zext(c) & a`, which is `c ? (a & 1) : 0`.

For the special case of `c := a == C`, if C is even then this reduces to `0`, if C is odd it reduces to `zext(c)`.

Possibly we shouldn't special case the `a == C` case though and just generally canonicalize to the select form, on which all possible folds can then be performed?

In any case, this needs to at least handle arbitrary constants.

2023-09-18 19:26 UTC, dtcxzyw commented
> The general pattern here would be `zext(c) & a`, which is `c ? (a & 1) : 0`.
> 
> For the special case of `c := a == C`, if C is even then this reduces to `0`, if C is odd it reduces to `zext(c)`.
> 
> Possibly we shouldn't special case the `a == C` case though and just generally canonicalize to the select form, on which all possible folds can then be performed?
> 
> In any case, this needs to at least handle arbitrary constants.

Proof: https://alive2.llvm.org/ce/z/xVWkj3

2023-09-19 06:20 UTC, closed without merging

2023-09-19 06:20 UTC, dtcxzyw commented
The canonicalization is posted as #66740.