[RISCV] Generalize the (ADD (SLLI X, 32), X) special case in constant…
llvm/llvm-project pull request #66931
Opened 2023-09-20 17:31 UTC by topperc

… materialization.

We don't have to limit ourselves to a shift amount of 32. We can support other shift amounts that make the upper 32 bits line up.

2023-09-20 23:01 UTC, preames requested changes

2023-09-20 23:01 UTC, preames commented on llvm/lib/Target/RISCV/RISCVISelLowering.cpp
> +  int64_t LoVal = SignExtend64<32>(Imm);
I really dislike the increasing duplication here.

Could we at least introduce a matchShiftedConstant helper?  Have it return the shift amount and instseq for the value by reference?

2023-09-20 23:04 UTC, topperc commented on llvm/lib/Target/RISCV/RISCVISelDAGToDAG.cpp
> +                                     CurDAG->getTargetConstant(32, DL, VT)),
Oops. yes

2023-09-22 15:53 UTC, preames commented on llvm/lib/Target/RISCV/RISCVISelLowering.cpp
> +  int64_t LoVal = SignExtend64<32>(Imm);
I took a shot at rolling this into the InstSeq abstraction.  I posted it here: https://github.com/llvm/llvm-project/pull/67159

I'm not sold on this approach myself.  I think it's probably only worth doing if we anticipate other cases where we want multiple live values in the same sequence.

2023-09-30 20:08 UTC, topperc commented
Moving to draft while I work out issues and refactor.

2023-10-01 18:43 UTC, topperc commented
I refactored the duplicate code into a new function in RISCVMatInt.

2023-10-02 19:14 UTC, preames approved these changes
LGTM w/minor comment

2023-10-02 19:14 UTC, preames commented on llvm/lib/Target/RISCV/RISCVISelDAGToDAG.cpp
> +      // Prefer ADD when possible.
Kill the oddly placed comment

2023-10-02 20:03 UTC, merged