[Libcxx][NFC] fixing missing forward declarations of uses_allocator_construction_args
llvm/llvm-project pull request #67044
Opened 2023-09-21 17:26 UTC by phyBrackets

Fixing #66714

2023-09-22 04:51 UTC, phyBrackets commented
Hi @philnik777 , thanks for the comment! I am kinda unsure about the current way of updating the tests is the best, have a look.

2023-09-22 14:05 UTC, phyBrackets commented
not exactly sure about this, test seems to get passed on my machine.

2023-09-23 14:12 UTC, phyBrackets commented
Not really sure why, test fail over modular build?

2023-09-27 14:48 UTC, ldionne requested changes
I think this looks pretty good to me, but I am struggling to figure whether there's other similar cases that would be problematic and for which we should add test coverage.

@philnik777 can you take a look since you wrote this in the first place?

2023-09-27 14:48 UTC, ldionne commented on libcxx/test/std/utilities/memory/allocator.uses/allocator.uses.construction/uses_allocator_construction_args.pass.cpp
> +  {
You can change the test to this:

```
{
    // See https://github.com/llvm/llvm-project/issues/66714
    {
      using NestedPairType = std::pair<int, std::pair<int, UsesAllocArgT>>;
      std::same_as<std::tuple<std::piecewise_construct_t,
                              std::tuple<>,
                              std::tuple<std::piecewise_construct_t,
                                         std::tuple<>,
                                         std::tuple<std::allocator_arg_t, const Alloc&>>>> auto ret =
          test_uses_allocator_construction_args<NestedPairType>(a);
          (void)ret;
    }
    {
      using NestedPairType = std::pair<int, std::pair<UsesAllocArgT, int>>;
      std::same_as<std::tuple<std::piecewise_construct_t,
                              std::tuple<>,
                              std::tuple<std::piecewise_construct_t,
                                         std::tuple<std::allocator_arg_t, const Alloc&>,
                                         std::tuple<>>>> auto ret =
        test_uses_allocator_construction_args<NestedPairType>(a);
        (void)ret;
    }
  }
```

It doesn't require using `std::pmr`.

2023-09-27 14:48 UTC, ldionne commented on libcxx/test/std/utilities/memory/allocator.uses/allocator.uses.construction/common.h
> +#include <memory_resource>
Then the changes in this file can be removed.

2023-09-27 16:17 UTC, ldionne commented
Also, this should probably be rebased on top of #66939 once it lands -- I think it'll be easier to do that than the other way around.

2023-10-09 18:48 UTC, EricWF commented
LGTM, but the bots need to get green and this change needs to be updated to merge cleanly.

2023-10-10 19:31 UTC, phyBrackets commented
Thanks @ldionne and @EricWF !

2023-10-10 21:31 UTC, philnik777 requested changes
This looks to me like we're adding a lot more forward declarations than tests, which makes me suspect that this is fixing bugs which we don't add regression tests for. Please make sure we test all the overloads (especially differently qualified pair overloads).

2023-10-10 21:31 UTC, philnik777 commented on libcxx/test/std/utilities/memory/allocator.uses/allocator.uses.construction/uses_allocator_construction_args.pass.cpp
> +    // See https://github.com/llvm/llvm-project/issues/66714
Could you add a short description instead of just a link to the bug report?

2023-10-17 09:42 UTC, philnik777 commented
It looks like you have some non-ASCII characters in your source. Did you copy the synopsis from eel.is/c++draft/? In that case they're probably in there.

2023-10-17 10:10 UTC, phyBrackets commented
No, I don't think so 🤔. Although I have tried to look at any non-ASCII character in case, using regex but didn't find any.

2023-10-17 14:20 UTC, philnik777 commented
Oh sorry. I misread the output. It looks like the clang-format versions of the formatting checker and our generated output runner are different. Just add `libcxx/test/std/utilities/memory/allocator.uses/allocator.uses.construction/uses_allocator_construction_args.pass.cpp` to the `ignore_format.txt` and run the CI again.

2023-10-17 19:15 UTC, phyBrackets commented
Thank you @philnik777 . Thoughts on the updated patch?

2023-10-21 11:31 UTC, philnik777 commented
Could you ping me again when the CI is green?

2023-11-01 14:52 UTC, ldionne commented
It looks like this is only failing in C++20 mode now, hopefully this should be pretty easy to fix?

2023-11-23 23:08 UTC, ldionne commented
Ping. I'd like to get this review finished and merged. If you have no time to work on it, please let us know and we'll find someone to pick it up, but we'd like to avoid accumulating too many outstanding reviews cause it makes the operation of the project harder.

2023-12-24 11:56 UTC, mordante commented
@phyBrackets are you still interested in finishing this patch?

2024-01-08 18:33 UTC, ldionne commented
I'll let @philnik777 finish the review on this one, don't let my "request for changes" block a merge.

2024-01-22 12:40 UTC, phyBrackets commented
Hi @philnik777 , Can you please review this? I am not actually sure what causing CI to fails.

2024-07-31 22:12 UTC, ldionne approved these changes

2024-08-01 12:54 UTC, merged