[Driver] -include: do not probe .gch
llvm/llvm-project pull request #67084
Opened 2023-09-22 02:13 UTC by MaskRay

`-include a.h` probes `a.h.pch` and `a.h.gch`, if not found, falls back to
`a.h`. `.pch` is the preferred extension name. Probing .gch is supposed to
provide compatibility with build systems that do
```
clang -x c-header a.h -o out/a.h.gch
clang -include out/a.h -c a.c  # out/a.h.gch is present while out/a.h is absent
```
(not sure what projects actually do this with Clang)

But it can often get in the way [0][1] when GCC and Clang are mixed as the file
format is incompatible with GCC's. Let's just stop probing .gch files.
Some tests using `-include` are switched to `.pch`.

[0]: https://discourse.llvm.org/t/how-to-have-clang-ignore-gch-directories/51835
[1]: https://bugreports.qt.io/browse/QTCREATORBUG-22427

2023-09-22 02:17 UTC, MaskRay commented
@madscientist

2023-09-22 16:22 UTC, jansvoboda11 commented
Xcode is actively using this feature: the `.pch` extension is used for headers that are to be precompiled, the `.pch.gch` extension is used for the actual precompiled header, and Clang is expected to expand the given `-include X.pch` argument into `-include-pch X.pch.gch`.

We're okay with changing the build system to explicitly pass `-include-pch X.pch.gch` to the compiler, but I think it would be more prudent for Clang to emit a deprecation warning for now and only remove this feature (land this patch) after the next upstream release is cut.

2023-09-22 16:25 UTC, jansvoboda11 requested changes
Xcode is actively using this feature: the .pch extension is used for headers that are to be precompiled, the .pch.gch extension is used for the actual precompiled header, and Clang is expected to expand the given -include X.pch argument into -include-pch X.pch.gch.

We're okay with changing the build system to explicitly pass -include-pch X.pch.gch to the compiler, but I think it would be more prudent for Clang to emit a deprecation warning for now and only remove this feature (land this patch) after the next upstream release is cut.

2023-09-24 18:20 UTC, MaskRay commented
> Xcode is actively using this feature: the `.pch` extension is used for headers that are to be precompiled, the `.pch.gch` extension is used for the actual precompiled header, and Clang is expected to expand the given `-include X.pch` argument into `-include-pch X.pch.gch`.
> 
> We're okay with changing the build system to explicitly pass `-include-pch X.pch.gch` to the compiler, but I think it would be more prudent for Clang to emit a deprecation warning for now and only remove this feature (land this patch) after the next upstream release is cut.

Sounds good. Switched to a `-Wdeprecated` diagnostic.

2023-09-25 16:10 UTC, jansvoboda11 approved these changes
Thanks! LGTM.

2023-09-26 11:53 UTC, nico commented
Can we add a dedicated `-Wdeprecated-gch` diag group or something for this? This is a very disruptive change, and it'd be good if we didn't have to disable all deprecation warnings while we rearrange things.

Reading the linked bugs, it's not clear that removing this would've helped all these issues all that much and it introduces a bunch of toil. So maybe we don't want to do this at all? But if we do, please put it behind a dedicated warning flag.

2023-09-26 12:23 UTC, zmodem commented
> Can we add a dedicated -Wdeprecated-gch diag group or something for this?

I gave it a flag in 39f36d5d5c88f49eaa946a3ee9ef887c04275a33

> (not sure what projects actually do this with Clang)

Turns out Chromium (and anyone else using gn) does: https://crbug.com/1486799
And probably other projects doing GCC-style pre-compiled header builds with Clang as a drop-in replacement for GCC.

In an environment like that, I'm not sure what action users should take when they see this warning: GCC doesn't understand `-include-pch`, and if `x.h.gch` is renamed to `x.h.pch`, GCC's `-include x.h` will not find it.

So it seems this feature really is necessary for drop-in compatibility with GCC.

2023-09-26 12:28 UTC, zmodem commented
As an archaeological note, the gch probing was added a long time ago in a2aedc69435dd430925e77022cbd26cc51e30982 with the motivation

> It's wonky, but we include looking for .gch so we can support seamless replacement into a build system already set up to be generating .gch files.

2023-09-26 17:56 UTC, MaskRay commented
> Reading the linked bugs, it's not clear that removing this would've helped all these issues all that much and it introduces a bunch of toil. So maybe we don't want to do this at all? But if we do, please put it behind a dedicated warning flag.

Clang PCH generation prefers `.pch` and the default extension name has been changed to use `.pch`. The inconvenience probing `.gch` happens when GCC and Clang `.pch` files are mismatched, which also happens with Clang tooling (language servers).

```
gcc -x c-header a.h
clang -include a.h -c a.c
```

Having a `-Wdeprecated-include-gch` looks good to me.

2023-09-26 18:22 UTC, zmodem commented
> Having a `-Wdeprecated-include-gch` looks good to me.

But do we intend to remove it later? That will break the drop-in ability of Clang, and probably a lot of people's builds.

> The inconvenience probing .gch happens when GCC and Clang .pch files are mismatched

To solve this, couldn't the driver peek at the magic at the start of the file or something like that?

2023-09-26 19:32 UTC, MaskRay commented
> > Having a `-Wdeprecated-include-gch` looks good to me.
> 
> But do we intend to remove it later? That will break the drop-in ability of Clang, and probably a lot of people's builds.
> 
> > The inconvenience probing .gch happens when GCC and Clang .pch files are mismatched
> 
> To solve this, couldn't the driver peek at the magic at the start of the file or something like that?

This is feasible but not elegant, and likely unnecessary.

I have tried many keywords to figure out `-o .*\.gch` users and the number is likely extremely small. Among them, there are many that place the `-include` header and `.gch` file in the same directory, and these users won't be affected at all (a lot of distributions do not use a separate build directory)
https://sourcegraph.com/search?q=context:global+-o%5B+%5D.*%5C.gch&patternType=regexp&sm=1&groupBy=repo

Many modern build systems (Bazel, Buck) require the full set of output files.
As an opt-in feature, PCH is typically not modeled at all, at least for the majority of packages.

2023-09-27 11:18 UTC, zmodem commented
The .gch probing has been part of Clang since 2009, and it matches GCC's behavior, so of course there are going to be users depending on it (Hyrum's law etc.). We don't have to look far for those users: Jan reported that Xcode relies on it, and I have reported that Chromium does as well. I think it's safe to assume that there are many more.

Because of that, I feel strongly that we should keep this behavior. It may be inelegant, but breaking our users is much worse.

Maybe one day Clang will define a new elegant driver interface without concerns about GCC or backwards compatibility, but that's not today.

If we want to solve the issues you linked to, checking the file magic seems like a more practical approach.

cc @llvm/clang-vendors in case there are more opinions.

2023-09-28 16:55 UTC, tahonermann commented
I am also rather uncomfortable with this behavioral change. There are a lot of build systems in use out there. My preference would be to continue to probe for a .gch file, but also validate that it is a (compatible) Clang PCH file before trying to use it.

2023-09-28 17:08 UTC, MaskRay commented
I'd appreciate seeing concrete evidence rather than relying solely on intuition. I've considered the potential disruption of deprecating `.gch` files but haven't been able to substantiate it (let's say the concern is about autotools users). When using the regular expression `-o.*\.gch`, I've found very few examples, and it's likely that many of them are not affected since many builds place an `-include`d file alongside a `.gch` file.

FWIW https://github.com/Kitware/CMake/blob/92adbb5d8c2a043c6e6c8539e9817a75a813fa1b/Modules/Compiler/Clang.cmake#L108 sets `set(CMAKE_PCH_EXTENSION .pch)`

2023-09-28 17:23 UTC, zmodem commented
> I'd appreciate seeing concrete evidence rather than relying solely on intuition.

XCode and GN are two concrete examples.

2023-10-16 13:54 UTC, zmodem commented
I've posted an alternative patch in https://github.com/llvm/llvm-project/pull/69204 which I believe is fixing the issues mentioned in this pr better (users don't have to wait another release), while not breaking builds relying on gch probing.

2024-05-03 08:11 UTC, cor3ntin commented
@MaskRay @zmodem Can we close this?

2024-05-04 06:57 UTC, closed without merging