Fix printing of 'pop' alias.
llvm/llvm-project pull request #67181
Opened 2023-09-22 19:11 UTC by Rot127

The condition to print the 'pop' alias could never be fulfilled, because the immediate was encoded for Address Modes 2.

2023-09-25 03:50 UTC, XVilka requested changes
I suppose test also should be updated:
```
Failed Tests (1):
     LLVM :: MC/Disassembler/ARM/basic-arm-instructions.txt
```

2023-09-25 20:25 UTC, jroelofs commented
Adding a test that exercises this would be good.

2023-09-25 20:29 UTC, Rot127 commented
Yes, sorry for being sloppy. Have made it in between some other things. Will add a test/ fix the old one soon.

2025-04-25 16:32 UTC, Rot127 commented
I will eventually come back to this. But currently I won't find time to finish this. We accumulated a few other LLVM fixes in Capstone anyways.

2025-04-25 16:32 UTC, closed without merging