[ARM] Add writeback information to STC and LDC instructions.
llvm/llvm-project pull request #67180
Opened 2023-09-22 19:11 UTC by Rot127

`LDC` and `STC` were missing the write-back register.

2023-09-25 03:46 UTC, XVilka requested changes

2023-09-25 03:46 UTC, XVilka commented on llvm/lib/Target/ARM/Disassembler/ARMDisassembler.cpp
> +    MCOperand_CreateImm0(Inst, (0));
```
FAILED: lib/Target/ARM/Disassembler/CMakeFiles/LLVMARMDisassembler.dir/ARMDisassembler.cpp.o
--
  | CCACHE_CPP2=yes CCACHE_HASHDIR=yes /usr/bin/ccache /usr/bin/clang++ -DBUILD_EXAMPLES -DGTEST_HAS_RTTI=0 -D_DEBUG -D_GLIBCXX_ASSERTIONS -D_GNU_SOURCE -D_LIBCPP_ENABLE_HARDENED_MODE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I/var/lib/buildkite-agent/builds/linux-56-7f758798dd-z9fgd-1/llvm-project/github-pull-requests/build/lib/Target/ARM/Disassembler -I/var/lib/buildkite-agent/builds/linux-56-7f758798dd-z9fgd-1/llvm-project/github-pull-requests/llvm/lib/Target/ARM/Disassembler -I/var/lib/buildkite-agent/builds/linux-56-7f758798dd-z9fgd-1/llvm-project/github-pull-requests/llvm/lib/Target/ARM -I/var/lib/buildkite-agent/builds/linux-56-7f758798dd-z9fgd-1/llvm-project/github-pull-requests/build/lib/Target/ARM -I/var/lib/buildkite-agent/builds/linux-56-7f758798dd-z9fgd-1/llvm-project/github-pull-requests/build/include -I/var/lib/buildkite-agent/builds/linux-56-7f758798dd-z9fgd-1/llvm-project/github-pull-requests/llvm/include -gmlt -fPIC -fno-semantic-interposition -fvisibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -pedantic -Wno-long-long -Wc++98-compat-extra-semi -Wimplicit-fallthrough -Wcovered-switch-default -Wno-noexcept-type -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wsuggest-override -Wstring-conversion -Wmisleading-indentation -Wctad-maybe-unsupported -fdiagnostics-color -ffunction-sections -fdata-sections -O3 -DNDEBUG -fvisibility=hidden  -fno-exceptions -funwind-tables -fno-rtti -UNDEBUG -std=c++17 -MD -MT lib/Target/ARM/Disassembler/CMakeFiles/LLVMARMDisassembler.dir/ARMDisassembler.cpp.o -MF lib/Target/ARM/Disassembler/CMakeFiles/LLVMARMDisassembler.dir/ARMDisassembler.cpp.o.d -o lib/Target/ARM/Disassembler/CMakeFiles/LLVMARMDisassembler.dir/ARMDisassembler.cpp.o -c /var/lib/buildkite-agent/builds/linux-56-7f758798dd-z9fgd-1/llvm-project/github-pull-requests/llvm/lib/Target/ARM/Disassembler/ARMDisassembler.cpp
  | /var/lib/buildkite-agent/builds/linux-56-7f758798dd-z9fgd-1/llvm-project/github-pull-requests/llvm/lib/Target/ARM/Disassembler/ARMDisassembler.cpp:1953:5: error: use of undeclared identifier 'MCOperand_CreateImm0'
  | MCOperand_CreateImm0(Inst, (0));
  | ^
  | 1 error generated.
```

2023-09-26 02:38 UTC, XVilka approved these changes
Failure seems unrelated:
```
FAILED: unittests/tools/llvm-profgen/LLVMProfgenTests.exe
--
  | cmd.exe /C "cd . && C:\BuildTools\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe -E vs_link_exe --intdir=unittests\tools\llvm-profgen\CMakeFiles\LLVMProfgenTests.dir --rc="C:\Program Files (x86)\Windows Kits\10\bin\10.0.19041.0\x64\rc.exe" --mt="C:\Program Files (x86)\Windows Kits\10\bin\10.0.19041.0\x64\mt.exe" --manifests  -- C:\BuildTools\VC\Tools\MSVC\14.29.30133\bin\Hostx64\x64\link.exe /nologo unittests\tools\llvm-profgen\CMakeFiles\LLVMProfgenTests.dir\ContextCompressionTest.cpp.obj unittests\tools\llvm-profgen\CMakeFiles\LLVMProfgenTests.dir\__\__\__\resources\windows_version_resource.rc.res  /out:unittests\tools\llvm-profgen\LLVMProfgenTests.exe /implib:unittests\tools\llvm-profgen\LLVMProfgenTests.lib /pdb:unittests\tools\llvm-profgen\LLVMProfgenTests.pdb /version:0.0 /machine:x64 /STACK:10000000 /INCREMENTAL:NO /subsystem:console  lib\LLVMSupport.lib  lib\LLVMSupport.lib  lib\llvm_gtest_main.lib  lib\llvm_gtest.lib  lib\LLVMTestingSupport.lib  lib\llvm_gtest.lib  lib\LLVMSupport.lib  psapi.lib  shell32.lib  ole32.lib  uuid.lib  advapi32.lib  delayimp.lib  -delayload:shell32.dll  -delayload:ole32.dll  lib\LLVMDemangle.lib  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
  | MT: command "C:\Program Files (x86)\Windows Kits\10\bin\10.0.19041.0\x64\mt.exe /nologo /manifest unittests\tools\llvm-profgen\LLVMProfgenTests.exe.manifest /outputresource:unittests\tools\llvm-profgen\LLVMProfgenTests.exe;#1" failed (exit code 0x1f) with the following output:
  |  
  | mt.exe : general error c101008d: Failed to write the updated manifest to the resource of file "unittests\tools\llvm-profgen\LLVMProfgenTests.exe". Operation did not complete successfully because the file contains a virus or potentially unwanted software.
  | [9679/9687] Linking CXX executable unittests\tools\llvm-exegesis\LLVMExegesisTests.exe
  | [9681/9687] Linking CXX executable tools\clang\unittests\Tooling\ToolingTests.exe
  | ninja: build stopped: subcommand failed.
```

2024-03-29 14:40 UTC, AtariDreams commented
Ping?

2024-03-30 15:02 UTC, Rot127 commented
It is still on the todo list. Sorry for letting it run stale. Will update it soon.

2025-04-25 16:33 UTC, Rot127 commented
I will eventually come back to this. But currently I won't find time to finish this. We accumulated a few other LLVM fixes in Capstone anyways.

2025-04-25 16:33 UTC, closed without merging