[InstCombine] Fold `ctpop(X) <u 2` into `ctpop(X) == 1` if X is non-zero
llvm/llvm-project pull request #67268
Opened 2023-09-24 15:25 UTC by dtcxzyw

This patch folds pattern `ctpop(X) <u 2` into `ctpop(X) == 1` if we know `X` is non-zero.
Fixes #57328.

2023-09-24 16:07 UTC, nikic requested changes
ctpop < 2 is better than ctpop == 1 for the backend, and we will no be able to recover from this transform in the backend if it comes from an assume.

2023-09-24 17:00 UTC, goldsteinn commented
Maybe leave a comment explaining as much though. But nikic is right, we intentionally don't do this. In the backend if we still have non-zero info we optimize this properly.

2023-09-24 17:36 UTC, nikic commented on llvm/lib/Transforms/InstCombine/InstCombineCompares.cpp
> +  if (Pred == ICmpInst::ICMP_EQ && CRhs == 1 &&
You should handle the conjugate `ne` case as well.

2023-09-25 20:19 UTC, nikic reviewed
This fold goes against the usual direction in IR, and in particular conflicts with this generic  fold: https://github.com/llvm/llvm-project/blob/bb764eccf8053244d64270df29c2e0bd3606f6c0/llvm/lib/Transforms/InstCombine/InstCombineCompares.cpp#L6207-L6210 This is risky and can easily lead to infinite loops. I think we won't get one right now because KnownBits for ctpop is a bit weak (https://github.com/llvm/llvm-project/blob/d3505c28a770fabd77d7483afbca383d453bef02/llvm/lib/Analysis/ValueTracking.cpp#L1560), but if it was later strengthened and e.g. inferred KnownBits `...0?1` then we could run into an infinite compile loop at that point.

2023-09-26 02:47 UTC, dtcxzyw commented
> This fold goes against the usual direction in IR, and in particular conflicts with this generic fold:
> 
> https://github.com/llvm/llvm-project/blob/bb764eccf8053244d64270df29c2e0bd3606f6c0/llvm/lib/Transforms/InstCombine/InstCombineCompares.cpp#L6207-L6210
> 
> This is risky and can easily lead to infinite loops. I think we won't get one right now because KnownBits for ctpop is a bit weak (
> https://github.com/llvm/llvm-project/blob/d3505c28a770fabd77d7483afbca383d453bef02/llvm/lib/Analysis/ValueTracking.cpp#L1560
> 
> ), but if it was later strengthened and e.g. inferred KnownBits `...0?1` then we could run into an infinite compile loop at that point.

Can we canonicalize `ctpop(X) <u 2` into `ctpop(X) == 1` in InstCombine and do inverse transform in CodeGenPrepare?

2023-09-26 08:35 UTC, nikic commented
In theory yes, but in practice CGP drops assumes at the very start, and I don't want to have a special ctpop fold run before that. I'd only take that if we stop dropping assumes in CGP (which is on the long-term roadmap, but tricky).

2023-10-23 11:22 UTC, closed without merging