[RISCV] Support VLS for VCIX
llvm/llvm-project pull request #67289
Opened 2023-09-25 07:30 UTC by 4vtomat

2023-09-25 16:43 UTC, topperc requested changes

2023-09-25 16:43 UTC, topperc commented on llvm/lib/Target/RISCV/RISCVISelLowering.cpp
> +    SDValue ScalableVector =
This should have two results, the RetContainerVT and MVT::Chain

2023-09-25 16:43 UTC, topperc commented on llvm/lib/Target/RISCV/RISCVISelLowering.cpp
> +    return DAG.getMergeValues({FixedVector, Op.getOperand(0)}, DL);
`Op.getOperand(0)` should be `ScalableVector.getValue(1)` after making `ScalableVector` have two results.

2023-10-03 08:31 UTC, 4vtomat commented
ping

2023-10-03 16:20 UTC, topperc approved these changes
LGTM

2023-10-06 17:29 UTC, merged