[RISCV] Fix a crash from trying to truncate an FP type in lowerBuildV…
llvm/llvm-project pull request #67488
Opened 2023-09-26 21:00 UTC by topperc

…ectorOfConstants.

ComputeNumSignBits can return an answer for FP constants based on bitcasting them to int.

Check for an integer type so we don't create an illegal truncate.

We could support this case with bitcasts, but I leave that to a separate patch.

2023-09-26 21:21 UTC, preames requested changes
LGTM

2023-09-26 21:49 UTC, topperc commented
> LGTM

I think you clicked the request changes button instead of approve?

2023-09-27 10:21 UTC, lukel97 approved these changes

2023-09-27 14:43 UTC, preames approved these changes
Still LGTM and I definitely selected Approve this time.

2023-09-27 19:21 UTC, merged