BlockFrequencyInfo: Add PrintBlockFreq helper
llvm/llvm-project pull request #67512
Opened 2023-09-27 00:47 UTC by MatzeB

- Refactor the (Machine)BlockFrequencyInfo::printBlockFreq functions into a `PrintBlockFreq()` function returning a `Printable` object. This simplifies usage as it can be directly piped to a `raw_ostream` like `dbgs() << PrintBlockFreq(MBFI, Freq) << '\n';`.
- Previously there was an interesting behavior where `BlockFrequencyInfoImpl` stores frequencies both as a `Scaled64` number and as an `uint64_t`. Most algorithms use the `BlockFrequency` abstraction with the integers, the print function for basic blocks printed the `Scaled64` number potentially showing higher accuracy than was used by the algorithm. This changes things to only print `BlockFrequency` values.
- Replace some instances of `dbgs() << Freq.getFrequency()` with the new function.

2023-09-27 19:37 UTC, WenleiHe approved these changes
LGTM.

2023-09-27 19:37 UTC, WenleiHe commented on llvm/lib/Analysis/BlockFrequencyInfoImpl.cpp
> -  return OS << getFloatingBlockFreq(Node);
thanks for cleaning this up..

2023-09-27 20:04 UTC, mtrofin commented on llvm/include/llvm/Analysis/BlockFrequencyInfoImpl.h
> +void PrintBlockFreqImpl(raw_ostream &OS, uint64_t EntryFreq,
this fct can be `const`, right?

2023-09-27 20:06 UTC, mtrofin approved these changes

2023-09-27 20:06 UTC, mtrofin commented on llvm/include/llvm/Analysis/BlockFrequencyInfo.h
> +Printable PrintBlockFreq(const BlockFrequencyInfo &BFI, BlockFrequency Freq);
can these 2 fcts be `const`?

2023-09-27 21:31 UTC, MaskRay commented on llvm/include/llvm/Analysis/BlockFrequencyInfo.h
> +Printable PrintBlockFreq(const BlockFrequencyInfo &BFI, BlockFrequency Freq);
`functionName` for new functions.

2023-09-27 21:32 UTC, MaskRay requested changes

2023-09-27 21:32 UTC, MaskRay commented on llvm/include/llvm/Analysis/BlockFrequencyInfo.h
> +Printable PrintBlockFreq(const BlockFrequencyInfo &BFI, BlockFrequency Freq);
Use `functionName` for new functions.

2023-09-27 22:21 UTC, MatzeB commented on llvm/include/llvm/Analysis/BlockFrequencyInfoImpl.h
> +void PrintBlockFreqImpl(raw_ostream &OS, uint64_t EntryFreq,
> this fct can be const, right?

It's a function, not a class method.

2023-10-02 22:21 UTC, MatzeB commented
@MaskRay is this good to go now?

2023-10-05 20:25 UTC, MatzeB commented
I believe I have addressed the feedback from @MaskRay and it's been a week. Will rebase and land now.

2023-10-06 01:26 UTC, merged