[libc++] Add std::fpclassify overloads for floating-point.
llvm/llvm-project pull request #67913
Opened 2023-10-01 13:01 UTC by antl-m

Standard says that implementation of math functions that have floating-point-type parameter should provide an "overload for each cv-unqualified floating-point type".

2023-10-01 13:28 UTC, philnik777 requested changes
The implementation looks good, but this needs tests. Specifically,
- there should be a regression test to make sure an implicit conversion works now
- please make sure that we have test coverage for the `_LIBCPP_NODISCARD_EXT`s
- please make sure that we have test for the `noexcept`ness of the overloads.

You should be able to find tests for this under `libcxx/test/libcxx/{diagnostics,numerics/c.math}` if they exist.

2023-10-02 21:09 UTC, antl-m commented
Sorry, I pulled commits from main :(
I'll revert it

2023-10-02 21:33 UTC, antl-m commented
Now code diff's showing correct changes. But I'll probably need to create new PR to merge changes without extra commits...

Added tests for implicit conversions and `noexcept`ness to `libcxx/test/std/numerics/c.math/cmath.pass.cpp`.
Tests for `nodiscard` already exist in `libcxx/test/libcxx/diagnostics/math_nodiscard_extensions.verify.cpp`.

2023-10-02 21:38 UTC, philnik777 commented
You can just rebase to fix your issues.

2023-10-02 21:46 UTC, antl-m commented
Maybe I've done something wrong, but I've rebased and those all commits from main were added ahead of mine and appeared here...
I can somehow fix that and remove these commits from PR?

2023-10-02 21:57 UTC, philnik777 commented
You probably did something wrong while rebasing. In a rebase workflow you want a single commit that you're force-pushing to your branch generally. It looks like you had a merge commit or something like that and the new commits got rebased onto that, resulting in different hashes; i.e. different commits. When running `git log HEAD...main` in your branch you should see only the commits you want to be part of this PR until you see `origin/main`, or `upstream/main` or whatever you named the upstream repo. (And no worries; I pinged dozens of people a few times too when I screwed up a rebase - happens to everyone)

2023-10-02 22:12 UTC, antl-m commented
`git log HEAD...main` on my branch gives all commits that I've merged (when I did rebase) and then reverted + commits relevant to this PR. I don't know if I can remove them now...

2023-10-02 22:28 UTC, philnik777 commented
You should be able to `git rebase -i main` and then drop the commits.

2023-10-02 22:35 UTC, antl-m commented
Many thanks, that worked! I should definitely read more documentation on how git rebase works and be more careful next time : )

2023-10-05 09:07 UTC, philnik777 approved these changes
LGTM with a comment added.

2023-10-05 09:07 UTC, philnik777 commented on libcxx/include/math.h
> +template <class = int>
Could you add a comment why this is required on the non-double overloads too?

2023-10-05 19:18 UTC, merged