[Target] Change `no-trap-after-noreturn` to `trap-after-noreturn`
llvm/llvm-project pull request #67925
Opened 2023-10-01 16:14 UTC by chsigg

2023-10-01 16:57 UTC, chsigg commented
The buildkite failure is unrelated to this PR. The culprit is commit https://github.com/llvm/llvm-project/commit/6403287eff71a3d6f6c862346d6ed3f0f000eb70.

2023-10-01 19:04 UTC, nikic requested changes
Please add a patch description justifying this change. As-is, this seems like a pointless rename to me.

2023-10-02 19:39 UTC, Artem-B commented
> Please add a patch description justifying this change. As-is, this seems like a pointless rename to me.

I've suggested renaming it to improve readability. Double negations in a single word are already hard to read, and when it's used in a negation, `!NoTrapAfterNoreturn` looks outright odd to me.

We don't need these changes, but I think it's a nice cleanup.

2023-10-02 19:46 UTC, nikic commented
NoTrapAfterNoreturn is a modifier on TrapUnreachable. You enable traps and then disable some of them again. If you formulate this positively, it looks like TrapAfterNoreturn=true should work independently of TrapUnreachable (insert traps after noreturn calls only), which is not how this actually works.

2023-10-03 01:21 UTC, Artem-B commented
OK. If the naming was intentional, I'm fine keeping it as is.

2023-10-03 05:08 UTC, closed without merging

2023-10-03 08:11 UTC, MaskRay commented
> OK. If the naming was intentional, I'm fine keeping it as is.

I think a variable with a positive meaning (`TrapAfterNoreturn`) is preferred.  You could make the change non-functional.

It's just that how `TrapAfterNoreturn` is set to true and false should be thought carefully.