[mlir][CAPI, python bindings]
llvm/llvm-project pull request #67922
Opened 2023-10-01 16:02 UTC by makslevental

Expose `Operation::setSuccessor`.

2023-10-01 18:23 UTC, jpienaar approved these changes
Looks good, thanks (I see this follows the C convention, I'd have flipped block and pos, but keeping consistent better).

2023-10-02 09:14 UTC, ftynse requested changes

2023-10-02 09:14 UTC, ftynse commented on mlir/lib/Bindings/Python/IRCore.cpp
> +      });
Have you considered a more Pythonic and less imperative syntax here? E.g., defining an list-like `successors` field so one can do `len(op.successors)` or `op.successor[42] = ...`?  We do something similar with operand and results, so there is even the C++ glue code for defining interface classes.

2023-10-02 17:07 UTC, ftynse approved these changes

2023-10-02 20:37 UTC, merged