[LLVM][DWARF] Create thread safe context for DWP DWARFContext
llvm/llvm-project pull request #68262
Opened 2023-10-04 21:42 UTC by ayermolo

Right now DWARFContext is created is the same when input is DWO or DWP file.
Changed so that for DWP it creates a thread safe context.

2023-10-09 16:35 UTC, ayermolo commented
@dwblaikie @clayborg ping :D

2023-10-09 17:05 UTC, clayborg requested changes

2023-10-09 17:05 UTC, clayborg commented on llvm/lib/DebugInfo/DWARF/DWARFContext.cpp
> +        FileName.find(".dwp") != StringRef::npos);
Add a comment stating why your are enabling threading support and make a local variable so we can add a comment:
```
// Allow multi-threaded access if there is a .dwp file as the CU index 
// and TU index might be accessed from multiple threads.
bool ThreadSafe = FileName.find(".dwp") != StringRef::npos;
S->Context = DWARFContext::create(
        *S->File.getBinary(), DWARFContext::ProcessDebugRelocations::Ignore,
        nullptr, "", WithColor::defaultErrorHandler,
        WithColor::defaultWarningHandler, ThreadSafe);
```

2023-10-09 17:46 UTC, clayborg approved these changes

2023-10-09 18:13 UTC, dwblaikie commented
Not sure I follow - wouldn't it be suitable for a ThreadUnsafeDWARFContext to create a ThreadUnsafeDWARFContext for the DWP? And only a ThreadSafeDWARFContext would create a ThreadSafeDWARFContext for the DWP?

2023-10-09 18:18 UTC, clayborg commented
> Not sure I follow - wouldn't it be suitable for a ThreadUnsafeDWARFContext to create a ThreadUnsafeDWARFContext for the DWP? And only a ThreadSafeDWARFContext would create a ThreadSafeDWARFContext for the DWP?

No one is creating a thread safe context right now except llvm-gsymutil. So we could enable thread safe everywhere, but people seemed to think there would be some performance hit if that was done.

2023-10-09 18:23 UTC, clayborg commented
> > Not sure I follow - wouldn't it be suitable for a ThreadUnsafeDWARFContext to create a ThreadUnsafeDWARFContext for the DWP? And only a ThreadSafeDWARFContext would create a ThreadSafeDWARFContext for the DWP?
> 
> No one is creating a thread safe context right now except llvm-gsymutil. So we could enable thread safe everywhere, but people seemed to think there would be some performance hit if that was done.

If this issue here was we had a thread safe DWARContext for the main DWARF, and this wasn't being correctly propagated into the .dwp DWARFContext, then this should be fixed by detecting the thread safe setting from the DWARContext and using that setting for any child DWARFContext (.dwp and any .dwo files that are not in a .dwp file) objects.

2023-10-09 20:04 UTC, dwblaikie commented
> > > Not sure I follow - wouldn't it be suitable for a ThreadUnsafeDWARFContext to create a ThreadUnsafeDWARFContext for the DWP? And only a ThreadSafeDWARFContext would create a ThreadSafeDWARFContext for the DWP?
> > 
> > 
> > No one is creating a thread safe context right now except llvm-gsymutil. So we could enable thread safe everywhere, but people seemed to think there would be some performance hit if that was done.
> 
> If this issue here was we had a thread safe DWARContext for the main DWARF, and this wasn't being correctly propagated into the .dwp DWARFContext, then this should be fixed by detecting the thread safe setting from the DWARContext and using that setting for any child DWARFContext (.dwp and any .dwo files that are not in a .dwp file) objects.

But this code change is being made in the `ThreadUnsafeDWARFContextState` - the thread unsafe class is making a thread safe DWP context. That doesn't seem right? Shouldn't only a ThreadSafeDWARFContextState create a thread safe context for the DWP?

2023-10-09 21:55 UTC, clayborg commented
So sounds like we need to change this patch to propagate the "ThreadSafe" from one context to any child DWARFContext things (like for owned .dwp and .dwo contexts. I would recommend adding a new virtual function to DWARFContext:
```
virtual bool IsThreadSafe() = 0;
```
Then have ThreadUnsafeDWARFContextState override this and return false, and ThreadSafeState override it return true. Then it will be easy to propagate the setting using the current "DWARFContext::State" iivar from a DWARFContext to create another.

2023-10-09 22:04 UTC, ayermolo commented
OK, will make the change so that DWO/DWP DWARFContext is controlled by main binary DWARFContext thread safetiness.

2023-10-10 05:21 UTC, dwblaikie approved these changes
Sounds OK

2023-10-10 13:53 UTC, merged