[MLIR][Presburger] Fix reduce bug in Fraction class and add tests
llvm/llvm-project pull request #68298
Opened 2023-10-05 10:20 UTC by Abhinav271828

We modify `Fraction.reduce()` to work with negative fractions as well.
We add tests to verify the implementation of arithmetic and relational operators on Fractions.

2023-10-05 10:27 UTC, Groverkss requested changes
Please remove the libcxx changes

2023-10-06 00:18 UTC, Superty requested changes

2023-10-06 00:18 UTC, Superty commented on mlir/unittests/Analysis/Presburger/FractionTest.cpp
> +  ASSERT_FALSE(g < f);
You can use EXPECT_TRUE/EXPECT_FALSE here

2023-10-06 00:18 UTC, Superty commented on mlir/unittests/Analysis/Presburger/FractionTest.cpp
> +}
please add a new line to the end of the file

2023-10-06 16:17 UTC, merged

2023-10-06 16:17 UTC, Superty commented
Thanks!