Port CodeGenPrepare to new pass manager
llvm/llvm-project pull request #68530
Opened 2023-10-08 15:22 UTC by Krishna-13-cyber

2023-10-09 14:26 UTC, arsenm requested changes

2023-10-09 14:26 UTC, arsenm commented on llvm/lib/CodeGen/CodeGenPrepare.cpp
> +  CodeGenPrepare CGP;
I'd expect this to be constructed with the TargetMachine, not have a TM argument

2023-10-09 14:26 UTC, arsenm commented on llvm/lib/CodeGen/CodeGenPrepare.cpp
> +  // auto &BBSectionsProfileReader =
Don't comment this out?

2023-10-09 14:26 UTC, arsenm commented on llvm/lib/CodeGen/CodeGenPrepare.cpp
> +  auto *TPC = getAnalysisIfAvailable<TargetPassConfig>();
Do you still need this if the TM is passed to the constructor function?

2023-10-09 14:26 UTC, arsenm commented on llvm/lib/CodeGen/CodeGenPrepare.cpp
> +// auto &BasicBlockSectionsProfileReader = AM.getResult<BasicBlockSectionsProfileReader>(F);
This is another analysis pass that needs to be ported as a dependency

2023-10-09 14:26 UTC, arsenm commented on llvm/lib/CodeGen/CodeGenPrepare.cpp
> +  // TM = &getAnalysisUsage<TargetPassConfig>().getTM<TargetMachine>();
Drop this, it comes from the pass constructor

2023-10-09 14:26 UTC, arsenm commented on llvm/lib/CodeGen/CodeGenPrepare.cpp
> +bool CodeGenPrepare::run(Function &F, const TargetMachine *TM,
Don't need the TM argument

2023-10-09 14:26 UTC, arsenm commented on llvm/lib/CodeGen/CodeGenPrepare.cpp
> +  // TTI = &getAnalysis<TargetTransformInfoWrapperPass>().getTTI(F);
Get TTI with &AM.getResult<TargetIRAnalysis>(F)

2023-10-09 14:26 UTC, arsenm commented on llvm/lib/CodeGen/CodeGenPrepare.cpp
> +  // TLInfo = &getAnalysis<TargetLibraryInfoWrapperPass>().getTLI(F);
AM.getResult<TargetLibraryAnalysis>(F)

2023-10-09 14:26 UTC, arsenm commented on llvm/lib/CodeGen/CodeGenPrepare.cpp
> +  // LI = &getAnalysis<LoopInfoWrapperPass>().getLoopInfo();
AM.getResult<LoopAnalysis>(F)

2023-10-09 14:26 UTC, arsenm commented on llvm/lib/CodeGen/CodeGenPrepare.cpp
> +  // PSI = &getAnalysis<ProfileSummaryInfoWrapperPass>().getPSI();
Looking at ConstantHoisting as an example, I think you need something like:

```
  auto &MAMProxy = AM.getResult<ModuleAnalysisManagerFunctionProxy>(F);
  auto *PSI = MAMProxy.getCachedResult<ProfileSummaryAnalysis>(*F.getParent());
```

2023-10-09 14:26 UTC, arsenm commented on llvm/lib/CodeGen/CodeGenPrepare.cpp
> +  //     getAnalysisIfAvailable<BasicBlockSectionsProfileReader>();
This needs to be ported for access through the analysis manager

2024-01-09 17:46 UTC, Krishna-13-cyber commented
Hi @nickleus27 ,
Thanks for carrying the work as I couldn't continue due to hardware constraints on my side.

Closing this PR as done in #75380

2024-01-09 17:46 UTC, closed without merging