[clang][dataflow] Add support for lambda captures
llvm/llvm-project pull request #68558
Opened 2023-10-09 07:09 UTC by sgatev

This adds support for copy, ref, and this lambda captures to the core framework and also adds relevant test in UncheckedOptionalAccessTest.

2023-10-09 22:20 UTC, Xazax-hun approved these changes
LG!

2023-10-10 14:59 UTC, ymand requested changes

2023-10-10 14:59 UTC, ymand commented on clang/unittests/Analysis/FlowSensitive/UncheckedOptionalAccessModelTest.cpp
> +TEST_P(UncheckedOptionalAccessTest, Lambda) {
Please split these into individual tests.

2023-10-10 20:40 UTC, sgatev commented on clang/unittests/Analysis/FlowSensitive/TransferTest.cpp
> +        EXPECT_THAT(BarLoc, IsNull());
It's null because `Bar` isn't used in the body of the lambda. I added a comment to make this clear.

2023-10-10 20:40 UTC, sgatev commented on clang/unittests/Analysis/FlowSensitive/UncheckedOptionalAccessModelTest.cpp
> +TEST_P(UncheckedOptionalAccessTest, Lambda) {
Done.

2023-10-11 13:31 UTC, ymand approved these changes
Thanks!

2023-10-11 20:18 UTC, merged