[Flang][OpenMP] Fix comments that should not be Sentinels on fixed format. (#68653)
llvm/llvm-project pull request #68911
Opened 2023-10-12 16:30 UTC by Z572

Fixes #68653

2023-10-12 20:44 UTC, rofirrim requested changes

2023-10-13 09:28 UTC, Z572 commented on flang/lib/Parser/prescan.cpp
> +  if (p[0] != '$') {
looks like this code cannot diagnostic,i opened a new issues #68966

2023-10-13 09:40 UTC, kiranchandramohan commented
> no idea why Lower/OpenMP/parallel-private-clause-fixes.f90 test fail.

Do you have https://github.com/llvm/llvm-project/commit/ef9f6170b61647e07ecbeabea7400bf4ac8e1fce in your branch from where you made this PR? If not could you rebase?

2023-10-13 12:51 UTC, rofirrim reviewed
LGTM. But let's wait for @klausler in case he has further comments.

2023-10-13 12:51 UTC, rofirrim commented on flang/test/Parser/OpenMP/sentinels.f
> +!dir$ ignore_tkr a
Can you add a second dummy argument (say `b`) and split an `ignore_tkr` directive like so (mind the extra blank at the beginning of the continuing line), so we have a test for a continuation as well?

```fortran
        subroutine sub(a, b)
!dir$ ignore_tkr
!dir$+ b
!dir$ ignore_tkr a
      real(4):: a, b
```

2023-10-13 12:51 UTC, rofirrim commented on flang/lib/Parser/prescan.cpp
> +    } else {
This is just a comment and no action is required.

A hypothetical line starting with `!$fp +` would not be considered a continuation of a previous line starting with `!$fp ` line as we check for `column == 6` below.

However, given that we do not have sentinels of length 2 or 3 (only 1 or 4, and length 1 is already handled in a special way) I believe this doesn't need solving now (I don't think one could write a test for that case currently).

2023-10-13 12:55 UTC, rofirrim commented on flang/lib/Parser/prescan.cpp
> +  if (p[0] != '$') {
I think with your last update, this is addressed.

2023-10-17 04:48 UTC, Z572 commented on flang/lib/Parser/prescan.cpp
> +      break;
`dir!` and `@cuf` can't contain Spaces, so I don't think they break the any existing code. and see https://github.com/llvm/llvm-project/pull/68911#discussion_r1357342950

2023-10-20 08:20 UTC, Z572 commented
ping

2023-10-20 17:02 UTC, klausler commented on flang/lib/Parser/prescan.cpp
> +    } else {
If the loop is now going to terminate on a space, then the various `break` conditions in the loop can be combined to be less confusing.

2023-10-28 00:30 UTC, Z572 commented
ping

2023-10-30 15:12 UTC, klausler approved these changes

2023-10-30 16:20 UTC, merged