[HWASAN] Mark built-ins as not built-ins to prevent optimizations
llvm/llvm-project pull request #68936
Opened 2023-10-12 23:00 UTC by kstoimenov

The other 3 sanitizers (ASAN, TSAN and MSAN) all use maybeMarkSanitizerLibraryCallNoBuiltin to make disable optimizations which inline functions like memcmp for example. The lack of this optimization was allowing ExpandMemCmpPass to convert a memcmp call to inlined assembly and cause a false negative in HWASAN.

2023-10-12 23:44 UTC, thurstond approved these changes

2023-10-13 16:28 UTC, vitalybuka commented
Check LGTM, but if we change llvm transformation, we should also update/add llvm test cases

2023-10-13 16:28 UTC, vitalybuka requested changes
please add/update some llvm/ tests

2023-10-13 17:41 UTC, vitalybuka commented on llvm/test/Instrumentation/HWAddressSanitizer/str-nobuiltin.ll
> +; RUN: opt < %s -passes=asan -S | FileCheck %s
-passes=hwasan ?

2023-10-13 17:56 UTC, kstoimenov commented on llvm/test/Instrumentation/HWAddressSanitizer/str-nobuiltin.ll
> +; RUN: opt < %s -passes=asan -S | FileCheck %s
Done.

2023-10-13 18:20 UTC, vitalybuka approved these changes

2023-10-13 18:43 UTC, merged