[clang] Fix --entry command line option
llvm/llvm-project pull request #69114
Opened 2023-10-15 16:17 UTC by JohnyTheCarrot

New to this sort of thing, still learning how to work with the project.
Contructive feedback very welcome.

See [the corresponding issue](https://github.com/llvm/llvm-project/issues/68355) for information on the bug.

Fixes: #68355

2023-10-15 21:22 UTC, s-barannikov approved these changes
Thanks, LGTM
(Please make sure to edit the description before merging so that `git log` does not contain irrelevant information.)

2023-10-15 21:28 UTC, MaskRay requested changes
The new option (alias) can be unnamed.

2023-10-15 22:08 UTC, MaskRay commented on clang/test/Driver/entry.c
> +// RUN: %clang -### --entry test %s 2>&1 | FileCheck %s
In the absence of `--target=`, the default target triple `LLVM_DEFAULT_TARGET_TRIPLE` is used. The selected `ToolChain` may not run AddLinkerInputs to render `-e`.

We should add `--target=` (common choice is a linux triple) and try reusing an existing test https://maskray.me/blog/2021-08-08-toolchain-testing#i-dont-know-an-existing-test-can-be-enhanced

Perhaps linker-opts.c or Xlinker-args.c

2023-10-22 08:52 UTC, JohnyTheCarrot commented
Ping. Requested changes were made. Apologies if this ping is misplaced, I made it in good faith.

> (Please make sure to edit the description before merging so that git log does not contain irrelevant information.)

You mean during the merge phase, right?

2023-10-26 07:07 UTC, MaskRay commented on clang/include/clang/Driver/Options.td
> +def : Joined<["--"], "entry=">, Flags<[LinkerInput]>, Group<Link_Group>, Alias<e>;
Remove Flags and Group. They are ignored.

2023-11-14 11:12 UTC, JohnyTheCarrot commented
Ping.

2023-12-18 11:11 UTC, JohnyTheCarrot commented
Heya @MaskRay 

If and when you get the chance, would you mind giving it another look?
I applied your requested changes. :)

Thanks!

2023-12-25 04:25 UTC, MaskRay commented
Since `--entry` is wrong, `--entry=` is unsupported, and nobody seems to use the driver option which only affects linking, we probably should just remove it. Users are expected to use `-Wl,-e,entry` or `-Wl,--entry=entry` anyway.

2023-12-25 21:08 UTC, s-barannikov commented
We do use this option with gcc, this is why I filed the issue.

2026-06-06 07:12 UTC, JohnyTheCarrot commented
Hope I did that right. Apologies for the delay, I totally didn't forget. I would do no such thing.

2026-06-22 15:32 UTC, erichkeane approved these changes
This seems reasonable.

2026-06-22 17:13 UTC, s-barannikov commented on clang/test/Driver/linker-opts.c
> +// RUN: %clang -### -target x86_64-unknown-linux-gnu -etest %s 2>&1 | FileCheck --check-prefix=ENTRY %s
Re: CI failure
gcc accepts both `-etest` and `-e test`. Currently, we support only the second variant. If we want to support the first variant as well, the `def e` should be changed to `JoinedOrSeparate`. If we don't, this line should be changed to pass `-e test`.

2026-07-09 09:44 UTC, JohnyTheCarrot commented
Small update: I will be able to attend to the CI failure around but no earlier than the 16th.
I appreciate the issue appears small, but I have a critically important assessment due that day, for which I can afford no distractions. I've put it in my calendar, though. See you soon!

2026-08-08 13:40 UTC, JohnyTheCarrot commented
Local testing suggests my latest commit should fix the failed test.

2026-08-10 16:47 UTC, erichkeane approved these changes
I'm happy when CI is.

2026-08-10 17:09 UTC, MaskRay commented on clang/test/Driver/linker-opts.c
> +// RUN: %clang -### -target x86_64-unknown-linux-gnu -etest %s 2>&1 | FileCheck --check-prefix=ENTRY %s
Use `--target=`. `-target ` is deprecated. We don't need to test every supported form. Having 3 lines is too much. Two is fine. You can test `--entry test --entry=test` and check that there is only one `-e` in the output.

2026-08-24 09:42 UTC, JohnyTheCarrot commented on clang/test/Driver/linker-opts.c
> +// RUN: %clang -### -target x86_64-unknown-linux-gnu -etest %s 2>&1 | FileCheck --check-prefix=ENTRY %s
Unsure if these latest changes I made just now is what you meant, let me know if not.

2026-08-29 06:54 UTC, MaskRay approved these changes

2026-08-29 06:54 UTC, merged