Detect against invalid variant index for LibStdC++ std::variant data formatters
llvm/llvm-project pull request #69253
Opened 2023-10-16 21:26 UTC by jeffreytan81

https://github.com/llvm/llvm-project/pull/68012/files added new data formatters for LibStdC++ std::variant. 

However, this formatter can crash if std::variant's index field has invalid value (exceeds the number of template arguments). 
This can happen if the current IP stops at a place std::variant is not initialized yet. 

This patch fixes the crash by ensuring the index is a valid value.

2023-10-16 21:34 UTC, clayborg reviewed
We should add a test. Should be easy to access the "_M_index" child and set its value to something invalid and then make sure the summary is "<Invalid>".

2023-10-16 21:35 UTC, jeffreytan81 commented
> We should add a test. Should be easy to access the "_M_index" child and set its value to something invalid and then make sure the summary is "".

Sure, I can do that.

2023-10-16 23:02 UTC, clayborg requested changes

2023-10-16 23:02 UTC, clayborg commented on lldb/examples/synthetic/gnu_libstdcpp.py
>      active_type = data_obj.GetType().GetTemplateArgumentType(index)
If this is what was crashing, we should modify the GetTemplateArgumentType(<index>) to not crash with an inalid index as part of this fix.

2023-10-17 20:24 UTC, clayborg approved these changes

2023-10-18 00:26 UTC, merged

2023-10-18 04:39 UTC, rupprecht commented
This seems to cause `TestTemplatePackArgs.py` to fail, e.g. https://lab.llvm.org/buildbot/#/builders/68/builds/61819

```shell
  File "/home/worker/2.0.1/lldb-x86_64-debian/llvm-project/lldb/test/API/lang/cpp/class-template-parameter-pack/TestTemplatePackArgs.py", line 42, in test_template_argument_pack
    self.assertEqual(nested_template.GetTemplateArgumentType(2).GetName(), "bool")
AssertionError: '' != 'bool'
```

2023-10-18 10:29 UTC, DavidSpickett commented
I've reverted it as the failure reason wasn't immediately obvious to me. Looks like it will reproduce quite easily.