[clang-format]: Split alignment of declarations around assignment
llvm/llvm-project pull request #69340
Opened 2023-10-17 14:42 UTC by gedare

Function pointers are detected as a type of declaration using FunctionTypeLParen. They are aligned based on rules for AlignConsecutiveDeclarations. When a function pointer is on the right-hand side of an assignment, the alignment of the function pointer can result in excessive whitespace padding due to the ordering of alignment, as the alignment processes a line from left-to-right and first aligns the declarations before and after the assignment operator, and then aligns the assignment operator. Injection of whitespace by alignment of declarations after the equal sign followed by alignment of the equal sign results in the excessive whitespace.

Fixes #68079.

2023-10-17 20:27 UTC, HazardyKnusperkeks commented on clang/unittests/Format/FormatTest.cpp
> +  verifyFormat("using Fn   = int    (A::*)();\n"
See https://github.com/llvm/llvm-project/issues/68079#issuecomment-1767116044

2023-10-17 20:27 UTC, HazardyKnusperkeks commented on clang/lib/Format/WhitespaceManager.cpp
> +        for (FormatToken *Prev = C.Tok->Previous; Prev; Prev = Prev->Previous)
Could you extract that check and use the same function for the alignment? I'd not like the code duplication.

2023-10-18 18:58 UTC, HazardyKnusperkeks approved these changes

2023-10-27 12:47 UTC, tru commented
@gedare can you fix the merge conflict on this one?

2023-10-27 19:20 UTC, owenca commented
> @gedare can you fix the merge conflict on this one?

We don't want to merge this yet. See [here](https://github.com/llvm/llvm-project/issues/68079#issuecomment-1776826021).

2023-10-27 19:22 UTC, owenca requested changes
Please see [here](https://github.com/llvm/llvm-project/issues/68079#issuecomment-1776826021).

2023-11-09 17:00 UTC, gedare commented
force push was required to layer the revert commit correctly.

2023-11-10 03:54 UTC, owenca reviewed
See https://github.com/llvm/llvm-project/issues/66857#issuecomment-1793022188. Can you make this a suboption, e.g. `AlignFunctionPointers`? We can add another (e.g. `AlignConstructorsDestructors`) for ctors and dtors in the future.

2023-11-10 04:06 UTC, gedare commented
> See [#66857 (comment)](https://github.com/llvm/llvm-project/issues/66857#issuecomment-1793022188). Can you make this a suboption, e.g. `AlignFunctionPointers`? We can add another (e.g. `AlignConstructorsDestructors`) for ctors and dtors in the future.

Yes, I will work on this.

2023-11-17 23:58 UTC, mydeveloperday approved these changes

2024-01-05 20:32 UTC, gedare commented
@owenca this waits for re-review

2024-01-06 04:04 UTC, owenca commented
> @owenca this waits for re-review

Can you rebase the patch?

2024-01-06 06:42 UTC, gedare commented
> > @owenca this waits for re-review
> 
> Can you rebase the patch?

done

2024-01-06 10:25 UTC, owenca reviewed
Please also update the release notes. LGTM otherwise.

2024-01-06 10:25 UTC, owenca commented on clang/include/clang/Format/Format.h
> +    /// are aligned.
```suggestion
    /// Only for ``AlignConsecutiveDeclarations``. Whether function pointers are
    /// aligned.
```
Please regenerate the rst file after reflowing the comment.

2024-01-06 10:25 UTC, owenca commented on clang/lib/Format/Format.cpp
>                       /*PadOperators=*/true}));
```suggestion
                     /*AlignFunctionPointers=*/false, /*PadOperators=*/true}));
```

2024-01-06 10:25 UTC, owenca commented on clang/lib/Format/Format.cpp
>                       /*PadOperators=*/true}));
Ditto.

2024-01-06 10:25 UTC, owenca commented on clang/lib/Format/Format.cpp
>                       /*PadOperators=*/true}));
Ditto.

2024-01-06 10:25 UTC, owenca commented on clang/lib/Format/Format.cpp
>                       /*PadOperators=*/true}));
Ditto.

2024-01-06 10:25 UTC, owenca commented on clang/lib/Format/Format.cpp
>                       /*PadOperators=*/true}));
Ditto.

2024-01-06 10:25 UTC, owenca commented on clang/lib/Format/WhitespaceManager.cpp
> +          for (FormatToken *Prev = C.Tok->Previous; Prev; Prev = Prev->Previous)
```suggestion
          for (const auto *Prev = C.Tok->Previous; Prev; Prev = Prev->Previous)
```

2024-01-09 20:32 UTC, gedare commented
> Please also update the release notes. LGTM otherwise.

Fixed the comments and added a release note.

2024-01-10 04:04 UTC, owenca approved these changes

2024-01-10 04:06 UTC, owenca commented on clang/docs/ReleaseNotes.rst
> +- Add ``AlignFunctionPointers`` sub-option for ``AlignConsecutiveDeclarations''.
```suggestion
- Add ``AlignFunctionPointers`` sub-option for ``AlignConsecutiveDeclarations``.
```

2024-01-11 03:35 UTC, merged