Correct end for the CastOperation.OpRange
llvm/llvm-project pull request #69480
Opened 2023-10-18 16:18 UTC by HoBoIs

Set the correct end for the CastOperation.OpRange in CXXFunctionalCastExpr. Now it is the closing bracket's location instead of the parameter's location.

This can lead to better highlight in the diagnostics. 
Similar to https://github.com/llvm/llvm-project/pull/66853
Example:
Before:
```
warning: cast from 'long (*)(const int &)' to 'decltype(fun_ptr)' (aka 'long (*)(int &)') converts to incompatible function type 
[-Wcast-function-type-strict]
   24 | return decltype(fun_ptr)( f_ptr /*comment*/);
      |        ^~~~~~~~~~~~~~~~~~~~~~~~
```
After:
```
warning: cast from 'long (*)(const int &)' to 'decltype(fun_ptr)' (aka 'long (*)(int &)') converts to incompatible function type [-Wcast-function-type-strict]
   24 | return decltype(fun_ptr)( f_ptr /*comment*/);
      |        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

2023-10-18 16:21 UTC, tbaederr commented
The output looks good, but you should probably add a test in `clang/test/Misc/misc-source-ranges.cpp`.

2023-10-19 14:57 UTC, tbaederr commented
LGTM but let's ping @cjdb and @AaronBallman and check if they see a problem.

2023-10-19 16:53 UTC, AaronBallman approved these changes
LGTM but please add a release note about the diagnostic improvement.

2023-10-24 07:32 UTC, tbaederr approved these changes

2023-10-24 12:29 UTC, whisperity requested changes

2023-10-24 12:29 UTC, whisperity commented on clang/docs/ReleaseNotes.rst
> +  the end of the expression we convert from. Now clang underscores the until the closing bracket.
```suggestion
- When describing a warning/error in a function-style type conversion Clang underlines only until
  the end of the expression we convert from. Now, Clang underlines until the closing parenthesis.
```

2023-10-24 12:29 UTC, whisperity commented on clang/test/Misc/misc-source-ranges.cpp
> +using fun = long(*)(int&);
```suggestion
using fun = long(*)(int &);
```
Format.

2023-10-24 12:29 UTC, whisperity commented on clang/test/Misc/misc-source-ranges.cpp
> +  long (*f_ptr)(const int&);
```suggestion
  long (*f_ptr)(const int &);
```
Format.

2023-10-24 14:46 UTC, closed without merging