[RISCV][GlobalISel] Create generic instructions to handle legalization and selection of G_GLOBAL_VALUE for medlow code model
llvm/llvm-project pull request #69562
Opened 2023-10-19 05:32 UTC by nitinjohnraj

We create generic instructions G_RISCV_HI and G_RISCV_ADD_LO. We lower G_GLOBAL_VALUE to these instructions during legalization, and we use pre-existing tablegen rules to select these instructions.

2023-10-19 05:38 UTC, topperc commented on llvm/lib/Target/RISCV/GISel/RISCVInstructionSelector.cpp
> +  switch(Opc) {
Why can't this be part of the normal switch?

2023-10-19 05:38 UTC, topperc commented on llvm/lib/Target/RISCV/GISel/RISCVInstructionSelector.cpp
> +    MRI.setType(DstReg, XLenLLT);
Why do we need to call setType on a virtual register that's got a register class?

2023-10-19 05:38 UTC, topperc commented on llvm/lib/Target/RISCV/GISel/RISCVInstructionSelector.cpp
> +  errs() << "HERE\n";
???

2024-01-30 05:55 UTC, arsenm requested changes

2024-01-30 05:55 UTC, arsenm commented on llvm/test/CodeGen/RISCV/GlobalISel/regbankselect/global.mir
> +  bb.0 (%ir-block.0):
drop block name

2024-01-30 05:55 UTC, arsenm commented on llvm/lib/Target/RISCV/GISel/RISCVLegalizerInfo.cpp
> +      llvm_unreachable("Code model not handled!");
should prefer to fail legalization by returning false instead of asserting

2024-01-30 06:04 UTC, closed without merging