[AMDGPU] Generic lowering for rint and nearbyint
llvm/llvm-project pull request #69596
Opened 2023-10-19 12:23 UTC by Acim-Maravic

The are three different rounding intrinsics, that are brought down to same instruction.

2023-10-19 12:26 UTC, Acim-Maravic commented
Continuation of: https://reviews.llvm.org/D159271

2023-10-24 07:47 UTC, arsenm requested changes

2023-10-24 07:47 UTC, arsenm commented on llvm/include/llvm/CodeGen/GlobalISel/MachineIRBuilder.h
> +  buildintrinsicRoundeven(const DstOp &Dst, const SrcOp &Src0,
Capitalization is off. I'd also probably just drop the intrinsic part from the name (we should also drop it from the opcode name)

2023-11-08 08:26 UTC, arsenm approved these changes

2023-11-14 17:49 UTC, merged