[lld/ELF] Place large executable sections at the end
llvm/llvm-project pull request #70358
Opened 2023-10-26 17:37 UTC by aeubanks

So that when mixing small and large text, large text stays out of the way of the rest of the binary.

2023-10-27 00:00 UTC, MaskRay commented
The x86-64 ABI mentions `.ltext`, but there is no toolchain support or GNU ld support. I have clarified large data for the x86-64 large code model but not done anything related to `.ltext`. Things like `.lgot` and `.plt` are for theoretic exercise. Their presence in the ABI does not mean a linker needs to implement it. I intentionally do not handle `.ltext` in https://reviews.llvm.org/D150510

I believe `.ltext` is not useful, possibly forever (or 10+ years) and we should hold off adding any lld/ELF code.

This change may also break certain user expectation of the `_end` symbol (end of data).

2023-10-27 00:01 UTC, MaskRay requested changes
see main comment

2023-11-01 05:50 UTC, MaskRay commented
I'd consider that we place `.ltext` before `.lrodata`, so non-writable sections and writable sections have a clear border. With `--no-rosegment`, the large text and rodata share one single `PT_LOAD` segment.

2023-11-17 22:27 UTC, aeubanks commented
it's fine if .ltext is far away from .got, it uses a 64-bit relocation to access it

I agree that partitioned executables would be nice, but in cases where it's prohibitively expensive to change the deployment model from one main executable to multiple files, this is a nice way of getting things to link if we don't care about performance while also handling precompiled libraries. we can (and do want to) explore more efficient ways to work around the small code model limits, but this is an extremely quick and low-maintenance way to get things linking in the meantime without restructuring everything else

2023-11-17 23:29 UTC, rnk approved these changes
I think this looks good. From what I can tell you've addressed @MaskRay 's concern, but we should confirm.

2023-11-17 23:29 UTC, rnk commented on lld/ELF/Writer.cpp
>    RF_NOT_ALLOC = 1 << 26,
This ranking mechanism is a bit difficult to understand, but changing it is out of scope of this change.

2023-11-17 23:30 UTC, MaskRay commented
Even my suggestion placing `.ltext` separately (before rodata) has a potential problem that its distance with `.eh_frame` may be larger and `.eh_frame` doesn't have a complete 64-bit implementation. Some large code model users may hard code the section name to be `.ltext` (terrible idea, but such users may be present). I wish that we have complete analysis that this is necessary and `-mcmodel=medium` isn't sufficient before proceeding with the linker change.

2023-12-04 23:14 UTC, aeubanks commented
what do you mean by `Some large code model users may hard code the section name to be .ltext`?

2024-02-22 23:17 UTC, rnk commented
> I wish that we have complete analysis that this is necessary and -mcmodel=medium isn't sufficient before proceeding with the linker change.

I think our analysis of msan track origins shows that it has a 3x .text size multiplier, and many reasonable applications have ~0.67GiB of .text. Even with `-mlarge-data-treshold=0` and zero relocation pressure from any data sections, this configuration will require the large code model. Is that sufficient analysis?

Landing this `.ltext` placement logic will effectively make code compiled in the large code model ABI compatible with small code, and I think we should do it.

2024-03-19 20:04 UTC, ayermolo commented
Reading between the lines, the main motivation for this is msan builds?

Regarding the point of evicting code to dynamic libraries. Yeah it's possible, we do it, but even if it is possible it's not super scalable since each service has setup what to evict in their builds. 
For certain build modes I think it's beneficial to set thing up on high level so it just builds and removes at least this category of errors.

TBH this discussion sound very similar to https://groups.google.com/g/x86-64-abi/c/jnQdJeabxiU for data sections.

2024-04-25 22:14 UTC, MaskRay commented
I think we can give this a try. Best to mention when LLVM started to emit `.ltext` for large code model. #70358 ? 

The code and x86-64-section-layout.s has other changes, so this PR needs a rebase. We probably should add another assembly file in `x86-64-section-layout.s` for `.ltext` with very few other sections.

2025-06-02 20:17 UTC, aeubanks commented
I've rebased this, any thoughts?

2025-06-02 21:50 UTC, rnk approved these changes

2025-06-02 21:50 UTC, rnk commented on lld/ELF/Writer.cpp
> +      if (isWrite)
This can be a one-liner with a ternary conditional and it will match the else case, which is easier to read. I don't know if I would go so far as to do nested ternaries, but it seems like other simplifications are possible.

2025-06-03 03:57 UTC, MaskRay approved these changes

2025-06-03 03:57 UTC, MaskRay commented on lld/test/ELF/x86-64-section-layout.s
> +.section .ltext,"axl",@progbits
Add a comment along the line of `## Test .ltext`

2025-06-12 18:41 UTC, merged