[OpenMP][libomptarget] Fix potential atomics ordering bug
llvm/llvm-project pull request #70503
Opened 2023-10-27 20:13 UTC by jplehr

This addresses a potential ordering bug in the AMDGPU plugin that may cause an assertion error at runtime, due to the Slot signal not being updated.
Original author @carlobertolli

2023-10-27 20:16 UTC, shiltian commented
This patch looks able to fix #65811?

2023-10-27 20:18 UTC, carlobertolli commented
> This patch looks able to fix #65811?

Partially. The problem @ye-luo reported is still there but this change is necessary as a first progress towards resolution of the bug.

2023-10-27 21:55 UTC, ye-luo commented
I don't think the fence in the plugin is doing anything useful and they should be removed. hsa is responsible for manipulating the fence.

2023-11-08 08:50 UTC, arsenm commented on openmp/libomptarget/plugins-nextgen/amdgpu/src/rtl.cpp
> +    assert(Slot && "Invalid slot");
This part of the assert can stay in the function prolog

2024-02-06 13:01 UTC, arsenm requested changes
Is this still relevant?

2024-02-07 11:12 UTC, jplehr commented
Will need to reevaluate. We have seen sporadic assertion errors in the buildbot about the Slot or the Signal.

2024-02-07 15:09 UTC, ye-luo commented
> Will need to reevaluate. We have seen sporadic assertion errors in the buildbot about the Slot or the Signal.

There are known issues in HSA/driver causing this. https://github.com/ROCm/ROCm/issues/2616

2024-02-09 09:44 UTC, jplehr commented
Yes, the known issue is about the signal dependencies and their synchronization. I remember that we were seeing the assertion about the `Slot` failing on the buildbots sometimes. I'm not sure that is related to the missed synchronization.

But the assertion error on the `Slot` happened very rarely, so I would need to re-evaluate.

2024-04-23 11:13 UTC, jplehr commented
I’m going to close this PR and, should the need arise, open a new one.

2024-04-23 11:13 UTC, closed without merging