[mlir][linalg] Enable CollapseLinalgDimensions to collapse ops with C…
llvm/llvm-project pull request #70653
Opened 2023-10-30 11:48 UTC by amirBish

…anonicalized Identity maps

Supporting collapsion of linalg ops which have
canonicalized identity maps matched for their
OpOperands.

Canonnicalized Identity is an identity affine map
which include zero constants corresponded to the
values of `1` of the Operand's shape.

a common use case for this support would be the
usage of CollapseLinalgDimensions after Tosa-To-Linalg , since the later generates linalg.generic ops with canonicalized identity maps (and the rewrite pattern would fail matching, since it supports only projected permutes indexing maps).

2023-10-30 11:55 UTC, amirBish commented
Adding @aniragil @AviadCo @amrami as subscribers.

2023-10-31 06:29 UTC, MaheshRavishankar requested changes
Ill review this, but in general IMO having `0`s in indexing maps is an anti-pattern... Have you tried using `FoldUnitExtentDims` pass... it is meant to convert the numpy-style broadcasting into more canonical Linalg broadcasting.

2023-10-31 07:26 UTC, nicolasvasilache commented
> Ill review this, but in general IMO having `0`s in indexing maps is an anti-pattern... Have you tried using `FoldUnitExtentDims` pass... it is meant to convert the numpy-style broadcasting into more canonical Linalg broadcasting.

+1 this seems undesirable atm

2023-10-31 08:01 UTC, amirBish commented
@MaheshRavishankar @nicolasvasilache Thanks for the quick response, searched for such a pattern and missed this one :( , I agree usage of `FoldUnitExtentDims` would solve my problem. 
would close this MR, thanks again.

2023-10-31 08:05 UTC, closed without merging

2023-10-31 08:19 UTC, nicolasvasilache commented
@amirBish I am sorry that it was hard to find .. please do not hesitate to ping us proactively on discord or discourse to help accelerate thinking. I would also suggest you skim through the various `transform.` transform dialect operations which should give you an understanding of what exists and can help make discovery easier.

I sometimes run the following command to help me skim through existing things:
```
git grep -o -e "[[:space:]]transform[a-z_\.]*" mlir/test/ | awk {'print $2'} | sort | uniq
```

2023-10-31 08:42 UTC, amirBish commented
@nicolasvasilache Great, thanks for the tips :)