[OpenMP][libomptarget] Fixes possible no-return warning
llvm/llvm-project pull request #70808
Opened 2023-10-31 14:05 UTC by jplehr

The UNREACHABLE macro resolves to message + trap, which may still give you no-return warnings. This silences these warnings.

2023-10-31 14:26 UTC, shiltian requested changes
I'm not sure if this is the right way to fix things. I think it makes more sense to use either `llvm_unreachable` or `__builtin_unreachable` after printing the message.

2023-10-31 14:29 UTC, jplehr commented
I thought there was a particular reason for not using these utilities, e.g. not available for device code. I'll check and update patch.

2023-10-31 14:30 UTC, shiltian commented
`__builtin_unreachable` has already been used in AMD dedicated code path.

2023-11-01 10:39 UTC, jplehr commented
I was thinking about this again, and I believe that `__builtin_unreachable` is not the right thing to use here. It's not technically unreachable, is it?
It should not be reached, and this is why it prints a message and traps.

I wonder if we should instead rename/add another macro that carries that semantic.

2023-11-01 15:40 UTC, shiltian commented
Since you want to get rid of the compiler warnings, in the worst case you can do `__builtin_unreachable` followed by trap.

2023-11-06 09:10 UTC, jplehr commented
I now actually used a combination of trap and unreachable.

2023-11-06 14:46 UTC, shiltian approved these changes
LG

2023-11-06 15:45 UTC, merged