[GlobalISel] Allow some load/store instructions to be folded in Match Table backend
llvm/llvm-project pull request #70830
Opened 2023-10-31 17:00 UTC by dzhidzhoev

Load/store instruction can be folded into non-adjacent instruction
within the same basic block, if there are no other instructions with
memory/other side effects between them.

2023-11-01 02:20 UTC, arsenm requested changes
Needs tests

2023-11-01 02:27 UTC, arsenm commented on llvm/lib/CodeGen/GlobalISel/GIMatchTableExecutor.cpp
> +           MI.implicit_operands().empty();
Don't understand the implicit operands check. I think this is starting to reproduce MachineInstr::isSafeToMove

2024-01-30 05:57 UTC, arsenm commented
reverse ping?

2024-02-06 14:27 UTC, arsenm requested changes
Seems to be reinventing isSafeToMove

2025-04-12 13:10 UTC, dzhidzhoev commented
Implemented in https://github.com/llvm/llvm-project/pull/101675.

2025-04-12 13:10 UTC, closed without merging