[YAMLParser] Unfold multi-line scalar values
llvm/llvm-project pull request #70898
Opened 2023-11-01 05:54 UTC by igorkudrin

Long scalar values can be split into multiple lines to improve readability. The rules are described in Section 6.5. "Line Folding", https://yaml.org/spec/1.2.2/#65-line-folding. In addition, for flow scalar styles, the Spec states that "All leading and trailing white space characters on each line are excluded from the content", https://yaml.org/spec/1.2.2/#73-flow-scalar-styles.

The patch implements these unfolding rules for double-quoted, single-quoted, and plain scalars.

2023-11-06 22:15 UTC, slinder1 requested changes
I don't mean to make existing debt your problem, but if it isn't too much work could you post a pre-patch that just adds the `FileCheck`s to the existing tests where the behavior changes, so the test diff is more self-documenting?

I left some comments but not so much about spec compliance as I don't have the time right now to work through it right now.

Either way, thank you for the work, and I'm happy to see the parser move towards more compliant parsing!

2023-11-09 06:25 UTC, igorkudrin commented on llvm/lib/Support/YAMLParser.cpp
> +      this->setError("Unrecognized escape code", T);
Fixed. Thanks.

2023-11-09 06:27 UTC, igorkudrin commented on llvm/lib/Support/YAMLParser.cpp
> +    if (UnquotedValue[I] != '\x0D' && UnquotedValue[I] != '\x0A') {
It was an idea to be a bit closer to the spec, where all special characters are defined by their value. I changed them back to mnemonics in the last update.

2023-11-09 06:28 UTC, igorkudrin commented on llvm/lib/Support/YAMLParser.cpp
> +                 StringRef LookupChars,
Added a description for the function and its arguments.

2023-11-09 06:37 UTC, igorkudrin commented
> I don't mean to make existing debt your problem, but if it isn't too much work could you post a pre-patch that just adds the `FileCheck`s to the existing tests where the behavior changes, so the test diff is more self-documenting?

* Added #71774 for the tests
* Also added a unittest `YAMLParser.UnfoldsScalarValue` to check various combinations of line breaks and other characters. It seems like a `gtest`-based test suits better than a lit one.

2023-11-09 18:47 UTC, slinder1 approved these changes
Thank you for breaking out the NFC test changes, and for adding even more unittests!

I am again not being meticulous and exhaustive in looking for spec compliance, but in every case I did examine you were fixing a clear issue. I also ran a few cases through http://ben-kiki.org/ypaste/ and it agreed.

Thank you for the cleanup, and again thank you for taking all of my review comments on even when it required cleaning up an existing mess in the tests!

2023-11-10 00:19 UTC, merged