[RISCV] Introduce and use BF16 in Xsfvfwmaccqqq intrinsics
llvm/llvm-project pull request #71140
Opened 2023-11-03 04:34 UTC by sunshaoce

BF16 implementation based on @joshua-arch1's https://reviews.llvm.org/D152498
Fixed the incorrect f16 type introduced in https://github.com/llvm/llvm-project/pull/68296

---------

Co-authored-by: Jun Sha (Joshua) <cooper.joshua@linux.alibaba.com>

2023-11-03 05:50 UTC, 4vtomat commented
Good catch！
LGTM, leave final decision to others~

2023-11-03 06:27 UTC, topperc requested changes
I believe we need to update `Sema::checkRVVTypeSupport` too

2023-11-04 18:41 UTC, eopXD approved these changes
Sorry I did not do this before you.

The patch looks good, I would say we also need tuples of bf16 for completeness. But I will be adding a suite of intrinsics around BFloat16 (https://github.com/riscv-non-isa/rvv-intrinsic-doc/pull/293) so we can probably do that after this landed too.

I would recommend to mention that vector bfloat16 types is introduced in the title of this PR.

2023-11-04 18:42 UTC, eopXD commented
Approval is upon addressing Craig's comment.

2023-11-06 02:14 UTC, topperc commented on clang/lib/Sema/SemaChecking.cpp
> +      !TI.hasFeature("experimental-zfbfmin") &&
Does zfbfmin provide vector support?

2023-11-06 02:33 UTC, topperc commented on clang/lib/Sema/SemaChecking.cpp
> +        << Ty << "experimental-zvfbfmin";
Drop the "experimental-". That's not part of the extension name.

2023-11-06 02:42 UTC, topperc approved these changes
LGTM

2023-11-06 03:22 UTC, merged

2023-12-15 21:06 UTC, topperc commented
This patch is unfortunately incorrect because  Zvfbfmin implies Zfbfmin but the SiFive CPUs that implement Xsfvfwmaccqqq do not implement Zfbfmin.