[mlir][vector] Add support for multi-dim reduction vector distribution
llvm/llvm-project pull request #71193
Opened 2023-11-03 15:53 UTC by Groverkss

2023-11-04 18:11 UTC, antiagainst reviewed
Wonderful. Thanks for extending this @Groverkss! A few comments inlined. Additionally, can you add some explanation to the commit message?

2023-11-04 18:11 UTC, antiagainst commented on mlir/test/Dialect/Vector/vector-warp-distribute.mlir
> +//       CHECK-PROP:   gpu.shuffle
Could we use `CHECK-PROP-COUNT-*` to check the exact count?

Can we also check the second loop nest? Interested to know how we distribute it.

Another thing is that now we may eventually see subtle discrepency between how we distribute transfer read and the rest, given they are two code paths. Would be good to unify. Can happen in a next patch too.

2023-11-04 18:11 UTC, antiagainst commented on mlir/test/Dialect/Vector/vector-warp-distribute.mlir
> +//       CHECK-PROP:       vector.transfer_read {{.*}} : memref<2x32x40x384xf32>, vector<1x4xf32>
Can we check the transfer_read index? That's an important part of the distribution--how we are deseralizing the 1-D processor ID there.

2023-11-04 18:41 UTC, antiagainst commented on mlir/test/Dialect/Vector/vector-warp-distribute.mlir
> +//       CHECK-PROP:       vector.transfer_read {{.*}} : memref<2x32x40x384xf32>, vector<1x4xf32>
Acutally ignore this--we distribute transfer read in another code path.. Would be good to unify.

2023-11-08 05:47 UTC, Groverkss commented on mlir/lib/Dialect/Vector/Transforms/VectorDistribute.cpp
> +/// map(d0, d1, d2) -> (d1, d2), and a warp size of 128 would distribute first
I think there are some things here that are decisions and not contracts. The contract distribution map specifies is the order of indexing for distribution of the vector. getDistributedType takes this map, and uses the decision that we should distribute the leading dimensions of the final vector first, so as to get contigious chunks.

I think we should document the api contract in the documentation of DistributeMapFn, and we should document the decision in getDistributedType. What do you think?

2023-11-10 06:47 UTC, antiagainst requested changes

2023-11-10 06:47 UTC, antiagainst commented on mlir/lib/Dialect/Vector/Transforms/VectorDistribute.cpp
> +    indexMap.dump();
Leftover debugging prints?

2023-11-10 06:47 UTC, antiagainst commented on mlir/test/Dialect/Vector/vector-warp-distribute.mlir
> +// CHECK-PROP-COUNT=8:   gpu.shuffle
`CHECK-PROP-COUNT-8`

2023-11-10 06:47 UTC, antiagainst commented on mlir/test/Dialect/Vector/vector-warp-distribute.mlir
> +// CHECK-PROP-COUNT=8:   gpu.shuffle
`CHECK-PROP-COUNT-8`

2023-11-10 06:47 UTC, antiagainst commented on mlir/test/Dialect/Vector/vector-warp-distribute.mlir
> +// CHECK-PROP-COUNT=2:   gpu.shuffle
`CHECK-PROP-COUNT-2`

2023-11-10 06:47 UTC, antiagainst commented on mlir/lib/Dialect/Vector/Transforms/VectorDistribute.cpp
> +  WarpOpTransferWrite(MLIRContext *ctx, PatternBenefit b = 1)
This can just be `using OpRewritePattern::OpRewritePattern` now?

2023-11-10 06:47 UTC, antiagainst commented on mlir/lib/Dialect/Vector/Transforms/VectorDistribute.cpp
> +  WarpOpScfForOp(MLIRContext *ctx, PatternBenefit b = 1)
This can just be using `OpRewritePattern::OpRewritePattern` now?

2023-11-10 06:47 UTC, antiagainst commented on mlir/include/mlir/Dialect/Vector/Transforms/VectorDistribution.h
> +/// TODO: Add documentation here how the distribution is done.
We need to do this. :)

2023-12-05 23:58 UTC, kuhar commented
cc: @kuhar

2024-04-03 09:12 UTC, Groverkss commented
Closing since the current distribution approach does not extend to anything beyond 1-d dimensions. There are better approaches taken by Triton, IREE, ... which would be good to upstream at some point.

For more information:
IREE: https://www.youtube.com/watch?v=b779to--7es
Triton: https://github.com/openai/triton/blob/main/include/triton/Dialect/TritonGPU/IR/TritonGPUAttrDefs.td

2024-04-03 09:12 UTC, closed without merging