InstCombine: fix transformation of bitwiseAnd to fabs
llvm/llvm-project pull request #71257
Opened 2023-11-04 00:06 UTC by rjodinchr

Since 5c0da5839de1 instcombine transform pattern masking the MSB with a call to fabs.

While this might be correct in C, it is not in OpenCL. Math operations are allowed to flush denormalized numbers to zero in OpenCL. Thus what should be just masking the MSB starts to change much more data.

This is an issue in libclc as those implementations are using this pattern and rely on the fact that only the MSB is masked. Using fabs instead breaks conformance on platforms where fabs flushes denormalized numbers to zero.

Instead look for the complete pattern:
```
bitcast float to int
bitwiseand
bitcast int to float
=>
fabs
```

Fix #69464

2023-11-04 00:07 UTC, rjodinchr commented
@arsenm @alan-baker , Could you please review?

2023-11-04 09:07 UTC, dtcxzyw commented on llvm/lib/Transforms/InstCombine/InstCombineCasts.cpp
> +      if (match(L, m_BitCast(m_Value(Cast))) && match(R, m_MaxSignedValue())) {
```suggestion
    Value *Cast;
    if (match(Src, m_And(m_BitCast(m_Value(Cast)), m_MaxSignedValue()))) {
```

2023-11-07 05:26 UTC, arsenm requested changes
The rationale for this change is incorrect. By definition, fabs, fneg, and copysign only change the sign bit and cannot make any other value modifications. Any lowering of these operations which do flush denormals or quiet signaling nans are incorrect and should be fixed. This is universally true, OpenCL is not unique here.

2023-11-07 09:53 UTC, rjodinchr commented
Could you please provide references of this universal definition that `fabs` only changed the sign bit?

2023-11-08 09:16 UTC, nikic commented
> Could you please provide references of this universal definition that `fabs` only changed the sign bit?

Quoting from LangRef (https://llvm.org/docs/LangRef.html#llvm-fabs-intrinsic):

> This function returns the same values as the libm fabs functions would, and handles error conditions in the same way. The returned value is completely identical to the input except for the sign bit; in particular, if the input is a NaN, then the quiet/signaling bit and payload are perfectly preserved.

2023-11-08 10:41 UTC, closed without merging