[lldb] Read Checksum from DWARF line tables
llvm/llvm-project pull request #71458
Opened 2023-11-06 23:09 UTC by JDevlieghere

Read the MD5 checksum from DWARF line tables and store it in the
corresponding support files.

2023-11-06 23:09 UTC, JDevlieghere commented
Depends on #71457.

2023-11-07 00:38 UTC, bulbazord approved these changes
the dwarf line tables patch LGTM

2023-11-07 01:07 UTC, medismailben approved these changes

2023-11-07 19:17 UTC, clayborg requested changes
I would love to see if we can do this without increasing the size of FileSpec objects. Can we have the DWARF line tables store a FileSpec + checksum and do its warning without making every file object contain a checksum object that most people will never use?

2023-11-09 05:22 UTC, JDevlieghere commented on lldb/include/lldb/Utility/FileSpec.h
> +
To close the loop on this for others, Greg measured the impact of the size increase in #71457 (thank you!) and we think the size increase is acceptable in the grand scheme of things. As I mentioned in the commit message, we can always revisit this in the future.

2023-11-09 16:59 UTC, merged

2023-11-09 20:36 UTC, dyung commented
Hi @JDevlieghere, this change seems to be causing 59 test failures in the cross-project-test suite. Can you take a look?

https://lab.llvm.org/buildbot/#/builders/217/builds/30979
https://lab.llvm.org/buildbot/#/builders/243/builds/15142

2023-11-09 20:42 UTC, JDevlieghere commented
> Hi @JDevlieghere, this change seems to be causing 59 test failures in the cross-project-test suite. Can you take a look?
> 
> https://lab.llvm.org/buildbot/#/builders/217/builds/30979 https://lab.llvm.org/buildbot/#/builders/243/builds/15142

I'll revert the change, but I doubt this is the cause as this patch should just be storing a member. However there's nothing in the logs to exonerate me so let's see if the revert changes anything.

2023-11-09 20:44 UTC, JDevlieghere commented
Reverted in #71864.

2023-11-09 20:44 UTC, dyung commented
> > Hi @JDevlieghere, this change seems to be causing 59 test failures in the cross-project-test suite. Can you take a look?
> > https://lab.llvm.org/buildbot/#/builders/217/builds/30979 https://lab.llvm.org/buildbot/#/builders/243/builds/15142
> 
> I'll revert the change, but I doubt this is the cause as this patch should just be storing a member. However there's nothing in the logs to exonerate me so let's see if the revert changes anything.

I did try building the commit immediately before yours, and then yours and that is how I determined it to be caused by your commit.

2023-11-09 20:48 UTC, dyung commented
> Reverted in #71864.

Thanks, they seem to be passing now:
https://lab.llvm.org/buildbot/#/builders/243/builds/15146
https://lab.llvm.org/buildbot/#/builders/217/builds/30989

2023-11-09 20:48 UTC, JDevlieghere commented
It was also passing before with the change, so the issue isn't fully deterministic: https://lab.llvm.org/buildbot/#/builders/217/builds/30986

2023-11-09 20:49 UTC, dyung commented
> It was also passing before with the change, so the issue isn't fully deterministic: https://lab.llvm.org/buildbot/#/builders/217/builds/30986

That was me forcing the build of the commit immediately preceding yours to verify it was passing:

`reason
A build was forced by '': Build a particular revision `

2023-11-09 20:55 UTC, dyung commented
For completeness, here is where I forced a build of the commit immediately preceding yours:
https://lab.llvm.org/buildbot/#/builders/217/builds/30986
Note the git checkout step:
```
...
 using PTY: False
2984156fd34a6969c7461b228d90b72711e3797c
program finished with exit code 0
...
```
That run completed successfully.

Then I forced a run with only your changes in https://lab.llvm.org/buildbot/#/builders/217/builds/30987
git checkout output:
```
...
 using PTY: False
5da98dec7ab8c3adc3f70147ea666428431adf34
program finished with exit code 0
...
```
That run had 59 failures.

2023-11-09 20:56 UTC, JDevlieghere commented
That would've been helpful information to include in your original message and saved me the time of having to go through the logs.

2023-11-09 20:58 UTC, dyung commented
> That would've been helpful information to include in your original message and saved me the time of having to go through the logs.

Sorry about that, I'll be sure to do so next time.