[clangd][RFC] Add container field to remote index Refs grpc method
llvm/llvm-project pull request #71605
Opened 2023-11-07 23:51 UTC by tdupes

call hierarchy cannot be enhanced via the remote index because the Refs returned by the remote index do not have the ID of its container.

2023-11-08 08:07 UTC, HighCommander4 commented
This sounds like it might be the culprit behind https://github.com/clangd/clangd/issues/1358

2023-11-08 15:31 UTC, tdupes commented
Oh I wasn't aware of that issue, that is the exact bug I am aiming to fix.

2023-11-20 19:58 UTC, tdupes commented
Updated the relevant remote marshalling tests. Please let me know if there are any further testing I should do. I am using this with an unordinary remote grpc service so if there is some integration test or manual process I can test the clangd-indexer & remote server on I would be happy to do further testing

2023-12-04 15:28 UTC, kadircet requested changes
thanks a lot (and sorry for missing this, so far)

2023-12-04 15:28 UTC, kadircet commented on clang-tools-extra/clangd/index/remote/marshalling/Marshalling.cpp
> +    return ContainerID.takeError();
this shouldn't be a failure, as an old server might provide a ref response without a container, but the clients should still keep working.

2023-12-04 15:28 UTC, kadircet commented on clang-tools-extra/clangd/unittests/remote/MarshallingTests.cpp
> +  Ref.Container = llvm::cantFail(SymbolID::fromStr("0000000000000001"));
this is actually not being tested properly, can you update https://github.com/llvm/llvm-project/blob/main/clang-tools-extra/clangd/index/YAMLSerialization.cpp#L318 to serialize container to YAML ?

2023-12-07 16:25 UTC, tdupes commented
Thank  you, updated the tests & yaml. Also squashed the changes into one commit.

2024-01-02 08:51 UTC, kadircet approved these changes
thanks!

2025-04-18 19:20 UTC, HighCommander4 commented
@tdupes @kadircet it looks like this PR was approved but has not been merged -- could we merge it?

2025-04-26 16:07 UTC, tdupes commented
Yes this is good to go

2025-04-26 17:42 UTC, HighCommander4 commented
> Yes this is good to go

Could you rebase it to apply to latest trunk please? I'm happy to go ahead and merge it then.

2025-05-01 07:10 UTC, HighCommander4 commented
Thanks! I'll go ahead and merge.

2025-05-01 07:11 UTC, merged