[flang][driver] add -flang-deprecated-no-hlfir hidden option
llvm/llvm-project pull request #71820
Opened 2023-11-09 16:16 UTC by jeanPerier

Patch 1/3 of the transition to use the HLFIR step by default in lowering as described in https://discourse.llvm.org/t/rfc-enabling-the-hlfir-lowering-by-default/72778/7

This option will allow to lower code without the HLFIR step during a grace period as described in the RFC. It is not meant to be a long term switch for flang.

2023-11-09 17:25 UTC, tblah requested changes
Thanks for this!

Please could you also add testing in flang/Driver/frontend-forwarding.f90, flang/test/HLFIR/hlfir-flang.f90

2023-11-09 17:25 UTC, tblah commented on flang/lib/Frontend/CompilerInvocation.cpp
> +      !args.hasArg(clang::driver::options::OPT_emit_hlfir)) {
nit: specifying -flang-depricated-nohlfir and -flang-experimental-hlfir together should probably be an error or at least a warning

2023-11-09 18:21 UTC, jeanPerier commented
> Please could you also add testing in flang/Driver/frontend-forwarding.f90, flang/test/HLFIR/hlfir-flang.f90

Thanks for the review @tblah. I could not find flang/test/HLFIR/hlfir-flang.f90 test, did you mean flang/test/HLFIR/hlfir-**flags**.f90 (in which case it is updated in this PR already).

I added an error when -flang-deprecated-no-hlfir and -flang-experimental-hlfir are both specified and updated frontend-forwarding.f90.

2023-11-09 18:49 UTC, vzakhari approved these changes
Thank you, Jean!

2023-11-10 10:21 UTC, tblah approved these changes
> Thanks for the review @tblah. I could not find flang/test/HLFIR/hlfir-flang.f90 test, did you mean flang/test/HLFIR/hlfir-**flags**.f90 (in which case it is updated in this PR already).

Yes I meant hlfir-flags.f90. Sorry about that. Thanks for the changes!

2023-11-10 10:54 UTC, merged

2023-11-10 10:54 UTC, jeanPerier commented
> Yes I meant hlfir-flags.f90. Sorry about that. Thanks for the changes!
No problem, thanks for the review and comments!