[OpenMP][OMPIRBuilder] Handle replace uses of ConstantExpr's inside of Target regions
llvm/llvm-project pull request #71891
Opened 2023-11-10 04:09 UTC by agozillon

Currently there's an edge cases where constant indexing in target regions can lead to incorrect results as we do not correctly replace uses of mapped variables in generated target functions with the target arguments (and accessor instructions) that replace them. This patch seeks to fix that by extending the current logic in the OMPIRBuilder.

Things like GEP's can come in the form of Constants/ConstantExprs, Constants and ConstantExpr's do not have access to the knowledge of what they're contained in, so we must dig a little to find an instruction so we can tell if they're used inside of the function we're outlining so we can be sure they are replaceable and we are not accidentally replacing a usage somewhere else in the module that's still necessary.

This patch handles these by replacing the original constant expression with a new instruction equivalent; an instruction as it allows easy modification in the following loop, as we can now know the constant (instruction) is owned by our target function (as it holds this knowledge) and replaceUsesOfWith can now be invoked on it (cannot do this with constants it seems), a brand new one also allows us to be cautious as it is perhaps possible the old expression was used inside of the function but exists and is used externally (unlikely by the nature of a Constant, but still a positive side affect).

2023-11-10 12:47 UTC, skatrak approved these changes
Thanks Andrew! LGTM, just a couple nits. I'd wait for a second reviewer before merging.

2023-11-10 12:47 UTC, skatrak commented on llvm/lib/Frontend/OpenMP/OMPIRBuilder.cpp
> +    // equivelant; an instruction as it allows easy modification in the
```suggestion
    // equivalent; an instruction as it allows easy modification in the
```

2023-11-10 12:47 UTC, skatrak commented on llvm/lib/Frontend/OpenMP/OMPIRBuilder.cpp
> +    // Things like GEP's can come in the form of Constants, constants and
I think it reads a little better this way, but maybe it's not what you're trying to say. Please ignore this suggestion if you don't agree with it.
```suggestion
    // Things like GEP's can come in the form of Constants. Constants and
```

2023-11-10 12:47 UTC, skatrak commented on llvm/lib/Frontend/OpenMP/OMPIRBuilder.cpp
> +    // (cannot do this with constants it seems), a brand new one also allows us
Same as before. I think it improves readability, but feel free to ignore.
```suggestion
    // (cannot do this with constants it seems). A brand new one also allows us
```

2023-11-10 12:47 UTC, skatrak commented on llvm/lib/Frontend/OpenMP/OMPIRBuilder.cpp
> +    // nature of a Constant, but still)
```suggestion
    // nature of a Constant, but still).
```

2023-11-10 12:47 UTC, skatrak commented on llvm/lib/Frontend/OpenMP/OMPIRBuilder.cpp
> +      if (auto *Const = dyn_cast<Constant>(User))
Is there any reason why `User` can't be checked here for the `ConstantExpr` type directly and remove the check at the top of the `ReplaceConstantUsedInFunction` lambda?

2023-11-10 15:57 UTC, agozillon commented
Thank you for the review Sergio! I've updated the PR with your feedback. I'll await one more reviewer as you suggest.

2023-11-14 17:12 UTC, jsjodin requested changes

2023-11-14 17:12 UTC, jsjodin commented on llvm/lib/Frontend/OpenMP/OMPIRBuilder.cpp
> +    auto ReplaceConstantUsedInFunction = [](ConstantExpr *ConstExpr,
No need to use lambda, we're not passing this around.

2023-11-15 14:32 UTC, jsjodin approved these changes
LGTM

2023-11-15 14:45 UTC, merged