[clangd] Let DefineOutline tweak create a definition from scratch
llvm/llvm-project pull request #71950
Opened 2023-11-10 15:43 UTC by ckandeler

2023-11-13 09:53 UTC, ckandeler commented
> This implements [clangd/clangd#445](https://github.com/clangd/clangd/issues/445)

Aha, so this implementation does not work, because it relies on the AST only for figuring out whether an implementation exists. And querying the index is considered too expensive during the prepare() step. That's a pity then.

2023-11-13 12:11 UTC, ckandeler commented
The new patch set properly considers "external" definitions (using the frowned-upon index lookup).

2024-04-18 08:40 UTC, tom-anders commented
> The new patch set properly considers "external" definitions (using the frowned-upon index lookup).

I've been using this patch for a few weeks now, and it works very well. Haven't encountered any issues/crashes yet. Performance also seems reasonable (working in a medium-sized project)

2024-04-18 17:15 UTC, ckandeler commented
We should probably rekindle the discussion on the associated bug report; I think users (rightly) expect this feature.

2024-04-18 19:01 UTC, tom-anders commented
> We should probably rekindle the discussion on the associated bug report; I think users (rightly) expect this feature.

Agreed, [maybe a protocol extension would also be an option](https://github.com/clangd/clangd/issues/445#issuecomment-1250355799)

2026-05-15 15:42 UTC, timon-ul requested changes
Hello there, I hope you haven't died of old age waiting for a review. Overall this looks already pretty good and I am almost ready to merge, as you can see there are some nitpicks I would like to have cleaned up before. 

One consideration you could have is, when using this feature on a defaulted function, the `default` is moved into the cpp, but maybe we instead want to create a function body (with potentially a generated assert to make sure the user does not forget to actually implement it). At least I do not see any reason as to why someone would do this on e.g. a constructor and then keep the constructor as default. Iirc we already do something similar with virtual functions when generating them. I would prefer this feature as part of this PR, but I am open to being convinced against it (or as a follow up).

One more thing I thought about during the review: we could technically move the index lookup into the `apply` stage instead if we notice that getting this code action is too slow, I personally could not notice any delay before the code action appears so I am fine with it happening in the `prepare` stage, just noting down the option **if** someone happens to have a problem with it. Notably though this would lead to it appearing in a lot of cases where it makes no sense. So if speed is not a problem I do prefer the current behaviour.

Lastly some things I noticed during testing this patch are bugs with the general `out-of-line` feature, that are not to be addressed in this PR and just me noting them down (and probably creating bug reports later). First off, when the function is declared above all functions that appear in the cpp file it gets generated above the header includes, really awkward. The other is that some reformatting is happening sometimes, for example `void test(){}void test2();` and  then moving the first one to the cpp it eats up the `void`token of `test2`, which of course breaks things. Also `test2` gets moved to a new line, but I think this behaviour is acceptable (even if not expected).

2026-05-15 15:42 UTC, timon-ul commented on clang-tools-extra/clangd/refactor/tweaks/DefineOutline.cpp
> +    auto tokens = TokBuf.expandedTokens(FD->getSourceRange());
nit: please capitalize `Tokens`

2026-05-15 15:42 UTC, timon-ul commented on clang-tools-extra/clangd/refactor/tweaks/DefineOutline.cpp
> +        const auto nextIt = std::next(It);
nit: please capitalize `NextIt`

2026-05-15 18:09 UTC, tom-anders commented
> Hello there, I hope you haven't died of old age waiting for a review. Overall this looks already pretty good and I am almost ready to merge, as you can see there are some nitpicks I would like to have cleaned up before.
> 
> One consideration you could have is, when using this feature on a defaulted function, the `default` is moved into the cpp, but maybe we instead want to create a function body (with potentially a generated assert to make sure the user does not forget to actually implement it). At least I do not see any reason as to why someone would do this on e.g. a constructor and then keep the constructor as default. Iirc we already do something similar with virtual functions when generating them. I would prefer this feature as part of this PR, but I am open to being convinced against it (or as a follow up).
> 
> One more thing I thought about during the review: we could technically move the index lookup into the `apply` stage instead if we notice that getting this code action is too slow, I personally could not notice any delay before the code action appears so I am fine with it happening in the `prepare` stage, just noting down the option **if** someone happens to have a problem with it. Notably though this would lead to it appearing in a lot of cases where it makes no sense. So if speed is not a problem I do prefer the current behaviour.
> 
> Lastly some things I noticed during testing this patch are bugs with the general `out-of-line` feature, that are not to be addressed in this PR and just me noting them down (and probably creating bug reports later). First off, when the function is declared above all functions that appear in the cpp file it gets generated above the header includes, really awkward. The other is that some reformatting is happening sometimes, for example `void test(){}void test2();` and then moving the first one to the cpp it eats up the `void`token of `test2`, which of course breaks things. Also `test2` gets moved to a new line, but I think this behaviour is acceptable (even if not expected).

When a class C has a `unique_ptr<T>` field and you forward declare T, then you need to move C::~C()=default to the cpp, heaving it in the header would cause linker issues. So that's a use case where you want to keep the default keyword I think.

2026-05-15 19:55 UTC, timon-ul commented
> When a class C has a unique_ptr<T> field and you forward declare T, then you need to move C::~C()=default to the cpp, heaving it in the header would cause linker issues. So that's a use case where you want to keep the default keyword I think.

I see, thank you so much, I wasn't aware of this. Then I would drop that requirement for this PR. What I just remembered though which should be added in this PR is a comment in the release notes `clang-tools-extra/docs/ReleaseNotes.rst`  in the `Code Actions`section describing the new feature.

2026-05-18 11:16 UTC, ckandeler commented on clang-tools-extra/clangd/refactor/tweaks/DefineOutline.cpp
> +    auto tokens = TokBuf.expandedTokens(FD->getSourceRange());
Done.

2026-05-18 11:16 UTC, ckandeler commented on clang-tools-extra/clangd/refactor/tweaks/DefineOutline.cpp
> +        const auto nextIt = std::next(It);
Done.

2026-05-18 11:20 UTC, ckandeler commented
> One more thing I thought about during the review: we could technically move the index lookup into the `apply` stage instead if we notice that getting this code action is too slow, I personally could not notice any delay before the code action appears so I am fine with it happening in the `prepare` stage, just noting down the option **if** someone happens to have a problem with it. Notably though this would lead to it appearing in a lot of cases where it makes no sense. So if speed is not a problem I do prefer the current behaviour.

Delaying the index look-up would mean that the code action would show up for pretty much every function declaration with an out-of-line definition, which I think is unacceptable.

> 
> Lastly some things I noticed during testing this patch are bugs with the general `out-of-line` feature, that are not to be addressed in this PR and just me noting them down (and probably creating bug reports later). First off, when the function is declared above all functions that appear in the cpp file it gets generated above the header includes, really awkward. The other is that some reformatting is happening sometimes, for example `void test(){}void test2();` and then moving the first one to the cpp it eats up the `void`token of `test2`, which of course breaks things. Also `test2` gets moved to a new line, but I think this behaviour is acceptable (even if not expected).

There are some known (though not reported) issues, some of them stemming from the lack of whitespace insertion. These should be tackled one by one in extra patches.

2026-05-18 11:37 UTC, timon-ul commented
> Delaying the index look-up would mean that the code action would show up for pretty much every function declaration with an out-of-line definition, which I think is unacceptable.

I was not sure if this is unacceptable for people, but I do agree that it is undesireable.

> These should be tackled one by one in extra patches.

Absolutely, I will file the bug reports as soon as this PR is merged.

Also @ckandeler just to make sure, please do not forget to add a comment in the [release notes, ](https://searchfox.org/llvm/source/clang-tools-extra/docs/ReleaseNotes.rst#164) as part of this PR, people should be informed about this helpful feature :)

2026-05-18 11:46 UTC, ckandeler commented
> Also @ckandeler just to make sure, please do not forget to add a comment in the [release notes, ](https://searchfox.org/llvm/source/clang-tools-extra/docs/ReleaseNotes.rst#164) as part of this PR, people should be informed about this helpful feature :)

Right. Done.

2026-05-18 12:33 UTC, timon-ul approved these changes
LGTM

2026-05-18 12:48 UTC, timon-ul commented
Just fyi, I am ready to merge this, the failures in the builds seem unrelated, but I will first ask about proper procedure for these cases, should not take 3 years tho :)

2026-05-18 13:15 UTC, ckandeler commented
> Just fyi, I am ready to merge this, the failures in the builds seem unrelated, but I will first ask about proper procedure for these cases, should not take 3 years tho :)

Given that there was opposition to the general idea by maintainers, it seems appropriate to wait a couple of days before merging, in order to give them time to comment.

2026-05-18 13:35 UTC, timon-ul commented
> Given that there was opposition to the general idea by maintainers, it seems appropriate to wait a couple of days before merging, in order to give them time to comment.

Well this would mean waiting forever, since they are not maintainers anymore. That being said now that I read it again it is indeed a valid concern they raised about each code action individually queuing the index. Instead I would like to have a way of code actions sharing index results so if any other one needs the same information it can get it easily (since the lookup is required). For this I would need to spend a bit of time to properly understand how this could be realised to see what seems feasable. A first thought would be a wrapper around the current index with a cache that is newly created when the code actions are requested, but not sure if there is maybe a simpler way of doing this. 

The other concern is about it breaking code because it creates a definition if there already exists one due to the index being stale. This one I am not sure if the concern really applies, to run into this you would 
 - be unaware of a definition
 - have a stale index without said definition

so somehow you created a definition that ends up being not in the index and then use the code action and somehow NOT run into any compiler errors, seems unrealistic to me? Or at least so rare I would be surprised if this is strong enough to block this feature.

Edit: that being said I wonder if there even is any other code action that queuries the index, given how long this issue has been open I would expect not, but again I would need to check. Reason I am wondering about this is that creating infrastructure for something that does not exist might not be neccessary. Yes this does not scale but what if there never is a need for it to scale (I doubt it, but we could just cross that bridge once we get there). So maybe it is fine to delay the decision to the 2nd code action that will need an Index lookup. That being said it would probably make sense to leave a comment about this where the lookup happens currently.

2026-05-18 14:56 UTC, timon-ul commented on clang-tools-extra/clangd/refactor/tweaks/DefineOutline.cpp
> +#include "XRefs.h"
Actually what is this include required for? Or is this a fragment from when this was using an AST lookup?

2026-05-19 12:57 UTC, ckandeler commented
> Edit: that being said I wonder if there even is any other code action that queuries the index, given how long this issue has been open I would expect not, but again I would need to check. Reason I am wondering about this is that creating infrastructure for something that does not exist might not be neccessary. Yes this does not scale but what if there never is a need for it to scale (I doubt it, but we could just cross that bridge once we get there). So maybe it is fine to delay the decision to the 2nd code action that will need an Index lookup. 

That was my reasoning in the discussion as well.

> That being said it would probably make sense to leave a comment about this where the lookup happens currently.

Done.

2026-05-19 14:05 UTC, timon-ul requested changes
@ckandeler so I have spent some time thinking about this and I think the only thing I would add now is a simple check for `Source->getDefinition()` to see if we have the information in the current AST and if we do there is no point in asking the index. Of course I suspect this to rarely yield a positive result, but it is so cheap we might aswell do it. With this I would be fine to merge it.

2026-05-19 18:14 UTC, timon-ul approved these changes
LGTM (again)

2026-05-19 18:16 UTC, merged

2026-05-19 18:17 UTC, timon-ul commented
Thanks for the work here @ckandeler , small (personal) thing for the future, the commits get merged into 1 singular commit anyway so preferably you leave the commit history, makes reviewing incrementally easier and I do not need to check the whole code every time :)

2026-05-19 20:30 UTC, HighCommander4 commented
> small (personal) thing for the future, the commits get merged into 1 singular commit anyway so preferably you leave the commit history, makes reviewing incrementally easier and I do not need to check the whole code every time :)

Note that you can click on the "Compare" links in the conversation view to see what has changed between versions of a patch when it's force-pushed.

As a reviewer, I'm fine with patch authors either amending and force-pushing (in which case I use the "Compare" links), or pushing fixup commits (in which case I use the interdiff in the "Files changed" view).

The only thing that's problematic is if someone rebases _and_ makes changes to a patch between force-pushes, because in that case the "Compare" link is useless. This can be avoided by force-pushing just the rebase separately.

2026-05-20 08:59 UTC, ckandeler commented
I don't use github in my daily work, so I'm probably unaware of all the best practices (and if I learned them, I'd have forgotten them just in time for my next patch). Please bear with me.