[lld] lld/ELF/Writer.cpp: write directly to outs when output is "-"
llvm/llvm-project pull request #72061
Opened 2023-11-12 18:51 UTC by keithw

This PR lets the LLD ELF driver write directly to outs (skipping the filesystem) when the output filename is "-".
This is a step towards being able to use LLD as a library without using an `open` syscall.

2023-11-16 03:41 UTC, keithw commented
@smithp35 @MaskRay

2023-11-16 04:50 UTC, MaskRay requested changes
`ld.lld a.o -o -` already writes to stdout. See https://reviews.llvm.org/D56940

2023-11-16 07:21 UTC, keithw commented
Yes, unfortunately that writes to llvm::outs(), i.e. the `STDOUT_FILENO` file descriptor.

This PR makes it write to `lld::outs()`, the `stdoutOS` argument to `lld::elf::link()`. We're using this (and hopefully others might benefit) so we can use the LLD ELF driver as a library where the object gets written to an in-memory `raw_string_ostream`.

2023-11-17 07:49 UTC, MaskRay commented
Ah, thanks for the explanation. The description can mention `raw_ostream`:

> This lets the LLD ELF driver be used as a library with its output written to a `raw_ostream`.

`message` calls write to `stdoutOS`, so you'll need to set `disableOutput` if you use any feature that calls `message`.

I think this is still fine but we need a unittest in `lld/unittest/` (`ninja check-lld-unit`)

2026-07-12 23:33 UTC, MaskRay commented
> Ah, thanks for the explanation. The description can mention `raw_ostream`:
> 
> > This lets the LLD ELF driver be used as a library with its output written to a `raw_ostream`.
> 
> `message` calls write to `stdoutOS`, so you'll need to set `disableOutput` if you use any feature that calls `message`.
> 
> I think this is still fine but we need a unittest in `lld/unittest/` (`ninja check-lld-unit`)

Adding the feature in https://github.com/llvm/llvm-project/pull/209064  with a unit test.

2026-07-12 23:33 UTC, closed without merging