[libc++] Use __datasizeof for __libcpp_datasizeof if available
llvm/llvm-project pull request #72104
Opened 2023-11-13 11:30 UTC by philnik777

This avoids the UB and makes things a bit cheaper in terms of compile-times.

2023-11-16 18:22 UTC, mordante requested changes
I see the changes in Clang have landed a few days ago. Can you update the CI image and then re-run the CI for this patch. Then we're sure the branch of
`#if __has_extension(datasizeof)` is taken and passes the CI.

2023-12-21 17:04 UTC, ldionne approved these changes
This LGTM once you re-upload against `main`, which will cause the CI to execute again against the GH Actions jobs. Like we checked just now, those seem to be running Clang from `main` at commit 3494c555c93c, which should contain the `__datasizeof` extension.

2023-12-21 17:05 UTC, ldionne commented
You probably want to give a bit of time for @mordante to see this, but otherwise I think this is pretty uncontroversial once it runs on the right CI.

2023-12-22 19:14 UTC, mordante commented
> This LGTM once you re-upload against `main`, which will cause the CI to execute again against the GH Actions jobs. Like we checked just now, those seem to be running Clang from `main` at commit [3494c55](https://github.com/llvm/llvm-project/commit/3494c555c93c5f5cf5c36a84a819b80a4d922a82), which should contain the `__datasizeof` extension.

This resolves my concern. I wanted to be sure the code worked properly with Clang having that feature available.

2023-12-22 19:14 UTC, mordante approved these changes

2023-12-24 07:45 UTC, merged