[mlir] Add narrow type emulation conversions
llvm/llvm-project pull request #72181
Opened 2023-11-14 00:49 UTC by Max191

Adds narrow type emulation support for:
    - `memref.alloca`
    - `memref.store`
    - `memref.reinterpret_cast`

2023-11-15 22:42 UTC, MaheshRavishankar commented
Could we split the `store` part out cause that is a bit more involved

2023-11-15 22:54 UTC, hanhanW requested changes
Can we split it to three PRs?

- memref.store
- memref.reinterpret_cast
- memref.alloca

2023-11-15 22:54 UTC, hanhanW commented on mlir/lib/Dialect/MemRef/Transforms/EmulateNarrowType.cpp
> +struct ConvertMemRefAlloc final : OpConversionPattern<OpTy> {
Perhaps we can rename it to `ConvertMemRefAllocation`. It is not only used by memref.alloc, but also memref.alloca.

2023-11-15 22:54 UTC, hanhanW commented on mlir/lib/Dialect/MemRef/Transforms/EmulateNarrowType.cpp
> +/// conversion. Only the 0 dimensional case is supported.
Why only 0D is supported? Are we able to emulate other cases?

2023-11-15 22:54 UTC, hanhanW commented on mlir/lib/Dialect/MemRef/Transforms/EmulateNarrowType.cpp
> +          .getResult();
IIRC, `.getResult()` is not needed when `Value` type is specified. same for below other codes.

2023-11-15 22:54 UTC, hanhanW commented on mlir/lib/Dialect/MemRef/Transforms/EmulateNarrowType.cpp
> +      rewriter.eraseOp(op);
Can we use `replaceOp` instead? That's more common in pattern-rewrite.

2023-11-15 22:54 UTC, hanhanW commented on mlir/lib/Dialect/MemRef/Transforms/EmulateNarrowType.cpp
> +    if (convertedType.getRank() == 0) {
The code is becoming larger than I expect.. Let's create two static functions. One for 0D case, and the other for non-0D case. What do you think?

2023-11-15 23:28 UTC, MaheshRavishankar requested changes

2023-11-22 21:47 UTC, Max191 commented
This PR has been split into:
https://github.com/llvm/llvm-project/pull/73144
https://github.com/llvm/llvm-project/pull/73174
https://github.com/llvm/llvm-project/pull/73138

2023-11-22 21:47 UTC, closed without merging