[llvm][DebugInfo] DWARFv5: static data members declarations are DW_TAG_variable
llvm/llvm-project pull request #72234
Opened 2023-11-14 09:58 UTC by Michael137

This patch adds the LLVM-side infrastructure to implement DWARFv5 issue 161118.1: "DW_TAG for C++ static data members".

The clang-side of this patch will simply construct the DIDerivedType with a different DW_TAG.

2023-11-14 23:53 UTC, adrian-prantl approved these changes

2023-11-14 23:53 UTC, adrian-prantl commented on llvm/lib/IR/DebugInfo.cpp
> +    unsigned Tag, uint32_t AlignInBits) {
Somebody might complain if we change the C API, but I don't think we guarantee compatibility.

2023-11-14 23:54 UTC, adrian-prantl requested changes
I think this is missing a test in clang/test/CodeGenCXX that verifies Clang generates the expected LLVM IR.

2023-11-14 23:55 UTC, adrian-prantl commented on clang/lib/CodeGen/CGDebugInfo.cpp
> +      llvm::dwarf::DW_TAG_member, Align);
Assuming this _changes_ the IR.

2023-11-14 23:57 UTC, Michael137 commented
> I think this is missing a test in clang/test/CodeGenCXX that verifies Clang generates the expected LLVM IR.

I added those tests here: https://github.com/llvm/llvm-project/pull/72235

The IR doesn't change with this patch. It merely adds the necessary parameter to the DIBuilder API to be used from clang in the subsequent patch

2023-11-14 23:59 UTC, adrian-prantl approved these changes
LGTM, then

2023-11-15 08:16 UTC, merged

2023-11-15 08:39 UTC, Michael137 commented
Looks like the OCaml bindings are using the C-API that was changed in this PR. Will make a follow-up fix for those

2023-11-15 14:13 UTC, pogo59 reviewed
@adrian-prantl We do have a pretty strong guarantee of compatibility in the llvm-c API. A new parameter pretty much means you need to define a new function.

2023-11-15 18:42 UTC, aeubanks commented
we're seeing debug info verifier issues in Rust with this change, e.g.
```
 invalid tag
 !50 = !DIDerivedType(tag: DW_TAG_imported_declaration, name: "DISCR_EXACT", scope: !37, file: !2, baseType: !51, flags: DIFlagStaticMember, extraData: i64 0)
 invalid tag
 !61 = !DIDerivedType(tag: DW_TAG_imported_declaration, name: "DISCR_EXACT", scope: !54, file: !2, baseType: !51, flags: DIFlagStaticMember, extraData: i64 1)
 invalid tag
 !86 = !DIDerivedType(tag: DW_TAG_shared_type, name: "DISCR_EXACT", scope: !79, file: !2, baseType: !87, flags: DIFlagStaticMember, extraData: i64 0)
 invalid tag
 !97 = !DIDerivedType(tag: DW_TAG_shared_type, name: "DISCR_EXACT", scope: !90, file: !2, baseType: !87, flags: DIFlagStaticMember, extraData: i64 1)
```

is this expected?

(https://logs.chromium.org/logs/chromium/buildbucket/cr-buildbucket/8764364541415601649/+/u/package_rust/stdout?format=raw)

2023-11-15 18:59 UTC, Michael137 commented
> we're seeing debug info verifier issues in Rust with this change, e.g.
> 
> ```
> 
>  invalid tag
> 
>  !50 = !DIDerivedType(tag: DW_TAG_imported_declaration, name: "DISCR_EXACT", scope: !37, file: !2, baseType: !51, flags: DIFlagStaticMember, extraData: i64 0)
> 
>  invalid tag
> 
>  !61 = !DIDerivedType(tag: DW_TAG_imported_declaration, name: "DISCR_EXACT", scope: !54, file: !2, baseType: !51, flags: DIFlagStaticMember, extraData: i64 1)
> 
>  invalid tag
> 
>  !86 = !DIDerivedType(tag: DW_TAG_shared_type, name: "DISCR_EXACT", scope: !79, file: !2, baseType: !87, flags: DIFlagStaticMember, extraData: i64 0)
> 
>  invalid tag
> 
>  !97 = !DIDerivedType(tag: DW_TAG_shared_type, name: "DISCR_EXACT", scope: !90, file: !2, baseType: !87, flags: DIFlagStaticMember, extraData: i64 1)
> 
> ```
> 
> 
> 
> is this expected?
> 
> 
> 
> (https://logs.chromium.org/logs/chromium/buildbucket/cr-buildbucket/8764364541415601649/+/u/package_rust/stdout?format=raw)
> 
> 

Hmmm yea that's problematic. Feel free to revert since I'm currently not at my PC. It looks like the Tag parameter wouldve been better off strongly typed since I suspect there are some callers that I missed that now pass alignment to where now the tag is.

2023-11-15 19:02 UTC, aeubanks commented
ah I see, that definitely sounds plausible

I've also recently done some NFC changes to better catch issues like this in https://github.com/llvm/llvm-project/pull/66295

2023-11-15 19:04 UTC, aeubanks commented
actually I think the caller is in Rust, so perhaps we should just update Rust instead. but making some of these params more strongly typed would be good

2023-11-15 19:04 UTC, Michael137 commented
Is it possible that this is to be fixed at the callsites in the rust frontend? Dont think i missed any callers in LLVM (then again I'm not at a PC to confirm this atm)