[libc++] Optimize char_traits a bit
llvm/llvm-project pull request #72799
Opened 2023-11-19 16:58 UTC by philnik777

This implements two kinds of optimizations. Specifically
- `char_traits<char8_t>` uses `char` code paths; these are heavily
  optimized and the operations are equivalent
- `char16_t` and `char32_t` `find` uses `std::find` to forward to
  `wmemchr` if they have the same size

2023-11-20 18:25 UTC, ldionne requested changes

2023-11-20 18:25 UTC, ldionne commented on libcxx/include/__string/constexpr_c_functions.h
> +template <class _Tp>
I really don't like that we're accepting arbitrary integral types in `__constexpr_strlen`. IMO it doesn't make sense to use `strlen` on e.g. `int8_t` -- it only makes sense for character types. Instead, I'd be much happier if you checked explicitly for `char` and `char8_t`.

2023-11-21 01:24 UTC, EricWF commented
Could you please provide information about:

(A) Benchmark results for these functions.
(B) The changes to compile times and compiler memory usage.

2023-11-21 01:25 UTC, EricWF requested changes
As mentioned, I would like to see some data on the improvements.

2024-03-25 08:26 UTC, philnik777 commented
> Could you please provide information about:
> 
> (A) Benchmark results for these functions.

These are the numbers from optimizing `std::find`:
```
---------------------------------------------------------------
Benchmark                                   old             new
---------------------------------------------------------------
bm_find<char>/1                         10.5 ns         10.5 ns
bm_find<char>/2                         18.3 ns         10.4 ns
bm_find<char>/3                         21.1 ns         10.4 ns
bm_find<char>/4                         22.4 ns         10.3 ns
bm_find<char>/5                         23.3 ns         10.3 ns
bm_find<char>/6                         23.7 ns         10.4 ns
bm_find<char>/7                         24.0 ns         10.3 ns
bm_find<char>/8                         24.5 ns         10.2 ns
bm_find<char>/16                        26.2 ns         10.2 ns
bm_find<char>/64                        29.9 ns         20.8 ns
bm_find<char>/512                       80.2 ns         36.0 ns
bm_find<char>/4096                       523 ns         43.0 ns
bm_find<char>/32768                     3838 ns          105 ns
bm_find<char>/262144                   30832 ns          988 ns
bm_find<char>/1048576                 122541 ns         4854 ns
bm_find<int>/1                          10.4 ns         12.1 ns
bm_find<int>/2                          18.4 ns         12.0 ns
bm_find<int>/3                          21.9 ns         12.0 ns
bm_find<int>/4                          23.3 ns         11.9 ns
bm_find<int>/5                          24.2 ns         12.1 ns
bm_find<int>/6                          24.7 ns         12.0 ns
bm_find<int>/7                          24.8 ns         11.9 ns
bm_find<int>/8                          25.2 ns         11.9 ns
bm_find<int>/16                         26.2 ns         21.9 ns
bm_find<int>/64                         30.5 ns         33.8 ns
bm_find<int>/512                        80.4 ns         40.4 ns
bm_find<int>/4096                        497 ns         71.7 ns
bm_find<int>/32768                      3844 ns          498 ns
bm_find<int>/262144                    30722 ns         4901 ns
bm_find<int>/1048576                  123303 ns        22864 ns
```

Since it's basically the same optimization I think these are pretty representative of the expected speedup. The numbers for `length` would also be similar, since `strlen` is basically `memchr(str, '\0', <buffer_len>)`, just with possible out-of-bounds reads.

> (B) The changes to compile times and compiler memory usage.

I don't know how to measure memory usage properly, but the time of including `<string>` is within margin of error. I've checked with `-std=c++23`, which eagerly instantiates all the functions.

2024-04-05 16:43 UTC, ldionne approved these changes
LGTM assuming we already have appropriate coverage in char_traits for `char8_t` and friends.

2024-04-05 16:43 UTC, ldionne commented on libcxx/include/__string/char_traits.h
> +    const char_type* __match = std::__find_impl(__s, __s + __n, __a, __proj);
Unrelated to this patch, but can we rename `__find_impl` to `__find` for consistency?

2024-04-11 15:56 UTC, philnik777 commented
ping @EricWF

2024-04-20 09:40 UTC, philnik777 commented
Landing, since I addressed all the feedback. @EricWF if you have any more thoughts feel free to comment.

2024-04-20 09:40 UTC, merged