[mlir] Add narrow type emulation for `memref.reinterpret_cast`
llvm/llvm-project pull request #73144
Opened 2023-11-22 17:13 UTC by Max191

2023-11-22 17:55 UTC, MaheshRavishankar requested changes
Probably need a lit test for the `reinterpret_cast` support.

2023-11-22 18:17 UTC, Max191 commented
> Probably need a lit test for the `reinterpret_cast` support.

Oh, I didn't realize somehow the test got lost in this branch. I'll add it back

2023-11-22 20:42 UTC, MaheshRavishankar approved these changes

2023-11-27 18:40 UTC, hanhanW approved these changes

2023-11-27 18:41 UTC, merged