[libunwind][WebAssembly] Don't build libunwind.cpp
llvm/llvm-project pull request #73196
Opened 2023-11-23 02:22 UTC by aheejin

Wasm doesn't use that file; Wasm does not allow access of system registers and those functionalities are provided from the VM. Wasm only uses
https://github.com/llvm/llvm-project/blob/main/libunwind/src/Unwind-wasm.c, which implements a few interface functions.

2023-11-23 14:34 UTC, ldionne approved these changes

2023-11-27 20:52 UTC, arichardson requested changes
The commit message is slightly misleading, it appears there are some parts of the file that are actually used?

2023-11-27 20:53 UTC, arichardson commented
> The commit message is slightly misleading, it appears there are some parts of the file that are actually used?

Other than this, the change looks good to me.

2023-11-28 00:39 UTC, aheejin commented
> The commit message is slightly misleading, it appears there are some parts of the file that are actually used?

As the commit message says, we only use https://github.com/llvm/llvm-project/blob/main/libunwind/src/Unwind-wasm.c and not libunwind.cpp. We don't use any parts of libunwind.cpp. Do you have any suggestions on how to improve the message to make it clearer?

2023-11-28 15:10 UTC, arichardson commented
> > The commit message is slightly misleading, it appears there are some parts of the file that are actually used?
> 
> As the commit message says, we only use https://github.com/llvm/llvm-project/blob/main/libunwind/src/Unwind-wasm.c and not libunwind.cpp. We don't use any parts of libunwind.cpp. Do you have any suggestions on how to improve the message to make it clearer?

Looking at the file, there is some code that will still be compiled for wasm (at least for debug builds). If those functions are also not used for wasm they should be ifdef'd out as well?

Commit message could be something like `Omit unused parts of libunwind.cpp for WASM`.

2023-11-28 19:19 UTC, aheejin commented
Hmm, yes, I thought we didn't build `libunwind.cpp` because the code next to the part I excluded was wrapped with `#ifdef __APPLE__`:
https://github.com/llvm/llvm-project/blob/a8ac930b99d93b2a539ada7e566993d148899144/libunwind/src/libunwind.cpp#L352-L432

But yeah then we build the `logAPI` part: https://github.com/llvm/llvm-project/blob/a8ac930b99d93b2a539ada7e566993d148899144/libunwind/src/libunwind.cpp#L434-L474

Will fix the message accordingly.

2023-11-28 20:02 UTC, arichardson approved these changes

2023-11-30 02:03 UTC, aheejin commented
I think the CI failures are unrelated. Merging.

2023-11-30 02:03 UTC, merged

2023-12-13 05:28 UTC, trcrsired commented
![image](https://github.com/llvm/llvm-project/assets/100043421/fef1a590-37cd-4fc0-803d-01ff18890439)
Not working

2023-12-13 05:49 UTC, aheejin commented
@trcrsired When we use it in Emscripten, we build it with `-D__USING_WASM_EXCEPTIONS__`. Does that work? I'm not sure which toolchain and libraries you are using though. (It looks you are using WASI, but does WASI have the EH support? Does it allow usage with llvm libunwind?)

2024-01-15 10:49 UTC, kaz7 reviewed
Please correct this code.  Thank you!

2024-01-16 04:09 UTC, aheejin commented on libunwind/src/libunwind.cpp
> +#if !defined(__USING_SJLJ_EXCEPTIONS__) || !defined(__USING_WASM_EXCEPTIONS__)
Sorry, fixed in #78230.

2024-01-16 09:20 UTC, kaz7 commented on libunwind/src/libunwind.cpp
> +#if !defined(__USING_SJLJ_EXCEPTIONS__) || !defined(__USING_WASM_EXCEPTIONS__)
Thanks a lot!!