[clang] Add partial-inlining options
llvm/llvm-project pull request #73210
Opened 2023-11-23 05:06 UTC by Jolyon0202

Adaptation of adding -fpartial-inlining and -fno-partial-inlining options with GCC.

2023-12-08 01:38 UTC, Jolyon0202 commented
This patch is used to adapt to many projects using gcc.

2025-02-14 09:33 UTC, TiborGY commented
@Jolyon0202 Your patch looks valid at first glance, but there is a merge conflict. Could you resolve that please?

2025-02-14 09:36 UTC, TiborGY requested changes
Since this is adding a (pair of) command line option, it should be added to docs/ReleaseNotes.rst

2025-02-27 09:23 UTC, Jolyon0202 commented
> @Jolyon0202 Your patch looks valid at first glance, but there is a merge conflict. Could you resolve that please?

Thx, I update a new merge request  #129024 and close this old mr.

2025-02-27 09:26 UTC, closed without merging