[clang][analyzer] Support `fputs` in the StreamChecker
llvm/llvm-project pull request #73335
Opened 2023-11-24 14:53 UTC by benshi001

2023-11-24 15:40 UTC, balazske requested changes

2023-11-27 10:14 UTC, balazske commented on clang/test/Analysis/stream-error.c
> +
One type of test is missing, where the stream is in EOF state (`StreamTesterChecker_make_feof_stream(F)` can be used to get such a stream `F`) and a `fputc` or `fputs` is called. Then no error and no warning should be generated, and the state after the call should be non-error and non-EOF.

2023-11-28 08:30 UTC, balazske commented on clang/lib/StaticAnalyzer/Checkers/StreamChecker.cpp
> +    auto &ASTC = C.getASTContext();
Line 866 still contains `auto`, usually `auto` is not used at such places (https://llvm.org/docs/CodingStandards.html#id29).

2023-11-28 08:38 UTC, balazske commented
I prefer to have the new test code with `StreamTesterChecker_make_feof_stream` in a new test function (with appropriate name like `write_after_eof_is_allowed`), to improve code maintainability (`fputc` and `fputs` can be in the same function).

In github PR's usually force push is not the good way to update the code (it makes difficult to follow what was updated compared to the previous code). It is better to add new commits for the changes. The final "squash and merge" will merge all into one commit.

2023-11-28 09:30 UTC, benshi001 commented
> I prefer to have the new test code with `StreamTesterChecker_make_feof_stream` in a new test function (with appropriate name like `write_after_eof_is_allowed`), to improve code maintainability (`fputc` and `fputs` can be in the same function).
> 
> In github PR's usually force push is not the good way to update the code (it makes difficult to follow what was updated compared to the previous code). It is better to add new commits for the changes. The final "squash and merge" will merge all into one commit.

I have added a new test `write_after_eof_is_allowed` as you mentioned. Thanks.

2023-11-28 10:40 UTC, balazske approved these changes

2023-11-28 12:14 UTC, merged