[libc++][format] Fixes formatting code units as integers.
llvm/llvm-project pull request #73396
Opened 2023-11-25 15:57 UTC by mordante

This paper was voted in as a DR, so it's retroactively enabled back to C++20; the C++ version that introduced std::format.

Implements:
- P2909R4 Fix formatting of code units as integers (Dude, where’s my ``char``?)

2023-11-27 19:53 UTC, ldionne requested changes

2023-11-28 18:25 UTC, mordante reviewed
Thanks for the review!

2023-11-28 18:25 UTC, mordante commented on libcxx/test/std/utilities/format/format.formatter/format.formatter.spec/formatter.char.fsigned-char.pass.cpp
> +  test(STR("10000000"), STR("b}"), char(-128));
@ldionne These values are different, for the unsigned test I use non-negative values.

2023-11-28 18:25 UTC, mordante commented on libcxx/test/std/utilities/format/format.formatter/format.formatter.spec/formatter.char.fsigned-char.pass.cpp
> +//===----------------------------------------------------------------------===//
They are not the same. See my other comment where they differ.

2023-11-29 14:40 UTC, ldionne approved these changes
LGTM -- please apply the clang-format diff to appease it though.

2023-11-29 16:53 UTC, mordante commented
> LGTM -- please apply the clang-format diff to appease it though.

Thanks for the review. It seems I locally have an older clang-format in my script.

2023-11-29 16:55 UTC, merged