[InstCombine] Do not simplify lshr/shl arg if it is part of fshl rotate pattern.
llvm/llvm-project pull request #73441
Opened 2023-11-26 11:10 UTC by quic-eikansh

The fshl/fshr having first two arguments as same gets lowered to targets
specific rotate. But based on the uses, one of the arguments can get
simplified resulting in different arguments performing equivalent operation.

This patch prevents the simplification of the arguments of lshr/shl if they are
part of fshl pattern.

2023-11-26 11:55 UTC, quic-eikansh commented
This pull request is created to address the reviews in https://github.com/llvm/llvm-project/pull/66115

2023-11-27 16:39 UTC, goldsteinn commented
I would expect to see test difference in the commit adding the new restriction.

2023-11-28 08:09 UTC, quic-eikansh commented
> I would expect to see test difference in the commit adding the new restriction.

I didn't get what you meant by this. Should I have code changes and test in the same commit?

2023-11-28 16:24 UTC, goldsteinn commented
> > I would expect to see test difference in the commit adding the new restriction.
> 
> I didn't get what you meant by this. Should I have code changes and test in the same commit?

Yes, otherwise the commit with the impl will not be passing (and it makes review more difficult as its hard to see the proper side affects of a change).

2023-12-05 14:23 UTC, quic-eikansh commented
I have squashed the changes and test into one commit. @goldsteinn

2023-12-06 23:48 UTC, goldsteinn commented
> I have squashed the changes and test into one commit. @goldsteinn

Thats not really ideal either... Then its difficult to review the test changes.
Typically the way we do it is two seperate commits i.e

commit 1: Tests (w/ checks before the implementation)
commit 2: Implementation (re update test checks)

That way in commit 2 we can see what actual changes the implementation is causing.

2023-12-13 16:27 UTC, quic-eikansh commented
@goldsteinn I have made the changes as you suggested.

2024-01-08 18:11 UTC, quic-eikansh commented
@goldsteinn Did you get a chance to look at it?

2024-01-08 20:03 UTC, dtcxzyw requested changes

2024-01-08 20:03 UTC, dtcxzyw commented on llvm/lib/Transforms/InstCombine/InstCombineAndOrXor.cpp
>    // TODO: Can we reduce the code duplication between this and the related
```suggestion
  assert(Or.getOpcode() == BinaryOperator::Or && "Expecting or instruction");
  // TODO: Can we reduce the code duplication between this and the related
```

2024-02-01 18:02 UTC, quic-eikansh commented on llvm/lib/Transforms/InstCombine/InstCombineAndOrXor.cpp
> +std::optional<std::tuple<Intrinsic::ID, SmallVector<Value *, 3>>>
Do `std::pair`  has advantage over `std::tuple`? I see `std::tuple` used in codebase even for 2 element. I have addressed other 2 reviews.

2024-02-02 07:15 UTC, dtcxzyw approved these changes
LGTM. Thanks!
Please wait for additional approval from other reviewers.

2024-02-02 09:09 UTC, quic-eikansh commented
@goldsteinn @nikic

2024-02-02 09:11 UTC, quic-eikansh commented
> LGTM. Thanks! Please wait for additional approval from other reviewers.

Thanks

2024-02-05 18:50 UTC, dtcxzyw commented
Ping.

2024-02-14 17:47 UTC, efriedma-quic approved these changes
Changes LGTM... but I'd like to land as a series of three commits; one for the refactor (6bbc776 and the fixup), one for the new tests (b896ff5), then one for the actual behavior change.

Please push separate PRs for the refactor and the test, then I'll merge everything for you.

2024-02-16 15:23 UTC, nikic commented on llvm/lib/Transforms/InstCombine/InstCombineAndOrXor.cpp
> +std::optional<std::tuple<Intrinsic::ID, SmallVector<Value *, 3>>>
I agree that we should use std::pair instead of std::tuple if there are only two elements.

2024-02-16 15:55 UTC, closed without merging