<algorithm>: __is_callable checks whether the callable can be called with rvalue
llvm/llvm-project pull request #73451
Opened 2023-11-26 17:13 UTC by changkhothuychung

2023-11-26 17:16 UTC, changkhothuychung commented
@ldionne ldi
can you give me a test example so I can add for this PR? should it be a verify or pass test?

2023-11-27 15:31 UTC, ldionne requested changes

2023-11-27 15:32 UTC, ldionne requested changes
Also, please add a description of the patch in the PR description!

2023-12-05 20:07 UTC, EricWF requested changes
I don't understand the motivation behind static asserts like this.  They have a number of downsides.

1.  They cost compile time and memory. The instantiations they perform live in the compilers AST until the end of the TU.
2. They don't catch broken code. The broken code is already broken, this just diagnoses it differently.
3.  They break well formed code.

As evidenced here, when we get the needless checks wrong, they break valid code. Which is a lot worse than providing a slightly better diagnostic to ill-formed code.

I say we get rid of them entirely.

2023-12-09 19:18 UTC, changkhothuychung commented
> I don't understand the motivation behind static asserts like this. They have a number of downsides.
> 
> 1. They cost compile time and memory. The instantiations they perform live in the compilers AST until the end of the TU.
> 2. They don't catch broken code. The broken code is already broken, this just diagnoses it differently.
> 3. They break well formed code.
> 
> As evidenced here, when we get the needless checks wrong, they break valid code. Which is a lot worse than providing a slightly better diagnostic to ill-formed code.
> 
> I say we get rid of them entirely.

@ldionne l
do you have any opinions on this? I will wait for your response before I continue.

2023-12-11 15:29 UTC, ldionne commented
> do you have any opinions on this? I will wait for your response before I continue.

@philnik777 Do you remember why you added the `__is_callable` checks in the first place? The Standard isn't all that clear about what the requirements are for classic algorithms, so I think removing these checks would also be a viable path forward. I seem to remember there was a good reason for adding those, so I'm reluctant to do it without remembering the context.

2023-12-11 15:29 UTC, ldionne commented on libcxx/test/libcxx/algorithms/const_callable.veriry.cpp
> +#include <algorithm>
Missing license.

2023-12-11 15:29 UTC, ldionne commented on libcxx/test/libcxx/algorithms/const_callable.veriry.cpp
> +}
Missing newline at the end of the file.

2023-12-11 15:29 UTC, ldionne commented on libcxx/test/libcxx/algorithms/const_callable.veriry.cpp
> +#include <algorithm>
Also, there is a typo in the file name (`.veriry.cpp`).

2023-12-11 15:42 UTC, philnik777 commented
> > do you have any opinions on this? I will wait for your response before I continue.
> 
> @philnik777 Do you remember why you added the `__is_callable` checks in the first place? The Standard isn't all that clear about what the requirements are for classic algorithms, so I think removing these checks would also be a viable path forward. I seem to remember there was a good reason for adding those, so I'm reluctant to do it without remembering the context.

We added them to disallow the use of functions to member pointers etc. to be passed to the classic algorithms.

2023-12-11 16:38 UTC, ldionne commented
> > @philnik777 Do you remember why you added the `__is_callable` checks in the first place? The Standard isn't all that clear about what the requirements are for classic algorithms, so I think removing these checks would also be a viable path forward. I seem to remember there was a good reason for adding those, so I'm reluctant to do it without remembering the context.
> 
> We added them to disallow the use of functions to member pointers etc. to be passed to the classic algorithms.

Oh yeah, that's it. Wouldn't that fail to compile already though?

2023-12-14 20:17 UTC, changkhothuychung commented on libcxx/test/libcxx/random/random.uniform.real/test.cpp
> +// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
@ldionne l
did you want to make the second operator `const &` ? I am getting errors, overloading either requires both functions to have ref-qualifiers or both lack.

2023-12-14 22:02 UTC, changkhothuychung commented on libcxx/test/libcxx/random/random.uniform.real/test.cpp
> +// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
I added a `.pass` file, can you take a look and let me know if they are good? if yes, I will add similar tests for the remaining algorithms.

2023-12-15 23:28 UTC, changkhothuychung commented
@ldionne it looks like there is a bug with the use of `std::lower_bound(begin(collatenames), end(collatenames), s, use_strcmp());` in the file regex.cpp, because `use_strcmp` doesn't have a const reference operator overloading. Should we add one to that code?

2024-01-08 18:57 UTC, ldionne commented
> @ldionne it looks like there is a bug with the use of `std::lower_bound(begin(collatenames), end(collatenames), s, use_strcmp());` in the file regex.cpp, because `use_strcmp` doesn't have a const reference operator overloading. Should we add one to that code?

Yes, we should add a const-qualification to `use_strcmp` in our own code.

@EricWF Now that I think about it some more, I think the issue these static asserts are addressing is that without them, we'll end up using `std::__invoke` to call the functions, which means that passing a PMF as a function would appear to work with classic algorithms, when in reality it's non-standard. So these static assertions are guarding us against Hyrum's law since our underlying algorithm implementation would allow for PMFs to be passed.

2024-08-01 14:32 UTC, ldionne approved these changes
Will merge once CI is green.

2024-08-01 18:08 UTC, merged

2024-08-01 19:45 UTC, vitalybuka commented
This one breaks multiple build bot 

https://lab.llvm.org/buildbot/#/builders/66/builds/2419

```
/b/sanitizer-x86_64-linux/build/build_default/runtimes/runtimes-bins/compiler-rt/lib/sanitizer_common/symbolizer/RTSanitizerCommonSymbolizerInternal.i386/symbolizer/libcxx/include/c++/v1/__algorithm/upper_bound.h:54:17: error: static assertion failed due to requirement '__is_callable<(lambda at /b/sanitizer-x86_64-linux/build/llvm-project/llvm/lib/DebugInfo/CodeView/LazyRandomTypeCollection.cpp:174:33) &, const llvm::codeview::TypeIndexOffset &, const llvm::codeview::TypeIndex &>::value': The comparator has to be callable
   54 |   static_assert(__is_callable<_Compare&, decltype(*__first), const _Tp&>::value, "The comparator has to be callable");
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/b/sanitizer-x86_64-linux/build/llvm-project/llvm/include/llvm/ADT/STLExtras.h:1974:15: note: in instantiation of function template specialization 'std::upper_bound<llvm::FixedStreamArrayIterator<llvm::codeview::TypeIndexOffset>, llvm::codeview::TypeIndex, (lambda at /b/sanitizer-x86_64-linux/build/llvm-project/llvm/lib/DebugInfo/CodeView/LazyRandomTypeCollection.cpp:174:33)>' requested here
 1974 |   return std::upper_bound(adl_begin(Range), adl_end(Range),
      |               ^
1 error generated.
[191/638] Building CXX object lib/DebugInfo/CodeView/CMakeFiles/LLVMDebugInfoCodeView.dir/TypeTableCollection.cpp.o
```

2024-08-01 19:55 UTC, ldionne commented
I'll revert. I think that's a bug in the order of arguments I passed to `__is_callable` for `upper_bound`. That wasn't intended.