[Clang] CWG2789 Overload resolution with implicit and explicit object…
llvm/llvm-project pull request #73493
Opened 2023-11-27 09:51 UTC by cor3ntin

… member functions

Implement the resolution to CWG2789 from
https://wiki.edg.com/pub/Wg21kona2023/StrawPolls/p3046r0.html

The DR page is not updated because the issue has not made it to a published list yet.

2023-11-27 17:20 UTC, Endilll requested changes

2023-11-27 17:20 UTC, Endilll commented on clang/test/CXX/drs/dr27xx.cpp
> +    s.g(); // expected-error {{call to member function 'g' is ambiguous}}
I believe our current best practices on handling errors with notes in DR tests are showcased here: https://github.com/llvm/llvm-project/blob/fe3c4218438adeebba4914a57b4d382e3a947394/clang/test/CXX/drs/dr13xx.cpp#L505
Notes being scattered across the test makes it harder to match the test against compiler output on e.g. Compiler Explorer.

2023-11-27 18:52 UTC, AaronBallman approved these changes
Changes LGTM modulo some comments on the review.

2023-11-27 18:52 UTC, AaronBallman commented on clang/lib/Sema/SemaOverload.cpp
> +  auto *Fn2 = Cand2.Function;
Please spell out the types explicitly as they're not spelled by the initializer.

2023-11-28 03:29 UTC, cor3ntin commented
@Endilll I addressed your feedback!

2023-11-28 08:05 UTC, Endilll approved these changes

2023-11-28 12:30 UTC, merged