[libc++][test] Change forbidden `extents<char>` to `extents<signed char>`
llvm/llvm-project pull request #73535
Opened 2023-11-27 16:20 UTC by StephanTLavavej

Found while running libc++'s test suite with MSVC's STL.

[N4964](https://wg21.link/N4964) \[mdspan.extents.overview\]/1.1:

> ```cpp
> template<class IndexType, size_t... Extents>
> class extents {
> ```
> \[...\]
> *Mandates:*
> * `IndexType` is a signed or unsigned integer type \[...\]

This famously excludes `char`.

<details><summary>Click to expand citation, [basic.fundamental]/1, /2, /7:</summary>

> There are five *standard signed integer types*: "`signed char`", "`short int`", "`int`", "`long int`", and "`long long int`". \[...\] The standard and extended signed integer types are collectively called *signed integer types*.

> For each of the standard signed integer types, there exists a corresponding (but different) *standard unsigned integer type*: "`unsigned char`", "`unsigned short int`", "`unsigned int`", "`unsigned long int`", and "`unsigned long long int`". \[...\] The standard and extended unsigned integer types are collectively called *unsigned integer types*.

> Type `char` is a distinct type that has an implementation-defined choice of "`signed char`" or "`unsigned char`" as its underlying type.
</details>

MSVC's STL enforces the Mandates here, so this PR changes the relevant occurrences of `char` to `signed char`. To make this work, we also need to add an `operator signed char()` to the test helper type `IntType` so it remains unambiguously convertible.

(libc++ should also enforce the Mandates, \[structure.specifications\]/3.2, but this PR doesn't attempt to make such a change. I'm not set up to build and test libc++ normally, I just have my exotic configuration.)

2023-11-27 18:51 UTC, ldionne commented
@crtrott Can you follow-up on adding a `static_assert` for the mandate? We should do this sooner rather than later since it'll prevent people from starting to rely on this.

2023-11-27 18:51 UTC, ldionne requested changes

2023-11-28 02:22 UTC, StephanTLavavej commented on libcxx/test/std/containers/views/mdspan/ConvertibleToIntegral.h
>    constexpr operator char() const noexcept { return val; }
Done! I worried it might be used in some other context, but it ended up being harmless to remove.

2023-11-28 23:17 UTC, ldionne approved these changes

2023-11-28 23:20 UTC, merged