[AArch64][SME2] Add _x2/_x4 svqrshr builtins.
llvm/llvm-project pull request #74100
Opened 2023-12-01 16:30 UTC by dtemirbulatov

Patch by: Kerry McLaughlin <kerry.mclaughlin@arm.com>

2023-12-01 16:41 UTC, sdesmalen-arm requested changes

2023-12-01 16:42 UTC, kmclaughlin-arm commented on clang/include/clang/Basic/arm_sve.td
>  }
The qrshr* builtins have changed again in the latest ACLE update (https://github.com/ARM-software/acle/pull/278):
```
arm_neon.h shift-by-immediate instructions use an _n suffix
to indicate that the shift amount is scalar. arm_sve.h
carried this across to the full/non-overloaded forms of SVE
immediate shifts. It seems worth doing the same here for
consistency, and to protect against vector-vector forms
being added in future.
```
Please can you apply this change here?

2023-12-05 08:59 UTC, sdesmalen-arm approved these changes
LGTM

2023-12-07 16:29 UTC, merged

2023-12-07 17:44 UTC, jayfoad commented
I committed a fix for builds that do not enable AArch64: fb2b907fbd2c9ac25077dae01d777d884e09a7a4