[Driver][LTO] Copy fix empty stats filename to AMDGPU, HIPAMD, MinGW
llvm/llvm-project pull request #74178
Opened 2023-12-02 03:34 UTC by brad0

Copying https://github.com/llvm/llvm-project/commit/1881832994840baa6e42f908b8822ce4d15ab632 to the last of the targets that use LTO.

But I am not sure about tests for these targets, especially the AMD toolchains.

Could the respective AMD and MinGW commiters please help here?

2023-12-02 03:57 UTC, jhuber6 reviewed
Why couldn't you have put this logic in `addLTOOptions`? Seems like it's copy-pasted verbatim at every site now.

AMD should handle very similarly to Linux here. They both compile down to LLVM-IR and get sent to `ld.lld`.

2023-12-02 04:08 UTC, brad0 commented
> Why couldn't you have put this logic in `addLTOOptions`? Seems like it's copy-pasted verbatim at every site now.
> 
> AMD should handle very similarly to Linux here. They both compile down to LLVM-IR and get sent to `ld.lld`.

It's not my area, but I was thinking that would make more sense. I am just trying to ensure consistency with the various targets.

2023-12-02 04:10 UTC, brad0 commented
@MaskRay

2023-12-02 04:55 UTC, MaskRay commented
At this point, it does seem that changing `addLTOOption` to accept `Inputs` instead of `Input` will eliminate duplication and ensure consistency among targets.

2023-12-02 15:41 UTC, yxsamliu commented
I think we should change signature of addLTOOptions. Instead of accepting a single InputInfo, it should accept InputInfoList. Then these ConstructJob members will pass Inputs to addLTOOptions, and addLTOOptions will pick the first file from it. This should be able to avoid repeated code.

2023-12-09 08:36 UTC, brad0 commented
@MaskRay Any response to what [yxsamliu](https://github.com/yxsamliu) said?

2023-12-09 19:14 UTC, MaskRay commented
We should change `addLTSOption` and let it perform:
```
    auto Input = llvm::find_if(
        Inputs, [](const InputInfo &II) -> bool { return II.isFilename(); });
    if (Input == Inputs.end())
      // For a very rare case, all of the inputs to the linker are
      // InputArg. If that happens, just use the first InputInfo.
      Input = Inputs.begin();
```

2024-01-09 08:42 UTC, arsenm requested changes
Last comments requested changes

2025-05-24 01:56 UTC, jhuber6 approved these changes
Looks like a nice cleanup

2025-05-24 02:45 UTC, MaskRay approved these changes

2025-05-24 03:03 UTC, merged