Missing opt with ctlz and shifts of power of 2 constants (#41333)
llvm/llvm-project pull request #74175
Opened 2023-12-02 03:26 UTC by snikitav

Closes #41333

2023-12-02 05:53 UTC, dtcxzyw commented
Could you please add the alive2 proof to the PR description?

2023-12-02 06:00 UTC, dtcxzyw requested changes

2023-12-02 06:09 UTC, dtcxzyw requested changes

2023-12-02 20:17 UTC, snikitav commented on llvm/lib/Transforms/InstCombine/InstCombineCalls.cpp
> +  ConstantInt *CInt;
If change `ConstantInt` to `Constant` not only constant splat vectors may be handled:
```llvm
----------------------------------------
define <2 x i32> @src(<2 x i32> %#0) {
#1:
  %div = lshr <2 x i32> { 8387584, 1234567 }, %#0
  %ctlz = ctlz <2 x i32> %div, 1
  ret <2 x i32> %ctlz
}
=>
define <2 x i32> @tgt(<2 x i32> %#0) {
#1:
  %ctlz = add <2 x i32> %#0, { 9, 11 }
  ret <2 x i32> %ctlz
}
Transformation seems to be correct!
```

2023-12-02 22:30 UTC, snikitav commented on llvm/test/Transforms/InstCombine/ctlz-cttz-shifts.ll
> +; RUN: opt -passes=instcombine -S < %s | FileCheck %s
done

2023-12-04 05:41 UTC, dtcxzyw requested changes

2023-12-04 06:02 UTC, dtcxzyw commented on llvm/lib/Transforms/InstCombine/InstCombineCalls.cpp
> +      return IC.replaceInstUsesWith(II, IC.Builder.CreateAdd(ConstCttz, X));
Inferring `nsw/nuw` flags can exploit more optimization opportunities. You don't need to do anything until we find it is a missed optimization in some real-world applications.

But if you think it has value I'm OK with it. Beware of the type as `nsw/nuw` flags may not be applicable to `i1/i2` :)

2023-12-05 20:56 UTC, snikitav commented on llvm/lib/Transforms/InstCombine/InstCombineCalls.cpp
> +        match(Op0, m_NSWShl(m_Constant(C), m_Value(X)))) {
Thank you for pointing this out. Fixed the code. BTW, is there a comprehensive guide how to use alive2 properly?

2023-12-06 12:18 UTC, dtcxzyw approved these changes
LGTM. Please wait for additional approval from other reviewers.

2023-12-07 15:00 UTC, nikic approved these changes
LGTM apart from one issue.

2023-12-07 20:03 UTC, snikitav commented on llvm/lib/Transforms/InstCombine/InstCombineCalls.cpp
> +    if (match(Op0, m_Shl(m_Constant(C), m_Value(X))) && match(Op1, m_One())) {
Fixed

2023-12-08 07:02 UTC, dtcxzyw approved these changes

2023-12-08 07:06 UTC, merged