[libc++][test] disable all atomic<long double> tests
llvm/llvm-project pull request #74201
Opened 2023-12-02 17:57 UTC by huixie90

2023-12-02 22:13 UTC, EricWF commented
This does not fix the issue, it hides it.

2023-12-02 22:13 UTC, EricWF requested changes
This is not an OK way to deal with broken tests.

2023-12-03 15:29 UTC, huixie90 commented
> This is not an OK way to deal with broken tests.
There are lots of discussions on the other PR when these tests were added.  Basically long double atomic is broken for years and we had some bug reports (against clang) open already. These tests were newly added which already had lots of platforms disabled. But after the merge, we just got more reports that these tests failed in the wild that lots of other platforms that are not in our CI. After some discussions, we will just disable the tests. atomic long double was and is broken. We need to fix the issue before we can have these tests running. 

We cannot fix it in the library side by our own. We need clang’s support (at least provide a way to zero out the long double’s 56bits padding)

2023-12-04 15:21 UTC, ldionne approved these changes
I agree with @huixie90 here. This is not fixing the broken atomic support, but we have other GH issues tracking that. This is merely making the CI green again for some configurations that are currently failing.

The bottom line is that atomic's support for `long double` is broken all around and we added tests for it, which now obviously fail. We should probably have punted on adding the tests for `long double` until they actually worked on all platforms, and this is what this PR is doing.

2023-12-04 23:57 UTC, vitalybuka commented
Would it be better to disable `long double` test for x86_64 only?

2023-12-09 13:18 UTC, mordante reviewed
I also prefer to temporary disable the tests to get the CI green again.

2023-12-09 13:18 UTC, mordante commented on libcxx/test/libcxx/atomics/atomics.types.generic/atomics.types.float/lockfree.pass.cpp
> +  // https://github.com/llvm/llvm-project/issues/47978
```suggestion
  // TODO https://github.com/llvm/llvm-project/issues/47978
```
This makes it easier to find them.

2023-12-11 21:19 UTC, ldionne approved these changes
LGTM. I am going to merge this since CI seems happy and this will resolve CI issues that have been ongoing for way too long on Gentoo.

2023-12-11 21:20 UTC, merged