[clang-tidy] readability-container-contains literal suffixes
llvm/llvm-project pull request #74215
Opened 2023-12-02 23:19 UTC by schenker

Before this PR, readability-container-contains fixits did not handle integer literal suffixes correctly. It e.g. changed
```
  MyMap.count(2) != 0U;
```
into
```
  MyMap.contains(2)U;
```

With this PR, it correctly changes it to
```
  MyMap.contains(2);
```

2023-12-03 03:23 UTC, EugeneZelenko requested changes

2023-12-03 03:23 UTC, EugeneZelenko commented on clang-tools-extra/docs/ReleaseNotes.rst
> +  interger literals with suffixes in fixits.
`fix-its`.

2023-12-04 09:24 UTC, PiotrZSL approved these changes
LGTM

2023-12-04 15:33 UTC, EugeneZelenko approved these changes

2023-12-04 16:30 UTC, merged