[flang] Error out when assumed rank variable is used as dummy argument
llvm/llvm-project pull request #74286
Opened 2023-12-04 07:42 UTC by NimishMishra

This patch adds a check to error out when an assumed rank variable is used as dummy argument.

Fixes https://github.com/llvm/llvm-project/issues/74285

2023-12-04 16:02 UTC, klausler requested changes
The title of this patch refers to dummy arguments, but the code itself seems to be testing the selector of a `SELECT TYPE` construct to implement a check to ensure that the selector is not assumed-rank. Where in the standard are assumed rank objects precluded from being used in `SELECT TYPE`?

(Also, `evaluate::IsAssumedRank()` would be a better implementation of the test, if it were needed.  But I need to understand what constraint or requirement in the standard is being enforced here first.)

2023-12-06 03:18 UTC, NimishMishra commented
> The title of this patch refers to dummy arguments, but the code itself seems to be testing the selector of a `SELECT TYPE` construct to implement a check to ensure that the selector is not assumed-rank. Where in the standard are assumed rank objects precluded from being used in `SELECT TYPE`?

Thank you for the comment. I can change the title of the patch.

The interpretation leading to this patch that I was following was C838 in the "An assumed-rank variable name shall not appear in a designator or expression except as an actual argument that corresponds to a dummy argument that is assumed-rank...". Since SELECT TYPE selectors are either designators or expressions (from parse-tree.h), my understanding was this restriction is transitively applicable in the current context too. Plus, seemed like C838 was also responsible for gfortran's semantic error on this test case.

2024-01-01 06:05 UTC, NimishMishra commented
@klausler Could you have a relook at this once, if it is okay now?

2024-01-01 18:16 UTC, klausler approved these changes

2024-01-01 18:16 UTC, klausler commented on flang/lib/Semantics/check-select-type.cpp
> +          "Assumed-rank variable "
I recommend that you not split error messages across multiple lines -- that makes it much more difficult to grep the sources to find the code that emits a particular error.

2024-01-03 13:46 UTC, merged