[AssignemntTracking] Skip large types in redundant debug info pruning
llvm/llvm-project pull request #74329
Opened 2023-12-04 15:22 UTC by OCHyams

The pruning code uses a BitVector for varibles. BitVector supports sizes less than
`max(uint32)-63`, so skip equal and larger types. Fixes https://github.com/llvm/llvm-project/issues/74189 (crash report).

The reason it's `max(uint32)-63` and not `max(uint32)` is because of `BitVector::NumBitWords`:
```
  unsigned NumBitWords(unsigned S) const {
    return (S + BITWORD_SIZE-1) / BITWORD_SIZE;
  }
```
The numerator evaluation yields an incorrect value when S + BITWORD_SIZE wraps to >= 1. I'm hesitant to change BitVector code, so have gone with this defensive fix.

2023-12-04 17:28 UTC, jryans requested changes, later dismissed
Overall reasonable, but see comments below.

Also, there's a typo in the commit and PR title: "AssignemntTracking" should be "AssignmentTracking"

2023-12-04 19:46 UTC, nikic commented
Independently of the crash, doesn't this mean that this code will be incredibly slow for large types?

2023-12-05 08:12 UTC, OCHyams commented on llvm/lib/CodeGen/AssignmentTrackingAnalysis.cpp
> +      const uint64_t MaxSize = std::numeric_limits<unsigned>::max() - 63;
Can do - I'll change this if we keep the cutoff tied to bitvector.

2023-12-05 08:19 UTC, OCHyams commented
Thanks both for the reviews.

@nikic 

> Independently of the crash, doesn't this mean that this code will be incredibly slow for large types?

There's probably a point at which pruning becomes unprofitable. We could lower the threshold - do you have a ballpark figure you'd suggest?

2023-12-05 15:04 UTC, jmorse commented
This sounds good, while agreeing with the comments so far. It's tempting to say that "anyone who's allocating a massively sized stack variable is asking for trouble" and to not support that situation well. Unfortunately that's also exactly the scenario where developers probably want their debugger to work well. What are the implications of over-sized types being ignored by this code, are there any correctness issues or is it just efficiency?

2023-12-05 16:19 UTC, OCHyams commented
> What are the implications of over-sized types being ignored by this code, are there any correctness issues or is it just efficiency?

Just efficiency.

As well as choosing a smaller size limit, another easy win here could be to use byte sizes rather than bit sizes, which would bring down the bitvector sizes in all cases (at the cost accidentally not pruning where some fragments don't fit into bytes exactly, but that'll probably be a very rare situation and doesn't impose any correctness problems).

I can also have a look to see if there's something else we can use. Ideally we actually want something like an interval map, though IntervalMap as it exists now is not useful for this since it doesn't support overlapping insertion (and also might be a bit heavy weight too).

2023-12-06 17:03 UTC, jryans reviewed
Thanks, the issues I mentioned appear to be resolved. I have no opinion on the details of exactly what cutoff to use, so I'll leave that for others to weigh in on.

2023-12-07 14:53 UTC, nikic commented on llvm/lib/CodeGen/AssignmentTrackingAnalysis.cpp
> +      uint64_t SizeInBytes = SizeInBits + 7 / 8;
divideCeil

2023-12-07 14:53 UTC, nikic commented on llvm/lib/CodeGen/AssignmentTrackingAnalysis.cpp
> +      uint64_t StartInBytes = Fragment.startInBits() + 7 / 8;
Not familiar with this code, but shouldn't the start be rounded down?

2023-12-07 16:20 UTC, OCHyams commented
+  Address outstanding feedback
+ Update summary

2023-12-11 11:27 UTC, SLTozer approved these changes
Got a small question about the BitVector FIXME, but otherwise this LGTM.

2023-12-11 11:27 UTC, SLTozer commented on llvm/lib/CodeGen/AssignmentTrackingAnalysis.cpp
> +        // FIXME: Don't use a BitVector.
Is there a reason to not use a BitVector here, given that as discussed we don't lose correctness, and for the vast majority of cases we are well below this limit?

2023-12-11 12:23 UTC, merged