[SymbolFileDWARF][NFC] Remove duplicated code checking for type tags
llvm/llvm-project pull request #74773
Opened 2023-12-07 22:19 UTC by felipepiovezan

There was duplicated (and complex) code querying whether tags were type-like tags (i.e. class or struct); this has been factored out into a helper function.

There was also a comment about not comparing identical DIEs without ever performing that check; this comment has been removed. It was likely a result of copy paste from another function in this same file which actually does that check.

2023-12-07 22:25 UTC, Michael137 approved these changes
LGTM

2023-12-07 22:55 UTC, bulbazord approved these changes
LGTM

2023-12-08 08:00 UTC, clayborg requested changes

2023-12-08 13:34 UTC, felipepiovezan commented on lldb/source/Plugins/SymbolFile/DWARF/SymbolFileDWARF.cpp
> +          type_tag == tag || (IsTypeTag(type_tag) && IsTypeTag(tag));
I'm not sure I follow, the logic of the opposite: equality failed, so we have to test whether both are "clasd-ish" tags. If one is a class but the other is a namespace, we need this expression to be false

2023-12-08 13:35 UTC, felipepiovezan commented on lldb/source/Plugins/SymbolFile/DWARF/SymbolFileDWARF.cpp
> +bool IsTypeTag(llvm::dwarf::Tag Tag) {
I'll rename it.

Regarding static, this function as well as most functions defined above it, are in an anonymous namespace

2023-12-08 14:09 UTC, felipepiovezan commented on lldb/source/Plugins/SymbolFile/DWARF/SymbolFileDWARF.cpp
> +bool IsTypeTag(llvm::dwarf::Tag Tag) {
Do you prefer if I take it out of the namespace and make it static? In llvm-project/llvm I would have done because of the programming guidelines

2023-12-08 17:40 UTC, clayborg approved these changes
Thanks for the quick change, and I need to check sources for the anonymous namespace before I comment next time!

2023-12-11 11:01 UTC, merged