[Cygwin] Cygwin general
llvm/llvm-project pull request #74944
Opened 2023-12-09 18:19 UTC by xu-chiheng

2023-12-11 12:48 UTC, mstorsjo commented
Changes need a more elaborate explanation than this.

We shouldn't, in general, be moving platform specific code from `Windows/Process.inc` into the comon code in `Process.cpp`. I presume the context is that Cygwin builds generally are considered Unix, not Windows, and use `Unix/Process.inc`, while for this specific function, it needs to use Win32 API. Such context needs to be mentioned for reviewers to be able to make sense of the change.

I'm not sure what the cleanest/most acceptable way to do that would be though - @MaskRay?

2023-12-16 21:46 UTC, MaskRay commented
> Changes need a more elaborate explanation than this.
> 
> We shouldn't, in general, be moving platform specific code from `Windows/Process.inc` into the comon code in `Process.cpp`. I presume the context is that Cygwin builds generally are considered Unix, not Windows, and use `Unix/Process.inc`, while for this specific function, it needs to use Win32 API. Such context needs to be mentioned for reviewers to be able to make sense of the change.

Agree.

> I'm not sure what the cleanest/most acceptable way to do that would be though - @MaskRay?

It seems that cygwin should use the `LLVM_ON_UNIX` code path?
I feel that adding more cygwin stuff is worth a discussion on https://discourse.llvm.org/

@chapuni added some cygwin support long time ago and may know more about the history.

2023-12-17 01:38 UTC, chapuni commented
It's nasty. Cygwin shall be "Unix-variant but smells Win32".

I don't know the right answer since I haven't played Cygwin for a long while.
What is the correlation between `dwPageSize`, `dwAllocationGranularity`, and Cygwin's `::getpagesize()` and their actual values?
(IIRC, Cygwin assumed `dwAllocationGranularity`, that was 64k, 56bc3419a3b33fc8c110001c0ab06fced4b6a6df)

@MaskRay FYI, I was running builders for cygwin in the past.

IMO, this is just only a place that Cygwin wanted to know the phys page size and may leave as-is.
(and I wonder it didn't affect to other Win32 implementations)

@xu-chiheng let's know your actual issues and what you wanted to resolve.

2023-12-18 13:39 UTC, xu-chiheng commented
> @xu-chiheng let's know your actual issues and what you wanted to resolve.
Just to remove the kludge below and beautify code.
-#if defined(__CYGWIN__)
-  // Don't try to map files that are exactly a multiple of the physical page size
-  // if we need a null terminator.
-  // FIXME: We should reorganize again getPageSize() on Win32.
-  if ((FileSize & (4096 - 1)) == 0)
-    return false;
-#endif
-

2023-12-31 23:20 UTC, asl requested changes

2023-12-31 23:20 UTC, asl commented on llvm/lib/Support/Process.cpp
> +#if defined(_WIN32) || defined(__CYGWIN__)
Supporting what @mstorsjo said, this should be done in opposite direction. Process.cpp is mostly considered as "target-neutral"

2024-04-02 06:56 UTC, closed without merging