[BPF] support indirect branch (callx) in AsmParser
llvm/llvm-project pull request #74988
Opened 2023-12-10 10:30 UTC by inclyc

Simply mark `callx` as a valid ID, so it can be recognized.

Previously this valid asm triggers an error:

    # clang local/callx.s -target bpf
    local/callx.s:8:2: error: invalid register/token name
            callx r1
            ^

2023-12-10 10:32 UTC, inclyc commented
Sorry looks the tests are placed in wrong directory

2025-02-27 10:50 UTC, TiborGY commented
@inclyc Was there a reason why this never got merged?

2025-02-28 01:48 UTC, inclyc commented
Kindly ping @yonghong-song @4ast, could you review this PR?

2025-02-28 01:51 UTC, 4ast requested changes
Because callx is a reserved insn. There is no kernel support yet.

2025-02-28 02:04 UTC, inclyc commented
> Because callx is a reserved insn. There is no kernel support yet.

Thanks, I will close the PR :).

2025-02-28 02:04 UTC, closed without merging