[clang-tidy][misleading-indentation]ignore false-positives for line started with empty macro
llvm/llvm-project pull request #75061
Opened 2023-12-11 15:33 UTC by HerrCai0907

Fixes: #71767

2023-12-12 15:39 UTC, EugeneZelenko commented on clang-tools-extra/docs/ReleaseNotes.rst
> +- Improved :doc:`readability-misleading-indentation
Please keep alphabetical order (by check name).

2023-12-17 13:52 UTC, PiotrZSL commented on clang-tools-extra/clang-tidy/readability/MisleadingIndentationCheck.cpp
> +  if (SM.getExpansionLineNumber(BeforeLoc) ==
return X != Y;

2023-12-17 13:53 UTC, PiotrZSL commented on clang-tools-extra/clang-tidy/readability/MisleadingIndentationCheck.cpp
> +  NextLoc.dump(SM);
remove debug

2023-12-17 13:54 UTC, PiotrZSL requested changes
+- fine, fix pointed out nits and could land

2023-12-27 07:34 UTC, PiotrZSL approved these changes
LGTM

2023-12-27 08:16 UTC, merged