[WIP][compiler-rt][fuchsia] Preallocate a vmar for sanitizer internals
llvm/llvm-project pull request #75256
Opened 2023-12-13 00:05 UTC by PiJoules

In an effort to reduce more mmap fragmentation, allocate a large enough vmar where we can map sanitizer internals via DoAnonymousMmap. Objects being mapped here include asan's FakeStack, LowLevelAllocator mappings, the primary allocator's TwoLevelMap, InternalMmapVector, StackStore, and asan's thread internals. The vmar is large enough to hold the total size of these objects seen in a "typical" process lifetime. If the vmar is full, it will fallback to mapping in the root vmar.

2023-12-13 00:06 UTC, PiJoules commented
WIP for now and will request a formal review once I assert I can do 100 runs of the boot-libc-unittests on bringup.riscv64-asan without a flake.

2023-12-13 19:28 UTC, PiJoules commented
Ok now requesting a formal review since it ran 100 times without flaking. Prior to this, it would flake about every 10 runs.

2024-01-10 18:25 UTC, PiJoules commented
*ping*

2024-01-11 01:23 UTC, frobtech commented on compiler-rt/lib/sanitizer_common/sanitizer_fuchsia.cpp
> +// For any sanitizer internal that needs to map something which can be unmmaped
typo: "unmapped"

2024-01-11 01:35 UTC, frobtech requested changes

2024-01-11 01:35 UTC, frobtech commented on compiler-rt/lib/sanitizer_common/sanitizer_fuchsia.cpp
> +// later, first attempt to map to a pre-allocated vmar. This helps reduce
I find it more readable to use caps for acronyms like VMAR.

2024-01-11 01:35 UTC, frobtech commented on compiler-rt/lib/sanitizer_common/sanitizer_fuchsia.cpp
> +// internal mappings in a run of boot-libc-unittests.
I don't think we should be referring to individual Fuchsia tree things here.  We can say things more generic like "a large test case".  Let's use a more round number.  If ~12.32MiB is a good number, then 13MiB is a good number, and you can write that as `13 << 20; // 13 MiB` or something more readable like that.

2024-01-11 01:35 UTC, frobtech commented on compiler-rt/lib/sanitizer_common/sanitizer_fuchsia.cpp
> +static zx_handle_t gSanitizerHeapVmar = 0;
It's fine to just assume that default zero initialization is right here, but if you're going to be explicit then use `ZX_HANDLE_INVALID`.

2024-01-11 01:35 UTC, frobtech commented on compiler-rt/lib/sanitizer_common/sanitizer_fuchsia.cpp
> +  if (!gSanitizerHeapVmar) {
Don't use implicit bool coercion for non-pointers.  Use `!= ZX_HANDLE_INVALID`.

2024-01-11 01:35 UTC, frobtech commented on compiler-rt/lib/sanitizer_common/sanitizer_fuchsia.cpp
> +    CHECK_NE(gSanitizerHeapVmar, 0);
`ZX_HANDLE_INVALID`.

2024-01-11 01:35 UTC, frobtech commented on compiler-rt/lib/sanitizer_common/sanitizer_fuchsia.cpp
> +  if ((status = GetSanitizerHeapVmar(&vmar)) != ZX_OK)
Prefer initializing in the declaration to setting the variable inside the `if`.

2024-01-11 01:35 UTC, frobtech commented on compiler-rt/lib/sanitizer_common/sanitizer_fuchsia.cpp
> +  if (status != ZX_OK && target_vmar == gSanitizerHeapVmar) {
Check for the specific error code returned for this case, which is `ZX_ERR_INVALID_ARGS`.

2024-01-11 01:35 UTC, frobtech commented on compiler-rt/lib/sanitizer_common/sanitizer_fuchsia.cpp
> +  UnmapOrDieVmar(addr, size, gSanitizerHeapVmar);
This needs to use the fallback logic in case the root vmar was used, as above.

2024-01-11 22:38 UTC, frobtech approved these changes

2024-01-11 22:38 UTC, frobtech commented on compiler-rt/lib/sanitizer_common/sanitizer_fuchsia.cpp
> +  UnmapOrDieVmar(addr, size, gSanitizerHeapVmar);
I see, thanks. The way I saw the diff that was hard to find, probably just my lack of familiarity with the GH code review UI.

2024-01-11 23:30 UTC, merged