[clang] Parse attribute [[gnu::no_stack_protector]]
llvm/llvm-project pull request #75289
Opened 2023-12-13 06:57 UTC by Lancern

This commit adds relative TableGen definitions to parse the [[gnu::no_stack_protector]] attribute.

This PR addresses issue #75235.

2023-12-13 08:09 UTC, inclyc requested changes
The PR contains functional change so please add test & assertions under `clang/test`

2023-12-13 13:11 UTC, inclyc approved these changes

2023-12-13 15:47 UTC, Lancern commented on clang/test/Parser/gnu-attributes.c
> +// RUN: %clang_cc1 -fsyntax-only -verify -std=c23 %s
My concern is that names such as `attr-no-stack-protector.cpp` are too "specific". No other single attribute has its dedicated test file under the test directory.

2023-12-13 17:20 UTC, inclyc commented on clang/test/Parser/gnu-attributes.c
> +// RUN: %clang_cc1 -fsyntax-only -verify -std=c23 %s
I just noticed that we already have test file at `clang/test/Sema/no_stack_protector.c`, may be just update that file.

> No other single attribute has its dedicated test file under the test directory.

No, just see `no_stack_protector.c`.

2023-12-13 17:26 UTC, inclyc commented on clang/test/Parser/gnu-attributes.c
> +// RUN: %clang_cc1 -fsyntax-only -verify -std=c23 %s
PS. for cxx attribute you may create a new file.

2023-12-14 03:22 UTC, inclyc approved these changes

2023-12-14 03:31 UTC, merged