[mlir][vector] Deal with special patterns when emulating masked load/store
llvm/llvm-project pull request #75587
Opened 2023-12-15 12:08 UTC by Hsiangkai

We can simplify the generated code when the mask is created by constant_mask or create_mask. The mask will look like [1, 1, 1, ...]. We can use vector.load + vector.insert_strided_slice to emulate maskedload and use vector.extract_strided_slice + vector.store to emulate maskedstore.

2023-12-19 14:54 UTC, kuhar reviewed
What happens when you run `--canonicalize --cse` after masked load/store emulation? Is this enough to fold all the masking away? If not, what is left?

2023-12-19 15:42 UTC, Hsiangkai commented
> What happens when you run `--canonicalize --cse` after masked load/store emulation? Is this enough to fold all the masking away? If not, what is left?

There is no change after applying `--canonicalize --cse`.

2023-12-19 15:54 UTC, kuhar commented
> > What happens when you run `--canonicalize --cse` after masked load/store emulation? Is this enough to fold all the masking away? If not, what is left?
> 
> There is no change after applying `--canonicalize --cse`.

I mean with the current lowering without the changes from this PR. When I wrote `vector.gather` lowering I found that we didn't need any special cases for constant inputs as everything would just fold away: https://github.com/llvm/llvm-project/blob/1b4a0794b0c7244a0b74ac0a2239fb60a62f9c70/mlir/test/Dialect/Vector/vector-gather-lowering.mlir#L130-L153

2023-12-19 16:41 UTC, Hsiangkai commented
I use the following mlir func as input (without this PR)
```
func.func @vector_maskedstore_c2(%arg0: memref<4x5xf32>, %arg1: vector<4xf32>) {
  %c7 = arith.constant 7 : index
  %c6 = arith.constant 6 : index
  %c5 = arith.constant 5 : index
  %c0 = arith.constant 0 : index
  %c4 = arith.constant 4 : index
  %0 = vector.constant_mask [2] : vector<4xi1>
  %1 = vector.extract %0[0] : i1 from vector<4xi1>
  scf.if %1 {
    %5 = vector.extract %arg1[0] : f32 from vector<4xf32>
    memref.store %5, %arg0[%c0, %c4] : memref<4x5xf32>
  }
  %2 = vector.extract %0[1] : i1 from vector<4xi1>
  scf.if %2 {
    %5 = vector.extract %arg1[1] : f32 from vector<4xf32>
    memref.store %5, %arg0[%c0, %c5] : memref<4x5xf32>
  }
  %3 = vector.extract %0[2] : i1 from vector<4xi1>
  scf.if %3 {
    %5 = vector.extract %arg1[2] : f32 from vector<4xf32>
    memref.store %5, %arg0[%c0, %c6] : memref<4x5xf32>
  }
  %4 = vector.extract %0[3] : i1 from vector<4xi1>
  scf.if %4 {
    %5 = vector.extract %arg1[3] : f32 from vector<4xf32>
    memref.store %5, %arg0[%c0, %c7] : memref<4x5xf32>
  }
  return
}
```
After applying `--canonicalize --cse`, there is no change at all.
The output is
```
func.func @vector_maskedstore_c2(%arg0: memref<4x5xf32>, %arg1: vector<4xf32>) {
  %c7 = arith.constant 7 : index
  %c6 = arith.constant 6 : index
  %c5 = arith.constant 5 : index
  %c0 = arith.constant 0 : index
  %c4 = arith.constant 4 : index
  %0 = vector.constant_mask [2] : vector<4xi1>
  %1 = vector.extract %0[0] : i1 from vector<4xi1>
  scf.if %1 {
    %5 = vector.extract %arg1[0] : f32 from vector<4xf32>
    memref.store %5, %arg0[%c0, %c4] : memref<4x5xf32>
  }
  %2 = vector.extract %0[1] : i1 from vector<4xi1>
  scf.if %2 {
    %5 = vector.extract %arg1[1] : f32 from vector<4xf32>
    memref.store %5, %arg0[%c0, %c5] : memref<4x5xf32>
  }
  %3 = vector.extract %0[2] : i1 from vector<4xi1>
  scf.if %3 {
    %5 = vector.extract %arg1[2] : f32 from vector<4xf32>
    memref.store %5, %arg0[%c0, %c6] : memref<4x5xf32>
  }
  %4 = vector.extract %0[3] : i1 from vector<4xi1>
  scf.if %4 {
    %5 = vector.extract %arg1[3] : f32 from vector<4xf32>
    memref.store %5, %arg0[%c0, %c7] : memref<4x5xf32>
  }
  return
}
```

2023-12-19 16:44 UTC, Hsiangkai commented
For `vector.gather`, we have handled "all set" and "no set" special case in the pattern.
Refer to `mlir/lib/Dialect/Vector/IR/VectorOps.cpp`,

```
class GatherFolder final : public OpRewritePattern<GatherOp> {
public:
  using OpRewritePattern::OpRewritePattern;
  LogicalResult matchAndRewrite(GatherOp gather,
                                PatternRewriter &rewriter) const override {
    switch (getMaskFormat(gather.getMask())) {
    case MaskFormat::AllTrue:
      return failure(); // no unmasked equivalent
    case MaskFormat::AllFalse:
      rewriter.replaceOp(gather, gather.getPassThru());
      return success();
    case MaskFormat::Unknown:
      return failure();
    }
    llvm_unreachable("Unexpected 1DMaskFormat on GatherFolder");
  }
};
```

2023-12-19 16:48 UTC, Hsiangkai commented
In this patch, the special case is continuous 1s, then continuous 0s, e.g., [1, 1, 1, ..., 0, 0].

2023-12-19 16:58 UTC, kuhar commented
> In this patch, the special case is continuous 1s, then continuous 0s, e.g., [1, 1, 1, ..., 0, 0].

I would expect these to fold to constants:
```mlir
  %0 = vector.constant_mask [2] : vector<4xi1>
  %1 = vector.extract %0[0] : i1 from vector<4xi1>
```

Instead of working around this in the `VectorMaskedLoadOpConverter`/`VectorMaskedStoreOpConverter`, can we add the missing folds, or am I missing something here?

2023-12-19 17:00 UTC, kuhar requested changes
Adding a blocking review so that I don't forget about this

2023-12-19 17:01 UTC, Hsiangkai commented
> > In this patch, the special case is continuous 1s, then continuous 0s, e.g., [1, 1, 1, ..., 0, 0].
> 
> I would expect these to fold to constants:
> 
> ```mlir
>   %0 = vector.constant_mask [2] : vector<4xi1>
>   %1 = vector.extract %0[0] : i1 from vector<4xi1>
> ```
> 
> Instead of working around this in the `VectorMaskedLoadOpConverter`/`VectorMaskedStoreOpConverter`, can we add the missing folds, or am I missing something here?

Even we add the missing constant folds, use vector.load + vector.insert_strided_slice is more efficient than multiple scalar memref.load, isn't it?

2023-12-19 17:59 UTC, kuhar commented
So what I suggest is to handle 3 cases for the mask:
- All ones --> generate an unmasked load/store. This should be done for the folders for `vector.maskedload`/`maskedstore`. 
- All zeros --> get the passthrough. This should be done for the folders for `vector.maskedload`/`maskedstore`.
- Everything else --> lower as-is and rely on the folders to simplify any known zero/one bits. Fix the other folders as necessary (`vector.create_mask`, `vector.extract` from mask.

2024-01-16 01:40 UTC, dcaballe commented
+1 to what @kuhar suggested. I think the only missing pattern is to fold:
```
  %0 = vector.constant_mask [2] : vector<4xi1>
  %1 = vector.extract %0[0] : i1 from vector<4xi1>
```
into the specific constant value:
```
  %0 = arith.constant 1 : i1
```

The rest of the folding that you are looking for should happen automatically after that.

2024-01-17 08:54 UTC, Hsiangkai commented
> +1 to what @kuhar suggested. I think the only missing pattern is to fold:
> 
> ```
>   %0 = vector.constant_mask [2] : vector<4xi1>
>   %1 = vector.extract %0[0] : i1 from vector<4xi1>
> ```
> 
> into the specific constant value:
> 
> ```
>   %0 = arith.constant 1 : i1
> ```
> 
> The rest of the folding that you are looking for should happen automatically after that.

Thanks for your comments. I will work on the missing fold pattern.

2024-02-07 23:48 UTC, Hsiangkai commented
Create another PR for rewriting ExtractOp(ConstantMaskOp) https://github.com/llvm/llvm-project/pull/81057

2024-02-07 23:48 UTC, closed without merging