[MC][x86] Fix missing check in MC binary expression
llvm/llvm-project pull request #75693
Opened 2023-12-16 08:41 UTC by cygao90

This fixes #73109.
In instruction `addl %eax %rax`, because there is a missing comma in the middle of two registers, the asm parser will treat it as a binary expression.
```
%rax  %  rax --> register mod identifier
```
However, In `MCExpr::evaluateAsRelocatableImpl`, it only checks the left side of the expression. This patch ensures the right side will also be checked.

2023-12-16 10:09 UTC, phoebewang commented
Thanks for the fix! I think it would be a typo when added the code in https://github.com/llvm/llvm-project/commit/7fd992a75502b7eb251daa1b1e4d23a73fa76d53
But I'd like to invite @rnk to double confirm it.

2023-12-16 10:37 UTC, phoebewang requested changes
I found a problem when built it locally:

```
$ echo 'setb %al %rbx' | llvm-mc --show-encoding
        .text
        setb    (%al)%rbx                       # encoding: [0x0f,0x92,0x04,0x25,A,A,A,A]
                                        #   fixup A - offset: 4, value: (%al)%rbx, kind: reloc_signed_4byte
```

In this case, `%rbx` is taken as a relocation, which is incorrect.
I think the `cast` is intended here. What we should do is to make it user friendly by emitting an error with message. But it seems not easy to do here.

2023-12-16 15:59 UTC, cygao90 commented
@phoebewang Thank you for your review. I tested on gcc. gcc will also accept such instruction:
https://godbolt.org/z/er5zEhThY
but assembler will reject it:
https://godbolt.org/z/4EnPq7rjq
Perhaps we should leave it to llvm assembler
```
echo 'setb %al %rbx' | ./llvm-mc --filetype=obj -o test
<stdin>:1:1: error: expected relocatable expression
setb %al %rbx
^
```

2023-12-16 17:54 UTC, MaskRay commented
I fixed `MCBinaryExpr::NE` and extended `llvm/test/MC/X86/register-assignment.s`, but did not think much about non-MCTargetExpr `RHS`.

I think this patch is correct but we need a test to `llvm/test/MC/X86/register-assignment.s`. It can be `.if var_cata == 1 ...`

2023-12-17 01:04 UTC, phoebewang approved these changes
Makes sense to me, please address @MaskRay 's comments.

2023-12-17 10:23 UTC, cygao90 commented
I don't know why this check failed...

2023-12-17 10:49 UTC, phoebewang commented
Check fail occurs sometimes for other reasons like infrastructure issue or problem in recent merged patches. You just need to take a look at the failed tests and ignore it if they are unrelated to your change.

2023-12-17 11:20 UTC, cygao90 commented
```
--
  | MLIR :: python/dialects/affine.py
  | MLIR :: python/dialects/amdgpu.py
  | MLIR :: python/dialects/arith_dialect.py
  | MLIR :: python/dialects/builtin.py
  | MLIR :: python/dialects/cf.py
  | MLIR :: python/dialects/complex_dialect.py
  | MLIR :: python/dialects/func.py
  | MLIR :: python/dialects/linalg/opdsl/arguments.py
  | MLIR :: python/dialects/linalg/opdsl/assignments.py
  | MLIR :: python/dialects/linalg/opdsl/doctests.py
  | MLIR :: python/dialects/linalg/opdsl/emit_convolution.py
  | MLIR :: python/dialects/linalg/opdsl/emit_fill.py
  | MLIR :: python/dialects/linalg/opdsl/emit_matmul.py
  | MLIR :: python/dialects/linalg/opdsl/emit_misc.py
  | MLIR :: python/dialects/linalg/opdsl/emit_pooling.py
  | MLIR :: python/dialects/linalg/opdsl/metadata.py
  | MLIR :: python/dialects/linalg/opdsl/shape_maps_iteration.py
  | MLIR :: python/dialects/linalg/opdsl/test_core_named_ops.py
  | MLIR :: python/dialects/linalg/ops.py
  | MLIR :: python/dialects/math_dialect.py
  | MLIR :: python/dialects/memref.py
  | MLIR :: python/dialects/ml_program.py
  | MLIR :: python/dialects/nvgpu.py
  | MLIR :: python/dialects/nvvm.py
  | MLIR :: python/dialects/ods_helpers.py
  | MLIR :: python/dialects/pdl_ops.py
  | MLIR :: python/dialects/python_test.py
  | MLIR :: python/dialects/quant.py
  | MLIR :: python/dialects/scf.py
  | MLIR :: python/dialects/shape.py
  | MLIR :: python/dialects/tensor.py
  | MLIR :: python/dialects/transform.py
  | MLIR :: python/dialects/transform_bufferization_ext.py
  | MLIR :: python/dialects/transform_structured_ext.py
  | MLIR :: python/dialects/vector.py
  | MLIR :: python/ir/array_attributes.py
  | MLIR :: python/ir/attributes.py
  | MLIR :: python/ir/blocks.py
  | MLIR :: python/ir/builtin_types.py
  | MLIR :: python/ir/diagnostic_handler.py
  | MLIR :: python/ir/dialects.py
  | MLIR :: python/ir/location.py
  | MLIR :: python/ir/operation.py
  | MLIR :: python/ir/symbol_table.py
  | MLIR :: python/ir/value.py
  | MLIR :: python/pass_manager.py
```
Seems unrelated.

2023-12-18 03:06 UTC, KanRobert commented on llvm/test/MC/X86/register-assignment-error.s
> +// RUN: not llvm-mc -triple x86_64-unknown-unknown %s -o /dev/null 2>&1 | FileCheck %s --check-prefix=CHECK-ERROR
Minor suggestion

You don't need `-unknown-unknown`, `x86_64` is enough. Ony one check prefix is used, `--check-prefix=CHECK-ERROR` is redundant.

2023-12-18 04:15 UTC, KanRobert approved these changes

2023-12-20 08:03 UTC, cygao90 commented
Can someone with write access merge this PR if no further change is required? Thanks.

2023-12-20 08:43 UTC, merged

2023-12-29 03:46 UTC, MaskRay commented
> Can someone with write access merge this PR if no further change is required? Thanks.

We should add a test `.ifdef 1 == var_xdata` as well and ensure there is an EOL at the end of the file. I merged the new test file into `register-assignment.s` in a22c8efad733cf3407a93387a6a9c743659dc74c.