[clang][CodeGen] Always use CLANG_VENDOR as a quoted string
llvm/llvm-project pull request #75935
Opened 2023-12-19 14:16 UTC by DimitryAndric

In 9a38a72f1d482 `ProductId` was assigned from the stringified value of `CLANG_VENDOR`, if that macro was defined. However, `CLANG_VENDOR` is supposed to be a string, as it is defined (optionally) as such in the top-level clang `CMakeLists.txt`.

Move the addition of `-DCLANG_VENDOR` to the compiler flags from `clang/lib/Basic/CMakeLists.txt` to the top-level `CMakeLists.txt`, so it is consistent across the whole clang codebase. Then remove the stringification from `CodeGenModule.cpp`, to make it work correctly.

Fixes:		9a38a72f1d482

2023-12-19 19:40 UTC, smeenai requested changes
IIRC, applying definitions like this only to a small set of files was an intentional decision, to minimize rebuilding when their values changed. It matters much more for the commit hash than the vendor, but passing defines like this to every single compilation in Clang is ugly IMO. Can we instead add a function to Version.cpp to access the vendor (so that the correct type gets encoded in the function signature) and use that from CodeGenModule.cpp instead of referencing `CLANG_VENDOR` directly?

2023-12-19 20:14 UTC, ysyeda approved these changes
LGTM, thanks

2023-12-19 21:17 UTC, petrhosek requested changes
I agree with @smeenai, we shouldn't be setting `CLANG_VENDOR` as a global define.

2023-12-20 12:53 UTC, DimitryAndric commented on clang/lib/CodeGen/CodeGenModule.cpp
> +    std::string ProductId = getClangVendor() + "clang";
Note that this is the way you are supposed to get a "product-id-with-vendor", as the vendor tag itself normally does not contain the word "clang". For example, FreeBSD uses "FreeBSD " (so with a trailing space), and Apple uses "Apple " (also with trailing space). If any space is desired between the vendor tag and the word "clang", it has to be specified in the vendor tag, and not appended here in the string concatenation.

2023-12-20 18:06 UTC, smeenai approved these changes
LGTM, thanks!

2023-12-20 19:03 UTC, merged