[CodeGen] Don't codegen the weak function when there is a defined non-weak symbol
llvm/llvm-project pull request #76040
Opened 2023-12-20 11:01 UTC by DianQK

When there is an IR with inline asm modules and another with a weak function, LTO can lead to multiple symbol definition issue. The weak function can be correctly discarded without using LTO.
I found that the LLVM IR can't understand the asm content and can only handle it in codegen.
Currently I've only solved the weak function under ELF.

2023-12-20 21:06 UTC, MaskRay requested changes
(I'll be out for 2 weeks and my response time will be very slow.)

Can you describe your case using concrete commands?
We already have `.lto_discard` to handle non-prevailing symbols.

I am also concerned of adding `IsWeak` to MCSymbol, which makes the representation less orthogonal.

2023-12-21 01:40 UTC, DianQK commented
> Can you describe your case using concrete commands? We already have `.lto_discard` to handle non-prevailing symbols.

The concrete usage case is to override the default builtin functions in rust. Currently rust adds builtin functions to LTO.

An example might be as follows:
```rust
#![no_std]
#![no_main]

use core::panic::PanicInfo;

#[panic_handler]
fn panic(_info: &PanicInfo) -> ! {
    loop {}
}

core::arch::global_asm!(
    ".global __aeabi_uidivmod",
    ".type __aeabi_uidivmod, %function",
    "__aeabi_uidivmod:",
    "str    r0, [r2, #0x060]",
    "str    r1, [r2, #0x064]",
);
```

Then run `rustc -Clto --target=thumbv6m-none-eabi`. This requires many other settings, such as setting the `weak-intrinsics`. (I should be able to make an example for x86_64 if needed.)

This will probably get `user.ll` and `builtin.ll`.

```llvm
target datalayout = "e-m:e-p:32:32-Fi8-i64:64-v128:64:128-a:0:32-n32-S64"
target triple = "thumbv6m-none-unknown-eabi"

module asm ".global __aeabi_uidivmod"
module asm ".type __aeabi_uidivmod, %function"
module asm "__aeabi_uidivmod:"
module asm "str    r0, [r2, #0x060]"
module asm "str    r1, [r2, #0x064]"
```

```llvm
target datalayout = "e-m:e-p:32:32-Fi8-i64:64-v128:64:128-a:0:32-n32-S64"
target triple = "thumbv6m-none-unknown-eabi"

; Function Attrs: naked nocf_check noinline nounwind
define weak hidden void @__aeabi_uidivmod() unnamed_addr {
  tail call void asm sideeffect alignstack "push {lr}\0Asub sp, sp, #4\0Amov r2, sp\0Abl __udivmodsi4\0Aldr r1, [sp]\0Aadd sp, sp, #4\0Apop {pc}", "~{cc},~{memory}"()
  unreachable
}
```

Then run with `llvm-link user.ll builtin.ll -S -o out.ll` and `llc out.ll`.

Looking at `.lto_discard` related code, this could be useful or something similar. I will look into it. Thanks.

2023-12-22 01:06 UTC, DianQK commented
From https://github.com/llvm/llvm-project/blob/7c3b67d2038cfb48a80299089f6a1308eee1df7f/llvm/include/llvm/Object/ModuleSymbolTable.h#L52-L59, I can handle it at LTO.
This is the better approach for me. Marked as a draft as I am preparing a new PR.

It seems that `.lto_discard` can be used to handle the presence of a weak and a global symbol in the inline asm. But I want to drop the weak function defined in IR.

2023-12-24 11:17 UTC, DianQK commented
Alternative #76287.

I also found a way I could solve this issue by writing symbol resolution. This is similar to the `llvm-lto2` command.

2023-12-28 00:40 UTC, DianQK commented
I prefer https://github.com/llvm/llvm-project/pull/76287 or https://github.com/rust-lang/rust/pull/119348.

2023-12-28 00:40 UTC, closed without merging