[libc++] make std::atomic works with types with paddings
llvm/llvm-project pull request #76180
Opened 2023-12-21 20:31 UTC by huixie90

2023-12-22 19:25 UTC, mordante reviewed
I mainly glossed over the patch since it's still a draft.

2023-12-22 19:25 UTC, mordante commented on libcxx/include/__atomic/cxx_atomic_impl.h
> +      !__has_unique_object_representations(_Tp) && !is_same<_Tp, float>::value && !is_same<_Tp, double>::value;
Is it guaranteed `float` and `double` never have padding. Wouldn't it be better to have a builtin that tells whether padding should be removed? Or even make the builtin a no-op when it's not needed for the type.

2023-12-22 19:25 UTC, mordante commented on libcxx/include/__atomic/cxx_atomic_impl.h
> +    if (!__builtin_is_constant_evaluated()) {
why not `std::is_constant_evaluated`?

2024-01-19 17:27 UTC, ldionne commented on libcxx/include/__atomic/cxx_atomic_impl.h
> +  _Tp __expected_copy = *__expected;
We should have a test that fails if you forget to make a copy here. This would require a situation where we clear the padding bits of `__expected`.

2026-06-18 15:28 UTC, ldionne commented on libcxx/test/std/atomics/atomics.types.generic/padding.pass.cpp
> +#else // !__has_builtin(__builtin_clear_padding)
I think it would make more sense to make this XFAIL on compilers that don't provide the builtin.

2026-06-19 18:20 UTC, ldionne commented
CC @jiixyj in case you're interested to help review this

2026-06-21 13:23 UTC, huixie90 commented on libcxx/test/std/atomics/atomics.types.generic/padding.pass.cpp
> +#else // !__has_builtin(__builtin_clear_padding)
hmm since the builtin was just merged in clang, I don't find a reliable way to XFAIL. if we XFAIL clang-23, the in-tree clang will not fail and fail the test. any suggestions?

2026-07-03 18:28 UTC, ldionne requested changes
I'm glad to see this making progress! This is a non-trivial patch, I have some comments but it's looking very reasonable.

2026-07-03 18:28 UTC, ldionne commented on libcxx/test/std/atomics/atomics.types.generic/padding.pass.cpp
> +// UNSUPPORTED: c++03, c++11, c++14, c++17
Missing synopsis. Please also add a short comment explaining what this test is about.

2026-07-03 18:28 UTC, ldionne commented on libcxx/test/std/atomics/atomics.types.generic/padding.pass.cpp
> +struct Foo {
I think it would make sense to have at least a few different types being tested here. For example, with padding between two members. To make your life easier, perhaps keep limit it to two members:

```
struct Bar {
  char c;
  int i;
};
```

That's not a crazy increase in coverage, but it's a bit better, and it allows making the test at least somewhat generic.

2026-07-03 18:28 UTC, ldionne commented on libcxx/test/std/atomics/atomics.types.generic/padding.pass.cpp
> +void assert_foo_padding(const Foo& f, unsigned char pad_byte) {
You can provide overloads of this function for `Foo` and `Bar` that do the same kind of check, but does them differently.

2026-07-03 18:28 UTC, ldionne commented on libcxx/test/std/atomics/atomics.types.generic/padding.pass.cpp
> +void test_default_constructor() {
I would like to suggest using nested scopes inside a templated `test<Foo|Bar>` function directly, with plain english comments explaining what each test case is doing.

2026-07-03 18:28 UTC, ldionne commented on libcxx/test/std/atomics/atomics.types.generic/padding.pass.cpp
> +  std::memcpy(original_expected, &expected, sizeof(Foo));
```suggestion
Foo original_expected; // make a copy including padding bits
std::memcpy(&original_expected, expected, sizeof(Foo));
```

Would that work too?

2026-07-03 18:28 UTC, ldionne commented on libcxx/test/std/atomics/atomics.types.generic/padding.pass.cpp
> +  assert_foo_padding(expected, 0);
Why is the padding `0` here? I think this should be a libc++ specific test, but also a comment would be useful.

2026-07-03 18:28 UTC, ldionne commented on libcxx/test/std/atomics/atomics.types.generic/padding.pass.cpp
> +}
Your comment: you should probably add a test case where expected and the atomic are the same, including their padding.

2026-07-03 18:28 UTC, ldionne commented on libcxx/test/std/atomics/atomics.types.generic/padding.pass.cpp
> +    assert(std::chrono::steady_clock::now() < deadline && "compare_exchange_weak did not succeed within 3 seconds");
I would suggest that we instead assert that we succeeded within N attempts, with e.g. N = 100. That removes the "timing" aspect of this, which is very brittle given some of our platforms run on emulators, etc.

Technically this test is still flaky but I think it's difficult to do better.

2026-07-03 18:28 UTC, ldionne commented on libcxx/test/std/atomics/atomics.types.generic/padding.pass.cpp
> +#else // !__has_builtin(__builtin_clear_padding)
Let's use your current approach but leave a `// TODO(LLVM-23): Switch to XFAIL: clang-22`. We prefer tracking test failures using Lit annotations for consistency, and because the test runner surfaces those explicitly.

2026-07-03 18:28 UTC, ldionne commented on libcxx/include/__atomic/support/c11.h
>  #define _LIBCPP___ATOMIC_SUPPORT_C11_H
Open question: Should we implement this paper as a DR? In a certain way, this can be seen as a bug fix against the fact that `atomic<TypeWithPading>::compare_exhange` is broken before C++20. I'd be okay either way (DR or not), but as a non power user of atomics, CAS being broken for `atomic<TypeWithPadding>` is definitely not something that jumps at me as being obvious, hence the "bug report" categorization I am suggesting.

CC @frederick-vs-ja 

Also CC @jwakely and @StephanTLavavej : have you folks implemented this? If so, did you DR?

2026-07-03 18:28 UTC, ldionne commented on libcxx/include/__atomic/support/c11.h
> +#  if _LIBCPP_STD_VER >= 20 && __has_builtin(__builtin_clear_padding)
This `#if` is going to hinge on the DR question.

2026-07-03 18:28 UTC, ldionne commented on libcxx/include/__atomic/support/c11.h
> +  return __atomic_cas_with_clear_padding(
```suggestion
  return std::__atomic_cas_with_clear_padding(
```

Also below?

2026-07-03 18:28 UTC, ldionne commented on libcxx/include/__atomic/support/common.h
> +_LIBCPP_HIDE_FROM_ABI bool __atomic_cas_with_clear_padding(_Tp* __expected, _Up&& __value, _CasFunc&& __cas_func) {
```suggestion
_LIBCPP_HIDE_FROM_ABI bool __atomic_cas_with_clear_padding(_Tp* __expected, _Up __value, _CasFunc&& __cas_func) {
```

I would suggest taking by value here. That makes it easier to understand since you're clearing the padding below (otherwise we have to know that the caller of this function already made a copy that they are about to discard, which requires non local reasoning). I suspect it doesn't make a difference in the codegen since they are small functions and are probably inlined anyway.

2026-07-03 18:28 UTC, ldionne commented on libcxx/include/__atomic/support/common.h
> +constexpr
You can use `_LIBCPP_CONSTEXPR_SINCE_CXX14` for this.

2026-07-03 18:28 UTC, ldionne commented on libcxx/include/__atomic/support/common.h
> +_LIBCPP_HIDE_FROM_ABI constexpr void __clear_padding_if_needed(_Tp&& __obj) noexcept {
I would suggest taking a simple lvalue reference here, since this is totally an out-parameter.

2026-07-03 18:28 UTC, ldionne commented on libcxx/include/__atomic/support/common.h
> +#ifndef _LIBCPP___ATOMIC_SUPPORT_COMMON_H
I think I would rather leave this header outside of `__atomic/support`: `__atomic/support` is intended purely for the platform-specific API. Since this isn't that, I'd suggest e.g. `__atomic/clear_padding.h` or anything else that makes sense, just not nested under `/support`.

2026-07-03 18:28 UTC, ldionne commented on libcxx/include/__atomic/support/gcc.h
> +  _LIBCPP_CONSTEXPR explicit __cxx_atomic_base_impl(_Tp __value) _NOEXCEPT : __a_value(__value) {
Another option here would be `_LIBCPP_CONSTEXPR_SINCE_CXX14`. Does anything break if we make this type non-constexpr-friendly in C++11?

2026-07-10 18:09 UTC, ldionne approved these changes
LGTM assuming the C++11-ifying works with GCC.

2026-07-10 18:09 UTC, ldionne commented on libcxx/include/__atomic/clear_padding.h
> +  // return __obj as c++11 does not constexpr function to return void
I don't think this comment is necessary.

2026-07-10 18:09 UTC, ldionne commented on libcxx/include/__atomic/clear_padding.h
> +  // return __obj as c++11 does not constexpr function to return void
Same here, I'd remove the comment.

2026-07-10 18:09 UTC, ldionne commented on libcxx/test/libcxx/atomics/atomics.types.generic/padding.pass.cpp
> +// TODO(LLVM-23): Switch to X_F_A_I_L: clang-22
```suggestion
// TODO(LLVM-23): Switch to XFAIL with clang-22
```

2026-07-10 18:09 UTC, ldionne commented on libcxx/test/std/atomics/atomics.types.generic/padding.pass.cpp
> +// TODO(LLVM-23): Switch to X_F_A_I_L: clang-22
```suggestion
// TODO(LLVM-23): Switch to XFAIL with clang-22
```

2026-07-10 18:09 UTC, ldionne commented on libcxx/include/__atomic/clear_padding.h
> +_LIBCPP_HIDE_FROM_ABI _LIBCPP_CONSTEXPR _Tp& __clear_padding_if_needed(_Tp& __obj) noexcept {
To get rid of the `if constexpr`, you could use SFINAE instead. You'll get two bodies:

```c++
{
  return __obj;
}
```

which is clearly constexpr-friendly, and

```c++
{
  return __builtin_is_constant_evaluated() ? __obj : __builtin_clear_padding(std::addressof(__obj)), __obj;
}
```

which should also be constexpr friendly and work on GCC / C++11.

Note that we did discuss the possibility of simply not supporting this in C++11. However, if we decide to DR this paper, it's that we basically consider it to be a bug. And if we consider it to be a bug, then we should strive to fix that bug in all standard modes, not skip C++11 because the code looks ugly.

If we decide (with other implementers, see https://github.com/llvm/llvm-project/pull/76180/changes#r3521358580) that we don't DR this, then we could go back to the previous implementation which doesn't need to work in C++11 on GCC.

2026-07-24 08:01 UTC, huixie90 commented
I am a bit struggling that the codegen seems to be much worse in some cases.  For example,
https://godbolt.org/z/9K35c36eq
- If I don't capture `success` memory order in the lambda, everything is nicely inlined
- as long as I capture the `success` memory order, it will generate all combination of the memory order in CAS and a switch statement to select the right one. and lambda can no longer inlined due to this complexity

2026-07-24 18:14 UTC, ldionne commented on libcxx/test/libcxx/atomics/atomics.types.generic/padding.pass.cpp
> +//===----------------------------------------------------------------------===//
In `libcxx/test/libcxx/atomics/builtin_clear_padding.pass.cpp`, can we change that test to use `std::__clear_padding_if_needed` instead? That would make the test actually exercise libc++ code instead of a pure builtin.

2026-07-24 18:14 UTC, ldionne commented on libcxx/include/__atomic/support/gcc.h
> +            __to_gcc_order(__success),
I think you should qualify these calls?

2026-07-24 18:14 UTC, ldionne commented on libcxx/test/libcxx/atomics/atomics.types.generic/padding.pass.cpp
> +// XFAIL: clang-21, apple-clang-21, clang-22
Perhaps add a short comment like

```
// Older Clang doesn't implement __builtin_clear_padding
```

2026-07-24 18:14 UTC, ldionne commented on libcxx/test/libcxx/atomics/atomics.types.generic/padding.pass.cpp
> +    // atomic();
Please add a short comment explaining why this is disabled before C++20 (atomic is uninitialized, so padding is not guaranteed zero).

2026-07-24 18:14 UTC, ldionne commented on libcxx/test/std/atomics/atomics.types.generic/padding.pass.cpp
> +    libcpp_assert_padding(expected, 0);
I would suggest that you replace this by explicit

```
#ifdef _LIBCPP_VERSION
assert_padding(expected, 0);
#endif
```

instead. I think it's easier to spot that this is libc++ specific and we use that pattern elsewhere: I don't think we often define a function like `libcpp_assert_whatever`.

2026-07-24 18:14 UTC, ldionne commented on libcxx/include/__atomic/support/c11.h
> +      __expected, __value, [__a, __success, __failure](_Tp* __expected_or_copy, _Tp __value_maybe_padding_cleared) {
> I am a bit struggling that the codegen seems to be much worse in some cases. For example,
https://godbolt.org/z/9K35c36eq

Based on https://godbolt.org/z/snx1csxTr, I think you could throw `_LIBCPP_ALWAYS_INLINE` on the lambda to solve that problem. You should add a short comment though.

2026-07-24 18:14 UTC, ldionne commented on libcxx/test/std/atomics/atomics.types.generic/padding.pass.cpp
> +//===----------------------------------------------------------------------===//
For the CI failure in https://github.com/llvm/llvm-project/actions/runs/30073453650/job/89425778135?pr=76180, I would try to add `-pthread` to https://github.com/llvm/llvm-project/blob/e200ea609b9292ab7bfe5c0eb67a6e4cea5677cc/libcxx/test/configs/llvm-libc%2B%2B-llvm-libc.cfg.in#L11

However, I am not 100% certain about that fix, I'd like @llvm/reviewers-libc to chime in.

TLDR for libc folks: it looks like this added test ends up using non-lockfree atomics, and that fails to link on the LLVM libc configuration.

2026-07-27 16:37 UTC, ldionne approved these changes
LGTM with minor comments!

2026-07-27 16:37 UTC, ldionne commented on libcxx/utils/libcxx/test/features/misc.py
> +        for x in [64, 128, 1024]
```suggestion
        for n in [64, 128, 1024]
```

Otherwise this is somewhat confusing with the existing `x` variable!

2026-07-27 16:37 UTC, ldionne commented on libcxx/include/__atomic/support/c11.h
> +      // clang fails to inline the lambda when the memory order is a constant
```suggestion
      // Use always_inline since Clang fails to inline the lambda, even when the memory order is a constant
```

2026-07-27 18:21 UTC, ldionne commented on libcxx/test/libcxx/atomics/clear_padding.pass.cpp
>      __builtin_clear_padding(&s2);
Why is this not `__clear_padding_if_needed`?

2026-07-27 18:21 UTC, ldionne commented on libcxx/test/libcxx/atomics/builtin_clear_padding.pass.cpp
Let's rename the file to reflect the function it's testing now.

2026-07-27 18:22 UTC, ldionne approved these changes
LGTM

2026-07-27 18:22 UTC, ldionne commented on libcxx/test/libcxx/atomics/clear_padding.pass.cpp
>      __builtin_clear_padding(&s2);
Nevermind, I didn't read the comment above carefully enough.

2026-07-27 22:25 UTC, ldionne approved these changes

2026-07-28 06:15 UTC, merged

2026-07-28 07:33 UTC, philnik777 commented on libcxx/include/__atomic/support/c11.h
> +      [__a, __success, __failure](_Tp* __expected_or_copy, _Tp __value_maybe_padding_cleared) _LIBCPP_ALWAYS_INLINE {
Why is this marked with `_LIBCPP_ALWAYS_INLINE`?

Edit: Sorry, missed the comment above.

2026-07-28 09:39 UTC, huixie90 commented on libcxx/include/__atomic/support/c11.h
> +      [__a, __success, __failure](_Tp* __expected_or_copy, _Tp __value_maybe_padding_cleared) _LIBCPP_ALWAYS_INLINE {
Ah Ok. Let me know if the comment is unclear. The detailed discussion is here https://github.com/llvm/llvm-project/pull/76180#discussion_r3647291757

2026-08-19 10:07 UTC, mgorny commented
The added test crashes on 32-bit x86:

```
FAIL: llvm-libc++-shared.cfg.in :: libcxx/atomics/clear_padding.pass.cpp (2072 of 11569)
******************** TEST 'llvm-libc++-shared.cfg.in :: libcxx/atomics/clear_padding.pass.cpp' FAILED ********************
Exit Code: 250

Command Output (stdout):
--
# COMPILED WITH
/usr/lib/ccache/bin/i686-pc-linux-gnu-clang++-24 /var/tmp/portage/llvm-runtimes/libcxx-24.0.0.9999/work/libcxx/test/libcxx/atomics/clea
r_padding.pass.cpp -pthread --target=i686-pc-linux-gnu -nostdinc++ -I /var/tmp/portage/llvm-runtimes/libcxx-24.0.0.9999/work/runtimes_b
uild-abi_x86_32.x86/libcxx/test-suite-install/include/c++/v1 -I /var/tmp/portage/llvm-runtimes/libcxx-24.0.0.9999/work/runtimes_build-a
bi_x86_32.x86/libcxx/test-suite-install/include/c++/v1 -I /var/tmp/portage/llvm-runtimes/libcxx-24.0.0.9999/work/libcxx/test/support -s
td=c++26 -Wall -Wctad-maybe-unsupported -Wextra -Wshadow -Wundef -Wunused-template -Wno-unused-command-line-argument -Wno-attributes -W
no-pessimizing-move -Wno-noexcept-type -Wno-atomic-alignment -Wno-reserved-module-identifier -Wdeprecated-copy -Wdeprecated-copy-dtor -
Wshift-negative-value -Wno-user-defined-literals -Wno-tautological-compare -Wno-stringop-overread -Wsign-compare -Wunused-variable -Wun
used-parameter -Wunreachable-code -Wno-unused-local-typedef -Wno-local-type-template-args -Wno-c++11-extensions -Wno-unknown-pragmas -W
no-pass-failed -Wno-mismatched-new-delete -Wno-redundant-move -Wno-self-move -Wno-nullability-completeness -flax-vector-conversions=non
e -D_LIBCPP_HAS_NO_PRAGMA_SYSTEM_HEADER -Werror -D_LIBCPP_ENABLE_EXPERIMENTAL -Wuser-defined-warnings -Wno-deprecated-volatile -Wno-dyn
amic-class-memaccess -lc++experimental -nostdlib++ -L /var/tmp/portage/llvm-runtimes/libcxx-24.0.0.9999/work/runtimes_build-abi_x86_32.
x86/libcxx/test-suite-install/lib -Wl,-rpath,/var/tmp/portage/llvm-runtimes/libcxx-24.0.0.9999/work/runtimes_build-abi_x86_32.x86/libcx
x/test-suite-install/lib -lc++ -latomic -o /var/tmp/portage/llvm-runtimes/libcxx-24.0.0.9999/work/runtimes_build-abi_x86_32.x86/libcxx/
test/libcxx/atomics/Output/clear_padding.pass.cpp.dir/t.tmp.exe
# executed command: /usr/lib/ccache/bin/i686-pc-linux-gnu-clang++-24 /var/tmp/portage/llvm-runtimes/libcxx-24.0.0.9999/work/libcxx/test
/libcxx/atomics/clear_padding.pass.cpp -pthread --target=i686-pc-linux-gnu -nostdinc++ -I /var/tmp/portage/llvm-runtimes/libcxx-24.0.0.
9999/work/runtimes_build-abi_x86_32.x86/libcxx/test-suite-install/include/c++/v1 -I /var/tmp/portage/llvm-runtimes/libcxx-24.0.0.9999/w
ork/runtimes_build-abi_x86_32.x86/libcxx/test-suite-install/include/c++/v1 -I /var/tmp/portage/llvm-runtimes/libcxx-24.0.0.9999/work/li
bcxx/test/support -std=c++26 -Wall -Wctad-maybe-unsupported -Wextra -Wshadow -Wundef -Wunused-template -Wno-unused-command-line-argumen
t -Wno-attributes -Wno-pessimizing-move -Wno-noexcept-type -Wno-atomic-alignment -Wno-reserved-module-identifier -Wdeprecated-copy -Wde
precated-copy-dtor -Wshift-negative-value -Wno-user-defined-literals -Wno-tautological-compare -Wno-stringop-overread -Wsign-compare -W
unused-variable -Wunused-parameter -Wunreachable-code -Wno-unused-local-typedef -Wno-local-type-template-args -Wno-c++11-extensions -Wn
o-unknown-pragmas -Wno-pass-failed -Wno-mismatched-new-delete -Wno-redundant-move -Wno-self-move -Wno-nullability-completeness -flax-ve
ctor-conversions=none -D_LIBCPP_HAS_NO_PRAGMA_SYSTEM_HEADER -Werror -D_LIBCPP_ENABLE_EXPERIMENTAL -Wuser-defined-warnings -Wno-deprecat
ed-volatile -Wno-dynamic-class-memaccess -lc++experimental -nostdlib++ -L /var/tmp/portage/llvm-runtimes/libcxx-24.0.0.9999/work/runtim
es_build-abi_x86_32.x86/libcxx/test-suite-install/lib -Wl,-rpath,/var/tmp/portage/llvm-runtimes/libcxx-24.0.0.9999/work/runtimes_build-abi_x86_32.x86/libcxx/test-suite-install/lib -lc++ -latomic -o /var/tmp/portage/llvm-runtimes/libcxx-24.0.0.9999/work/runtimes_build-abi_x86_32.x86/libcxx/test/libcxx/atomics/Output/clear_padding.pass.cpp.dir/t.tmp.exe
# EXECUTED AS
/usr/bin/python3.14 /var/tmp/portage/llvm-runtimes/libcxx-24.0.0.9999/work/libcxx/utils/run.py --execdir /var/tmp/portage/llvm-runtimes/libcxx-24.0.0.9999/work/runtimes_build-abi_x86_32.x86/libcxx/test/libcxx/atomics/Output/clear_padding.pass.cpp.dir --  /var/tmp/portage/llvm-runtimes/libcxx-24.0.0.9999/work/runtimes_build-abi_x86_32.x86/libcxx/test/libcxx/atomics/Output/clear_padding.pass.cpp.dir/t.tmp.exe
# executed command: /usr/bin/python3.14 /var/tmp/portage/llvm-runtimes/libcxx-24.0.0.9999/work/libcxx/utils/run.py --execdir /var/tmp/portage/llvm-runtimes/libcxx-24.0.0.9999/work/runtimes_build-abi_x86_32.x86/libcxx/test/libcxx/atomics/Output/clear_padding.pass.cpp.dir -- /var/tmp/portage/llvm-runtimes/libcxx-24.0.0.9999/work/runtimes_build-abi_x86_32.x86/libcxx/test/libcxx/atomics/Output/clear_padding.pass.cpp.dir/t.tmp.exe
# .---command stderr------------
# | *** stack smashing detected ***: terminated
# `-----------------------------
# error: command failed with exit status: 250

--

********************
```

May be a bug in clang, though.

2026-08-19 11:05 UTC, mgorny commented
I was a bit wrong; it fails just the same on amd64 too. Passes on arm64, though.