[ASan][libc++] String annotations optimizations fix with lambda
llvm/llvm-project pull request #76200
Opened 2023-12-22 02:18 UTC by AdvenamTacet

This commit addresses optimization and instrumentation challenges encountered within comma constructors.
  1) _LIBCPP_STRING_INTERNAL_MEMORY_ACCESS does not work in comma constructors.
  2) Code inside comma constructors is not always correctly optimized. Problematic code examples:
        - : __r_(((__str.__is_long() ? 0 : (__str.__annotate_delete(), 0)), std::move(__str.__r_))) {
        - : __r_(__r_([&](){ if(!__s.__is_long()) __s.__annotate_delete(); return std::move(__s.__r_);}())) {

However, lambda with argument seems to be correctly optimized. This patch uses that fact.

Use of lambda based on idea from @ldionne.

2023-12-22 02:26 UTC, AdvenamTacet commented
This does not answer problem of `_LIBCPP_STRING_INTERNAL_MEMORY_ACCESS` not working inside comma constructors and therefore we have additional write to shadow memory while using ASan. That's a small cost, which I think we can ignore.

Alternative is a function like that:
```cpp
  _LIBCPP_HIDE_FROM_ABI _LIBCPP_CONSTEXPR_SINCE_CXX20 _LIBCPP_STRING_INTERNAL_MEMORY_ACCESS
  __compressed_pair<__rep, allocator_type> && __compressed_pair_id(basic_string &__str) {
    if (!__str.__is_long())
      __str.__annotate_delete();
    return std::move(__str.__r_);
  }

```

But I support lambda solution.

2023-12-22 19:17 UTC, ldionne approved these changes
I'm fine with this (with a nitpick about the comment, which I think doesn't add much). This is kind of just a cleaner way to write the same thing as before, so even better if it fixes an optimization problem.

If this were making the code harder to read or more complicated, I'd ask for at least a regression test but in this case we can pretend that it's just a slight "refactoring", even though it is motivated by fixing a regression. It would be good to have some kind of regression test is that's feasible, though.

2023-12-22 19:17 UTC, ldionne commented on libcxx/include/string
> +      // access macro.
IMO this comment doesn't add information we want to retain in the code, and I would remove it. I think this kind of information is best found in the commit message.

2023-12-22 19:18 UTC, ldionne commented
Since this change is motivated by issues reported by @EricWF, I think it would be relevant for Eric to stamp this change as well, to make sure it solves at least some of the problems he was seeing.

2023-12-27 07:40 UTC, AdvenamTacet commented
It also makes the code easier to read. Code inside of the lambda is easy to read, instead of being a hack with comma operator.

2024-01-05 14:38 UTC, EricWF requested changes
LGTM, but I would like to see some actual assembly before and after in the review thread. Could you provide a godbolt or diff of the assembly generated?

I found some other things unrelated to this review while looking at this, which I'll bring up offline.

2024-01-05 18:47 UTC, AdvenamTacet commented
@EricWF the difference is the same as described here: https://github.com/llvm/llvm-project/pull/76192#issuecomment-1867058465
Basically asm goes back to the state from before any string annotations on know to me examples.

I can create dedicated examples to that patch on Monday.

I also see a big benefit in readability.

2024-01-05 19:10 UTC, EricWF approved these changes
Actually I'm happy to generate the examples myself.

You've won me on the readability argument alone.

2024-01-08 17:02 UTC, merged

2024-01-08 21:50 UTC, AdvenamTacet commented
It looks like this PR made a buildbot fail.
https://lab.llvm.org/buildbot/#/builders/37/builds/29650

I'm trying to understand why.