[LTO] Drop the weak function if there is a non-weak global symbol
llvm/llvm-project pull request #76287
Opened 2023-12-23 14:30 UTC by DianQK

Alternative to #76040.

This PR only implements the handling of the weak function.

We should also be able to use `.lto_discard` to handle weak asm symbols. However, we may require additional effort to enhance the maintenance of `.lto_discard`.

2023-12-26 18:04 UTC, teresajohnson requested changes
@cachemeifyoucan since afaict this is specific to users of the legacy LTO interfaces. Hoping you can give some insight into where this is best handled and how it works via ld64.

I don't think the handling should be down in the ModuleLinker. To clarify, this does not appear to be a general LTO issue, but you are changing the module linking used by some of the legacy LTO interfaces (e.g. llvm-lto and llvm-link). The new LTO api used by lld, gold plugin, and llvm-lto2 handle this already (in llvm/lib/LTO/LTO.cpp, we decide which symbols to keep when invoking the IRMover based on prevailing info from the linker, and it also processes the asm symbols in the ModuleSymbolTable).

I also believe this is likely handled ok by ld64 which uses the legacy LTO APIs as well, because the ModuleSymbolTable already contains parsed asm symbols, and it has ways of querying that information.

Looking at the linked earlier alternative PR, it looks like this is to fix rust LTO linking that uses llvm-link directly? Here though the tests use llvm-lto. Is rust using one of these tools or is it interfacing with the module linking directly via LLVM libraries? I'm really not sure where in the legacy LTO this handling should go. Note that llvm-lto already creates an LTOModule that contains a ModuleSymbolTable that already has these asm symbols.

2023-12-26 18:35 UTC, bjorn3 commented
> Is rust using one of these tools or is it interfacing with the module linking directly via LLVM libraries?

Rustc's LLVM backend directly interfaces with libLLVM both for generating the LLVM modules as well as doing LTO. This is necessary for what rustc calls "thin local lto". This is thinLTO, except only applying to a single crate (library/smallest compilation unit) rather than than the linker input. This mode was introduced to allow creating multiple codegen units for a single crate in release mode (to improve build performance) without hurting runtime performance due to not being able to do optimizations across codegen units. Having rustc do LTO using libLLVM is also a lot easier than convincing the linker to use the right libLTO for the LLVM version used by rustc. While for most linkers rustc could ship a matching libLTO, this wouldn't work for lld as far as I understand it, so if the system installation of LLVM is older than rustc (which it is for most users as rustc uses the latest LLVM version while distros generally keep an older one for the entire lifespan of the distro), then you are out of luck. Rustc does support `-Clinker-plugin-lto` to let the linker do LTO just like clang does, but in that case it is your own responsibility to make sure the right libLTO version is used. By setting the right clang version as linker, by passing the path to libLTO as argument to `-Clinker-plugin-lto` or by using the right lld version.

That said for fat LTO I believe we use `llvm::Linker::linkInModule` (https://github.com/rust-lang/rust/blob/e1fadb2c35a6082867a037f012bfdfc5eb686211/compiler/rustc_llvm/llvm-wrapper/Linker.cpp#L44)

For thinLTO it seems we duplicated a fair amount of logic from LLVM: https://github.com/rust-lang/rust/blob/e1fadb2c35a6082867a037f012bfdfc5eb686211/compiler/rustc_llvm/llvm-wrapper/PassWrapper.cpp#L1242-L1355 for the global analysis and then https://github.com/rust-lang/rust/blob/e1fadb2c35a6082867a037f012bfdfc5eb686211/compiler/rustc_codegen_llvm/src/back/lto.rs#L726-L781 for the per-module optimizations. (The last code snippet references some functions named `LLVMRust*`. These are wrappers around the C++ api exposing a C interface. Rust doesn't have native C++ FFI capability.)

2023-12-27 01:27 UTC, DianQK commented
> The new LTO api used by lld, gold plugin, and llvm-lto2 handle this already.

If I understand correctly, the new LTO gives control of symbol resolution to the caller? This way rustc can choose which symbols to use, just like llvm-lto2 or lld.

> Looking at the linked earlier alternative PR, it looks like this is to fix rust LTO linking that uses llvm-link directly? Here though the tests use llvm-lto. Is rust using one of these tools or is it interfacing with the module linking directly via LLVM libraries?

@bjorn3 has provided a detailed explanation. The current behavior is more like the legacy LTO.

> I'm really not sure where in the legacy LTO this handling should go. Note that llvm-lto already creates an LTOModule that contains a ModuleSymbolTable that already has these asm symbols.

So will we continue to maintain the legacy LTO?

2023-12-28 17:47 UTC, cachemeifyoucan commented
@teresajohnson This is `ModuleLinker` that mostly affects FullLTO, rather than thinLTO. I don't remember how `lld` implements fullLTO, is it not using `ModuleLinker` at all?

In the context of fullLTO, `ld64` doesn't really care about weak symbols that has a non-weak def in asm or other definitions. Because every symbol gets pulled into one module, in worst case, LTO codegen is going to produce both weak and non-weak definition and ld64 is going to pick one and dead-strip the other (if codegen can write both into the single output object file, I am not sure what is going to happen there).

In a more general context, apple linker is good at dead-stripping, and it also picks non-weak symbols over weak symbols, so adding such new function in LTO should not affect ld64.

> If I understand correctly, the new LTO gives control of symbol resolution to the caller? This way rustc can choose which symbols to use, just like llvm-lto2 or lld. I tried it at https://github.com/rust-lang/rust/pull/119348.

If rust compiler has idea of which symbol to use, using IRMover is probably better since it gives you much better control of the behavior, rather than rely on a single builtin behavior in ModuleLinker.

> So will we continue to maintain the legacy LTO?

While it is not required to implement new features that are available in new LTO interface in legacy LTO interface, please don't break legacy LTO since we still have users of them.

2024-01-23 05:07 UTC, DianQK commented
The associated PR has been reverted in https://github.com/rust-lang/rust/pull/119885.

2024-01-23 05:07 UTC, closed without merging

2024-01-23 21:40 UTC, DianQK commented
> > @teresajohnson This is `ModuleLinker` that mostly affects FullLTO, rather than thinLTO. I don't remember how `lld` implements fullLTO, is it not using `ModuleLinker` at all?
> 
> Forgot to respond to this question before. Right, lld and other new LTO API users do not use the ModuleLinker, but rather invoke the IRMover [directly](https://github.com/llvm/llvm-project/blob/6ad4ed5f1dd0a8160cd3c7b75e63a0e2f6061b5b/llvm/lib/LTO/LTO.cpp#L991).

Thank you for your response.