[Cygwin] Cygwin X86ISelDAGToDAG.cpp
llvm/llvm-project pull request #76284
Opened 2023-12-23 11:20 UTC by xu-chiheng

Fix the regression caused by commit ec92d74a0ef89b9dd46aee6ec8aca6bfd3c66a54 2023-12-14, that, in Cygwin, Clang can't build binutils 2.42.
configure:4686: checking whether we are cross compiling
configure:4694: clang -o conftest.exe -march=x86-64 -O3  -Wl,--strip-all conftest.c  >&5
/cygdrive/c/Users/ADMINI~1/AppData/Local/Temp/conftest-385c4a.o:conftest.c:(.text+0x10): relocation truncated to fit: IMAGE_REL_AMD64_ADDR32 against `.rdata'
/cygdrive/c/Users/ADMINI~1/AppData/Local/Temp/conftest-385c4a.o:conftest.c:(.text+0x15): relocation truncated to fit: IMAGE_REL_AMD64_ADDR32 against `.rdata'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
configure:4698: $? = 1
configure:4705: ./conftest.exe
../binutils/configure: line 4707: ./conftest.exe: No such file or directory
configure:4709: $? = 127
configure:4716: error: in `/cygdrive/e/Note/Tool/binutils-release-build':
configure:4718: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details

2023-12-23 16:51 UTC, aeubanks commented
do you have a test showing where this broke?

2023-12-31 23:25 UTC, asl requested changes

2023-12-31 23:25 UTC, asl commented on llvm/lib/Target/X86/X86ISelDAGToDAG.cpp
> +  if (Subtarget->isTargetWindowsCygwin() && Subtarget->isTargetWin64()) {
This seems to largely duplicate the generic code below. The only difference is when we've failed to get absolute symbol range for the GV. So, certainly there should not be any code duplication and test / example is required.

2024-01-04 17:04 UTC, aeubanks commented
can you explain what actually the problem is? without further context it looks like we're just blindly pushing workarounds

2024-01-04 17:06 UTC, aeubanks commented
is the configure check is using the medium code model on cygwin? how large is the linked binary in the failing configure check? is it running into relocation overflows?

2024-01-04 23:32 UTC, xu-chiheng commented
> /cygdrive/c/Users/ADMINI~1/AppData/Local/Temp/conftest-385c4a.o:conftest.c:(.text+0x10): relocation truncated to fit: IMAGE_REL_AMD64_ADDR32 against `.rdata' /cygdrive/c/Users/ADMINI~1/AppData/Local/Temp/conftest-385c4a.o:conftest.c:(.text+0x15): relocation truncated to fit: IMAGE_REL_AMD64_ADDR32 against `.rdata'



> can you explain what actually the problem is? without further context it looks like we're just blindly pushing workarounds

/cygdrive/c/Users/ADMINI~1/AppData/Local/Temp/conftest-385c4a.o:conftest.c:(.text+0x10): relocation truncated to fit: IMAGE_REL_AMD64_ADDR32 against .rdata' /cygdrive/c/Users/ADMINI~1/AppData/Local/Temp/conftest-385c4a.o:conftest.c:(.text+0x15): relocation truncated to fit: IMAGE_REL_AMD64_ADDR32 against .rdata'

2024-01-04 23:34 UTC, xu-chiheng commented
> is the configure check is using the medium code model on cygwin? how large is the linked binary in the failing configure check? is it running into relocation overflows?
> 
> providing the configure source file being compiled would be helpful

Yes, Cygwin 64 bit must use medium code model. Otherwise, there are runtime errors.

2024-01-05 11:19 UTC, RKSimon commented
> > is the configure check is using the medium code model on cygwin? how large is the linked binary in the failing configure check? is it running into relocation overflows?
> > providing the configure source file being compiled would be helpful
> 
> Yes, Cygwin 64 bit must use medium code model. Otherwise, there are runtime errors.

In which case we shouldn't be allowing the other code models to be enabled in the first place for cygwin64 triples, not trying to fixup later on - I'm pretty sure we already do this restriction in other cases.

2024-01-05 18:51 UTC, xu-chiheng commented
> > > is the configure check is using the medium code model on cygwin? how large is the linked binary in the failing configure check? is it running into relocation overflows?
> > > providing the configure source file being compiled would be helpful
> > 
> > 
> > Yes, Cygwin 64 bit must use medium code model. Otherwise, there are runtime errors.
> 
> In which case we shouldn't be allowing the other code models to be enabled in the first place for cygwin64 triples, not trying to fixup later on - I'm pretty sure we already do this restriction in other cases.

The Cygwin 64 bit runtime, cygwin1.dll assume the module is compiled as cmodel medium,  so it can load and execute programs.
This assumption is hard coded.  
I'm not very familiar with source code of cygwin1.dll. But my guess is that, cygwin1.dll require specific pattern of symbol table, relocation table, the set of relocation entry kinds, so it can implement fork() using Win32 API.

2024-01-05 19:15 UTC, xu-chiheng commented
> In which case we shouldn't be allowing the other code models to be enabled in the first place for cygwin64 triples, not trying to fixup later on - I'm pretty sure we already do this restriction in other cases.

There should be no restriction, because if a module's code does not call fork(),  the cmodel can be not medium, that's my guess.
MinGW 64 bit default to cmodel small, but can be set to medium.

2024-04-02 06:55 UTC, closed without merging