[emacs][lsp][tblgen] add tblgen-lsp-server support for emacs lsp-mode
llvm/llvm-project pull request #76337
Opened 2023-12-24 15:32 UTC by mgcsysinfcat

2025-01-07 23:46 UTC, keryell requested changes
Thank you very much for doing this!
Since the `tblgen` name of the group is used in the customization UI names as `Lsp Tblgen Server Args` or `Lsp Tblgen Server Executable`, I wonder whether we should not rename any `tblgen` to `tablegen` in this file to be clearer.
Also this file could be renamed to `tblgen-lsp-client.el` to follow `mlir-lsp-client.el`.

2025-01-07 23:46 UTC, keryell commented on mlir/utils/emacs/tblgen-lsp.el
> +;;  LSP clinet to use with `tablegen-mode' that uses `tblgen-lsp-server' or any
```suggestion
;;  LSP client to use with `tablegen-mode' that uses `tblgen-lsp-server' or any
```

2025-01-07 23:46 UTC, keryell commented on mlir/utils/emacs/tblgen-lsp.el
> +    :server-id 'tblgen-lsp-server)))
```suggestion
    :server-id 'tblgen-lsp)))
```
to follow the naming from `mlir-lsp-client.el`

2025-01-07 23:46 UTC, keryell commented on mlir/utils/emacs/tblgen-lsp.el
> +
```suggestion
(require 'lsp-mode)
```
as in `mlir-lsp-client.el`

2025-01-07 23:46 UTC, keryell commented on mlir/utils/emacs/tblgen-lsp.el
> +  "Args of LSP client for TableGen "
```suggestion
  "Args of LSP client for TableGen, for example '--tablegen-compilation-database=.../build/tablegen_compile_commands.yml'"
```

2025-01-07 23:46 UTC, keryell commented on mlir/utils/emacs/tblgen-lsp.el
> +    :new-connection (lsp-stdio-connection (lambda () (cons lsp-tblgen-server-executable lsp-tblgen-server-args))); (concat "--tablegen-compilation-database=" lsp-tblgen-compilation-database-location)
To handle an arbitrary number of argument:
```suggestion
    :new-connection (lsp-stdio-connection (lambda () (cons lsp-tblgen-server-executable (split-string-shell-command lsp-tblgen-server-args))))
```

2025-01-08 19:36 UTC, mgcsysinfcat commented
> Thank you very much for doing this! Since the `tblgen` name of the group is used in the customization UI names as `Lsp Tblgen Server Args` or `Lsp Tblgen Server Executable`, I wonder whether we should not rename any `tblgen` to `tablegen` in this file to be clearer. Also this file could be renamed to `tblgen-lsp-client.el` to follow `mlir-lsp-client.el`.

Thank you for your feedback! It's been a while since I last worked on these, so I hope I didn't overlook anything. I've made the requested changes to the submission.

2025-01-09 20:44 UTC, keryell commented
> Thank you for your feedback! It's been a while since I last worked on these, so I hope I didn't overlook anything. I've made the requested changes to the submission.

I am sorry that nobody gave you feedback before. :frowning_face:
Your file works for me on Ubuntu 24.10 &  GNU Emacs 29.4. :+1:

2025-01-09 20:44 UTC, keryell approved these changes
Almost there.

2025-01-09 20:44 UTC, keryell commented on mlir/utils/emacs/tblgen-lsp-client.el
> +;;; tblgen-lsp.el --- Description -*- lexical-binding: t; -*-
```suggestion
;;; tblgen-lsp-client.el --- Description -*- lexical-binding: t; -*-
```

2025-01-09 20:44 UTC, keryell commented on mlir/utils/emacs/tblgen-lsp-client.el
> +;;; tblgen-lsp.el ends here
```suggestion
;;; tblgen-lsp-client.el ends here
```

2025-01-17 18:14 UTC, keryell commented
@joker-eph could you please look at this, as you contributed `mlir-lsp-client.el`?

2025-01-28 19:26 UTC, merged

2025-01-29 00:09 UTC, keryell commented
@ftynse Thanks!