[InstCombine] Simplify compare abs(X) and X.
llvm/llvm-project pull request #76385
Opened 2023-12-26 07:52 UTC by Z572

fix https://github.com/llvm/llvm-project/issues/72653
proof: https://alive2.llvm.org/ce/z/zPNyUb

2023-12-26 07:55 UTC, dtcxzyw commented
See also #73189.

2023-12-29 12:41 UTC, dtcxzyw requested changes

2023-12-29 12:41 UTC, dtcxzyw commented on llvm/lib/Transforms/InstCombine/InstCombineCompares.cpp
> +        break;
```suggestion
        llvm_unreachable("Invalid predicate!");
```

2023-12-29 12:41 UTC, dtcxzyw commented on llvm/lib/Transforms/InstCombine/InstCombineCompares.cpp
> +  {
Describe the transform in the header comments.

2023-12-29 12:41 UTC, dtcxzyw commented on llvm/lib/Transforms/InstCombine/InstCombineCompares.cpp
> +      auto *MinVal = ConstantInt::get(
```suggestion
      Value *NullValue = Constant::getNullValue(X->getType());
      Value *MinVal = ConstantInt::get(
```

2023-12-29 12:41 UTC, dtcxzyw commented on llvm/lib/Transforms/InstCombine/InstCombineCompares.cpp
> +        auto *SGE = Builder.CreateICmpSGE(X, NullValue);
```suggestion
        auto *SGT = Builder.CreateICmpSGT(X, AllOnesValue);
```
Canonicalize `sge X, 0 -> sgt X, -1`.

2023-12-29 12:41 UTC, dtcxzyw commented on llvm/lib/Transforms/InstCombine/InstCombineCompares.cpp
> +                   ? Builder.CreateOr(SGE, Builder.CreateICmpEQ(X, MinVal))
The transform doesn't match the alive2 proof:
```
----------------------------------------
define i1 @src_icmp_uge_abs(i4 %arg) {
#0:
  %abs = abs i4 %arg, 1
  %cmp = icmp uge i4 %abs, %arg
  ret i1 %cmp
}
=>
define i1 @tgt_icmp_uge_abs(i4 %arg) {
#0:
  %cmp = icmp sgt i4 %arg, 15
  ret i1 %cmp
}
Transformation seems to be correct!
```

Generally, `is_int_min_poison=1` provides more information. Thus we shouldn't emit more instructions than the case with `is_int_min_poison=0`.

2023-12-29 12:41 UTC, dtcxzyw commented on llvm/lib/Transforms/InstCombine/InstCombineCompares.cpp
> +    if (match(Op0, m_OneUse(m_Intrinsic<Intrinsic::abs>(m_Value(X),
I think we can drop the one-use constraint as we never create more than one instruction.

2024-01-02 11:45 UTC, nikic commented on llvm/lib/Transforms/InstCombine/InstCombineCompares.cpp
> +               m_Intrinsic<Intrinsic::abs>(m_Specific(X), m_Constant(C))))) {
You are matching the operands in swapped order here, but keep the old predicate. This will result in a miscompile (as your last test shows).

2024-01-02 15:17 UTC, nikic commented
Please rebase over https://github.com/llvm/llvm-project/commit/9d5b0965c43b4e8b3f21c106fe829391b1382277 and move the fold into foldICmpCommutative().

2024-01-04 11:14 UTC, dtcxzyw approved these changes
LGTM. Please wait for additional approval from other reviewers.

2024-01-04 11:14 UTC, dtcxzyw commented on llvm/lib/Transforms/InstCombine/InstCombineCompares.cpp
> +         match(Op1, m_Specific(X)))) {
```suggestion
    if (match(Op0, m_Intrinsic<Intrinsic::abs>(m_Value(X), m_Constant(C))) &&
         match(Op1, m_Specific(X))) {
```

2024-01-04 11:14 UTC, dtcxzyw commented on llvm/lib/Transforms/InstCombine/InstCombineCompares.cpp
> +                                 : Builder.CreateICmpULE(X, MinVal));
`icmp ule X, C` will be canonicalized into `icmp ult X, C+1`.

2024-01-04 11:14 UTC, dtcxzyw commented on llvm/test/Transforms/InstCombine/icmp-abs.ll
> +define i1 @icmp_sge_abs2(i4 %arg) {
Please add a negative test `abs(X) < Y`:
```
define i1 @icmp_sge_abs_mismatched_op(i4 %arg, i4 %arg2) {
   %abs = call i4 @llvm.abs.i4(i4 %arg, i1 true)
   %cmp = icmp sge i4 %abs, %arg2
   ret i1 %cmp
 }
```

2024-01-05 07:10 UTC, dtcxzyw approved these changes
LGTM. Please wait for additional approval from other reviewers.

2024-01-05 09:04 UTC, nikic approved these changes
LGTM

2024-01-05 09:08 UTC, merged