[Flang] Xfail hlfir test case on AIX
llvm/llvm-project pull request #76802
Opened 2024-01-03 09:57 UTC by madanial0

2024-01-03 20:03 UTC, kkwli commented on flang/test/HLFIR/simplify-hlfir-intrinsics.fir
> +// XFail the following test case on AIX due to potential miscompilation
TODO: Crash fir-opt on AIX

2024-01-04 10:26 UTC, tblah requested changes
Please could you provide some description of the problem, to explain why this is an XFail and not a bug

2024-01-04 20:08 UTC, madanial0 commented
> Please could you provide some description of the problem, to explain why this is an XFail and not a bug

Appologies, updated the description, this is potentially a bug that is currently being looked at the XFail on AIX will only be temporarily.

2024-01-05 10:33 UTC, tblah approved these changes
Okay thanks for updating. If you don't intend to work on this immediately, please could you make an issue upstream so that this is not forgotten.

2024-01-09 19:06 UTC, merged