[NFC] Renames a template parameter to avoid clashes with userspace names.
llvm/llvm-project pull request #76829
Opened 2024-01-03 15:55 UTC by bgra8

2024-01-03 16:16 UTC, mordante requested changes
Thanks for catching this!

Can you add `N` to https://github.com/llvm/llvm-project/blob/main/libcxx/test/libcxx/system_reserved_names.gen.py#L134 too? That way we will not repeat this mistake.

2024-01-03 16:16 UTC, mordante commented on libcxx/include/__format/format_arg_store.h
> +template <class _Context, size_t _Nargs>
This is our typical name for these.
```suggestion
template <class _Context, size_t _Np>
```

2024-01-03 16:47 UTC, bgra8 commented
> Thanks for catching this!
> 
> Can you add `N` to https://github.com/llvm/llvm-project/blob/main/libcxx/test/libcxx/system_reserved_names.gen.py#L134 too? That way we will not repeat this mistake.

Done.

2024-01-03 17:20 UTC, mordante approved these changes
Thanks LGTM!
Can you rebase the patch on main to see whether it passes the CI. The issues look like something I just fixed. When the CI is green feel free to land this patch.

2024-01-04 03:50 UTC, philnik777 commented
I've just created #76888 to fix more of these issues.

2024-01-04 08:25 UTC, bgra8 commented
The failing bots have been cancelled for some reason. I see no actual error or test failure.

2024-01-04 08:25 UTC, merged