[libcxx][test] try to directly create socket file in /tmp when filepath is too long
llvm/llvm-project pull request #77058
Opened 2024-01-05 08:53 UTC by yingcong-wu

If TMP is set to a folder which path is too long, the current libcxx test helper function `create_socket()` will fail because of the test temp folder `test_root`'s path is too long to be used in socket creation.
In such case, this patch will try to create the socket file directly in `/tmp` folder.

2024-01-07 16:56 UTC, mordante requested changes
Does this problem happen in practice? If so on what platform did this occur?

2024-01-07 16:56 UTC, mordante commented on libcxx/test/support/filesystem_test_helper.h
> +      // /tmp to make sure file path is short enough.
Why not using `std::tempnam` instead?

2024-01-08 01:20 UTC, yingcong-wu commented on libcxx/test/support/filesystem_test_helper.h
> +      // /tmp to make sure file path is short enough.
Good advice, I will change to use that.

2024-01-08 01:23 UTC, yingcong-wu commented
> Does this problem happen in practice? If so on what platform did this occur?

My problem happened on Linux when I set a TEMP folder with some long path.
I think the test should handle long TEMP, and the rest of tests are fine. Only the socket creation fails because there are a length limit in the socket file path.

2024-01-08 16:36 UTC, mordante approved these changes
Thanks! LGTM!

2024-01-08 16:36 UTC, mordante commented on libcxx/test/support/filesystem_test_helper.h
> +// on Android, let's not apply it for Android.
Not too happy about this, but since we assert afterwards it will fail the test. If that happens we can investigate.

2024-01-09 01:06 UTC, yingcong-wu commented
Great, thank you. I don't have commit access, could you please help land this patch for me?

2024-01-09 19:15 UTC, merged

2024-01-10 01:20 UTC, yingcong-wu commented
Thank you very much.