[libc++] tests: add long-double-is-double feature
llvm/llvm-project pull request #77076
Opened 2024-01-05 10:20 UTC by domin144

The current approach with matching the platforms by name is error prone. In my internal tests the platform is "arm-none-eabi" and was not matched even though the test is not valid there.

2024-01-08 11:13 UTC, domin144 commented
@ldionne @DavidSpickett @Quuxplusone

2024-01-08 11:43 UTC, DavidSpickett commented on libcxx/test/std/language.support/cmp/cmp.alg/strong_order_long_double.verify.cpp
> -// UNSUPPORTED: target=i686-{{.+}}-android{{.*}}
The UNSUPPORTED here might be brittle but the list of known systems without long double may prove useful for folks working in this area in future.

2024-01-08 11:44 UTC, DavidSpickett commented on libcxx/test/std/language.support/cmp/cmp.alg/strong_order_long_double.verify.cpp
> -// UNSUPPORTED: target=i686-{{.+}}-android{{.*}}
So keep the text that isn't UNSUPPORTED, is what I mean.

2024-01-08 16:45 UTC, mordante requested changes
In general we try to avoid feature macros when they are used once.
Since this test planned to be removed I rather keep the status quo. Otherwise we have a test macro with 0 users.

2024-01-08 16:45 UTC, mordante commented on libcxx/test/std/language.support/cmp/cmp.alg/strong_order_long_double.verify.cpp
The TODO on line 21 mentions this unsupported is temporary.

2024-01-09 08:51 UTC, closed without merging

2024-01-09 08:52 UTC, domin144 commented
Thanks for the comments, after thinking it of again, I decided to drop this PR. I have some more tests, which I mark as unsupported in my downstream patches and it does not make sense to push them upstream - they are not really useful here. I will rather try to figure out a way to skip them in my test configuration rather than patching the test sources.

2024-01-09 19:12 UTC, mordante commented
Note in general we don't mind patches that fix things that are tested in our CI.