[libc++] Fix `regex_search` to match `$` alone with `match_default` flag
llvm/llvm-project pull request #77256
Opened 2024-01-07 21:15 UTC by SanjayMarreddi

Using `regex_search` with the regex_constant `match_default` and a simple regex pattern `$` is expected to match general strings such as _"a", "ab", "abc"..._ at `[last, last)` positions.  But, the current implementation fails to do so.

Fixes #75042

2024-01-08 16:54 UTC, mordante requested changes
Thanks looks good, I'd like one more test before approval.

2024-01-08 16:54 UTC, mordante commented on libcxx/test/std/re/re.const/re.matchflag/match_not_eol.pass.cpp
> +      assert(!std::regex_search(target, re, std::regex_constants::match_not_eol));
Can you add a `regex_match` test too?

2024-01-08 20:42 UTC, SanjayMarreddi commented on libcxx/test/std/re/re.const/re.matchflag/match_not_eol.pass.cpp
> +      assert(!std::regex_search(target, re, std::regex_constants::match_not_eol));
Done

2024-01-09 19:17 UTC, mordante approved these changes
Thanks! LGTM! Do you need assistance to land this patch?

2024-01-09 19:38 UTC, SanjayMarreddi commented
I'm sorry, I don't think I fully understood what you asked. If you have asked, if I need assistance to get this merged, yes!!

2024-01-09 19:39 UTC, merged

2024-01-09 19:40 UTC, mordante commented
> I'm sorry, I don't think I fully understood what you asked. If you have asked, if I need assistance to get this merged, yes!!

Yes it was about merging. Before we used Phabricator and used the word landing.

2024-01-09 19:42 UTC, SanjayMarreddi commented
> > I'm sorry, I don't think I fully understood what you asked. If you have asked, if I need assistance to get this merged, yes!!
> 
> Yes it was about merging. Before we used Phabricator and used the word landing.

Now, I get it :) Thanks!!

2024-01-16 02:01 UTC, alexfh commented
It looks like the patch changes the behavior of search for patterns anchored both to the start and to the end of the input, e.g. after this change `std::regex_search` finds a pattern like `^b*$` in strings that don't match it (like `"a"`). Is this intended?

The behavior is now different to that of libstdc++: https://gcc.godbolt.org/z/hcd4acrb6

```
#include <regex>
#include <string>

int main() {
  std::string t = "a";
  std::regex re {"^b*$"};
  std::smatch matches;
  return std::regex_search(t, matches, re);
}
```
returns 1 on libc++ and 0 on libstdc++ (and libc++ before this change).

2024-01-16 09:37 UTC, SanjayMarreddi commented
@alexfh Thanks much for letting us know about this. I will look into it.

2024-01-16 13:12 UTC, alexfh commented
As usual: if the behavior is not intended (which I suspect is true) and there's no obvious and reliable fix, I'd suggest to revert first.

2024-01-16 14:11 UTC, ldionne commented
This seems broken to me -- the pattern `^b*$` shouldn't match `a`. @SanjayMarreddi if you're unsure how to fix this forward, let's revert the commit and add this regression test case, and then work on re-landing the patch without breaking that case. Let me know if you need help with the revert.

2024-01-16 21:26 UTC, SanjayMarreddi commented
I have created the revert. Will add this test case and work on relanding the patch.

2024-01-20 13:11 UTC, SanjayMarreddi commented
I have fixed the above test case along with the `$` alone test case and created a PR: #78845