Implement foldICmpRemConstant in InstCombineCompares
llvm/llvm-project pull request #77410
Opened 2024-01-09 05:02 UTC by Baxi-codes

2024-01-09 07:24 UTC, dtcxzyw requested changes
I applied your patch locally. It works for me:
```
> bin/opt -passes=instcombine test.ll -S
; ModuleID = 'test.ll'
source_filename = "test.ll"

define i1 @src(i8 noundef %0, i8 noundef %1) {
  %3 = mul i8 %0, 3
  %4 = urem i8 %3, %1
  %5 = icmp eq i8 %4, 0
  ret i1 %5
}
```

2024-01-09 07:24 UTC, dtcxzyw commented on llvm/lib/Transforms/InstCombine/InstCombineCompares.cpp
> +  const ICmpInst::Predicate Pred = Cmp.getPredicate();
```suggestion
  assert((Rem->getOpcode() == Instruction::SRem || Rem->getOpcode() == Instruction::URem) && "Only for srem/urem!");
  const ICmpInst::Predicate Pred = Cmp.getPredicate();
```

2024-01-09 07:24 UTC, dtcxzyw commented on llvm/lib/Transforms/InstCombine/InstCombineCompares.cpp
> +  Value *X = Rem->getOperand(0);
```suggestion
  if (!ICmpInst::isEquality(Pred) || !C.isZero())
    return nullptr;
  Value *X = Rem->getOperand(0);
```
It only holds for `==/!= 0`.

2024-01-09 07:24 UTC, dtcxzyw commented on llvm/lib/Transforms/InstCombine/InstCombineCompares.cpp
> +    return nullptr;
```suggestion
  Value *A, *B;
  const APInt *C1, *C2;
  if (Rem->getOpcode() == Instruction::SRem) {
    if (!match(X, m_NSWMul(m_Value(A), m_APInt(C1))))
      retur nullptr;
    if (!match(Y, m_NSWMul(m_Value(B), m_APInt(C2))))
      retur nullptr;
    if (!C1->srem(*C2).isZero())
      return nullptr;
  }
  else {
     ... // match with m_NUWMul and use urem
  }
```
Be careful of `nsw/nuw` flags.

2024-01-09 07:24 UTC, dtcxzyw commented on llvm/lib/Transforms/InstCombine/InstCombineCompares.cpp
> +  APInt K = C1Value->udiv(*C2Value);
For srem, use `sdiv` instead.

2024-01-09 07:24 UTC, dtcxzyw commented on llvm/lib/Transforms/InstCombine/InstCombineCompares.cpp
> +  Value *NewRem = Builder.CreateURem(Builder.CreateMul(A, ConstantInt::get(A->getType(), K)), B);
Same problem as above.
BTW, I think we can preserve the NSW/NUW flags for the mul.

2024-01-09 07:25 UTC, dtcxzyw commented
> Doesn't work right now

Please update your PR description and attach alive2 proofs.

2024-01-10 16:10 UTC, Baxi-codes commented on llvm/lib/Transforms/InstCombine/InstCombineCompares.cpp
> +  case Instruction::URem:
How do I do this? Do I undo the changes, add tests, and commit, then do the changes again?

2024-01-10 16:21 UTC, dtcxzyw commented on llvm/lib/Transforms/InstCombine/InstCombineCompares.cpp
> +  case Instruction::URem:
Yes.

2024-01-20 05:35 UTC, closed without merging

2024-01-20 05:39 UTC, Baxi-codes commented
Closed this pr, will create a new one

2024-01-21 18:28 UTC, Baxi-codes commented
> > Doesn't work right now
> 
> Please update your PR description and attach alive2 proofs.

nsw with srem doesn't verify
https://alive2.llvm.org/ce/z/n7wYL5

2024-01-22 02:10 UTC, dtcxzyw commented
> > > Doesn't work right now
> > 
> > 
> > Please update your PR description and attach alive2 proofs.
> 
> nsw with srem doesn't verify https://alive2.llvm.org/ce/z/n7wYL5

https://alive2.llvm.org/ce/z/R73iWv

`sdiv INT_MIN, -1` will overflow.

2024-01-23 03:38 UTC, Baxi-codes commented
> > > > Doesn't work right now
> > > 
> > > 
> > > Please update your PR description and attach alive2 proofs.
> > 
> > 
> > nsw with srem doesn't verify https://alive2.llvm.org/ce/z/n7wYL5
> 
> https://alive2.llvm.org/ce/z/R73iWv
> 
> `sdiv INT_MIN, -1` will overflow.

I am not sure how to implement that transformation.
The original transformation turns out to be correct if both nsw and nuw flags are set
https://alive2.llvm.org/ce/z/THjHEk

2024-01-24 23:15 UTC, Baxi-codes commented
Please review the new PR
https://github.com/llvm/llvm-project/pull/79383