[LoopInterchange] Fix depends() check parameters
llvm/llvm-project pull request #77719
Opened 2024-01-11 03:19 UTC by ShivaChen

This commit enables loop-interchange with -enable-loopinterchange for the case in https://github.com/llvm/llvm-project/issues/71519.
With the loop-interchange, the case can be vectorized.

    for (int nl = 0; nl < 10000000/256; nl++)
      for (int i = 0; i < 256; ++i)
        for (int j = 1; j < 256; j++)
          aa[j][i] = aa[j - 1][i] + bb[j][i];

The commit address the issues that:
1. populateDependencyMatrix determine aa[j][i] has output dependency with itself.
2. The reversed parameter order of depends() caused the distance between aa[j][i] and aa[j - 1][i] be -1 instead of 1.

2024-01-11 16:46 UTC, Meinersbur commented
1. `populateDependencyMatrix` MUST check for self-dependencies, i.e. StoreInsts that overwrite memory of previous iterations. These must be kept in-order so the last overwrite is the value in memory when the loop nest finishes.

2. The order of I/J does not matter because of `D->normalize(SE)`.

2024-01-11 20:26 UTC, Meinersbur requested changes

2024-01-11 20:26 UTC, Meinersbur commented on llvm/lib/Transforms/Scalar/LoopInterchange.cpp
> +    for (J = I + 1, JE = MemInstr.end(); J != JE; ++J) {
https://godbolt.org/z/Tacx7M7M7

There is just a single MemInst (a StoreInst) in the loop body, hence `I == J` is the only check that would prevent the loop being interchanged.

2024-01-12 10:46 UTC, ShivaChen commented
> 1. `populateDependencyMatrix` MUST check for self-dependencies, i.e. StoreInsts that overwrite memory of previous iterations. These must be kept in-order so the last overwrite is the value in memory when the loop nest finishes.
> 2. The order of I/J does not matter because of `D->normalize(SE)`.

Hi Meinersbur,

Thanks for providing the example in https://godbolt.org/z/Tacx7M7M7, it make it easier to follow the reason of store self checking. :-)

1. It seems the interchange in the case is invalid due to the store type is wider than the array element type. Could we detect the type size to prevent the interchange instead of output dependency to itself? The loop in s231() didn't has cross multiple iteration store and bail out by the store self checking. There is a https://github.com/llvm/llvm-project/pull/77885 PR to address the issue.
2. According to `isDirectionNegative()`, it will normalize if find ">". However, s231 has 3 level loop. There is no dependency in Level 1 loop and Direction is initialized as "*" which prevent the normalize.

 ```
   for (int nl = 0; nl < 10000000/256; nl++) // Level 1
     for (int i = 0; i < 256; ++i)           // Level 2
       for (int j = 1; j < 256; j++)         // Level 3
         aa[j][i] = aa[j-1][i] + bb[j][i];

```
Index SCEV of aa[j] is {1,+,1}, Index SCEV of aa[j-1] is {0,+,1}.
The depends(aa[j][i], aa[j-1][i]) call site in LoopCacheAnalysis return the correct distance 1.
The call site in LoopInterchange has depends(aa[j-1][i], aa[j][i]) and return distance as -1.
Should LoopInterchange follow the parameters as LoopCacheAnalysis?

2024-01-16 06:29 UTC, ShivaChen commented
> > 1. `populateDependencyMatrix` MUST check for self-dependencies, i.e. StoreInsts that overwrite memory of previous iterations. These must be kept in-order so the last overwrite is the value in memory when the loop nest finishes.
> > 2. The order of I/J does not matter because of `D->normalize(SE)`.
> 
> Hi Meinersbur,
> 
> Thanks for providing the example in https://godbolt.org/z/Tacx7M7M7, it make it easier to follow the reason of store self checking. :-)
> 
> 1. It seems the interchange in the case is invalid due to the store type is wider than the array element type. Could we detect the type size to prevent the interchange instead of output dependency to itself? The loop in s231() didn't has cross multiple iteration store and bail out by the store self checking. There is a [[LoopInterchange] Forbid interchange if load store type wider than element type #77885](https://github.com/llvm/llvm-project/pull/77885) PR to address the issue.
> 2. According to `isDirectionNegative()`, it will normalize if find ">". However, s231 has 3 level loop. There is no dependency in Level 1 loop and Direction is initialized as "*" which prevent the normalize.
> 
> ```
>   for (int nl = 0; nl < 10000000/256; nl++) // Level 1
>     for (int i = 0; i < 256; ++i)           // Level 2
>       for (int j = 1; j < 256; j++)         // Level 3
>         aa[j][i] = aa[j-1][i] + bb[j][i];
> ```
> 
> Index SCEV of aa[j] is {1,+,1}, Index SCEV of aa[j-1] is {0,+,1}. The depends(aa[j][i], aa[j-1][i]) call site in LoopCacheAnalysis return the correct distance 1. The call site in LoopInterchange has depends(aa[j-1][i], aa[j][i]) and return distance as -1. Should LoopInterchange follow the parameters as LoopCacheAnalysis?

It seems LoopCacheAnalysis only consider |distance| to fit in cache line instead of direction.
And depending on program order could have oppose case get the wrong direction.

    for (int j = 1; j < M; j++) 
      for (int i = 1; i < N; i++) {
        aa[1][j-1] += bb[i][j];
        cc[i][j] = aa[1][j];
      }

What about make call site as `depends(store, load)`?
So we can catch the distance of cross iteration flow dependency.

`depends(aa[j][i], aa[j-1][i])` return distance 1 for j in s231() and `depends(aa[1][j-1], aa[1][j])` return distance -1 for j in the above case.

2024-01-22 22:35 UTC, Meinersbur commented
> 1. It seems the interchange in the case is invalid due to the store type is wider than the array element type. Could we detect the type size to prevent the interchange instead of output dependency to itself? The loop in s231() didn't has cross multiple iteration store and bail out by the store self checking. There is a [[LoopInterchange] Forbid interchange if load store type wider than element type #77885](https://github.com/llvm/llvm-project/pull/77885) PR to address the issue.

Traditionally, dependence analysis does not assume that store will completely overwrite a previous value, but some bits remain. This is what my example is showing. Removing stores that will be overwritten anyway is what a 'dead store elimination' optimization would do. You could do this by adding a "is completely overwritten" accessor or similar to a `FullDependency` testing for all required conditions. #77885 is insufficient as I will explain there.


> 2. According to `isDirectionNegative()`, it will normalize if find ">". However, s231 has 3 level loop. There is no dependency in Level 1 loop and Direction is initialized as "*" which prevent the normalize.
> 
> ```
>   for (int nl = 0; nl < 10000000/256; nl++) // Level 1
>     for (int i = 0; i < 256; ++i)           // Level 2
>       for (int j = 1; j < 256; j++)         // Level 3
>         aa[j][i] = aa[j-1][i] + bb[j][i];
> ```
> 
> Index SCEV of aa[j] is {1,+,1}, Index SCEV of aa[j-1] is {0,+,1}. The depends(aa[j][i], aa[j-1][i]) call site in LoopCacheAnalysis return the correct distance 1. The call site in LoopInterchange has depends(aa[j-1][i], aa[j][i]) and return distance as -1. Should LoopInterchange follow the parameters as LoopCacheAnalysis?
>
> It seems LoopCacheAnalysis only consider |distance| to fit in cache line instead of direction. And depending on program order could have oppose case get the wrong direction.
> 
> ```
> for (int j = 1; j < M; j++) 
>   for (int i = 1; i < N; i++) {
>     aa[1][j-1] += bb[i][j];
>     cc[i][j] = aa[1][j];
>   }
> ```
> 
> What about make call site as `depends(store, load)`? So we can catch the distance of cross iteration flow dependency.
> 
> `depends(aa[j][i], aa[j-1][i])` return distance 1 for j in s231() and `depends(aa[1][j-1], aa[1][j])` return distance -1 for j in the above case.

LoopCacheAnalysis does not care about the order of access, but whether the values are close enough to fit into the cache or cache line. E.g. if it is in the same cache line, then the second access will already have been established in the L1 cache, and therefore can be accessed with lower latency. Which of the accesses is first/second does not matter, accessing one of them will establish the other in the cache line[^1].

[^1]: LoopCacheAnalysis does not consider cache line boundaries and data alignment, but if two neighboring addresses do not fall into the same cache line, the processor may have prefetched the neighboring cache line. Hence, it should be a good enough heuristic.

2024-01-25 07:25 UTC, ShivaChen commented
> > Index SCEV of aa[j] is {1,+,1}, Index SCEV of aa[j-1] is {0,+,1}. The depends(aa[j][i], aa[j-1][i]) call site in LoopCacheAnalysis return the correct distance 1. The call site in LoopInterchange has depends(aa[j-1][i], aa[j][i]) and return distance as -1. Should LoopInterchange follow the parameters as LoopCacheAnalysis?
> >> It seems LoopCacheAnalysis only consider |distance| to fit in cache line instead of direction. 
> 
> LoopCacheAnalysis does not care about the order of access, but whether the values are close enough to fit into the cache or cache line. E.g. if it is in the same cache line, then the second access will already have been established in the L1 cache, and therefore can be accessed with lower latency. Which of the accesses is first/second does not matter, accessing one of them will establish the other in the cache line[1](#user-content-fn-1-e1f02a32cb7511a1ac56645b1134c78e).
> 
> ## Footnotes
> 1. LoopCacheAnalysis does not consider cache line boundaries and data alignment, but if two neighboring addresses do not fall into the same cache line, the processor may have prefetched the neighboring cache line. Hence, it should be a good enough heuristic. [↩](#user-content-fnref-1-e1f02a32cb7511a1ac56645b1134c78e)

Agree, LoopCacheAnalysis only need to consider the aboslute value of |distance|. So might not a good analogue of LoopInterchange which the direction matter.
And LoopCacheAnalysis should able to catch the correct direction if the normalize occur as expected.

2024-02-06 07:16 UTC, ShivaChen commented
Loop Access Analysis would use distance's direction for validation. LAA is using `SinkSCEV - SrcSCEV` to calculate distance. Dependence Analysis used by loop interchange is using `SrcSCEV - DstSCEV(SinkSECV)`. So reverse the call site Dst and Src can sync with LAA. Another observation is that LAA using LoopBlocksRPO to traverse the blocks with program order. GCC use get_loop_body_in_dom_order to traverse blocks with program order. GCC's build_classic_dist_vector will have leftmost distance always positive by reverse the direction and record DDR_REVERSED_P to determine whether the vector has been reversed. In gimple-loop-interchange.cc, gcc will consider DDR_REVERSED_P, that is it will use original distance signedness to  determine the validation. 
An alternative method would rely on normalize to reverse the distance: https://github.com/llvm/llvm-project/pull/78951.

2025-05-05 06:30 UTC, closed without merging