[LoopInterchange] Forbid interchange if load store type wider than element type
llvm/llvm-project pull request #77885
Opened 2024-01-12 07:38 UTC by ShivaChen

Consider the following case, interchange is not valid as the store type(int) is wider than the array element type(char).

    char p[7];
    for (int j = 0; j < 2; ++j)
      for (int i = 0; i < 2; ++i)
        *((int*)&p[2*i+j]) = 2*i+j+1;

2024-01-22 23:14 UTC, Meinersbur requested changes
Using different type widths is not a sufficient condition for testing overwrites. It could be the same type, but with offsets single bytes apart. There could be other conditions, e.g. function calls/atomics that only partially overwrite the target. Admittedly, DependenceAnalysis currently bails out on those, but in the very least the comment should mention all the necessary conditions and explain why they don't need to be checked. Your comments only explain the what, not the why.

2024-01-25 05:11 UTC, ShivaChen commented
Thanks for your kind explanation and bring more cases that could have overwritten.
Another angle could be would the casting between int and char types is well-defined behavior.
If it isn't, should we abandon the PR because the compiler may not be able to guarantee the results?

2024-01-25 05:14 UTC, ShivaChen commented on llvm/lib/Transforms/Scalar/LoopInterchange.cpp
> +    Type *ElementTy = GEP->getSourceElementType();
Thanks for the information. I was mimicking how the delinearization extract the subscripts. I assume we should not increase the dependency to GEP. Thanks.

2024-01-26 00:31 UTC, Meinersbur commented
Yes, I suggest to abandon this approach. Delinearization by use the GEP data type, but would also have to change if the GEP type goes away. Better not add a dependency on it.

However, it is "safe" for delinerization because passes are required to add runtime checks that check that verify that the indices fall into the expected range (e.g. no negative). In worst case when the delinerization heuristic is completely wrong the runtime check would always fail and the fallback (non-optimized) version to be executed.

2024-01-26 10:23 UTC, ShivaChen commented
Abandon due to the case might be undefined behavior.

2024-01-26 10:23 UTC, closed without merging