[mlir][vector] Fix invalid IR in `ContractionOpLowering`
llvm/llvm-project pull request #78130
Opened 2024-01-15 09:20 UTC by matthias-springer

If a rewrite pattern returns "failure", it must not have modified the IR. This commit fixes `Dialect/Vector/vector-contract-to-outerproduct-transforms-unsupported.mlir` when running with `MLIR_ENABLE_EXPENSIVE_PATTERN_API_CHECKS`.

```
  * Pattern (anonymous namespace)::ContractionOpToOuterProductOpLowering : 'vector.contract -> ()' {
Trying to match "(anonymous namespace)::ContractionOpToOuterProductOpLowering"
    ** Insert  : 'vector.transpose'(0x5625b3a8cb30)
    ** Insert  : 'vector.transpose'(0x5625b3a8cbc0)
"(anonymous namespace)::ContractionOpToOuterProductOpLowering" result 0
  } -> failure : pattern failed to match
} -> failure : pattern failed to match

LLVM ERROR: pattern returned failure but IR did change
```

Note: `vector-contract-to-outerproduct-transforms-unsupported.mlir` is merged into `vector-contract-to-outerproduct-matvec-transforms.mlir`. The `greedy pattern application failed` error is not longer produced. This error indicates that the greedy pattern rewrite did not convergence; it does not mean that a pattern could not be applied.

2024-01-15 19:23 UTC, joker-eph approved these changes

2024-01-16 00:51 UTC, hanhanW commented on mlir/lib/Dialect/Vector/Transforms/LowerVectorContract.cpp
> +
I think keeping the variable is quite useful in terms of readability. Can we keep it?

2024-01-16 00:51 UTC, hanhanW commented on mlir/lib/Dialect/Vector/Transforms/LowerVectorContract.cpp
> -    Value transposedMask = t(mask);
ditto

2024-01-16 00:51 UTC, hanhanW commented on mlir/lib/Dialect/Vector/Transforms/LowerVectorContract.cpp
> +  std::optional<int64_t> getReductionSize(VectorType vecType,
Can you add a doc to the method? Otherwise, people need to look at implementation to understand when `std::nullopt` will be returned.

2024-01-16 05:09 UTC, nicolasvasilache requested changes

2024-01-16 05:09 UTC, nicolasvasilache commented on mlir/lib/Dialect/Vector/Transforms/LowerVectorContract.cpp
> +        return outerProd(tlhs, t(rhs), res, lhsType, *reductionSize,
These tests have now become non-deterministic across different systems as the order of the commas is not specified.

The line just before was a way to remedy this, you'll need to calculate the mask (or t(rhs)) ahead of time in each case.

we could sprinkle CHECK-DAG in various places like you did but this does not scale, every test writer will need to be aware of this or they will end up writing new tests that work on their system and be very puzzled when build bots come back red.

2024-01-16 08:20 UTC, matthias-springer commented on mlir/lib/Dialect/Vector/Transforms/LowerVectorContract.cpp
> -    Value transposedMask = t(mask);
See above, must be nested.

2024-01-16 08:30 UTC, nicolasvasilache approved these changes
Thanks for fixing.

Can you please add a clear comment, before the first `if`, for whomever is going to want to factor the mask construction out in the future that they should not ?

2024-01-16 08:31 UTC, nicolasvasilache commented on mlir/test/Dialect/Vector/vector-contract-to-outerproduct-matvec-transforms.mlir
> +  // CHECK-DAG:     vector.transpose %[[MASK]]
please drop these, let's be deterministic

2024-01-16 08:40 UTC, merged