[ASan][AMDGPU] Fix Assertion Failure.
llvm/llvm-project pull request #78410
Opened 2024-01-17 08:24 UTC by ampandey-1995

Assertion failure `(i >= FTy->getNumParams() || FTy->getParamType(i) == Args[i]->getType()) && "Calling a function with a bad signature!"'.  The 'llvm.memcpy' intercepted by ASan instrumentation pass is implemented by it's own __asan_memcpy implementation. The second argument of llvm.memcpy accepts ptr to addrspace(4), __asan_memcpy also has to follow ptr to addrspace(4) convention.

2024-01-17 08:33 UTC, arsenm requested changes

2024-01-17 08:33 UTC, arsenm commented on llvm/test/Instrumentation/AddressSanitizer/AMDGPU/asan_instrument_mem_intrinsics.ll
> +
Should also test the same function with the operand/pointer types swapped

2024-01-17 08:33 UTC, arsenm commented on llvm/lib/Transforms/Instrumentation/AddressSanitizer.cpp
> +                   {MI->getOperand(0),
Both pointer operands will have the same issue, should test both

2024-01-17 08:33 UTC, arsenm commented on llvm/test/Instrumentation/AddressSanitizer/AMDGPU/asan_instrument_mem_intrinsics.ll
> +call void @llvm.memcpy.p0.p4.i64(ptr align 16 %fmt.ascast, ptr addrspace(4) align 16 @__const.__assert_fail.fmt, i64 47, i1 false)
Test both memmove and memcpy

2024-01-17 10:23 UTC, arsenm commented on llvm/test/Instrumentation/AddressSanitizer/AMDGPU/asan_instrument_mem_intrinsics.ll
> +
Also another test where both operands require the cast, as well as the integer cast.

2024-01-19 12:43 UTC, ampandey-1995 commented
Apologies there are some unnecessary changes added to this PR. Closing this PR in favour of new one

2024-01-19 12:43 UTC, closed without merging