[clangd] forward clang-tidy's readability-identifier-naming fix to textDocument/rename
llvm/llvm-project pull request #78454
Opened 2024-01-17 14:45 UTC by tom-anders

2024-01-29 08:49 UTC, HighCommander4 commented
Linking to the issue this is seeking to address for reference: https://github.com/clangd/clangd/issues/1589

2024-01-29 09:02 UTC, HighCommander4 reviewed
Thanks, the approach in this patch looks pretty good to me.

My only feedback is to encapsulate the "hard coding" into a function like:

```
Option<CodeActionResult::Rename> TryConvertToRename(const Diag *D, const Fix *F)
```

because I can imagine in the future coming across other diagnostics that are conceptually renames that we may want to handle this way.

Regarding testing: I find lit-tests pretty hard to read and maintain; a nicer alternative might be a gtest in `ClangdLSPServerTests` (e.g. see [this one](https://searchfox.org/llvm/rev/23b233c8adad5b81e185e50d04356fab64c2f870/clang-tools-extra/clangd/unittests/ClangdLSPServerTests.cpp#198) for testing call hierarchy incoming calls).

2024-01-29 17:45 UTC, tom-anders commented
Duplicate issue: https://github.com/clangd/clangd/issues/741

2024-01-31 07:59 UTC, HighCommander4 commented
> Duplicate issue: [clangd/clangd#741](https://github.com/clangd/clangd/issues/741)

Nice find, I closed it as a duplicate.

2024-01-31 18:57 UTC, tom-anders commented
Thanks for the feedback!

> Thanks, the approach in this patch looks pretty good to me.
> 
> My only feedback is to encapsulate the "hard coding" into a function like:
> 
> ```
> Option<CodeActionResult::Rename> TryConvertToRename(const Diag *D, const Fix *F)
> ```
> 
> because I can imagine in the future coming across other diagnostics that are conceptually renames that we may want to handle this way.

:heavy_check_mark: 

> Regarding testing: I find lit-tests pretty hard to read and maintain; a nicer alternative might be a gtest in `ClangdLSPServerTests` (e.g. see [this one](https://searchfox.org/llvm/rev/23b233c8adad5b81e185e50d04356fab64c2f870/clang-tools-extra/clangd/unittests/ClangdLSPServerTests.cpp#198) for testing call hierarchy incoming calls).

Perfect, thanks for the hint! I had to adapt `LSPClient` a bit, it usually would flag every server->client call as an error, but in this case we actually expect a `workspace/applyEdit` after we trigger the renaming.

2024-02-06 07:21 UTC, HighCommander4 commented
Looks pretty good!

Are there further changes you're planning to make, or is this ready to graduate from "Draft" status?

2024-02-06 09:48 UTC, tom-anders commented
> Looks pretty good!
> 
> Are there further changes you're planning to make, or is this ready to graduate from "Draft" status?

Ah, thanks about the heads up, forgot about this

2024-02-06 18:33 UTC, tom-anders commented
(fixed formatting issues)

2024-02-11 04:44 UTC, HighCommander4 requested changes
Ok, I had a more detailed look at the implementation. Still looks good overall, just have some minor comments.

2024-02-11 23:48 UTC, HighCommander4 commented
Something else I noticed while trying out the patch locally: before the patch, the description of the quick fix in the editor is "change 'foo' to 'Foo'", i.e. a description of what the code action will do.

After the patch, the description of the quick fix is now "invalid case style for function 'foo'", i.e. it describes the problem, not the fix.

We should keep the description of the code action the same, i.e. describing the fix.

2024-02-11 23:54 UTC, HighCommander4 commented
(It's also no longer labelled as a "quick fix", likely due to the `CodeActionKind` changing from `quickfix` to `refactor`, but that's probably fine.)

2024-02-18 11:13 UTC, tom-anders commented on clang-tools-extra/clangd/ClangdServer.cpp
> +TryConvertToRename(const Diag *Diag, const ClangdServer::DiagRef &DR,
hah :D 

At work we're using Google style, so functions are CamelCase and variables snake_case. Switching back and forth between Google and LLVM style is so confusing

2024-02-18 11:24 UTC, tom-anders commented
> Something else I noticed while trying out the patch locally: before the patch, the description of the code action in the editor is "change 'foo' to 'Foo'", i.e. a description of what the code action will do.
> 
> After the patch, the description of the code action is now "invalid case style for function 'foo'", i.e. it describes the problem, not the fix.
> 
> We should keep the description of the code action the same, i.e. describing the fix.

Ah good find, I added a new `FixMessage` field for this (and also added this to the test)

2024-02-20 07:25 UTC, HighCommander4 approved these changes
Thanks, LGTM!

2024-02-20 07:35 UTC, merged