[RemoveDIs][DebugInfo] Update SROA to handle DPVAssigns
llvm/llvm-project pull request #78475
Opened 2024-01-17 17:00 UTC by SLTozer

SROA needs to update llvm.dbg.assign intrinsics when it migrates debug info in response to alloca splitting; this patch updates the debug info migration code to handle DPVAssigns as well, making use of generic code to avoid duplication as much as possible.

2024-01-19 15:48 UTC, OCHyams approved these changes
Code changes all LGTM, but this needs tests too. What's your intended strategy for landing code/test changes?

FWIW For DPDeclares I updated the tests for each pass in the same patch the code was update (e.g., you would update SROA tests here), with the tests "rotten green" (not actually testing the DPDeclares) until the capstone patch that enabled dbg.declare -> DPDeclare landed.

2024-01-19 15:48 UTC, OCHyams commented on llvm/lib/Transforms/Scalar/SROA.cpp
> +static DPValue *createLinkedAssign(DPValue *, DIBuilder &DIB,
clang-format?

2024-01-19 15:48 UTC, OCHyams requested changes
(oops wrong button)

2024-01-22 11:08 UTC, OCHyams approved these changes
LGTM (after clang-format)

2024-01-23 09:37 UTC, merged

2024-01-23 09:58 UTC, cHackz18 commented
@SLTozer Hi Stephen,

it looks as though your change may have caused a build bot failure here:
https://lab.llvm.org/buildbot/#/builders/139/builds/57800

2024-01-23 10:02 UTC, SLTozer commented
Apologies, I see the fix has already been landed - thanks for catching this!