[libc][NFC] Fix GCC volatile warning
llvm/llvm-project pull request #78509
Opened 2024-01-17 22:07 UTC by gchatelet

GCC complains about "type qualifiers ignored on cast result type"

2024-01-17 22:08 UTC, gchatelet commented
Looking at functions around this one, I suspect the volatile is unnecessary.

2024-01-17 22:11 UTC, nickdesaulniers commented
added by @lntue in d6802581700bd.

Honestly, does this test need to use `volatile` at all?  `volatile` is kind of a broken qualifier at least in regards to storage; it should only be used to force loads/stores to be atomic and non-coalesced (by casting the address of an lvalue to a pointer of that type plus volatile, then deferencing that).

2024-01-17 22:12 UTC, nickdesaulniers commented
consider adding the diagnostic you're addressing to the commit message (here and in future patches) to help reviewers understand precisely what you're addressing.

2024-01-17 22:13 UTC, nickdesaulniers commented
Also, I'm curious if clang supports this diagnostic flag and if/why we don't see it with clang. That's another "thread to pull on."

2024-01-17 22:46 UTC, lntue commented
The intention of `volatile` was to force the conversion to double for each rounding mode inside the macro `EXPECT_FP_EQ_ALL_ROUNDING`: https://github.com/llvm/llvm-project/blob/main/libc/test/UnitTest/FPMatcher.h#L190
Without forcing re-evaluation, the compiler will optimize and only use the default rounding mode output of the conversion for all the rounding modes.
It seems to work properly on clang, and probably because gcc ignores the attribute, this test failed on gcc?

A proper fix is probably updating the `EXPECT_FP_EQ_ALL_ROUNDING` in every rounding mode check as:
```
  if (__r.success) {
    volatile auto e = (expected);
    volatile auto a = (actual);
    EXPECT_FP_EQ(e, a);
  }
```

2024-01-17 22:57 UTC, nickdesaulniers commented
> this test failed on gcc?

Is this test failing with GCC?

2024-01-17 22:57 UTC, gchatelet commented
Then a proper fix is probably to use something like google benchmark [`DoNotOptimize`](https://github.com/google/benchmark/blob/3d293cd67a264701378c46e2ae3b6408d533e093/include/benchmark/benchmark.h#L453-L456).

`volatile` is [broken in many ways](https://www.youtube.com/watch?v=KJW_DLaVXIY).

2024-01-17 22:58 UTC, nickdesaulniers commented
> Without forcing re-evaluation, the compiler will optimize and only use the default rounding mode output of the conversion for all the rounding modes.

As in the compiler may do constant folding with a default rounding mode (rather than a rounding mode that may be changed during runtime)?

Regardless, could use comments in the source then to document _why_.

2024-01-17 22:59 UTC, gchatelet commented
> > this test failed on gcc?
> 
> Is this test failing with GCC?

It doesn't AFAICT, GCC warns about "type qualifiers ignored on cast result type".

2024-01-17 23:06 UTC, nickdesaulniers commented
> As in the compiler may do constant folding with a default rounding mode (rather than a rounding mode that may be changed during runtime)?

https://gcc.gnu.org/onlinedocs/gcc/Optimize-Options.html#index-frounding-math

2024-01-18 15:30 UTC, gchatelet commented
I changed the build system to add `-frounding-math` to both CMake and Bazel. @lntue let me know if there's a better way to do this. I've checked that the flag is passed down to the command line but I haven't checked the generated code.

2024-01-18 15:52 UTC, lntue commented
> I changed the build system to add `-frounding-math` to both CMake and Bazel. @lntue let me know if there's a better way to do this. I've checked that the flag is passed down to the command line but I haven't checked the generated code.

Adding that flag should work.  Can you only add that flag to the updated tests in this patch for now?

2024-01-18 16:11 UTC, gchatelet commented
> > I changed the build system to add `-frounding-math` to both CMake and Bazel. @lntue let me know if there's a better way to do this. I've checked that the flag is passed down to the command line but I haven't checked the generated code.
> 
> Adding that flag should work. Can you only add that flag to the updated tests in this patch for now?

Do you mean that I should add the flag only on this particular test and not globally for all `add_fp_unittest` / `libc_test`?

2024-01-18 16:18 UTC, lntue commented
> > > I changed the build system to add `-frounding-math` to both CMake and Bazel. @lntue let me know if there's a better way to do this. I've checked that the flag is passed down to the command line but I haven't checked the generated code.
> > 
> > 
> > Adding that flag should work. Can you only add that flag to the updated tests in this patch for now?
> 
> Do you mean that I should add the flag only on this particular test and not globally for all `add_fp_unittest` / `libc_test`?

Yes.

2024-01-18 16:21 UTC, nickdesaulniers commented
> > Do you mean that I should add the flag only on this particular test and not globally for all `add_fp_unittest` / `libc_test`?
> 
> Yes.

+1, then you can remove all uses of `volatile` in that test as well.

2024-01-18 16:28 UTC, nickdesaulniers requested changes
don't forget to remove volatiles!

2024-01-18 19:15 UTC, nickdesaulniers approved these changes

2024-01-18 19:15 UTC, nickdesaulniers commented on libc/test/src/__support/FPUtil/CMakeLists.txt
> +  COMPILE_OPTIONS
consider adding a comment why this is necessary

2024-01-18 19:58 UTC, lntue approved these changes

2024-01-19 08:27 UTC, merged