Update amdgpu_gfx functions to use s0-s3 for inreg SGPR arguments on targets using scratch instructions for stack
llvm/llvm-project pull request #78553
Opened 2024-01-18 09:11 UTC by Rajveer100

Resolves Issue #78226

Update the argument list for `*_Gfx` calling conventions for AMDGPU calling convention and update the conditional check under `enableFlatScratch` which pre-allocates the registers.

2024-01-18 09:12 UTC, Rajveer100 commented
@arsenm 
Let me know if these were the intended changes to be done.

2024-01-18 12:04 UTC, Rajveer100 commented
@philnik777 @ldionne 
Is it normal to see 175+ tests failing here, or is there any flag to bless tests (like `--bless`) to produce the necessary changes.

2024-01-18 12:22 UTC, philnik777 commented
How would I know? I'm working on libc++ and clang, not LLVM backends.

2024-01-18 14:29 UTC, arsenm commented
Code change looks right (though it's missing the mirror change for GlobalISel in AMDGPUCallLowering). This will need test updates though

2024-01-26 10:50 UTC, arsenm commented on llvm/lib/Target/AMDGPU/AMDGPUCallLowering.cpp
> -    if (!IsGraphics && InReg)
This is the wrong change for this particular patch. You want the AllocateReg above determineAssignments

2024-02-06 12:47 UTC, arsenm requested changes
Removed the wrong IsGraphics and needs test updates

2024-02-07 10:12 UTC, Rajveer100 commented
How should the tests be added, I see too many of them failing?

2024-02-08 10:03 UTC, arsenm commented
> How should the tests be added, I see too many of them failing at the moment?

This should be covered by existing tests (which just now need many updates)

2024-02-08 13:42 UTC, Rajveer100 commented
I don't think I have to manually fix each of the 175 tests individually, or do I?

2024-02-08 14:37 UTC, arsenm commented
> I don't think I have to manually fix each of the 175 tests individually, or do I? Also, could you describe about testing _.ll_ files in particular that have _FileCheck_ and _assertions_.

Everything that's failing. 175 sounds a bit high for this. Just about every test has FileCheck. update_llc_test_checks ----update-only will likely get most of them

2024-02-08 18:45 UTC, Rajveer100 commented
Do I have to include any additional builds (like _openmp_) in the llvm build to generate those tests, as they are currently only in the _llvm/_ directory and hence isn't invoked by _update_llc_test_checks_ due to this.

2024-02-09 17:18 UTC, arsenm commented
> Do I have to include any additional builds (like _openmp_) in the llvm build to generate those tests, as they are currently only in the _llvm/_ directory and hence isn't invoked by _update_llc_test_checks_ due to this?

No

> 
> ```shell
> > llvm/utils/update_llc_test_checks.py llvm/test/CodeGen/AMDGPU/GlobalISel/irtranslator-call.ll -u
> 
> WARNING: Skipping test which wasn't autogenerated by utils/update_llc_test_checks.py: llvm/test/CodeGen/AMDGPU/GlobalISel/irtranslator-call.ll
> ```

Some are updated by update_mir_test_checks, some update_test_checks, and some are hand written. Some have checks for multiple types of checks (which the update scripts don't gracefully handle). I'd expect update_llc_test_checks to handle the majority of them

2024-02-10 19:01 UTC, Rajveer100 commented
To be clear, I see this warning for all tests, i.e, I am unable to use those utility commands with same output as mentioned in the above comment.

2024-02-21 07:31 UTC, Rajveer100 commented
> For clarity, I see this warning for all tests, i.e, I am unable to use any of those utility commands with the same issue as mentioned in the above comment.

@arsenm 
Can you let me know the cause for this?

2024-02-29 06:23 UTC, arsenm commented
> > For clarity, I see this warning for all tests, i.e, I am unable to use any of those utility commands with the same issue as mentioned in the above comment.
> 
> @arsenm Can you let me know the cause for this?

Some tests are not autogenerated and will need manually updating (or updating with update_mir_test_checks). The warning is expected. You should see it working on some of them

2024-02-29 12:17 UTC, arsenm commented
Duplicate #81394

2024-02-29 12:46 UTC, Rajveer100 commented
@arsenm 
It looks like @SahilPatidar is much [closer](https://github.com/llvm/llvm-project/pull/81394) to completion, closing this PR.

Will keep an eye on the same, to learn more!

2024-02-29 12:46 UTC, closed without merging