Resolve FIXME: use RegScavenger to find the best unused register
llvm/llvm-project pull request #78910
Opened 2024-01-21 20:00 UTC by AtariDreams

2024-01-24 10:21 UTC, jayfoad commented on llvm/lib/Target/AArch64/AArch64SpeculationHardening.cpp
> +    }
I think you can call scavengeRegisterBackwards even at the start of a block - can't you?
```
    if (I == MBB.begin())
      RS.enterBasicBlock(MBB);
    else
      RS.backward(I);
    TmpReg = RS.scavengeRegisterBackwards(AArch64::GPR64commonRegClass, I,
                                          false, 0, false);
```
The only reason this code was special casing `I == MBB.begin()` in the first place is for efficiency, not for correctness. The assumption is that `enterBasicBlock` is more efficient than `backward` which might have to step over arbitrarily many instructions.

2024-01-24 21:19 UTC, qcolombet commented on llvm/test/CodeGen/AArch64/speculation-hardening.mir
> +  ; CHECK-LABEL: nobranch_fallthrough:
If you use the autogenerated test, make sure to clear the all check lines.
As is, there are labels that are repeated which may lead in weird failures with FileCheck. (e.g., the label nobranch_fallthrough appears twice.)

2024-01-24 21:21 UTC, qcolombet commented on llvm/test/CodeGen/AArch64/speculation-hardening.mir
>    define void @nobranch_fallthrough(i32 %a, i32 %b) speculative_load_hardening {
Could you add a comment of what needs to happen or must not happen in the comment?

The manual checks were conveying this in a more direct way (but broken in its own way :P).

2024-02-06 13:25 UTC, arsenm requested changes
Previous comments

2024-02-08 11:19 UTC, arsenm commented on llvm/lib/Target/AArch64/AArch64SpeculationHardening.cpp
> -    // already to do this - but it's unclear if that could easily be used here.
This comment should probably be reserved, fundamentally the scavenge is still doing the same thing and not finding a "nicer" register

2024-08-11 15:34 UTC, closed without merging