[RISCV] Add regalloc hints for Zcb instructions.
llvm/llvm-project pull request #78949
Opened 2024-01-22 08:02 UTC by topperc

This hints the register allocator to use the same register for source and destination to enable more compression.

2024-01-22 08:28 UTC, dtcxzyw requested changes

2024-01-22 08:28 UTC, dtcxzyw commented on llvm/lib/Target/RISCV/RISCVRegisterInfo.cpp
> +      // c.zext.h
```suggestion
      // c.zext.b
```

2024-01-22 08:28 UTC, dtcxzyw commented on llvm/lib/Target/RISCV/RISCVRegisterInfo.cpp
> +      return Subtarget.hasStdExtZcb() && MI.getOperand(2).getReg() == RISCV::X0;
```suggestion
      return Subtarget.hasStdExtZcb() && MI.getOperand(2).isReg() && MI.getOperand(2).getReg() == RISCV::X0;
```

2024-01-22 18:27 UTC, dtcxzyw approved these changes
LGTM. Thanks!

2024-01-23 15:34 UTC, asb approved these changes
LGTM.

2024-01-23 17:33 UTC, merged