[LoopInterchange] Increment isDirectionNegative check to next level for scalar direction
llvm/llvm-project pull request #78951
Opened 2024-01-22 09:09 UTC by ShivaChen

It could be an alternative way of https://github.com/llvm/llvm-project/pull/77719 to enable interchange for the following case.

    for (int nl = 0; nl < 10000000/256; nl++) // Level 1
      for (int i = 0; i < 256; ++i)                      // Level 2
        for (int j = 1; j < 256; j++)                    // Level 3
          aa[j][i] = aa[j - 1][i] + bb[j][i];

isDirectionNegative() is the function to detect `>` occur and enable normalize ().
It bail out due to the DV for Level 1 is a scalar instead of  `=`.
This commit increments the check to next level as `=` for scalar direction.

2024-01-22 20:54 UTC, Meinersbur commented
I would need a more convincing argument than "it makes my case work".

Suppose the scalar dependency is an implicit `<` dependencies. 
```
for (int i = 0; i < n; ++i)
  a=a/i;
```
This example would not be reversed because there is no inner level but consider this to be the "either way goes" case.
Reversing the scalar dependence would make a `>`-dependence out of it, which is definitely wrong because it would make it depend on the future (which `normalize()` is supposed to normalize).

Possibly, `normalize()` would also need to reverse the direction of scalar dependencies, but I would need some more thoughts on why

2024-01-23 14:49 UTC, bmahjour requested changes
Skipping the scalar direction is incorrect. Scalar dependencies get carried from every iteration to every iteration, so they **must** be treated more conservatively than a `=` dependence. 

I think this problem should be solved in the loop interchange pass itself where if the candidate pair of loops is nested inside other loops, and those outer loop IVs don't contribute to the index calculations in the pair of loops, then the dependence entries corresponding to the outer loops should be ignored.

2024-01-24 06:38 UTC, ShivaChen commented
> Skipping the scalar direction is incorrect. Scalar dependencies get carried from every iteration to every iteration, so they **must** be treated more conservatively than a `=` dependence.
> 
> I think this problem should be solved in the loop interchange pass itself where if the candidate pair of loops is nested inside other loops, and those outer loop IVs don't contribute to the index calculations in the pair of loops, then the dependence entries corresponding to the outer loops should be ignored.

Thanks for pointing the direction. :-)  Could you help me to check does the latest commit as you expected?

2024-01-24 18:35 UTC, bmahjour commented
> > Skipping the scalar direction is incorrect. Scalar dependencies get carried from every iteration to every iteration, so they **must** be treated more conservatively than a `=` dependence.
> > I think this problem should be solved in the loop interchange pass itself where if the candidate pair of loops is nested inside other loops, and those outer loop IVs don't contribute to the index calculations in the pair of loops, then the dependence entries corresponding to the outer loops should be ignored.
> 
> Thanks for pointing the direction. :-) Could you help me to check does the latest commit as you expected?

I'm saying let's not modify DependenceAnalysis. The custom handling should be done in Loop Interchange to ignore dependencies at outer levels when they don't matter to the legality of interchange.

2024-01-25 04:29 UTC, ShivaChen commented
> > > Skipping the scalar direction is incorrect. Scalar dependencies get carried from every iteration to every iteration, so they **must** be treated more conservatively than a `=` dependence.
> > > I think this problem should be solved in the loop interchange pass itself where if the candidate pair of loops is nested inside other loops, and those outer loop IVs don't contribute to the index calculations in the pair of loops, then the dependence entries corresponding to the outer loops should be ignored.
> > 
> > 
> > Thanks for pointing the direction. :-) Could you help me to check does the latest commit as you expected?
> 
> I'm saying let's not modify DependenceAnalysis. The custom handling should be done in Loop Interchange to ignore dependencies at outer levels when they don't matter to the legality of interchange.

I try to implement without modifying DependenceAnalysis and figure out that LoopInterchange rely on normalize() to enable few optimization opportunities. normalize() didn't happen because the outer loop is the initial value DVEntry::ALL.
Currently, normalize() is part of DependenceAnalysis which allow the function to update private DV variable.

Setting non-constributed(IV didn't affect instructions) loops direction to NONE for each dependency by scanning the SCEV form of the pointers of Src and Dst instructions instead of initial value ALL seems generally correct for DependenceAnalysis.

Or LoopInterchange should explore the way to legalize interchange without normalize? Thanks.

2024-01-25 21:17 UTC, bmahjour commented
> > > > Skipping the scalar direction is incorrect. Scalar dependencies get carried from every iteration to every iteration, so they **must** be treated more conservatively than a `=` dependence.
> > > > I think this problem should be solved in the loop interchange pass itself where if the candidate pair of loops is nested inside other loops, and those outer loop IVs don't contribute to the index calculations in the pair of loops, then the dependence entries corresponding to the outer loops should be ignored.
> > > 
> > > 
> > > Thanks for pointing the direction. :-) Could you help me to check does the latest commit as you expected?
> > 
> > 
> > I'm saying let's not modify DependenceAnalysis. The custom handling should be done in Loop Interchange to ignore dependencies at outer levels when they don't matter to the legality of interchange.
> 
> I try to implement without modifying DependenceAnalysis and figure out that LoopInterchange rely on normalize() to enable few optimization opportunities. normalize() didn't happen because the outer loop is the initial value DVEntry::ALL. Currently, normalize() is part of DependenceAnalysis which allow the function to update private DV variable.
> 
> Setting non-constributed(IV didn't affect instructions) loops direction to NONE for each dependency by scanning the SCEV form of the pointers of Src and Dst instructions instead of initial value ALL seems generally correct for DependenceAnalysis.
> 
> Or LoopInterchange should explore the way to legalize interchange without normalize? Thanks.

What would the semantics of `DVEntry::NONE` be? It cannot be treated less pessimistically than `ALL` because the same memory locations get modified in every iteration of the outer loop! It's important for DenepdenceAnalysis to remain conservatively correct in the results in produces, regardless of the consumer of that analysis. 

IMHO, how loop interchange deals with the "non-contributing" outer loops is an implementation issue inside loop-interchange itself. One solution might be to have its own normalize function, so you construct the dependence matrix, prune it (eg. by replacing the `*` with `=` in that entry), then normalize it again.

2024-01-26 10:07 UTC, ShivaChen commented
> > > > > Skipping the scalar direction is incorrect. Scalar dependencies get carried from every iteration to every iteration, so they **must** be treated more conservatively than a `=` dependence.
> > > > > I think this problem should be solved in the loop interchange pass itself where if the candidate pair of loops is nested inside other loops, and those outer loop IVs don't contribute to the index calculations in the pair of loops, then the dependence entries corresponding to the outer loops should be ignored.
> > > > 
> > > > 
> > > > Thanks for pointing the direction. :-) Could you help me to check does the latest commit as you expected?
> > > 
> > > 
> > > I'm saying let's not modify DependenceAnalysis. The custom handling should be done in Loop Interchange to ignore dependencies at outer levels when they don't matter to the legality of interchange.
> > 
> > 
> > I try to implement without modifying DependenceAnalysis and figure out that LoopInterchange rely on normalize() to enable few optimization opportunities. normalize() didn't happen because the outer loop is the initial value DVEntry::ALL. Currently, normalize() is part of DependenceAnalysis which allow the function to update private DV variable.
> > Setting non-constributed(IV didn't affect instructions) loops direction to NONE for each dependency by scanning the SCEV form of the pointers of Src and Dst instructions instead of initial value ALL seems generally correct for DependenceAnalysis.
> > Or LoopInterchange should explore the way to legalize interchange without normalize? Thanks.
> 
> What would the semantics of `DVEntry::NONE` be? It cannot be treated less pessimistically than `ALL` because the same memory locations get modified in every iteration of the outer loop! It's important for DenepdenceAnalysis to remain conservatively correct in the results in produces, regardless of the consumer of that analysis.
> 
> IMHO, how loop interchange deals with the "non-contributing" outer loops is an implementation issue inside loop-interchange itself. One solution might be to have its own normalize function, so you construct the dependence matrix, prune it (eg. by replacing the `*` with `=` in that entry), then normalize it again.

Have created normalize function in interchange. Thanks for the advice. :-)

2024-01-26 10:19 UTC, ShivaChen commented
Fix clang-format and rebase.

2024-09-17 15:02 UTC, madhur13490 commented on llvm/lib/Transforms/Scalar/LoopInterchange.cpp
> +static bool normalize(std::vector<Dependence::DVEntry> &DV, ScalarEvolution *SE,
I am learning this transformation and came across your patch. 

This function is sort of duplicate of FullDependece::normalize() but does not update the distance vector. Do you think we should avoid duplication? and updating distance vector is not necessary?

2025-05-05 06:29 UTC, closed without merging