mark std::make_format_args with clang::lifetimebound attribute
llvm/llvm-project pull request #78997
Opened 2024-01-22 15:59 UTC by kelbon

Inspired by:

https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2023/p2905r2.html

[[clang::lifetimebound]] is great, it may be very useful in many places of standard library

how it will work:

https://godbolt.org/z/dqj5eazMn

2024-01-22 18:21 UTC, mordante requested changes
Thanks for your patch. Can you add a verify test that this warning is show. I expect we should do the same for `make_wformat_args`?

Can you please make your e-mail address visible? We like to merge commits with the proper attribution.

2024-01-28 18:56 UTC, mordante commented
> > Thanks for your patch. Can you add a verify test that this warning is show. I expect we should do the same for `make_wformat_args`?
> > Can you please make your e-mail address visible? We like to merge commits with the proper attribution.
> 
> Can you please say what this test (Check libc++ generated files) do? Or where documentation about it?)

It's this command
```
grep -rn '[^ -~]' libcxx/include libcxx/src libcxx/test libcxx/benchmarks --exclude '*.dat' --exclude '*unicode*.cpp' --exclude '*print*.sh.cpp' --exclude 'escaped_output.*.pass.cpp' --exclude format_tests.h --exclude format.functions.tests.h --exclude 'formatter.*.pass.cpp' --exclude grep.pass.cpp --exclude locale-specific_form.pass.cpp --exclude ostream.pass.cpp --exclude transcoding.pass.cpp --exclude underflow.pass.cpp
```

Did you use clang-format?

> About email - dont want to make it public now, i have already commits in llvm and it seem to not be required

This thread talks about hidden addresses
https://discourse.llvm.org/t/hidden-emails-on-github-should-we-do-something-about-it/74223
and it was revived again recently
https://discourse.llvm.org/t/hidden-emails-on-github-should-we-do-something-about-it/74223/26

not being able to contact the author of a patch is an issue for the LLVM project.

2024-01-28 19:19 UTC, kelbon commented
> Did you use clang-format?

Yes ofcourse

2024-02-25 19:02 UTC, philnik777 commented on libcxx/include/__format/format_functions.h
> +make_format_args(_Args&... __args _LIBCPP_LIFETIMEBOUND) {
```suggestion
make_format_args(_LIBCPP_LIFETIMEBOUND _Args&... __args) {
```
Same below, just to keep it consistent across the code base.

2024-02-25 19:02 UTC, philnik777 commented on libcxx/test/libcxx/diagnostics/format.lifetimebound_extensions.verify.cpp
> +// Check that format functions are marked [[clang::lifetimebound]] as a conforming extension
Please add the license header.

2024-02-25 19:54 UTC, kelbon commented on libcxx/test/libcxx/diagnostics/format.lifetimebound_extensions.verify.cpp
> +// Check that format functions are marked [[clang::lifetimebound]] as a conforming extension
added

2024-02-27 11:26 UTC, philnik777 commented
Why did you close this PR?

2024-02-27 11:52 UTC, philnik777 commented
I think a rebase on top of main should fix any problems. If you don't have time for that, feel free to say so and I'll finish up the PR.

2024-02-27 12:20 UTC, kelbon commented
> I think a rebase on top of main should fix any problems. If you don't have time for that, feel free to say so and I'll finish up the PR.

no, not such problems, there are was something about incorrect whtespace symbols (grep check)

2024-05-17 17:06 UTC, MaskRay commented
https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-email-preferences/setting-your-commit-email-address Have you made your email address non-private? (https://discourse.llvm.org/t/hidden-emails-on-github-should-we-do-something-about-it/74223/32?u=maskray)

2024-07-10 17:03 UTC, mordante commented
@kelbon  do you want to make your e-mail public and pursue this patch?

2026-06-17 08:44 UTC, closed without merging