[InstCombine] Precommit test for #79417. NFC.
llvm/llvm-project pull request #79418
Opened 2024-01-25 07:56 UTC by bzEq

2024-01-25 08:34 UTC, ecnelises commented on llvm/test/CodeGen/PowerPC/absdiff.ll
> +define  i64 @absdiff(i64 %0, i64 %1) {
Will the combination differ by triple? If this is `opt` change, I don't think we should mix `opt` runlines in codegen test to 'prove' combine result is better.

2024-01-25 14:30 UTC, RKSimon requested changes
Please don't put instcombine tests in codegen

2024-01-26 05:09 UTC, bzEq commented
Put codegen comparison in #79417 .

2024-01-26 06:25 UTC, ecnelises commented
If this IR sequence doesn't change after instcombine currently, you can just add it in the patch. Also, maybe you can put it in files like `abs-1.ll` or `abs_abs.ll`.

2024-02-02 01:40 UTC, bzEq commented
Put tests directly in #79417.

2024-02-02 01:40 UTC, closed without merging