[analyzer] Avoid a crash in a debug printout function
llvm/llvm-project pull request #79446
Opened 2024-01-25 13:35 UTC by NagyDonat

Previously the function `RangeConstraintManager::printValue()` crashed when it encountered an empty rangeset (because `RangeSet::getBitwidth()` and `RangeSet::isUnsigned()` assert that the rangeset is not empty). This commit adds a special case that avoids this behavior.

As `printValue()` is only used by the checker debug.ExprInspection (and during manual debugging), the impacts of this commit are very limited.

2024-01-25 15:06 UTC, steakhal commented
When is it possible to have an empty range set as a constraint?

2024-01-25 15:19 UTC, NagyDonat commented
When I added `RangeConstraintManager::printValue()` calls at the top of `evalBinOpNN` (while doing printf-style debugging), I got crashes from the test files `infeasible-sink.c` and `constant-folding-crash.cpp`. I'd guess that getting an empty range set stops the analysis quickly (perhaps via a PosteriorlyOverconstrained state?), but apparently my debug printout was in a location that crashed before this could happen.

2024-01-25 15:23 UTC, steakhal requested changes

2024-01-25 15:23 UTC, steakhal commented on clang/lib/StaticAnalyzer/Core/RangeConstraintManager.cpp
> +  }
```suggestion
  if (RS.isEmpty()) {
    Out << "<empty rangeset>";
    return;
  }
  Out << RS.getBitWidth() << (RS.isUnsigned() ? "u:" : "s:");
  RS.dump(Out);
```

2024-01-25 15:37 UTC, steakhal approved these changes

2024-01-25 16:03 UTC, merged

2024-03-06 16:53 UTC, steakhal commented
I'm thinking of backporting this to clang-18, but given that it's only developer-facing, I don't think it worth it.
WDYT @NagyDonat?

2024-03-06 16:58 UTC, NagyDonat commented
Yup, there is no need to backport this.