[mlir][EmitC] Add `verbatim` op
llvm/llvm-project pull request #79584
Opened 2024-01-26 11:54 UTC by simon-camp

The `verbatim` operation produces no results and the value is emitted as is durung translation. If `trailing_semicolon` is present an additional semicolon is emitted.

Note: Use with caution. This operation can have arbitrary effects on the semantics of the emitted code. Use semantically more meaningful operations whenever possible. Additionally this op is *NOT* intended to be used to inject large snippets of code.

This operation can be used in situations where a more suitable operation is not yet implemented in the dialect or where preprocessor directives interfere with the structure of the code.

2024-01-26 12:49 UTC, marbre requested changes
Thanks @simon-camp :) As we've already discussed this offline for quite a while, I don't have much to say. From a first quick review, there are only minor things to change.

2024-01-26 12:49 UTC, marbre commented on mlir/test/Dialect/EmitC/invalid_ops.mlir
> +}
Missing newline at EOF.

2024-01-26 12:49 UTC, marbre commented on mlir/test/Dialect/EmitC/ops.mlir
> +emitc.verbatim "typedef float f32" trailing_semicolon
Do you want to add one of those or even both to the example in the description?

2024-01-30 19:57 UTC, AlexDenisov commented
This is very useful!

Out of curiosity, what makes the `trailing_semicolon` necessary? Isn't it easier to include `;` into the string itself, and the overcome the validation by adding a space at the end of the string?

2024-01-31 04:27 UTC, jpienaar commented
> This is very useful!
> 
> Out of curiosity, what makes the `trailing_semicolon` necessary? Isn't it easier to include `;` into the string itself, and the overcome the validation by adding a space at the end of the string?

+1, could the attribute be avoided?

2024-01-31 08:16 UTC, marbre commented on mlir/include/mlir/Dialect/EmitC/IR/EmitC.td
> +    followed by a '\n' character during translation.
```suggestion
   followed by a line break  '\n' character during translation.
```

2024-01-31 08:25 UTC, simon-camp commented
> This is very useful!
> 
> Out of curiosity, what makes the `trailing_semicolon` necessary? Isn't it easier to include `;` into the string itself, and the overcome the validation by adding a space at the end of the string?

Good suggestion, thank you.

I'm not sure I follow the validation part. The semicolon is now part of the attribute, so there is nothing to verify. Nonetheless this made me think of the implicit `\n` generated during emission, so this is now mentioned in the op description.

2024-01-31 10:54 UTC, marbre approved these changes

2024-01-31 10:56 UTC, merged