[libc++][ranges] implement `std::ranges::zip_transform_view`
llvm/llvm-project pull request #79605
Opened 2024-01-26 15:16 UTC by huixie90

2025-05-30 07:28 UTC, frederick-vs-ja commented on libcxx/docs/Status/RangesViews.csv
> +C++23,`zip_transform <https://wg21.link/P2321R2>`_,Hui Xie,No patch yet,✅
This PR seems very near to complete now. `RangesViews.csv` and `ZipProjects.csv` are now deleted. We should rebase/merge with the changes dropped.

2025-07-04 17:49 UTC, ldionne reviewed
Let's rebase this onto `main` and on top of the latest standard. We can take a look in our next 1:1.

2025-07-04 17:49 UTC, ldionne commented on libcxx/docs/Status/RangesViews.csv
> +C++23,`zip_transform <https://wg21.link/P2321R2>`_,Hui Xie,No patch yet,✅
```suggestion
C++23,`zip_transform <https://wg21.link/P2321R2>`_,Hui Xie,https://github.com/llvm/llvm-project/pull/79605,✅
```

2025-07-04 17:49 UTC, ldionne commented on libcxx/include/__ranges/zip_transform_view.h
> +concept __base_forward = forward_range<__maybe_const<_Const, zip_view<_Views...>>>;
I feel like this may not pull its weight. Why not inline it?

2025-07-10 08:40 UTC, frederick-vs-ja commented on libcxx/docs/Status/Cxx23Issues.csv
> +"`LWG3798 <https://wg21.link/LWG3798>`__","Rvalue reference and ``iterator_category``","2022-11 (Kona)","|Partial|","","``join_with_view``, and ``adjacent_transform_view`` haven't been done yet since
`join_view` was implemented recently (#65536), and the part related to LWG3798 was also implemented.

https://github.com/llvm/llvm-project/blob/2e38beebcf3766200e4b0c435a5729eea347b9bf/libcxx/include/__ranges/join_with_view.h#L167-L169

```suggestion
"`LWG3798 <https://wg21.link/LWG3798>`__","Rvalue reference and ``iterator_category``","2022-11 (Kona)","|Partial|","","``adjacent_transform_view`` hasn't been done yet since this type isn't implemented yet"
```

2025-07-11 18:02 UTC, ldionne requested changes

2025-07-11 18:02 UTC, ldionne commented on libcxx/test/std/ranges/range.adaptors/range.zip.transform/ctor.views.pass.cpp
> +  //static_assert(test());
Oversight?

2025-07-11 18:02 UTC, ldionne commented on libcxx/test/std/ranges/range.adaptors/range.zip.transform/ctor.views.pass.cpp
> +  {
IMO we should have tests for 1, 2, 3 and maybe 4 ranges. You already have 2 and 3.

2025-07-11 18:02 UTC, ldionne commented on libcxx/test/std/ranges/range.adaptors/range.zip.transform/begin.pass.cpp
> +  int buffer[8] = {1, 2, 3, 4, 5, 6, 7, 8};
I'd like to have an actual runtime test for 1, 2 and 3 views.

Also, a test where you put an empty view in position 0, 1 and 2.

2025-07-11 18:02 UTC, ldionne commented on libcxx/test/std/ranges/range.adaptors/range.zip.transform/end.pass.cpp
> +  test();
Same comments for 1, 2 and 3 will apply here. Also for the empty view in 0, 1 and 2 positions.

2025-07-11 18:02 UTC, ldionne commented on libcxx/test/std/ranges/range.adaptors/range.zip.transform/size.pass.cpp
> +    // single range
Let's also test with an empty range in various positions, and with a single empty range.

2025-07-11 18:02 UTC, ldionne commented on libcxx/test/std/ranges/range.adaptors/range.zip.transform/ctad.compile.pass.cpp
> +struct Container {
```suggestion
#include "types.h"

struct Container {
```

2025-07-11 18:02 UTC, ldionne commented on libcxx/test/std/ranges/range.adaptors/range.zip.transform/types.h
This seems to be more or less a copy of `libcxx/test/std/ranges/range.adaptors/range.zip/types.h` with a bit more stuff in it. Can we share instead?

2025-07-11 18:02 UTC, ldionne commented on libcxx/test/std/ranges/range.adaptors/range.zip.transform/iterator/ctor.other.pass.cpp
> +    // underlying non-const to const not convertible
```suggestion
    // Check when we can't perform a non-const-to-const conversion of the ziperator
```

2025-07-11 18:02 UTC, ldionne commented on libcxx/include/__ranges/zip_transform_view.h
> +    return [this](const auto&... __iters) noexcept(
I would suggest capturing the function object directly, it seems easier to follow from a "is it dangling?" perspective.

```
[&__fun = *__parent_->__fun_](const auto&... __iters) { ... }
```

That way you end up with a lambda that captures only a function object that lives inside the parent view -- seems more direct.

2025-07-11 18:02 UTC, ldionne commented on libcxx/test/std/ranges/range.adaptors/range.zip.transform/iterator/deref.pass.cpp
> +  std::array a{1, 2, 3, 4};
I find this a bit light on the runtime testing. For example you could make sure that dereferencing an iterator twice within its lifetime works. And also maybe increment the iterator before dereferencing it again (in another test).

2025-07-11 18:02 UTC, ldionne commented on libcxx/test/std/ranges/range.adaptors/range.zip.transform/iterator/member_types.compile.pass.cpp
> +  int buffer[] = {1, 2, 3, 4};
Do you have a test that there's no `iterator_category` if the underlying range isn't a forward range? https://eel.is/c++draft/range.zip.transform#iterator-1

2025-07-11 18:02 UTC, ldionne commented on libcxx/test/std/ranges/range.adaptors/range.zip.transform/types.h
> +};
IMO this is small enough that we should define it in each TU where it's used. Otherwise it's less readable to have to jump around just to see this simple definition.

2025-07-11 18:02 UTC, ldionne commented on libcxx/test/std/ranges/range.adaptors/range.zip.transform/sentinel/eq.pass.cpp
> +  {
Let's test comparison with a `zip_transform_view` over a single range? Also an empty range?

2025-07-11 18:02 UTC, ldionne commented on libcxx/test/std/ranges/range.adaptors/range.zip.transform/iterator/subscript.pass.cpp
> +    std::ranges::zip_transform_view v(MakeTuple{}, SizedRandomAccessView{buffer}, std::views::iota(0));
Can you add more runtime testing as requested in some of the other tests?

2025-07-11 18:03 UTC, ldionne commented on libcxx/docs/Status/Cxx23Issues.csv
Let's also add a release note and make sure to mention any GH issue that this may close in the commit message.

2025-07-13 12:32 UTC, huixie90 commented on libcxx/docs/Status/Cxx23Issues.csv
added link to this PR in the check lists of https://github.com/llvm/llvm-project/issues/105169

2025-07-18 17:25 UTC, ldionne approved these changes
LGTM with small comments applied and green CI. Thanks a lot!

2025-07-18 17:25 UTC, ldionne commented on libcxx/docs/ReleaseNotes/21.rst
> +- P2321R2: ``zip`` (`Github <https://github.com/llvm/llvm-project/issues/105169>`__) (The paper is partially implemented. ``zip_transform_view`` is implemented in this release)
This should move to `22.rst` now.

2025-07-18 17:25 UTC, ldionne commented on libcxx/test/std/ranges/range.adaptors/range.zip.transform/cpo.pass.cpp
> +// std::views::zip_transform
I think we're missing some tests for the "function object" aspect of this CPO. For example, if `views::zip_transform` were not copy-constructible, this test would pass but you wouldn't be able to pass it to a higher-order function. I think we're missing an addition to https://github.com/llvm/llvm-project/blob/main/libcxx/test/std/library/description/conventions/customization.point.object/cpo.compile.pass.cpp.

2025-07-18 17:25 UTC, ldionne commented on libcxx/test/std/ranges/range.adaptors/types.h
>  //
Maybe rename this file to `range_adaptor_types.h` to avoid having a header named `types.h` living simply at different directory levels?

2025-07-18 17:25 UTC, ldionne commented on libcxx/test/std/ranges/range.adaptors/range.zip.transform/types.h
> +#endif // TEST_STD_VER <= 20
```suggestion
#endif
```

2025-07-18 17:27 UTC, ldionne commented on libcxx/docs/Status/Cxx23Issues.csv
> +"`LWG3702 <https://wg21.link/LWG3702>`__","Should ``zip_transform_view::iterator`` remove ``operator<``","2022-07 (Virtual)","|Complete|","21",""
```suggestion
"`LWG3702 <https://wg21.link/LWG3702>`__","Should ``zip_transform_view::iterator`` remove ``operator<``","2022-07 (Virtual)","|Complete|","22",""
```

2025-07-18 17:27 UTC, ldionne commented on libcxx/docs/Status/Cxx23Issues.csv
> +"`LWG3773 <https://wg21.link/LWG3773>`__","``views::zip_transform`` still requires ``F`` to be ``copy_constructible`` when empty pack","2022-11 (Kona)","|Complete|","21",""
```suggestion
"`LWG3773 <https://wg21.link/LWG3773>`__","``views::zip_transform`` still requires ``F`` to be ``copy_constructible`` when empty pack","2022-11 (Kona)","|Complete|","22",""
```

2025-07-20 08:13 UTC, merged