[libc] abs is a const function
llvm/llvm-project pull request #79650
Opened 2024-01-26 21:23 UTC by AtariDreams

2024-01-26 21:28 UTC, jhuber6 commented
@michaelrj-google Do we have a formalized way to specify attributes? My gut says it should go in `libc/spec/stdc.td` but I remember hearing there was some desire to move away from tablegen?

2024-01-26 21:29 UTC, AtariDreams commented
> @michaelrj-google Do we have a formalized way to specify attributes? My gut says it should go in `libc/spec/stdc.td` but I remember hearing there was some desire to move away from tablegen?

I have no idea how to do it in tablegen

2024-01-26 21:29 UTC, jhuber6 commented
As it stands, this won't be exported. The header modified is simply the internal header. The installed ones go through a tool called `lib-hdrgen` which uses LLVM TableGen to spit the definitions out into where `%%public_api()` is.

2024-01-26 21:30 UTC, SchrodingerZhu requested changes

2024-01-26 21:30 UTC, SchrodingerZhu commented on libc/src/stdlib/abs.h
> +__attribute__((__const__)) int abs(int n);
`[[gnu::const]]`

2024-01-26 21:30 UTC, jhuber6 commented
> I have no idea how to do it in tablegen

I was asking Michael, because I recall that this is an existing issue that the infrastructure hasn't solved yet. I had problems earlier where it conflicted with a lot of GNU definitions that expect things like `pure` or similar.

2024-01-26 21:36 UTC, SchrodingerZhu commented
We have internal versions of math kernels `LIBC_NAMESPACE`. I think it is legitimate to add additional attributes to these internal versions of these functions if found helpful. Addition non-standard attributes to exposed version as specified in spec sometimes will lead problems.

2024-01-26 21:42 UTC, SchrodingerZhu approved these changes
This approval is to dismiss previous "Request changes". I don't know how to dismiss a "Request changes" without approving the PR.

2024-02-04 06:01 UTC, closed without merging

2024-02-05 10:30 UTC, nickdesaulniers commented
Isn't https://github.com/llvm/llvm-project/pull/79891 trying to add generalized support for attributes?

2024-02-05 12:56 UTC, jhuber6 commented
> Isn't #79891 trying to add generalized support for attributes?

I think the attributes on the installed headers and the internal headers are separate.