[BDCE] Handle multi-use `select` of `and`s on demanded bits
llvm/llvm-project pull request #79688
Opened 2024-01-27 10:45 UTC by antoniofrighetto

Simplify multi-use `select` of `and`s  when these last do not affect the demanded bits being considered.

Fixes: https://github.com/llvm/llvm-project/issues/78596.

Proofs: https://alive2.llvm.org/ce/z/BBdrCz.

2024-01-27 11:15 UTC, dtcxzyw commented on llvm/lib/Transforms/Scalar/BDCE.cpp
> +            continue;
```suggestion
          const APInt* Mask;
          if (!match(U, m_OneUse(m_And(m_Specific(&I), m_APInt(Mask)))))
            continue;
```

2024-01-27 11:15 UTC, dtcxzyw commented on llvm/lib/Transforms/Scalar/BDCE.cpp
> +        for (Use &U : I.operands()) {
```suggestion
        for (Use &U : I.operands().drop_front()) {
```

2024-01-27 11:15 UTC, dtcxzyw commented on llvm/lib/Transforms/Scalar/BDCE.cpp
> +          if ((Mask | ~Demanded).isAllOnes()) {
```suggestion
          if (Demanded.isSubsetOf(Mask)) {
```
It would be clearer than the original.

2024-01-27 11:15 UTC, dtcxzyw commented on llvm/lib/Transforms/Scalar/BDCE.cpp
> +            Changed = true;
```suggestion
            ++NumSimplified;
            Changed = true;
```

2024-01-27 12:35 UTC, nikic requested changes
...wat? This should not be looking at selects. You should only be looking at the demanded bits of the and.

2024-01-27 13:55 UTC, antoniofrighetto commented
Could you kindly provide an example showing how not restricting this to the `select` may be beneficial? We don't need to specialize it for the `select`, but restricting the input space looked reasonable to me.

> You should only be looking at the demanded bits of the and.

You mean we should only be looking at the demanded bits of the instruction itself when the operand analyzed is the `and`? I don't see how the optimization can take place if the instruction examined is not the multi-use instruction.

2024-01-27 14:12 UTC, nikic commented
> Could you kindly provide an example showing how not restricting this to the `select` may be beneficial? We don't need to specialize it for the `select`, but restricting the input space looked reasonable to me.

You can replace the select with pretty much any instruction that transfers demanded bits, e.g. https://alive2.llvm.org/ce/z/om-5yP.

> 
> > You should only be looking at the demanded bits of the and.
> 
> You mean we should only be looking at the demanded bits of the instruction itself when the operand analyzed is the `and`? I don't see how the optimization can take place if the instruction examined is not the multi-use instruction.

I would expect you to query the demanded bits of the `and` instruction, similar to the code directly above that handles `sext`. Unless I'm missing something, that will cover the motivating pattern.

2024-01-27 14:18 UTC, XChy commented
For a single BDCE pass, I think a minimal testcase can be like:
```llvm
define void @src(i64 %a) {
entry:
  %and = and i64 %a, 24
  %ret1 = and i64 %and, 8
  %ret2 = and i64 %and, 16
  call void @use(i64 %ret1)
  call void @use(i64 %ret2)
  ret void
}

define void @tgt(i64 %a) {
entry:
  %ret1 = and i64 %a, 8
  %ret2 = and i64 %a, 16
  call void @use(i64 %ret1)
  call void @use(i64 %ret2)
  ret void
}
```

2024-01-27 18:33 UTC, antoniofrighetto commented on llvm/lib/Transforms/Scalar/BDCE.cpp
> +            Changed = true;
Thanks, must have gone away accidentally while rebasing.

2024-01-27 18:33 UTC, antoniofrighetto commented on llvm/lib/Transforms/Scalar/BDCE.cpp
> +          if (!And || !And->hasOneUse() || And->getOpcode() != Instruction::And)
Sure, thanks, adding it too.

2024-01-27 18:35 UTC, antoniofrighetto commented
> I would expect you to query the demanded bits of the and instruction, similar to the code directly above that handles sext. Unless I'm missing something, that will cover the motivating pattern.

Reviewed, thanks, somehow I thought it would be easier to handle the `and`/`or` as operands of the instruction being analyzed (and get its current demanded bits).

2024-01-28 03:24 UTC, XChy commented on llvm/lib/Transforms/Scalar/BDCE.cpp
> +                (Opc == Instruction::Or && !Demanded.intersects(Mask))) {
```suggestion
          const APInt *Mask;
          if (match(BO->getOperand(1), m_APInt(Mask))) {
            if ((Opc == Instruction::And && Demanded.isSubsetOf(*Mask)) ||
                (Opc == Instruction::Or && !Demanded.intersects(*Mask))) {
```
Match m_APInt to handle the splat.

2024-01-28 03:24 UTC, XChy commented on llvm/lib/Transforms/Scalar/BDCE.cpp
> +      if (Opc == Instruction::And || Opc == Instruction::Or) {
Could you turn it into a switch, please? I think there is room for other operators like `xor`, `add` to be here in the future.

2024-01-28 08:41 UTC, nikic reviewed
Thanks, this looks a lot more like what I had in mind.

2024-01-28 08:41 UTC, nikic commented on llvm/test/Transforms/BDCE/and-or-multiuse.ll
> +  %or = or i64 %and1, %and2
Can you please add a test variant with `or disjoint`, to show that the flag gets dropped correctly?

2024-01-28 08:41 UTC, nikic commented on llvm/test/Transforms/BDCE/dead-uses.ll
> -; CHECK-NEXT:    [[X:%.*]] = or i32 [[A:%.*]], 0
Can you change the `or` operand to  `1` (or something else that doesn't optimize away) instead? Dropping it is not really the point of this tests.

2024-01-29 07:24 UTC, antoniofrighetto commented
Reviewed, thanks.

2024-01-29 13:18 UTC, nikic approved these changes
LGTM

2024-01-29 14:49 UTC, XChy approved these changes
LGTM.

2024-01-29 18:07 UTC, merged