[InstCombine] Loosen one-use restriction if common operand is constant
llvm/llvm-project pull request #79767
Opened 2024-01-28 20:38 UTC by AtariDreams

2024-01-30 21:12 UTC, AtariDreams commented
@nikic Ready!

2024-02-13 16:57 UTC, nikic requested changes

2024-02-13 16:57 UTC, nikic commented on llvm/test/Transforms/InstCombine/xor-and-or.ll
> +}
Result is the same without your change: https://llvm.godbolt.org/z/debfW4WqY

2024-02-13 16:57 UTC, nikic commented on llvm/lib/Transforms/InstCombine/InstCombineAndOrXor.cpp
> +      return BinaryOperator::CreateAnd(Builder.CreateXor(B, C), NotA);
It's not possible to remove one-use entirely. This may replace one instruction with two instructions.

2024-02-13 17:00 UTC, nikic commented
Loosening this one-use restriction does not seem particularly valuable, and is not worth babysitting this PR.

2024-02-13 17:00 UTC, closed without merging