Use relative includes to allow source-based dependencies without `-I`
llvm/llvm-project pull request #80443
Opened 2024-02-02 15:10 UTC by georgthegreat

We store libunwind code inside monorepo and would like to reduce the overall amount of `-I` flags.

2024-02-02 15:19 UTC, ldionne requested changes
We require that the right paths be setup with `-I` or `-isystem` as a general requirement of libc++, libc++abi and libunwind. This change seems brittle to me, especially if there's no test or no official guarantee being added and documented.

Basically, this might fix things for you in the immediate term, but it's really just a band-aid and it will break again in the future. Can you please provide more context about your use case and what official change you'd like us to make (now, but also going forward in the code base). Then, if we agree this is worth pursuing, we should set up some kind of test that allows us to provide that property in a guaranteed way and not regress it.

2024-02-02 16:11 UTC, georgthegreat commented
We have pretty large codebase and we use custom command-graph based build system (consider bazel as a well-known example of such buld system). The system uses module as a basic unit, modules might depend one each other, dependencies might affect dependant modules (but not vise versa).

In order to reduce the total size of the command graph, we would like to reduce the amount of `-I` flags induced by the most common modules.

libunwind is one of such modules: almost every module transitively depend on it yet very little do include `unwind.h` directly.

We include unwind.h using a repository-root-relative-path (i. e. `contrib/libs/libunwind/include/unwind.h`).
Everything else just works if we apply this patch.

2024-02-08 19:27 UTC, ldionne commented
Doing ad-hoc changes like that to provide an apparent guarantee without actually documenting it, testing it and enforcing it throughout is just churning the code base. Unless we actually have a plan to do that properly, I would push back this change. I understand you're just trying to fix your specific problem, but this is not a scalable way to handle changes in a project with so many users.

2024-02-08 19:38 UTC, georgthegreat commented
I am OK with fixing this particular guarantee with a test.

However, I am not familiar with libc++ testset organization and I need to be guided.
Could you, please, provide me with some clues to start wtih?

2024-02-09 00:59 UTC, arichardson reviewed
It does seem like all other libunwind sources use `#include "` to find headers that are part of libunwind, so I think doing it for the includes that are installed should also be fine. I don't think installing these headers into separate directories and adding custom -isystem flags is a supported build configuration. It will also ensure that we always pick the matching header rather than one that happens to come first in the include order.

2024-02-09 19:41 UTC, georgthegreat commented
@ldionne, do you find @arichardson reasoning good enough to proceed with merging this PR?

2024-02-28 17:08 UTC, georgthegreat commented
@ldionne, gentle ping

2024-05-22 10:16 UTC, georgthegreat commented
@ldionne, gentle ping

2024-05-22 17:48 UTC, ldionne commented
> @ldionne, do you find @arichardson reasoning good enough to proceed with merging this PR?

I'm not convinced. We use `#include <header>` pretty consistently in libc++ and libc++abi and we should strive for all the runtimes to be consistent. I am especially not convinced that the end goal (of avoiding a `-I` flag) is worthwhile.

2024-05-24 11:55 UTC, closed without merging