[GlobalISel] replace right identity X * -1.0 with fneg(x)
llvm/llvm-project pull request #80526
Opened 2024-02-03 04:27 UTC by nickleus27

follow up patch to #78673

@Pierre-vh @jayfoad @arsenm Could you review when you have a chance.

2024-02-03 13:20 UTC, phoebewang commented on llvm/test/CodeGen/X86/popcnt.ll
> +
The change seems unrelated, should better to revert.

2024-02-03 13:35 UTC, jayfoad requested changes
I don't think this is safe since fmul is an arithmetic operation that may quieten nans and flush denormals, whereas fneg is defined to just flip the sign bit.

See https://reviews.llvm.org/D109446 for the DAG equivalent.

2024-02-03 15:45 UTC, arsenm commented
> I don't think this is safe since fmul is an arithmetic operation that may quieten nans and flush denormals, whereas fneg is defined to just flip the sign bit.
> 
> See https://reviews.llvm.org/D109446 for the DAG equivalent.

This is OK, we are allowed to drop canonicalizes for non-strictfp functions. The DAG is too strict and I've been meaning to remove those restrictions

2024-02-04 21:00 UTC, tschuett commented
I believe that we should move to a visitOpcode model like the Dag combiner eventually. If this combine is registered before, `constant_fold_fp_binop`, then we get a `fneg`.  Otherwise, we may have gotten a constant for `fmul 1000,0 * -1`.

2024-02-06 14:28 UTC, Pierre-vh commented on llvm/include/llvm/Target/GlobalISel/Combine.td
> +    [{ return Helper.matchConstantFPOp(${y}, -1.0); }]),
Unfortunately not, it's also been on my list but I'm not sure how to handle them well. TableGen doesn't have float literals. I can see a few options:

- Add float literals to tablegen
- Parse them from strings using APFloat
- Only allow hex/integer immediates and bitconvert to FP

What do you prefer?

2024-02-06 17:45 UTC, arsenm commented on llvm/include/llvm/Target/GlobalISel/Combine.td
> +    [{ return Helper.matchConstantFPOp(${y}, -1.0); }]),
Not sure how much work adding float literals would be, but I assume that parsing them with APFloat would be an implementation detail of that.

2024-02-06 20:51 UTC, nickleus27 commented
> This is OK, we are allowed to drop canonicalizes for non-strictfp functions. The DAG is too strict and I've been meaning to remove those restrictions

Does this mean the matcher should be checking for FMafn flags or check that the function has UnsafeFPMath?

2024-02-08 10:25 UTC, arsenm commented
> > This is OK, we are allowed to drop canonicalizes for non-strictfp functions. The DAG is too strict and I've been meaning to remove those restrictions
> 
> Does this mean the matcher should be checking for FMafn flags or check that the function has UnsafeFPMath?

Neither. It would be a question of checking the parent function's denormal mode (could maybe consider unsafe flags, but none are an exact match). I think we need to loosen the DAG code, and this is fine (for non-strictfp functions, in which case this would be G_STRICT_FMUL so this wouldn't fire anyway)

2024-02-08 10:26 UTC, arsenm approved these changes
InstCombine already does this, and the DAG should resume doing this

2024-02-08 10:26 UTC, arsenm commented on llvm/test/CodeGen/AMDGPU/GlobalISel/combine-fpneg-one-fneg.mir
> +...
Vector case wouldn't hurt

2024-02-08 14:22 UTC, Pierre-vh commented
> I believe that we should move to a visitOpcode model like the Dag combiner eventually. If this combine is registered before, `constant_fold_fp_binop`, then we get a `fneg`. Otherwise, we may have gotten a constant for `fmul 1000,0 * -1`.

No, a `visitOpcode` model would be a regression compared to what we have now, IMHO.

I agree we need a way to tell the combiner which combine goes first. Currently I _think_ it's decided by the order in which the combines appear in the list, but I don't think it's actually enforced much (well, a bunch of tests check the match table as a whole so if its order changes, those tests will fail).

We can achieve ordering differently:

- Use a system like AddedComplexity, maybe with a bit more syntactic sugar, to tell which combine goes first.
- Allow a combine to explicitly mention some dependencies so it can't run unless something else has been checked first (probably overkill)
- etc.

Is it a concern/issue currently? Do we have bugs due to combine ordering?
If so, please create an issue. I don't mind looking into it and coming up with more detail proposals

2024-02-08 15:56 UTC, tschuett commented
A miscompile is caused by ordering issues:
https://github.com/llvm/llvm-project/issues/78383
Nonetheless, I would expect UNDEF and catching misbeviour be executed/registered before optimizations.

2024-02-09 09:56 UTC, jayfoad commented
> A miscompile is caused by ordering issues: #78383 Nonetheless, I would expect UNDEF and catching misbeviour be executed/registered before optimizations.

I think it's wrong to say that ordering issues _cause_ that problem. One of the combines is broken - that's what causes the problem. Ordering issues just happen to _hide_ the problem in some cases.

2024-02-09 10:03 UTC, tschuett commented
Agreed that combine is broken, but detecting misbehaviour is executed/registered after the buggy optimisation.

2024-02-21 09:28 UTC, jayfoad commented
No objection from me given @arsenm's comment about dropping canonicalizations. I thought this was already approved.

2024-02-21 09:35 UTC, nickleus27 commented
If everyone approves could someone go ahead and commit for me. I do not have write access. Thank you.

2024-02-21 09:41 UTC, jayfoad approved these changes

2024-02-21 09:41 UTC, merged