Resolve FIXME: Try SCEV getRange.
llvm/llvm-project pull request #80623
Opened 2024-02-05 00:01 UTC by AtariDreams

Using the range to see if it is a single constant value instead of seeing if there is a constant size is more accurate.

2024-02-05 08:54 UTC, dtcxzyw commented
Tests?

2024-02-13 16:53 UTC, nikic requested changes

2024-02-13 16:53 UTC, nikic commented on llvm/lib/CodeGen/SafeStack.cpp
> +  auto element = LenRange.getSingleElement();
There's no point to doing this if you're only going to handle single-element ranges.

2024-04-25 03:26 UTC, nikic requested changes
No tests

2024-09-10 13:10 UTC, closed without merging