[NewPM/CodeGen] Rewrite pass manager nesting
llvm/llvm-project pull request #81068
Opened 2024-02-08 00:57 UTC by aeubanks

Currently the new PM infra for codegen puts everything into a MachineFunctionPassManager. The MachineFunctionPassManager owns both Module passes and MachineFunction passes, and batches adjacent MachineFunction passes like a typical PassManager.

The current MachineFunctionAnalysisManager also directly references a module and function analysis manager to get results.

The initial argument was that the codegen pipeline is relatively "flat", meaning it's mostly machine function passes with a couple of module passes here and there. However, there are a couple of issues with this as compared to a more structured nesting more like the optimization pipeline. For example, it doesn't allow running function passes then machine function passes on a function and its machine function all at once. It also currently requires the caller to split out the IR passes into one pass manager and the MIR passes into another pass manager.

This patch rewrites the new pass manager infra for the codegen pipeline to be more similar to the nesting in the optimization pipeline. Basically, a Function contains a MachineFunction. So we can have Module -> Function -> MachineFunction adaptors. It also rewrites the analysis managers to have inner/outer proxies like the ones in the optimization pipeline. The new pass managers/adaptors/analysis managers can be seen in use in PassManagerTest.cpp.

This allows us to consolidate to just having to add to one ModulePassManager when using the codegen pipeline.

I haven't added the Function -> MachineFunction adaptor in this patch, but it should be added when we merge AddIRPass/AddMachinePass so that we can run IR and MIR passes on a function before proceeding to the next function.

The MachineFunctionProperties infra for MIR verification is still WIP.

2024-02-08 00:58 UTC, aeubanks commented
as mentioned in the description the MachineFunctionProperties  stuff is still WIP, but I'd like some eyes on this now

we should extend https://llvm.org/docs/NewPassManager.html to talk about the design of the codegen infra

2024-02-08 02:55 UTC, paperchalice reviewed
Thanks for doing this! Some comments.

2024-02-15 05:46 UTC, aeubanks commented on llvm/include/llvm/CodeGen/MachinePassManager.h
> +extern template class OuterAnalysisManagerProxy<ModuleAnalysisManager,
The parts about accessing outer analyses in https://llvm.org/docs/NewPassManager.html#using-analyses is still relevant for MachineFunction passes and Module analyses, so we should have these.

Agreed that MachineFunction passes should be able to query for Function analyses though.

2024-02-19 12:52 UTC, paperchalice requested changes

2024-02-20 21:37 UTC, aeubanks commented on llvm/tools/llc/NewPMDriver.cpp
> +    exit(1);
oops, bad merge

2024-02-20 21:41 UTC, aeubanks commented on llvm/tools/llc/NewPMDriver.cpp
> +    ExitOnErr(PB.parsePassPipeline(MPM, PassPipeline));
yes, although I'll leave that for a follow-up patch. added a FIXME

2024-02-21 02:47 UTC, paperchalice approved these changes

2024-02-22 20:02 UTC, alinas approved these changes
Thank you for working on this.

2024-02-22 20:47 UTC, merged