[lldb] Store proper integer bitwidth in Scalar Type
llvm/llvm-project pull request #81451
Opened 2024-02-12 08:45 UTC by kamleshbhalui

Storing Larger bitwidth causes problem when byteswapping.

2024-02-12 17:57 UTC, clayborg commented
What is the problem here? I tried to understand the description, but don't know what the issue is? Can we test this?

2024-02-12 18:35 UTC, bulbazord requested changes
This uses `DataExtractor::GetMaxU64` which already does this under the hood. What does this do that isn't already being done? It may help if you add a test case to show what you are trying to fix.

2024-02-13 06:44 UTC, kamleshbhalui commented
> This uses `DataExtractor::GetMaxU64` which already does this under the hood. What does this do that isn't already being done? It may help if you add a test case to show what you are trying to fix.

The problem with GetMaxU64 is that it always returns uint64_t even though actual type was uint32_t, so when byteswap is performed it becomes invalid integer, to fixed this we need to store correct bitwidth not higher.
i.e.
Suppose there is actual 32 bit integer i.e. 0xffffffff
`GetMaxU64` will return 0x00000000ffffffff (prmoted to uint64_t from uint32_t)
 and when performing byteswap on this it becomes 0xffffffff00000000 which is invalid.

2024-02-13 21:22 UTC, clayborg commented
> > This uses `DataExtractor::GetMaxU64` which already does this under the hood. What does this do that isn't already being done? It may help if you add a test case to show what you are trying to fix.
> 
> @clayborg @bulbazord The problem with GetMaxU64 is that it always returns uint64_t even though actual type was uint32_t, so when byteswap is performed it becomes invalid integer, to fixed this we need to store correct bitwidth not higher. i.e. Suppose there is actual 32 bit integer i.e. 0xffffffff `GetMaxU64` will return 0x00000000ffffffff (prmoted to uint64_t from uint32_t) and when performing byteswap on this it becomes 0xffffffff00000000 which is invalid.

So you are saying someone is taking the resulting Scalar and trying to byteswap it? Errors can still happen then in this class for int8_t/uint8_t and int16_t/uint16_t as there are no overloads for these in the `Scalar` class. We only currently have:
```
  Scalar(int v);
  Scalar(unsigned int v);
  Scalar(long v);
  Scalar(unsigned long v);
  Scalar(long long v);
  Scalar(unsigned long long v);
```
It would suggest if we are going to make a requirement that Scalar will hold the correct bit widths, then we need to stop using "int" and "long" and switch to using the `int*_t` and `uint*_t` typedefs to make things clear:
```
  Scalar(int8_t v);
  Scalar(int16_t v);
  Scalar(int32_t v);
  Scalar(int64_t v);
  Scalar(uint8_t v);
  Scalar(uint16_t v);
  Scalar(uint32_t v);
  Scalar(uint64_t v);
```
Then we have all of the bit widths handled correctly.

2024-02-13 21:23 UTC, clayborg commented
What code is taking a scalar and then trying to byte swap it after it has been created?

2024-02-14 11:35 UTC, kamleshbhalui commented
@clayborg @bulbazord 
we have extension in lldb to support cobol code debugging, we require byteswapping there. upstream version of lldb does not do byteswapping on scalar so no problem seen.

2024-02-14 11:51 UTC, kamleshbhalui commented
I think this PR https://reviews.llvm.org/D121408 introduced the current code, which causing the problem.

2024-02-14 11:51 UTC, kamleshbhalui commented
> > > This uses `DataExtractor::GetMaxU64` which already does this under the hood. What does this do that isn't already being done? It may help if you add a test case to show what you are trying to fix.
> > 
> > 
> > @clayborg @bulbazord The problem with GetMaxU64 is that it always returns uint64_t even though actual type was uint32_t, so when byteswap is performed it becomes invalid integer, to fixed this we need to store correct bitwidth not higher. i.e. Suppose there is actual 32 bit integer i.e. 0xffffffff `GetMaxU64` will return 0x00000000ffffffff (prmoted to uint64_t from uint32_t) and when performing byteswap on this it becomes 0xffffffff00000000 which is invalid.
> 
> So you are saying someone is taking the resulting Scalar and trying to byteswap it? Errors can still happen then in this class for int8_t/uint8_t and int16_t/uint16_t as there are no overloads for these in the `Scalar` class. We only currently have:
> 
> ```
>   Scalar(int v);
>   Scalar(unsigned int v);
>   Scalar(long v);
>   Scalar(unsigned long v);
>   Scalar(long long v);
>   Scalar(unsigned long long v);
> ```
> 
> It would suggest if we are going to make a requirement that Scalar will hold the correct bit widths, then we need to stop using "int" and "long" and switch to using the `int*_t` and `uint*_t` typedefs to make things clear:
> 
> ```
>   Scalar(int8_t v);
>   Scalar(int16_t v);
>   Scalar(int32_t v);
>   Scalar(int64_t v);
>   Scalar(uint8_t v);
>   Scalar(uint16_t v);
>   Scalar(uint32_t v);
>   Scalar(uint64_t v);
> ```
> 
> Then we have all of the bit widths handled correctly.

@clayborg I agree, we should use suggested type to fix it for all.

2024-02-14 17:46 UTC, adrian-prantl commented on lldb/source/Expression/DWARFExpression.cpp
> +  }
Can this be tested?

2024-02-14 18:26 UTC, bulbazord commented
> @clayborg @bulbazord we have extension in lldb to support cobol code debugging, we require byteswapping there. upstream version of lldb does not do byteswapping on scalar so no problem seen.

Maybe not, but this should still be testable with a unit test. If somebody modifies or refactors this code in the future without a test, this might break in a similar way and you would have to do all this work again. :)

2024-02-14 19:26 UTC, clayborg commented
I am fine with this patch if we fix the Scalar class to obey the bit width as suggested above. I do worry though that other Scalar values in the expression might get set to 64 bit values all of the time and cause problems with DWARF expressions. Do you have a code snippet of where this is used where you rely on the bit width? Usually `DW_OP_*` opcodes act on a pointer width integer, but some do actually specify a width (some of the deref operations).

2024-02-15 01:52 UTC, kamleshbhalui commented
> > @clayborg @bulbazord we have extension in lldb to support cobol code debugging, we require byteswapping there. upstream version of lldb does not do byteswapping on scalar so no problem seen.
> 
> Maybe not, but this should still be testable with a unit test. If somebody modifies or refactors this code in the future without a test, this might break in a similar way and you would have to do all this work again. :)

Will try to write a unit test for same.

2024-02-15 01:52 UTC, kamleshbhalui commented on lldb/source/Expression/DWARFExpression.cpp
> +  }
I will write a unit test.

2024-02-15 02:16 UTC, kamleshbhalui commented
> I am fine with this patch if we fix the Scalar class to obey the bit width as suggested above. I do worry though that other Scalar values in the expression might get set to 64 bit values all of the time and cause problems with DWARF expressions. Do you have a code snippet of where this is used where you rely on the bit width? Usually `DW_OP_*` opcodes act on a pointer width integer, but some do actually specify a width (some of the deref operations).

Yes here it is https://github.com/llvm/llvm-project/blob/main/llvm/lib/Support/APInt.cpp#L715.

2026-06-30 06:01 UTC, closed without merging