[clang-tidy] fix incorrect hint for InitListExpr in prefer-member-initializer
llvm/llvm-project pull request #81560
Opened 2024-02-13 01:16 UTC by HerrCai0907

Fixes: #77684.

2024-02-13 14:36 UTC, 5chmidti requested changes
Just two nits.

2024-02-13 14:36 UTC, 5chmidti commented on clang-tools-extra/clang-tidy/cppcoreguidelines/PreferMemberInitializerCheck.cpp
> +    bool AddBracket = false;
Brackets are `[]`, use brace (`{}`).

2024-02-13 14:36 UTC, 5chmidti commented on clang-tools-extra/test/clang-tidy/checkers/cppcoreguidelines/prefer-member-initializer.cpp
> +}
These `CHECK-FIXES` could be written without regex, which would make them more readable.

2024-02-13 15:32 UTC, 5chmidti reviewed
FYI: I have found a false-negative that is unrelated to this pr and issue, but my fix builds upon your pr. I filed an issue for it here #81613 and will post a pr once yours in merged, I don't want to make a stack just for that fix.

2024-02-13 15:32 UTC, 5chmidti commented on clang-tools-extra/clang-tidy/cppcoreguidelines/PreferMemberInitializerCheck.cpp
> +        AddBracket = isa<InitListExpr>(Init->getInit());
This could be inside the else-branch right above, right?

2024-02-15 15:59 UTC, 5chmidti approved these changes

2024-02-15 16:31 UTC, PiotrZSL approved these changes
LGTM

2024-02-16 01:18 UTC, merged