[AMDGPU] Let LowerModuleLDS run twice on the same module
llvm/llvm-project pull request #81729
Opened 2024-02-14 12:09 UTC by Pierre-vh

If all variables in the module are absolute, this means we're running the pass again on an already lowered module, and that works.
If none of them are absolute, lowering can proceed as usual.
Only diagnose cases where we have a mix of absolute/non-absolute GVs, which means we added LDS GVs after lowering, which is broken.

See #81491
Split from #75333

2024-02-21 14:20 UTC, JonChesterfield requested changes

2024-02-21 14:20 UTC, JonChesterfield commented on llvm/lib/Target/AMDGPU/AMDGPULowerModuleLDSPass.cpp
> +  std::optional<bool> HasAbsoluteGVs;
This is only used by one function, make it a local variable and reinstate the static annotations. Minimising scope of mutable state is important.

2024-02-21 14:20 UTC, JonChesterfield commented on llvm/lib/Target/AMDGPU/AMDGPULowerModuleLDSPass.cpp
> +      if (HasAbsoluteGVs.has_value()) {
Lets call GV.isAbsoluteSymbolRef once instead of three times

2024-03-01 13:04 UTC, Pierre-vh commented
ping

2024-03-08 22:43 UTC, JonChesterfield approved these changes
Thanks for the cleanup. Latest commit looks good to me and risk profile on it is low, let's ship it. Thanks!

2024-03-11 08:20 UTC, merged