[clangd] Fix C++20 modules crash
llvm/llvm-project pull request #81919
Opened 2024-02-15 21:01 UTC by CLRN

This fix partially reverts https://github.com/llvm/llvm-project/commit/a0b6747804e46665ecfd00295b60432bfe1775b6.

The serialization part is restored to the state prior to the mentioned commit as it causing issue with reading back Decl.
ODR checks logic is kept in place.

Close https://github.com/llvm/llvm-project/issues/80570.

2024-02-16 00:51 UTC, poyaoc97 commented
cc @ChuanqiXu9

2024-02-18 01:48 UTC, ChuanqiXu9 requested changes
This is not wanted. While we have a policy to revert patches if the patches break existing codes, the C++20 modules support in clangd is literally broken: https://github.com/clangd/clangd/issues/1293

Also the ability to skip ODR checks is an important feature to modules. So I don't think we should revert this now.

Also I don't understand why it can make clangd to crash. A test will be helpful for us to understand what happened.

2024-02-19 07:31 UTC, h-vetinari commented
> A test will be helpful for us to understand what happened.

There's a reproducer in https://github.com/llvm/llvm-project/issues/80570

2024-02-20 05:32 UTC, ChuanqiXu9 commented
I'd like to close this since the issue got closed.

2024-02-20 05:32 UTC, closed without merging