[mlir][Vector] Fix bug in vector xfer op flattening transformation
llvm/llvm-project pull request #81964
Opened 2024-02-16 03:24 UTC by dcaballe

It looks like the affine map generated to compute the indices of the collapsed dimensions used the wrong dim size. For indices `[idx0][idx1]` we computed the collapsed index as `idx0*size0 + idx1` instead of `idx0*size1 + idx1`. This led to correctness issues in convolution tests when enabling this transformation internally.

2024-02-16 15:44 UTC, MacDue commented on mlir/lib/Dialect/Vector/Transforms/VectorTransferOpTransforms.cpp
> +            rewriter, loc, offsetExpr + nextDimSize * idxExpr,
Just double checking is this correct for > 2D? 

`[idx0][idx1][idx2]` would be:

 `idx0 * size1*size2 + idx1 * size2 + idx2`

2024-02-16 15:46 UTC, banach-space commented on mlir/test/Dialect/Vector/vector-transfer-flatten.mlir
> +// CHECK: #[[$ATTR_0:.+]] = affine_map<()[s0, s1] -> (s0 * 6 + s1 * 4)>
Shouldn't this be `s0 * 6 + s1 * (4 * 6)`? As in, this affine map looks incorrect to me.

2024-02-16 16:09 UTC, nicolasvasilache requested changes
We have IndexingUtils to avoid reinventing such code every time..

Can we please use that and improve / evolve as needed?

2024-02-16 22:50 UTC, dcaballe commented
Thanks! Good catch! Using index utils now. It should ready

2024-02-19 18:43 UTC, hanhanW approved these changes
LGTM, thanks!

2024-02-21 01:58 UTC, dcaballe commented
Thanks! Will land this tomorrow if no more comments.

2024-02-22 20:37 UTC, merged