[libc++] tests with picolibc: prevent looking for unneeded "rt" library
llvm/llvm-project pull request #82262
Opened 2024-02-19 16:20 UTC by domin144

The clock_gettime function is provided by picolibc. There is no need to link to "rt" library, to have it. If still trying to link to "rt", following error is given:
    unable to find library from dependent library specifier: rt

2024-02-19 16:23 UTC, domin144 commented
@ldionne @mplatings

2024-02-20 08:20 UTC, pwprzybyla approved these changes

2024-02-27 16:06 UTC, ldionne requested changes

2024-02-27 16:06 UTC, ldionne commented on libcxx/cmake/config-ix.cmake
> +  check_library_exists("" clock_gettime "" LIBCXX_HAS_RT_FUNC_WITHOUT_LIB)
IMO the issue here is that `check_library_exists(rt ...)` doesn't ensure that `rt` actually exists, it seems to only ensure that `clock_gettime` can be used. What happens if we use something like `check_library_exists("" "" "" LIBCXX_HAS_RT_LIB)` instead?

2024-02-28 14:20 UTC, ldionne approved these changes

2024-02-29 07:54 UTC, merged