[compiler-rt] optimize __umodti3
llvm/llvm-project pull request #82353
Opened 2024-02-20 12:43 UTC by Eisenwave

See https://github.com/llvm/llvm-project/issues/82183 for discussion.

This PR only fixes the missed optimization at a compiler-rt level. Future work still includes improving codegen so that no call to `__umodti3` is emitted.

2024-02-22 23:41 UTC, compnerd approved these changes
This seems reasonable. We are already using `divq` directly on other outlined functions.

2024-05-26 18:10 UTC, efriedma-quic commented
Is this patch waiting for something?

2024-05-26 18:28 UTC, efriedma-quic requested changes
Actually, I'm pretty sure the logic here is wrong if b.s.hi is non-zero.  Among other things, there's an incorrect divide by zero.

2024-05-27 06:14 UTC, Eisenwave commented
> Is this patch waiting for something?

I just need to make some changes regarding code formatting.

> Actually, I'm pretty sure the logic here is wrong if b.s.hi is non-zero. Among other things, there's an incorrect divide by zero.

`b.s.hi` is always zero/ignored. That's a precondition of this function.

2024-05-27 20:20 UTC, efriedma-quic commented
> That's a precondition of this function.

Precondition where, exactly?  As far as I know, both clang and gcc call __umodti3 for 128-bit modulo with unknown denominator.

2026-06-17 05:30 UTC, closed without merging