[Tosa] Add Tosa Sin and Cos operators
llvm/llvm-project pull request #82510
Opened 2024-02-21 17:26 UTC by Jerry-Ge

- Add Tosa Sin and Cos operators to the MLIR dialect
- Define the new Tosa_FloatTensor type

2024-02-21 17:28 UTC, Jerry-Ge commented
cc @Tai78641

2024-02-22 02:24 UTC, eric-k256 requested changes

2024-02-22 02:24 UTC, eric-k256 commented on mlir/include/mlir/Dialect/Tosa/IR/TosaOps.td
> -
nit: can you remove these whitespace changes as they aren't relevant to this change. Same below for the 'cast' changes.

2024-02-22 23:52 UTC, eric-k256 approved these changes

2024-02-22 23:54 UTC, merged