goldsteinn/kb both sides
llvm/llvm-project pull request #82818
Opened 2024-02-23 19:31 UTC by goldsteinn

- **[ValueTracking] Add tests for tracking `(and/or cond0**
- **[ValueTracking] Compute knownbits for `(and/or cond0**

2024-02-23 19:55 UTC, nikic commented on llvm/lib/Analysis/ValueTracking.cpp
> +      Known = Known2.unionWith(Known3);
```suggestion
      Known2 = Known2.unionWith(Known3);
```
You probably meant this?

2024-02-23 20:04 UTC, goldsteinn commented on llvm/lib/Analysis/ValueTracking.cpp
> +      Known = Known2.unionWith(Known3);
Bah yup, Fixed.

2024-02-23 20:05 UTC, nikic commented
@dtcxzyw Can you please rerun the tests?

@goldsteinn What's the compile-time impact?

2024-02-23 20:34 UTC, goldsteinn commented
> @dtcxzyw Can you please rerun the tests?
> 
> @goldsteinn What's the compile-time impact?

No meaningful affect:
https://llvm-compile-time-tracker.com/compare.php?from=55bc0488af077acb47be70542718d1bc17f3de4f&to=a6a7dcd98c13617dfaf0f82614b06cc66a14694c&stat=instructions:u

2024-02-23 20:45 UTC, dtcxzyw approved these changes
LGTM.

2024-02-23 20:47 UTC, topperc commented on llvm/lib/Analysis/ValueTracking.cpp
> +    if (Invert ? match(Cond, m_LogicalOr(m_Value(A), m_Value(B)))
You can use m_Value() instead of m_Value(A/B). You don't need to recapture the variables.

2024-02-23 20:53 UTC, nikic requested changes
You'll also have to adjust the logic in DomCondCache to recurse into all and/or, not just ones that match the top-level type. Unless you intentionally only want to handle the inverted type at the top level?

Please recheck compile-time impact after doing that.

2024-02-23 22:23 UTC, goldsteinn commented
> You'll also have to adjust the logic in DomCondCache to recurse into all and/or, not just ones that match the top-level type. Unless you intentionally only want to handle the inverted type at the top level?
> 
> Please recheck compile-time impact after doing that.

https://llvm-compile-time-tracker.com/compare.php?from=55bc0488af077acb47be70542718d1bc17f3de4f&to=d3e117a04afb14a00686eb689213776b2921154b&stat=instructions%3Au

Mostly minimal with two notable regressions:
Stage2-O0-g: tramp3d-v4	20259M	20310M (+0.25%)
Stage1-ReleaseLTO-g: consumer-typeset	58135M	58200M (+0.11%)

2024-02-25 16:36 UTC, nikic approved these changes
LGTM

2024-02-25 18:44 UTC, closed without merging