[mlir] Don't rely on values of MLIR_(CURDA|ROCM)_CONVERSIONS_ENABLED.
llvm/llvm-project pull request #82988
Opened 2024-02-26 11:46 UTC by ingomueller-net

This PR changes the `#if XXX == 1` sections for these macros to `#ifdef` sections such that the actual values that the macros are defined with do not matter. This scheme is used for most (but not all) such macros in the MLIR code base and the fact that these two macros did not follow it has lead to bugs downstream (which assumed that `#ifdef` was being used and defined them to a value != 1).

2024-02-26 11:49 UTC, ingomueller-net commented
As a comparison, these are the macros where `#if` is being used. (I removed manually some tests like `__clang_major__ <= 5`.) Note that the majority of those also doesn't rely on the values of the macros.

```
> git grep -E "^#if " -- mlir | cut -f2 -d: | sort -u
...
#if LLVM_ENABLE_ABI_BREAKING_CHECKS
#if LLVM_ENABLE_STATS
#if LLVM_ENABLE_THREADS != 0
#if LLVM_HAS_NVPTX_TARGET
#if LLVM_NATIVE_TARGET_TEST_ENABLED == 0
#if MLIR_CAPI_BUILDING_LIBRARY
#if MLIR_DEPRECATED_GPU_SERIALIZATION_ENABLE == 1
#if MLIR_ENABLE_EXPENSIVE_PATTERN_API_CHECKS
#if MLIR_ENABLE_PDL_IN_PATTERNMATCH
#if MLIR_GPU_TO_HSACO_PASS_ENABLE
#if MLIR_NVPTXCOMPILER_ENABLED == 1
```

And this is where `#ifdef` is being used:

```
> git grep -E "^#ifdef" -- mlir | cut -f2 -d: | sort -u
#ifdef __cplusplus
#ifdef CUSPARSE_COO_AOS
#ifdef CUSPARSE_COO_AOS // deprecated in cuSPARSE 11.2
#ifdef ERROR1
#ifdef ERROR10
#ifdef ERROR11
#ifdef ERROR12
#ifdef ERROR13
#ifdef ERROR2
#ifdef ERROR3
#ifdef ERROR4
#ifdef ERROR5
#ifdef ERROR6
#ifdef ERROR7
#ifdef ERROR8
#ifdef ERROR9
#ifdef EXPENSIVE_CHECKS
#ifdef GEN_PASS_DECL_MYPASS
#ifdef __has_attribute
#ifdef __linux__
#ifdef LLVM_ENABLE_ABI_BREAKING_CHECKS
#ifdef mlir_arm_sme_abi_stubs_EXPORTS
#ifdef mlir_async_runtime_EXPORTS
#ifdef MLIR_CRUNNERUTILS_DEFINE_FUNCTIONS
#ifdef mlir_c_runner_utils_EXPORTS
#ifdef MLIR_CUDA_CONVERSIONS_ENABLED
#ifdef MLIR_ENABLE_CUDA_CUSPARSE
#ifdef MLIR_ENABLE_CUDA_CUSPARSELT
#ifdef MLIR_FLOAT16_DEFINE_FUNCTIONS // We are building this library
#ifdef mlir_float16_utils_EXPORTS // We are building this library
#ifdef MLIR_GREEDY_REWRITE_RANDOMIZER_SEED
#ifdef MLIR_INCLUDE_TESTS
#ifdef MLIR_ROCM_CONVERSIONS_ENABLED
#ifdef mlir_runner_utils_EXPORTS
#ifdef NDEBUG
#ifdef __sparc__
#ifdef _WIN32
```

2024-02-26 13:43 UTC, fabianmcg commented
Did you run `mlir-check` on both AMD and NVIDIA GPUs and verified the integration tests run?
I never liked the pattern `#if X == 1`, however, I don't remember if it was setup like that because of the tests.

2024-02-26 14:12 UTC, ingomueller-net commented
I have just run all bazel test targets under `mlir/test` and they passed. However, I am not 100% sure whether actually runs on the two GPU architectures. Doesn't the CI do that eventually?

2024-02-26 14:28 UTC, ingomueller-net commented
Yeah, I see the problem. The thing with testing with CMake is that I don't have a machine with a GPU to test things. I can only run those GPU tests that Bazel runs in our internal build/test cloud... If you could run the tests, that'd be great -- thanks!

2024-02-27 00:52 UTC, joker-eph requested changes
I have concerns with this direction which seems the opposite of what we should do.

I would want to never use `ifdef` so that we can turn on the `-Wundef` warning and catch the usual misconfiguration problem where there are spelling issue, or a macro is renamed and usage not updated, etc.

2024-02-27 00:54 UTC, joker-eph commented
As an example, the form `#if LLVM_ENABLE_ABI_BREAKING_CHECKS` would be caught by `-Wundef` if the Config.h header isn't included, but silently misconfigured with `ifdef`.

2024-02-27 09:46 UTC, ingomueller-net commented
OK, that's a good argument. That might have caught #83004 -- I'll try out running with that warning flag and see if I find similar problems.

One clarification, though: even if we use `#if` instead of `#ifdef`, we don't have to rely on a value, right? That would prefer `#if X` over `#if X == 1`. Is that so?

FWIW, I think our downstream problems were actually unrelated to the macro value.

2024-02-27 16:43 UTC, ingomueller-net commented
Closing in favor of #83004. That PR only makes changes to the CUDA-related variable but I'll probably submit other PRs for the other ones once we agreed on the approach.

2024-02-27 16:43 UTC, closed without merging