[flang] Produce warning instead of error when bound checking arrays
llvm/llvm-project pull request #83011
Opened 2024-02-26 14:37 UTC by mjklemm

Fixes issue #82684.

While out-of-bounds accesses are not permitted by the Fortran standard, the compiler should not produce a fatal error but emit a warning.  This is inline with other compilers and can easily be turned into an error via `-Werror`.

2024-02-26 15:50 UTC, klausler requested changes
What application requires this change?

2024-02-26 17:45 UTC, mjklemm commented
We have one customer workload that we cannot disclose publicly (it's sort of a cummunity code in Europe), plus NWChem has similar patterns (even though they go undetected).  GFortran also just warns and does not error out by default.

2024-02-26 17:47 UTC, klausler commented
> We have one customer workload that we cannot disclose publicly (it's sort of a cummunity code in Europe), plus NWChem has similar patterns (even though they go undetected). GFortran also just warns and does not error out by default.

@jeffhammond is this true about nwchem?

2024-02-26 17:49 UTC, jeffhammond commented
if it's true in NWChem, it's a bug and we will fix it.  i want to know about these errors by default.

2024-02-26 18:03 UTC, mjklemm commented
> if it's true in NWChem, it's a bug and we will fix it. i want to know about these errors by default. i don't recall this issue when i compiled NWChem with `flang-new`, FWIW.

It's the usage of `mb_dbl` and it's friends.  All their accesses through out the code are outside of the their definition, which is `mb_dbl(2)` in a `common` block.

2024-02-26 19:15 UTC, mjklemm commented
> ugh, if `dbl_mb` triggers this then all of NWChem is broken with bounds checking.

NWChem does not trigger the warning, as the compiler is not smart enough.  But that does not mean the problem does not exist.  So, yes, the problem is there for NWChem and it is badly UB all over the place.


> @klausler for context, `dbl_mb` is used to implement a heap allocator. it's a common block member and C code increases the size of it, in spite of its declaration. the whole thing is trash but rewriting to use `allocate` would take years.
> 
> in theory, we can increase the size by some amount that makes it much harder for the compiler to prove OOB errors (that aren't really errors, thanks to C) but i don't know how well this will work.

So, even though the problem does not show up, I'd argue that a less harsh reaction of Flang on case where it can detect that seems useful, given that other compilers are either completely silent about this detectable case (ifort, ifx) or prefer to warn (gfortran).

2024-02-26 19:20 UTC, jeffhammond commented
indeed, i agree it should be fatal by default because most of the uses are bad and should be trapped.

2024-02-26 19:39 UTC, kkwli commented
> > So, even though the problem does not show up, I'd argue that a less harsh reaction of Flang on case where it can detect that seems useful, given that other compilers are either completely silent about this detectable case (ifort, ifx) or prefer to warn (gfortran).
> 
> It's a fatal error by default with better compilers (NAG & XLF).

Not really for XLF.
```
$ cat tt.f90

program main
  implicit none
 
  integer, parameter :: N = ONE_OR_TWO
  integer :: array(N)
 
  array(1) = 1
  if (N > 1) then
    array(2) = 2
  endif
 
  write(*,*) array
 
end program main

$ xlf90 -qpreprocess -DONE_OR_TWO=1 tt.f90
"tt.f90", line 10.5: 1516-023 (E) Subscript is out of bounds.
** main   === End of Compilation 1 ===
1501-510  Compilation successful for file tt.f90.
```

2024-02-26 20:21 UTC, mjklemm commented
I just came across Clang's behavior:

```
/home/micklemm/git/llvm/llvm-project/llvm/include/llvm/ADT/SparseBitVector.h: In member function ‘llvm::Error llvm::pdb::HashTable<ValueT>::load(llvm::BinaryStreamReader&) [with ValueT = llvm::support::detail::packed_endian_specific_integral<unsigned int, llvm::endianness::little, 1>]’:
/home/micklemm/git/llvm/llvm-project/llvm/include/llvm/ADT/SparseBitVector.h:130:15: warning: array subscript 2 is above array bounds of ‘const BitWord [2]’ {aka ‘const long unsigned int [2]’} [-Warray-bounds]
  130 |       if (Bits[i] != 0)
      |           ~~~~^
/home/micklemm/git/llvm/llvm-project/llvm/include/llvm/ADT/SparseBitVector.h:55:11: note: while referencing ‘llvm::SparseBitVectorElement<128>::Bits’
   55 |   BitWord Bits[BITWORDS_PER_ELEMENT];
      |           ^~~~
```

So, Flang behavior would be consistent with its C/C++ counterpart.

2024-02-26 20:25 UTC, klausler commented
> I just came across Clang's behavior:
> 
> ```
> /home/micklemm/git/llvm/llvm-project/llvm/include/llvm/ADT/SparseBitVector.h: In member function ‘llvm::Error llvm::pdb::HashTable<ValueT>::load(llvm::BinaryStreamReader&) [with ValueT = llvm::support::detail::packed_endian_specific_integral<unsigned int, llvm::endianness::little, 1>]’:
> /home/micklemm/git/llvm/llvm-project/llvm/include/llvm/ADT/SparseBitVector.h:130:15: warning: array subscript 2 is above array bounds of ‘const BitWord [2]’ {aka ‘const long unsigned int [2]’} [-Warray-bounds]
>   130 |       if (Bits[i] != 0)
>       |           ~~~~^
> /home/micklemm/git/llvm/llvm-project/llvm/include/llvm/ADT/SparseBitVector.h:55:11: note: while referencing ‘llvm::SparseBitVectorElement<128>::Bits’
>    55 |   BitWord Bits[BITWORDS_PER_ELEMENT];
>       |           ^~~~
> ```
> 
> So, Flang behavior would be consistent with its C/C++ counterpart.

Fortran is neither C nor C++.

2024-02-26 20:42 UTC, mjklemm commented
> Fortran is neither C nor C++.

I understand that, even though sometime I misplace ';' in the code.  However, it seems to hint a certain behavior that users may expect from other compilers and that can make it easier when when moving between compilers and languages.

2024-06-10 17:57 UTC, mjklemm commented
With the latest discussions about errors/warnings on Slack is there anyway you can be convinced that this should also be a warning instead of an error?

2024-06-10 18:04 UTC, klausler commented
> With the latest discussions about errors/warnings on Slack is there anyway you can be convinced that this should also be a warning instead of an error?

The discussion is about language extensions.  Do you want out-of-bounds array references to be treated as a language extension?

2024-06-10 18:27 UTC, jeffhammond commented
Out-of-bounds array access is not a language extension, anymore than dividing by zero is.

2024-06-11 07:33 UTC, mjklemm commented
I'm not sure where I have said this.  But there were statements in the Slack thread that could be interpreted that not all violations of the Fortran spec should be errors, but could be treated as warnings.

2024-06-11 07:51 UTC, jeffhammond commented
Violating obvious restrictions of the standard is not the same thing as allowing language extensions.  Integer division by zero is always wrong, while allowing integer addition to wraparound for finite-width types is a language extension.  There is no way to describe out-of-bounds array indexing as a language extension.  The Slack discussion is about allowing something that no one has been able to demonstrate is actually bad.

2024-06-27 15:29 UTC, mjklemm commented
Closing this PR due to objections.

2024-06-27 15:29 UTC, closed without merging

2026-09-02 19:32 UTC, ronGreenNV commented
@mjklemm I had reason to revisit this PR.  I agree with you that we want a warning for bounds error, not error.  I created PR 220435 to do just this. I will add you to the reviewers after a push a few fixes requested by Eugene and others.