[DFAJumpThreading] Enable the pass by default
llvm/llvm-project pull request #83033
Opened 2024-02-26 17:08 UTC by UsmanNadeem

Change-Id: Ia13cd78498ac964cda650138d7eca83b4204b3a9

2024-02-26 18:49 UTC, nikic requested changes
Enabling this pass by default currently causes a timeout in the stage 2 build: http://llvm-compile-time-tracker.com/show_error.php?commit=f3418c749f6060a5610020ef53a5d78e222be455

As such I can't provide up to date compile-time numbers, but the last time I tried there were unacceptably large regressions, and I don't think anything has changed since (http://llvm-compile-time-tracker.com/compare.php?from=387c1573f89117687f4b964ae3a90ea7c91a4f90&to=2a66b841e34f385331226d2b4f89fffd1840cda1&stat=instructions:u).

This pass is not production ready.

2024-02-26 19:58 UTC, nikic commented
@UsmanNadeem Given what the pass does, you should aim for 0.1% first-order impact. (IIRC the cost of the original implementation was in that ballpark.)

2024-02-29 03:43 UTC, XChy commented
The performance improvement brought by DFAJumpThreading looks fairly good to me. But it's uncertain whether we test this pass enough for correctness, especially with just few maintainance after the initial patch of DFAJumpThreading. To add it into the pipeline, I believe we need more correctness proofs apart from internal unit tests.

2024-04-09 22:56 UTC, UsmanNadeem commented
> The performance improvement brought by DFAJumpThreading looks fairly good to me. But it's uncertain whether we test this pass enough for correctness, especially with just few maintainance after the initial patch of DFAJumpThreading. To add it into the pipeline, I believe we need more correctness proofs apart from internal unit tests.

I believe that enabling it by default will enable more testing, and thus uncover more bugs. We have plenty of time till the next release to fix them.

2024-04-30 01:23 UTC, nikic commented
Thanks, the new compile-time numbers look a lot better!

While this mostly resolves the compile-time issues for average cases, I am still concerned about the behavior of the pass in pathological cases, in particular the discussion starting at https://github.com/llvm/llvm-project/pull/85015#issuecomment-1998028311. We need to make sure that even if all the early-exit conditions don't trigger, we never inspect an unreasonably large number of paths.

2024-08-28 13:30 UTC, djtodoro commented
Hi, what is the status of this PR? What are the next steps?

2024-08-28 13:34 UTC, djtodoro commented
>We need to make sure that even if all the early-exit conditions don't trigger, we never inspect an unreasonably large number of paths.

Could we implement a threshold to limit the number of paths inspected? This could be set as a backend option.

2024-08-28 16:38 UTC, UsmanNadeem commented
> Hi, what is the status of this PR? What are the next steps?

I have merged https://github.com/llvm/llvm-project/pull/96127 which changes the algorithm a little and adds more limits to reduce compile time. There are some assertions triggered after the patch which I am planning to look into soon. Here is the open issue: https://github.com/llvm/llvm-project/issues/106083

2024-09-26 21:36 UTC, UsmanNadeem commented
> > > Hi, what is the status of this PR? What are the next steps?
> > 
> > 
> > I have merged #96127 which changes the algorithm to reduce the number of paths inspected and also adds more limits to reduce compile time. There are some assertions triggered after the patch which I am planning to look into soon. Here is the open issue: #106083
> 
> Since #109511 got merged, we can proceed with this one, right?

@nikic ping!

2024-09-28 21:46 UTC, nikic commented
Can you please rebase the PR?

2024-09-29 08:09 UTC, nikic commented
New compile-time: https://llvm-compile-time-tracker.com/compare.php?from=29b92d07746fac26cd64c914bc9c5c3833974f6d&to=bcc333192cfadbe63154294b8606fba53247c7fd&stat=instructions:u

The results on CTMark look reasonable. Clang has two big regressions:
```
lib/DebugInfo/PDB/CMakeFiles/LLVMDebugInfoPDB.dir/Native/NativeInlineSiteSymbol.cpp.o 	5979M 	7853M (+31.34%)
tools/clang/lib/AST/CMakeFiles/obj.clangAST.dir/ByteCode/Interp.cpp.o 	39908M 	43794M (+9.74%)
```

2025-11-04 19:32 UTC, UsmanNadeem commented
Duplicated by https://github.com/llvm/llvm-project/pull/157646

2025-11-04 19:32 UTC, closed without merging