[mlir][arith] fix wrong floordivsi fold (#83079)
llvm/llvm-project pull request #83248
Opened 2024-02-28 11:17 UTC by lipracer

Fixs https://github.com/llvm/llvm-project/issues/83079

2024-02-28 12:42 UTC, kuhar reviewed
Looks fine upon a quick scan of the patch. Given the number or error code paths, I think it could be made more readable with something like `constFoldBinaryOpConditional` IIRC.

2024-02-28 13:59 UTC, pingshiyu commented
Not sure this is the right patch, please see [this comment](https://github.com/llvm/llvm-project/issues/83079#issuecomment-1969041763)

2024-03-03 06:41 UTC, lipracer commented
@kuhar There are indeed many overflow states that need to be checked here, but I haven't come up with a good method yet. Can you give me a specific suggestion? Thank you.

2024-03-03 18:07 UTC, kuhar commented
> @kuhar There are indeed many overflow states that need to be checked here, but I haven't come up with a good method yet. Can you give me a specific suggestion? Thank you.

Without knowing the exact details of the floordivsi algorithm, the way I'd think about it is that we only need to detect if the *final* overflow happened or not. And of course fold correctly when there is no overflow. If there are intermediate overflows, I'd think that they can fold into one of the two buckets: (a) those that indicate that the floordivsi overflows for these arguments, and (b) implementation bugs.

It might be helpful to extract this fold code to a unit test (say one of the APInt test files) and go from there. Pick a few inputs that are known to overflow and trace the values and intermediate overflows. Maybe write a separate check to decide if overflow happens for the given input instead of relying on some intermediate checks.

2024-03-03 18:09 UTC, kuhar commented
@lipracer Another idea: we could perform the division on APInt with more bits than the bitwidth of the folded integer type. Maybe this way it'd be easier to detect overflow. And then once we are confident there's no overflow, truncate it back to the desired bitwidth.

2024-03-11 02:42 UTC, kuhar requested changes
@lipracer could you land the APInt change separately from the mlir fold fixes? This will make it easier to review and land properly.

2024-03-11 02:47 UTC, lipracer commented
Ok.

2024-03-11 05:21 UTC, lipracer commented
submit a APInt change [PR](https://github.com/llvm/llvm-project/pull/84720).

2024-03-11 20:33 UTC, dwblaikie commented on llvm/lib/Support/APInt.cpp
> +    return quotient;
LLVM style encourages skipping else-after-return, so would be written as:
```
  return quotient - 1;
return quotient;
```

2024-03-18 06:32 UTC, lipracer commented
> @lipracer could you open a separate PR for the APInt change? This will make it easier to review and land properly.

APInt change has already merged.

2024-03-18 07:27 UTC, kuhar approved these changes
Looks fine upon a quick scan but I won't have the time to understand the details of the expansion in near future. Please get a second approval before landing.

2024-03-18 07:45 UTC, lipracer commented
Thank you very much for your valuable suggestion.

2024-03-20 08:51 UTC, lipracer commented
@joker-eph  I'd like someone to review my code, could you help me with that?

2024-03-20 17:59 UTC, Mogball approved these changes
This change almost certainly has performance implications. Do we have some way to measure or even guess at that? If this is fixing a correctness bug, I am also not the right person to verify that, but I trust the author in this

2024-03-20 18:02 UTC, joker-eph commented
@pingshiyu  would you be able to review the correctness of this change?

2024-03-20 18:18 UTC, lipracer commented
> This change almost certainly has performance implications. Do we have some way to measure or even guess at that? If this is fixing a correctness bug, I am also not the right person to verify that, but I trust the author in this

Yes, this may indeed affect performance. This implementation is based on tensorflow. For performance considerations, I think we can have a compilation option similar to ‘fast-expand’ for expansion. This change is only consistent with the behavior of llvm.

2024-03-21 00:24 UTC, pingshiyu commented
> @pingshiyu would you be able to review the correctness of this change?

sure, I've just taken some time to check through the cases, lgtm re correctness. 

thanks @lipracer!

maybe some extra tests would be nice for the edge cases, e.g. `floordivsi(min_val, 1)`, and `floordivsi(max_val, -1)`

2024-03-21 07:31 UTC, lipracer commented
@pingshiyu Thanks, I have added more corner tests.

2024-03-22 04:46 UTC, lipracer commented
The CI error seems unrelated to this change. If the performance drops after merging, I will submit another change to enable "fast expand".

2024-03-22 04:53 UTC, joker-eph commented
The premerge is green at HEAD: can you rebase? https://lab.llvm.org/buildbot/#/builders/271

2024-03-22 04:56 UTC, joker-eph commented
Nevermind I misread the log, it's failing on building flang by running out of memory:
```
_bk;t=1711039712398C:\ws\src\flang\include\flang\Evaluate\tools.h(236): fatal error C1060: compiler is out of heap space
```

I concur that it is unrelated, and all the MLIR tests are passing.

2024-03-22 04:58 UTC, lipracer commented
Thanks, I will rebase on head.

2024-03-22 15:52 UTC, merged