[InstCombine] Fix Failure to convert vector fp comparisons that can be represented as integers #82241
llvm/llvm-project pull request #83274
Opened 2024-02-28 15:24 UTC by SahilPatidar

Resolve #82241

2024-02-28 15:44 UTC, dtcxzyw commented on llvm/lib/Transforms/InstCombine/InstCombineCompares.cpp
>    const APFloat &RHS = cast<ConstantFP>(RHSC)->getValueAPF();
```suggestion
  const APFloat *RHS;
  if (!match(RHSC, m_APFloat(RHS)))
    return nullptr;
```

2024-02-28 15:44 UTC, dtcxzyw commented on llvm/lib/Transforms/InstCombine/InstCombineCompares.cpp
> +
```suggestion
```

2024-02-28 15:44 UTC, dtcxzyw commented on llvm/lib/Transforms/InstCombine/InstCombineCompares.cpp
> +          return replaceInstUsesWith(I, False);
```suggestion
          return replaceInstUsesWith(I, ConstantInt::getFalse(I.getType()));
```

2024-02-28 15:44 UTC, dtcxzyw commented on llvm/lib/Transforms/InstCombine/InstCombineCompares.cpp
> +        return replaceInstUsesWith(I, True);
```suggestion
        return replaceInstUsesWith(I, ConstantInt::getTrue(I.getType()));
```

2024-02-28 15:44 UTC, dtcxzyw commented on llvm/lib/Transforms/InstCombine/InstCombineCompares.cpp
> +
```suggestion
```

2024-02-28 15:44 UTC, dtcxzyw commented on llvm/lib/Transforms/InstCombine/InstCombineCompares.cpp
>    return new ICmpInst(Pred, LHSI->getOperand(0), Builder.getInt(RHSInt));
```suggestion
  return new ICmpInst(Pred, LHSI->getOperand(0), ConstantInt::get(LHSI->getOperand(0)->getType(), RHSInt));
```

2024-02-28 15:44 UTC, dtcxzyw commented on llvm/test/Transforms/InstCombine/cast-int-fcmp-eq-0.ll
> +define <2 x i1> @i32_vec_cast_cmp_oeq_vec_int_0_sitofp(<2 x i32> %i) {
Please pre-commit these tests.

2024-02-28 16:11 UTC, RKSimon commented on llvm/lib/Transforms/InstCombine/InstCombineCompares.cpp
> +  }
No need to check isVectorTy - its safe to just do:
```cpp
if (Constant *CV = RHSC->getSplatValue(false))
  RHSC = CV;
```

2024-02-28 16:11 UTC, RKSimon commented on llvm/lib/Transforms/InstCombine/InstCombineCompares.cpp
> +    False = Builder.CreateVectorSplat(EC, Builder.getFalse());
@nikic Is there a better way to do this - could we create Builder.getTrue(Type*) variants?

2024-02-28 16:18 UTC, RKSimon requested changes

2024-02-28 16:18 UTC, RKSimon commented on llvm/lib/Transforms/InstCombine/InstCombineCompares.cpp
> +  }
@dtcxzyw m_APFloat proposal is better

2024-02-29 05:51 UTC, arsenm approved these changes

2024-02-29 09:10 UTC, dtcxzyw approved these changes
LGTM.

2024-03-05 11:45 UTC, RKSimon approved these changes
LGTM - @SahilPatidar do you have commit access?

2024-03-05 11:49 UTC, merged

2024-03-05 11:49 UTC, arsenm commented
> LGTM - @SahilPatidar do you have commit access?

Mouseover on the username usually shows if they're a member of llvm-committers