[mlir][linalg] Enable expansion of parallel dims of reduction ops
llvm/llvm-project pull request #83473
Opened 2024-02-29 20:19 UTC by qedawkins

This adds support for expansion of linalg ops with reduction iterators. This improves the ability to make fusion decisions WRT reduction operations. To recover the previous behavior, users of the patterns can add a control function to restrict propagation of reshape by expansion through linalg ops with reduction iterators.

2024-02-29 21:14 UTC, hanhanW commented on mlir/lib/Dialect/Linalg/Transforms/ElementwiseOpFusion.cpp
> +      iteratorTypes[i] = type;
nit1: should replace the second `i` variable with name `j`.
nit2: the group is only used here, how about directly pass it to for op? I.e.,

```
for (auto j : expansionInfo.getExpandedDims(i))
  iteratorTypes[j] = type;
```

2024-02-29 22:01 UTC, hanhanW reviewed
I don't really follow these logics these days, so I suggest to wait for Mahesh.

2024-02-29 22:39 UTC, qedawkins commented
sounds good, thanks for taking a look!

2024-03-02 07:38 UTC, MaheshRavishankar requested changes
This is OK to land, but you can change the utility method here to work on any `LinalgOp`. I am suspecting for.your use case you are generalizing the op before applying the reshape. We can skip that step.

2024-03-03 00:11 UTC, qedawkins commented
> This is OK to land, but you can change the utility method here to work on any `LinalgOp`. I am suspecting for.your use case you are generalizing the op before applying the reshape. We can skip that step.

Done. The same should probably be done for the collapsing patterns, but I assume that's fine to do as a follow up?

2024-03-03 05:12 UTC, MaheshRavishankar approved these changes
Nice ! Thanks!

2024-03-03 06:54 UTC, merged