[UBSAN] Preserve ubsan code with ubsan-unique-traps
llvm/llvm-project pull request #83470
Opened 2024-02-29 19:50 UTC by vitalybuka

Removing `TrapBB->getParent()->size()` added with #65972. Counter as-is
is not very unique after inlining https://godbolt.org/z/4KfEKq7zb (see
m()).

2024-03-05 02:47 UTC, vitalybuka commented
> > It happens later, in LLVM backend, it needs to be fixed.
> 
> From [#65972 (comment)](https://github.com/llvm/llvm-project/pull/65972#issuecomment-1971855638)
> 
> Is this something you have planned to fix? If not would replacing the .size() counter with perhaps a seeded random uint8 be acceptable?
> 
> My use case prevents me from shipping the minimal runtime alongside the instrumentation so my goal was to create an improvement (definitely imperfect!) to the debugability of a production deployment of BoundsSan. This PR as is would revert that behavior entirely.

I don't plan to do anything about it.
My point that it does not work even on trivial example as in description.
Unless you/someone else is willing to work on real fix, this behavior is not worse of preserving.

2024-03-06 05:34 UTC, oskarwirga requested changes
If you are going to remove this feature, I would rather you simply revert the old commit. There is no point leaving the flag in at this point. 

I had explored earlier dealing with the optimization at a later time in the compilation pipeline, but got nowhere and this solution was ideal for my use case, binary size constraints limited any inlining so I never ran into the issue. I appreciate you cleaning this up! :)

2024-03-06 06:06 UTC, vitalybuka commented
> If you are going to remove this feature, I would rather you simply revert the old commit. There is no point leaving the flag in at this point.
> 
> I had explored earlier dealing with the optimization at a later time in the compilation pipeline, but got nowhere and this solution was ideal for my use case, binary size constraints limited any inlining so I never ran into the issue. I appreciate you cleaning this up! :)

Actually I am here because I want to use the flag to avoid merging basic blocks.
We are going to opt-out ubsan checks based on PGO, per basic block hotness https://github.com/llvm/llvm-project/pull/83471 

However I am considering introducing a special intrinsic for that, the this patch will not be needed.

2024-03-06 21:39 UTC, oskarwirga approved these changes

2024-04-05 16:59 UTC, oskarwirga commented
> I changed my design, so I don't need this patch. Given https://godbolt.org/z/4KfEKq7zb, I can revert your patch, or just leave it as is. I have no preference.

I would prefer leaving it as is, I will make a note to revisit this pending further testing on my end to see how useful it really is. Thank you :)

2024-04-05 19:47 UTC, vitalybuka commented
abandoning

2024-04-05 19:47 UTC, closed without merging