AMDGPU: Correct cycle counts for f64 mfma on gfx940
llvm/llvm-project pull request #83782
Opened 2024-03-04 08:13 UTC by arsenm

The manual states these are 4 and 8 pass instructions. I'm also not sure if reporting these as using VALU and not XDL resource is correct. The Latency and ReleaseAtCycles values were also mismatched, which I'm also not sure was intentional or not.

2024-03-04 19:35 UTC, rampitec requested changes
Indeed the number of cycles for v_mfma_f64_16x16* is incorrect. However, the hazard recognizier tests are correct. Hazard recognizer uses TargetSchedModel and the number of cycles to insert a correct number of waits (because that's the proper modeling of the underlying hazard). The code related to 8 pass DGEMM now needs to be moved from 'case 16' to 'case 8' in the `GCNHazardRecognizer::checkMAIHazards90A` and `GCNHazardRecognizer::checkMAIVALUHazards`.

No, DGEMM does not use XDL, it uses VALU pipeline, that is correct.

2024-03-04 19:35 UTC, rampitec commented on llvm/test/CodeGen/AMDGPU/mai-hazards-gfx90a.mir
> +# GCN-NEXT: S_NOP 2
This still shall be 18 wait states.

2024-03-04 19:35 UTC, rampitec commented on llvm/test/CodeGen/AMDGPU/mai-hazards-gfx90a.mir
> +# GCN-NEXT: S_NOP 2
Same here.

2024-03-04 19:35 UTC, rampitec commented on llvm/test/CodeGen/AMDGPU/mai-hazards-gfx940.mir
> +# GCN-NEXT: S_NOP 1
And this is still 11 waitstates.

2024-03-05 17:23 UTC, arsenm commented
>  The code related to 8 pass DGEMM now needs to be moved from 'case 16' to 'case 8' in the 
> `GCNHazardRecognizer::checkMAIVALUHazards`.

This one avoids the test changes

> `GCNHazardRecognizer::checkMAIHazards90A` 

This one seems to be unnecessary since it's special casing the MFMA_F64 opcodes before that switch

2024-03-05 21:44 UTC, rampitec approved these changes
LGTM, thanks!

2024-03-06 04:06 UTC, merged