[MLIR] Add llvm (debug) attributes to CAPI
llvm/llvm-project pull request #83992
Opened 2024-03-05 11:21 UTC by edg-l

This PR adds the following to the mlir c api:

- The disctinct mlir builtin attribute.
- LLVM attributes (mostly debug related ones)

While i almost have this working, there is an issue i encountered and have no idea how to solve, when trying to create attributes which need a list of attributes, such as DINodeAttr or DITypeAttr, i get a compilation error when unwrapping the list:

<details><summary>The error example</summary>

```
❯ ninja
[1/4] Building CXX object tools/mlir/lib/CAPI/Dialect/CMakeFiles/obj.MLIRCAPILLVM.dir/LLVM.cpp.o
FAILED: tools/mlir/lib/CAPI/Dialect/CMakeFiles/obj.MLIRCAPILLVM.dir/LLVM.cpp.o 
CCACHE_CPP2=yes CCACHE_HASHDIR=yes /usr/bin/ccache ccache /usr/lib/ccache/bin/clang++ -DGTEST_HAS_RTTI=0 -DMLIR_CAPI_BUILDING_LIBRARY=1 -DMLIR_ROCM_CONVERSIONS_ENABLED=0 -D_DEBUG -D_GLIBCXX_ASSERTIONS -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I/data2/edgar/llvm-project/build/tools/mlir/lib/CAPI/Dialect -I/data2/edgar/llvm-project/mlir/lib/CAPI/Dialect -I/data2/edgar/llvm-project/build/include -I/data2/edgar/llvm-project/llvm/include -I/data2/edgar/llvm-project/mlir/include -I/data2/edgar/llvm-project/build/tools/mlir/include -fPIC -fno-semantic-interposition -fvisibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -pedantic -Wno-long-long -Wc++98-compat-extra-semi -Wimplicit-fallthrough -Wcovered-switch-default -Wno-noexcept-type -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wsuggest-override -Wstring-conversion -Wmisleading-indentation -Wctad-maybe-unsupported -fno-omit-frame-pointer -O1 -fsanitize=address -fsanitize=undefined -fno-sanitize=vptr,function -fno-sanitize-recover=all -fsanitize-blacklist=/data2/edgar/llvm-project/llvm/utils/sanitizers/ubsan_ignorelist.txt -fdiagnostics-color -Werror=mismatched-tags -g -std=c++17 -fvisibility=hidden  -fno-exceptions -funwind-tables -fno-rtti -gsplit-dwarf -MD -MT tools/mlir/lib/CAPI/Dialect/CMakeFiles/obj.MLIRCAPILLVM.dir/LLVM.cpp.o -MF tools/mlir/lib/CAPI/Dialect/CMakeFiles/obj.MLIRCAPILLVM.dir/LLVM.cpp.o.d -o tools/mlir/lib/CAPI/Dialect/CMakeFiles/obj.MLIRCAPILLVM.dir/LLVM.cpp.o -c /data2/edgar/llvm-project/mlir/lib/CAPI/Dialect/LLVM.cpp
In file included from /data2/edgar/llvm-project/mlir/lib/CAPI/Dialect/LLVM.cpp:12:
In file included from /data2/edgar/llvm-project/mlir/include/mlir/CAPI/Registration.h:13:
In file included from /data2/edgar/llvm-project/mlir/include/mlir/CAPI/IR.h:19:
/data2/edgar/llvm-project/mlir/include/mlir/CAPI/Wrap.h:43:7: error: static assertion failed due to requirement 'std::is_same<mlir::Attribute, mlir::LLVM::DITypeAttr>::value': incompatible C and C++ types
   43 |       std::is_same<decltype(unwrap(std::declval<CTy>())), CppTy>::value,
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/data2/edgar/llvm-project/mlir/lib/CAPI/Dialect/LLVM.cpp:241:37: note: in instantiation of function template specialization 'unwrapList<mlir::LLVM::DITypeAttr, const MlirAttribute>' requested here
  241 |   mlir::ArrayRef<DITypeAttr> list = unwrapList(nTypes, types, elementsStorage);
      |                                     ^
In file included from /data2/edgar/llvm-project/mlir/lib/CAPI/Dialect/LLVM.cpp:12:
In file included from /data2/edgar/llvm-project/mlir/include/mlir/CAPI/Registration.h:13:
In file included from /data2/edgar/llvm-project/mlir/include/mlir/CAPI/IR.h:19:
/data2/edgar/llvm-project/mlir/include/mlir/CAPI/Wrap.h:52:23: error: no viable conversion from 'mlir::Attribute' to 'ValueParamT' (aka 'mlir::LLVM::DITypeAttr')
   52 |     storage.push_back(unwrap(*(first + i)));
      |                       ^~~~~~~~~~~~~~~~~~~~
/data2/edgar/llvm-project/mlir/include/mlir/IR/Attributes.h:38:18: note: candidate inherited constructor not viable: no known conversion from 'mlir::Attribute' to 'const ImplType *' (aka 'const mlir::AttributeStorage *') for 1st argument
   38 |   /* implicit */ Attribute(const ImplType *impl)
      |                  ^         ~~~~~~~~~~~~~~~~~~~~
/data2/edgar/llvm-project/mlir/include/mlir/Dialect/LLVMIR/LLVMAttrs.h:57:21: note: constructor from base class 'DINodeAttr' inherited here
   57 |   using DINodeAttr::DINodeAttr;
      |                     ^
/data2/edgar/llvm-project/mlir/include/mlir/Dialect/LLVMIR/LLVMAttrs.h:55:7: note: candidate constructor (the implicit copy constructor) not viable: cannot bind base class object of type 'mlir::Attribute' to derived class reference 'const DITypeAttr &' for 1st argument
   55 | class DITypeAttr : public DINodeAttr {
      |       ^~~~~~~~~~
/data2/edgar/llvm-project/mlir/include/mlir/Dialect/LLVMIR/LLVMAttrs.h:55:7: note: candidate constructor (the implicit move constructor) not viable: cannot bind base class object of type 'mlir::Attribute' to derived class reference 'DITypeAttr &&' for 1st argument
   55 | class DITypeAttr : public DINodeAttr {
      |       ^~~~~~~~~~
/data2/edgar/llvm-project/llvm/include/llvm/ADT/SmallVector.h:574:30: note: passing argument to parameter 'Elt' here
  574 |   void push_back(ValueParamT Elt) {
      |                              ^
2 errors generated.
ninja: build stopped: subcommand failed.
```
</details>

2024-03-05 15:19 UTC, ftynse commented
`unwrapList` can only unwrap C API data structures to their C++ counterpart, e.g. `MlirAttribute` to `mlir::Attribute`. It will not magically downcast attributes to a specific type. You will have to do that yourself.

2024-03-05 15:48 UTC, edg-l commented
> `unwrapList` can only unwrap C API data structures to their C++ counterpart, e.g. `MlirAttribute` to `mlir::Attribute`. It will not magically downcast attributes to a specific type. You will have to do that yourself.

thanks! my cpp was a bit rusty (haha pun intended), i know how to make it work now

2024-03-05 17:10 UTC, edg-l commented
should be ready now

2024-03-06 09:35 UTC, ftynse requested changes
Thanks for your contribution! Please address the inline comments.

2024-03-06 09:35 UTC, ftynse commented on mlir/lib/CAPI/Dialect/LLVM.cpp
> +#include <stdint.h>
Nit: prefer `cstdint` in C++ code.

2024-03-06 09:35 UTC, ftynse commented on mlir/lib/CAPI/Dialect/LLVM.cpp
> +#include "mlir/Dialect/LLVMIR/LLVMOpsAttrDefs.h.inc"
We shouldn't ever need to explicitly include the `.inc` files. I suspect your editor adds includes automatically, which isn't something that we necessarily want in MLIR/LLVM codebase. Transitive includes and forward declarations are totally fine.

2024-03-06 09:35 UTC, ftynse commented on mlir/lib/CAPI/Dialect/LLVM.cpp
> +  auto list = mlir::ArrayRef<uint64_t>(arguments, nArguments);
We shouldn't need the `mlir::` prefix in MLIR codebase. Here and below.

2024-03-06 09:35 UTC, ftynse commented on mlir/lib/CAPI/Dialect/LLVM.cpp
> +  SmallVector<Attribute, 2> attrStorage;
Nit: don't specify number of stack elements in a small vector unless you have a compelling reason to select a number. Here and below.

2024-03-06 09:35 UTC, ftynse commented on mlir/lib/CAPI/Dialect/LLVM.cpp
> +  }
Nit: `llvm::map_to_vector` replaces all of this with a nice little lambda.

2024-03-06 09:35 UTC, ftynse commented on mlir/lib/CAPI/Dialect/LLVM.cpp
> +                                           uint64_t emissionKind) {
Could we map this to a C enum so we don't pass magic numbers through the API?

2024-03-06 09:35 UTC, ftynse commented on mlir/lib/CAPI/Dialect/LLVM.cpp
> +  return wrap(ComdatAttr::get(unwrap(ctx), comdat::Comdat(comdat)));
Can we please expose enums as C enums anot not magic numbers? Here and below.

2024-03-06 09:35 UTC, ftynse commented on mlir/test/CAPI/llvm.c
> +  mlirAttributeDump(mlirLLVMComdatAttrGet(ctx, 0x0));
We shouldn't have magic numbers in the API...

2024-03-06 09:35 UTC, ftynse commented on mlir/test/CAPI/llvm.c
> +  MlirAttribute di_type = mlirLLVMDIBasicTypeAttrGet(ctx, 0, foo, 64, 0x5);
Ditto. As a code reader, I have no idea whether `0x5` corresponds to `DW_ATE_signed` or not so cannot understand whether the test is correct or not.

2024-03-06 09:35 UTC, ftynse commented on mlir/test/CAPI/llvm.c
> +  // "bar", apinotes = "foo", line = 1>
Please format this to be readable and actually check what needs to be checked. FileCheck has many useful directives: https://llvm.org/docs/CommandGuide/FileCheck.html

Specifically, comments lines _not_ starting with `CHECK` are not actually checked! There is also a way to capture previously matched strings and reuse them below.

2024-03-06 12:07 UTC, edg-l commented
Okay, i think i did most of your comments, in the process i found some outdated llvm-c enums and updated them, hope thats okay.

2024-03-06 18:42 UTC, ftynse requested changes
We shouldn't have random reformatting in unrelated parts of the project. Please undo any change made to `include/llvm-c`.

Also, I did not mean that MLIR C API should include LLVM C API, but provide C enums for the corresponding C++ enums in MLIR C++ API. Similarly to how we do for `MlirDiagnosticSeverity` or `MlirSparseTensorLevelFormat`.

2024-03-07 11:03 UTC, edg-l commented
> We shouldn't have random reformatting in unrelated parts of the project. Please undo any change made to `include/llvm-c`.
> 
> Also, I did not mean that MLIR C API should include LLVM C API, but provide C enums for the corresponding C++ enums in MLIR C++ API. Similarly to how we do for `MlirDiagnosticSeverity` or `MlirSparseTensorLevelFormat`.

is now better?

2024-03-07 17:09 UTC, ftynse approved these changes

2024-03-07 17:10 UTC, merged