[MLIR] Add missing MLIRGPUDialect dep to MLIRSPIRVDialect
llvm/llvm-project pull request #84554
Opened 2024-03-08 19:38 UTC by RoboTux

This fixes a failure when doing a clean build of
lib/libMLIRSPIRVDialect.a only.

2024-03-08 20:31 UTC, kuhar requested changes
The spir-v dialect doesn't depend on the gpu dialect, no?

2024-03-08 20:47 UTC, kuhar commented
> The spir-v dialect doesn't depend on the gpu dialect, no?

(I'm just surprised that this is the case, but maybe I missed something. If we do have a dependency, could you provide an example?)

2024-03-08 21:25 UTC, joker-eph commented
What does the failure look like? ` ninja clean && ninja lib/libMLIRSPIRVDialect.a ` does not reproduce at HEAD for me right now.

2024-03-09 16:28 UTC, RoboTux commented
> What does the failure look like? `ninja clean && ninja lib/libMLIRSPIRVDialect.a` does not reproduce at HEAD for me right now.

I can't seem to reproduce with ninja at the moment but I did yesterday when I was submitting the patch series. I suspect it might be exposed by some of the other patches in the series. I'm trying to find out which one exactly.

2024-03-10 14:16 UTC, zero9178 commented
> What does the failure look like? `ninja clean && ninja lib/libMLIRSPIRVDialect.a` does not reproduce at HEAD for me right now.

I can reproduce this using `ninja clean && rm .ninja_deps && ninja lib/libMLIRSPIRVDialect.a`. One needs to delete `.ninja_deps` as it contains/records header dependencies found by the C++ compiler on successful compiles. Unless you have a fresh cmake generation directory then ninja likely already recorded the dependency. 

The compiler error looks as follows:
```
CCACHE_CPP2=yes CCACHE_HASHDIR=yes /usr/bin/ccache /usr/bin/clang++ -DGTEST_HAS_RTTI=0 -DMLIR_CUDA_CONVERSIONS_ENABLED=0 -DMLIR_ROCM_CONVERSIONS_ENABLED=0 -D_DEBUG -D_GLIBCXX_ASSERTIONS -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I/home/markus/CLionProjects/llvm-project/llvm/cmake-build-debug-clang/tools/mlir/lib/Dialect/SPIRV/IR -I/home/markus/CLionProjects/llvm-project/mlir/lib/Dialect/SPIRV/IR -I/home/markus/CLionProjects/llvm-project/llvm/cmake-build-debug-clang/include -I/home/markus/CLionProjects/llvm-project/llvm/include -I/home/markus/CLionProjects/llvm-project/mlir/include -I/home/markus/CLionProjects/llvm-project/llvm/cmake-build-debug-clang/tools/mlir/include -fPIC -fno-semantic-interposition -fvisibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -pedantic -Wno-long-long -Wc++98-compat-extra-semi -Wimplicit-fallthrough -Wcovered-switch-default -Wno-noexcept-type -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wsuggest-override -Wstring-conversion -Wmisleading-indentation -Wctad-maybe-unsupported -fdiagnostics-color -Werror=mismatched-tags -Werror=global-constructors -g -std=c++17 -fcolor-diagnostics  -fno-exceptions -funwind-tables -fno-rtti -MD -MT tools/mlir/lib/Dialect/SPIRV/IR/CMakeFiles/obj.MLIRSPIRVDialect.dir/SPIRVDialect.cpp.o -MF tools/mlir/lib/Dialect/SPIRV/IR/CMakeFiles/obj.MLIRSPIRVDialect.dir/SPIRVDialect.cpp.o.d -o tools/mlir/lib/Dialect/SPIRV/IR/CMakeFiles/obj.MLIRSPIRVDialect.dir/SPIRVDialect.cpp.o -c /home/markus/CLionProjects/llvm-project/mlir/lib/Dialect/SPIRV/IR/SPIRVDialect.cpp
In file included from /home/markus/CLionProjects/llvm-project/mlir/lib/Dialect/SPIRV/IR/SPIRVDialect.cpp:17:
/home/markus/CLionProjects/llvm-project/mlir/include/mlir/Dialect/GPU/IR/CompilationInterfaces.h:120:10: fatal error: 'mlir/Dialect/GPU/IR/CompilationAttrInterfaces.h.inc' file not found
  120 | #include "mlir/Dialect/GPU/IR/CompilationAttrInterfaces.h.inc"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

The SPIR-V dialect doesn't technically depend on the GPU Dialect but rather the interface header being generated by TableGen for the purpose of registering the promise here: https://github.com/llvm/llvm-project/blob/3ec1f25f3cf9346590892397ec9ddd859397d363/mlir/lib/Dialect/SPIRV/IR/SPIRVDialect.cpp#L138

2024-03-10 22:07 UTC, RoboTux commented
> > What does the failure look like? `ninja clean && ninja lib/libMLIRSPIRVDialect.a` does not reproduce at HEAD for me right now.
> 
> I can reproduce this using `ninja clean && rm .ninja_deps && ninja lib/libMLIRSPIRVDialect.a`. One needs to delete `.ninja_deps` as it contains/records header dependencies found by the C++ compiler on successful compiles. Unless you have a fresh cmake generation directory then ninja likely already recorded the dependency.

Ah that's it, I forgot that bash's * doesn't match files starting with a dot. Removing the .ninja_deps I can now reproduce again. I've updated the description again accordingly. Thanks!

2024-03-19 13:43 UTC, RoboTux commented
Ping?

2024-03-20 06:28 UTC, joker-eph approved these changes

2024-03-20 10:13 UTC, merged