[analyzer] Turn NodeBuilderContext into a class
llvm/llvm-project pull request #84638
Opened 2024-03-09 16:27 UTC by diego-est

From issue #73088. I changed `NodeBuilderContext` into a class. Additionally, there were some other mentions of the former being a struct which I also changed into a class. This is my first time working with an issue so I will be open to hearing any advice or changes that need to be done.

2024-03-10 11:11 UTC, steakhal commented
Thanks for the PR.
I think it would make sense to not expose data members in a class' public api.
We might need some member functions along the way to make this possible.

2024-03-10 11:12 UTC, steakhal requested changes
See my previous reply.

2024-03-11 01:59 UTC, diego-est commented
I added the appropriate functions and moved the class members into private. Additionally I ran `make check-all` to make sure the now-private members wouldn't cause any issues with the rest of the codebase, all the checks passed.

2024-03-11 12:59 UTC, steakhal reviewed
Alright. So we can simply mark all the members private. I was surprised a bit.
LGTM, but remove the TODO comment you fix.

2024-03-11 12:59 UTC, steakhal commented on clang/include/clang/StaticAnalyzer/Core/PathSensitive/CoreEngine.h
>  // TODO: Turn into a class.
Remove this TODO, as its completed.

2024-03-12 13:50 UTC, diego-est commented on clang/include/clang/StaticAnalyzer/Core/PathSensitive/CoreEngine.h
>  // TODO: Turn into a class.
Done.

2024-03-12 14:30 UTC, diego-est commented
Seems like it wasn't as easy as just making them private. I think I found all the places where there were private member accesses. The tests passed on my side again and the github-pull-requests action. The code_formatter action keeps failing because of the documentation on something I didn't touch (but seems to be fixed high upstream). Everything should be fixed now.

2024-03-12 17:21 UTC, merged