[APInt] add sfloordiv_ov APInt's member function
llvm/llvm-project pull request #84720
Opened 2024-03-11 05:11 UTC by lipracer

for mlir fold to avoid too many overflow state check

2024-03-11 06:00 UTC, topperc commented on llvm/lib/Support/APInt.cpp
> +  else
No else after return

2024-03-13 20:06 UTC, kuhar requested changes
Could we exhaustively test this on int8 against some reference implementation? Maybe something in numpy, etc., just to be confident that this implementation is correct.

2024-03-13 20:06 UTC, kuhar commented on llvm/lib/Support/APInt.cpp
> +  auto quotient = sdiv_ov(RHS, Overflow);
nit: APInt instead of auto

2024-03-13 20:06 UTC, kuhar commented on llvm/include/llvm/ADT/APInt.h
> +  APInt sfloordiv_ov(const APInt &RHS, bool &Overflow) const;
This deserves some documentation IMO. Could you add a comment explaining what this calculates?

2024-03-13 20:06 UTC, kuhar commented on llvm/unittests/ADT/APIntTest.cpp
> +      [[maybe_unused]] auto quotient = divisor.sfloordiv_ov(dividend, Overflow);
```suggestion
     (void)divisor.sfloordiv_ov(dividend, Overflow);
```

2024-03-13 20:06 UTC, kuhar commented on llvm/unittests/ADT/APIntTest.cpp
> +    std::apply(check_overflow_all, std::tuple<char, short, int, int64_t>());
Err, is there a more standard way of checking this for all of these types? Could we call this test 3 times instead of doing it this way?

2024-03-14 16:44 UTC, kuhar approved these changes

2024-03-15 11:09 UTC, merged