[NVPTX] Add `-march=general` option to mirror default configuration
llvm/llvm-project pull request #85222
Opened 2024-03-14 13:09 UTC by oraluben

This PR adds `-march=generic` support for the NVPTX backend. This fulfills a TODO introduced in #79873.

With this PR, users can explicitly request the default CUDA architecture. This default is regularly updated, and the most recent configuration as of commit ab202aa sets it to `sm_52`. This value is also assumed when no `-march` option is provided.

This PR does not address any compatibility issues between different CUDA versions.

2024-03-14 13:12 UTC, oraluben commented
@jhuber6 @Artem-B You might want to check if this LGTY :)

2024-03-14 13:19 UTC, jhuber6 requested changes
Thanks for looking at this. When the user compiles with `-march=xyz` it introduces a lot of subtarget specific metadata intro the output IR. The purpose of the original patch was to keep `-target-cpu` unset in cases where `-march=xyz` was not passed in. The expected semantics here is that `-march=sm_52 -march=generic` will override `-march=sm_52` and result in no `-target-cpu` being set just like if you didn't pass `-march` at all.

2024-03-14 13:27 UTC, oraluben commented on clang/test/Driver/cuda-cross-compiling.c
I see, thanks for clarifying!

2024-03-14 13:54 UTC, jhuber6 commented
FWIW I think you can kind of do this with `-march=sm_52 -march=` to just set it to empty.

2024-03-15 12:59 UTC, jhuber6 approved these changes
LG, thanks for the patch.

2024-03-15 14:13 UTC, jhuber6 commented on clang/lib/Driver/ToolChains/Cuda.cpp
> +  } else if (DAL->getLastArgValue(options::OPT_march_EQ) == "generic") {
```suggestion
  } else if (DAL->getLastArgValue(options::OPT_march_EQ) == "generic"
                 && OffloadKind == Action::OFK_None) {
```
Ah, forgot, we probably don't want to expose this to CUDA just yet.

2024-03-15 22:16 UTC, merged