[Scalar] Resolve FIXME: No Lowering of FNeg to FMul unless it is safe
llvm/llvm-project pull request #85252
Opened 2024-03-14 15:43 UTC by AtariDreams

Or association flags are specified.

2024-03-14 16:01 UTC, dtcxzyw commented
Could you please provide the proof? I cannot prove the correctness with alive2.

2024-03-14 17:07 UTC, dtcxzyw commented
https://alive2.llvm.org/ce/z/Ki3Rf2

`nnan` is all you need :)

2024-03-14 17:10 UTC, dtcxzyw requested changes

2024-03-15 08:16 UTC, arsenm commented
> https://alive2.llvm.org/ce/z/Ki3Rf2
> 
> `nnan` is all you need :)

In this context, it's not simply doing this transform in isolation. It's being consumed by another canonicalizing operation. The problem is this is introducing a canonicalization, which doesn't matter if it's only used by operations that canonicalize the inputs. nnan would not be sufficient to introduce this, since operations may also do other bit pattern changing side effects (like denormal flush). Since this is consumed by a canonicalizing operation, it's either correct to always do (in the has one use case) (or it's wrong to ever do).

2024-03-15 08:16 UTC, arsenm requested changes

2024-03-15 08:16 UTC, arsenm commented on llvm/test/Transforms/Reassociate/fast-basictest.ll
> +  %mul = fmul fast float %neg, %b
Don't need the full set of fast flags. Also don't need it on every instruction. Should target testing missing specific flags contexts

2024-03-15 08:16 UTC, arsenm commented on llvm/test/Transforms/Reassociate/fast-basictest.ll
> +}
Also add test where it's know not-nan from the source

2024-03-15 08:17 UTC, arsenm commented
> which doesn't matter if it's only used by operations that canonicalize the inputs. 

I guess we technically don't guarantee canonicalization on FP operations, but I think we can assert that it may happen

2024-09-10 13:14 UTC, closed without merging