[clang] Add `__has_extension(swiftcc)` support
llvm/llvm-project pull request #85347
Opened 2024-03-15 01:40 UTC by kateinoigakukun

This patch adds `swiftcc` feature to check if the target supports Swift calling convention as well as we do for `swiftasynccc`.

This support is necessary to fix https://github.com/apple/swift/issues/72343

2024-03-15 13:35 UTC, aschwaighofer requested changes
In a past review (https://github.com/llvm/llvm-project/pull/72159), @AaronBallman noted that the existing use of `FEATURE` (as in `FEATURE(swiftasynccc,...`) was not the right qualifier to use. And it should have been an `EXTENSION` instead. We should use `EXTENSION` for the `swiftcc` check.

Quoting from the top of the file:
```
// FEATURE(...) should be used to advertise support for standard language       
// features, whereas EXTENSION(...) should be used for clang extensions. Note   
// that many of the identifiers in this file don't follow this rule for backward
// compatibility reasons.
```

2024-03-15 13:35 UTC, aschwaighofer commented on clang/include/clang/Basic/Features.def
> +FEATURE(swiftcc,
I think we should use `EXTENSION` instead of `FEATURE`.

2024-03-15 14:28 UTC, AaronBallman reviewed
You should also add documentation for this to https://github.com/llvm/llvm-project/blob/main/clang/docs/LanguageExtensions.rst and a release note for the change in https://github.com/llvm/llvm-project/blob/main/clang/docs/ReleaseNotes.rst.

2024-03-15 16:29 UTC, kateinoigakukun commented
Oh, I didn't see the past discussion. Thanks!

2024-03-18 16:36 UTC, AaronBallman reviewed
I'm happy enough with the changes so long as Swift folks are okay with the change in behavior for existing code. CC @compnerd @rjmccall for opinions (I'll leave the approval to one of them).

2024-03-18 17:38 UTC, rjmccall approved these changes
Yeah, it's fine with me.

2024-03-19 01:20 UTC, compnerd approved these changes
Might be nice to have a test for `swiftasynccc` as well.

2024-03-20 11:26 UTC, AaronBallman commented
Do you need someone to commit this on your behalf?

2024-03-20 12:18 UTC, merged