[libc] stop including unistd.h in src/
llvm/llvm-project pull request #85971
Opened 2024-03-20 17:23 UTC by nickdesaulniers

It's not hermetic to include the system libc's headers and is one of the
reasons why our linter bot has been very red for a long time.

This is starting to be an issue for new contributors as well, since we're now
getting conflicts between the parts of our codebase that are hermetic, vs parts
that aren't.

I need to think about a rule of thumb or policy that can be publicly documented
so that we don't backslide.

I should probably clean up test/ as well, but let's clean up just src/ to
unblock fellow contributors.

Link: https://github.com/llvm/llvm-project/pull/85514#discussion_r1532078163

2024-03-20 17:27 UTC, nickdesaulniers commented on libc/src/unistd/getopt.h
> +#include "src/__support/common.h"
not necessary

2024-03-20 17:34 UTC, michaelrj-google reviewed
You also need to update the bazel.

2024-03-20 21:27 UTC, nickdesaulniers commented
hmm...[a previous run](https://buildkite.com/llvm-project/github-pull-requests/builds/49030#018e5ce9-23c6-46aa-8713-8273405897c2) showed a failure running `ninja libc_unistd_unittests` for libc/test/src/unistd/sysconf_test.cpp. I wonder what could be going wrong there. I can't seem to reproduce locally.

2024-03-20 21:40 UTC, nickdesaulniers commented
> hmm...a previous run showed a failure running ninja libc_unistd_unittests for libc/test/src/unistd/sysconf_test.cpp. I wonder what could be going wrong there. I can't seem to reproduce locally.

Perhaps the inclusion of <unistd.h> in libc/test/src/unistd/sysconf_test.cpp is getting a different value for _SC_PAGESIZE than the one we provide.

We define this value to 1, but glibc's it's 30. Bionic defines this to 0x0027 (39).

2024-03-20 22:27 UTC, michaelrj-google approved these changes
LGTM

2024-04-23 21:38 UTC, michaelrj-google requested changes
This patch needs to be updated to use the new header indirection design.

2026-07-16 16:11 UTC, closed without merging