[mlir][emitc] Arith to EmitC: Handle addi, subi and muli
llvm/llvm-project pull request #86120
Opened 2024-03-21 14:01 UTC by mgehre-amd

No handling yet for divsi and divui, as they require special considerations for signedness.

2024-03-21 14:18 UTC, marbre commented
> No handling yet for divsi and divui, as they require special considerations for signedness.

Probably we already need some special considerations for this case. E.g. for `arith.addi` the docs https://mlir.llvm.org/docs/Dialects/ArithOps/#arithaddi-arithaddiop state

> Performs N-bit addition on the operands. The operands are interpreted as unsigned bitvectors. The result is represented by a bitvector containing the mathematical value of the addition modulo 2^n, where n is the bitwidth. 

Following https://en.cppreference.com/w/cpp/language/operator_arithmetic#Overflows

> Unsigned integer arithmetic is always performed modulo 2n where n is the number of bits in that particular integer.

we should probably cast to unsigned, perform the arithmetic operation and add another cast. WDYT?

2024-03-21 14:25 UTC, marbre reviewed
> No handling yet for divsi and divui, as they require special considerations for signedness.

Probably we already need some special considerations for this case. E.g. for `arith.addi` the docs https://mlir.llvm.org/docs/Dialects/ArithOps/#arithaddi-arithaddiop state

> Performs N-bit addition on the operands. The operands are interpreted as unsigned bitvectors. The result is represented by a bitvector containing the mathematical value of the addition modulo 2^n, where n is the bitwidth.

Following https://en.cppreference.com/w/cpp/language/operator_arithmetic#Overflows

> Unsigned integer arithmetic is always performed modulo 2n where n is the number of bits in that particular integer.

we should probably cast to unsigned, perform the arithmetic operation and add another cast. WDYT?

2024-03-21 15:06 UTC, mgehre-amd commented
> > No handling yet for divsi and divui, as they require special considerations for signedness.
> 
> Probably we already need some special considerations for this case. E.g. for `arith.addi` the docs [mlir.llvm.org/docs/Dialects/ArithOps/#arithaddi-arithaddiop](https://mlir.llvm.org/docs/Dialects/ArithOps/#arithaddi-arithaddiop) state
> 
> > Performs N-bit addition on the operands. The operands are interpreted as unsigned bitvectors. The result is represented by a bitvector containing the mathematical value of the addition modulo 2^n, where n is the bitwidth.
> 
> Following [en.cppreference.com/w/cpp/language/operator_arithmetic#Overflows](https://en.cppreference.com/w/cpp/language/operator_arithmetic#Overflows)
> 
> > Unsigned integer arithmetic is always performed modulo 2n where n is the number of bits in that particular integer.
> 
> we should probably cast to unsigned, perform the arithmetic operation and add another cast. WDYT?

Good point, this will otherwise cause UB for when the C types are signed.

2024-03-22 08:30 UTC, simon-camp commented on mlir/lib/Conversion/ArithToEmitC/ArithToEmitC.cpp
> +
Return a match failure for `i1`, as these are emitted as `bool` and the arithmetic doesn't wrap around as expected. We can add additional patterns in a follow up.

2024-03-22 08:33 UTC, simon-camp requested changes

2024-03-22 08:33 UTC, simon-camp commented on mlir/test/Conversion/ArithToEmitC/arith-to-emitc.mlir
> +  // CHECK: %[[C1:[^ ]*]] = emitc.cast %arg0 : i32 to ui3
```suggestion
  // CHECK: %[[C1:[^ ]*]] = emitc.cast %arg0 : i32 to ui32
```
Same for the lines below

2024-03-22 13:53 UTC, marbre approved these changes
Thanks, looks good now :) Just one minor _wish_, could you maybe add a more descriptive commit message? I think what is in the PR description right now is more additional context for review but not necessarily adding value as part of a commit message.

2024-03-22 14:39 UTC, merged