[DirectX][DXIL] Align type spec of TableGen DXIL Op mapping with that of LLVM Intrinsic
llvm/llvm-project pull request #86311
Opened 2024-03-22 16:59 UTC by bharadwajy

Align specification of return type and parameter type fields of DXIL Op mapping with those of TableGan class Intrinsic.

A `void` return type of LLVM Intrinsic is represented as `[]` in its TableGen description record. Currently, a `void` return type of DXIL Operation is represented as `[llvm_void_ty]`. In addition, return and parameter types are recorded as a single list with an understanding that element at index `0` is the return type.

These changes leverage and align DXIL Op type specification with the type specification of the LLVM Intrinsic. As a result, return and parameter types are now specified as two separate lists no longer requiring a different representation for `void` return type. Additionally, type specification would be more succinct yet equally informative for DXIL Op records for which the same LLVM Intrinsics types are also valid.

Added a test to verify lowering of LLVM intrinsic with `void` return.

Barrier intrinsic has a `void` return type. Specification of its DXIL Op can inherit the types of this intrinsic. The test verifies the changes.

Move OverloadKind to DXILABI.h.

Fixes #86229

2024-03-25 18:30 UTC, coopp approved these changes
Yeah.. This looks like it is now matching Justin's PR.

2024-03-25 20:27 UTC, bharadwajy commented on llvm/include/llvm/Support/DXILABI.h
> +  Invalid = 0,
> This change is dup with [a83ed04](https://github.com/llvm/llvm-project/commit/a83ed0423dcafd4fecb15994a5c5c8b85a56f59b) , may need to sync and rebase.

Done.

2024-03-25 20:39 UTC, bogner approved these changes

2024-03-25 23:48 UTC, llvm-beanz requested changes
I want to put the breaks on this PR.

We have a document that is documenting this design which is inconsistent with this PR. Before we merge this we should make the documentation consistent. The doc PR is here: https://github.com/llvm/llvm-project/pull/85170.

2024-03-29 22:28 UTC, bharadwajy commented
> I want to put the breaks on this PR.
> 
> We have a document that is documenting this design which is inconsistent with this PR. Before we merge this we should make the documentation consistent. The doc PR is here: #85170.

Updated the document 
1. to reflect the changes proposed in this PR. 
2. with details of another option - along with a link to corresponding changes.

Thanks!

2024-03-29 22:49 UTC, llvm-beanz reviewed
I'm not going to block this, but I'm still unsure that the documentation is clear and covers all the cases we need. I'll defer to @bogner.

2024-03-29 23:11 UTC, bharadwajy commented
> I'm not going to block this, but I'm still unsure that the documentation is clear and covers all the cases we need. I'll defer to @bogner.

I think I prefer the Option 3 (Leverage the existing classification of DXIL Operations) in the updated design document (#85170) compared to the one proposed in this PR for the reasons specified there. I'll explore its current implementation (changeset link in the design doc) a bit more and submit a PR that potentially overrides this one. 

Thanks!

2024-04-09 17:21 UTC, bharadwajy commented
Taking a different design direction - see PR #87803. Closing.

2024-04-09 17:21 UTC, closed without merging