[clang][ExtractAPI] Add ability to create multiple symbol graphs
llvm/llvm-project pull request #86676
Opened 2024-03-26 14:55 UTC by daniel-grumberg

This allows to segregate symbols that are extending symbols from other modules into a spearate graph. This also uses the opportunity to clean up the emit-symbol-graph interface.

2024-03-26 15:21 UTC, QuietMisdreavus commented on clang/include/clang/ExtractAPI/API.h
> +
Looks like `NextInContext` is typo'd here.

2024-03-26 16:08 UTC, QuietMisdreavus commented on clang/include/clang/ExtractAPI/Serialization/APISetVisitor.h
> +/// the dynamic type of 'node', call a user-overridable function to actually
Should this `'node'` here actually say `'record'`?

2024-03-26 16:39 UTC, QuietMisdreavus commented on clang/lib/ExtractAPI/Serialization/SymbolGraphSerializer.cpp
> +  // If the hierarchy has at leas one parent and child.
Typo:
```suggestion
  // If the hierarchy has at least one parent and child.
```

2024-03-26 17:14 UTC, QuietMisdreavus commented on clang/test/ExtractAPI/objc_block.m
> +// RUN: Filecheck %s --input-file %t/output.symbols.json --check-prefix NOPARAM
Is this `Filecheck` (not `FileCheck`) valid? I'm not sure if this will work properly on all platforms where these tests are run.

2024-03-26 17:20 UTC, QuietMisdreavus commented on clang/test/ExtractAPI/objc_external_category.m
> +// RUN: Filecheck %s --input-file  %t/symbols/Module.symbols.json --check-prefix MOD
Same `Filecheck` capitalization issue.

2024-03-26 17:24 UTC, daniel-grumberg commented on clang/tools/libclang/CXExtractAPI.cpp
> +    return VisitObjCInterfaceDecl(Decl->getClassInterface());
Restore logic to grab symbols defined only in the implementation. First visit the interface and then add the things only defined in the implementation block to the interface record.

2024-03-26 17:25 UTC, daniel-grumberg commented on clang/tools/libclang/CXExtractAPI.cpp
> -    if (WalkupParentContext<ObjCContainerDecl>(Parent, Visitor))
Restore this logic for objc types?

2024-03-26 17:30 UTC, QuietMisdreavus requested changes
Looks mostly good, though i would have preferred having multiple commits to wade through rather than having to spend 2.5 hours walking through it in person :wink: There are some comments that came out of that chat that i'd like to see addressed or investigated.

2024-03-28 23:45 UTC, QuietMisdreavus approved these changes
Looks good, thanks!

2024-04-02 14:03 UTC, merged

2024-04-02 14:42 UTC, daniel-grumberg commented
Just reverted this due to buildbot failures in `Misc/warning-flags.c` will reenable shortly.