[AMDGPU] Fix missing `IsExact` flag when expanding vector binary operator
llvm/llvm-project pull request #86712
Opened 2024-03-26 18:47 UTC by shiltian

2024-03-26 18:48 UTC, shiltian commented
I'll update the test case in https://github.com/llvm/llvm-project/pull/83155 once that patch is landed to test this patch.

2024-03-27 08:54 UTC, arsenm requested changes
Missing test

2024-03-27 08:55 UTC, arsenm commented
> I'll update the test case in #83155 once that patch is landed to test this patch.

The code is already tested, just add a case with exact

2024-03-27 09:34 UTC, jayfoad commented on llvm/lib/Target/AMDGPU/AMDGPUCodeGenPrepare.cpp
> +          if (PossiblyExactOperator::isPossiblyExactOpcode(
Can you use something simpler like `NewEltI->copyIRFlags(I)`?

2024-03-27 17:05 UTC, shiltian commented
> > I'll update the test case in #83155 once that patch is landed to test this patch.
> 
> The code is already tested, just add a case with exact

Done.

2024-03-27 17:13 UTC, jayfoad approved these changes
LGTM

2024-03-27 21:40 UTC, merged