[libc++] <experimental/simd> Add compound assignment operators for simd reference
llvm/llvm-project pull request #86761
Opened 2024-03-27 03:03 UTC by joy2myself

2024-04-15 06:33 UTC, joy2myself commented
@philnik777 Hi! This and the other two patches (https://github.com/llvm/llvm-project/pull/86478, https://github.com/llvm/llvm-project/pull/88091) are ready for review.

2024-07-08 05:32 UTC, joy2myself commented
@philnik777 Gentle ping.

2024-07-19 04:52 UTC, joy2myself commented
Hi @philnik777,

Just following up on this PR and #88091. Could you please take a look when you get a chance?

I have some follow-up patches ready, but they may depend on these currently open PRs. It would be great if these two PRs could be merged soon.

Thanks!

2024-07-19 07:23 UTC, philnik777 requested changes
Sorry for the slow review, I didn't have a lot of time recently.

2024-07-19 07:23 UTC, philnik777 commented on libcxx/include/experimental/__simd/reference.h
> +#  undef _LIBCXX_SIMD_REFERENCE_OP_
I think we should just expand this. Macros result in notoriously bad error messages and here it really doesn't seem that bad to just expand the macros.

2024-07-19 07:23 UTC, philnik777 commented on libcxx/test/std/experimental/simd/simd.reference/reference_operators.pass.cpp
> +  };
Could we refactor this to take an operation as a functor instead? So the instantiation looks something like `SimdReferenceOperatorHelper<T, SimdAbi, decltype([](auto& lsh, auto ths) { lhs += rhs; })>` etc.

2024-07-19 07:23 UTC, philnik777 commented on libcxx/include/experimental/__simd/reference.h
> +    template <class _Up, class = decltype(std::declval<value_type&>() __op## = std::declval<_Up>())>                   \
Isn't this just `is_assignable`?

2024-08-02 06:56 UTC, joy2myself commented
@philnik777 Hello, I have removed all macro definitions according to your comment. However, the compiler does not allow lambda expressions to be passed directly into the template, so I use struct to wrap lambda expressions to pass template parameters in test files.

In addition, due to the error of insufficient memory or flash capacity in ARMv7 CI, I split the test cases into two test files.

Any other comments?

2024-08-02 08:36 UTC, philnik777 approved these changes

2024-08-02 08:36 UTC, philnik777 commented on libcxx/include/experimental/__simd/reference.h
> +      enable_if_t<is_assignable_v<value_type&, decltype(std::declval<value_type&>() + std::declval<_Up>())&&>, int> = 0>
I think this should be reverted to the previous state. I misread what this did before, sorry.

2024-08-04 02:16 UTC, merged