[Clang][Sema] Fix explicit specializations of member function templates with a deduced return type
llvm/llvm-project pull request #86817
Opened 2024-03-27 15:44 UTC by sdkrystian

Currently, clang erroneously rejects the following:
```cpp
template<typename T>
struct A
{
    template<typename U>
    auto f();
};

template<>
template<typename U>
auto A<int>::f(); // error: conflicting types for 'f'
```
This happens because the explicit specialization of `f` has its return type replaced with a dependent `AutoType` in `ActOnFunctionDeclarator`, but no such replacement occurs for the implicitly instantiated function template `A<int>::f`. Since the return types don't match, the explicit specialization is diagnosed as an invalid redeclaration. 

This patch moves the replacement of the return type to `CheckFunctionDeclaration` so it also happens during instantiation. `setObjectOfFriendDecl` will have been called by then, so the `isFriend && CurContext->isDependentContext()` condition is made redundant & removed (as it already happens in `DeclContext::isDependentContext`). `Sema::IsOverload` only checks the _declared_ return type (which isn't changed by the adjustment), so adjusting the return type afterwards should be safe.

2024-03-27 15:45 UTC, sdkrystian commented
Still needs a release note but should otherwise be good to go

2024-03-28 18:05 UTC, Sirraide requested changes
LGTM after looking at this for a while, except for some minor comments.

2024-03-29 15:43 UTC, sdkrystian commented on clang/lib/Sema/SemaDecl.cpp
> +  //   operand.
I changed both quotes to "C++"

2024-03-29 15:49 UTC, sdkrystian commented on clang/docs/ReleaseNotes.rst
> +  to be explicitly specialized for a given implicit instantiation of the class template.
How about:
> Fixed a bug that prevented member function templates of class templates declared with a deduced return type from being explicitly specialized for a given implicit instantiation of the class template.

2024-03-29 16:43 UTC, Sirraide commented on clang/docs/ReleaseNotes.rst
> +  to be explicitly specialized for a given implicit instantiation of the class template.
Sure, that probably works.

2024-03-29 16:44 UTC, Sirraide approved these changes
LGTM

2024-04-01 17:04 UTC, sdkrystian commented
Ping @erichkeane

2024-04-01 17:48 UTC, erichkeane approved these changes

2024-04-02 12:35 UTC, merged