[LLDB] Add APFloat helper functions to Scalar class.
llvm/llvm-project pull request #86862
Opened 2024-03-27 19:39 UTC by cmtice

This adds the ability to create a Scalar from an APFloat, and to create an APFloat from an APSInt or another APFloat.

2024-03-27 23:53 UTC, bulbazord requested changes
Could you add a test for these new methods in `unittests/Utility/ScalarTest.cpp`?

2024-03-28 22:21 UTC, cmtice commented
> Could you add a test for these new methods in `unittests/Utility/ScalarTest.cpp`?

Done. :-)

2024-03-28 23:24 UTC, JDevlieghere approved these changes

2024-03-29 04:29 UTC, bulbazord approved these changes

2024-03-29 04:29 UTC, bulbazord commented
> > Could you add a test for these new methods in `unittests/Utility/ScalarTest.cpp`?
> 
> Done. :-)

Thank you! :)

2024-03-29 04:39 UTC, merged