goldsteinn/kb nuw add
llvm/llvm-project pull request #87180
Opened 2024-03-31 03:42 UTC by goldsteinn

- **[ValueTracking] Add tests for computing knownbits from `(icmp ult/ule (add nuw X, Y), C)`; NFC**
- **[ValueTracking] Compute knownbits from `(icmp ult/ule (add nuw X, Y), C)`**

2024-03-31 07:04 UTC, dtcxzyw requested changes

2024-03-31 07:04 UTC, dtcxzyw commented on llvm/lib/Analysis/ValueTracking.cpp
> +          // X | Y u< C -> X u< C && Y u< C
Please update the comments.

2024-04-01 06:56 UTC, dtcxzyw commented
Can you have a look at the regression https://github.com/dtcxzyw/llvm-opt-benchmark/pull/465#discussion_r1546021756?

2024-04-01 18:42 UTC, goldsteinn commented
> Can you have a look at the regression [dtcxzyw/llvm-opt-benchmark#465 (comment)](https://github.com/dtcxzyw/llvm-opt-benchmark/pull/465#discussion_r1546021756)?

Okay, reduced test:
```
define void @foo(i32 %x, i32 %y) {
  %z = add nuw i32 %x, %y
  %cmp0 = icmp ult i32 %z, 255
  br i1 %cmp0, label %L0, label %L2

L0:
  %sub_x = sub i32 255, %x
  br label %L1

L1:
  %phi = phi i32 [ 0, %L0 ], [ 1, %L1 ]
  %cmp1 = icmp ult i32 %phi, %sub_x
  br i1 %cmp1, label %L1, label %L2

L2:
  ret void
}
```

The issue occurs due to the InstCombine fold at:
https://github.com/llvm/llvm-project/blob/main/llvm/lib/Transforms/InstCombine/InstCombineAddSub.cpp#L2280-L2288

We produce:

**Bad:**
```
define void @foo(i32 %x, i32 %y) local_unnamed_addr {
  %z = add nuw i32 %x, %y
  %cmp0 = icmp ult i32 %z, 255
  br i1 %cmp0, label %L0, label %L2

L0:                                               ; preds = %0
  %sub_x = xor i32 %x, 255
  br label %L1

L1:                                               ; preds = %L1, %L0
  %phi = phi i32 [ 0, %L0 ], [ 1, %L1 ]
  %cmp1 = icmp ult i32 %phi, %sub_x
  br i1 %cmp1, label %L1, label %L2

L2:                                               ; preds = %L1, %0
  ret void
}
```

vs
**Good:**
```
define void @foo(i32 %x, i32 %y) local_unnamed_addr {
  %z = add nuw i32 %x, %y
  %cmp0 = icmp ult i32 %z, 255
  br i1 %cmp0, label %L0, label %L2

L0:                                               ; preds = %0
  %sub_x = sub i32 255, %x
  br label %L1

L1:                                               ; preds = %L1, %L0
  %phi = phi i32 [ 0, %L0 ], [ 1, %L1 ]
  %cmp1 = icmp ult i32 %phi, %sub_x
  br i1 %cmp1, label %L1, label %L2

L2:                                               ; preds = %L1, %0
  ret void
}
```

The issue then arises because we fold `(icmp eq/ne (sub C0, x), C1)` -> `(icmp eq/ne x, C2)` even if the sub has multi-use but we don't do the same for `xor`:
https://github.com/llvm/llvm-project/blob/main/llvm/lib/Transforms/InstCombine/InstCombineCompares.cpp#L3463-L3474

Ill add a patch for the `xor` case.

2024-04-04 16:46 UTC, goldsteinn commented
My preference would be to not have this blocked by the missing multi-use xor fold. It seems pretty unrelated that we end up with that pattern w/ this patch but not w/ (in that one case) and handling multi-use xor seems independently valuable.

2024-04-05 01:56 UTC, goldsteinn commented
@dtcxzyw i update with support for `sub nuw` as well.

2024-04-11 18:09 UTC, goldsteinn commented
rebased

2024-04-25 03:15 UTC, nikic commented
Needs another rebase.

> @dtcxzyw i update with support for `sub nuw` as well.

Why?

2024-04-25 16:01 UTC, goldsteinn commented
> Needs another rebase.
> 
> > @dtcxzyw i update with support for `sub nuw` as well.
> 
> Why?

I guess the `add nuw` mirrors the `or` case and the `sub nuw` mirrors the `and` case. I had meant to leave it as a folllowup todo but it seemed to fit well enough.

2024-05-05 00:24 UTC, goldsteinn commented
ping

2024-05-10 19:08 UTC, goldsteinn commented
ping

2024-05-16 03:30 UTC, nikic approved these changes
LGTM

2024-05-16 03:30 UTC, nikic commented on llvm/test/Transforms/InstCombine/known-bits.ll
> +}
Negative tests without nuw?

2024-05-16 17:26 UTC, goldsteinn commented on llvm/test/Transforms/InstCombine/known-bits.ll
> +}
done + rebased/

2024-05-16 18:04 UTC, closed without merging