[clang-format] Fix a regression in annotating BK_BracedInit
llvm/llvm-project pull request #87450
Opened 2024-04-03 04:40 UTC by owenca

Fixes #86539.

2024-04-03 15:21 UTC, hnakamura5 requested changes, later dismissed

2024-04-03 16:12 UTC, owenca commented on clang/lib/Format/UnwrappedLineParser.cpp
> -    if (!Style.isTableGen()) {
I figured that you added the guard for a reason, but there were no unit tests for it. Can you give an example why it’s necessary?

2024-04-04 16:57 UTC, owenca commented on clang/lib/Format/UnwrappedLineParser.cpp
> -    if (!Style.isTableGen()) {
It doesn't seem to make a difference on the above example, but I put the guard back in. We can add a `TableGen` test case for the guard in another patch.

2024-04-04 19:12 UTC, HazardyKnusperkeks approved these changes

2024-04-05 00:55 UTC, merged

2024-04-19 16:05 UTC, owenca commented
/cherry-pick 7c9c38eaa9b7