goldsteinn/non zero overflow
llvm/llvm-project pull request #87701
Opened 2024-04-04 20:37 UTC by goldsteinn

- **[ValueTracking] Add tests for overflow detection functions is `isKnownNonZero`; NFC**
- **[ValueTracking] Split `isNonZero(mul)` logic to a helper; NFC**
- **[ValueTracking] Add support for overflow detection functions is `isKnownNonZero`**

2024-04-05 13:08 UTC, dtcxzyw requested changes

2024-04-05 16:03 UTC, goldsteinn commented on llvm/test/Transforms/InstSimplify/known-non-zero.ll
> +define i1 @extract_value_uadd(i8 %xx, i8 %yy) {
I think you do understand correctly. I think basically all of our extra logic for `isNonZeroAdd` is really dup logic of proving `nuw`.

2024-04-05 16:22 UTC, goldsteinn commented on llvm/test/Transforms/InstSimplify/known-non-zero.ll
> +define i1 @extract_value_uadd(i8 %xx, i8 %yy) {
Fixed (made it a vec test w/ partial nuw where we can prove for the demandedelts).

2024-04-09 08:24 UTC, nikic approved these changes
LGTM

2024-04-09 08:24 UTC, nikic commented on llvm/test/Transforms/InstCombine/known-bits.ll
> +  %add_sov = call { i8, i1} @llvm.sadd.with.overflow(i8 %x, i8 %y)
```suggestion
  %add_sov = call { i8, i1 } @llvm.sadd.with.overflow(i8 %x, i8 %y)
```
Here and elsewhere.

2024-04-09 08:24 UTC, nikic commented on llvm/lib/Analysis/ValueTracking.cpp
> +      switch (WO->getIntrinsicID()) {
Could slightly simplify this by matching on getBinaryOp().

2024-04-10 15:41 UTC, closed without merging