[LLVM][CodeGen][AArch64] Remove bogus lowering of sve_while{gt/ge/hi/hs} intrinsics.
llvm/llvm-project pull request #88126
Opened 2024-04-09 13:49 UTC by paulwalker-arm

When fed constant operands we try to lower WHILE intrinsics to PTRUE using a fixed length pattern.  This is not valid for the decrementing variants of WHILE because they construct their result predicate vector by traversing from high->low lanes whereas the incrementing variants and PTRUE traverse from low->high lanes.

Whilst we can still utilise PTRUE by reversing its result I figure replacing a single WHILE with multiple SVE instructions is likely counterproductive.

2024-04-11 09:03 UTC, dtemirbulatov approved these changes
LGTM, With unused tests now could be removed.

2024-04-11 23:28 UTC, dtemirbulatov requested changes
Sorry, While revisiting this review once again examining the chane, I am a bit confused now. If we look at WHILE{GT/GE/HI,HS} instructions, according to the spec it says:
...
for e = elements-1 downto 0
...
Looks like it should not be a problem for traversing from high->low lanes?

2024-04-12 09:44 UTC, paulwalker-arm commented
> Sorry, While revisiting this review once again examining the change, I am a bit confused now. If we look at WHILE{GT/GE/HI,HS} instructions, according to the spec it says: ... for e = elements-1 downto 0 ... Looks like, it should not be a problem for traversing from high->low lanes?

The fact the WHILE{GT/GE/HI,HS} instructions traverse from high->low lanes is what makes the replacement with PTRUE incorrect.  For example:
```
whilege(2,0) -> 0 0 0 0 0 1 1 1
```
whereas:
```
ptrue vl3    -> 1 1 1 0 0 0 0 0
```

2024-04-12 10:19 UTC, sdesmalen-arm approved these changes

2024-04-12 10:19 UTC, sdesmalen-arm commented on llvm/lib/Target/AArch64/AArch64ISelLowering.cpp
>  static SDValue optimizeWhile(SDValue Op, SelectionDAG &DAG, bool IsSigned,
minor nit: is it worth renaming this to `optimizeIncrementingWhile` to distinguish it further?

2024-04-12 10:49 UTC, dtemirbulatov approved these changes

2024-04-15 11:51 UTC, merged