[clang-tidy] Export fixes from check_clang_tidy.py
llvm/llvm-project pull request #88186
Opened 2024-04-09 20:14 UTC by revane

Makes it possible to export fixes from running llvm-lit on a clang-tidy test. To enable, modify the RUN invocation directly in the test with the new -export flag. llvm-lit will report the test passed and fixes can be found in the file specified to the -export flag.

2024-04-10 13:45 UTC, revane commented
@PiotrZSL @carlosgalvezp @LegalizeAdulthood @njames93 For your consideration.

2024-04-10 14:46 UTC, EugeneZelenko commented on clang-tools-extra/docs/ReleaseNotes.rst
> +- Improved :program:`check_clang_tidy.py` script. Added argument `-export`
Please merge with previous entry.

2024-04-10 17:43 UTC, EugeneZelenko commented on clang-tools-extra/docs/ReleaseNotes.rst
> +- Improved :program:`check_clang_tidy.py` script. Added argument `-export`
Sorry, my bad - I missed that tool names are different :-( Please drop later commit.

2024-04-12 14:32 UTC, revane commented
@AaronBallman Other reviewers you would suggest?

2024-04-12 18:26 UTC, PiotrZSL requested changes
Rename this from -export to -export-fixes, because that's what it is, and could land.

2024-04-12 18:26 UTC, PiotrZSL commented on clang-tools-extra/test/clang-tidy/check_clang_tidy.py
> +        "-export",
can't we call it export-fixes ?

2024-04-12 18:26 UTC, PiotrZSL commented on clang-tools-extra/test/clang-tidy/check_clang_tidy.py
> +        self.export = args.export
export_fixes

2024-04-12 18:49 UTC, revane commented on clang-tools-extra/test/clang-tidy/check_clang_tidy.py
> +        self.export = args.export
Done

2024-04-12 18:49 UTC, revane commented on clang-tools-extra/test/clang-tidy/check_clang_tidy.py
> +        "-export",
Done

2024-04-12 20:24 UTC, PiotrZSL approved these changes

2024-04-13 19:01 UTC, merged