[InstCombine] Fold -X/-Y -> X / Y
llvm/llvm-project pull request #88422
Opened 2024-04-11 18:09 UTC by AtariDreams

Alive Proofs:

https://alive2.llvm.org/ce/z/zLMokH
https://alive2.llvm.org/ce/z/xviNg3
https://alive2.llvm.org/ce/z/4rdGvf

2024-04-11 18:41 UTC, goldsteinn commented on llvm/lib/Transforms/InstCombine/InstCombineMulDivRem.cpp
> +  if (!KnownDividend.getMinValue().isMinSignedValue() &&
getSignedMinValue()

2024-04-11 18:42 UTC, goldsteinn commented on llvm/lib/Transforms/InstCombine/InstCombineMulDivRem.cpp
> +    NewNeg->setHasNoSignedWrap(true);
true is unnecessary.

2024-04-11 18:43 UTC, goldsteinn commented on llvm/lib/Transforms/InstCombine/InstCombineMulDivRem.cpp
> +  }
Its a bit less clear to me the `-(X / Y)` is preferable to `X / -Y`.

2024-04-11 18:48 UTC, goldsteinn commented
The second and third proof seem unrelated?
Also the first proof is incorrect w.o the `noundef` i.e: https://alive2.llvm.org/ce/z/22Bers
you need to make sure the div will not trigger immediate UB. Please update your code and proofs accordingly.

2024-04-11 18:50 UTC, dtcxzyw commented
Is there any real-world motivation for these transforms?

2024-04-11 18:59 UTC, AtariDreams commented
> Is there any real-world motivation for these transforms?

Absolutely.

Negation of divisor and dividend are common when working with macros especially in older C code back when constexpr were not a thing and offsets were calculated via:

...

#define X_START  0
#define Y_START = 0

int distanceFromX = X_START - x;
int distanceFromY = Y_START - y;

int rate = distanceFromY/distanceFromX

Yes, I know that a lot of code doesn't look like this anymore, but for a lot of software this was pretty much how it looked.

2024-04-11 19:03 UTC, AtariDreams commented
> The second and third proof seem unrelated? Also the first proof is incorrect w.o the `noundef` i.e: https://alive2.llvm.org/ce/z/22Bers you need to make sure the div will not trigger immediate UB. Please update your code and proofs accordingly.

I fill find out how to deal with those but for now I will opt for the check of no poison or undef

2024-04-11 19:13 UTC, dtcxzyw requested changes

2024-04-11 19:13 UTC, dtcxzyw commented on llvm/lib/Transforms/InstCombine/InstCombineMulDivRem.cpp
> +  }
It has been handled by following two folds.

2024-04-11 19:13 UTC, dtcxzyw commented on llvm/lib/Transforms/InstCombine/InstCombineMulDivRem.cpp
> +  if (match(&I, m_SDiv(m_OneUse(m_Value(X)), m_Value(Y))))
```suggestion
  if (match(&I, m_SDiv(m_OneUse(m_NSWNeg(m_Value(X))), m_Value(Y))))
```

2024-04-11 19:17 UTC, dtcxzyw commented
> a lot of software this was pretty much how it looked.

I will accept this patch when we meet this pattern in some real-world applications.

2024-04-12 14:04 UTC, kparzysz commented
> I will accept this patch when we meet this pattern in some real-world applications.

If we see it in an actual application, it means that some customer has encountered an optimization opportunity which we missed. Handling potential issues before they happen is a reasonable thing to to.

What concerns do you have with this patch as-is?

2024-04-12 14:12 UTC, AtariDreams commented
I realized there are some bugs I encountered with this fold I'll mark it as draft

2024-04-13 08:01 UTC, dtcxzyw commented
> > I will accept this patch when we meet this pattern in some real-world applications.
> 
> If we see it in an actual application, it means that some customer has encountered an optimization opportunity which we missed. Handling potential issues before they happen is a reasonable thing to to.

I disagree. Adding unused folds makes InstCombine slow and buggy. It is also a maintenance burden for our LLVM developers and researchers who develop fuzzers and formal-method based tools.

> What concerns do you have with this patch as-is?

I am not willing to pay for the expensive call to `computeKnownBits(Op1, 0, &I)`.

2024-04-13 08:14 UTC, dtcxzyw approved these changes
LGTM. But I will leave it to other reviewers to decide if we should merge this patch.

2024-04-13 08:14 UTC, dtcxzyw commented on llvm/lib/Transforms/InstCombine/InstCombineMulDivRem.cpp
> +        // FIXME: Hack for checking if is -1, which is just all ones
This FIXME may be misleading. Can we improve it in the future? If not, please drop this line.

2024-04-13 11:25 UTC, nikic commented on llvm/lib/Transforms/InstCombine/InstCombineMulDivRem.cpp
> +        !KnownDivisor.getMaxValue().isMaxValue()) {
I don't think this case has test coverage?

2024-04-13 11:26 UTC, nikic commented
> Alive Proofs:
> 
> https://alive2.llvm.org/ce/z/zLMokH https://alive2.llvm.org/ce/z/xviNg3 https://alive2.llvm.org/ce/z/4rdGvf https://alive2.llvm.org/ce/z/LDqsa_

Can you please clean up the proofs? The second link looks completely unrelated, and the other ones look related but non-obvious -- I would expect something simple like sub on just the divisor plus either an assume on the dividend or divisor.

2024-04-15 07:02 UTC, nikic commented
Please, can you stop rebasing your pull requests all the time? You are generating notifications every time you do that, and as far as I can tell you don't actually do any changes in most cases? Or did something change in the last rebase?

2024-04-18 20:15 UTC, AtariDreams commented
> Please, can you stop rebasing your pull requests all the time? You are generating notifications every time you do that, and as far as I can tell you don't actually do any changes in most cases? Or did something change in the last rebase?

Edit the commit message.

2024-04-19 00:09 UTC, nikic commented
@AtariDreams PRs are merged by squashing, there is no need to edit commit messages. Only the pull request description matters.

2024-09-10 13:15 UTC, closed without merging