Fold `memref.dim` into `memref.expand_shape`
llvm/llvm-project pull request #88423
Opened 2024-04-11 18:41 UTC by bjacob

The lack of this folding pattern causes TypeConverter errors downstream (IREE) as `memref.dim` on `memref.expand_shape` cause non-1D memrefs to survive after we expect them to have been flattened.

I this code is mostly copied from the corresponding TensorOps.cpp code, performing the corresponding folding of `tensor.dim`. The difference is that that code used a `AffineApplyOp` and we can't do that here, because that could create a dependency of MemRefDialect on AffineDialect, which would be circular as AffineDialect depends on MemRefDialect.

For the same reason, this PR only folds into `expand_shape` and not `collapse_shape`. Sorry about the dissymetry, it's because the folding code for `collapse_shape` made more involved use of AffineDialect so would have been more work to reimplement without AffineDialect, and for my own immediate purposes, `expand_shape` is enough.

2024-04-11 19:39 UTC, MaheshRavishankar commented
Actually I am really surprised that the `memref.expand/collapse_shape` and the `tensor.expand/collapse_shape`  ops do not implement the [`ReifyRankedShapedTypeOpInterface`](https://github.com/llvm/llvm-project/blob/5d6d8dcd292e0a107b11d378932eee9c2f9ccfc7/mlir/include/mlir/Interfaces/InferTypeOpInterface.td#L344) . They really should be and dim folding shouldnt be part of the canonicalization. If you make the operation implement the interface you can then just add the [`memref::populateResolveRankedShapedTypeResultDimsPatterns`](https://github.com/llvm/llvm-project/blob/5d6d8dcd292e0a107b11d378932eee9c2f9ccfc7/mlir/lib/Dialect/MemRef/Transforms/ResolveShapedTypeResultDims.cpp#L127) wherever you need to fold the dims away.

If you want a separate pass you can just run `resolve-ranked-shaped-type-result-dims` pass to run the patterns as a separate pass.

2024-04-11 19:40 UTC, MaheshRavishankar requested changes
This shouldnt be a canonicalization and should be implemented through using the interface. See other comment for details.

2024-04-11 20:02 UTC, joker-eph commented
> This shouldnt be a canonicalization 

Can you expand why?

2024-04-12 16:06 UTC, bjacob commented
I can see how that makes sense. It means that for each such op, we just teach the compiler about computing its result shapes (by implementing `reifyResultShapes`) and it figures out how to do things such as folding `dim` ops, without the need for handwritten pattern rewriter code.

I should have the patch for `memref.expand_shape` today. But it seems that this treatment will be needed in more places, and I'm not sure I can commit to take care of them.

2024-04-17 17:50 UTC, bjacob commented
Superseded by #89111.

2024-04-17 17:50 UTC, closed without merging