[mlir][memref] Fold subview into nd-tensor descriptor
llvm/llvm-project pull request #88698
Opened 2024-04-15 08:30 UTC by adam-smnk

2024-04-15 08:35 UTC, adam-smnk commented
FYI @chencha3

2024-04-15 09:59 UTC, ftynse requested changes

2024-04-15 10:31 UTC, adam-smnk commented on mlir/lib/Dialect/MemRef/Transforms/FoldMemRefAliasOps.cpp
> +#include "mlir/Dialect/XeGPU/IR/XeGPU.h"
Fair enough. It looked like a common place to gather these folders given that NVGPU is also present here.

2024-04-15 13:05 UTC, adam-smnk commented
To be moved into a separate XeGPU transform pass.

2024-04-15 13:05 UTC, closed without merging

2024-04-16 15:43 UTC, chencha3 reviewed
Thanks @adam-smnk, LGTM.