[Libomptarget] Rework Record & Replay to be a plugin member
llvm/llvm-project pull request #88928
Opened 2024-04-16 16:35 UTC by jhuber6

Summary:
Previously, the R&R support was global state initialized by a global
constructor. This is bad because it prevents us from adequately
constraining the lifetime of the library. Additionally, we want to
minimize the amount of global state floating around.

This patch moves the R&R support into a plugin member like everything
else. This means there will be multiple copies of the R&R implementation
floating around, but this was already the case given the fact that we
currently handle everything with dynamic libraries.

2024-04-16 16:52 UTC, koparasy requested changes
Overall it LGTM. Some minor comments.

2024-04-16 16:52 UTC, koparasy commented on openmp/libomptarget/plugins-nextgen/common/CMakeLists.txt
> +target_compile_options(PluginCommon PUBLIC ${offload_compile_flags} -g -O0)
Do we always want O0 and debug?

2024-04-16 16:52 UTC, koparasy commented on openmp/libomptarget/plugins-nextgen/common/include/PluginInterface.h
> +  /// Get the RPC server running on this device.
Fix the comment: Get the RecordReplay instance?

2024-04-16 16:53 UTC, jhuber6 commented on openmp/libomptarget/plugins-nextgen/common/CMakeLists.txt
> +target_compile_options(PluginCommon PUBLIC ${offload_compile_flags} -g -O0)
Debugging, forgot about it.

2024-04-16 17:41 UTC, ggeorgakoudis requested changes
LGTM, one comment

2024-04-16 17:41 UTC, ggeorgakoudis commented on openmp/libomptarget/plugins-nextgen/common/include/PluginInterface.h
> +    assert(RPCServer && "R&R not initialized");
assert RecordReplay?

2024-04-16 18:10 UTC, jhuber6 commented on openmp/libomptarget/plugins-nextgen/common/include/PluginInterface.h
> +    assert(RPCServer && "R&R not initialized");
Done, lots of copy and paste mistakes.

2024-04-16 18:12 UTC, ggeorgakoudis approved these changes

2024-04-16 19:19 UTC, merged

2024-04-17 06:53 UTC, jplehr commented
This apparently broke all our buildbots, example: https://lab.llvm.org/buildbot/#/builders/193/builds/50201