[BOLT][NFC] Store FILE symbols in a vector
llvm/llvm-project pull request #89088
Opened 2024-04-17 15:24 UTC by aaupov

Replace a map from local symbol to associated file name with a vector of
symbol index + StringRef for FILE symbols only. This cuts down on memory
needed to resolve local file name.

Test Plan: NFC

2024-04-17 20:15 UTC, dcci requested changes
What is the tradeoff here? Did we try on large binaries? It looks like you're trading `O(1)`'ish access for potentially `O(N)`. Can this ever be a problem?

2024-04-17 21:36 UTC, aaupov commented
> What is the tradeoff here? Did we try on large binaries? It looks like you're trading `O(1)`'ish access for potentially `O(N)`. Can this ever be a problem?

The tradeoff is:
- storing a large unordered map Symbol (16b) -> FileName (16b) for _each_ _local_ symbol with set FileName, where we get FileName in O(1) for each local _function_ symbol (i.e. now we store strictly more than needed),
- vs a vector of just FILE symbol data (8b), where we get FileName in O(log FileSyms) * cost of FileSym->getName for each function symbol.

For reference, in one of our medium-sized test binaries we have:
- 6020 local symbols,
- 5841 local function symbols,
- 141 file symbols.

So space savings are quite significant, we gain storage locality, and an extra per-symbol cost is reasonable.

If your concern is about Symbol->getName cost, we can memorize FileName and store pairs of symbol data (8b) and StringRef (16b) instead, reducing the per-symbol cost to just O(log FileSyms).

The switch to storing FILE symbols is a prerequisite for using the symbol table information for split fragment matching.

2024-04-17 21:40 UTC, dcci commented
> For reference, in one of our medium-sized test binaries we have:

Can we try on large binaries and try to have an upper bound on the size? I am not against this I just want to make sure we don't regress time dramatically.

> The switch to storing FILE symbols is a prerequisite for using the symbol table information for split fragment matching

Thanks for the context. Feel free to add more motivation to your NFC patches/commits, in particular if they're in preparation for something bigger.

2024-04-17 22:10 UTC, aaupov commented
> > For reference, in one of our medium-sized test binaries we have:
> 
> Can we try on large binaries and try to have an upper bound on the size? I am not against this I just want to make sure we don't regress time dramatically.

For one large prod binary, we have the following:
- 2356369 local symbols,
- 1327085 local function symbols,
- 27784 file symbols.

The space tradeoff becomes:
- unordered map: 16b key + 16b value + 8b hash, times # of local symbols => ~90Mb of logical storage
- vector: 8b Symbol data + assuming the memorization of FileName (8b) => ~0.5Mb of logical storage

> 
> > The switch to storing FILE symbols is a prerequisite for using the symbol table information for split fragment matching
> 
> Thanks for the context. Feel free to add more motivation to your NFC patches/commits, in particular if they're in preparation for something bigger.

Done.

2024-04-17 22:25 UTC, aaupov commented
> > > > For reference, in one of our medium-sized test binaries we have:
> > > 
> > > 
> > > Can we try on large binaries and try to have an upper bound on the size? I am not against this I just want to make sure we don't regress time dramatically.
> > 
> > 
> > For one large prod binary, we have the following:
> > 
> > * 2356369 local symbols,
> > * 1327085 local function symbols,
> > * 27784 file symbols.
> 
> What's the BOLT processing time before/after the change? 100MB is a significant amount but how does it compare with BOLT's peak memory usage?

It's a drop in the bucket, processing time- and peak memory- wise (~1/1000). Treat this diff as a data structure change to facilitate new use case (which will bring memory consumption back up).

2024-04-17 22:38 UTC, dcci commented
Would be useful, before merging, to see the whole set of patches. The difficulty with tiny NFC patches is that they result in larger picture to be lost, sometimes.

2024-05-06 04:14 UTC, aaupov commented
For chromium 5735 binary with ~1.2M symbols, discover file objects wall time:
- before: 12.6422s
- after: 12.0297s

2025-06-20 17:34 UTC, rafaelauler approved these changes
lgtm

2025-06-20 21:29 UTC, merged