[MLIR] Add single definition multiple regions for mem2reg
llvm/llvm-project pull request #89107
Opened 2024-04-17 17:31 UTC by fanfuqiang

The mem2reg restricts all cases that can be processed to stay at the same mlir region now, this is because the iterated dominant frontier calculate can not support multiple regions currently.

This commit adds simple case support for the existing mem2reg pass, that when we have a single definition and multiple uses, the definition and uses stay at multiple regions, and the definition dominates all the uses. so we can forward the value to all the uses directly.

2024-04-18 15:06 UTC, Dinistro requested changes
Thanks for your contribution. As you correctly observed, Mem2Reg does currently not support structured control flow, due to a lack of proper dominance analysis for CFGs with regions + interfaces to extend region holding operations with new values that need to flow into all successor regions. The latter would be required to promote values properly and let their results flow through registers (SSA values) instead of memory.

Unfortunately, this PR does only solve one specific special case, which is not something we strive for. If we want to support CFGs with regions, we need a principled approach that will require substantial extension to the existing algorithm.

May I ask what your use case for this specific special case is?

2024-04-18 15:07 UTC, Moxinilian commented
Hey! Thanks for the contribution. I'm worried that this adds a lot of ad hoc infrastructure for an extremely specific case. Do you think this could be made more general?

2024-04-18 15:11 UTC, Moxinilian requested changes
Hey! Thanks for the contribution. I'm worried that this adds a lot of ad hoc infrastructure for an extremely specific case. Do you think this could be made more general?

2024-04-18 15:14 UTC, fanfuqiang commented on mlir/test/Dialect/Transform/mem2reg-hybird-dialects.mlir
> +// The definition doesn't dominate all uses, mem2reg fails.
I mean the store.

2024-04-18 15:31 UTC, Moxinilian commented
In that case I think the mem2reg is just not ready for your use case unfortunately. There is a strong desire to support region-based control flow in mem2reg, but I think it requires being done at once to avoid having the infrastructure grow to organically.

2024-04-18 15:33 UTC, fanfuqiang commented
> Hey! Thanks for the contribution. I'm worried that this adds a lot of ad hoc infrastructure for an extremely specific case. Do you think this could be made more general?

To make mem2reg more general must need a completely dominant frontier construction support the multiple regions.
I am not sure if this work is useful or not. For me, this simple patch has done lots of work.

2024-04-18 15:39 UTC, fanfuqiang commented
> In that case I think the mem2reg infra is just not ready for your use case unfortunately. There is a strong desire to support region-based control flow in mem2reg, but I think it requires being done at once to avoid having the infrastructure grow too organically.

So dominate frontier support multiple regions in the mlir function is needed?
Does someone working for this already?

2024-04-18 16:01 UTC, Moxinilian commented
Yeah, I think this needs a general way to express dominance between values across regions. I think [this talk](https://www.youtube.com/watch?v=VJORFvHJKWE) summarizes pretty well why this is difficult in regions.

I am not aware of anyone working actively on this, but an RFC is always welcome if you have an idea on how to model this properly. I think it is a fun challenge, albeit fairly difficult. I think loops in particular require to be extra careful.

2024-04-18 16:03 UTC, joker-eph commented
> Yeah, I think this needs a general way to express dominance between values across regions. I think [this talk](https://www.youtube.com/watch?v=VJORFvHJKWE) summarizes pretty well why this is difficult in regions.

As far as I know, the talk you refer only touches on asynchronously executed region and also I believe it misuses "dominance" for "liveness".

2024-04-18 16:18 UTC, Mogball commented
In general, the upstream IR model lacks the granularity to say what regions are contiguous (executed immediately) or executed deferred.

2024-04-19 12:38 UTC, Dinistro commented
> Right. I think for mem2reg liveness and dominance are somewhat similar, at least in the scope of what this mem2reg infrastructure was designed for. If we successfully model dominance in regions, this should provide enough information to compute a useful amount of variable tracking for mem2reg.

While this is a non-trivial task, it might be possible to somehow generalize dominance for this. Unfortunately, one will also require to design interfaces that allow adding results to regions in some kind of generic way. I do not have any concrete idea about how to achieve this goal at the moment, so such a Mem2Reg generalization is not something we will see in due time.

@fanfuqiang are you lowering back to LLVM dialect at some point? If so, can you not just apply mem2reg on that level for now?

2024-04-19 13:54 UTC, fanfuqiang commented
> > Right. I think for mem2reg liveness and dominance are somewhat similar, at least in the scope of what this mem2reg infrastructure was designed for. If we successfully model dominance in regions, this should provide enough information to compute a useful amount of variable tracking for mem2reg.
> 
> While this is a non-trivial task, it might be possible to somehow generalize dominance for this. Unfortunately, one will also require to design interfaces that allow adding results to regions in some kind of generic way. I do not have any concrete idea about how to achieve this goal at the moment, so such a Mem2Reg generalization is not something we will see in due time.
> 
> @fanfuqiang are you lowering back to LLVM dialect at some point? If so, can you not just apply mem2reg on that level for now?

Some hybrid dialects are the end for my job, not pure LLVM dialect.
Thanks for all the reviews, I will try to think about the generalized ssa construction.

2024-04-20 00:55 UTC, joker-eph commented
> If we successfully model dominance in regions, 

What does this mean exactly? We're not talking about SSA dominance here, are we? (the MLIR verifier enforces dominance rules already, which AFAIK are well defined with regions)

2024-04-20 08:52 UTC, Moxinilian commented
> What does this mean exactly? We're not talking about SSA dominance here, are we? (the MLIR verifier enforces dominance rules already, which AFAIK are well defined with regions)

This is about dominance in the sense "op A dominates op B" if and only if "for all control-flow paths reaching op B, this path goes through op A". The MLIR verifier enforces dominance rule at a sort of syntactic level, but does not take into account actual control-flow.

2024-04-20 12:24 UTC, joker-eph commented
> The MLIR verifier enforces dominance rule at a sort of syntactic level, but does not take into account actual control-flow (for example in deferred execution of regions). 

This isn’t syntactic, this is actual proper dominance.
I mentioned before that “async” is Theo Bly property that requires some care, but that’s not a dominance problem: an operation with a region does not imply that the region is immediately executed. From a dominance point of view the execution model is that the operands (and all implicitly captured values) are immediately evaluated (and pointers possibly escaped), and the result values are produced when the operation completes (which does not mean the region body was executed: for example the async dialect returns async values).

> By modelling we mean being able to assert (or not) this property on any given pair of operations, for which there currently is no sufficient interface for mem2reg purposes. Is that what you are talking about?

Let’s take all the cases:

- a value is defined by an operation and used as operand by an operation in the same region. The rules of dominance are well defined (this is the base case)
- A value is defined by an operation but used in a region nested beneath another operation in the same region. This is an implicit capture, and it actually has the same semantics as the case above: it can be considered “captured” as an implicit operand by the operation in the same region as where it is defined (point of evaluation), as if the operation was isolated. Without more information you can’t infer anything about the region execution here.
- there are no other cases that would pass the verifier.

> Come to think of it, it may just be sufficient to have an interface that says the regions of an operation are not deferred, which would cover a lot of cases useful to mem2reg.

This is what I pointed before: the talk you referred to is mixing up the async problem for a dominance one.

But in general what can mem2reg do without the RegionBranchOpInterface anyway? And in this case don’t you already know there is no asynchronicity involved?

2024-04-20 14:10 UTC, Moxinilian commented
> A value is defined by an operation but used in a region nested beneath another operation in the same region. This is an implicit capture, and it actually has the same semantics as the case above: it can be considered “captured” as an implicit operand by the operation in the same region as where it is defined (point of evaluation), as if the operation was isolated. Without more information you can’t infer anything about the region execution here.

Here we are modelling effects that are not embedded in the value semantics, typically `load %x` and `store %x`. The definition of dominance you mention is not general enough to model this. There is no capture when a store happens outside of a region and a load inside the region (except for the pointer of course but that does not model what we are after), because the value can still be modified after the region declaration:

```mlir
store %ptr
%promise = async {
    load %ptr
}
store %ptr
evaluate %promise
```

The value pointed at by the pointer has not been captured and cannot be, precisely because the region does not own it.

When we say dominance we really do mean "op A dominates op B" if and only if "for all control-flow paths reaching op B, this path goes through op A", in the very academic sense, which depends on execution properties such as deferred execution. In the example above, we would say that the second store dominates the load in the region. Perhaps this is not the same semantics as what has been used in MLIR for the word "dominance", but at least this is what we need. I think we are only arguing about terms here.

The reason people have been saying that the notion of dominance verified in the MLIR verifiers is more "syntactic" is because it matches the natural dominance observed in the syntax without modelling this more precise, other relationship also called dominance. This other relationship (or a safe approximation of it) is the one we need in mem2reg.

2024-04-20 22:18 UTC, joker-eph commented
> Here we are modelling effects that are not embedded in the value semantics, typically load %x and store %x.

I understand that quite well, however:

> The definition of dominance you mention is not general enough to model this. 

Can you please refer to the existing literature and provide pointer to any definition of what you want to discuss? 
I can't follow you because it seems to me that you're trying to mix-and-match things that don't fit together: I'm not the one who brought dominance in the discussion here!!


> There is no capture when a store happens outside of a region and a load inside the region (except for the pointer of course but that does not model what we are after),

I believe the pointer is exactly what we're after here actually. The region capturing the pointer means the pointer escape, and that implies that without more information you can't know when the load happens (the "pointer escaping" is what makes it possible that the region can be executed concurrently for example).


> The value pointed at by the pointer has not been captured and cannot be

Sure... but I don't quite see how it relates to the discussion about the dominance?
The memory state is something that changes potentially with every single operation, I really can't follow how you're trying to tie in the memory state to dominance!

> When we say dominance we really do mean "op A dominates op B" if and only if "for all control-flow paths reaching op B, this path goes through op A", in the very academic sense, which depends on execution properties such as deferred execution. 

This is exactly the definition I have been using (I mean: I sent the link above in the discussion...).
This is the basis under which I explained above how the semantics works in MLIR.

> In the example above, we would say that the second store dominates the load in the region

I don't think so: it highly depends on the semantics of async here. There is no dominance if there is concurrent execution here I believe.

And back to MLIR semantics, in your example:

- the first store properly dominates the the `async` op, and the region nested within the `async` op.
- the async op properly dominates the second store.
- the only dominance property associated with the region nested within the async op is that all operations dominating the async are also dominating all the operations here. There is no dominance relationship between the load and the second store. As I mentioned before, an interface like RegionOpInterface **can** provide this extra information, for example for something like `scf.execute_region`, but without interfaces you just can't infer anything (and "asynchronicity" just does not allow to infer anything in terms of dominance).


>  Perhaps this is not the same semantics as what has been used in MLIR for the word "dominance", but at least this is what we need. I think we are only arguing about terms here.

Terminology is key though: everything I've done here is insisting that you're a bit more consistent with it (also because I had concerned with the angle presented by the talk last year on this point).

2024-04-21 07:18 UTC, Moxinilian commented
> I don't think so: it highly depends on the semantics of async here.

I think this is the core of the problem here: we do not agree on what counts as a control-flow path. Let’s just agree to disagree.

2025-04-10 12:09 UTC, closed without merging