[RISCV][TTI] Scale the cost of ArithmeticInstr with LMUL
llvm/llvm-project pull request #89170
Opened 2024-04-18 05:44 UTC by arcbbb

2024-04-22 16:27 UTC, preames requested changes
The code you're replacing is already linear in LMUL; your test changes are caused by adding new instructions to the switch.

Please update your review description to match and to justify the change,.

2024-04-22 18:23 UTC, topperc commented on llvm/lib/Target/RISCV/RISCVTargetTransformInfo.cpp
>    case ISD::FMUL:
It's weird that FMUL uses VFADD.

2024-04-22 18:43 UTC, topperc commented
What's the history of why the cost model tests use `-riscv-v-fixed-length-vector-lmul-max=1`? That prevents fixed vector tests from covering LMULs larger than 1.

2024-04-24 07:14 UTC, lukel97 commented
> What's the history of why the cost model tests use `-riscv-v-fixed-length-vector-lmul-max=1`? That prevents fixed vector tests from covering LMULs larger than 1.

First commit adding vector cost model tests I can find is https://reviews.llvm.org/D99142, presumably back when fixed vector support was new

2024-04-29 23:56 UTC, arcbbb commented on llvm/lib/Target/RISCV/RISCVTargetTransformInfo.cpp
> +  // Assuming instructions falling through the switch-cases have the same cost
Exactly! That captures what I was trying to convey.  Thank you!

2024-05-10 08:17 UTC, arcbbb commented
ping

2024-05-10 16:41 UTC, topperc approved these changes
LGTM

2024-05-13 01:47 UTC, merged