[libc++] Don't commit libcxx.imp
llvm/llvm-project pull request #89391
Opened 2024-04-19 14:45 UTC by ldionne

We can instead generate it on-the-fly when we install the headers. This reduces the amount of boilerplate we have to re-generate whenever we add, remove or relocate header files.

Fixes #88529

2024-04-19 16:53 UTC, mordante requested changes
Thanks for the cleanup. I like to have a short look after it passes the CI.

2024-04-19 16:53 UTC, mordante commented on libcxx/utils/CMakeLists.txt
> -            libcxx-generate-iwyu-mapping
Can you also fix the tab I sneaked in on the line above?

2024-04-19 16:53 UTC, mordante commented on libcxx/include/CMakeLists.txt
> +list(APPEND _all_includes "${LIBCXX_GENERATED_INCLUDE_DIR}/libcxx.imp")
It looks like this breaks the CI.

2024-04-19 18:04 UTC, mordante approved these changes
I see some CI's passing, so I'm happy. LGTM!

2024-04-22 12:45 UTC, merged

2024-04-24 14:18 UTC, nico commented
Hello, is there any way this could be reconsidered? We have a bot that auto-updates libc++ in Chromium, and that bot only watches for revisions and produces CLs without having any local checkout state. This change here makes it impossible for that bot to continue working in its current state.

("Can't you just change the bot?" Not easily. It's a general dependency-updating system that we use for many dependencies, and not having to have local checkouts is a design decision that the team setting up that system made.)

If it's a big pain to keep upstream, we'll find some way I suppose, but I figured asking first is easy, and if it isn't painful to keep this upstream…

2024-04-24 15:26 UTC, ldionne commented
I am not sure I understand what's problematic about this specific patch w.r.t. that bot, can you explain?

We generate several files in the installation directory (e.g. `__config_site` and `__assertion_handler`) already, how is this one different?

2024-04-25 15:34 UTC, nico commented
We don't use any of the other generated files either. We have fixed `__config_site` and `__assertion_handler` files in our tree. They never (or rarely) change, and if they do, something tends to break loudly if we don't update our version. This file here changes more often, and the error case is that IWYU silently adds includes of internal headers.

2024-04-25 16:30 UTC, ldionne commented
So, are you basically asking whether we would be comfortable with not generating files into the install directory without having them checked in somewhere, in the general case?

Sorry, I'm genuinely trying to understand what your request entails before I can really form an opinion.

2024-07-12 14:15 UTC, nico commented
> So, are you basically asking whether we would be comfortable with not generating files into the install directory without having them checked in somewhere, in the general case?

Yes, except I'm not asking about the general case, but about this specific case :)