Add more cases for UDIV, SDIV, SRA, and SRL
llvm/llvm-project pull request #89522
Opened 2024-04-21 00:09 UTC by AtariDreams

2024-04-21 02:26 UTC, topperc commented on llvm/lib/CodeGen/SelectionDAG/SelectionDAG.cpp
> +    if (KnownBits::uge(ValKnown, KnownBits::lshr(One, Shift)))
KnownBits::uge returns a std::optional. This is only checking that the optional has a value. Not what the value is.

2024-04-21 02:28 UTC, topperc commented on llvm/lib/CodeGen/SelectionDAG/SelectionDAG.cpp
> +    if (KnownBits::uge(ValKnown, KnownBits::lshr(One, Shift)))
KnownBits::uge returns a std::optional. This is only checking that the optional has a value, not what the value is.

2024-04-21 10:41 UTC, RKSimon reviewed
Please can you compare with the ValueTracking.cpp implementations? You'd be better off adding new handling in there first (and then updating SelectionDAG to match) as we have much better fuzz testing in the middle end for this kind of thing than in the backend.

2024-06-09 20:46 UTC, arsenm commented
Title needs to say cases for what

2024-06-10 08:29 UTC, jayfoad requested changes

2024-06-10 08:29 UTC, jayfoad commented on llvm/lib/CodeGen/SelectionDAG/SelectionDAG.cpp
> +    std::optional<bool> uge = KnownBits::uge(Op0, Op1);
Variable names should be capitalized

2024-06-10 08:29 UTC, jayfoad commented on llvm/lib/CodeGen/SelectionDAG/SelectionDAG.cpp
> +      return true;
No! -1 sdiv 2 is zero!

2024-06-10 08:29 UTC, jayfoad commented on llvm/lib/CodeGen/SelectionDAG/SelectionDAG.cpp
> +      return true;
No! 1 sdiv -2 is zero!

2024-06-10 08:35 UTC, jayfoad commented on llvm/lib/CodeGen/SelectionDAG/SelectionDAG.cpp
> +      if (XKnown.isNonZero() || isKnownNeverZero(Op.getOperand(0), Depth + 1))
Suggest removing `XKnown.isNonZero() || ` here since it will be handled by the general case below (and the general case is not slow).

2024-06-10 08:37 UTC, jayfoad commented on llvm/lib/Support/KnownBits.cpp
> +    Known.makeGE(APInt(BitWidth, 1));
Split KnownBits changes into a separate patch, with a unit test that fails without this extra code.

2024-06-10 10:39 UTC, RKSimon reviewed
Maybe split this into separate PRs for each opcode change?

2024-08-16 18:36 UTC, arsenm reviewed
It would be much easier to review this if only one operation was covered per PR

2024-08-16 18:38 UTC, arsenm commented on llvm/lib/CodeGen/SelectionDAG/SelectionDAG.cpp
> +    Op1 = Op1.abs(/*IntMinIsPoison*/ false);
```suggestion
    Op0 = Op0.abs(/*IntMinIsPoison=*/ false);
    Op1 = Op1.abs(/*IntMinIsPoison=*/ false);
```

2024-08-16 18:38 UTC, arsenm commented on llvm/lib/CodeGen/SelectionDAG/SelectionDAG.cpp
> +        return true;
Can you just check isSignBitSet then instead of intersect with Mask?

2025-03-06 02:27 UTC, closed without merging