[libcxx] Avoid __cxa_atexit with -O0
llvm/llvm-project pull request #89882
Opened 2024-04-24 07:03 UTC by vitalybuka

Empty destructor will register __cxa_atexit.
https://gcc.godbolt.org/z/hce587b65

We can not remove the destructor with union where
_Tp can have non-trivial destructor.

But we can remove destructor if we use in-place
new instead of union.
https://gcc.godbolt.org/z/Yqxx57eEd - empty even with -O0.

2024-04-24 08:56 UTC, frederick-vs-ja commented on libcxx/include/__utility/no_destroy.h
> +  }
The `constexpr` becomes meaningless after the current changes, even after [P2747](https://wg21.link/p2747) which will be adopted for C++26 soon. Note that the always-meaningless `constexpr` on a function makes the program ill-formed, no diagnostic required before C++23.

2024-04-24 08:56 UTC, frederick-vs-ja commented on libcxx/include/__utility/no_destroy.h
> +  }
Likewise, `reinterpret_cast` makes the `constexpr` meaningless.

2024-04-24 09:07 UTC, frederick-vs-ja reviewed
I guess we should remove some `_LIBCPP_CONSTEXPR`/`_LIBCPP_CONSTEXPR_SINCE_CXX14`.

2024-04-24 16:55 UTC, vitalybuka commented on libcxx/include/__utility/no_destroy.h
> +  _LIBCPP_CONSTEXPR_SINCE_CXX14 _LIBCPP_HIDE_FROM_ABI explicit __no_destroy(__uninitialized_tag) {}
done and reordered to have _LIBCPP_HIDE_FROM_ABI first for better text alignment and consistency with the rest of libcxx

2024-04-25 13:47 UTC, ldionne requested changes

2024-04-25 18:06 UTC, vitalybuka commented on libcxx/test/libcxx/utilities/no_destroy.pass.cpp
> +#include "test_macros.h"
now it's used

2024-04-26 14:16 UTC, ldionne approved these changes

2024-04-27 05:27 UTC, merged