[Clang] Fix LibTooling doc
llvm/llvm-project pull request #90441
Opened 2024-04-29 08:43 UTC by maxmosk

Replace CommonOptionsParser ctor by factory method ::create.

Found on page https://clang.llvm.org/docs/LibTooling.html

2024-04-29 09:23 UTC, Sirraide requested changes
Thanks for improving our documentation!

There’s some error handling missing here. The `CommonOptionsParser` constructor would previously just exit, but that is no longer the case here, so we actually need to handle errors now.

2024-04-29 09:23 UTC, Sirraide commented on clang/docs/LibTooling.rst
> +    auto OptionsParser = CommonOptionsParser::create(argc, argv, MyToolCategory);
Also, `->` needs to be replaced with `.` again below.

2024-04-29 09:23 UTC, Sirraide commented on clang/docs/LibTooling.rst
> +    auto OptionsParser = CommonOptionsParser::create(argc, argv, MyToolCategory);
As above

2024-04-29 09:23 UTC, Sirraide commented on clang/include/clang/Tooling/CommonOptionsParser.h
> +///   auto OptionsParser = CommonOptionsParser::create(argc, argv, MyToolCategory);
And here too

2024-04-29 09:36 UTC, Sirraide commented
I also just noticed that there already is a pr for this: #70427.

2024-04-29 09:44 UTC, maxmosk commented
> I also just noticed that there already is a pr for this: #70427.

This PR wasn't approved and doc is still not fixed :(
What to do with this PR?

2024-04-29 09:50 UTC, Sirraide commented
> This PR wasn't approved and doc is still not fixed :( What to do with this PR?

It somehow just went unnoticed all this time, unfortunately. I’ll approve the other pr since it seems to do the same thing that we’re also doing somewhere else in our documentation, and it’s pretty much what I suggested here anyway.

The comment in `clang/Tooling/CommonOptionsParser.h` still needs to be updated, which the other pr doesn’t do; you can still do that if you’d like. Sorry about the entire confusion here; this is something that shouldn’t normally happen...

2024-04-30 09:57 UTC, maxmosk commented
@Sirraide updated with header doc fix, please review

2024-04-30 12:48 UTC, Sirraide approved these changes
LGTM seeing as this matches what’s already in the documentation.

2024-04-30 12:56 UTC, Sirraide commented
Right, what `clang-format` is suggesting here is a bit bizzare; please reformat the comment manually so every line fits within the 80 column limit.

2024-04-30 13:06 UTC, Sirraide approved these changes

2024-04-30 13:07 UTC, merged