Add isTrivial() and isTriviallyCopyable() AST matchers
llvm/llvm-project pull request #90634
Opened 2024-04-30 17:39 UTC by higher-performance

There are currently no AST matchers for the equivalent of `std::is_trivial`, `std::is_trivially_default_constructible`, `std::is_trivially_copyable`, and the like.

This pull request adds matchers to check if records and their member functions are trivial.

It does _not_ attempt to handle other trivial entities (such as pointers).

2024-09-30 16:02 UTC, ilya-biryukov commented
I remember back in the day that adding new matchers was a problem because it grew the size of the files beyond some supported compiler's limit.

Could @AaronBallman or someone else knowledgable about this(cc @kadircet) take a look and confirm adding matchers is fine now?

2024-09-30 16:02 UTC, ilya-biryukov requested changes

2024-09-30 16:02 UTC, ilya-biryukov commented on clang/include/clang/ASTMatchers/ASTMatchers.h
> +/// Matches trivial methods and types.
I do not think is actually matches `types`, but rather `classes` or `CXXRecordDecl`.
And the question is: should it?

I believe we could extend this matcher to also work on types and type locs.
Do you see any downsides to that? (same for the other matcher)

2024-10-10 18:52 UTC, AaronBallman commented
> I remember back in the day that adding new matchers was a problem because it grew the size of the files beyond some supported compiler's limit.
> 
> Could @AaronBallman or someone else knowledgable about this(cc @kadircet) take a look and confirm adding matchers is fine now?

We generally only add matchers when there's a need for them to reside in-tree (e.g., a few clang-tidy checks will use them); otherwise we recommend that folks define their own custom matchers. The reason is mostly because compile time overhead for compiling ASTMatchers.h is... huge... due to the template instantiations, so we usually want there to be a need before adding any.

Is there a planned need here?

2024-10-11 11:59 UTC, AaronBallman commented
Thanks for the details! I'd say let's hold off on adding these matchers; if you have a check that needs them, then you could look through clang-tidy to see if other checks have also added a local matcher for the same thing, and if there's two or more matchers needing it, then we'll add it as a global matcher.

As for the check itself, that looks like an interesting one!

2024-10-12 08:28 UTC, philnik777 commented
While the libc++ checks are in the same tree as clang-tidy itself we (libc++) don't actually consider them in-tree, since they are compiled as a plugin against a clang-tidy that's already installed on the system.

2024-10-15 20:50 UTC, closed without merging