[BugFix] : Crash in getPackOpResultTypeShape for tensor.pack/unpack ops.
llvm/llvm-project pull request #90641
Opened 2024-04-30 18:05 UTC by sahas3

Windows build of `mlir` with Visual Studio (19.36.32538 for x64) using with the following command:

`cmake.exe -GNinja -DCMAKE_BUILD_TYPE=Release -DLLVM_ENABLE_PROJECTS=mlir -DLLVM_ENABLE_EH=ON -DLLVM_ENABLE_RTTI=1 -DLLVM_TARGETS_TO_BUILD=host llvm`

is leading to a crash when calling canonicalization on `tensor.pack`/`tensor.unpack` ops `mlir-opt --canonicalize input.mlir` where the `input.mlir` is as follows (this is taken from one of the filecheck tests for `tensor.pack`):

```
func.func @pack_unpack(%arg0: tensor<128x256xf32>) -> tensor<128x256xf32> {
          %pack_dest = tensor.empty() : tensor<8x16x8x32xf32>
          %unpack_dest = tensor.empty() : tensor<128x256xf32>
          %tp = tensor.pack %arg0 outer_dims_perm = [1, 0] inner_dims_pos = [0, 1] inner_tiles = [8, 32] into %pack_dest : tensor<128x256xf32> -> tensor<8x16x8x32xf32>
          %tup = tensor.unpack %tp outer_dims_perm = [1, 0] inner_dims_pos = [0, 1] inner_tiles = [8, 32] into %unpack_dest : tensor<8x16x8x32xf32> -> tensor<128x256xf32>
          return %tup : tensor<128x256xf32>
        }
```

The crash is seemingly coming from accessing `innerDimsPos` within `getPackOpResultTypeShape`. 

This crash is also causing the following tests to fail:

2024-05-02 00:15 UTC, MaheshRavishankar requested changes
Thanks for the fix. The issue is at the call site though. The `ArrayRef` indicates a "reference argument" so this seems to be an error in how the function is called. Do you have more information on that?

2024-05-02 13:18 UTC, sahas3 commented
> Thanks for the fix. The issue is at the call site though. The `ArrayRef` indicates a "reference argument" so this seems to be an error in how the function is called. Do you have more information on that?

Thanks for reviewing. 

TBH, this "fix" is a puzzle for me too since `ArrayRef` doesn't own the data. Debugging doesn't provide any information since the issue is only reproducible in `Release` build. `RelWithDebInfo` doesn't produce the crash either. 

The callgraph leading to the crash is: `PackOp::verify -> commonVerifierPackAndUnPackOp -> inferPackedType -> getPackOpResultTypeShape`. All the call-sites starting from `inferPackedType` pass `innerDimsPos` as `ArrayRef` as the getter itself returns it as `ArrayRef`. This seems to be because `innerDimsPos` is a `DenseI64ArrayAttr` which gets cast as `ArrayRef` when returned in the getters.

What I've tried unsuccessfully:
1. Convert the returned value from `getInnerDimsPos` to a `SmallVector` in `commonVerifierPackAndUnPackOp` and use that for all the subsequent calls. 
2. Call `inferPackedType` as the first function from `commonVerifierPackAndUnPackOp` (just to ensure that the memory for `innerDimsPos` doesn't get affected by any other call -- though nothing in that code seemed to be doing that)

2024-05-03 20:26 UTC, MaheshRavishankar commented
I am just waiting for either @joker-eph or @jpienaar to chime in. Overall I am OK with this. Maybe @ftynse has some insight here?

2024-05-09 23:04 UTC, sahas3 commented
> I am just waiting for either @joker-eph or @jpienaar to chime in. Overall I am OK with this. Maybe @ftynse has some insight here?

@joker-eph / @jpienaar / @ftynse do you have any thoughts on this PR? Thanks!

2024-05-09 23:39 UTC, MaheshRavishankar approved these changes
This is a legit fix. I am fine by it, but it is also hiding a problem

2024-05-13 22:18 UTC, merged

2024-05-17 12:17 UTC, ftynse commented
Yeah, nothing that is immediately visible to me either. Two default hypotheses are (1) the referenced object got moved after the reference was taken, (2) something messes up the lifetime extension rules so the underlying storage is rewritten.  I'd check if getting values directly from `packOrUnpack` instead of using cached arrayrefs here `RankedTensorType expectedPackedType = PackOp::inferPackedType(
      unpackedType, packOrUnPack.getStaticTiles(), innerDimsPos, outerDimPerm);` helps.

2024-05-17 12:43 UTC, ftynse commented
Another random thing could is to use `auto &&[index, value] : llvm::enumerate()` to preserve the info about references.