[llvm/Support] Make `llvm::sys::RWMutex` Lockable
llvm/llvm-project pull request #90667
Opened 2024-04-30 21:04 UTC by medismailben

This patch extends the `llvm::sys::RWMutex` class to fullfill the `Lockable` requirement to include attempted locking, by implementing a `bool try_lock` member function.

As the name suggests, this method will try to acquire to lock in a non-blocking fashion and release it immediately. If it managed to acquire the lock, returns `true`, otherwise returns `false`.

2024-04-30 21:51 UTC, bulbazord commented on llvm/lib/Support/RWMutex.cpp
> +  int errorcode = pthread_rwlock_tryrdlock(rwlock);
There's an inconsistency here. `RWMutexImpl` has `shared` variants of `lock` and `unlock` that are used for reading while the plain versions of `lock` and `unlock` are for writing. I think this needs to use `pthread_rwlock_trywrlock` and then you probably want to add `RWMutexImpl::try_lock_shared()`.

2024-05-01 19:23 UTC, bulbazord approved these changes
LGTM

2024-05-01 22:03 UTC, JDevlieghere requested changes
It looks like this is trying to implement something like `is_locked`. `try_lock` has fairly well defined semantics for `std::mutex` and `pthreads`. In both cases this acquires the lock if it succeeds. Our implementation shouldn't behave differently.

2024-05-01 22:25 UTC, JDevlieghere approved these changes
This LGTM!

2024-05-01 22:26 UTC, bulbazord approved these changes

2024-05-01 22:32 UTC, merged

2024-05-06 17:16 UTC, dwblaikie commented
as an aside - per the instructions here ( https://llvm.org/docs/GitHub.html#updating-pull-requests ) please don't force-push to pull request reviews, as it makes it difficult to trace back comments and discussion through the revisions of a patch (I think, especially, inline comments can get lost/hidden/hard to find when force pushing)

2024-05-06 18:10 UTC, medismailben commented
> as an aside - per the instructions here ( https://llvm.org/docs/GitHub.html#updating-pull-requests ) please don't force-push to pull request reviews, as it makes it difficult to trace back comments and discussion through the revisions of a patch (I think, especially, inline comments can get lost/hidden/hard to find when force pushing)

Sure! I'll keep that in mind next time.