[alpha.webkit.UncountedLocalVarsChecker] Don't warning on inlined functions
llvm/llvm-project pull request #90733
Opened 2024-05-01 14:30 UTC by mikhailramalho

As per the guidelines, trivial inline functions shouldn't be changed to adopt smart pointers.

2024-05-01 14:34 UTC, mikhailramalho commented
@rniwa we noticed quite a drop in the warnings when using this patch, but we understand that there is another approach to handle inline functions: to add the `SUPPRESS_UNCOUNTED_LOCAL` to local variables inside these functions, like it was done here: https://github.com/WebKit/WebKit/pull/27870/files#diff-33ee084014f64a3d61fecb03211318d0d48dfa8f5b4ef6f4364fc2ab0364f9ebL137

Please let me know what you think of these approaches. If you prefer the macro one, I can close this  PR and open another one.

2024-05-01 14:56 UTC, steakhal commented
In the LLVM project we expect functional changes to include tests demonstrating the motivational example, and to also serve as a regression test for the future.

2024-05-01 17:30 UTC, rniwa commented
> As per the guidelines, trivial inline functions shouldn't be changed to adopt smart pointers.

The triviality of a function is checked by `TrivialFunctionAnalysis`. We shouldn't assume every inline function as trivial. For example, an inline function could call a non-inline function which mutates the memory state.

2024-05-01 17:31 UTC, rniwa requested changes

2024-05-01 17:31 UTC, rniwa commented on clang/lib/StaticAnalyzer/Checkers/WebKit/UncountedLocalVarsChecker.cpp
> +      if (FD->isInlined())
I don't think we should do this.

2024-05-02 01:49 UTC, haoNoQ commented
@mikhailramalho long time no see!

I think @rniwa is right on this one. "Inline" is completely orthogonal to "safe". Fundamentally it only matters what the function _actually does_; it doesn't matter how it's defined or where or how the code is generated for it.

These checkers don't follow our usual paradigm of "false positives are bad". They're coding convention checkers that force WebKit to use smart pointers consistently, even if the compiler hasn't identified any specific memory leaks or use-after-free vulnerabilities to worry about. While it's still valuable to avoid emitting warnings when the code is "obviously safe", they probably wouldn't go for a very approximate reasoning such as "all inline functions are safe" . We do this sort of stuff quite often in the rest of the static analyzer where false positives are much more terrifying than false negatives. But here, WebKit people such as @rniwa have consensually accepted a potentially high "false positive" rate as long as this means getting close to _some real safety_.

So this whole "trivial function analysis" thing aggressively treats unknown functions as unsafe by default, and when it actually gets to see the body (which correlates quite a bit with being inline) it carefully inspects it and confirms that it's actually "trivial" enough to not screw memory management. If you turn it off for inline functions, that's pretty close to turning it off entirely. That's probably not what they're looking for. There has to be a more careful solution to the false positves you're seeing.

2024-05-02 14:39 UTC, mikhailramalho commented
Thanks for the feedback folks. I'll close the PR.

2024-05-02 14:39 UTC, closed without merging