[AArch64] Support preserve_none calling convention
llvm/llvm-project pull request #91046
Opened 2024-05-04 05:28 UTC by antangelo

Adds AArch64 support for the `preserve_none` calling convention. Registers X0-X17 and X19-X28 are caller save, and can be used to pass arguments. Delegates to AAPCS for all other registers.

Closes #87423

2024-05-04 08:23 UTC, pinskia commented
I don't think you can use x16 and x17 for argument passing due to them being reserved for PLTs and call veneers.

2024-05-04 23:33 UTC, brandtbucher commented
Aw, but that means we only have *twenty-six* registers for argument-passing... ;)

2024-05-05 04:43 UTC, antangelo commented
> I don't think you can use x16 and x17 for argument passing due to them being reserved for PLTs and call veneers. That is if the linker decides to create a branch island or if the function is called via a PLT, x16 and x17 will be clobbered on the call so arguments using that will also won't work.

Thanks for catching this, I've removed them from the argument passing list.

2024-05-05 16:08 UTC, pinskia commented on clang/include/clang/Basic/AttrDocs.td
> +  Registers X19-X28 and X0-X17 are used to pass function arguments.
Even though you removed X16/X17 you seemly forgot to update the documentation.

2024-05-08 22:56 UTC, weiguozhi requested changes

2024-05-08 22:56 UTC, weiguozhi commented on llvm/lib/Target/AArch64/AArch64CallingConvention.td
> +                                   X6, X7, X8, X9, X10, X11,
X8 is used to pass SRet parameter in AArch64_Common, so it can not be used as a general argument register.

2024-05-15 05:24 UTC, antangelo commented
Friendly ping

2024-05-15 16:35 UTC, weiguozhi reviewed
Looks good to me.
Please wait for AArch64 maintainer's approval.

2024-05-22 23:24 UTC, antangelo commented
Friendly ping

2024-05-30 13:20 UTC, antangelo commented
Friendly ping

2024-05-31 08:15 UTC, DanielKristofKiss approved these changes
Thanks for the PR, just NITS otherwise LGTM

2024-06-03 22:42 UTC, merged

2024-06-04 01:24 UTC, efriedma-quic commented
X19 is the base register; can we actually allocate arguments in it in general?  This seems hard to fix.

It looks like frame lowering assumes X9 is available; that's probably fixable, but the code needs to be reworked, I think.

X15 is used on Windows for stack allocation; I think you can use it in this context, but probably worth a test to verify the interaction works the way you want.  (And more generally, that this calling convention doesn't explode on Windows targets.)

What's the interaction between varargs and preserve_none?

2024-06-04 03:56 UTC, antangelo commented
Thank you for catching these.

> X19 is the base register; can we actually allocate arguments in it in general? This seems hard to fix.

I will remove X19 from the argument passing list. `ghccc` also uses X19 for argument passing, and I didn't run into issues while testing this PR, so I'm not sure under what conditions issues present for this but it makes sense to remove it regardless.

> It looks like frame lowering assumes X9 is available; that's probably fixable, but the code needs to be reworked, I think.

The function that allocates X9 as scratch has a fallback provision for when the basic block is not an entry block, where it checks for liveness before picking a scratch register if X9 is unavailable. I think we can modify this so that `preserve_none` functions always follow this path, and then X9 should be usable for argument passing.

> X15 is used on Windows for stack allocation; I think you can use it in this context, but probably worth a test to verify the interaction works the way you want. (And more generally, that this calling convention doesn't explode on Windows targets.)

It looks like X15 is clobbered so I don't think it will be usable on Windows. Do you think it should be excluded from argument passing only on Windows or always?

As an aside, it seems like I missed adding the calling convention to the Windows target in clang, so this is currently only reachable from IR directly.

> What's the interaction between varargs and preserve_none?

I don't believe there is a defined interaction between varargs and `preserve_none` as per the RFC, given that the primary use case is for tail calls (which don't support varargs) I imagine it's unlikely to be used outright. It does not seem to work correctly on either AArch64 with this implementation or the X86_64 reference implementation, so we should probably treat it as unsupported.

I will prepare a patch to address the above issues. Do you think this warrants a revert of this PR in the meantime?

2024-06-04 04:29 UTC, efriedma-quic commented
Since nothing should be using preserve_none on aarch64 yet, it's probably fine to just fix forward.

> I'm not sure under what conditions issues present for this

We only allocate a base pointer under restricted circumstances (primarily, functions with dynamic allocation), so maybe GHC never tripped over the issues.

> It looks like X15 is clobbered so I don't think it will be usable on Windows. Do you think it should be excluded from argument passing only on Windows or always?

You probably could make this work if you really wanted to: you can allocate small amounts of stack without __chkstk, which you could then use to spill X15.  Not sure if that's the right tradeoff here.

2024-06-04 08:41 UTC, diegorusso commented
We (CPython project) will use it for the new JIT. I'll be testing the current implementation and report back any issue. I don't think you need to revert the PR but please let me know when you create the new one to address the post-merge comments so I can test it again.

Thanks

2024-06-21 15:48 UTC, antangelo commented
I have posted the followup changes in PR #96259 . I have left out the frontend changes required for `preserve_none` to be usable from clang on Windows for a separate patch, since they will require some changes to mangling (which are also required for X86).