[clang-format] Add option to remove leading blank lines
llvm/llvm-project pull request #91221
Opened 2024-05-06 14:40 UTC by sstwcw

2024-05-06 14:41 UTC, sstwcw commented
Should I make dropping leading blank lines the default?

There are some tests verifying that files that start with newlines should still start with newlines after being formatted.  However, they seem to be there to prevent the newlines from moving to wrong places.

There is 303baf53b1 "skip empty lines and comments in the top of the code when inserting new headers".

```C++
  std::string Code = "\nint x;";
  std::string Expected = "\n#include \"fix.h\"\n"
                         "#include \"a.h\"\n"
                         "#include \"b.h\"\n"
                         "#include \"c.h\"\n"
                         "#include <list>\n"
                         "#include <vector>\n"
                         "int x;";
  tooling::Replacements Replaces = toReplacements(
      {createInsertion("#include \"a.h\""), createInsertion("#include \"c.h\""),
       createInsertion("#include \"b.h\""),
       createInsertion("#include <vector>"), createInsertion("#include <list>"),
       createInsertion("#include \"fix.h\"")});
  EXPECT_EQ(Expected, formatAndApply(Code, Replaces));
```

There is also a test for preserving the byte order mark.

```C++
  verifyFormat("\xef\xbb\xbf\n#include <iostream>");
```

2024-05-09 09:49 UTC, HazardyKnusperkeks approved these changes

2024-05-09 14:48 UTC, mydeveloperday approved these changes

2024-05-11 02:06 UTC, owenca commented
I think this is a good time to combine the `KeepEmptyLines...` options. For example:
```
KeepEmptyLines:
  AtStartOfBlock: true
  AtStartOfFile: false
  AtEndOfFile: true
```

2024-05-11 02:10 UTC, owenca commented
> Should I make dropping leading blank lines the default?

We should keep leading blank lines (up to `MaxEmptyLinesToKeep`) by default as before.

2024-05-11 02:11 UTC, owenca requested changes
See https://github.com/llvm/llvm-project/pull/91221#issuecomment-2105454428.

2024-05-30 07:56 UTC, owenca commented
Please refer to e3eca335940251308c8990c8880341002e74b9c1 for grouping/deprecating existing options with a new one.

2024-06-10 10:47 UTC, HazardyKnusperkeks commented on clang/lib/Format/ContinuationIndenter.cpp
> +    LanguageStyle->KeepEmptyLines.AtStartOfFile = true;
Why exactly is this necessary?

2024-06-11 03:07 UTC, sstwcw commented
I was initially going to make removing leading blank lines the default.
Now the line is not needed anymore.  But I forgot to remove it.

2024-06-18 07:44 UTC, owenca approved these changes

2024-06-18 07:44 UTC, owenca commented on clang/unittests/Format/FormatTest.cpp
> +  auto Style = getLLVMStyle();
An empty line before `auto Style = ...`?

2024-06-18 07:44 UTC, owenca commented on clang/unittests/Format/FormatTest.cpp
> +  auto Style = getLLVMStyle();
Ditto.

2024-06-25 04:02 UTC, merged

2024-06-25 06:56 UTC, vitalybuka commented
@sstwcw Please don't ignore the presubmit, it detected issue before merging:

Some checks were not successful
2 skipped, 65 successful, 48 failing, and 3 pending checks