release/18.x: [InstSimplify] Do not simplify freeze in `simplifyWithOpReplaced` (#91215)
llvm/llvm-project pull request #91419
Opened 2024-05-08 02:23 UTC by AtariDreams

See the LangRef:
> All uses of a value returned by the same ‘freeze’ instruction are
guaranteed to always observe the same value, while different ‘freeze’ instructions may yield different values.

It is incorrect to replace freezes with the simplified value.

Proof:
https://alive2.llvm.org/ce/z/3Dn9Cd
https://alive2.llvm.org/ce/z/Qyh5h6

Fixes https://github.com/llvm/llvm-project/issues/91178

(cherry picked from commit d085b42cbbefe79a41113abcd2b1e1f2a203acef)

2024-05-08 02:29 UTC, dtcxzyw requested changes

2024-05-09 00:26 UTC, nikic approved these changes
LGTM

2024-05-10 00:10 UTC, dtcxzyw commented
@AtariDreams Please don't rebase your patch unless there are some conflicts to be resolved.

At least you should tell us what you did.

2024-05-14 23:33 UTC, merged

2024-05-14 23:33 UTC, tstellar commented
@AtariDreams  (or anyone else). If you would like to add a note about this fix in the release notes (completely optional). Please reply to this comment with a one or two sentence description of the fix.  When you are done, please add the release:note label to this PR.