[clang][static analyzer] ignore try statements in dead code checker
llvm/llvm-project pull request #91675
Opened 2024-05-09 22:51 UTC by soukatch

Fixes #90162. Simplest approach I could come up with was to skip cxxtry statements. Let me know if you have any suggestions. Thanks!

2024-05-09 22:51 UTC, soukatch commented on clang/lib/StaticAnalyzer/Checkers/UnreachableCodeChecker.cpp
> +      if (isa<CXXTryStmt>(S))
everything above this point is just clang-format changes

2024-05-09 22:52 UTC, soukatch commented
@steakhal I believe you're the best person to tag :).

2024-05-09 22:53 UTC, soukatch commented on clang/lib/StaticAnalyzer/Checkers/UnreachableCodeChecker.cpp
> +      if (isa<CXXTryStmt>(S))
everything besides this if statement is just a clang-format change

2024-05-13 14:39 UTC, steakhal requested changes
Please remove the formatting changes. (Keep only the relevant lines)
Add a test demonstrating that this fixes a false-positive.

To find which file you need to add your test, I'd recommend braking something inside the checker to see which tests break. Then pick the file that seems to be the most relevant.

2024-05-13 15:54 UTC, soukatch commented
> To find which file you need to add your test,

I created a new file altogether since I don't think any of the current one would fit the test.

2024-05-14 06:55 UTC, steakhal approved these changes

2024-05-14 06:55 UTC, steakhal commented on clang/test/Analysis/unreachable-code-exceptions.cpp
> +// RUN: %clang_analyze_cc1 -verify %s -fcxx-exceptions -fexceptions -analyzer-checker=core -analyzer-checker=alpha.deadcode.UnreachableCode
```suggestion
// RUN: %clang_analyze_cc1 -verify %s -fcxx-exceptions -fexceptions -analyzer-checker=core,alpha.deadcode.UnreachableCode
```

2024-05-14 06:55 UTC, steakhal commented on clang/test/Analysis/unreachable-code-exceptions.cpp
> +}
```suggestion
void fp_90162() {
  try { // no-warning: The TryStmt shouldn't be unreachable.
    foo();
  } catch (int) {
    foo(); // We assume that catch handlers are reachable.
  }
}

```

2024-05-14 09:57 UTC, merged

2024-05-14 13:57 UTC, soukatch commented
Thanks for the review!