[compiler-rt][ASan] Add function moving annotations
llvm/llvm-project pull request #91702
Opened 2024-05-10 06:08 UTC by AdvenamTacet

This PR adds a `__sanitizer_move_contiguous_container_annotations` function, which moves annotations from one memory area to another. Old area is unpoisoned at the end. New area is annotated in the same way as the old region at the beginning (within limitations of ASan).

```cpp
void __sanitizer_move_contiguous_container_annotations(
    const void *old_storage_beg_p, const void *old_storage_end_p,
    const void *new_storage_beg_p, const void *new_storage_end_p) {
```

This function aims to help with short string annotations and similar container annotations. Right now we change trait types of `std::basic_string` when compiling with ASan.

https://github.com/llvm/llvm-project/blob/87f3407856e61a73798af4e41b28bc33b5bf4ce6/libcxx/include/string#L738-L751

The goal is to not change `__trivially_relocatable` when compiling with ASan. If this function is accpeted and upstreamed, the next step is creating function like `__memcpy_with_asan` moving memory with ASan. And then using this function instead of `__builtin__memcpy` while moving trivially relocatable objects.

https://github.com/llvm/llvm-project/blob/11a6799740f824282650aa9ec249b55dcf1a8aae/libcxx/include/__memory/uninitialized_algorithms.h#L644-L646

NOTICE: I did not test it yet, so it's probably not compiling, but I don't expect big changes. PR is WIP until I test it.

---

I'm thinking if there is a good way to address fact that in a container the new buffer is usually bigger than the previous one. We may add two more arguments to the functions to address it (the beginning and the end of the whole buffer.

Another potential change is removing `new_storage_end_p` as it's redundant, because we require the same size.

2024-05-10 21:27 UTC, philnik777 commented
trivial relocation is also interesting for erasing object from a vector, so the builtins should probably be more akin to a `memmove` than a `memcpy`.

2024-05-20 16:26 UTC, vitalybuka commented
LGTM for Asan however HWASAN story is not clear.
Let's make sure we can use this for HWASAN as well. 

It's probably fine, but I'd like to think about this more.

2024-05-22 02:10 UTC, AdvenamTacet commented
I still have to fix failing CI, I can sit to it on Monday and, if necessary, spend next week enough of time to fix it. I expect the problem to be a small implementation bug. Let me know if you have any high level requests for that code, I'm happy to implement them.
I will also create a separate PR cleaning compiler-rt ASan code, as I noticed a little bit of outdated code while writing this one.

> trivial relocation is also interesting for erasing object from a vector, so the builtins should probably be more akin to a memmove than a memcpy.

Should we change `__builtin_memcpy` to `__builtin_memmove`? Then I would have to add support for overlapping areas to this PR. (It complicates the implementation a little bit.)

> It's probably fine, but I'd like to think about this more.

Sure, let me know what are your conclusions!

2024-05-22 09:04 UTC, philnik777 commented
> > trivial relocation is also interesting for erasing object from a vector, so the builtins should probably be more akin to a memmove than a memcpy.
> 
> Should we change `__builtin_memcpy` to `__builtin_memmove`? Then I would have to add support for overlapping areas to this PR. (It complicates the implementation a little bit.)

Yes. My plan is to change the `__builtin_memcpy` to `__builtin_memmove` in `__uninitialized_allocator_relocate` to implement more optimizations in `vector`.

2024-08-08 00:38 UTC, vitalybuka requested changes
I assume work in progress.

2024-08-30 18:12 UTC, AdvenamTacet commented
This PR is ready for the review. I see nothing more what has to be done in it.

Next step (but it may be in a separate PR) is adding a function like `asan_unsafe_memmove`, which would be a `memmove` with turned off instrumentation (to not trigger ASan error). I'm unsure in which file we should add the function and I'm open to suggestions. Optionally we can create `asan_unsafe_memmove_with_annotations` (to copy content and annotations in one call).

2024-09-06 19:44 UTC, vitalybuka reviewed
I need some time to reasonably review PR.

2024-09-16 07:54 UTC, AdvenamTacet reviewed
> I need some time to reasonably review PR.

If I can help in any way, let me know!

2024-09-16 07:54 UTC, AdvenamTacet commented on compiler-rt/lib/asan/asan_poisoning.cpp
> +  uptr dst_storage_end =
That was my first implementation and original reasoning, but later I changed it. My motivation behind removing that argument was intended use of that function when (without ASan) memmove or memcpy is used and those functions assume same size of both containers. But I'm happy with either, reverted that change for now.

Also, should we keep this order of arguments (src, dst) or should we change the order to dst be before src? I based order on old/new container annotation functions, like:
```
void __sanitizer_annotate_double_ended_contiguous_container(
    const void *storage_beg_p, const void *storage_end_p,
    const void *old_container_beg_p, const void *old_container_end_p,
    const void *new_container_beg_p, const void *new_container_end_p) {
```
But maybe it's better to mimic memmove/memcpy with destination being first?

2024-09-16 07:54 UTC, AdvenamTacet commented on compiler-rt/test/asan/TestCases/copy_container_annotations.cpp
> +  char *old_buffer = new char[old_buffer_size];
Does it look good now? Or should I change more?

2024-10-03 06:51 UTC, vitalybuka approved these changes
Please pull the rest of https://github.com/llvm/llvm-project/pull/110941 and LGTM

I guess future TODO is to optimize  SLOW routines, which is 15x slower then fast path.

I think reasonably readable and efficient approach is to create
iterators which walk src shadow in bytes and convert into bitsets of poisoned bytes, with required shifts by offset.

and another iterator which stores bitsets into dst shadow.

2024-10-15 11:26 UTC, merged