[libc++][ranges] LWG3618: Unnecessary `iter_move` for `transform_view::iterator`
llvm/llvm-project pull request #91809
Opened 2024-05-10 21:03 UTC by xiaoyang-sde

## Introduction

This patch implements LWG3618: Unnecessary `iter_move` for `transform_view::iterator`.

`transform_view`'s iterator currently specifies a customization point for `iter_move`. This customization point does the same thing that the default implementation would do, but its sole purpose is to ensure the appropriate conditional `noexcept` specification.

## Reference

- [[range.transform.iterator]](https://eel.is/c++draft/range.transform.iterator)
- [LWG3618](https://cplusplus.github.io/LWG/issue3618)

2024-05-16 17:13 UTC, mordante commented on libcxx/docs/Status/Cxx23Issues.csv
> +"`3618 <https://wg21.link/LWG3618>`__","Unnecessary ``iter_move`` for ``transform_view::iterator`` ","February 2022","|Complete|","19.0","|ranges|"
The LWG-issues adds a `noexcept`. This is not tested in `libcxx/test/std/ranges/range.adaptors/range.transform/iterator/deref.pass.cpp`. Please update this test.

2024-07-04 17:04 UTC, ldionne requested changes
Gentle ping, it looks like there is outstanding feedback that needs to be addressed.

2024-07-05 05:16 UTC, xiaoyang-sde commented on libcxx/test/std/ranges/range.adaptors/range.transform/iterator/deref.pass.cpp
> +    ASSERT_NOEXCEPT(*std::declval<std::ranges::iterator_t<View>>());
The `operator*` previously provided a `noexcept` specifier as a libc++ extension. Following the adoption of this LWG issue, the `noexcept` specifier is now standard behavior.

2024-07-16 14:41 UTC, ldionne approved these changes
Thanks for clarifying with your comment. LGTM!

2024-07-21 23:12 UTC, xiaoyang-sde commented
> Thanks for clarifying with your comment. LGTM!

Could you please merge this patch? Thank you!

2024-07-22 16:32 UTC, merged