[clang][driver] add pointer qualifier to auto type
llvm/llvm-project pull request #91874
Opened 2024-05-11 23:57 UTC by VoltrexKeyva

Fix an LLVM coding standards inconformity by adding pointer qualifiers to `auto`-typed variables that deduce to pointer types.

See what the coding standards state [here](https://llvm.org/docs/CodingStandards.html#beware-unnecessary-copies-with-auto).

2024-05-20 03:05 UTC, VoltrexKeyva commented
Pinging are there haven't been any reviews in a week.

2024-05-26 08:03 UTC, VoltrexKeyva commented
Pinging again after another week of no reviews.

2024-06-03 16:17 UTC, JOE1994 approved these changes

2024-06-03 16:28 UTC, JOE1994 requested changes
The 3 updated items seem to be iterators and not pointers.

I think [the coding standard item](https://llvm.org/docs/CodingStandards.html#beware-unnecessary-copies-with-auto) doesn't apply here.

2024-06-06 22:17 UTC, VoltrexKeyva commented
I see, closing.

2024-06-06 22:17 UTC, closed without merging