[lldb] Refactor string manipulation in Debugger.cpp (#91209)
llvm/llvm-project pull request #91880
Opened 2024-05-12 06:51 UTC by aabhinavg

Author: aabhinavg <tiwariabhinavak@gmail.com>
Date: Sun May 12 12:46:54 2024 +0800
Reviewers: @JOE1994, @chelcassanova, @dcb314

Fixes: #91209

Summary of Changes:
- Replaced the ineffective call to 'substr' with a more efficient use of 'resize' to truncate the string.
- Adjusted the code to use 'resize' instead of 'substr' for better performance and readability.

2024-05-12 11:25 UTC, JOE1994 commented
A new user already asked to be assigned to work on #91209 2 days ago in the comments.
**I think that user deserves an opportunity to work on the issue**.

Next time when you see a **"good first issue"** which a new user had already asked to get assigned to,
please assign it to the new user.

2024-05-14 00:51 UTC, adrian-prantl commented
> A new user already asked to be assigned to work on #91209 2 days ago in the comments. **I think that user deserves an opportunity to work on the issue**.
> 
> Next time when you see a **"good first issue"** which a new user had already asked to get assigned to, please assign it to the new user.

We usually don't grant exclusive rights to work on an issue in the project, since individual priorities may always change and people might loose interest in an issue. Typically this kind of conflict doesn't happen very often either. For an issue as trivial as this one, it might be better to just open a PR straight ahead instead of waiting for the issue to be assigned to someone (which is also something we typically don't do in the project for the aforementioned reasons).

2024-05-14 01:29 UTC, JOE1994 commented
> We usually don't grant exclusive rights to work on an issue in the project, since individual priorities may always change and people might loose interest in an issue. Typically this kind of conflict doesn't happen very often either. 

I understand that, but just for "good first issue"s,
I think it's desirable to allow 1 week to the person (likely a newcomer to the project) who first requested to be assigned to it
(the 1st step in the "good first issue" instructions also suggests this).

The user who initially asked to be assigned to the linked issue doesn't have "assign" access, and was likely waiting to get assigned. Assigning the issue to another user without any explanation or ping can be emotionally frustrating to the new user.

I've seen a similar conflict around a "good first issue" get heated in (`#84207`).

2024-05-14 23:47 UTC, adrian-prantl commented
That's just not how the LLVM project operates.
I'd rather deal with two conflicting PRs than deal with an assigned orphaned issue that the assignee lost interest in.
This is in the end a communication problem, and I don't mind if someone responds to the bug to say that they're working on it, so another person doesn't waste time duplicating the effort. But we're not going to enforce exclusivity on the project level.

2024-05-17 15:21 UTC, JOE1994 requested changes
* The PR contains irrelevant changes to `X86` codegen.
* Author of the commit shows up as another contributor.

It seems like the author of this PR did a `git commit --amend`
on top of e586556e375fc5c4f7e76b5c299cb981f2016108 to add new changes.

Please update the branch to address these issues.

2024-05-17 15:36 UTC, merged