[mlir][vector] Split `TransposeOpLowering` into 2 patterns
llvm/llvm-project pull request #91935
Opened 2024-05-13 08:41 UTC by banach-space

Splits `TransposeOpLowering` into two patterns:
  1. `Transpose2DWithUnitDimToShapeCast` - rewrites 2D `vector.transpose`
    as `vector.shape_cast` (there has to be at least one unit dim),
  2. `TransposeOpLowering` - the original pattern without the part
    extracted into `Transpose2DWithUnitDimToShapeCast`.

The rationale behind the split:
  * the output generated by `Transpose2DWithUnitDimToShapeCast` doesn't
    really match the intended output from `TransposeOpLowering` as
    documented in the source file - it doesn't make much sense to keep
    it embedded inside `TransposeOpLowering`,
  * `Transpose2DWithUnitDimToShapeCast` _does_ work for scalable vectors,
    `TransposeOpLowering` _does_ not.

2024-05-13 09:09 UTC, MacDue commented
> Transpose2DWithUnitDimToShapeCast does work for scalable vectors, TransposeOpLowering does not.

Note that it only works _if_ (and only if) the `vector.shape_cast` cancels out.

2024-05-13 09:10 UTC, c-rhodes approved these changes

2024-05-13 09:23 UTC, MacDue approved these changes
Approving this PR, but I do wonder (with the benefit of hindsight), if the `Transpose2DWithUnitDimToShapeCast` lowering would be better as a (more specific) canonicalization of a `shape_cast + transpose`. Since what we really want here is for the illegal vector types (e.g. `vector<[4]x1xf32>`) to be eliminated, which won't _always_ happen if the transpose is replaced with a shape cast. 

E.g. the rewrite could be:

```
%0 = some_op 
%1 = vector.shape_cast %0 : vector<[4]xf32> to vector<[4]x1xf32>
%2 = vector.transpose %1 [1, 0] : vector<[4]x1xf32> to vector<1x[4]xf32>
```
->
```
%0 = some_op 
%1 = vector.shape_cast %0 : vector<[4]xf32> to vector<1x[4]xf32>
```

2024-05-13 16:18 UTC, MaheshRavishankar requested changes
I think such a change causes failure on SPIR-V backend. I think we've had this discussion previously. 

Waiting for more people to chime in. cc @kuhar  and @antiagainst

2024-05-13 18:41 UTC, banach-space commented
> I think such a change causes failure on SPIR-V backend.

It shouldn't, this is merely moving code around.

2024-05-13 19:50 UTC, MacDue commented
> > > I think such a change causes failure on SPIR-V backend.
> > 
> > 
> > It shouldn't, this is merely moving code around.
> 
> IIRC this is now going to be generating a vector.shape_cast that isnt handled on SPIR-V backends, and this pattern is being added to a "generic vector lowering" pattern set. I'd suggest adding a "populateVectorTransposeLoweringForLLVMPatterns" and adding this to that path. I know the SPIR-V path isnt tested as well in MLIR, but the shape_cast isnt supported on SPIR-V path.

IIRC this lowering has not been a problem on SPIR-V for a while now (since `populateVectorShapeCastLoweringPatterns()` is now called in the IREE SPIR-V backend). We removed any option to disable this lowering as it was not needed for SPIR-V (see #75062).

2024-05-13 21:03 UTC, banach-space commented
> IIRC this is now going to be generating a vector.shape_cast that isnt handled on SPIR-V backends

No, `TransposeOpLowering` _is already generating `vector.shape_cast`_ as demonstrated by these tests: https://github.com/llvm/llvm-project/blob/1fd196c8df8e9fa4e0eddddc92b012824d8d1b0b/mlir/test/Dialect/Vector/vector-transpose-lowering.mlir#L801-L858

In our previous discussion about these patterns, @antiagainst confirmed that those are not a problem for SPIR-V:
> We explicitly control when to perform transpose lowering and thus we can slot the lowering for type_cast in there too.

In any case, let me re-iterate, **this patch does not add any new patterns**, it is merely _moving_ the existing patterns.

> and this pattern is being added to a "generic vector lowering" pattern set

No, this pattern:
*  is _already_ present [within TransposeOpLowering](https://github.com/llvm/llvm-project/blob/1fd196c8df8e9fa4e0eddddc92b012824d8d1b0b/mlir/lib/Dialect/Vector/Transforms/LowerVectorTranspose.cpp#L337-L353), which
* is _already_ [added to populateVectorTransposeLoweringPatterns](https://github.com/llvm/llvm-project/blob/1fd196c8df8e9fa4e0eddddc92b012824d8d1b0b/mlir/lib/Dialect/Vector/Transforms/LowerVectorTranspose.cpp#L482-L487).

This PR merely extracts that logic into a separate class, `Transpose2DWithUnitDimToShapeCast`.  The rationale for that is summarised ... in the summary.

2024-05-13 23:52 UTC, MaheshRavishankar approved these changes
Ah, I understand now. Thanks for the explanation and sorry for the noise!

2024-05-14 08:37 UTC, banach-space commented
> I do wonder (with the benefit of hindsight), if the Transpose2DWithUnitDimToShapeCast lowering would be better as a (more specific) canonicalization of a shape_cast + transpose. 

That's a good point, but I'd like to get input from other reviewers first (specifically, folks that are using these patterns for something _other than_ scalable vectors). Let me add a TODO with your suggestion and we can re-visit at some later time. Hopefully somebody will notice and bring it up.

> Ah, I understand now. Thanks for the explanation and sorry for the noise!

It's good to have somebody with a SPIR-V hat on scanning these PRs, thanks for taking a look!

2024-05-14 11:08 UTC, merged