[msan] Dynamically grow kNumStackOriginDescrs
llvm/llvm-project pull request #92826
Opened 2024-05-20 21:48 UTC by thurstond

StackOriginDescr/StackOriginPC are currently fixed size arrays
and have a FIXME of resizability. This patch dynamically doubles
the size of these arrays as needed (for runtime that is amortized linear
in the size of the array).

Since NumStackOriginDescrs (the number of items currently stored in the array)
is monotonically increasing, there is no need to ever decrease the
allocated size of the array.

Testing notes: the old fixed limit was 1 million variables; this would be an
extremely large test case. By manually capping the maximum size, I found
that param_tls_limit.cpp is the test that is most sensitive to
kNumStackOriginDescrs.

2024-05-20 22:47 UTC, eugenis requested changes
This is not thread safe. I do not think you can do realloc() if you want the mutation to be lock free.

We could simply increase the constant size of the buffer (not perfect, but it is just .bss, not real memory).

We could go with an array of pointers to exponentially increasing allocations (i.e. same as your case, but never deallocate, instead just allocate more and consider the container a logical concatenation of multiple buffers).

2024-05-20 22:57 UTC, kstoimenov commented on compiler-rt/lib/msan/msan.cpp
> +    ResizeStackOriginMetadata(idx);
I am not sure if this is thread safe. I would recommend allocating StackOriginDescr to 1024 * 1024 in __msan_init and call ResizeStackOriginMetadata only to double the size. It still won't be 100% thread safe, but we expect it to happen very few times.

2024-05-21 00:02 UTC, thurstond commented
> This is not thread safe. I do not think you can do realloc() if you want the mutation to be lock free.

Thanks for the review, I had overlooked thread safety.

> We could simply increase the constant size of the buffer (not perfect, but it is just .bss, not real memory).

This is implemented in https://github.com/llvm/llvm-project/pull/92838

> We could go with an array of pointers to exponentially increasing allocations (i.e. same as your case, but never deallocate, instead just allocate more and consider the container a logical concatenation of multiple buffers).

This is still tricky to implement in a thread-safe, lock-free manner, because there are two arrays to be grown (StackOriginDescrs, StackOriginPC).

2024-05-21 16:17 UTC, closed without merging

2024-05-21 17:54 UTC, eugenis commented
> > We could go with an array of pointers to exponentially increasing allocations (i.e. same as your case, but never deallocate, instead just allocate more and consider the container a logical concatenation of multiple buffers).
> 
> This is still tricky to implement in a thread-safe, lock-free manner, because there are two arrays to be grown (StackOriginDescrs, StackOriginPC).

I think it will actually work pretty well.

If subarrays are power of 2 sized (1, 2, 4, 8, 16, ...), then the subarray for index i is basically log2(i+1). Both arrays can be handled independently; once the index is acquired, the subarray pointer is initialized with a double-checked locking pattern.

2024-05-21 19:29 UTC, eugenis commented
But then, it seems easier to just MAP_NORESERVE a large enough array in msan_init. It can be really large then, no concerns about relocation offset.