[AArch64] Remove usage of PostRAScheduler
llvm/llvm-project pull request #92871
Opened 2024-05-21 07:39 UTC by wangpc-pp

This doesn't take effect as we have overrided `enablePostRAScheduler`
and we should use the `FeaturePostRAScheduler` feature in processor
definitions.

2024-05-21 17:45 UTC, asl requested changes
Submit your PRs to `main` branch

2024-05-21 18:26 UTC, wangpc-pp commented
> Submit your PRs to `main` branch

I used [spr](https://getcord.github.io/spr/) to create this PR, so I think it's OK.

2024-05-22 02:20 UTC, dc03-work commented
> > Submit your PRs to `main` branch
> 
> I used [spr](https://getcord.github.io/spr/) to create this PR, so I think it's OK.

No, your target branch is wrong. Either you should want to merge into `main` or into a branch for another PR created by `spr`. However, in this case it appears you are targeting the same branch as your source.

2024-05-22 02:52 UTC, wangpc-pp commented
> > > Submit your PRs to `main` branch
> > 
> > 
> > I used [spr](https://getcord.github.io/spr/) to create this PR, so I think it's OK.
> 
> No, your target branch is wrong. Either you should want to merge into `main` or into a branch for another PR created by `spr`. However, in this case it appears you are targeting the same branch as your source.

These are two different branches:
wangpc-pp wants to merge 1 commit into
users/wangpc-pp/spr/main.aarch64-remove-usage-of-postrascheduler
from
users/wangpc-pp/spr/aarch64-remove-usage-of-postrascheduler

2024-05-22 03:39 UTC, dc03-work commented
> > > > Submit your PRs to `main` branch
> > > 
> > > 
> > > I used [spr](https://getcord.github.io/spr/) to create this PR, so I think it's OK.
> > 
> > 
> > No, your target branch is wrong. Either you should want to merge into `main` or into a branch for another PR created by `spr`. However, in this case it appears you are targeting the same branch as your source.
> 
> These are two different branches: wangpc-pp wants to merge 1 commit into users/wangpc-pp/spr/main.aarch64-remove-usage-of-postrascheduler from users/wangpc-pp/spr/aarch64-remove-usage-of-postrascheduler

Okay, but looking at the commits of the target: https://github.com/llvm/llvm-project/commits/users/wangpc-pp/spr/main.aarch64-remove-usage-of-postrascheduler/, it appears that spr has squashed all main commits into one commit. Anyways, this isn't the main branch. Change your PR to target the `main` branch.

2024-05-22 04:07 UTC, wangpc-pp commented
These branches are created by `spr`, which is out of my control, and we can merge it into `main` branch via `spr land`. These branches are just magics behind `spr`, please don't obsess over this. `spr` is a tool that the community suggests, I have used it for a long time and I haven't met any issue.

2026-08-03 12:18 UTC, closed without merging