Fix vgpr live range
llvm/llvm-project pull request #92940
Opened 2024-05-21 17:23 UTC by cmc-rep

2024-05-21 18:39 UTC, arsenm reviewed
Title and description needs to say what this is for and what it does

2024-05-22 10:22 UTC, perlfu commented on llvm/lib/Target/AMDGPU/AMDGPUFixLiveRangePreWaveRA.cpp
> +          if (CondOpnd.getReg() != AMDGPU::VCC &&
Yes this won't be sufficient.
I think the idea long term is to use MachineUniformityInfo.

2024-06-07 15:44 UTC, arsenm requested changes
Title and description needs work

2024-06-07 15:44 UTC, arsenm commented on llvm/lib/Target/AMDGPU/AMDGPUFixLiveRangePreWaveRA.cpp
> +static bool MBBHasWWM(const MachineBasicBlock &MBB) {
Start with lowercase

2024-06-07 15:44 UTC, arsenm commented on llvm/lib/Target/AMDGPU/AMDGPUFixLiveRangePreWaveRA.cpp
> +  if (CtrlDeps.find(DepMBB) == CtrlDeps.end())
is_contained?

2024-06-07 15:44 UTC, arsenm commented on llvm/lib/Target/AMDGPU/AMDGPUFixLiveRangePreWaveRA.cpp
> +  }
Can do this in the initializer

2024-06-07 15:44 UTC, arsenm commented on llvm/lib/Target/AMDGPU/AMDGPUFixLiveRangePreWaveRA.cpp
> +    WL.pop_back();
pop_back_val

2024-06-07 15:44 UTC, arsenm commented on llvm/lib/Target/AMDGPU/AMDGPUFixLiveRangePreWaveRA.cpp
> +bool AMDGPUFixLiveRangePreWaveRA::influences(MachineBasicBlock *CtrlMBB,
Is this the same as checking if they share a nearest common dominator?

2024-06-07 15:44 UTC, arsenm commented on llvm/lib/Target/AMDGPU/AMDGPUFixLiveRangePreWaveRA.cpp
> +                    << "\n");
Might as well delete this debug printing, it's redundant with PM debugging

2024-06-07 15:44 UTC, arsenm commented on llvm/lib/Target/AMDGPU/AMDGPUFixLiveRangePreWaveRA.cpp
> +                if (Opnd.isReg() && Opnd.getReg() == Reg) {
Exact equality of registers is probably broken when aliases are involved

2024-06-07 15:44 UTC, arsenm commented on llvm/lib/Target/AMDGPU/AMDGPUFixLiveRangePreWaveRA.cpp
> +                }
This loop should be a helper function (which also probably exists already)

2024-06-07 15:44 UTC, arsenm commented on llvm/lib/Target/AMDGPU/AMDGPUFixLiveRangePreWaveRA.cpp
> +                MI.addOperand(MF, MachineOperand::CreateReg(Reg, false, true));
Comment the parameters. Is this just an implicit use?

2024-06-07 15:44 UTC, arsenm commented on llvm/include/llvm/CodeGen/RegAllocCommon.h
> +#include <llvm/CodeGen/Register.h>
Use "" for project local includes

2025-12-24 01:37 UTC, closed without merging

2025-12-24 01:37 UTC, cmc-rep commented
close, move it to a branch in a different repo