[mlir] Decouple NVPTX target from CUDA toolkit presence
llvm/llvm-project pull request #93008
Opened 2024-05-22 09:26 UTC by tyb0807

Currently we only allow to serialize GPU module if CUDA toolkit is present, while in fact only serializing to binary format requires the latter.

This change make it possible to serialize GPU module to offload or assembly formats even when CUDA toolkit is not provided. The condition to be able to serialize GPU module is NVPTX target having been specified when building LLVM.

2024-05-22 10:23 UTC, ftynse approved these changes
Looks reasonable, IIRC, the design of the new GPU pipeline was intended to avoid a compile-time dependency on CUDA libraries.

Does the AMD backend suffer from the same issue?

2024-05-22 10:23 UTC, ftynse commented on mlir/lib/Target/LLVM/NVVM/Target.cpp
> +  std::optional<SmallVector<char, 0>>
I see that you are only moving this, but consider adding some documentation if you understand what this does.

2024-05-22 10:23 UTC, ftynse commented on mlir/lib/Target/LLVM/NVVM/Target.cpp
> +  // Target options.
```suggestion
  /// Target options.
```

2024-05-22 10:23 UTC, ftynse commented on mlir/lib/Target/LLVM/NVVM/Target.cpp
> +        "CUDA toolkit not provided when trying to serialize GPU module.");
```suggestion
        "CUDA toolkit not provided when trying to serialize GPU module");
```

2024-05-22 10:27 UTC, grypp reviewed
Looks good, is it possible to add a test?

2024-05-22 10:27 UTC, grypp commented on mlir/lib/Target/LLVM/NVVM/Target.cpp
> +        "CUDA toolkit not provided when trying to serialize GPU module.");
Can we test that path?

2024-05-22 10:30 UTC, fabianmcg requested changes
They're already decoupled, `MLIR_ENABLE_CUDA_CONVERSIONS` is an alias for checking whether the `NVPTX` target was built, see:
https://github.com/llvm/llvm-project/blob/main/mlir/CMakeLists.txt#L115C1-L119

Also, `moduleToObject` will succeed if `NVPTX` was built and the compilation target is `offload` or `ptx`, I know this because I use it frequently in a machine without the toolkit.

I'm ok with changing the name of the flag as it might be confusing.

2024-05-22 12:21 UTC, tyb0807 commented
> They're already decoupled, `MLIR_ENABLE_CUDA_CONVERSIONS` is an alias for checking whether the `NVPTX` target was built, see: https://github.com/llvm/llvm-project/blob/main/mlir/CMakeLists.txt#L115C1-L119
> 
> Also, `moduleToObject` will succeed if `NVPTX` was built and the compilation target is `offload` or `ptx`, I know this because I use it frequently in a machine without the toolkit.
> 
> I'm ok with changing the name of the flag as it might be confusing.

Yes, one of the changes introduced here is just replacing `MLIR_ENABLE_CUDA_CONVERSIONS` to `LLVM_HAS_NVPTX_TARGET`. However, I'm keeping `MLIR_ENABLE_CUDA_CONVERSIONS` flag to indicate whether CUDA toolkit is configured or not, as one can build LLVM with `NVPTX`, then accidentally try to serialize to `binary` without having the toolkit available. The part of the code that does actual serialization to binary (using `ptxas` or `nvptxcompiler`) will now be guarded by `MLIR_ENABLE_CUDA_CONVERSIONS` and should only be available if CUDA toolkit is configured.

Does this make sense?

2024-05-22 12:36 UTC, fabianmcg commented
> The part of the code that does actual serialization to binary (using `ptxas` or `nvptxcompiler`) will now be guarded by `MLIR_ENABLE_CUDA_CONVERSIONS` and should only be available if CUDA toolkit is configured.
> 
> Does this make sense?

Not really. Because you're not changing the definition of `MLIR_ENABLE_CUDA_CONVERSIONS`, hence `MLIR_ENABLE_CUDA_CONVERSIONS` and `LLVM_HAS_NVPTX_TARGET` still fulfill the same purpose.

If the CUDA toolkit is not installed and try to serialize you'll get:
```
error: Couldn't find the `ptxas` binary. Please specify the toolkit path, add the compiler to $PATH, or set one of the environment variables in `NVVM::getCUDAToolkitPath()`.
```
And that's by design, as it allows to ship the functionality of compilation without requiring a hard dependency on the toolkit. This is also what `clang` does, you don't need the toolkit to build clang, only for compiling the code and if the toolkit is missing then fail gracefully.

2024-05-22 14:39 UTC, joker-eph commented
Considering the discussion, the whole PR title and description will need a revamp I believe.

2024-05-22 21:52 UTC, tyb0807 commented
I've replaced `MLIR_ENABLE_CUDA_CONVERSIONS` with `LLVM_HAS_NVPTX_TARGET`. There are way more modifications than anticipated but these are NFC IMO.

2024-05-22 21:58 UTC, joker-eph commented
I don't see a change in mlir-config.h ? Can you grep for MLIR_ENABLE_CUDA_CONVERSIONS and ensure it does not remain any occurrence in the codebase.

2024-05-22 21:59 UTC, joker-eph commented on mlir/test/lit.site.cfg.py.in
> +config.run_cuda_tests = "@LLVM_HAS_NVPTX_TARGET@"
Can you rename `run_cuda_tests` as well? It is incorrectly named now.

2024-05-22 22:14 UTC, tyb0807 commented
>I don't see a change in mlir-config.h ? Can you grep for MLIR_ENABLE_CUDA_CONVERSIONS and ensure it does not remain any occurrence in the codebase
Indeed, I messed up during rebase somehow. Thanks!

2024-05-23 06:46 UTC, tyb0807 commented
@fabianmcg is it better now?

2024-05-23 12:24 UTC, fabianmcg approved these changes
LGTM, thank you! Just make sure that:
- all integration tests pass
- `ninja check-mlir` succeeds with and without the NVPTX being built.

2024-05-24 09:56 UTC, ftynse requested changes
Looks even cleaner, thanks! But I suspect there is something off with how the macro is interpreted, it should be an always-defined 0/1 macro.

Note that Bazel is an optional build system for LLVM, you don't necessarily have to update it.

2024-05-24 13:29 UTC, ftynse approved these changes

2024-05-24 15:31 UTC, merged

2024-05-24 15:35 UTC, joker-eph commented on mlir/lib/Target/LLVM/CMakeLists.txt
>    find_package(CUDAToolkit)
This is marked resolved but I don't see the change?