[MC] Explicitly request executable stacks
llvm/llvm-project pull request #93478
Opened 2024-05-27 13:54 UTC by rofirrim

We are working on Fortran applications and some of them rely on passing a pointer to an internal (aka nested) function that uses the enclosing context (e.g., a variable of the enclosing function). [Flang uses trampolines](https://flang.llvm.org/docs/InternalProcedureTrampolines.html) which rely on `llvm.init.trampoline` and `llvm.adjust.trampoline`. Those rely on having an executable stack.

This change is a preliminary step to support trampolines on RISC-V.

According to GNU ld's manual

> If an input file does not have a .note.GNU-stack section present then
> the default behaviour is target specific.

We currently disable explicit stacks by default. But when we do need them, we instead rely on the default of them being enabled. This is not true for all the architectures. In special for RISC-V where executable stacks are disabled by default.

This changes to always emit the note.GNU-stack section.

The updated test belongs to X86 because at this point RISC-V still does not support trampolines. This will come in a later change.

2024-05-30 06:42 UTC, MaskRay commented
If flang's feature requires an executable stack.
I strongly encourage that you revisit the design.
A can of security mechanisms would frown upon execstack.
musl intentionally does not support executable stacks (thread stacks).

> We currently disable explicit stacks by default. But when we do need them, we instead rely on the default of them being enabled. This is not true for all the architectures. In special for RISC-V where executable stacks are disabled by default.

execstack would become more and more difficult to enable... https://www.redhat.com/en/blog/linkers-warnings-about-executable-stacks-and-segments

2024-05-30 08:55 UTC, rofirrim commented
Thanks @MaskRay .

@vzakhari @kiranchandramohan would it make sense to allocate the trampoline buffer somewhere else other than the stack? Say in the heap and free it upon leaving the function (it needs to be allocated just once per function as it is conceptually a temporary of the argument evaluation, so in that sense it is a bit like an `allocatable`).

2024-05-30 23:23 UTC, MaskRay commented
> Thanks @MaskRay .
> 
> @vzakhari @kiranchandramohan would it make sense to allocate the trampoline buffer somewhere else other than the stack? Say, on the heap and free it upon leaving the function (it needs to be allocated just once per function as it is conceptually a temporary of the argument evaluation, so in that sense it is a bit like an `allocatable`).
> 
> We could use the Fortran runtime to allocate an executable buffer.

Thanks. I'll request changes as I believe we don't want to support executable stacks or make easy for people to use it.

2024-05-30 23:23 UTC, MaskRay requested changes
.

2024-05-30 23:36 UTC, vzakhari commented
> Thanks @MaskRay .
> 
> @vzakhari @kiranchandramohan would it make sense to allocate the trampoline buffer somewhere else other than the stack? Say, on the heap and free it upon leaving the function (it needs to be allocated just once per function as it is conceptually a temporary of the argument evaluation, so in that sense it is a bit like an `allocatable`).
> 
> We could use the Fortran runtime to allocate an executable buffer.

Hello @rofirrim,

Yes, we want to avoid requiring the executable stack for executing Fortran internal subprograms via procedure pointers.  Have you read https://flang.llvm.org/docs/InternalProcedureTrampolines.html#alternative-implementation-s and https://flang.llvm.org/docs/InternalProcedureTrampolines.html#implementation-options?  These are some options available to us, and there may be more (e.g. https://fortran-lang.discourse.group/t/is-creating-nested-subroutines-functions-considered-good-practice-in-fortran/6545/26).

2024-05-31 02:26 UTC, rofirrim commented
> Hello @rofirrim,
> 
> Yes, we want to avoid requiring the executable stack for executing Fortran internal subprograms via procedure pointers. Have you read https://flang.llvm.org/docs/InternalProcedureTrampolines.html#alternative-implementation-s and https://flang.llvm.org/docs/InternalProcedureTrampolines.html#implementation-options? These are some options available to us, and there may be more (e.g. https://fortran-lang.discourse.group/t/is-creating-nested-subroutines-functions-considered-good-practice-in-fortran/6545/26).

Thanks @vzakhari somehow I missed the alternative options.

2024-05-31 02:27 UTC, rofirrim commented
> Thanks. I'll request changes as I believe we don't want to support executable stacks or make easy for people to use it.

Sure. I will close this as nothing is left to do for now.

The discussion suggests that a later PR should make the emission of the GNU-note for non-executable stacks unconditional (i.e. irrespective of whether the trampoline intrinsics were used in the module or not).

2024-05-31 02:27 UTC, closed without merging