[mlir][linalg] Add folder for transpose(transpose) -> transpose
llvm/llvm-project pull request #93606
Opened 2024-05-28 20:04 UTC by ryan-holt-1

Back to back `linalg.transpose` can be rewritten to a single transpose

2024-05-28 20:07 UTC, ryan-holt-1 commented
@akshathb

2024-05-29 12:42 UTC, cxy-1993 requested changes
Thanks for the patch. This patch still needs a few minor changes.

2024-05-29 12:42 UTC, cxy-1993 commented on mlir/test/Dialect/Linalg/canonicalize.mlir
> +  func.return %transpose2 : tensor<5x4x3xf32>
nit: Maybe we should check func.return use %input as result?

2024-05-29 12:42 UTC, cxy-1993 commented on mlir/lib/Dialect/Linalg/IR/LinalgOps.cpp
> +
nit: remove redundant blank line

2024-05-29 12:42 UTC, cxy-1993 commented on mlir/lib/Dialect/Linalg/IR/LinalgOps.cpp
> +      auto perms = transposeOp.getPermutation();
nit: expand auto unless it is obvious

2024-05-29 18:40 UTC, ryan-holt-1 commented
Thanks for the review @cxy-1993. I have addressed your comments.

2024-05-30 02:03 UTC, cxy-1993 approved these changes
LGTM

2024-05-30 08:28 UTC, ftynse approved these changes

2024-05-30 08:28 UTC, ftynse commented on mlir/lib/Dialect/Linalg/IR/LinalgOps.cpp
> +            transposeOp.getInput().getDefiningOp<TransposeOp>()) {
https://llvm.org/docs/CodingStandards.html#use-early-exits-and-continue-to-simplify-code

2024-05-30 14:41 UTC, merged