[mlir][EmitC] Emit parentheses when expression ops are used as operands
llvm/llvm-project pull request #93691
Opened 2024-05-29 14:24 UTC by simon-camp

Inlined expression ops where emitted as is irrespective to the context of the op in which they were used. This is corrected by emitting additional parentheses around the expression. The parentheses are omitted if it is safe to so in the context of the user.

Fixes #93470.

2024-05-29 15:01 UTC, mgehre-amd approved these changes
Thank you!

2024-05-29 15:18 UTC, aniragil commented
I wonder if we could instead add another restriction to `shouldBeInlined`: Don't inline if the user has the `CExpression` trait. 
The rationale is that the using `CExpression` could have been fused into its operand `ExpressionOp`. If it wasn't, then the pass(es) that formed the expressions did not want it to be fused. Inlining the `ExpressionOp` operand into it goes against that intention.
This would also make sure that we handle expression emission in one place, i.e. `ExpressionOp`s, where `cast` should already be emitted correctly with parenthesis as needed.

2024-05-29 15:32 UTC, cferry-AMD approved these changes
Looks good, thanks :)

2024-06-03 11:57 UTC, simon-camp commented
> I wonder if we could instead add another restriction to `shouldBeInlined`: Don't inline if the user has the `CExpression` trait. The rationale is that the using `CExpression` could have been fused into its operand `ExpressionOp`. If it wasn't, then the pass(es) that formed the expressions did not want it to be fused. Inlining the `ExpressionOp` operand into it goes against that intention. This would also make sure that we handle expression emission in one place, i.e. `ExpressionOp`s, where `cast` should already be emitted correctly with parenthesis as needed.

I implemented this in the last commit. I don't know which of these solutions is preferable.

2024-06-04 06:43 UTC, cferry-AMD approved these changes

2024-06-04 06:43 UTC, cferry-AMD commented on mlir/lib/Target/Cpp/TranslateToCpp.cpp
> +  }
```suggestion
  if (expressionOp && shouldBeInlined(expressionOp))
    return emitExpression(expressionOp);
```

2024-06-04 06:48 UTC, aniragil requested changes
LGTM (with a nit)

2024-06-04 06:48 UTC, aniragil commented on mlir/lib/Target/Cpp/TranslateToCpp.cpp
nit: please restore the [single statement format](https://www.llvm.org/docs/CodingStandards.html#don-t-use-braces-on-simple-single-statement-bodies-of-if-else-loop-statements)

2024-06-04 07:12 UTC, TinaAMD reviewed
Thanks for taking care of this!

2024-06-04 07:12 UTC, TinaAMD commented on mlir/test/Target/Cpp/expressions.mlir
> +// CPP-DEFAULT-NEXT:   int32_t v4 = 0;
Nit: Can you capture all the local variables?
```suggestion
// CPP-DEFAULT-NEXT:   int32_t [[VAL_4:v[0-9]+]] = 0;
```

2024-06-04 08:57 UTC, aniragil requested changes

2024-06-04 08:57 UTC, aniragil commented on mlir/lib/Target/Cpp/TranslateToCpp.cpp
> +  return !user->hasTrait<OpTrait::emitc::CExpression>();
Actually, isn't the first check now redundant?
If the user is part of an ExpressionOp then it must have the CExpression trait, right?

2024-06-04 10:11 UTC, aniragil approved these changes
Thanks @simon-camp !

2024-06-04 10:31 UTC, TinaAMD approved these changes
LGTM

2024-06-04 11:14 UTC, merged