[Clang][AArch64] Generalise streaming mode checks for builtins.
llvm/llvm-project pull request #93802
Opened 2024-05-30 10:49 UTC by sdesmalen-arm

PR #76975 added 'IsStreamingOrSVE2p1' to emit a diagnostic when a builtin marked
with 'IsStreamingOrSVE2p1' is used in a non-streaming function that is not
compiled with `+sve2p1`.

The problem is a bit more complex than only this case. For example, we've marked
lots of builtins with 'IsStreamingCompatible', meaning it can be used in either
streaming, streaming-compatible or non-streaming functions. But the code in
SemaChecking, doesn't check the appropriate target guards. This issue becomes
relevant when SVE builtins are only available in streaming mode, e.g. when
compiling for SME without SVE.

If we were to add the appropriate target guards, we'd have to add many more
combinations, e.g.:
  IsStreamingSMEOrSVE
  IsStreamingSME2OrSVE2
  IsStreamingSMEOrSVE2p1
  IsStreamingSME2OrSVE2p1
  etc.

To avoid having to add more combinations (and avoid having to add more in the
future for new extensions), we use a single 'IsSVEOrStreamingSVE' flag for all
builtins that are available in streaming mode for the appropriate SME flags, or
in non-streaming mode for the appropriate SVE flags, or both.  The code in
SemaChecking will then verify for which mode (or both) the builtin would be
defined, given the target features of the function/compilation unit.

For example:

  'svclamp' is enabled under FEAT_SVE2p1 and FEAT_SME2

* When we compile for SVE2p1 and SME (but not SME2), the builtin is undefined
  behaviour when called from a streaming function.

* When we compile for SME2 and SVE2 (but not SVE2p1), the builtin is undefined
  behaviour when called from a non-streaming function.

* When we compile for _both_ SVE2p1 and SME2, the builtin can be used in either
  mode (non-streaming, streaming or streaming-compatible)

2024-06-03 17:32 UTC, aemerson approved these changes
LGTM with suggestion

2024-06-03 17:32 UTC, aemerson commented on clang/test/Sema/aarch64-streaming-sme-or-nonstreaming-sve-builtins.c
> +}
For completeness can we have a test as well to check this case but instead with `__arm_streaming` as well

2024-06-04 16:52 UTC, paulwalker-arm requested changes

2024-06-04 16:52 UTC, paulwalker-arm commented on clang/lib/Sema/SemaARM.cpp
> +    if (SatisfiesSVE && SatisfiesSME)
Does this effectively prevent streaming compatible functions when only SVE feature flags are available?

My updated understand of streaming compatible functions is that SME features play no role and the user is expected to use SVE feature flags to direct the compiler to the level of SVE support a streaming compatible function can have, much like they would for ordinary functions.

2024-06-04 16:52 UTC, paulwalker-arm commented on clang/include/clang/Basic/arm_sve_sme_incl.td
> +def IsSVEOrStreamingSVE             : FlagType<0x40000000000>; // Use for intrinsics that are common between SVE and SME.
If you permit a bit of bike shedding I don't think this is a good name.  From what I can see the new flag is used to trigger dynamic resolution to determine if the builtin is available to use based on the target features along with any keywords associated with the function.  Perhaps `RequiresDynamicVerification`? or ideally something shorter that has the same meaning.

2024-06-14 09:44 UTC, sdesmalen-arm commented on clang/lib/Sema/SemaARM.cpp
> +        CallerFeatureMapWithoutSME;
You're right, not sure what I was thinking here with the 'static' variable :)

I'd rather not go down the route of parsing the BuiltinTargetGuards here or making assumptions on the format if we're not going to ensure this format in the arm_sve.td file. For example, one can write `(sve,featureX)|(sme2,featureX)` or `(sve|sme),featureX`. Sure we can assume the former format, but in that case I think we need to have a `SVETargetGuard` and a `SMETargetGuard`, that we let TableGen combine into a canonical form for the combined `TargetGuard`.

2024-06-14 09:44 UTC, sdesmalen-arm commented on clang/lib/Sema/SemaARM.cpp
> +      HasError |= checkArmStreamingBuiltin(SemaRef, TheCall, FD, *BuiltinType,
Done

2024-06-14 09:44 UTC, sdesmalen-arm commented on clang/lib/Sema/SemaARM.cpp
> +    static unsigned CachedODRHash = 0;
Done

2024-06-15 12:21 UTC, paulwalker-arm approved these changes

2024-06-16 16:24 UTC, merged