[clang-tidy] Option to ignore anonymous namespaces in avoid-non-const-global-variables
llvm/llvm-project pull request #93827
Opened 2024-05-30 14:07 UTC by pascalj

Add an option to ignore warnings for cppcoreguidelines avoid-non-const-global-variables.

Understandably, the core guidelines discourage non const global variables, even at the TU level (see https://github.com/isocpp/CppCoreGuidelines/issues/2195). However, having a small TU with an interface that uses a non const variable from an anonymous namespace can be a valid choice.

This adds an option that disables the warning just for anonymous namespaces, i.e. at the file level. The default is still to show a warning, just as before.

2024-05-30 14:13 UTC, EugeneZelenko commented on clang-tools-extra/docs/clang-tidy/checks/cppcoreguidelines/avoid-non-const-global-variables.rst
> +   When set to `true` (default is `false`), non-const variables in anonymous namespaces will not generate a warning.
Default value is usually stated in dedicated sentence at the end of paragraph.

2024-05-30 14:28 UTC, PiotrZSL requested changes
- storeOptions is missing
- release notes need to be updated about added new option
- tests need some love (reduce amount of changes)
- what about "static" non const global variables 

I'm fine for having an options that control behavior of the check.
But please note that there are other aspects of "I.2: Avoid non-const global variables" rule that anonymous namespace or static does not solve. Like race-conditions in multithread env. Or even to force developer not to use global objects to pass data between functions.

Even that I see many times that warnings from this check are being nolinted, I still think that it's doing good job.

2024-05-30 16:23 UTC, carlosgalvezp commented
I have a bit the feeling that users should use NOLINT* here instead of having a global option that is not seen in the code. Anonymous namespaces do not solve many of the remaining issues. A NOLINT in the code can grab the attention of a future developer and prompt a refactoring to avoid the pattern.

I don't have a strong opinion so if this is really wanted I won't object.

2024-05-31 10:04 UTC, pascalj commented on clang-tools-extra/test/clang-tidy/checkers/cppcoreguidelines/avoid-non-const-global-variables.cpp
> +// RUN: %check_clang_tidy %s -check-suffix=NAMESPACE cppcoreguidelines-avoid-non-const-global-variables %t -- \
Thanks for this hint, it made the checks much easier. It now tests only for the cases where the configuration differs.

2024-05-31 10:04 UTC, pascalj commented
Thanks for your feedback!

>     * what about "static" non const global variables

Good point, forgot about these. If both are allowed, it is more about the internal linkage than it is about the namespace. I renamed the option to `AllowInternalLinkage` and permit variables in anonymous namespaces and static global variables, since they're equivalent (AFAICT). 

> I'm fine for having an options that control behavior of the check. But please note that there are other aspects of "I.2: Avoid non-const global variables" rule that anonymous namespace or static does not solve. Like race-conditions in multithread env. Or even to force developer not to use global objects to pass data between functions.
> 
> Even that I see many times that warnings from this check are being nolinted, I still think that it's doing good job.

I completely agree with both you and @carlosgalvezp: this is neither an option that should be enabled by default, nor should people prefer it over nolinting without some thought. However, I see not much harm in giving someone the choice to do so. In the end, all of clang-tidy's checks are optional to some degree.

Having said that: if the maintainers prefer not to have this option, this is also fine with me.

2024-06-10 18:13 UTC, PiotrZSL approved these changes
LGTM

2024-06-15 10:06 UTC, SimplyDanny approved these changes

2024-06-15 10:06 UTC, SimplyDanny commented on clang-tools-extra/clang-tidy/cppcoreguidelines/AvoidNonConstGlobalVariablesCheck.cpp
> +      AllowInternalLinkage(Options.get("AllowInternalLinkage", false)) {}
Option name could be a constant to avoid duplication.

2024-06-15 10:56 UTC, 5chmidti approved these changes
While I'm leaning more towards 
> NOLINT in the code can grab the attention of a future developer and prompt a refactoring to avoid the pattern.

, it's an off-by-default option that provides a choice.

LGTM

2024-06-15 10:56 UTC, 5chmidti commented on clang-tools-extra/test/clang-tidy/checkers/cppcoreguidelines/avoid-non-const-global-variables.cpp
FYI: You could remove the explicit check-nots here:

```c++
// RUN: %check_clang_tidy %s -check-suffixes=,INTERNAL-LINKAGE cppcoreguidelines-avoid-non-const-global-variables %t
// RUN: %check_clang_tidy %s cppcoreguidelines-avoid-non-const-global-variables %t -- \
// RUN: -config="{CheckOptions: {cppcoreguidelines-avoid-non-const-global-variables.AllowInternalLinkage : 'true'}}"


namespace {
int nonConstAnonymousNamespaceInt = 0;
// CHECK-MESSAGES-INTERNAL-LINKAGE: :[[@LINE-1]]:5: warning: variable 'nonConstAnonymousNamespaceInt' is non-const and globally accessible, consider making it const [cppcoreguidelines-avoid-non-const-global-variables]
} // namespace
```

(There are also two check-nots where the line is off by one)

2024-06-15 13:18 UTC, HerrCai0907 approved these changes

2024-07-01 19:12 UTC, merged