[libc][type_traits] Add aligned_storage
llvm/llvm-project pull request #94074
Opened 2024-05-31 22:53 UTC by PiJoules

2024-05-31 23:36 UTC, michaelrj-google commented
This patch has reminded me that I need to simplify the bazel a bit, so definitely don't land it before this patch lands: https://github.com/llvm/llvm-project/pull/94079

2024-06-01 03:46 UTC, lntue approved these changes

2024-06-01 03:48 UTC, lntue requested changes
You'll need to add the new header to the `type_traits` target in `src/__support/CPP/CMakeLists.txt`

2024-06-03 19:54 UTC, PiJoules commented
> You'll need to add the new header to the `type_traits` target in `src/__support/CPP/CMakeLists.txt`

Done

2024-06-05 19:52 UTC, lntue approved these changes

2024-06-05 19:59 UTC, merged