[libc++] Mark a few functions in the dylib as noexcept
llvm/llvm-project pull request #94098
Opened 2024-06-01 06:33 UTC by philnik777

2024-06-04 18:07 UTC, EricWF commented
Why?

2024-06-04 18:07 UTC, EricWF requested changes
Please add a description of why.

2024-06-10 14:19 UTC, ldionne approved these changes
LGTM, thanks for adding an explanation of the motivation. This wasn't clear to me at all :)

2024-06-12 02:18 UTC, ldionne commented
Merging since CI is green.

2024-06-12 02:18 UTC, merged