[InstCombine] Add fold for fabs(-x) -> fabs(x)
llvm/llvm-project pull request #94183
Opened 2024-06-03 04:12 UTC by VaibhavRumale

Here is my patch for #94170
 
Added the missing optimization in `visitCallInst` function to fold `fabs(-x)` into `fabs(x)'. I also added the required test cases to verify the optimization for various data types, including scalar floats, doubles, and vector types.

2024-06-03 09:05 UTC, dtcxzyw commented on llvm/lib/Transforms/InstCombine/InstCombineCalls.cpp
> +    Value* Arg = II->getArgOperand(0);
Can you replace all following uses of `II->getArgOperand(0)` with `Arg`?

2024-06-03 09:05 UTC, dtcxzyw commented on llvm/lib/Transforms/InstCombine/InstCombineCalls.cpp
> +    if (match(Arg, m_FNeg(m_Value(X)))) {
Please drop the braces.
See https://llvm.org/docs/CodingStandards.html#don-t-use-braces-on-simple-single-statement-bodies-of-if-else-loop-statements

2024-06-03 09:05 UTC, dtcxzyw commented on llvm/test/Transforms/InstCombine/fabs-fneg-fold.ll
> +; RUN: opt -S -passes=instcombine %s | FileCheck %s
Please regenerate check lines with `llvm/utils/update_test_checks.py`

2024-06-03 09:05 UTC, dtcxzyw commented on llvm/test/Transforms/InstCombine/fabs-fneg-fold.ll
> +declare float @llvm.fabs.f32(float)
These declarations are unnecessary.

2024-06-03 16:16 UTC, arsenm commented on llvm/test/Transforms/InstCombine/fabs-fneg-fold.ll
> +
Should test flag preservation behavior

2024-06-03 16:16 UTC, arsenm commented on llvm/lib/Transforms/InstCombine/InstCombineCalls.cpp
> +    if (match(Arg, m_FNeg(m_Value(X)))) {
Somewhere is a strip sign operations helper function that also covers copysign

2024-06-04 08:56 UTC, dtcxzyw commented
@VaibhavRumale Please don't update your branch if there is no merge conflict. See https://llvm.org/docs/GitHub.html#rebasing-pull-requests-and-force-pushes

2024-06-04 08:59 UTC, dtcxzyw commented
@tstellar Should we turn off `Always suggest updating pull request branches`? I think it is misleading to new contributors.

2024-06-04 09:07 UTC, VaibhavRumale commented
@dtcxzyw Apologies! I will be more careful going forward. Thank you!

2024-06-06 10:25 UTC, arsenm requested changes
Should test flag preservation behavior. Should also add similar copysign tests, since those should be handled just like fabs

2024-06-07 07:53 UTC, VaibhavRumale commented
> @VaibhavRumale Please don't update your branch if there is no merge conflict. See https://llvm.org/docs/GitHub.html#rebasing-pull-requests-and-force-pushes

Thanks for sharing the guide. It seems like I made a mistake of committing from my main branch. Can I create a new PR with my new changes, as I know we cannot use forced commits?

2024-06-07 08:19 UTC, arsenm commented
> Can I create a new PR with my new changes, as I know we cannot use forced commits?

It's not that you can't, it's just generally discouraged but not always. But you can always create a new one

2024-06-14 23:57 UTC, closed without merging

2024-06-15 02:39 UTC, VaibhavRumale commented
Thanks for the reviews. I have opened a new PR #95627 with the changes.