goldsteinn/select equiv non const
llvm/llvm-project pull request #94719
Opened 2024-06-07 04:28 UTC by goldsteinn

- **[InstCombine] Add tests for expanding `foldSelectValueEquivalence`; NFC**
- **[InstCombine] Improve coverage of `foldSelectValueEquivalence` for non-constants**

2024-06-07 04:29 UTC, goldsteinn commented
Going to run csmith for a few days w/ this. Will ping back results probably monday.

2024-06-07 07:55 UTC, nikic requested changes
I don't think this is worth the complication. The only part of this I would consider is the `NewOp == V` case, though I'm having some trouble convincing myself that this really can't lead to a combine loop.

2024-06-12 16:29 UTC, goldsteinn commented
Ran ~5million csmith tests. No inf loops or bad codegen. Although note only got different resulting IR ~100 times over all the tests.

2024-06-12 17:33 UTC, dtcxzyw commented
> I don't think this is worth the complication. The only part of this I would consider is the `NewOp == V` case, though I'm having some trouble convincing myself that this really can't lead to a combine loop.

I agree.

2024-06-22 00:11 UTC, goldsteinn commented
Dropped the use-reduction code. Think for this to inf loop you would need to violate SSA i.e: f(x, y) -> y -> y(x, z) -> x. For us to go from x -> y, then y would need to both be dominated by x and dominate x.

2024-06-22 07:26 UTC, nikic commented on llvm/lib/Transforms/InstCombine/InstCombineSelect.cpp
> -      if (match(NewOp, m_ImmConstant())) {
Can you just add `|| NewOp == V` to this line and leave everything else alone?

2024-06-22 17:09 UTC, nikic approved these changes
LGTM

2024-06-22 18:42 UTC, dtcxzyw approved these changes
LGTM.

2024-06-23 03:16 UTC, closed without merging