[LLDB][NFC] Fix a cppcheck warning in lldb/source/Host/linux/Host.cpp
llvm/llvm-project pull request #94783
Opened 2024-06-07 18:08 UTC by xgupta

Fix #89710

2024-06-07 18:10 UTC, JDevlieghere requested changes
Similar concern as https://github.com/llvm/llvm-project/pull/94775#issuecomment-2155285000

2024-07-24 11:16 UTC, DavidSpickett commented
Please remove the formatting changes and limit this to just the specifier change.

I know most of the time we'd want it formatted but for a fix as limited as this, the formatting change just gets in the way, and not formatting it doesn't block merging either.

Otherwise this LGTM once that's done.

2024-07-24 11:16 UTC, DavidSpickett commented
The bot will complain again but we will ignore it :)

2024-07-24 11:33 UTC, labath reviewed
The field this is consuming is actually 17 bytes long, because the process name is in parenthesis. I suspect this will cause the function to reject any process whose name is longer than 13 characters.

The name field is actually quite hard to parse this way since it can contain any character (esp. parenthesis and spaces). Now, we could devise an algorithm to do that, but since the code is later opening `/proc/$PID/status` anyway, and `status` contains a superset of information, I think it'd be best to just delete this code and extract the information we want from there.

`status` parsing code also uses more modern and less error prone patterns.

2024-07-24 11:42 UTC, DavidSpickett requested changes
> The field this is consuming is actually 17 bytes long, because the process name is in parenthesis.

Ok then I am confused how this ever worked, but it sounds like scanf was never a great way to do this anyway?

2024-07-24 11:46 UTC, labath commented
> > The field this is consuming is actually 17 bytes long, because the process name is in parenthesis.
> 
> Ok then I am confused how this ever worked, but it sounds like scanf was never a great way to do this anyway?

The field it's overwriting is in a struct, so it has a lot of headroom for "safely" overflowing without hitting anything important. And since the the other fields are parsed after the string field, they probably just immediately overwrite the corrupted data.

2024-07-24 14:36 UTC, DavidSpickett commented
In that case, best not to store it at all at least until a better way to parse it is found - https://github.com/llvm/llvm-project/pull/100387.

2024-07-25 08:18 UTC, DavidSpickett commented
I have merged https://github.com/llvm/llvm-project/pull/100387 to fix this instead, because it needed some background knowledge to do correctly.

But never the less, thank you @xgupta for making the effort to do this PR, it has uncovered some unsafe code that only recently went in. Which is a great result in itself!

2024-07-25 08:18 UTC, closed without merging

2024-07-25 10:28 UTC, xgupta commented
Thanks, @DavidSpickett for your work.