[lldb] Adjust the for loop condition to prevent unintended increments in ExpandRLE (NFC)
llvm/llvm-project pull request #94844
Opened 2024-06-08 06:30 UTC by xgupta

This PR address the issue reported by static analyser cppcheck regarding missing bounds check for extra iterator increment in a loop. This could lead to accessing out-of-bounds memory. 
To fix this we have adjusted the loop conditions to not incrementing iterator c there.

Caught by cppcheck -
lldb/source/Plugins/Process/gdb-remote/GDBRemoteCommunication.cpp:1300:75: warning: Missing bounds check for extra iterator increment in loop. [StlMissingComparison]

Fix #91225

2024-06-10 07:53 UTC, labath commented on lldb/source/Plugins/Process/gdb-remote/GDBRemoteCommunication.cpp
> +    c++;
How does this prevent an out of bounds access? If I understand the problem correctly, the right fix to check for an almost-end iterator when doing the RLE expansion (change the condition to something like `if (*c == '*' && std::next(c) != packet.end())`, just less clumsy).

2024-08-19 04:47 UTC, xgupta commented
ping!

2024-08-20 18:38 UTC, bulbazord requested changes

2024-08-20 18:38 UTC, bulbazord commented on lldb/source/Plugins/Process/gdb-remote/GDBRemoteCommunication.cpp
> +    c++;
Having the `c++` here is equivalent to having it in the "increment" portion of the for loop construct, why move it here?

2024-08-20 18:38 UTC, bulbazord commented on lldb/source/Plugins/Process/gdb-remote/GDBRemoteCommunication.cpp
>      } else {
I can't comment on it for some reason, but above this else is an `else if (*c == 0x7d)`. That block also does `*++c`, which will also go out of bounds if `std::next(c) == packet.end()`. You need to add a check there too, don't you?

2025-02-10 09:44 UTC, xgupta commented
Could not understand the right fix. Better it to leave it.

2025-02-10 09:44 UTC, closed without merging