[BPF] Use ".L" local prefix label for basic blocks
llvm/llvm-project pull request #95103
Opened 2024-06-11 12:30 UTC by aengelke

Previously, PrivateLabelPrefix was default-initialized to "L", so basic block labels were added to the symbol table. This seems like an oversight, so use ".L" for all private labels.

---

I'm not sure whether this is correct. But there's no documentation anywhere that states something else and MCAsmInfo.h documentation states that PrivateLabelPrefix "Defaults to the same as PrivateGlobalPrefix," so this really seems like an oversight. Also, BPF is the only target where private label and global prefixes differ.

2024-06-11 18:14 UTC, 4ast requested changes
There is no need to add dot. The bpf asm code is often read my humans and extra dot is a visual noise.

2024-06-11 19:25 UTC, 4ast commented
> > The bpf asm code is often read my humans and extra dot is a visual noise.
> 
> basic block labels would no longer be added to the symbol table

that's a regression. they didn't meant to be in symbol table.

> Would removing the dot from private global symbols be an option, so that they are prefixed with `L` instead `.L`?

Yep. PrivateGlobalPrefix =  PrivateLabelPrefix = "L" is certainly better.

2024-06-11 19:57 UTC, aengelke commented
> PrivateGlobalPrefix = PrivateLabelPrefix = "L" is certainly better.

I now changed the prefix so that for BPF all local labels start with "L" without dot.

2024-06-12 14:49 UTC, 4ast commented
> The "quick fix" broke AMDGPU, so I had to add a new BPF mangling mode that uses "L" for private labels.

wait what ?
Why change ManglingMode ? This doesn't look right. It's still an ELF.
It's really puzzling why default "L" prefix needs this special logic.

@eddyz87 @yonghong-song pls take a look.

2024-06-12 22:02 UTC, MaskRay commented
While I'm not involved with BPF development, I favor using `PrivateGlobalPrefix = PrivateLabelPrefix = ".L"` like regular ELF targets.
This is better from an assembler's perspective: `.L` prevents name collision with user-defined symbols.
Object file formats that use `L` typically decorate regular symbols with `_` to avoid name collision, which causes uglier names.

If `.L` symbols in the symbol table are useful, I'd suggest that BPF targets enable the cc1 option `-save-temp-label` by default.

2024-06-13 01:31 UTC, 4ast commented
I'm starting to lean toward ".L" as well, but first would like to understand why "L" is causing issues.

2024-06-24 04:30 UTC, MaskRay commented
Ping:)

2024-07-10 05:57 UTC, MaskRay commented
Ping:)

2024-07-10 15:13 UTC, 4ast approved these changes
lgtm. sorry for delay.

2024-07-24 18:39 UTC, yonghong-song commented
Okay, looks like consensus is to use '.L' prefix for private global prefix and private label prefix. @aengelke could you make the change again? The below should work:
```
diff --git a/llvm/lib/Target/BPF/MCTargetDesc/BPFMCAsmInfo.h b/llvm/lib/Target/BPF/MCTargetDesc/BPFMCAsmInfo.h
index 7b2168458c93..1173fe2f7590 100644
--- a/llvm/lib/Target/BPF/MCTargetDesc/BPFMCAsmInfo.h
+++ b/llvm/lib/Target/BPF/MCTargetDesc/BPFMCAsmInfo.h
@@ -25,6 +25,7 @@ public:
       IsLittleEndian = false;
 
     PrivateGlobalPrefix = ".L";
+    PrivateLabelPrefix = ".L";
     WeakRefDirective = "\t.weak\t";
```

2024-07-24 19:04 UTC, 4ast commented
> Okay, looks like consensus is to use '.L' prefix for private global prefix and private label prefix. @aengelke could you make the change again? The below should work:
> 
> ```
> diff --git a/llvm/lib/Target/BPF/MCTargetDesc/BPFMCAsmInfo.h b/llvm/lib/Target/BPF/MCTargetDesc/BPFMCAsmInfo.h
> index 7b2168458c93..1173fe2f7590 100644
> --- a/llvm/lib/Target/BPF/MCTargetDesc/BPFMCAsmInfo.h
> +++ b/llvm/lib/Target/BPF/MCTargetDesc/BPFMCAsmInfo.h
> @@ -25,6 +25,7 @@ public:
>        IsLittleEndian = false;
>  
>      PrivateGlobalPrefix = ".L";
> +    PrivateLabelPrefix = ".L";
>      WeakRefDirective = "\t.weak\t";
> ```

No. The current diff changed things to work properly with "L".

2024-07-27 01:03 UTC, yonghong-song commented
Just want to confirm. @4ast You perfer to use prefix 'L' for all temp labels?

2024-07-27 02:42 UTC, 4ast commented
> Just want to confirm. @4ast You perfer to use prefix 'L' for all temp labels?

Yes. As this patch implements it. The issue we had is that those L labels were in symbol table. This patch is fixing that.

2024-07-27 04:09 UTC, yonghong-song commented
@aengelke This patch does not really work. I downloaded [aengelke:bpf-private-label-prefix](https://github.com/aengelke/llvm-project/tree/bpf-private-label-prefix) and build the clang/llvm tools.  I hit the following errors:

```
$ cat test.c
int test(int a, int b, int *p1, int *p2) {
   if (a < b) *p1 = a * b;
   else if (a > b) *p2 = a * b * a;
   return a * a;
}
$ ~/tmp3/llvm-project/llvm/build/install/bin/clang --target=bpf -O2 -c -g test.c
error: backend data layout 'e-m:b-p:64:64-i64:64-i128:128-n32:64-S128' does not match expected target description 'e-m:e-p:64:64-i64:64-i128:128-n32:64-S128'
1 error generated.
$
```

I then applied the following change,
```
diff --git a/clang/lib/Basic/Targets/BPF.h b/clang/lib/Basic/Targets/BPF.h
index d19b37dd4df7..00909afb8093 100644
--- a/clang/lib/Basic/Targets/BPF.h
+++ b/clang/lib/Basic/Targets/BPF.h
@@ -35,9 +35,9 @@ public:
     Int64Type = SignedLong;
     RegParmMax = 5;
     if (Triple.getArch() == llvm::Triple::bpfeb) {
-      resetDataLayout("E-m:e-p:64:64-i64:64-i128:128-n32:64-S128");
+      resetDataLayout("E-m:b-p:64:64-i64:64-i128:128-n32:64-S128");
     } else {
-      resetDataLayout("e-m:e-p:64:64-i64:64-i128:128-n32:64-S128");
+      resetDataLayout("e-m:b-p:64:64-i64:64-i128:128-n32:64-S128");
     }
     MaxAtomicPromoteWidth = 64;
     MaxAtomicInlineWidth = 64;
```
and compilation can now pass. However, I didn't see L* lables in the symbol table:
```
$ ~/tmp3/llvm-project/llvm/build/install/bin/clang --target=bpf -O2 -c -g test.c
$ ~/tmp3/llvm-project/llvm/build/install/bin/llvm-readelf -s test.o

Symbol table '.symtab' contains 12 entries:
   Num:    Value          Size Type    Bind   Vis       Ndx Name
     0: 0000000000000000     0 NOTYPE  LOCAL  DEFAULT   UND 
     1: 0000000000000000     0 FILE    LOCAL  DEFAULT   ABS test.c
     2: 0000000000000000     0 SECTION LOCAL  DEFAULT     2 .text
     3: 0000000000000000     0 SECTION LOCAL  DEFAULT     3 .debug_loclists
     4: 0000000000000000     0 SECTION LOCAL  DEFAULT     4 .debug_abbrev
     5: 0000000000000000     0 SECTION LOCAL  DEFAULT     7 .debug_str_offsets
     6: 0000000000000000     0 SECTION LOCAL  DEFAULT     9 .debug_str
     7: 0000000000000000     0 SECTION LOCAL  DEFAULT    10 .debug_addr
     8: 0000000000000000     0 SECTION LOCAL  DEFAULT    15 .debug_frame
     9: 0000000000000000     0 SECTION LOCAL  DEFAULT    17 .debug_line
    10: 0000000000000000     0 SECTION LOCAL  DEFAULT    19 .debug_line_str
    11: 0000000000000000   136 FUNC    GLOBAL DEFAULT     2 test
$ ~/tmp3/llvm-project/llvm/build/install/bin/llvm-objdump -d test.o

test.o: file format elf64-bpf

Disassembly of section .text:

0000000000000000 <test>:
       0:       bf 25 00 00 00 00 00 00 r5 = r2
       1:       67 05 00 00 20 00 00 00 r5 <<= 0x20
       2:       c7 05 00 00 20 00 00 00 r5 s>>= 0x20
       3:       bf 16 00 00 00 00 00 00 r6 = r1
       4:       67 06 00 00 20 00 00 00 r6 <<= 0x20
       5:       c7 06 00 00 20 00 00 00 r6 s>>= 0x20
       6:       bf 10 00 00 00 00 00 00 r0 = r1
       7:       2f 00 00 00 00 00 00 00 r0 *= r0
       8:       7d 56 03 00 00 00 00 00 if r6 s>= r5 goto +0x3 <test+0x60>
       9:       2f 12 00 00 00 00 00 00 r2 *= r1
      10:       63 23 00 00 00 00 00 00 *(u32 *)(r3 + 0x0) = r2
      11:       05 00 04 00 00 00 00 00 goto +0x4 <test+0x80>
      12:       7d 65 03 00 00 00 00 00 if r5 s>= r6 goto +0x3 <test+0x80>
      13:       bf 01 00 00 00 00 00 00 r1 = r0
      14:       2f 21 00 00 00 00 00 00 r1 *= r2
      15:       63 14 00 00 00 00 00 00 *(u32 *)(r4 + 0x0) = r1
      16:       95 00 00 00 00 00 00 00 exit
```

If I add '-Wa,-L' in the command line below, the L* labels will be in symbol
and those labels are in llvm-objdump as well.
```
$ ~/tmp3/llvm-project/llvm/build/install/bin/clang --target=bpf -O2 -c -g test.c -Wa,-L                                     
$ ~/tmp3/llvm-project/llvm/build/install/bin/llvm-readelf -s test.o                                                         
                                                                                                                                                       
Symbol table '.symtab' contains 15 entries:                                                                                                            
   Num:    Value          Size Type    Bind   Vis       Ndx Name                                                                                       
     0: 0000000000000000     0 NOTYPE  LOCAL  DEFAULT   UND                                                                                            
     1: 0000000000000000     0 FILE    LOCAL  DEFAULT   ABS test.c                                                                                     
     2: 0000000000000000     0 SECTION LOCAL  DEFAULT     2 .text                                                                                      
     3: 0000000000000060     0 NOTYPE  LOCAL  DEFAULT     2 LBB0_2                                                                                     
     4: 0000000000000080     0 NOTYPE  LOCAL  DEFAULT     2 LBB0_4                                                                                     
     5: 0000000000000000     0 SECTION LOCAL  DEFAULT     3 .debug_loclists                                                                            
     6: 0000000000000000     0 SECTION LOCAL  DEFAULT     4 .debug_abbrev
     7: 0000000000000000     0 NOTYPE  LOCAL  DEFAULT    17 Lline_table_start0
     8: 0000000000000000     0 SECTION LOCAL  DEFAULT     7 .debug_str_offsets
     9: 0000000000000000     0 SECTION LOCAL  DEFAULT     9 .debug_str
    10: 0000000000000000     0 SECTION LOCAL  DEFAULT    10 .debug_addr
    11: 0000000000000000     0 SECTION LOCAL  DEFAULT    15 .debug_frame
    12: 0000000000000000     0 SECTION LOCAL  DEFAULT    17 .debug_line
    13: 0000000000000000     0 SECTION LOCAL  DEFAULT    19 .debug_line_str 
    14: 0000000000000000   136 FUNC    GLOBAL DEFAULT     2 test
$ ~/tmp3/llvm-project/llvm/build/install/bin/llvm-objdump -d test.o

test.o: file format elf64-bpf

Disassembly of section .text:

0000000000000000 <test>:
       0:       bf 25 00 00 00 00 00 00 r5 = r2
       1:       67 05 00 00 20 00 00 00 r5 <<= 0x20
       2:       c7 05 00 00 20 00 00 00 r5 s>>= 0x20
       3:       bf 16 00 00 00 00 00 00 r6 = r1
       4:       67 06 00 00 20 00 00 00 r6 <<= 0x20
       5:       c7 06 00 00 20 00 00 00 r6 s>>= 0x20
       6:       bf 10 00 00 00 00 00 00 r0 = r1
       7:       2f 00 00 00 00 00 00 00 r0 *= r0
       8:       7d 56 03 00 00 00 00 00 if r6 s>= r5 goto +0x3 <LBB0_2>
       9:       2f 12 00 00 00 00 00 00 r2 *= r1
      10:       63 23 00 00 00 00 00 00 *(u32 *)(r3 + 0x0) = r2
      11:       05 00 04 00 00 00 00 00 goto +0x4 <LBB0_4>

0000000000000060 <LBB0_2>:
      12:       7d 65 03 00 00 00 00 00 if r5 s>= r6 goto +0x3 <LBB0_4>
      13:       bf 01 00 00 00 00 00 00 r1 = r0
      14:       2f 21 00 00 00 00 00 00 r1 *= r2
      15:       63 14 00 00 00 00 00 00 *(u32 *)(r4 + 0x0) = r1

0000000000000080 <LBB0_4>:
      16:       95 00 00 00 00 00 00 00 exit
```

So to ensure L* labels in symbol table, one way is to add -Wa,-L in compilation flags. But that is a little bit tedious, so maybe we can find some llvm internal setting which allows target to overwrite in order to enable L* labels in symbol table. I have not poked into llvm internal yet.

2024-07-27 04:22 UTC, 4ast commented
@yonghong-song we're talking past each other. L labels should NOT be in the symbol table. They are private. We had a bug before.

2024-07-27 04:39 UTC, yonghong-song commented
Okay, looks like current llvm19/llvm20 already do not have L* labels in symbol table.
@eddyz87 has another pull request (https://github.com/llvm/llvm-project/pull/100550) to address llvm-objdump without-label issue. There are a couple of options to resolve this. Since we do not want L* in the symbol table,
then the only option may be tweak llvm-objdump.

2024-07-27 05:09 UTC, MaskRay commented
> Okay, looks like current llvm19/llvm20 already do not have L* labels in symbol table. @eddyz87 has another pull request (#100550) to address llvm-objdump without-label issue. There are a couple of options to resolve this. Since we do not want L* in the symbol table, then the only option may be tweak llvm-objdump.

#100550 is for `llvm-objdump --symbolize-operands`, which creates fake labels for the disassembly output.

For this patch, I hope we use `.L` to be similar to other ELF architectures and not to create a special case:)

2024-07-27 15:58 UTC, 4ast commented
> > Okay, looks like current llvm19/llvm20 already do not have L* labels in symbol table. @eddyz87 has another pull request (#100550) to address llvm-objdump without-label issue. There are a couple of options to resolve this. Since we do not want L* in the symbol table, then the only option may be tweak llvm-objdump.
> 
> #100550 is for `llvm-objdump --symbolize-operands`, which creates fake labels for the disassembly output.
> 
> For this patch, I hope we use `.L` to be similar to other ELF architectures and not to create a special case:)

are you saying that if we use ".L" then private labels will automatically appear in disasm output and we don't need this extra flag?
If so let's switch to ".L".

2024-07-27 18:18 UTC, MaskRay commented
> > > Okay, looks like current llvm19/llvm20 already do not have L* labels in symbol table. @eddyz87 has another pull request (#100550) to address llvm-objdump without-label issue. There are a couple of options to resolve this. Since we do not want L* in the symbol table, then the only option may be tweak llvm-objdump.
> > 
> > 
> > #100550 is for `llvm-objdump --symbolize-operands`, which creates fake labels for the disassembly output.
> > For this patch, I hope we use `.L` to be similar to other ELF architectures and not to create a special case:)
> 
> are you saying that if we use ".L" then private labels will automatically appear in disasm output and we don't need this extra flag? If so let's switch to ".L".

`llvm-objdump -d --symbolize-operands` is a way to improve readability of the disassembly, which doesn't need symbol table entries.
With that feature, basic block labels are likely less relevant.  In that case, we should favor more `.L` to match regular ELF targets.

There is a question whether `--symbolize-operands` should be the default for `llvm-objdump` BPF. While I don't favor that inconsistency, the discussion can be postponed to a difference place and not block the PR that switches to `.L`

2024-07-27 23:30 UTC, 4ast commented
> 
> `llvm-objdump -d --symbolize-operands` is a way to improve readability of the disassembly, which doesn't need symbol table entries. With that feature, basic block labels are likely less relevant. In that case, we should favor more `.L` to match regular ELF targets.
> 
> There is a question whether `--symbolize-operands` should be the default for `llvm-objdump` BPF. While I don't favor that inconsistency, the discussion can be postponed to a difference place and not block the PR that switches to `.L`

well, this two PRs are related. Currently bpf users used to see L* labels in disasm and we have to preserve this behavior.
Turned out that they were in disasm by default because of bug/feature that L* labels were in symbol table.
Now if we remove them from symbol table either via this patch or via switching to ".L" we will regress disasm output, right?
I was hoping that switch to ".L" will make labels to appear in disasm automatically without extra flag.
If that is not the case we should treat both PRs as one and make sure disasm is still readable regardless of whether we pick L or .L

2024-07-28 00:12 UTC, yonghong-song commented
@4ast For this ' I was hoping that switch to ".L" will make labels to appear in disasm automatically without extra flag.', the switch to '.L' won't change anything to disasm since with '.L' the labels still not in symbol table.

https://github.com/llvm/llvm-project/pull/100550 is the right direction as at least with option --symbolize-operands, the disasm will break basic blocks with labels properly. Without https://github.com/llvm/llvm-project/pull/100550, even with --symbolize-operands, the disasm will display without any labels.

But at you mentioned, this is a regression. Previous, 'llvm-objdump -d ...' will be able to disasm with proper labels. Now we need 'llvm-objdump --symbolize-operands -d ...'. That is why I suggest to make '--symbolize-operands' as the default at least for BPF. An option '--no-symbolize-operands' can be added to disable labels.

2024-07-31 00:09 UTC, 4ast requested changes
We need to keep L symbols in symbol table to preserve current disasm behavior.
Once --symbolize-operands becomes a default for objdump we can revisit this diff.

2026-01-20 04:30 UTC, MaskRay commented
What else is needed to move forward this change to be consistent with other ELF targets?

2026-01-20 06:24 UTC, yonghong-song commented
I think `--symbolize-operands` is not default yet for bpf target.

2026-03-01 21:54 UTC, MaskRay commented
> I think `--symbolize-operands` is not default yet for bpf target.

OK. Created https://github.com/llvm/llvm-project/pull/184043 ("[llvm-objdump] Default --symbolize-operands for BPF"), after which this patch can hopefully be accepted.

After `MCAsmInfo::PrivateLabelPrefix` switches to `.L` to BPF, I plan to remove the misleading variable and rename `PrivateGlobalPrefix` (I am discussing with GAS maintainers on the new terminology. We will likely use "internal symbol prefix").

2026-03-05 18:15 UTC, MaskRay commented
> > I think `--symbolize-operands` is not default yet for bpf target.
> 
> OK. Created #184043 ("[llvm-objdump] Default --symbolize-operands for BPF"), after which this patch can hopefully be accepted.
> 
> After `MCAsmInfo::PrivateLabelPrefix` switches to `.L` to BPF, I plan to remove the misleading variable and rename `PrivateGlobalPrefix` (I am discussing with GAS maintainers on the new terminology. We will likely use "internal symbol prefix").

#184043 ("[llvm-objdump] Default --symbolize-operands for BPF") has been merged. This is unblocked.

2026-03-12 05:12 UTC, MaskRay commented
This is unblocked, but needs a rebase and needs to drop the `MM_BPF` IR mangling change.

2026-03-14 23:58 UTC, MaskRay approved these changes

2026-03-15 18:12 UTC, yonghong-song approved these changes

2026-03-15 18:28 UTC, merged