[lldb][swig] Refactor callback typemaps and functions
llvm/llvm-project pull request #95318
Opened 2024-06-12 21:48 UTC by chelcassanova

This commit refactors the typemaps and static functions used in the SWIG typemaps and wrappers to be in their own SWIG files that are included in the main `python.swig` file.

2024-06-12 21:56 UTC, medismailben requested changes

2024-06-12 21:56 UTC, medismailben commented on lldb/bindings/python/python-callbacks-typemaps.swig
> + use the Python C API to access Python objects instead of using PythonDataObjects.
nit: it would be nice to put the Python C API documentation link.

2024-06-12 21:56 UTC, medismailben commented on lldb/bindings/python/python-callbacks-typemaps.swig
> +    PythonCallable callable = Retain<PythonCallable>($input);
This is a PythonDataObject type

2024-06-12 21:56 UTC, medismailben commented on lldb/bindings/python/python-callbacks-typemaps.swig
> +    llvm::Expected<PythonCallable::ArgInfo> arg_info = callable.GetArgInfo();
Also you can't use llvm here.

2024-06-13 02:25 UTC, bulbazord reviewed
Is this just moving code around? The summary says what you're doing but not why, what's the motivation?

2024-06-18 22:38 UTC, closed without merging

2024-06-18 22:44 UTC, chelcassanova commented
Closing this PR, we wanted to be able to do this _without_ using the `PythonDataObjects` class in the swig wrapper that contains callback functions but this looks to be unfeasible for callbacks that return SB objects