Run PreStmt/PostStmt checker for GCCAsmStmt
llvm/llvm-project pull request #95409
Opened 2024-06-13 13:56 UTC by T-Gruber

Run PreStmt and PostStmt checker for GCCAsmStmt.
Unittest to validate that corresponding callback functions are triggered.

2024-06-13 18:22 UTC, steakhal commented
Could you please drop the format only changes so that I could focus on the actual change set?

2024-06-13 19:04 UTC, T-Gruber commented
> Could you please drop the format only changes so that I could focus on the actual change set?

I just reverted the format changes. Thanks for letting me know.

2024-07-10 06:44 UTC, T-Gruber commented
Hi @steakhal , what is your opinion on this PR?
Are there any open points from my side?

2024-07-10 07:34 UTC, steakhal requested changes
Thanks for the ping. Looks really nice!
FYI I just came across a case last week w.r.t asm gotos. You can have a read [here](https://sonarsource.atlassian.net/browse/CPP-5459) if you are interested in the subject.

2024-07-10 07:34 UTC, steakhal commented on clang/lib/StaticAnalyzer/Core/ExprEngine.cpp
> +    } break;
Hm, I think it would look better if the break was inside the braces.

2024-07-10 07:34 UTC, steakhal commented on clang/unittests/StaticAnalyzer/ExprEngineVisitTest.cpp
> +};
I think you could merge these two into a single class.
Similar goes to the other parts. To me `asm stmt` is itself a thing to test.
But it's just a personal preference.
One other way to look at this is basically the combinatorical explosion of the tests if we wanted to cover all other statements and different callback kinds. The boilerplate to useful code would just blow up.

2024-07-10 08:47 UTC, T-Gruber commented
> Thanks for the ping. Looks really nice! FYI I just came across a case last week w.r.t asm gotos. You can have a read [here](https://sonarsource.atlassian.net/browse/CPP-5459) if you are interested in the subject.

Thank you! Looks interesting. Does this mean that the linked problem would also benefit from this PR?

2024-07-10 11:08 UTC, steakhal commented
> > Thanks for the ping. Looks really nice! FYI I just came across a case last week w.r.t asm gotos. You can have a read [here](https://sonarsource.atlassian.net/browse/CPP-5459) if you are interested in the subject.
> 
> Thank you! Looks interesting. Does this mean that the linked problem would also benefit from this PR?

I haven't if this PR would help or not. My guess would be that this wouldn't help. 

Please fix the formatting. After that we can merge this PR.

2024-07-10 11:50 UTC, T-Gruber commented
> > > Thanks for the ping. Looks really nice! FYI I just came across a case last week w.r.t asm gotos. You can have a read [here](https://sonarsource.atlassian.net/browse/CPP-5459) if you are interested in the subject.
> > 
> > 
> > Thank you! Looks interesting. Does this mean that the linked problem would also benefit from this PR?
> 
> I haven't if this PR would help or not. My guess would be that this wouldn't help.
> 
> Please fix the [formatting](https://github.com/llvm/llvm-project/pull/95409#issuecomment-2219921933). After that we can merge this PR.

I reworked the unittest and fixed the format as well. Thanks for your help!

2024-07-10 12:14 UTC, steakhal approved these changes

2024-07-10 12:15 UTC, merged