Parse target attribute
llvm/llvm-project pull request #95519
Opened 2024-06-14 09:25 UTC by labrinea

This is the second attempt. We should be inserting the Driver
features in front of the features of a parsed target attribute
to avoid errors like the following:

```
% cat neon.c
__attribute__((target("arch=armv8-a")))
uint64x2_t foo(uint64x2_t a, uint64x2_t b) { return veorq_u64(a, b); }

% clang --target=aarch64-linux-gnu -c neon.c
error: always_inline function 'veorq_u64' requires target feature
       'outline-atomics', but would be inlined into function 'foo'
       that is compiled without support for 'outline-atomics'
```

2024-06-14 10:56 UTC, tommat01 requested changes

2024-06-18 08:48 UTC, tmatheson-arm approved these changes
LGTM

2024-06-18 14:34 UTC, tmatheson-arm approved these changes

2024-06-18 20:28 UTC, merged

2025-09-28 07:49 UTC, XiaShark commented
Hello, I noticed an issue after this PR: if both `-march` and `-mcpu` are specified in the command line parameters, the features in `-mcpu` are lost. See https://godbolt.org/z/hPq1z9rvn. Is this expected behavior?

2025-09-28 11:19 UTC, XiaShark commented
> Hello, I noticed an issue after this PR: if both `-march` and `-mcpu` are specified in the command line parameters, the features in `-mcpu` are lost. See https://godbolt.org/z/hPq1z9rvn. Is this expected behavior?

After re-adding `initFeatureMap`, the issue was resolved.
```c++
bool AArch64TargetInfo::initFeatureMap(
     llvm::StringMap<bool> &Features, DiagnosticsEngine &Diags, StringRef CPU,
     const std::vector<std::string> &FeaturesVec) const {
  std::vector<std::string> UpdatedFeaturesVec;
  // Parse the CPU and add any implied features.
  std::optional<llvm::AArch64::CpuInfo> CpuInfo = llvm::AArch64::parseCpu(CPU);
  if (CpuInfo) {
    auto Exts = CpuInfo->getImpliedExtensions();
    std::vector<StringRef> CPUFeats;
    llvm::AArch64::getExtensionFeatures(Exts, CPUFeats);
    for (auto F : CPUFeats) {
      assert((F[0] == '+' || F[0] == '-') && "Expected +/- in target feature!");
      UpdatedFeaturesVec.push_back(F.str());
    }
  }

  for (const auto &Feature : FeaturesVec)
    if (Feature[0] != '?') {
      std::string UpdatedFeature = Feature;
      if (Feature[0] == '+') {
        std::optional<llvm::AArch64::ExtensionInfo> Extension =
          llvm::AArch64::parseArchExtension(Feature.substr(1));
        if (Extension)
          UpdatedFeature = Extension->PosTargetFeature.str();
      }
      UpdatedFeaturesVec.push_back(UpdatedFeature);
    }

  return TargetInfo::initFeatureMap(Features, Diags, CPU, UpdatedFeaturesVec);
}
```

2025-09-28 17:25 UTC, davemgreen commented
GCC seems to work the same way, where the -march option takes precedence: https://godbolt.org/z/4vd13P5xx.

2025-09-29 02:46 UTC, XiaShark commented
> GCC seems to work the same way, where the -march option takes precedence: https://godbolt.org/z/4vd13P5xx.

I see, thanks