[clang] Emitting a warning if optimizations are enabled with sanitizers
llvm/llvm-project pull request #95934
Opened 2024-06-18 14:30 UTC by Ritanya-B-Bharadwaj

Sanitizers achieve better accuracy with lower optimization levels, and it is generally recommended to use `-O0` (the default optimization level) when using sanitizers for the most accurate results. However, many users might not be aware of this recommendation.

To ensure transparency, we should issue a warning when optimization levels other than `-O0` are enabled alongside sanitizers. This warning will inform users that higher optimization levels can reduce the effectiveness of sanitizers, thereby making them aware of the potential impact on the accuracy of sanitizer.

2024-06-27 08:48 UTC, sandeepkosuri commented on clang/include/clang/Basic/DiagnosticDriverKinds.td
> +  "enabling optimizations with sanitizers may potentially reduce effectiveness">;
```suggestion
  "enabling optimizations may reduce the effectiveness of sanitizers">;
```

2024-06-27 08:48 UTC, sandeepkosuri commented on clang/test/Driver/fsanitize.c
> +// CHECK-SAN-OPT-WARN: warning: enabling optimizations with sanitizers may potentially reduce effectiveness
```suggestion
// CHECK-SAN-OPT-WARN: warning: enabling optimizations may reduce the effectiveness of sanitizers
```

2024-06-27 15:34 UTC, Ritanya-B-Bharadwaj commented
ping

2024-06-27 15:49 UTC, AaronBallman reviewed
I'm not certain we should issue a diagnostic when optimizations are enabled with sanitizers. For example, there is [explicit documentation that users *should* use `-O1` with address sanitizer](https://github.com/google/sanitizers/wiki/AddressSanitizer#using-addresssanitizer) and [similarly, users should use `-O2` with the thread sanitizer](https://github.com/google/sanitizers/wiki/ThreadSanitizerCppManual#usage).

So perhaps this is a matter that's better handled with documentation so we can explain the tradeoffs to users?

2024-06-29 17:16 UTC, MaskRay commented
I agree that we should not add a driver diagnostic.
Using sanitizers with -O2/-O3 is pretty common, especially when user programs are so large that -O0 is too slow or does not build at all.
I think msan is the most affected sanitizer which will detect fewer bugs.

2024-07-14 20:28 UTC, MaskRay requested changes
.

2025-03-06 05:16 UTC, closed without merging