[lldb] Fix SBAddressRange validation checks.
llvm/llvm-project pull request #95997
Opened 2024-06-18 21:43 UTC by mbucko

2024-06-18 23:00 UTC, clayborg approved these changes

2024-06-20 16:15 UTC, JDevlieghere requested changes
This class behaves quite differently from other SB API classes. Normally, the opaque pointer can be cleared to release the potentially more resource heavy private counterpart. `AddressRange` is a pretty simple class, so I understand that it makes things easier if we guarantee the pointer is always valid, but it is somewhat of a surprise. 

Personally, I think consistency beats the small advantage of not having to check the pointer. If we want to stick to this approach, I'd like to see an assert that makes it clear that in this class, we have a precondition that the pointer is always valid: 

```
assert(m_opaque_up && "opaque pointer must always be valid");
```

2024-06-20 16:22 UTC, mbucko commented
> This class behaves quite differently from other SB API classes. Normally, the opaque pointer can be cleared to release the potentially more resource heavy private counterpart. `AddressRange` is a pretty simple class, so I understand that it makes things easier if we guarantee the pointer is always valid, but it is somewhat of a surprise.
> 
> Personally, I think consistency beats the small advantage of not having to check the pointer. If we want to stick to this approach, I'd like to see an assert that makes it clear that in this class, we have a precondition that the pointer is always valid:
> 
> ```
> assert(m_opaque_up && "opaque pointer must always be valid");
> ```

So you're ok with keeping the code as is plus adding the asserts?

2024-06-20 17:26 UTC, clayborg commented
> This class behaves quite differently from other SB API classes. Normally, the opaque pointer can be cleared to release the potentially more resource heavy private counterpart. `AddressRange` is a pretty simple class, so I understand that it makes things easier if we guarantee the pointer is always valid, but it is somewhat of a surprise.
> 
> Personally, I think consistency beats the small advantage of not having to check the pointer. If we want to stick to this approach, I'd like to see an assert that makes it clear that in this class, we have a precondition that the pointer is always valid:
> 
> ```
> assert(m_opaque_up && "opaque pointer must always be valid");
> ```

For simple classes, there is no need to clear the unique pointer, so I like this approach for small classes.

We can use the assert in a new protected `ref()` method:
```
lldb_private::AddressRange & SBAddressRange::ref() {
  assert(m_opaque_up && "opaque pointer must always be valid");
  return *m_opaque_up;
}
```
And then have everything that accesses `m_opaque_up` use the `ref()` function. It is similar to other classes and makes the code nicer when we don't see direct uses of `m_opaque_up`

2024-06-20 17:45 UTC, JDevlieghere approved these changes

2024-06-20 18:13 UTC, clayborg approved these changes

2024-06-21 15:24 UTC, merged