[GlobalISel][ARM] Selection of G_CONSTANT using constant pool
llvm/llvm-project pull request #96225
Opened 2024-06-20 18:47 UTC by spavloff

Some constants cannot be represented as immediate operands. They can be loaded from constant pool. This change implement selection of such constants in the same way as the DAG selector uses.

2024-06-21 17:18 UTC, arsenm requested changes
This shouldn't really be a matter for selection, but legalization. The default lower operation for constant/fconstant is already to emit load from constant pool

2024-06-24 06:16 UTC, spavloff commented
This implementation used the same approach as in AArch64, where loading from constant pool replaces G_CONSTANT in selector: https://github.com/llvm/llvm-project/blob/fec1b6f9d3cf5347b67ffb2078c995eb496acf47/llvm/lib/Target/AArch64/GISel/AArch64InstructionSelector.cpp#L2580

I could not find a use of constant pool in ARM global selector. In the DAG selector the replacement is made by the specific selecton code: https://github.com/llvm/llvm-project/blob/a9ac31910db3975d5e92a6265ab29dafd6a4691d/llvm/lib/Target/ARM/ARMISelDAGToDAG.cpp#L3699)

The difficulty of using constant pool loading at legalization stage is the specific nature of the legality predicate. In this case it should be based on the value of operand, but `LegalizerInfo::getAction(const LegalityQuery &Query)` does not provide such info. A possible solution is extending `LegalityQuery` with the information about constant arguments. Another way is to modify `LegalizerHelper::legalizeInstrStep` so that it allow selection of other legalization actions if some legalization step is failed. Both ways however require substantial changes and it is not clear if they agree with GlobalISel design. If you have ideas how to the legalization could be implemented, could you please share?

2024-06-24 09:37 UTC, arsenm commented
You can custom lower, check the value and then use the LegalizerHelper lower implementation if you need to expand it. Alternatively, we can make the default lower implementation for constant check the isImmLegal or whatever it's called TargetLowering hook

2024-07-10 19:14 UTC, spavloff commented
The alternative implementation is provided in #98308, it uses legalization instead of instruction selection.

2024-10-14 09:41 UTC, spavloff commented
Abandon in favour of https://github.com/llvm/llvm-project/pull/98308.

2024-10-14 09:41 UTC, closed without merging