[lld][AArch64][ELF][PAC] Support `.relr.auth.dyn` section
llvm/llvm-project pull request #96496
Opened 2024-06-24 14:50 UTC by kovdan01

This re-applies #87635 with fix of issue described in https://github.com/llvm/llvm-project/pull/87635#issuecomment-2155318065.

We need to discard `rel(a).dyn` section when output is a relocatable object file. The section is always empty in such a case (as well as both auth and regular relr sections), and emitting that resulted in its `sh_info` equal to 0. Section with zero index is always a NULL section according to ELF spec, and lld is unable to run `ObjFile<ELFT>::getRelocTarget` against relocation section with `sh_info` equal to zero (the ELF spec does not seem to define behavior for such a corner case). This is only an issue with relocatable object file output - having `sh_info` equal to zero for shared objects is OK.

Original commit description below.

Support `R_AARCH64_AUTH_RELATIVE` relocation compression as described in https://github.com/ARM-software/abi-aa/blob/main/pauthabielf64/pauthabielf64.rst#relocation-compression.

2024-06-25 07:10 UTC, zeroomega commented
I confirm it no longer generate empty `.rel.dyn` or invalid sh_info on REL section when building an relocatable object file.

2024-06-28 00:00 UTC, zeroomega approved these changes
LGTM from my point of view. I compared it with the original implementation in #87635 and confirm the empty and invalid `.rel.dyn` section in relocatable object file was fixed. 
Please wait for @MaskRay's approval before landing it.

2024-06-29 00:39 UTC, MaskRay requested changes
`.rela.dyn` is currently created outside of the `config->hasDynSymTab` condition.
In relocatable links, `.rela.dyn` will be discarded by `removeUnusedSyntheticSections`.
The reverted `.relr.auth.dyn` patch incorrectly retained the empty `.relr.dyn`.

I think we should suppress the creation of `.rela.dyn` in the first place.
I will try updating `createSyntheticSections`.

The `!config->relocatable` condition in `removeUnusedSyntheticSections` in this PR can then be dropped.

2024-06-29 00:49 UTC, MaskRay commented on lld/test/ELF/aarch64-reloc-pauth.s
> +# RUN: ld.lld -r -z pack-relative-relocs empty-rela.o -o empty-rela-relocatable
`-o empty-rela.ro`

2024-06-29 12:06 UTC, kovdan01 commented
> I think we should suppress the creation of `.rela.dyn` in the first place.
> I will try updating `createSyntheticSections`.

@MaskRay I agree that it's better not to construct the section at all if we know it's not needed than construct an empty one and then delete it, thanks for implementing that it ebc123e0793a1cbcb69b4af1548e339e018ffff2.

> The `!config->relocatable` condition in `removeUnusedSyntheticSections` in this PR can then be dropped.

Deleted, thanks. I also updated the PR description.

2024-06-29 12:07 UTC, kovdan01 commented on lld/test/ELF/aarch64-reloc-pauth.s
> +# RUN: ld.lld -r -z pack-relative-relocs empty-rela.o -o empty-rela-relocatable
Renamed, see 87d2e3f1894a3296a04f79a69385daabbc92884e

2024-06-29 16:35 UTC, MaskRay approved these changes

2024-06-29 17:07 UTC, kovdan01 commented
Pushed a merge commit to re-trigger buildkite job which failed to unrelated reasons

2024-06-29 17:58 UTC, merged