mlir/Presburger: strip dependency on MLIRSupport
llvm/llvm-project pull request #96517
Opened 2024-06-24 17:13 UTC by artagnon

Strip the Presburger library's dependency on the MLIR Support library, as well as the headers, in the interest of making it leaner.

This patch is part of a project to move the Presburger library into LLVM.

2024-06-24 17:31 UTC, Groverkss requested changes
Can we depend on LLVMSupport instead?

2024-06-24 17:35 UTC, artagnon commented
We already are depending on LLVMSupport implicitly (add_mlir_library in MLIR CMake already includes relevant LLVM libs). Further, we do include a lot of LLVM Support headers already.

2024-06-24 17:38 UTC, artagnon commented
Further, the only reason we depend on MLIRSupport is for TypeID.cpp, which is a completely unnecessary dependency. The only other Support headers we depend are LLVM.h and LogicalResult.h, which are also eliminated trivially.

2024-06-29 07:36 UTC, nikic approved these changes
LGTM

2024-06-29 07:36 UTC, nikic commented on mlir/lib/Analysis/Presburger/IntegerRelation.cpp
> +      bool ret = gaussianEliminateVar(pos);
You still need the `(void) ret` here, or `[[maybe_unused]]`, otherwise it will warn in release builds.

2024-06-29 11:23 UTC, merged

2024-06-30 16:27 UTC, Superty reviewed
Thanks for your patch. Please fix these two issues:
1. many comments refer to `returns failure if...` or `returns success if...`. Please fix to say `returns true/false`.
2. some functions don't say anything about the return but the type of LogicalResult previously made it clear that the return denotes success/failure, which now becomes unclear. Please add a line to the header doc in such cases mentioning that the function returns true if successful.

2024-06-30 21:04 UTC, joker-eph commented
> some functions don't say anything about the return but the type of LogicalResult previously made it clear that the return denotes success/failure, which now becomes unclear. Please add a line to the header doc in such cases mentioning that the function returns true if successful.

Better: can we please keep LogicalResult!! (move the header to LLVMSupport instead)