Fix flake in TestZerothFrame.py
llvm/llvm-project pull request #96685
Opened 2024-06-25 19:26 UTC by kendalharland

This test is currently flaky on a local Windows amd64 build.

If we print lldb's inputs and outputs while running, we can see that the breakpoints are always being set correctly, and always being hit:

```sh
runCmd: breakpoint set -f "main.c" -l 2
output: Breakpoint 1: where = a.out`func_inner + 1 at main.c:2:9, address = 0x0000000140001001

runCmd: breakpoint set -f "main.c" -l 7
output: Breakpoint 2: where = a.out`main + 17 at main.c:7:5, address = 0x0000000140001021

runCmd: run
output: Process 52328 launched: 'C:\workspace\llvm-project\llvm\build\lldb-test-build.noindex\functionalities\unwind\zeroth_frame\TestZerothFrame.test_dwarf\a.out' (x86_64)
Process 52328 stopped
* thread #1, stop reason = breakpoint 1.1
    frame #0: 0x00007ff68f6b1001 a.out`func_inner at main.c:2:9
   1    void func_inner() {
-> 2        int a = 1;  // Set breakpoint 1 here
                ^
   3    }
   4
   5    int main() {
   6        func_inner();
   7        return 0; // Set breakpoint 2 here
```

However, sometimes the backtrace printed in this test shows that the process is stopped inside NtWaitForWorkViaWorkerFactory from `ntdll.dll`:

```sh
Backtrace at the first breakpoint:
frame #0: 0x00007ffecc7b3bf4 ntdll.dll`NtWaitForWorkViaWorkerFactory + 20
frame #1: 0x00007ffecc74585e ntdll.dll`RtlClearThreadWorkOnBehalfTicket + 862
frame #2: 0x00007ffecc3e257d kernel32.dll`BaseThreadInitThunk + 29
frame #3: 0x00007ffecc76af28 ntdll.dll`RtlUserThreadStart + 40
```

If we print the list of threads each time the test is run, we notice that threads are sometimes in a different order, within `process.threads`:

```sh
Thread 0: thread #4: tid = 0x9c38, 0x00007ffecc7b3bf4 ntdll.dll`NtWaitForWorkViaWorkerFactory + 20
Thread 1: thread #2: tid = 0xa950, 0x00007ffecc7b3bf4 ntdll.dll`NtWaitForWorkViaWorkerFactory + 20
Thread 2: thread #1: tid = 0xab18, 0x00007ff64bc81001 a.out`func_inner at main.c:2:9, stop reason = breakpoint 1.1
Thread 3: thread #3: tid = 0xc514, 0x00007ffecc7b3bf4 ntdll.dll`NtWaitForWorkViaWorkerFactory + 20

Thread 0: thread #3: tid = 0x018c, 0x00007ffecc7b3bf4 ntdll.dll`NtWaitForWorkViaWorkerFactory + 20
Thread 1: thread #1: tid = 0x85c8, 0x00007ff7130c1001 a.out`func_inner at main.c:2:9, stop reason = breakpoint 1.1
Thread 2: thread #2: tid = 0xf344, 0x00007ffecc7b3bf4 ntdll.dll`NtWaitForWorkViaWorkerFactory + 20
Thread 3: thread #4: tid = 0x6a50, 0x00007ffecc7b3bf4 ntdll.dll`NtWaitForWorkViaWorkerFactory + 20
```

We're interested in whichever thread is executing `a.out`. If we print more info, we can see that this thread always has an `IndexID` of 1 regardless of where it appars in `process.threads`:

```sh
Thread 0: thread #3: tid = 0x2474, 0x00007ffecc7b3bf4 ntdll.dll`NtWaitForWorkViaWorkerFactory + 20
-- GetName:
-- GetQueueName: None
-- GetQueueID: 0
-- GetIndexId: 3
Thread 1: thread #2: tid = 0x2864, 0x00007ffecc7b3bf4 ntdll.dll`NtWaitForWorkViaWorkerFactory + 20
-- GetName:
-- GetQueueName: None
-- GetQueueID: 0
-- GetIndexId: 2
Thread 2: thread #4: tid = 0x9c90, 0x00007ffecc7b3bf4 ntdll.dll`NtWaitForWorkViaWorkerFactory + 20
-- GetName:
-- GetQueueName: None
-- GetQueueID: 0
-- GetIndexId: 4
Thread 3: thread #1: tid = 0xebbc, 0x00007ff643331001 a.out`func_inner at main.c:2:9, stop reason = breakpoint 1.1
-- GetName:
-- GetQueueName: None
-- GetQueueID: 0
-- GetIndexId: 1
```

By switching from `process.GetThreadAtIndex` to
`process.GetThreadByIndex` we consistently retrieve the correct thread.

This raises a few more questions that might lead to a different followup solution:

1. Why does our target thread always have an `IndexID` of 1? Why not 0 or any other value?
2. Why is `process.threads` non-deterministically ordered?

2024-06-25 21:16 UTC, bulbazord requested changes
Instead of assuming the thread's index or index ID, it might be a good idea to have a little helper method that can look through the inferior's threads to find the thread with the property that we care about. In this case, we're looking for the thread that's stopped in a specific module (`a.out` in this case).

Concurrency and thread order is not guaranteed to be stable, even if in practice they end up being that way on some platforms. The less we can rely on specific indices or IDs that "should" be correct, the better.

2024-06-25 21:37 UTC, kendalharland commented
> Instead of assuming the thread's index or index ID, it might be a good idea to have a little helper method that can look through the inferior's threads to find the thread with the property that we care about. In this case, we're looking for the thread that's stopped in a specific module (`a.out` in this case).
> 
> Concurrent execution and thread order is not guaranteed to be stable between runs, even if in practice they end up being that way on some platforms. The less we can rely on specific indices or IDs that "should" be correct, the better.

Sounds reasonable. I'll work that out with a helper method and resend for review once I upload a new commit. @bulbazord any idea how I can access the module from the `SBThread` object? I'm having trouble finding the right API.

2024-06-26 01:42 UTC, JDevlieghere commented
> Sounds reasonable. I'll work that out with a helper method and resend for review once I upload a new commit. @bulbazord any idea how I can access the module from the `SBThread` object, to compare it against the name `a.out`? I'm having trouble finding the right API.

The module is a property of the target, so you could do:

```
process = thread.GetProcess()
target = process.GetTarget()
module = target.GetModuleAtIndex(0)
```

or you can create an ExecutionContext from the thread, and get the target from that:

```
exe_ctx = SBExecutionContext(thread)
exe_ctx.target.GetModuleAtIndex(0)
```

2024-06-26 08:58 UTC, labath commented
The thread that you care about is stopped at a breakpoint, right?
If so, then you can use the `lldbutil.get_threads_stopped_at_breakpoint` utility to find it...

2024-06-27 16:59 UTC, kendalharland commented
> The thread that you care about is stopped at a breakpoint, right? If so, then you can use the lldbutil.get_threads_stopped_at_breakpoint utility to find it...

Thanks, this eventually led to me what I think is the most obvious solution: We can just set the breakpoints in this test while holding onto to the `SBBreakpoint` objects, and then fetch the associated thread from those breakpoints later, and compare the thread's frames' currently line numbers.

Thanks @JDevlieghere and @bulbazord for the additional suggestions!

2024-06-28 07:19 UTC, labath approved these changes
This should be fine, although looking at the test case again, I think that even simply replacing `process.GetThreadAtIndex(0)` with `self.thread()` should be enough. `self.thread()` returns the "selected" thread and lldb should always be selecting the thread which has stopped "for a reason" (e.g. a breakpoint) and not a random (or first) thread in the process.

2024-06-28 20:05 UTC, kendalharland commented
> This should be fine, although looking at the test case again, I think that even simply replacing process.GetThreadAtIndex(0) with self.thread() should be enough. self.thread() returns the "selected" thread and lldb should always be selecting the thread which has stopped "for a reason" (e.g. a breakpoint) and not a random (or first) thread in the process.

This also works. Agreed it's much better. Ty for the suggestion! Updated.

2024-07-01 06:43 UTC, labath approved these changes
Looks good. Are you able to merge this on your own?

2024-07-01 16:32 UTC, kendalharland commented
> Looks good. Are you able to merge this on your own?

Nope, I'll need someone with write access to do it.

2024-07-02 07:21 UTC, labath approved these changes

2024-07-02 07:46 UTC, labath commented
> > Looks good. Are you able to merge this on your own?
> 
> Nope, I'll need someone with write access to do it.

Sounds good. Can you just patch the formatter changes in, and then I'll submit it.

@bulbazord, if you don't respond, I'm going to assume that new version addresses your comments as well.

2024-07-02 19:47 UTC, bulbazord commented
Yes, looks good to me. Thanks for taking the time! :)

2024-07-02 22:14 UTC, kendalharland commented
Sure thing, I hadn't hooked up the formatter yet so I'll run it and reupload. Thanks for the reviews!

2024-07-03 18:42 UTC, kendalharland commented
Applied formatter patch and rebased onto main

2024-07-03 19:10 UTC, kendalharland commented
Apologies, I push the wrong commits to this PR and just had the fix them up. Should be good to go.

2024-07-05 15:50 UTC, kendalharland commented
I'll need help merging this since I don't have write access to the repo.

2024-07-08 10:20 UTC, labath approved these changes

2024-07-08 10:20 UTC, merged