[libc] Add `Scrt1.o` to `startup_components`
llvm/llvm-project pull request #97497
Opened 2024-07-03 00:44 UTC by izaakschroeder

Needed for `-fpie` targets. Don't know if this is safe or not... but it seems to run compiled C++ executables.

2024-07-03 00:45 UTC, izaakschroeder commented
/cc @michaelrj-google @jhuber6 @Intue

2024-07-03 15:23 UTC, SchrodingerZhu commented
cc @MaskRay . I am not sure directly creating `crt1` to `Scrt1` based on `crt1` will work? If it does work for current configuration, it can be easily broken in the future. `-pie`, `-static`, `-static-pie` should have different relocation policies.

2024-07-03 18:45 UTC, izaakschroeder commented
@SchrodingerZhu @MaskRay is there a simple path forward I can take, even if temporarily, to keep the ball moving? Like adding a `.start-pie` / `.tls-pie` (based on `.start` and `.tls` respectively) or something that is a copy but that could easily be modified in the future?

2024-07-03 19:51 UTC, MaskRay commented
> cc @MaskRay . I am not sure directly creating `crt1` to `Scrt1` based on `crt1` will work? If it does work for current configuration, it can be easily broken in the future. `-pie`, `-static`, `-static-pie` should have different relocation policies.

I am not familiar with the build system, but you can create `Scrt1.o` and make `crt1.o` a symlink.
For `-static-pie`, `rcrt1.o` is needed and it needs to resolve relative relocations (also IRELATIVE if ifunc is supported).

2024-07-03 21:11 UTC, jhuber6 commented
> > cc @MaskRay . I am not sure directly creating `crt1` to `Scrt1` based on `crt1` will work? If it does work for current configuration, it can be easily broken in the future. `-pie`, `-static`, `-static-pie` should have different relocation policies.
> 
> I am not familiar with the build system, but you can create `Scrt1.o` and make `crt1.o` a symlink. For `-static-pie`, `rcrt1.o` is needed and it needs to resolve relative relocations (also IRELATIVE if ifunc is supported).

Do you know where the differences between these is documented?

2024-07-03 21:48 UTC, MaskRay commented
> > > cc @MaskRay . I am not sure directly creating `crt1` to `Scrt1` based on `crt1` will work? If it does work for current configuration, it can be easily broken in the future. `-pie`, `-static`, `-static-pie` should have different relocation policies.
> > 
> > 
> > I am not familiar with the build system, but you can create `Scrt1.o` and make `crt1.o` a symlink. For `-static-pie`, `rcrt1.o` is needed and it needs to resolve relative relocations (also IRELATIVE if ifunc is supported).
> 
> Do you know where the differences between these files is documented?

They are undocumented. One needs to investigate whether other libc implementations do...

2024-07-03 21:50 UTC, jhuber6 commented
> 
> They are undocumented. One needs to investigate whether other libc implementations do...

Good to know my failing to find anything online wasn't a skill issue, thanks.

2024-10-15 16:38 UTC, nickdesaulniers requested changes
Throwing a "minus one" on this for now until we better understand if/why this is necessary.

2026-04-16 10:21 UTC, kaladron commented
I'm going to close this PR as being too fast of an implementation on something that's not quite needed yet.  (If this is blocking something, please re-open and let me know!)

2026-04-16 10:21 UTC, closed without merging