[libc] Add link.h and elf.h
llvm/llvm-project pull request #97504
Opened 2024-07-03 01:16 UTC by izaakschroeder

Builds on https://github.com/llvm/llvm-project/pull/97501 and completes the effort to compile `libunwind` + `libc` without baremetal mode. This is part of https://github.com/llvm/llvm-project/issues/97191.

2024-07-03 01:17 UTC, izaakschroeder commented
/cc @michaelrj-google @jhuber6 @SchrodingerZhu

2024-07-03 15:19 UTC, SchrodingerZhu requested changes
LGTM but need a small fix

2024-07-04 03:33 UTC, SchrodingerZhu approved these changes

2024-07-04 03:33 UTC, izaakschroeder commented on libc/src/link/dl_iterate_phdr.cpp
> +//----------------------------------===//
Done!

2024-07-19 05:26 UTC, petrhosek commented on libc/src/dlfcn/dladdr.cpp
> +// TODO(@izaakschroeder): https://github.com/llvm/llvm-project/issues/97929
The format I've seen more commonly used in LLVM is `TODO(#97929): More details...`.

2024-10-08 17:31 UTC, nickdesaulniers commented
What's the status of this PR? Should it be closed?

2025-04-01 17:23 UTC, closed without merging

2025-04-01 17:23 UTC, michaelrj-google commented
Closing as not superseded, `link` and `elf` headers are available.