[clang-doc] fix path bug introduced by asset test
llvm/llvm-project pull request #97540
Opened 2024-07-03 08:45 UTC by PeterChou1

Fixes https://github.com/llvm/llvm-project/issues/97507

this patch fixes the bug by copying assets to the correct repository for windows builds

2024-07-03 16:07 UTC, ilovepi commented
seems to fail on windows CI.

2024-07-03 16:07 UTC, dyung requested changes
I believe (and the pre-merge testing seems to validate my belief) that this breaks the case where you build with ninja + Visual Studio. Also, I believe the Xcode generator is similar to the Visual Studio generator in that they both are multi-config generators, so that configuration is likely failing as well.

2024-07-03 17:53 UTC, PeterChou1 commented
> I believe (and the pre-merge testing seems to validate my belief) that this breaks the case where you build with ninja + Visual Studio. Also, I believe the Xcode generator is similar to the Visual Studio generator in that they both are multi-config generators, so that configuration is likely failing as well.

@ilovepi 

I don't have access to a mac could you run build for checking clang-doc in xcode to see if it reports any errors?

2024-07-03 17:55 UTC, PeterChou1 commented on clang-tools-extra/clang-doc/tool/CMakeLists.txt
> +if(MSVC)
You're right this bug is specific to generators used I've update the code

2024-07-03 19:10 UTC, ilovepi commented
> > I believe (and the pre-merge testing seems to validate my belief) that this breaks the case where you build with ninja + Visual Studio. Also, I believe the Xcode generator is similar to the Visual Studio generator in that they both are multi-config generators, so that configuration is likely failing as well.
> 
> @ilovepi
> 
> I don't have access to a mac could you run build for checking clang-doc in xcode to see if it reports any errors?

while I have access to a mac, I don't have the ability to use XCode due to company policy.

2024-07-03 19:31 UTC, petrhosek commented
We already have set of CMake variables that we use to refer to `bin` or `lib` directory which account for various configurations: https://github.com/llvm/llvm-project/blob/c02e8f762a410e55581866c43636efcd6504c1bd/llvm/CMakeLists.txt#L446-L467

I think we should introduce another one for the `share` directory and use that.

2024-07-03 20:06 UTC, PeterChou1 commented
> We already have set of CMake variables that we use to refer to `bin` or `lib` directory which account for various configurations:
> 
> https://github.com/llvm/llvm-project/blob/c02e8f762a410e55581866c43636efcd6504c1bd/llvm/CMakeLists.txt#L446-L467
> 
> I think we should introduce another one for the `share` directory and use that.

I've introduced a variable in the root cmakelists.txt I'm not very familiar with cmake though I'm sure if this is the correct approach

2024-07-03 20:52 UTC, PeterChou1 commented
@dyung I do not have access to mac for xcode could you provide me with a log of the build failure on xcode

2024-07-03 21:29 UTC, dyung commented
> @dyung I do not have access to mac for xcode could you provide me with a log of the build failure on xcode

```
% python3 ~/src/git/llvm-dyung/build/Debug/bin/llvm-lit -v basic-project.test
-- Testing: 1 tests, 1 workers --
FAIL: Clang Tools :: clang-doc/basic-project.test (1 of 1)
******************** TEST 'Clang Tools :: clang-doc/basic-project.test' FAILED ********************
Exit Code: 1

Command Output (stdout):
--
Emiting docs in html format.

--
Command Output (stderr):
--
RUN: at line 1: rm -rf /Users/dyung/src/git/llvm-dyung/build/tools/clang/tools/extra/test/clang-doc/Output/basic-project.test.tmp && mkdir -p /Users/dyung/src/git/llvm-dyung/build/tools/clang/tools/extra/test/clang-doc/Output/basic-project.test.tmp/docs /Users/dyung/src/git/llvm-dyung/build/tools/clang/tools/extra/test/clang-doc/Output/basic-project.test.tmp/build
+ rm -rf /Users/dyung/src/git/llvm-dyung/build/tools/clang/tools/extra/test/clang-doc/Output/basic-project.test.tmp
+ mkdir -p /Users/dyung/src/git/llvm-dyung/build/tools/clang/tools/extra/test/clang-doc/Output/basic-project.test.tmp/docs /Users/dyung/src/git/llvm-dyung/build/tools/clang/tools/extra/test/clang-doc/Output/basic-project.test.tmp/build
RUN: at line 2: sed 's|$test_dir|/Users/dyung/src/git/llvm-dyung/clang-tools-extra/test/clang-doc|g' /Users/dyung/src/git/llvm-dyung/clang-tools-extra/test/clang-doc/Inputs/basic-project/database_template.json > /Users/dyung/src/git/llvm-dyung/build/tools/clang/tools/extra/test/clang-doc/Output/basic-project.test.tmp/build/compile_commands.json
+ sed 's|$test_dir|/Users/dyung/src/git/llvm-dyung/clang-tools-extra/test/clang-doc|g' /Users/dyung/src/git/llvm-dyung/clang-tools-extra/test/clang-doc/Inputs/basic-project/database_template.json
RUN: at line 3: clang-doc --format=html --output=/Users/dyung/src/git/llvm-dyung/build/tools/clang/tools/extra/test/clang-doc/Output/basic-project.test.tmp/docs --executor=all-TUs /Users/dyung/src/git/llvm-dyung/build/tools/clang/tools/extra/test/clang-doc/Output/basic-project.test.tmp/build/compile_commands.json
+ clang-doc --format=html --output=/Users/dyung/src/git/llvm-dyung/build/tools/clang/tools/extra/test/clang-doc/Output/basic-project.test.tmp/docs --executor=all-TUs /Users/dyung/src/git/llvm-dyung/build/tools/clang/tools/extra/test/clang-doc/Output/basic-project.test.tmp/build/compile_commands.json
default index.js file missing at /Users/dyung/src/git/llvm-dyung/build/Debug/bin/../share/clang-doc/index.js

```

2024-07-04 01:35 UTC, PeterChou1 commented
I've added the install path using a platform agnostic variable LLVM_RUNTIME_OUTPUT_INTDIR which should fix build path problems

2024-07-05 14:50 UTC, ilovepi approved these changes

2024-07-05 19:27 UTC, merged

2024-07-06 07:59 UTC, mgorny commented
This change broke standalone clang builds against installed LLVM, since `LLVM_SHARE_OUTPUT_INTDIR` is not exported by LLVM and therefore resolves to an empty path:

```
ninja: error: mkdir(/clang-doc): Permission denied
ninja: build stopped: .
```

Why are you even declaring the directory inside LLVM when it's only used by Clang?

Please revert.

2024-07-10 06:50 UTC, mgorny commented
Thank you.