[PowerPC] Support conversion between f16 and f128.
llvm/llvm-project pull request #97677
Opened 2024-07-04 05:19 UTC by EsmeYi

This patch enables conversion between f16 and f128, expanding on pre-Power9 targets and using HW instructions on Power9.
It fixes https://github.com/llvm/llvm-project/issues/92866

2024-07-09 08:15 UTC, tgross35 commented
Should tests at [`f128-conv.ll`](https://github.com/llvm/llvm-project/blob/ad82d1c53f089937c05af11ff45798ceb5ca894e/llvm/test/CodeGen/PowerPC/f128-conv.ll) or [`fp128-libcalls.ll`](https://github.com/llvm/llvm-project/blob/ad82d1c53f089937c05af11ff45798ceb5ca894e/llvm/test/CodeGen/PowerPC/fp128-libcalls.ll) be updated?

2024-07-23 06:17 UTC, efriedma-quic requested changes
For truncation, if you convert f128->f64->f16, you'll round twice, and therefore get the wrong result in some cases.  You need to ensure you only round once.

2024-07-25 05:23 UTC, EsmeYi commented
> For truncation, if you convert f128->f64->f16, you'll round twice, and therefore get the wrong result in some cases. You need to ensure you only round once.

Thanks Eli @efriedma-quic ! This is a great find. I just realized that the intermediate rounding during the stepwise conversion (f128->f64->f16) can produce a different result compared to the direct conversion (`f128->f16).

2024-07-25 05:47 UTC, EsmeYi commented
> Should tests at [`f128-conv.ll`](https://github.com/llvm/llvm-project/blob/ad82d1c53f089937c05af11ff45798ceb5ca894e/llvm/test/CodeGen/PowerPC/f128-conv.ll) or [`fp128-libcalls.ll`](https://github.com/llvm/llvm-project/blob/ad82d1c53f089937c05af11ff45798ceb5ca894e/llvm/test/CodeGen/PowerPC/fp128-libcalls.ll) be updated?

Thank you @tgross35. Sorry that I missed the comment before. I've updated the 2 tests and removed llvm/test/CodeGen/PowerPC/f16-to-from-f128.ll, since it was redundant then.

2024-08-08 06:15 UTC, EsmeYi commented
Gentle ping.

2024-08-20 01:30 UTC, chenzheng1030 approved these changes
Looks reasonable to me except some nits which can be addressed in the merge commit. Thanks for fixing this.

2024-08-20 01:30 UTC, chenzheng1030 commented on llvm/test/CodeGen/PowerPC/f128-conv.ll
> +define fp128 @ext(half %a) unnamed_addr {
nit: Is the `unnamed_addr` needed?

2024-08-20 01:30 UTC, chenzheng1030 commented on llvm/test/CodeGen/PowerPC/f128-conv.ll
> +  %0 = fptrunc fp128 %a to half
nit: We'd better avoid the unnamed variable names, like `%0`. (Suggested by https://llvm.org/docs/TestingGuide.html#writing-new-regression-tests)

2024-08-20 01:30 UTC, chenzheng1030 commented on llvm/lib/Target/PowerPC/PPCISelLowering.cpp
> +  setTruncStoreAction(MVT::f128, MVT::f16, Expand);
nit: could you please add a comment here why we can not use PWR9 instructions to do the conversion.

2025-03-02 11:43 UTC, tgross35 commented
@EsmeYi are you able to get this over the line? Looks like it just needs a few small tweaks.

2025-03-06 18:33 UTC, lei137 commented
Commandeering this patch to get this feature in.
https://github.com/llvm/llvm-project/pull/130158

2025-03-06 18:33 UTC, closed without merging