[llvm] Fix the MCSubtargetInfo used for module-level assembly.
llvm/llvm-project pull request #97685
Opened 2024-07-04 07:22 UTC by chrisnc

Provide both the default target CPU and default target features from the
module's context, rather than empty strings.

Fixes #61991.

2024-07-04 07:46 UTC, chrisnc commented
`test.c`

```c
asm("vmsr fpexc, r0");
```

Without fix:

```bash
$ bin/clang -target arm-none-eabi test.c -c -flto=thin -mcpu=cortex-r4
<inline asm>:1:1: error: instruction requires: VFP2
    1 | vmsr fpexc, r0
      | ^
1 error generated.

$ bin/clang -target arm-none-eabi test.c -c -flto=thin -mcpu=cortex-r5
<inline asm>:1:1: error: instruction requires: VFP2
    1 | vmsr fpexc, r0
      | ^
1 error generated.
```

With fix, using `-mcpu=cortex-r5` (which implies FPU support, while `cortex-r4` does not), does not emit an error:
```bash
$ bin/clang -target arm-none-eabi test.c -c -flto=thin -mcpu=cortex-r4
<inline asm>:1:1: error: instruction requires: VFP2
    1 | vmsr fpexc, r0
      | ^
1 error generated.

$ bin/clang -target arm-none-eabi test.c -c -flto=thin -mcpu=cortex-r5
```

2024-07-04 08:00 UTC, chrisnc commented
Credit to https://github.com/llvm/llvm-project/issues/61991#issuecomment-2207148632 @Dirbaio for finding where the problem was.

Hopefully this is not a breaking change for anything and the fix is this simple...

2024-07-05 18:41 UTC, efriedma-quic commented
The idea here makes sense, but the API in question is likely to change, so I'd rather not add new uses of that API until we've sorted that out.  See https://discourse.llvm.org/t/functions-generated-by-function-createwithdefaultattr-should-respect-target-features/79838 .

2024-07-05 18:46 UTC, MaskRay requested changes
Request changes since the ABI will change. My summary:

<https://github.com/llvm/llvm-project/pull/96721> implemented a strategy by storing the target features in `LLVMContext`, which is not serialized.
`Function::createWithDefaultAttr` will load the target features from `LLVMContext`.

While 96721 works well, there is a drawback that the generate module from the LTO pre-link compilation does not contain sufficient information.
Running `opt` without the correct target features would not mimick Clang .
To address this drawback, we can use module flags metadata that is dropped during merging.

2024-07-05 19:02 UTC, chrisnc commented
Oh! I did not notice that the interfaces I'm using only appeared a week ago. Thanks for the additional context.

> use module flags metadata

Is this something I can do now at this call-site, or something that needs more iteration on what the correct way to store/retrieve this information from various phases should be?

2024-07-30 15:06 UTC, chrisnc commented
Hi @MaskRay, is https://github.com/llvm/llvm-project/pull/98673 the confirmed direction yet? If so, I'll watch for that to merge and then re-visit this.

2024-07-31 05:47 UTC, MaskRay commented
> Hi @MaskRay, is #98673 the confirmed direction for how this info will be handled? If so, I'll watch for that to merge and then re-visit this.

I think so. Thanks  for waiting :)

2026-02-28 09:17 UTC, chrisnc commented
Hi @MaskRay, I've updated this branch to resolve conflicts and added a test. Can I ask that this be considered now, even though https://github.com/llvm/llvm-project/pull/98673 is still open? The change is very small and solves a real problem that people keep encountering, and should be easy to refactor into the right shape when the intended direction for target feature tracking is ready to land.

2026-03-20 18:41 UTC, chrisnc commented
@MaskRay bump.

2026-03-21 05:26 UTC, MaskRay commented on llvm/lib/Object/ModuleSymbolTable.cpp
unneeded blank line

2026-03-21 05:26 UTC, MaskRay commented
I am leaning toward accepting this. What do other reviewers think?

```
  std::unique_ptr<MCSubtargetInfo> STI(T->createMCSubtargetInfo(
      TT, Context.getDefaultTargetCPU(), Context.getDefaultTargetFeatures()));
```

2026-03-21 18:25 UTC, compnerd commented
I think that it makes sense, we can easily wire the more precise information through, so this is better.

2026-03-21 18:38 UTC, pcc commented
I'd be fine with landing this change now, as it makes things less broken than they are now. For module level asm we arguably need a way of attaching target-cpu and target-features to the asm, which is orthogonal to what my change is doing.

2026-03-21 18:45 UTC, MaskRay approved these changes

2026-03-21 18:46 UTC, MaskRay commented on clang/test/CodeGen/asm-module-fp.ll
> +; REQUIRES: arm-registered-target
Prefer `asm-*` as the prefix to make `asm-*` tests closer in the sorted  list.

2026-03-21 18:59 UTC, nikic requested changes
Isn't https://github.com/llvm/llvm-project/pull/174995 the agreed upon direction to fix this?

2026-03-21 19:22 UTC, pcc commented
> Isn't #174995 the agreed upon direction to fix this?

That change seems to have some problems as I just noted in a comment there. This workaround is simpler at least, and avoids adding unnecessary data to the IR.

2026-03-22 00:12 UTC, chrisnc commented
@MaskRay Thanks for the review! I've addressed your feedback and rebased again.

2026-03-25 03:45 UTC, chrisnc commented
@nikic looks like your "request changes" is blocking. Do you still have concerns?

2026-04-12 20:40 UTC, chrisnc commented
Bump. @nikic

2026-04-23 16:05 UTC, chrisnc commented
Bump. @nikic @MaskRay 
Is there anything still blocking this?

2026-05-14 07:40 UTC, chrisnc commented
Bump.

2026-05-16 08:04 UTC, MaskRay commented
> Bump.

Requires @nikic's approval

2026-06-18 10:55 UTC, nikic commented
> I'd be fine with landing this change now, as it makes things less broken than they are now. For module level asm we arguably need a way of attaching target-cpu and target-features to the asm, which is orthogonal to what my change is doing.

I believe that this is the actually correct way to solve this class of problem, and have implemented it in https://github.com/llvm/llvm-project/pull/204548.

2026-07-03 09:53 UTC, chrisnc commented
Obviated by https://github.com/llvm/llvm-project/pull/204548.

2026-07-03 09:53 UTC, closed without merging