Users/paschalis mpeis/bolt static binary patchelf fix
llvm/llvm-project pull request #97710
Opened 2024-07-04 10:53 UTC by paschalis-mpeis

# DRAFT / WIP: Work In Progress

static binaries fix: don't patch anything that is not in orig text segment

2024-07-09 06:43 UTC, paschalis-mpeis commented
## Minimal Reproducer:
main.c:
```c
int main() { return 0; }
```

```bash
clang main.c -Wl,-q -static -o out
llvm-bolt out -o out.bolt
./out.bolt
```

2024-07-19 09:20 UTC, samolisov commented
As I see, this branch has not been rebased on top of the recently merged changes with the introduction of the `createDummyReturn` function (or the final version of its name).

Please, rebase the branch to distinguish the correct set of changes, what makes the review much simpler.

2024-07-19 09:27 UTC, samolisov approved these changes
LGTM, thank you. Also thanks for the test.

2024-07-19 09:27 UTC, samolisov commented on bolt/test/AArch64/patch-elfstatic-libc.test
Unfortunately, I'm not familiar with the `-static` option and didn't manage to find what exactly it means. Why this option is required here, maybe it applies by default? I see `BC->IsStaticExecutable` in the check you introduced, do they, the option, and the variable's value related? Is `IsStaticExecutable` set to `true` for binaries statically linked with the glibc?

Thank you.

2024-07-23 12:35 UTC, peterwaller-arm commented
Hi, I've filed https://github.com/llvm/llvm-project/issues/100096 to try and capture in detail the issue that this PR is trying to solve.

2024-07-27 12:04 UTC, yota9 requested changes
Hello, please rebase the patch for further review

2024-07-27 12:06 UTC, yota9 commented on bolt/lib/Rewrite/RewriteInstance.cpp
> +      if (BC->IsStaticExecutable && !Function->Aliases.empty() &&
This way the function entry won't be patched either I think? It might also be a problem

2024-08-19 13:58 UTC, paschalis-mpeis commented
In the issue below, it was reached a consensus that BOLT [can reject such cases](https://github.com/llvm/llvm-project/issues/100096#issuecomment-2253322315), therefore I am closing this PR.
- https://github.com/llvm/llvm-project/issues/100096


---

I rebased it (as it was a stacked PR) and added some comments in case someone has such a binary and needs a workaround or a starting point.

2024-08-19 13:58 UTC, closed without merging