Unify handling of operations which are emitted in a deferred way
llvm/llvm-project pull request #97804
Opened 2024-07-05 09:32 UTC by simon-camp

2024-07-05 20:08 UTC, aniragil requested changes
Patch missing a more detailed description?

2024-07-08 09:43 UTC, simon-camp commented on mlir/lib/Target/Cpp/TranslateToCpp.cpp
> +          hasDeferredEmission(&op);
Yes the check looks redundant to me here, I removed it.

2024-07-08 10:54 UTC, aniragil approved these changes
LGTM!

Is the bug fixed the one pointed out [here](https://discourse.llvm.org/t/mlir-emitc-translate-to-c/79647)?

2024-07-10 08:21 UTC, marbre approved these changes
Looks good, just one minor suggestion.

2024-07-10 08:21 UTC, marbre commented on mlir/lib/Target/Cpp/TranslateToCpp.cpp
> +  // materialized.
Maybe rephrase to
```suggestion
  // the way their translation is implemented requires that variables are
  // materialized.
```
or
```suggestion
  // the way their translation is implemented requires to materialize
  // variables.
```
or
```suggestion
  // their translation requires the materialization of variables.
```

2024-07-10 13:24 UTC, merged