[msan] Precommit MSan Arm NEON vst tests
llvm/llvm-project pull request #98247
Opened 2024-07-09 23:44 UTC by thurstond

These tests show that MSan currently does not handle vst (or vld) correctly.

2024-07-09 23:55 UTC, vitalybuka requested changes
Discussed offline, it should be IR tests

2024-07-16 18:15 UTC, thurstond commented
Updated to IR tests

2024-07-17 18:22 UTC, vitalybuka commented on llvm/test/Instrumentation/MemorySanitizer/AArch64/neon_vst.ll
> +  call void @llvm.aarch64.neon.st3.v8i8.p0(<8 x i8> undef, <8 x i8> undef, <8 x i8> undef, ptr %P)
undefs are not fun here, they cause unconditional  `__msan_warning_noreturn`

2024-07-17 18:23 UTC, vitalybuka approved these changes
Please use args instead of undefs

2024-07-17 18:27 UTC, vitalybuka commented on llvm/test/Instrumentation/MemorySanitizer/AArch64/neon_vst.ll
> +  call void @llvm.aarch64.neon.st3.v8i8.p0(<8 x i8> undef, <8 x i8> undef, <8 x i8> undef, ptr %P)
I see that we also have no undef tests, so LGTM

2024-07-17 19:14 UTC, merged