[RISCV] Shrink uses of coalesced vsetvlis
llvm/llvm-project pull request #98286
Opened 2024-07-10 08:41 UTC by lukel97

When we coalesce and delete a vsetvli, we should shrink the LiveInterval of its AVL register now that there is one less use.

This fixes a -verify-machineinstrs assertion in an MIR test case I found while investigating https://github.com/llvm/llvm-project/pull/97264#issuecomment-2218036877. I couldn't recreate this at the LLVM IR level, seemingly because RISCVInsertVSETVLI will just avoid inserting extra vsetvlis that don't need coalesced.

2024-07-10 14:28 UTC, preames requested changes

2024-07-10 14:28 UTC, preames commented on llvm/lib/Target/RISCV/RISCVInsertVSETVLI.cpp
> +      for (MachineOperand &MO : MI->uses())
Calling MI->uses() after MI->eraseFromParent() is definitely unsafe.

2024-07-11 14:40 UTC, preames reviewed
I realized when taking a deeper look that you're duplicating functionality here.  This same case is supposed to be handled in the "if (DefReg.isVirtual() && LIS) {" above.  I think what happens is that you've got an order of operations bug.  You need to *actually* modify the instruction first, then perform all of the LIS update.  (That is, move that block done to just before the OldVReg update, and maybe move the setDesc call up.

2024-07-11 15:18 UTC, lukel97 commented
DefReg is a different register, it's the output VL, this is for the input AVL. But now that you mention it, we were also duplicating the liveintervals update for the AVL too. We already handle it for the normal case, but the bug was ultimately caused by this case here where we continue early for two consecutive vsetvlis with no pseudos in between:

https://github.com/llvm/llvm-project/pull/98286/files#diff-a186cfa1b7676c0a95a09935007221c321cfc52ce54b85d15064963d413725a3R1657-R1661

I've removed that redundant case so we're only updating the *AVL* in one place.

2024-07-11 17:04 UTC, preames commented
Sorry for the confusion, you're right about DefReg vs OldVLReg.  I think you're also right about the early continue being the trigger, but looking at that code, it looks like we're also missing the ADDI prune in that case as well.  Maybe pull out a lambda for prepareToDelete which does all the LIS fixup, ADDI deletion, and addition to the ToDelete list?

2024-07-12 00:43 UTC, preames approved these changes
LGTM to the current patch.

I talked with Luke offline, and was convinced this is correct as structured.  I'm not a fan of the style - doing the updates in two places, and out of order - but I'm explicitly okay with this landing, and I will post an NFC tomorrow.

2024-07-12 01:40 UTC, merged