[PatternMatch] Add matchers for `m_{I,F,}Cmp` and `m_{I,F,}SpecificCmp`; NFC
llvm/llvm-project pull request #98282
Opened 2024-07-10 08:20 UTC by goldsteinn

These matchers either take no predicate argument or match a specific
predicate respectively.

We have a lot of cases where the Pred argument is either unused and
requiring the argument reduces code clarity.

Likewise we have a lot of cases where we only pass in Pred to test
equality which the new `*Specific*` helpers can simplify.

2024-07-10 08:42 UTC, dtcxzyw commented on llvm/include/llvm/IR/PatternMatch.h
> +        if constexpr (!MatchExistingPred)
It is incorrect when `MatchExistingPred = true`.

2024-07-10 08:43 UTC, dtcxzyw commented on llvm/include/llvm/IR/PatternMatch.h
> +        if constexpr (!MatchExistingPred)
```
static_assert(!Commutable || !MatchExistingPred
```
Oh, sorry about this :)

2024-07-10 08:47 UTC, dtcxzyw approved these changes
LGTM.

2024-07-10 09:11 UTC, goldsteinn commented on llvm/include/llvm/IR/PatternMatch.h
> +      std::conditional_t<MatchExistingPred, const PredicateTy &, PredicateTy &>;
That would also work, no real preference on my end.

2024-07-10 09:25 UTC, nikic requested changes

2024-07-10 09:25 UTC, nikic commented on llvm/include/llvm/IR/PatternMatch.h
> +          bool Commutable = false, bool MatchExistingPred = false>
Please create a new class for this.

2024-07-10 13:08 UTC, nikic approved these changes
LGTM. We might also need m_c_SpecificICmp, but let's start with this.

2024-07-12 18:34 UTC, closed without merging

2024-07-12 21:33 UTC, nikic commented
Hm yeah, the way the "unused predicate" case is implemented doesn't work ... the actual match will happen later, and at that point the dummy variable is out of scope. I guess we'd need a separate matcher class for that.

2024-07-13 03:32 UTC, vitalybuka commented
@goldsteinn @nikic I temporarily disabled the test-case, please take a look.

2024-07-15 07:29 UTC, goldsteinn commented
> @goldsteinn @nikic I temporarily disabled the test-case, please take a look.

Fix at: https://github.com/llvm/llvm-project/pull/98866