[AArch64] Improve the codegen for sdiv 2
llvm/llvm-project pull request #98324
Opened 2024-07-10 14:06 UTC by vfdff

Follow PR97879, if X's size is BitWidth, then X sdiv 2 can be expressived as
```
  X += X >> (BitWidth - 1)
  X = X >> 1
```

Fix https://github.com/llvm/llvm-project/issues/97884

2024-07-10 14:13 UTC, dtcxzyw requested changes

2024-07-10 14:13 UTC, dtcxzyw commented on llvm/test/CodeGen/RISCV/sdiv-pow2-cmov.ll
> -; SFB-LABEL: sdiv2_32:
On SiFive's cores with SFB (Short forward branch), `bgez + addi` only takes one cycle.

2024-07-10 14:13 UTC, dtcxzyw commented on llvm/test/CodeGen/AArch64/aarch64-bit-gen.ll
> +; CHECK-SD-NEXT:    add w8, w0, w0, lsr #31
It would be better to fold `X < 0 ? X : X + 1` into `X + (X >>31)` on AArch64 backend (as we already did on RISC-V).

2024-07-10 18:00 UTC, topperc commented on llvm/lib/CodeGen/SelectionDAG/TargetLowering.cpp
> +    // If Divisor is 2, add 1 << (BitWidth -1) to it before shifting right.
This comment isn't accurate. It's adding (N0 >> (BitWidth - 1)).

2024-07-11 11:03 UTC, dtcxzyw approved these changes
LGTM.

2024-07-12 01:06 UTC, merged