[LLD] [Build Issue] Ubuntu24 build failure  due to LLD's COFF regression
llvm/llvm-project pull request #98447
Opened 2024-07-11 08:39 UTC by vg0204

It happened due to lld's COFF linker multiple regression tests failure. The bug found can be identified as a Heisenbug, which appears only in Release mode, not in Debug mode. It also vanishes when BUG is being tried to be outputed out or isolated. This behaviour cannot be seen at all in OS below Ubuntu24.

Eventually, the bug was about not handling exported symbols properly, when dealing with defining undefined symbols for COFF linker. Its specifically about improper forwarding of isUsedinRegObject boolean while invoking replaceSymbol() API, so hence explicitly doing it resolved issue.

2024-07-11 13:29 UTC, arsenm commented
Needs test?

2024-07-11 15:36 UTC, vg0204 commented
I don't know exactly, as this patch solved some failing test cases(bug) when ran in Ubuntu 24 (for the first time in psdb pipeline), but it was not needed up untill ubuntu 22.

2024-07-11 21:55 UTC, mstorsjo commented
FWIW, I can't reproduce such an issue with Ubuntu 24.04. I tested setting up Ubuntu 24.04, installed the `build-essential` packages (giving me GCC 13), built the latest git main of llvm-project (`-DCMAKE_BUILD_TYPE=Release -DLLVM_ENABLE_PROJECTS=lld -DLLVM_ENABLE_TARGETS="X86;ARM;AArch64"`) and ran `check-lld` and it all passed just fine.

2024-07-12 23:44 UTC, MaskRay commented
Request changes unless there is a reproduce and evidence that `isUsedInRegularObj` does resolve the issue.

I am more familiar with the ELF port where there used to be some issues related to `isUsedInRegularObj`, but the issues could all be reliably caught. I am not sure COFF port has Heisenbug since we don't perform parallel symbol resolution.

If you believe there is an issue `isUsedInRegularObj`, perhaps asan can expose the issue.

2024-07-12 23:44 UTC, MaskRay requested changes
.

2024-07-13 11:38 UTC, vg0204 commented
> Request changes unless there is a reproduce and evidence that `isUsedInRegularObj` does resolve the issue.
> 
> I am more familiar with the ELF port where there used to be some issues related to `isUsedInRegularObj`, but the issues could all be reliably caught. I am not sure COFF port has Heisenbug since we don't perform parallel symbol resolution.
> 
> If you believe there is an issue `isUsedInRegularObj`, perhaps asan can expose the issue.

Point noted!

2024-07-13 11:46 UTC, vg0204 commented
> FWIW, I can't reproduce such an issue with Ubuntu 24.04. I tested setting up Ubuntu 24.04, installed the `build-essential` packages (giving me GCC 13), built the latest git main of llvm-project (`-DCMAKE_BUILD_TYPE=Release -DLLVM_ENABLE_PROJECTS=lld -DLLVM_ENABLE_TARGETS="X86;ARM;AArch64"`) and ran `check-lld` and it all passed just fine.

As I looked into it again, what are you saying is true, but I am getting this issue while trying to build in a private repo, which gets updated with main upstream on regular basis. Seeing how things procced there, it would better to decide if this patch is really needed or not.

2024-07-15 09:37 UTC, arsenm commented
> As I looked into it again, what are you saying is true, but I am getting this issue while trying to build in a private repo, which gets updated with main upstream on regular basis. Seeing how things procced there, it would better to decide if this patch is really needed or not.

It would be easier to evaluate with a test. Any behavior change needs a test

2024-07-15 10:09 UTC, vg0204 commented
Also. I have a query regarding the replaceSymbol() function used for other linker like wasm or MachO. All of them used the reference forwarding, then why they need explicit re-assignment of boolean variables. If so, shouldn't it be uniformly done for all such variables in every version of replaceSymbol(). If anyone could comment on this.

2024-07-15 20:31 UTC, rnk commented
I think there's a real bug here.

It seems extremely sketchy that we don't initialize `isUsedInRegularObj` in the Symbol constructor, but that must be intentional. I'm pretty sure the compiler is entitled to zero initialize the whole object during the constructor, and that may be what @vg0204 is observing with some new GCC version on Ubuntu 24. And, with that toolchain, the bug is reliably observable in the regression test suite.

If we zero initialize the member in all builds, does that cause tests to fail, and then does this patch fix it? I think that's the next thing to try here.

2024-07-15 20:37 UTC, rnk commented
+ other LLD COFF stake holders: @mstorsjo @aganea

2024-07-16 07:51 UTC, vg0204 commented
> I think there's a real bug here.
> 
> It seems extremely sketchy that we don't initialize `isUsedInRegularObj` in the Symbol constructor, but that must be intentional. I'm pretty sure the compiler is entitled to zero initialize the whole object during the constructor, and that may be what @vg0204 is observing with some new GCC version on Ubuntu 24. And, with that toolchain, the bug is reliably observable in the regression test suite.
> 
> If we zero initialize the member in all builds, does that cause tests to fail, and then does this patch fix it? I think that's the next thing to try here.

Will do that right away!

2024-07-18 06:10 UTC, vg0204 commented
As mentioned in your commit, it really solves the problem. The regression failure can be reliably observed when isUsedDefinedInRegObj bit is zero-intialized in all builds (Ubuntu24 & below) and also identical in nature. Now, if this patch is applied on top of the zero intialization, the issue gets resolved for all builds. Exactly both of this is being done in your mentioned commit, thus exposing & solving the problem uniformly across different Ubuntu builds.

2024-07-19 07:16 UTC, vg0204 commented
PING!

2024-07-19 10:15 UTC, mstorsjo commented
I also reproduced, that if we as zeroing of this variable in the constructor, the issue appears, and this change fixes it.

But I would prefer if we’d add such zeroing in the constructor, to get consistent and reliable behavior across all toolchains. I’m not sure that it’s deliberately omitted, it seems like an oversight to me.

2024-07-19 16:37 UTC, rnk commented
Yeah, I put together that patch locally, but I wanted to give @vg0204  the opportunity to add the zero initialization so they get credit for the fix. :)

So, yes, that is the next step, add `isUsedByRegularObj(false)` to the ctor, and then we can merge it.

2024-07-22 05:55 UTC, vg0204 commented
Appreciate that @rnk, already made the necessary changes locally as well while testing out your suggestion on my toolchain of ubuntu24 where this issues had been intially observed. So, would push it up the changes soon, just after testing all regression suite one!

2024-07-22 07:13 UTC, mstorsjo approved these changes
LGTM, thanks!

The PR description/subject should probably be updated a bit before landing this though, now that the issue is better understood. (Although whoever merges it probably also can touch up the commit message.)

2024-07-22 07:15 UTC, vg0204 commented
Will do the needful, before the merge!

2024-07-22 10:12 UTC, merged