ArrayRef: add missing constexpr annotations (NFC)
llvm/llvm-project pull request #98874
Opened 2024-07-15 08:59 UTC by artagnon

2024-07-15 13:50 UTC, kuhar reviewed
Could you describe the intended use case for this?

2024-07-15 15:16 UTC, artagnon commented
> Could you describe the intended use case for this?

See #98893.

2024-07-15 17:19 UTC, artagnon commented
Thanks to @kuhar for explaining to me that these annotations are useless.

2024-07-19 00:09 UTC, artagnon commented
This is a perfectly good patch on its own, since Data + Length will  be optimized.

2024-07-19 00:14 UTC, kuhar requested changes
> This is a perfectly good patch on its own, since Data + Length will be optimized.

Please explain this

2024-07-19 00:55 UTC, kazutakahirata commented
> > This is a perfectly good patch on its own, since Data + Length will be optimized.
> 
> Please explain this

Are you referring to this?

```
constexpr iterator end() const { return Data + Length; }
```

If so, do you need `Data + Length` to be evaluated at compile time?

I haven't understood the application side of things, but if the `constexpr` being added makes a difference to you, you might want to add unit tests that depend on the `constexpr` being added.  You can do something like:

- `static_assert(Ref.size() == 3)`
- `if constexpr (foo == Ref.end())`

2024-08-27 11:20 UTC, artagnon commented
Not pursuing this.

2024-08-27 11:20 UTC, closed without merging