ADT/Matrix: two-dimensional Container with View
llvm/llvm-project pull request #98893
Opened 2024-07-15 12:55 UTC by artagnon

Leverage the excellent SmallVector infrastructure to write a two-dimensional container, along with a View that abstracts out indexing-arithmetic, eliminating memory operations on the underlying storage. The immediate applicability of Matrix is to replace uses of the vector-of-vectors idiom, with one caveat: an upper bound on the number of columns should be known ahead of time.

-- 8< --
Based on #98874.

2024-07-15 13:56 UTC, kuhar requested changes
Why would we want to have a dedicated owning (storage) type for 2d arrays? If all you want is to support 2d indexing, I'd imagine something like `std::ndspan` over a plain allocation (e.g., vector) would suffice?

Also, how is this related to adding `constexpr` to array ref? I understand it's the base PR, but why do we need `constexpr` in the first place?

2024-07-15 14:02 UTC, artagnon commented
> Why would we want to have a dedicated owning (storage) type for 2d arrays? If all you want is to support 2d indexing, I'd imagine something like `std::ndspan` over a plain allocation (e.g., vector) would suffice?
> 
> Also, how is this related to adding `constexpr` to array ref? I understand it's the base PR, but why do we need `constexpr` in the first place?

This is more advanced that `std::mdspan`: it supports variable-length rows, and the immediate use case is to replace the vector-of-vectors idiom. Besides, `std::mdspan` is only available from C++26. Please see #98895 for an example use case.

This is related to adding `constexpr` to ArrayRef, because otherwise, I can't mark anything that depends on ArrayRef functions as `constexpr`.

2024-07-15 14:07 UTC, kuhar commented
> Besides, std::mdspan is only available from C++26

My point was that we could implement something like mdspan in LLVM.

> This is related to adding constexpr to ArrayRef, because otherwise, I can't mark anything that depends on ArrayRef functions as constexpr.

What are constexpr functions do you need that depend on ArrayRef?

2024-07-15 14:11 UTC, artagnon commented
> > Besides, std::mdspan is only available from C++26
> 
> My point was that we could implement something like mdspan in LLVM.

Yes, and that's what I've implemented in MatrixView. The storage class is essentially SmallVector with an additional field for tracking the number of columns.
 
> > This is related to adding constexpr to ArrayRef, because otherwise, I can't mark anything that depends on ArrayRef functions as constexpr.
> 
> What are constexpr functions do you need that depend on ArrayRef?

The constructors, drop_back, drop_front, slice, for instance.

2024-07-15 16:23 UTC, kuhar commented
> Yes, and that's what I've implemented in MatrixView. The storage class is essentially SmallVector with an additional field for tracking the number of columns. I need to track the number of columns, so that I can reconstruct the View after the underlying storage has been reallocated.

Thanks you for the explanation. If this is the case, I don't think the name `Matrix*` is the most fitting. I'd call it something like 'JaggedArray': https://en.wikipedia.org/wiki/Jagged_array.

> The constructors, drop_back, drop_front, slice, for instance.

What I'm missing is:
* What compile-time computation do we intend to do and why we need it?
* Why does this computation include 2d arrays and, transitively, array ref?

2024-07-15 16:36 UTC, artagnon commented
> > Yes, and that's what I've implemented in MatrixView. The storage class is essentially SmallVector with an additional field for tracking the number of columns. I need to track the number of columns, so that I can reconstruct the View after the underlying storage has been reallocated.
> 
> Thanks you for the explanation. If this is the case, I don't think the name `Matrix*` is the most fitting. I'd call it something like 'JaggedArray': https://en.wikipedia.org/wiki/Jagged_array.

I suppose it is a MatrixStorage with a JaggedArrayView. Thanks for the name suggestion: I wasn't aware of this terminology. I would, however, like some suggestions for names from other reviewers as well, before we finalize on something.

> > The constructors, drop_back, drop_front, slice, for instance.
> 
> What I'm missing is:
> 
>     * What compile-time computation do we intend to do and why we need it?

The compile-time computation is very minor, and amounts to a few pointer subtractions. See `MutableArrayRef<T>::slice(Begin, End - Begin);` for instance.

>     * Why does this computation include 2d arrays and, transitively, array ref?

So, the 2D View returns a 1D View (called MatrixRowView) with an `operator[]`, and this struct inherits from MutableArrayRef.

2024-07-15 16:42 UTC, kuhar commented
> The compile-time computation is very minor, and amounts to a few pointer subtractions. See MutableArrayRef<T>::slice(Begin, End - Begin); for instance.

Again, please explain why we need this to happen at compilation time.

2024-07-15 16:46 UTC, artagnon commented
> > The compile-time computation is very minor, and amounts to a few pointer subtractions. See MutableArrayRef::slice(Begin, End - Begin); for instance.
> 
> Again, please explain why we need this to happen at compilation time.

Isn't it more efficient to do this at compile time, shaving the runtime?

2024-07-15 16:48 UTC, dwblaikie commented
> > > Yes, and that's what I've implemented in MatrixView. The storage class is essentially SmallVector with an additional field for tracking the number of columns. I need to track the number of columns, so that I can reconstruct the View after the underlying storage has been reallocated.
> > 
> > 
> > Thanks you for the explanation. If this is the case, I don't think the name `Matrix*` is the most fitting. I'd call it something like 'JaggedArray': https://en.wikipedia.org/wiki/Jagged_array.
> 
> I suppose it is a MatrixStorage with a JaggedArrayView. Thanks for the name suggestion: I wasn't aware of this terminology. I would, however, like some suggestions for names from other reviewers as well, before we finalize on something.

Why does the view support jagged arrays, though? Is that needed?

2024-07-15 16:49 UTC, kuhar commented
Say you define a function:
```c++
constexpr int add(int a, int b) { return a + b; }
```

this won't make any runtime call to `add` faster but it will allow you to write `static_assert(add(2 + 3) == 5);`

2024-07-15 16:54 UTC, artagnon commented
> > > > Yes, and that's what I've implemented in MatrixView. The storage class is essentially SmallVector with an additional field for tracking the number of columns. I need to track the number of columns, so that I can reconstruct the View after the underlying storage has been reallocated.
> > > 
> > > 
> > > Thanks you for the explanation. If this is the case, I don't think the name `Matrix*` is the most fitting. I'd call it something like 'JaggedArray': https://en.wikipedia.org/wiki/Jagged_array.
> > 
> > 
> > I suppose it is a MatrixStorage with a JaggedArrayView. Thanks for the name suggestion: I wasn't aware of this terminology. I would, however, like some suggestions for names from other reviewers as well, before we finalize on something.
> 
> Why does the view support jagged arrays, though? Is that needed?

The immediate motivating example is to migrate existing vector-of-vectors idioms, so yes, this is needed. The more long-term vision is to implement Matrix algorithm: most of these like Guassian Elimination need pivoting, and instead of complicating the code with pivot-tracking, we can use this view which tracks the last element automatically; therefore, we can swap any column index with the last element, and drop_back the row-view, as I've shown in the FM-Elimination in #98895.

2024-07-15 16:56 UTC, artagnon commented
> Say you define a function:
> 
> ```c++
> constexpr int add(int a, int b) { return a + b; }
> ```
> 
> this won't make any runtime call to `add` faster but it will allow you to write `static_assert(add(2 + 3) == 5);` or use it in `SmallVector<float, add(3+4)> floats;`

Thanks for the explanation. I will remove the useless `constexpr` annotations, and drop the arrayref-constexpr patch.

2024-07-17 14:40 UTC, kuhar commented
Same high-level comment as in https://github.com/llvm/llvm-project/pull/98895/files#r1681176240: could we make this code local to its first user before promoting to ADT?

2024-07-18 18:24 UTC, arsenm commented on llvm/include/llvm/ADT/Matrix.h
> +    assert(size() % NCols == 0 && "Internal error");
might as well drop the assert string if it's this generic

2025-01-09 20:44 UTC, closed without merging