[Bounds Safety][NFC] Add `SemaBoundsSafety` class and move existing Sema checks there
llvm/llvm-project pull request #98954
Opened 2024-07-15 20:20 UTC by delcypher

This patch creates a `SemaBoundsSafety` class to create a clean
separation between `-fbounds-safety` Sema checks and
other Sema checks. A `SemaBoundsSafety` object is available via the
`Sema::BoundsSafety()` method, similar to how other Sema checks have
been seperated out (e.g. `SemaSwift`).

The existing `CheckCountedByAttrOnField` function and related helper
functions and types from `SemaDeclAttr.cpp` has been moved into
`SemaBoundsSafety`. Although `counted_by(_or_null)` and
`sized_by(_or_null)` attributes have a meaning outside of
`-fbounds-safety` it seems reasonable to also have the Sema logic live
in `SemaBoundsSafety` since the intention is that the attributes will
have the same semantics (but not necessarily the same enforcement).

As `-fbounds-safety` is upstreamed additional Sema checks will be
added to the `SemaBoundsSafety` class.

rdar://131777237

2024-07-15 21:17 UTC, hnrklssn approved these changes
LGTM, might want to give the rest some time to have a look though

2024-07-15 21:35 UTC, Endilll requested changes
Unfortunately, I think this should be held off until we have a bigger picture for the future of `Sema`. I'll elaborate below.

If you take a close look at the existing set of `Sema` parts, it's almost entirely comprised of other languages or language extensions (from C and C++ standpoint) and backends. They were considered natural enough to be split off `Sema`, which, among other things, means that it's easy to explain their place in the big picture, like I did in the previous sentence.

I drove the effort to split `Sema`, and it has stalled, because it's not clear what to do with what's left there. We had several offline discussions, but we didn't find a solution that would substantially improve status quo.

I don't think this patch makes it easier to explain people where things are in this codebase, because (I think) `counted_by` is a declaration attribute, and we already have place for them. Having only one function also makes it a very small part of `Sema`, which doesn't sound compelling. A bigger picture this fits in would be a compelling argument (like it was for small backend parts), but to my knowledge there's none. Coming up with one and getting maintainers on board is certainly out of scope of this PR, so don't feel obligated to do that. Hopefully I'll get back to this whole topic later.

CC @AaronBallman

2024-07-15 21:35 UTC, Endilll commented on clang/include/clang/Sema/SemaBoundsSafety.h
> +class CountAttributedType;
I think only half of those forward declarations are really needed in the header.

2024-07-15 21:43 UTC, hnrklssn commented
> If you take a close look at the existing set of `Sema` parts, it's almost entirely comprised of other languages or language extensions (from C and C++ standpoint) and backends. They were considered natural enough to be split off `Sema`, which, among other things, means that it's easy to explain their place in the big picture, like I did in the previous sentence.

I don't have a strong opinion on whether this should be split up, but I just wanted to point out that `-fbounds-safety` is also a language extension, so it does kind of fit your description of other things separated out. It's currently in the process of being upstreamed which is why it's small, but it'd be easier to split now than wait until it's reached a certain size, if we do want to split it eventually.

2024-07-15 21:58 UTC, Endilll commented
> > If you take a close look at the existing set of `Sema` parts, it's almost entirely comprised of other languages or language extensions (from C and C++ standpoint) and backends. They were considered natural enough to be split off `Sema`, which, among other things, means that it's easy to explain their place in the big picture, like I did in the previous sentence.
> 
> I don't have a strong opinion on whether this should be split up, but I just wanted to point out that `-fbounds-safety` is also a language extension, so it does kind of fit your description of other things separated out.

"Extension" is definitely quite broad. What I meant are (basically) languages that are based off C or C++. Would you argue that `-fbounds-safety` fits into a set of OpenMP, OpenACC, CUDA, HLSL, Objective-C, and Swift?

> It's currently in the process of being upstreamed which is why it's small, but it'd be easier to split now than wait until it's reached a certain size, if we do want to split it eventually.

I did that a lot with other parts of `Sema`, and it's not that hard, unless it grows comparable to `SemaExprCXX.cpp` (which I consider unlikely to happen). I'd rather see this being upstreamed into the existing `Sema` structure as it has been planned all along, and use it as an input for the design of further `Sema` splitting, rather than committing today that `SemaBoundsSafety` is going to be a thing.

2024-07-16 12:43 UTC, delcypher commented
> Unfortunately, I think this should be held off until we have a bigger picture for the future of `Sema`. I'll elaborate below.
> 
> If you take a close look at the existing set of `Sema` parts, it's almost entirely comprised of other languages or language extensions (from C and C++ standpoint) and backends. They were considered natural enough to be split off `Sema`, which, among other things, means that it's easy to explain their place in the big picture, like I did in the previous sentence.

As noted above `-fbounds-safety` **is a C language extension** which makes it seem like it would fit nicely into the existing division of Sema into multiple objects and relevant source files.

> I don't think this patch makes it easier to explain people where things are in this codebase, because (I think) `counted_by` is a declaration attribute, and we already have place for them. Having only one function also makes it a very small part of `Sema`, which doesn't sound compelling. 

It doesn't right now because most of `-fbounds-safety` implementation isn't upstream yet.  I simply moved what is **currently upstream**. As we (Apple) upstream more and more of the implementation it makes a lot sense to try to keep as much of it in its own source file to:

* Create a clean separation between `-fbounds-safety` Sema checks and everything else. This will ultimately make exploring the code easier once a significant amount of our implementation has been upstreamed.
* Avoid growing all the existing `Sema*.cpp` files unnecessarily. They are already huge and we don't want to make the problem worse when there's an easy option available to avoid that.


> A bigger picture this fits in would be a compelling argument (like it was for small backend parts), but to my knowledge there's none.

The `counted_by` attribute is just one of several attributes that are part of the `-fbounds-safety` language extension which is documented here https://clang.llvm.org/docs/BoundsSafety.html. That's "bigger picture" for the feature, or did you mean something else by "bigger picture this fits in"?

> Coming up with one and getting maintainers on board is certainly out of scope of this PR, so don't feel obligated to do that. Hopefully I'll get back to this whole topic later.
>

My end goal is to have "somewhere" to put all of the Sema code that support `-fbounds-safety` as we upstream it. I think it's very much preferable to have this code go into its own source file and header file for the reasons I gave above.

We don't have to use the sub-class `SemaBase` mechanism that I've used here if this is really a problem. However, the mechanism does seem like a good fit for `-fbounds-safety` and would be a shame not to use it.

2024-07-16 13:10 UTC, delcypher commented
> "Extension" is definitely quite broad. What I meant are (basically) languages that are based off C or C++. Would you argue that `-fbounds-safety` fits into a set of OpenMP, OpenACC, CUDA, HLSL, Objective-C, and Swift?

In my opinion it fits in the set because it is a (pretty large) C language extension.
 
> > It's currently in the process of being upstreamed which is why it's small, but it'd be easier to split now than wait until it's reached a certain size, if we do want to split it eventually.
> 
> I did that a lot with other parts of `Sema`, and it's not that hard, unless it grows comparable to `SemaExprCXX.cpp` (which I consider unlikely to happen). I'd rather see this being upstreamed into the existing `Sema` structure as it has been planned all along, and use it as an input for the design of further `Sema` splitting, rather than committing today that `SemaBoundsSafety` is going to be a thing.

I don't agree with this approach. I outlined above why I think it makes a lot of sense to keep the `-fbounds-safety` Sema code in its own source file and blocking  doing that on a _potential future refactor_ that might never happen doesn't seem like a good idea to me.

If at some point we come up with some new design for Sema we can easily move the `-fbounds-safety` code out of its own source file (and class) and into the relevant locations required by the redesign. If the `-fbounds-safety` code is littered all over the other Sema files the "potential future refactor" could be much harder because finding all `-fbound-safety` code now is much more time consuming.

2024-07-16 14:09 UTC, Endilll commented
> > Unfortunately, I think this should be held off until we have a bigger picture for the future of `Sema`. I'll elaborate below.
> > If you take a close look at the existing set of `Sema` parts, it's almost entirely comprised of other languages or language extensions (from C and C++ standpoint) and backends. They were considered natural enough to be split off `Sema`, which, among other things, means that it's easy to explain their place in the big picture, like I did in the previous sentence.
> 
> As noted above `-fbounds-safety` **is a C language extension** which makes it seem like it would fit nicely into the existing division of Sema into multiple objects and relevant source files.

No, it don't fit nicely into the division, which is the reason we're having this discussion.

> > I don't think this patch makes it easier to explain people where things are in this codebase, because (I think) `counted_by` is a declaration attribute, and we already have place for them. Having only one function also makes it a very small part of `Sema`, which doesn't sound compelling.
> 
> It doesn't right now because most of `-fbounds-safety` implementation isn't upstream yet. I simply moved what is **currently upstream**. As we (Apple) upstream more and more of the implementation it makes a lot sense to try to keep as much of it in its own source file to:
> 
>     * Create a clean separation between `-fbounds-safety` Sema checks and everything else. This will ultimately make exploring the code easier once a significant amount of our implementation has been upstreamed.
> 
>     * Avoid growing all the existing `Sema*.cpp` files unnecessarily. They are already huge and we don't want to make the problem worse when there's an easy option available to avoid that.

You can have `SemaBoundsSafety.cpp` and your own "section" inside `Sema.h`, like C++ features do (like templates or lambdas). There's no reason to make separation physical by introducing `SemaBoundsSafety` class from the get-go.

> > A bigger picture this fits in would be a compelling argument (like it was for small backend parts), but to my knowledge there's none.
> 
> The `counted_by` attribute is just one of several attributes that are part of the `-fbounds-safety` language extension which is documented here https://clang.llvm.org/docs/BoundsSafety.html. That's "bigger picture" for the feature, or did you mean something else by "bigger picture this fits in"?

A bigger picture is "what are we going to do with the rest of the attributes in `SemaDeclAttr.cpp`?". Even bigger one is "what do we do about SemaDecl, SemaExpr, SemaDeclCXX, and SemaExprCXX?"

> > Coming up with one and getting maintainers on board is certainly out of scope of this PR, so don't feel obligated to do that. Hopefully I'll get back to this whole topic later.
> 
> My end goal is to have "somewhere" to put all of the Sema code that supports `-fbounds-safety` that we will upstream. I think it's very much preferable to have this code go into its own source file and header file for the reasons I gave above.
> 
> We don't have to use the sub-class `SemaBase` mechanism that I've used here if this is really a problem. However, the mechanism does seem like a good fit for `-fbounds-safety` and would be a shame not to use it.

> > "Extension" is definitely quite broad. What I meant are (basically) languages that are based off C or C++. Would you argue that `-fbounds-safety` fits into a set of OpenMP, OpenACC, CUDA, HLSL, Objective-C, and Swift?
> 
> In my opinion it fits in the set because it is a (pretty large) C language extension.
> 
> > > It's currently in the process of being upstreamed which is why it's small, but it'd be easier to split now than wait until it's reached a certain size, if we do want to split it eventually.
> > 
> > 
> > I did that a lot with other parts of `Sema`, and it's not that hard, unless it grows comparable to `SemaExprCXX.cpp` (which I consider unlikely to happen). I'd rather see this being upstreamed into the existing `Sema` structure as it has been planned all along, and use it as an input for the design of further `Sema` splitting, rather than committing today that `SemaBoundsSafety` is going to be a thing.
> 
> I don't agree with this approach. I outlined above why I think it makes a lot of sense to keep the `-fbounds-safety` Sema code in its own source file and blocking doing that on a _potential future refactor_ that might never happen doesn't seem like the right approach to me.

I have to say that `-fbounds-safety` upstreaming is in the same boat of something that might never happen.

> If at some point we come up with some new design for Sema we can easily move the `-fbounds-safety` code out of its own source file (and class) and into the relevant locations required by the redesign. If the `-fbounds-safety` code is littered all over the other Sema files the _potential future refactor_ could be much harder because finding all `-fbound-safety` code now is much more time consuming.

That's why I propose to follow long-established practice of doing `SemaBoundsSafety.cpp`, and move that around later. What I'd like to evaluate before deciding on `SemaBoundsChecking` is how big its interface is (what would be exposed via `SemaBoundsChecking` class,)

2024-07-16 15:43 UTC, AaronBallman commented
The separations we've been making so far in `Sema` have been at a higher level of granularity than this proposal. Vlad was calling it "language extensions" but perhaps a different way to phrase it would be "unique language dialects". e.g., Objective-C is its own language, but it's technically an extension of C. Similar for things like OpenMP, etc. I don't think bounds safety is the same kind of extension in that regard; it's a handful of features allowing for extra diagnostic checking more than it's a unique language. For example, thread safety analysis can be described in exactly the same way, so should it be split off too? If we keep doing that, will splitting semantic object by language feature scale? What's the criteria for when a language feature should or should not be split? I think we can side step all of this for right now.

That said, I think grouping the bounds safety semantic bits together in a single source file is a totally reasonable thing to do (Vlad's suggestion of `SemaBoundsSafety.cpp` was along the exact lines I was thinking this should go).

2024-07-17 10:37 UTC, delcypher commented
> > As noted above `-fbounds-safety` **is a C language extension** which makes it seem like it would fit nicely into the existing division of Sema into multiple objects and relevant source files.
> 
> No, it doesn't fit nicely into the division, which is the reason we're having this discussion.

If we don't agree on this then I must not fully understand what the criteria is for dividing Sema current is.
 
> You can have `SemaBoundsSafety.cpp` and your own "section" inside `Sema.h`, like C++ features do (like templates or lambdas). There's no reason to make separation physical by introducing `SemaBoundsSafety` class from the get-go.

I'm ok with this. Having the implementation in a separate file is where the main benefit lies. The separation into a separation into a separate class is a nice-to-have and ok to drop doing that.

> That's why I propose to follow long-established practice of doing `SemaBoundsSafety.cpp`, and move that around later. What I'd like to evaluate before deciding on `SemaBoundsChecking` is how big its interface is (what would be exposed via `SemaBoundsChecking` class,)

Sure. Let's go with that approach then.

2024-07-17 12:46 UTC, AaronBallman commented
> > > As noted above `-fbounds-safety` **is a C language extension** which makes it seem like it would fit nicely into the existing division of Sema into multiple objects and relevant source files.
> > 
> > 
> > No, it doesn't fit nicely into the division, which is the reason we're having this discussion.
> 
> If we don't agree on this then I must not fully understand what the criteria is for dividing Sema current is.

The goal is to provide some layering within Sema to help break it up more. e.g., the base layer is C and C++ needs, but then there's a layer for Objective-C needs, a different layer for OpenMP needs, etc. This helps make it more clear where dependencies lie between the large-scale different semantic components. Bounds safety isn't really a "layer". Does that make some sense?

> > You can have `SemaBoundsSafety.cpp` and your own "section" inside `Sema.h`, like C++ features do (like templates or lambdas). There's no reason to make separation physical by introducing `SemaBoundsSafety` class from the get-go.
> 
> I'm ok with this. Having the implementation in a separate file is where the main benefit lies. The separation into a separation into a separate class is a nice-to-have and ok to drop doing that.
> 
> > That's why I propose to follow long-established practice of doing `SemaBoundsSafety.cpp`, and move that around later. What I'd like to evaluate before deciding on `SemaBoundsChecking` is how big its interface is (what would be exposed via `SemaBoundsChecking` class,)
> 
> Sure. Let's go with that approach then.

Excellent, thank you!

2024-07-17 13:06 UTC, delcypher commented
> The separations we've been making so far in Sema have been at a higher level of granularity than this proposal. Vlad was calling it "language extensions" but perhaps a different way to phrase it would be "unique language dialects". e.g., Objective-C is its own language, but it's technically an extension of C. Similar for things like OpenMP, etc. I don't think bounds safety is the same kind of extension in that regard; it's a handful of features allowing for extra diagnostic checking more than it's a unique language.

Thanks for clarifying. I would describe`-fbounds-safety` as a lot more than extra diagnostic checking, it also injects runtime checks and its programming model adds restrictions that make C feel quite different. I'm not really sure that counts as a dialect but I guess it doesn't matter now given that I'll be going with a different approach.

Out of curiosity, how does the current division of Sema fit into the "unique language dialect" classification? I've noticed there are a bunch of architecture specific Sema classes (e.g. `SemaRISCV`, `SemaX86`) and those don't really fit the classification.

>  For example, thread safety analysis can be described in exactly the same way, so should it be split off too? If we keep doing that, will splitting semantic object by language feature scale? What's the criteria for when a language feature should or should not be split? I think we can side step all of this for right now.

Interesting question. I guess it depends on the size of the language feature and given that almost none of `-fbounds-safety` is currently upstream it is very difficult for you to make an informed decision in this particular case. So, yes let's side step this for now. We can always revisit it once a significant portion of `-fbounds-safety` is upstream.

> The goal is to provide some layering within Sema to help break it up more. e.g., the base layer is C and C++ needs, but then there's a layer for Objective-C needs, a different layer for OpenMP needs, etc. This helps make it more clear where dependencies lie between the large-scale different semantic components. Bounds safety isn't really a "layer". Does that make some sense?

Mostly, but I have some doubts about the "Bounds safety isn't really a layer" part but let's delay dealing with that until more of the implementation is upstream.

2024-07-17 13:15 UTC, Endilll commented
> Out of curiosity, how does the current division of Sema fit into the "unique language dialect" classification? I've noticed there are a bunch of architecture specific Sema classes (e.g. SemaRISCV, SemaX86) and those don't really fit the classification.

They are a different group of `Sema` parts, dedicated for backend-specific code. `SemaX86` and `SemaARM` serve as a good example of what a populated backend-specific part looks like.

2024-07-17 13:56 UTC, AaronBallman commented
> > Out of curiosity, how does the current division of Sema fit into the "unique language dialect" classification? I've noticed there are a bunch of architecture specific Sema classes (e.g. SemaRISCV, SemaX86) and those don't really fit the classification.
> 
> They are a different group of `Sema` parts, dedicated for backend-specific code. `SemaX86` and `SemaARM` serve as a good example of what a populated backend-specific part looks like.

Yup, and they're an example of where it helps to have layering (if parts of `SemaARM` need to call into `SemaX86`, it's good for that dependency to be more explicit).

2024-07-17 14:18 UTC, delcypher commented
Thanks all for the clarification. Closing this PR in favor of #99330

2024-07-17 14:18 UTC, closed without merging