[libc++] Fix acceptance of convertible-to-{float,double,long double} in std::isnan() and std::isinf()
llvm/llvm-project pull request #98952
Opened 2024-07-15 20:07 UTC by robincaloudis

2024-07-21 09:19 UTC, robincaloudis commented
With my changes, there is a conflicting declaration error of `isnan` and `isinf` between headers of `libc++`(libcxx of the llvm project) libstdc++ (default standard library of Clang on Linux) when running any of the cxx03 jobs. In `libstdc++`, both functions are guarded by preprocessor directives as [`/* isnan conflicts with C++11.  */`](https://github.com/bminor/glibc/blob/256574679feb0204ac859367fdbf4d91aff45d0a/math/bits/mathcalls.h#L224) and [`/* isinf conflicts with C++11.  */`](https://github.com/bminor/glibc/blob/256574679feb0204ac859367fdbf4d91aff45d0a/math/bits/mathcalls.h#L187). As we have `__cplusplus <= 199711L` in place for cxx03 jobs using `-std=c++03`, `isnan` and `isinf` are included. This more or less explains why we have a broken cxx03 job.

However, this does not explain the big picture to me:
- Why are headers from both `libstdc++` and `libc++` end up in the same compilation unit? From what I understand, Clang needs to either use the headers of `libstdc++` or `libc++` it in order to produce software that is compatible with the rest of the system
- A close look at the executed command shows us that the `-nostdlib++` and `-nostdinc++` is in place. I guess that this flag in the Clang frontend instructs the compiler not to use the standard system libraries as well as the corresponding headers. So the compilation unit needs to be „fully self contained“. Now I am even more confused as I do not understand how `/usr/include/x86_64-linux-gnu/bits/mathcalls.h` can end up in the compilation unit when `-nostdinc++` is in place.

To me it seems like `-I /home/runner/_work/llvm-project/llvm-project/build/generic-cxx03/include/c++/v1` (part of `libc++`) somehow depends on `/usr/include/x86_64-linux-gnu/bits/mathcalls.h` (part of`libstdc++`). Unfortunately, I have not found a way to proof my assumptions and probably lack some details. Could anyone give me a hint on what is going on under the hood?

Error output for `Build and Test libc++ / stage1 (generic-cxx03, clang-19, clang++-19)`
```
# executed command: /usr/bin/clang++-19 /home/runner/_work/llvm-project/llvm-project/libcxx/test/std/containers/unord/unord.multimap/key_eq.pass.cpp -pthread --target=x86_64-unknown-linux-gnu -nostdinc++ -I /home/runner/_work/llvm-project/llvm-project/build/generic-cxx03/include/c++/v1 -I /home/runner/_work/llvm-project/llvm-project/build/generic-cxx03/include/c++/v1 -I /home/runner/_work/llvm-project/llvm-project/libcxx/test/support -std=c++03 -Werror -Wall -Wctad-maybe-unsupported -Wextra -Wshadow -Wundef -Wunused-template -Wno-unused-command-line-argument -Wno-attributes -Wno-pessimizing-move -Wno-noexcept-type -Wno-atomic-alignment -Wno-reserved-module-identifier -Wdeprecated-copy -Wdeprecated-copy-dtor -Wno-user-defined-literals -Wno-tautological-compare -Wsign-compare -Wunused-variable -Wunused-parameter -Wunreachable-code -Wno-unused-local-typedef -Wno-local-type-template-args -Wno-c++11-extensions -Wno-unknown-pragmas -Wno-pass-failed -Wno-mismatched-new-delete -Wno-redundant-move -Wno-self-move -D_LIBCPP_HAS_NO_PRAGMA_SYSTEM_HEADER -D_LIBCPP_ENABLE_EXPERIMENTAL -D_LIBCPP_HARDENING_MODE=_LIBCPP_HARDENING_MODE_NONE -Werror=thread-safety -Wuser-defined-warnings -lc++experimental -nostdlib++ -L /home/runner/_work/llvm-project/llvm-project/build/generic-cxx03/lib -Wl,-rpath,/home/runner/_work/llvm-project/llvm-project/build/generic-cxx03/lib -lc++ -latomic -o /home/runner/_work/llvm-project/llvm-project/build/generic-cxx03/test/std/containers/unord/unord.multimap/Output/key_eq.pass.cpp.dir/t.tmp.exe
# .---command stderr------------
# | In file included from /home/runner/_work/llvm-project/llvm-project/libcxx/test/std/containers/unord/unord.multimap/key_eq.pass.cpp:17:
# | In file included from /home/runner/_work/llvm-project/llvm-project/build/generic-cxx03/include/c++/v1/unordered_map:591:
# | In file included from /home/runner/_work/llvm-project/llvm-project/build/generic-cxx03/include/c++/v1/__hash_table:43:
# | In file included from /home/runner/_work/llvm-project/llvm-project/build/generic-cxx03/include/c++/v1/cmath:318:
# | /home/runner/_work/llvm-project/llvm-project/build/generic-cxx03/include/c++/v1/math.h:422:20: error: target of using declaration conflicts with declaration already in scope
# |   422 | using std::__math::isinf;
# |       |                    ^
# | /home/runner/_work/llvm-project/llvm-project/build/generic-cxx03/include/c++/v1/__math/traits.h:86:83: note: target of using declaration
# |    86 | _LIBCPP_NODISCARD inline _LIBCPP_CONSTEXPR_SINCE_CXX23 _LIBCPP_HIDE_FROM_ABI bool isinf(double __x) _NOEXCEPT {
# |       |                                                                                   ^
# | /usr/include/x86_64-linux-gnu/bits/mathcalls.h:177:23: note: conflicting declaration
# |   177 | __MATHDECL_ALIAS (int,isinf,, (_Mdouble_ __value), isinf)
# |       |                       ^
# | In file included from /home/runner/_work/llvm-project/llvm-project/libcxx/test/std/containers/unord/unord.multimap/key_eq.pass.cpp:17:
# | In file included from /home/runner/_work/llvm-project/llvm-project/build/generic-cxx03/include/c++/v1/unordered_map:591:
# | In file included from /home/runner/_work/llvm-project/llvm-project/build/generic-cxx03/include/c++/v1/__hash_table:43:
# | In file included from /home/runner/_work/llvm-project/llvm-project/build/generic-cxx03/include/c++/v1/cmath:318:
# | /home/runner/_work/llvm-project/llvm-project/build/generic-cxx03/include/c++/v1/math.h:426:20: error: target of using declaration conflicts with declaration already in scope
# |   426 | using std::__math::isnan;
# |       |                    ^
# | /home/runner/_work/llvm-project/llvm-project/build/generic-cxx03/include/c++/v1/__math/traits.h:110:83: note: target of using declaration
# |   110 | _LIBCPP_NODISCARD inline _LIBCPP_CONSTEXPR_SINCE_CXX23 _LIBCPP_HIDE_FROM_ABI bool isnan(double __x) _NOEXCEPT {
# |       |                                                                                   ^
# | /usr/include/x86_64-linux-gnu/bits/mathcalls.h:213:23: note: conflicting declaration
# |   213 | __MATHDECL_ALIAS (int,isnan,, (_Mdouble_ __value), isnan)
# |       |                       ^
# | 2 errors generated.
# `-----------------------------
# error: command failed with exit status: 1
```

2024-07-21 09:35 UTC, robincaloudis commented
@ldionne or @philnik777, could you give me some direction? Thanks in advance!

2024-07-30 08:02 UTC, robincaloudis commented
@ldionne, I finally found a good solution. Please have another look. Thanks in advance!

2024-07-31 10:21 UTC, robincaloudis commented
> @robincaloudis The `mathcalls.h` header seems to be part of glibc, which is the C Standard Library on Linux. Not libstdc++, which is the C++ Standard Library (typically) used on Linux. So the setup here is what you would expect: libc++ layered on top of glibc (a C stdlib), and no second C++ stdlib anywhere.
> 
> It looks like the `float`, `double` and `long double` overloads of `std::isnan` have been added in C++11. So I guess what's happening here is that we incorrectly try to provide them and step on the toes of the C Standard Library.
> 
> It looks like libstdc++ ends up providing the `double` overload via a template checking `is_arithmetic`: https://godbolt.org/z/bse6GzEMx. Since templates are less preferred than non-template functions, perhaps this is why libstdc++ doesn't hit the same issue.

@ldionne, thanks for pointing out the obvious! I reconsidered my approach and found a solution. Do you mind to take a look? Thank you.

2024-07-31 14:03 UTC, ldionne requested changes
Do I understand correctly that the `convertible-to` tests fail only in the combination of libc++/C++03/glibc?

It seems to me like the cure may be worse than the disease in this case, I'm not certain this is worth addressing given the complexity it introduces. In a certain way, this can be seen as a bug in glibc since there's no such issue in other standard modes and in other standard libraries.

Instead, we could add the missing test coverage and disable it with a comment based on `TEST_STD_VER <= 03`

2024-07-31 14:59 UTC, robincaloudis commented
> Do I understand correctly that the `convertible-to` tests fail only in the combination of libc++/C++03/glibc?
> 
> It seems to me like the cure may be worse than the disease in this case, I'm not certain this is worth addressing given the complexity it introduces. In a certain way, this can be seen as a bug in glibc since there's no such issue in other standard modes and in other standard libraries.
> 
> Instead, we could add the missing test coverage and disable it with a comment based on `TEST_STD_VER <= 03`

Totally agree. The complexity is very high. The following is my current understanding: Disabling the missing tests based on `TEST_STD_VER <= 03` will still forces us to handle the non-standardized function declaration of `isnan(double)` with return type of `int` that glibc's `math.h` brings into scope. In order to handle that we need to either follow glib's approach of [`#undef isnan` from math.h in their <cmath>](https://cs.android.com/android/platform/superproject/+/master:bionic/libc/include/math.h;l=322-323;drc=master?hl=fr-BE%22https:%2F%2Fsupport.google.com%2Fmerchants%2Fanswer%2F188494%5C%22%22https:%2F%2Fsupport.google.com%2Fmerchants%2Fanswer%2F188494%5C%22) or displace the overload of the glibc library with `_LIBCPP_PREFERRED_OVERLOAD`. Note that `_LIBCPP_PREFERRED_OVERLOAD` was in place before. What I did was to restrict it to only the necessary situations. I believed that the underlying issue was not well understood up to this point and that's why `_LIBCPP_PREFERRED_OVERLOAD` is used as a "one-size-fits-it-all" solution. Please correct me if I misunderstand :)

2024-08-05 16:27 UTC, ldionne reviewed
You're right about us previously not really understanding why `_LIBCPP_PREFERRED_OVERLOAD` was used so liberally. However, given the complexity of adding it only in the cases where it's actually required, I'd drop the non-test changes from this patch and only improve the test coverage.

2024-08-05 16:27 UTC, ldionne commented on libcxx/test/std/numerics/c.math/cmath.pass.cpp
> +#if defined(__GLIBC__) && defined(_LIBCPP_CXX03_LANG) && !defined(_LIBCPP_PREFERRED_OVERLOAD)
I think I would suggest only keeping the test changes in this patch, and changing this to

```
#if defined(__GLIBC__) && TEST_STD_VER == 03 && defined(TEST_COMPILER_CLANG)
```

2024-08-07 11:41 UTC, robincaloudis commented
@ldionne, now the cure treats the disease the right way. All checks have succeeded. Could you have another look?

2024-08-16 15:15 UTC, ldionne approved these changes
This seems a lot better, thanks!

2024-08-16 15:18 UTC, merged

2024-09-02 10:36 UTC, dklimkin commented
I ran into some pre-existing code that got broken by this change. Original version was 
```
std::vector<double> foo;
return std::find_if_not(std::begin(foo), std::end(foo), std::isnan<double>);
```

Now the templated version is gone, and std::isnan(double) seems to be have `int` return value, breaking the call above with "Candidate template ignored: couldn't infer template argument '_Predicate'".

Does this work as intended?

2024-09-02 10:42 UTC, philnik777 commented
@dklimkin You're not allowed to take the address of non-addressable (i.e. most, see https://en.cppreference.com/w/cpp/language/extending_std) functions.

2024-09-02 10:57 UTC, dklimkin commented
@philnik777 thank you.