[Clang] Refactor uses of  in SemaOverload.cpp
llvm/llvm-project pull request #98965
Opened 2024-07-15 21:34 UTC by vortex73

2024-07-16 19:03 UTC, vortex73 commented
@haberman Please review.

2024-07-18 02:36 UTC, shafik approved these changes
Thank you for this refactor, just a couple of minor comments but otherwise looks good. Please fix first and then merge after it passes tests, if you need someone to merge for you please let me know.

2024-07-18 02:36 UTC, shafik commented on clang/lib/Sema/SemaOverload.cpp
> +  Function *CandFunc = Cand->Function;
We use `Fn` elsewhere, we should be consistent throughout the file.

2024-07-18 02:36 UTC, shafik commented on clang/lib/Sema/SemaOverload.cpp
> +      FunctionDecl *CandFunc = Cand->Function;
We use `Fn` elsewhere, we should be consistent with the rest of the file.

2024-07-18 02:39 UTC, shafik requested changes

2024-07-18 02:39 UTC, shafik commented on clang/lib/Sema/SemaOverload.cpp
> +  Function *CandFunc = Cand->Function;
```suggestion
  FunctionDecl *CandFunc = Cand->Function;
```
Whoops missed this the first time around, looks like a typo, please fix.

2024-07-18 04:59 UTC, vortex73 commented
@shafik I've made the changes. Please merge as I do not have write access.

2024-07-24 05:38 UTC, vortex73 commented
@shafik are any changes required for this PR?

2024-07-24 20:34 UTC, shafik approved these changes
LGTM

2024-07-24 20:42 UTC, merged