libc: Use UMAXV.4S to reduce bcmp result.
llvm/llvm-project pull request #99260
Opened 2024-07-17 00:51 UTC by pcc

We can use UMAXV.4S to reduce the comparison result in a single
instruction. This improves performance by roughly 4% on Apple M1:

Summary
  bin/libc.src.string.bcmp_benchmark3 --study-name="new bcmp" --sweep-mode --sweep-max-size=128 --output=/dev/null --num-trials=10 ran
    1.01 ± 0.02 times faster than bin/libc.src.string.bcmp_benchmark3 --study-name="new bcmp" --sweep-mode --sweep-max-size=128 --output=/dev/null --num-trials=10
    1.01 ± 0.03 times faster than bin/libc.src.string.bcmp_benchmark3 --study-name="new bcmp" --sweep-mode --sweep-max-size=128 --output=/dev/null --num-trials=10
    1.01 ± 0.03 times faster than bin/libc.src.string.bcmp_benchmark3 --study-name="new bcmp" --sweep-mode --sweep-max-size=128 --output=/dev/null --num-trials=10
    1.01 ± 0.02 times faster than bin/libc.src.string.bcmp_benchmark2 --study-name="new bcmp" --sweep-mode --sweep-max-size=128 --output=/dev/null --num-trials=10
    1.02 ± 0.03 times faster than bin/libc.src.string.bcmp_benchmark2 --study-name="new bcmp" --sweep-mode --sweep-max-size=128 --output=/dev/null --num-trials=10
    1.03 ± 0.03 times faster than bin/libc.src.string.bcmp_benchmark2 --study-name="new bcmp" --sweep-mode --sweep-max-size=128 --output=/dev/null --num-trials=10
    1.03 ± 0.03 times faster than bin/libc.src.string.bcmp_benchmark2 --study-name="new bcmp" --sweep-mode --sweep-max-size=128 --output=/dev/null --num-trials=10
    1.05 ± 0.02 times faster than bin/libc.src.string.bcmp_benchmark1 --study-name="new bcmp" --sweep-mode --sweep-max-size=128 --output=/dev/null --num-trials=10
    1.05 ± 0.02 times faster than bin/libc.src.string.bcmp_benchmark1 --study-name="new bcmp" --sweep-mode --sweep-max-size=128 --output=/dev/null --num-trials=10
    1.05 ± 0.03 times faster than bin/libc.src.string.bcmp_benchmark1 --study-name="new bcmp" --sweep-mode --sweep-max-size=128 --output=/dev/null --num-trials=10
    1.05 ± 0.02 times faster than bin/libc.src.string.bcmp_benchmark1 --study-name="new bcmp" --sweep-mode --sweep-max-size=128 --output=/dev/null --num-trials=10

(1 = original, 2 = a variant of this patch that uses UMAXV.16B, 3 = this patch)

2024-08-03 05:40 UTC, SchrodingerZhu commented
Hi, 

Thank you for the patch. Unfortunately, I think the proposed change is causing failures in tests:

```
Ran 5 tests.  PASS: 5  FAIL: 0
[4171/5229] Running unit test libc.test.src.stdio.snprintf_test.__unit__
FAILED: libc/test/src/stdio/CMakeFiles/libc.test.src.stdio.snprintf_test.__unit__ /home/schrodinger/development/llvm-project/build/libc/test/src/stdio/CMakeFiles/libc.test.src.stdio.snprintf_test.__unit__ 
cd /home/schrodinger/development/llvm-project/build/libc/test/src/stdio && /home/schrodinger/development/llvm-project/build/libc/test/src/stdio/libc.test.src.stdio.snprintf_test.__unit__.__build__
[==========] Running 2 tests from 1 test suite.
[ RUN      ] LlvmLibcSNPrintfTest.CutOff
/home/schrodinger/development/llvm-project/libc/test/src/stdio/snprintf_test.cpp:23: FAILURE
      Expected: buff
      Which is: 
To be equal to: "A simple string"
      Which is: A simple string
[  FAILED  ] LlvmLibcSNPrintfTest.CutOff
[ RUN      ] LlvmLibcSNPrintfTest.NoCutOff
/home/schrodinger/development/llvm-project/libc/test/src/stdio/snprintf_test.cpp:53: FAILURE
      Expected: buff
      Which is: 
To be equal to: "A simple string with no conversions."
      Which is: A simple string with no conversions.
[  FAILED  ] LlvmLibcSNPrintfTest.NoCutOff
Ran 2 tests.  PASS: 0  FAIL: 2
[4172/5229] Running unit test libc.test.src.stdio.vsnprintf_test.__unit__
FAILED: libc/test/src/stdio/CMakeFiles/libc.test.src.stdio.vsnprintf_test.__unit__ /home/schrodinger/development/llvm-project/build/libc/test/src/stdio/CMakeFiles/libc.test.src.stdio.vsnprintf_test.__unit__ 
cd /home/schrodinger/development/llvm-project/build/libc/test/src/stdio && /home/schrodinger/development/llvm-project/build/libc/test/src/stdio/libc.test.src.stdio.vsnprintf_test.__unit__.__build__
[==========] Running 2 tests from 1 test suite.
[ RUN      ] LlvmLibcVSNPrintfTest.CutOff
/home/schrodinger/development/llvm-project/libc/test/src/stdio/vsnprintf_test.cpp:35: FAILURE
      Expected: buff
      Which is: 
To be equal to: "A simple string"
      Which is: A simple string
[  FAILED  ] LlvmLibcVSNPrintfTest.CutOff
[ RUN      ] LlvmLibcVSNPrintfTest.NoCutOff
/home/schrodinger/development/llvm-project/libc/test/src/stdio/vsnprintf_test.cpp:64: FAILURE
      Expected: buff
      Which is: 
To be equal to: "A simple string with no conversions."
      Which is: A simple string with no conversions.
[  FAILED  ] LlvmLibcVSNPrintfTest.NoCutOff
Ran 2 tests.  PASS: 0  FAIL: 2
[4173/5229] Running unit test libc.test.src.stdio.fprintf_test.__unit__
FAILED: libc/test/src/stdio/CMakeFiles/libc.test.src.stdio.fprintf_test.__unit__ /home/schrodinger/development/llvm-project/build/libc/test/src/stdio/CMakeFiles/libc.test.src.stdio.fprintf_test.__unit__ 
cd /home/schrodinger/development/llvm-project/build/libc/test/src/stdio && /home/schrodinger/development/llvm-project/build/libc/test/src/stdio/libc.test.src.stdio.fprintf_test.__unit__.__build__
[==========] Running 1 test from 1 test suite.
[ RUN      ] LlvmLibcFPrintfTest.WriteToFile
/home/schrodinger/development/llvm-project/libc/test/src/stdio/fprintf_test.cpp:65: FAILURE
      Expected: printf_test::fread(data, 1, sizeof(simple) - 1, file)
      Which is: 0
To be equal to: sizeof(simple) - 1
      Which is: 37
[  FAILED  ] LlvmLibcFPrintfTest.WriteToFile
Ran 1 tests.  PASS: 0  FAIL: 1
[4184/5229] Linking CXX executable libc/test/src/stdio/libc.test.src.stdio.remove_test.__hermetic__.__build__
ninja: build stopped: subcommand failed.
```

2024-08-03 06:36 UTC, SchrodingerZhu requested changes
See previous comment

2025-08-15 03:14 UTC, pcc commented
can't reproduce this test failure. I did:
```
cmake -G Ninja -DLLVM_ENABLE_RUNTIMES=libc -DLLVM_ENABLE_PROJECTS=clang\;lld -DCMAKE_BUILD_TYPE=RelWithDebInfo -DLLVM_ENABLE_ASSERTIONS=1 -DLLVM_TARGETS_TO_BUILD=AArch64 -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ ../llvm
ninja libc
ninja -C ./runtimes/runtimes-bins check-libc
```
all tests passed.

2025-08-15 04:08 UTC, SchrodingerZhu commented
I will test it again. Thanks for letting me know.On Thu, Aug 14, 2025 at 23:14, Peter Collingbourne ***@***.***&gt; wrote:   Reopened #99260. —
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you are on a team that was mentioned.Message ID: ***@***.***&gt;

2025-09-06 00:58 UTC, pcc commented
> I will test it again. Thanks for letting me know.On Thu, Aug 14, 2025 at 23:14, Peter Collingbourne ***@***.***&gt; wrote: Reopened #99260. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are on a team that was mentioned.Message ID: ***@***.***&gt;

Did you have a chance to do this?

2025-09-06 07:28 UTC, overmighty commented
FYI, ~2 weeks ago I tried to reproduce your benchmark results on Android and I managed to cross-compile the benchmark from `main` and run it, but couldn't get it to compile from this PR's branch.

2025-09-12 21:02 UTC, pcc commented
Ping

> FYI, ~2 weeks ago I tried to reproduce your benchmark results on Android and I managed to cross-compile the benchmark from `main` and run it, but couldn't get it to compile from this PR's branch.

Yeah, you might need to rebase to main, it rebases cleanly here.

2025-10-10 23:48 UTC, pcc commented
Ping

2025-10-13 18:13 UTC, michaelrj-google approved these changes
Looks good to me

2025-10-13 18:21 UTC, merged