[clangd] fix crash in include cleaner
llvm/llvm-project pull request #99514
Opened 2024-07-18 15:27 UTC by yshui

Unsure if this is the correct fix. But let me explain what I know so far about this problem:

1. Include cleaner goes over macro refs, and calculates their source locations:
    https://github.com/llvm/llvm-project/blob/676efd0ffb717215c752f200fe14163732290dcc/clang-tools-extra/clangd/IncludeCleaner.cpp#L303-L305
2. It assumes the macro ref is in the main file. I think the intention is that `ParsedAST::Macros` only contains macro usages in the main file.
3. `ParsedAST::Macros` is filled in by `CollectMainFileMacros`:
    https://github.com/llvm/llvm-project/blob/676efd0ffb717215c752f200fe14163732290dcc/clang-tools-extra/clangd/CollectMacros.cpp#L27-L43
4. `CollectMainFileMacros` checks if the macro usage is in main file with `if (InMainFile)`, and `InMainFile` is updated in `CollectMainFileMacros::FileChange`.
5. I think the intention of `PPCallbacks::FileChange` is that it is called whenever the lexer moves to a new file.

Above is what I am sure about, after that I am not quite sure what's happening. 

I think macro expansions (`HandleIdentifier -> HandleMacroExpansion`) are done out of the normal file change logic? Because I observed `CollectMainFileMacros::add` being calling with source locations that are clearly not in the same file as reported by the most recent `FileChange`.

The consequence of that is that `CollectMainFileMacros` will get offsets related to one file, and those offsets will later be combined with another file (the main file) into a source location in the include cleaner. Those source locations will then be used to get a spelling, which triggers a assertion failure at:

https://github.com/llvm/llvm-project/blob/497ea1d84951626dea5bf644fef2d99e145e21ac/clang/lib/Tooling/Syntax/Tokens.cpp#L382

* * *

What I did here is instead of using `InMainFile`/`PPCallbacks::FileChange` to make sure the macro is in the main file, I check the `FileID` directly

2024-07-18 15:36 UTC, yshui commented
I can provide a repro if anyone is interested

2024-07-18 16:07 UTC, yshui commented
Looks like I definitely don't understand what's going on. Instead let me try a more conservative fix. This should preserve what the current code is doing and just fix the assertion failure.

2024-07-18 21:42 UTC, HighCommander4 commented
Is there a bug report this is fixing? Or a test case?

2024-07-18 22:10 UTC, yshui commented
Good question. I will try to add one once I figure out how this test system works

2024-08-23 05:36 UTC, HighCommander4 commented
> Looks like I definitely don't understand what's going on. Instead let me try a more conservative fix. This should preserve what the current code is doing and just fix the assertion failure.

Could you say more about what problem you ran into with the first fix approach?

2024-08-23 10:50 UTC, yshui commented
@HighCommander4 It's been a while. I think I was trying to ignore everything but the main file in CollectMacros, but the naive approach i used wasn't working

2024-08-26 03:18 UTC, HighCommander4 requested changes
Having debugged the failing scenario a bit (see [this comment](https://github.com/llvm/llvm-project/issues/99617#issuecomment-2309220224)), my sense is that we do not want to accept `MacroRefs` entries which are not in the main file; instead, I have a proposal for an alternative solution at the end of that comment.

Let me know if you're interested in implementing it, otherwise I can do it.

2024-08-26 17:36 UTC, yshui commented
@HighCommander4 thanks for looking into this! I think this can be closed, right?

2024-08-26 17:36 UTC, closed without merging