[libc++] Add missing xlocale.h include on Apple and FreeBSD
llvm/llvm-project pull request #99689
Opened 2024-07-19 19:31 UTC by ldionne

The <locale> header uses strtoll_l and friends which are defined in <xlocale.h> on these platforms. While this works via transitive includes when modules are disabled, this doesn't work anymore if the platforms are modularized properly.

2024-07-19 19:32 UTC, var-const approved these changes

2024-07-19 21:05 UTC, philnik777 requested changes
We should export this from `locale_base_api.h`. That's what the header is for.

2024-07-23 16:53 UTC, ldionne commented
Even with `export *` in `locale_base_api.h`, we are unable to fix this issue from `locale_base_api.h`. I don't know why that is the case, but I would like to merge this patch so as to make libc++ 19 compatible with a modularized SDK while we spend some cycles cleaning up the `<locale>` story in parallel.

2024-07-25 07:00 UTC, philnik777 commented
> Even with `export *` in `locale_base_api.h`, we are unable to fix this issue from `locale_base_api.h`. I don't know why that is the case, but I would like to merge this patch so as to make libc++ 19 compatible with a modularized SDK while we spend some cycles cleaning up the `<locale>` story in parallel.

Could the problem be that we don't actually include the base API in `<locale>`?

2024-07-25 13:13 UTC, ldionne commented
No, I tried that and it doesn't help.

2024-07-25 17:14 UTC, philnik777 approved these changes
OK, in that case let's ship this now and find a proper fix later.

2024-07-25 17:16 UTC, merged

2024-07-25 17:17 UTC, ldionne commented
/cherry-pick a55df237375e98cfc2520d5eb1a23b302ef02ba0