[libc] Fix statvfs test case when SYS_statfs64 is used
llvm/llvm-project pull request #99827
Opened 2024-07-21 22:53 UTC by mikhailramalho

When SYS_statfs64 is used, struct statfs64 is used instead of struct statfs. This patch adds a define to select the appropriate struct, similar to how it's done internally.

This patch also enables fstatvfs and statvfs on riscv, where these are failing to compile without this change.

2024-07-21 23:04 UTC, lntue commented on libc/test/src/sys/statvfs/linux/fstatvfs_test.cpp
> +using statFs = struct statfs64;
nit: `struct`'s are redundant.

2024-07-21 23:33 UTC, SchrodingerZhu requested changes

2024-07-21 23:33 UTC, SchrodingerZhu commented on libc/test/src/sys/statvfs/linux/fstatvfs_test.cpp
> +using statFs = struct statfs64;
using UpperCase for TypeName.

2024-07-22 00:17 UTC, SchrodingerZhu approved these changes

2024-07-22 00:21 UTC, merged