[clang-tidy] fix misc-const-correctness to work with function-try-blocks
llvm/llvm-project pull request #99925
Opened 2024-07-22 19:43 UTC by schenker

Make the clang-tidy check misc-const-correctness work with function-try-blocks.

Fixes #99860.

2024-07-22 19:51 UTC, PiotrZSL commented on clang-tools-extra/docs/ReleaseNotes.rst
> +- Improved :doc:`misc-const-correctness
wrong place, this should be in line 375

2024-07-22 19:51 UTC, PiotrZSL requested changes
Release notes need small fix, except that looks fine

2024-07-22 19:59 UTC, schenker commented on clang-tools-extra/docs/ReleaseNotes.rst
> +- Improved :doc:`misc-const-correctness
done

2024-07-22 20:14 UTC, PiotrZSL approved these changes
LGTM

2024-07-23 02:17 UTC, 5chmidti approved these changes

2024-07-23 06:17 UTC, merged

2024-07-23 06:47 UTC, PiotrZSL commented
Looks like missing -fexceptions

2024-07-23 14:17 UTC, schenker commented
> Looks like missing -fexceptions

thanks for fixing it